### ISSUE TITLE
never ending annoying as F%^k never ending nag to re  re re re re authorize. 

### ISSUE THREAD

**Issue by starvingstudios** [custom-components/alexa_media_player#1000]
never ending nag to re re re re re re authorize and then you get to re authorize again and again and again.

you literally authorize more than you actally use the integration

deleting, uninstalling and never going near this annoying nag ware ever again

**Comment by msauto** [comment]
SERIOUSLY DUDE! DONT USE THE ADDON IF YOU "AINT SMART ENOUGH" !!
"Dumb People Shouldn't have Smart Homes" And wouldn't if not for people like @alandtse !!
Thanks @keatontaylor and @alandtse for all your time and effort as well as everyone else responsible for building and maintaining this addon. Don't let the idiots get you down man. If not for you guys idiots like that guy couldn't even figure out how to spell Home Assistant much less have a smart home. 
Sorry , i know this is closed but had to speak my peace.

**Comment by alandtse** [comment]
@msauto I appreciate the support but I do want to keep the repo respectful so I will lock the thread and also hide your comment.
