### ISSUE TITLE
Leave voice message (green ring) possible?

### ISSUE THREAD

**Issue by dinki** [custom-components/alexa_media_player#1001]
My kids have chores that alternate between them and on different days.  I have HA automations for these and it sends me a Telegram message letting me know who is assigned for a chore for that day.  I'd like to use the Alexa message functionality to leave a message on each kid's echo dot when it is their day to do a chore.  Does anyone know how to get HA to send a message to a specific echo dot?

Here's a page that describes this functionality:
https://www.androidcentral.com/how-send-voice-message-amazon-alexa

from it:

> When you have a message waiting to be heard, you will be notified in two ways. If you have an Amazon Echo, a green ring around your notification light will let you know a message is waiting. On your phone, the Alexa app will prompt you with an incoming message notification. Both options will allow you to hear the message and reply, but the app will allow you to read the message without audio.

All the best to you!

**Comment by alandtse** [comment]
Are you looking to record your voice or just text to speech?

**Comment by dinki** [comment]
> Are you looking to record your voice or just text to speech?

Text-to-speech.  I want to automate this through Home Assistant so that would be the only way I would call it.  I went through the process on the phone and it goes like this:

Communications -> New Message -> Select Contact -> Type message ->  Send

**Comment by alandtse** [comment]
We'll need to sniff the packets from the app to figure this out since it isn't in the webapp directly. I'm also not sure how we can get a list of contacts as it's probably tied to some user id.

**Comment by dinki** [comment]
Cool.  I'm up for testing. Can you point me at a how to on how to sniff the packets?

**Comment by alandtse** [comment]
It's a bit involved to be honest but generally the steps are:

1. Setup a [virtual android device in a VM](https://developer.android.com/studio/run/emulator). You'll likely need an older version of Android so you can change the SSL certs in the next step. You could use your raw phone but it'll reduce the network traffic to review using an emulated phone.
2. Setup a [man in the middle proxy](https://mitmproxy.org/) to capture any communications from the android device.
3. Install the Alexa app on the device.
4. Run the steps you want to emulate and capture the logs from mitmproxy.
5. Provide the logs (you may have to scrub some of the data like userids, serialnumbers, etc.) or if you can figure out the API, help document it on the [wiki](https://github.com/custom-components/alexa_media_player/wiki/Developers%3A-Known-Endpoints).

Here's another [article](https://medium.com/testvagrant/intercept-ios-android-network-calls-using-mitmproxy-4d3c94831f62) on how to do it. If you search generally for `mitmproxy android` there's other guides.

**Comment by alandtse** [comment]
Do you know if this can be done via voice? If so, [custom commands](https://github.com/custom-components/alexa_media_player/wiki#run-custom-command) should be able to do it now.
