### ISSUE TITLE
Adding 2nd Amazon account does not work, replaces first

### ISSUE THREAD

**Issue by DPAmes** [custom-components/alexa_media_player#1002]
Based on the configuration guide that says you can add a 2nd Amazon account, I tried that. It works, but all the Echo devices from the first account become Unavailable, while those from the 2nd account appear. Removing the 2nd account and restarting restores the Echo devices from the first Amazon account.

**Comment by alandtse** [comment]
Please fill out the bug template as it has basic questions I'd need to help.
