### ISSUE TITLE
2 Factor Authentication - Captcha not supported by Amazon.in.   

### ISSUE THREAD

**Issue by AshokBaijal** [custom-components/alexa_media_player#1004]
I am from India. My Alexa devices are connected to Amazon.in (Site in India). Captcha is not supported by Amazon in India. Instead it allows for an OTP while logging in. OTP does not work while configuring the Alexa Media player. If I re-register my Alexa devices on Amazon.com, the music files in local language are not available on US sites.

I changed settings in Amazon.in to revert to single factor authentication. I was able to configure the media player without the second factor. Is this OK?

**Comment by alandtse** [comment]
There is no support if you don't have 2FA.
