### ISSUE TITLE
[v3.2.3] Empty device created after upgrade

### ISSUE THREAD

**Issue by chemelli74** [custom-components/alexa_media_player#1011]
**Describe the bug**
Upgrading from 3.2.2 to 3.2.3 create an empty device

**To Reproduce**
1. Install 3.2.2
2. Check devices
3. Upgrade to 3.2.3
4. Recheck devices

**Expected behavior**
No phantom device created

**Screenshots**

![image](https://user-images.githubusercontent.com/57354320/99884366-13f6ef00-2c2e-11eb-8140-f31de687da1e.png)

![image](https://user-images.githubusercontent.com/57354320/99884372-19543980-2c2e-11eb-8b8c-1ff6475150af.png)

**System details**
 - Home-assistant (version): 0.118.0
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): 3.2.3
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: Yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by alandtse** [comment]
3.2.3 didn't change any code that would've made an entity. Please provide debug logs of your startup if you want me to debug this as I don't see this behavior in my systems.

**Comment by chemelli74** [comment]
So I may have missed it before :-(

Anyway, if a device has no entities should be automatically removed.
Do you agree ?

Simone

**Comment by chemelli74** [comment]
@alandtse, can you please consider doing a cleanuip of state devices at init ?

Thx in advance,

Simone

**Comment by chemelli74** [comment]
Dirty workaround was to remove integration, delete all devices and add it back.

Simone
