### ISSUE TITLE
Links in HACS info page not clickable

### ISSUE THREAD

**Issue by Brianfit** [custom-components/alexa_media_player#1012]
**Describe the bug**
After installing in HACS, none of the "useful links" in the three dot "Information" menu work:

`General documentation

Installation and Configuration

FAQ

Repository

Forum post`

**To Reproduce**
1. Go to '.Three Dot menu in HASSIO'
2. Click on '.Information'
3. Scroll down to 'Useful Links'
4. See error 'Not so useful -- they don't work!'

**Expected behavior**
Browser takes you to useful links

**Screenshots**

**System details**
 - Home-assistant (version): 0.118.0
 - Hassio (Yes/No):  Yes

**Comment by alandtse** [comment]
I think this is a HACS issue. It's just loading this page, where the links all work. https://github.com/custom-components/alexa_media_player/blob/dev/info.md.

You can see the same problem if you open the HACS information page. Please report this to HACS and reference this if you want.

**Comment by alandtse** [comment]
HACS will fix this in 1.8.0b per https://github.com/hacs/integration/issues/1618
