### ISSUE TITLE
NotADirectoryError: [Errno 20] Not a directory: '/config/custom_components/alexa_media/translations/en.json'

### ISSUE THREAD

**Issue by Knot83** [custom-components/alexa_media_player#1013]
2020-11-23 21:29:08 ERROR (SyncWorker_4) [homeassistant.util.json] JSON file reading failed: /config/custom_components/alexa_media/translations/en.json
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 31, in load_json
    with open(filename, encoding="utf-8") as fdesc:
NotADirectoryError: [Errno 20] Not a directory: '/config/custom_components/alexa_media/translations/en.json'

**Comment by alandtse** [comment]
Please fill out the template as it has information I need such as version.

**Comment by Knot83** [comment]
Release 3.2.3
I did the manual installation adding the alexa_media folder from git under custom_components and got the above error in the log file. I was then able to install it from Hacs correctly. The difference i see is that the Git package has only the .translate subfolder while instead Hacs installed either .translate and traslate subfolders

**Comment by alandtse** [comment]
You should use the HACS install as the manual install isn't supported. I guess no one updated the manual install instructions to mention creating both directories (they exist in the repo). The release zip file includes both directories so if you unzipped that file it would've had everything.

Anyway, glad you got it installed with HACS.
