### ISSUE TITLE
Alarm Dismissed

### ISSUE THREAD

**Issue by broyuken** [custom-components/alexa_media_player#1014]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**

I would like to be able to trigger an automation when an alarm is dismissed. Now it is possible to do with a template to see when an alarm would go off, but if the alarm is snoozed it will not know. One of the routine triggers is alarm dismissed, I would like to have a button or event fired off when an alarm is actually shut off, not just snoozed.

**Comment by alandtse** [comment]
This may be doable although it's a question of how we can tell the difference between an alarm that is being dismissed after it goes off vs cancelled. I guess we could assume any cancellations around the scheduled time are dismissal but then we have to consider recurring alarms.

**Comment by alandtse** [comment]
Check out if https://github.com/custom-components/alexa_media_player/wiki#run-custom-command allows this now.

**Comment by alandtse** [comment]
Oops sorry, my last suggestion isn't right. You're looking for an event. Please ignore my response..

**Comment by broyuken** [comment]
No worries

**Comment by keatontaylor** [comment]
So I do something very similar in my personal setup. It takes a bit of a different approach. Basically if you already have lights and other devices controlled via voice from Alexa to home assistant. "Alexa, turn off the kitchen lights" via the Home Assistant smart home skill you can create a new input_boolean in home assistant and have the "Alarm Dismissed" routine action flip the input_boolean to on.

**Comment by broyuken** [comment]
Yea that’s exactly what I ended up doing, except instead of just a Boolean I made a virtual button so it gets flipped back to off after a second. That way I don’t need any routine or anything to reset it every day

**Comment by broyuken** [comment]
thank you for removing the label

**Comment by blm126** [comment]
So, my quest to completely abandon Alexa routines for HA automations continues and I now want this feature.  I figured out how to consistently detect dismissals and have this [implemented](https://github.com/blm126/alexa_media_player/commit/b19f7add7325275948f85e1338ca9d1fcc2badee).  

I did take a slightly different approach. Instead of sending an event, I added a "dismissed" attribute to the sensor. The attribute updates to the datetime of the last alarm dismissal. Then, I just trigger automations on any change to that attribute.

It wouldn't be all that hard to add an event as well, but I'm not sure I see the need. Is there some advantage to an event that I'm not aware of?

**Comment by alandtse** [comment]
Did you successfully disambiguate cancellations vs dismissals vs snoozes? That was one of the hard parts with this request.

Most people are used to events. Since we already started adding events this seems like something people will still want regardless of any other templates.

**Comment by blm126** [comment]
Yep, I think I have all the cases handled. The biggest trick I discovered was the "version" field on alarms. It behaves in a consistently strange but useful way. Dismissing or snoozing an alarm always increments it by 1. Editing/Disabling an alarm either via voice or the app always causes the version to increment by 2+. You can use that plus status to understand when a dismissal happens.

I'll throw in an event if you think that is what people will look for.

**Comment by alandtse** [comment]
@blm126 Thanks btw for all your recent work. I plan to do a release this weekend (to fix some stuff) so let me know if you think you'll have any updates to merge and I can wait for them.
