### ISSUE TITLE
Echo Show set image changes clock

### ISSUE THREAD

**Issue by dinki** [custom-components/alexa_media_player#1016]
Hi.  First off, thanks for this fantastic component.  We've been in a Google Mini world for a long while now and have just transitioned over to the Echo world.  This component has made the transition very smooth as we use a fair amount of voice notification automations.

I recently purchased an Echo Show and am wanting to use it to set different backgrounds with visual notifications of which kid has to do which chore on days they have things to do.  I've successfully managed to set an image, but it seems that the clock defaults to the small clock in the upper left corner instead of the much larger clock we were using.  Is there any way to choose the clock type when setting the background image?  If not, is that something that could be added?

All the best to you!

**Comment by alandtse** [comment]
Thanks. Glad it's been helpful for you. We're reliant on what the Amazon app can do as we're just emulating the functionality. I don't think it currently allows that setting when changing the background image but if you find it, we may be able to add that.

**Comment by dinki** [comment]
Ah, okay.  Just dug around and can't see any way to do it from the app.  Maybe someday :(  Thanks again.
