### ISSUE TITLE
TTS stopped working with latest update 3.3.0

### ISSUE THREAD

**Issue by BuxtonCalvin** [custom-components/alexa_media_player#1024]
**Describe the bug**
TTS stopped working and an error message is broadcast over all Alexa devices

**To Reproduce**

Fill in a test TTS on "Text to Speak" field in Lovelace card.  Press enter.

**Expected behavior**
TTS to broadcast on Alexa device.  Instead an error message is annunciated: 

"Sorry, text to speech can only be called with the notify.alexa_media service. Please see the alexa_media wiki for details"

**System details**
 - Home-assistant (version): docker standard

 - alexa_media  (version from `const.py` or HA startup): 3.3.0

 - alexapy (version from `pip show alexapy` or HA startup): unknown

 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered:  Y

**Logs**

Logger: custom_components.alexa_media.media_player
Source: custom_components/alexa_media/media_player.py:1154
Integration: Alexa Media Player (documentation, issues)
First occurred: 2:55:07 PM (1 occurrences)
Last logged: 2:55:07 PM

Sorry, text to speech can only be called with the notify.alexa_media service. Please see the alexa_media wiki for details.https://github.com/custom-components/alexa_media_player/wiki/Configuration%3A-Notification-Component#use-the-notifyalexa_media-service

**Additional context**

**Comment by Jelmerrevers** [comment]
Having the same issue, also happens with sending radio information to the Alexa device.

**Comment by alandtse** [comment]
It has never worked with the lovelace card as it doesn't do TTS the way other devices do with HA. The error message is what is required to run it. Please review the page if you want TTS.
