### ISSUE TITLE
Unknown error: 'otp_secret' Unknown error: Non-base32 digit found

### ISSUE THREAD

**Issue by nonome1** [custom-components/alexa_media_player#1025]
Logger: custom_components.alexa_media.config_flow
Source: custom_components/alexa_media/config_flow.py:232
Integration: Alexa Media Player (documentation, issues)
First occurred: 20:59:04 (17 occurrences)
Last logged: 21:48:23

Unknown error: 'otp_secret'
Unknown error: Non-base32 digit found

![image](https://user-images.githubusercontent.com/55211261/100525911-52f3ea00-31c4-11eb-8422-dc3189daff75.png)

System Health

Home Assistant Core Integration

version: 0.118.2
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
virtualenv: false
python_version: 3.8.6
os_name: Linux
os_version: 4.19.127-v7
arch: armv7l
timezone: Europe/Paris

Home Assistant Cloud

logged_in: true
subscription_expiration: 1 janvier 2018 à 1:00
relayer_connected: false
remote_enabled: false
remote_connected: false
alexa_enabled: true
google_enabled: true
can_reach_cert_server: ok
can_reach_cloud_auth: ok
can_reach_cloud: ok

Hass.io

host_os: HassOS 4.17
update_channel: beta
supervisor_version: 2020.11.4
docker_version: 19.03.12
disk_total: 6.6 GB
disk_used: 5.9 GB
healthy: true
supported: true
board: rpi3
supervisor_api: ok
version_api: ok
installed_addons: File editor (5.2.0), Samba share (9.3.0), Check Home Assistant configuration (3.6.0), Duck DNS (1.12.4), ESPHome (1.15.3), Grafana (5.3.5), InfluxDB (3.7.9), MQTT Server & Web client (1.2.0), Mosquitto broker (5.1), Node-RED (7.2.8), Spotify Connect (0.8.2), TasmoAdmin (0.13.1), Terminal & SSH (8.9.1)

Lovelace

dashboards: 1
mode: storage
views: 2
resources: 7

**Comment by alandtse** [comment]
Please fill out the template properly.

**Comment by Jordan-Work** [comment]
also getting this error `Unknown error: 'otp_secret'`

**Comment by fmmsfz** [comment]
The same here!
