### ISSUE TITLE
Integration fails to load - IndexError: string index out of range in hide_serial

### ISSUE THREAD

**Issue by mikesalz** [custom-components/alexa_media_player#1033]
**Describe the bug**
Integration stopped loading a day or so ago

**To Reproduce**
1. Restart HA

**Expected behavior**
Integration should load

**Screenshots**

**System details**
 - Home-assistant (version): Home Assistant 0.118.5
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): __version__ = "3.3.1" (Also tried 4.0)
 - alexapy (version from `pip show alexapy` or HA startup): 1.16.0
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: Yes

**Logs**
Logger: homeassistant.config_entries
Source: custom_components/alexa_media/__init__.py:1062
First occurred: 7:53:03 AM (1 occurrences)
Last logged: 7:53:03 AM

Error setting up entry xxxxxxx@gmail.com - amazon.com for alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/alexa_media/__init__.py", line 261, in async_setup_entry
    if await test_login_status(hass, config_entry, login):
  File "/config/custom_components/alexa_media/__init__.py", line 1062, in test_login_status
    _LOGGER.debug("Logging in: %s %s", obfuscate(account), in_progess_instances(hass))
  File "/usr/local/lib/python3.8/site-packages/alexapy/helpers.py", line 103, in obfuscate
    response[key] = hide_serial(value)
  File "/usr/local/lib/python3.8/site-packages/alexapy/helpers.py", line 69, in hide_serial
    response = "{}{}{}".format(item[0], "*" * (len(item) - 4), item[-3:])
IndexError: string index out of range

**Additional context**
This MIGHT have started failing when I upgraded from Home Assistant 0.118.4 to 0.118.5, but I am unsure if that is related.

**Comment by disforw** [comment]
Same issue here

**Comment by alandtse** [comment]
Did you get a new Alexa decide recently? It's failing because it has a serial number that appears to be too short.

**Comment by mikesalz** [comment]
@alandtse Thanks for responding.  No, I have not added any new Alexa devices.  The only change I have made recently that I am aware of was disabling the new Amazon Sidewalk setting.  I doubt that had any impact on this integration, but just throwing it out there.

**Comment by disforw** [comment]
I have not added anything recently (except the Vizio Smartcast skill?) and I did not change the sidewalk setting yet.

**Comment by disforw** [comment]
Fixed: I deleted and re-added the integration. No reboot required. I did happen to notice before removal that I had 2 devices named “This Device”, after readd, only 1.

**Comment by alandtse** [comment]
This Device is caused by having an Amazon app recently active. It's possible the faulty serial number is coming from there.

**Comment by mikesalz** [comment]
Removing and reinstalling fixed it for me as well.  Thanks for the suggestion, @disforw !  @alandtse Is it possible to permanently screen out "This Device" so this doesn't happen again in the future?

**Comment by alandtse** [comment]
This Device may be a device people will want. You can exclude it using the existing features. I'll address the actual error though in the next release. We just haven't had a serial this short before.

**Comment by mikesalz** [comment]
So, Amazon decided I needed to re-enter my credentials for the integration to work.  When I did, I got the same error again.  I guess I need to uninstall and reinstall.  Looking forward to the fix in the next release!!

**Comment by alandtse** [comment]
If you can't get in, you can manually replace this [file](https://gitlab.com/keatontaylor/alexapy/-/blob/dev/alexapy/helpers.py) for alexapy and it will resolve it.
