### ISSUE TITLE
Clarifying best practices for configuration and Excluding devices

### ISSUE THREAD

**Issue by genem2** [custom-components/alexa_media_player#1035]
At this time (v3.4.0), I'm adopting the [cookie approach](https://github.com/custom-components/alexa_media_player/wiki/Configuration#cookie-import), and have stored my cookie info in /config/.storage/alexa_media.{account}.txt.   Works great; I'm just hoping they don't expire it as frequently as Google Maps does!
(If they do, I assume my last alternative is to leverage the 2FA App approach.)

Anyway, regarding Exclusions: ([doc on Advanced Configuration](https://github.com/custom-components/alexa_media_player/wiki/Configuration#advanced-configuration))

It appears the alexa_media: exclude_devices: list I've always had in my configuration.yaml file is no longer affecting anything. 
Maybe configuring this via the HA Integration depreciating exclude_devices: options?

Regardless: during my Integration-add, I excluded the 11 devices of interest _(155 characters - so I'm hoping I don't need to enter string every time!)_, but then I have 36 'unavailable' switches (repeat/shuffle/DNDs) and sensors (next_alarm, next_reminder, next_timer) that I don't want visible in HA _(so templating loops, etc, are not tripped up by entities I don't care about)_.

Is there a better approach to manually disabling them each time the Integration needs to be cycled? Unless HA offers a better way, the hunt-and-click for all these on the Entitles Config screen is getting old.

**Comment by alandtse** [comment]
Exclude_devices is the only way and only superficially supported. Given HA wanted to move to UI based editing, I am unlikely to make significant investments in supporting it further. Please note you can also exclude the additional switches using the same interface.

I recognize the config flow is more cumbersome then the configuration.yaml, but my suggestion would be to save the string you use in the config flow somewhere so you can just paste it if you need to remove and readd.

Lastly, configuration.yaml should automatically update the existing config flow entry on start up. If you're saying it's not doing that, that may be a bug, but I'd need to see the startup logs.

**Comment by genem2** [comment]
Again, tonight, they dropped me I guess and I had to remake the cookie files. I was surprised to see my previous pickle file was no longer in .storage.   This Amazon stuff is really getting old.

> configuration.yaml should automatically update the existing _config flow entry_ on start up

I'm not sure what you mean by config flow entry. I re-added the integration, restarted HA, but still had the Excluded devices from the configuration.yaml file.

BTW: Someone's bound to mention this: after screwing up with the captchas long enough, things finally give up with an abort error, but the screen also says successful:
![AbortError](https://user-images.githubusercontent.com/46231389/101722530-493d7280-3a5f-11eb-9e05-2137b819b0ac.png)

**Comment by alandtse** [comment]
The .pickle is automatically deleted if a failure is detected. Yes, I wish Amazon was less fincky.

The integration page is also known as config flow. If you have the yaml entry, it will automatically create the integration for you on startup. If it already exists, it's supposed to update it.

The abort screen is a HA problem. I've raised it since it's so confusing but so far this is the approved mechanism.

**Comment by genem2** [comment]
Once again, thank you for your time on this. 

I just migrated to using your [Built-in 2FA App](https://github.com/custom-components/alexa_media_player/wiki/Configuration#built-in-2fa-app). I'm hoping it's easier to paste in strings for that code and my exclude devices, rather than having to screw around with their captchas and the authenticator app. Time will tell.
