### ISSUE TITLE
Login bug even with 2FA

### ISSUE THREAD

**Issue by thuantrinh** [custom-components/alexa_media_player#1046]
Bug:
1. On the Integration page, i enter the email, password, 2FA code correctly
2. Another dialog open asking me to enter password again, now with CAPTCHA. Theres already a 2FA field but its already filled out
3. When I click on Submit, it keep saying password is incorrect

Workaround:
On the integration, enter everything without the 2FA code
Once i get past this page, it will prompt me to enter the 2FA code only (unlike step 2 above)

**Comment by alandtse** [comment]
Please use the bug template if you'd like help.

**Comment by jjmwiwi** [comment]
iSame Problem here. Even after a fresh installation of hass io: Impossible to authenticate. 

Region: amazon.de
2FA code: doesn't work with or without

**Comment by jjmwiwi** [comment]
Hey
where Do I find the bug template?

**Comment by alandtse** [comment]
https://github.com/custom-components/alexa_media_player/issues/new/choose

**Comment by grewhit25** [comment]
I had the same or similar problem here; I found it was related to how the cookie.txt content was pasted in. I need to enter a  ‘space’ before pasting cookie.txt content; because it seems that this content is pre-pended with a comment after submission that crashed into the cookie text.

**Comment by alandtse** [comment]
Probably fixed in 3.4.2 but no idea since I don't have enough info here to know.
::shrug::
