### ISSUE TITLE
Pre-saved cookies don't work

### ISSUE THREAD

**Issue by tomjmul** [custom-components/alexa_media_player#1047]
I followed the instructions to export my cookies from the Alexa web app while logged in and save them to .storeage/alexa_media.my@email.com.txt, but it doesn't seem to work. Upon installing (or re-installing) the integration, the file is deleted and I am not logged in. I have verified the cookies are correct.

**Comment by alandtse** [comment]
Please fill out the template and provide logs.

**Comment by alandtse** [comment]
Closed due to lack of info. Also, cookie import it going to be deprecated soon so don't use it.
