### ISSUE TITLE
[Discussion] Make alexa_media a core integration

### ISSUE THREAD

**Issue by phrfpeixoto** [custom-components/alexa_media_player#1048]
Hi,

This is very well known custom integration for HA works GREAT, and it has been features on several video/live streams on major platforms, so why not make this a core integration for Home Assistant?

Has this ever been discussed within the maintainers? Has this ever been discussed with HA's core team?

Having it as part of the core will help get por people using it, grow the platform, and who knows, maybe even get Amazon's attention for documenting local APIs.

**Comment by alandtse** [comment]
We use webscraping for the logon which is prohibited by HA so we'd have to remove the login logic. Also, I don't want to go through the effort of getting HA to approve this integration. It's too big and would require a major rewrite. That said, if someone wants to do the legwork, I'm not opposed.
