### ISSUE TITLE
Unable to configure the plugin

### ISSUE THREAD

**Issue by Cosby86** [custom-components/alexa_media_player#1050]
**Describe the bug**
Hello all, I correctly installed the plugin but after received the link to validate on mobile phone (from amazon) and correctly validated it the plugin remains on "Alexa Media Player - Action required" form. If I press SUBMIT nothing occurs. in homeassistant logs I don't have anything.

**To Reproduce**
1. Entered on configuration page email, password (I tried with or without 2FA code)
2. Next form asked me to enter captcha
3. Entered the correct captcha i receive on my mobile phone the link to grant the access to the amazon account (I granted it correctly)
4. I come back on HomeAssistant page and press SUBMIT on "ACTION REQUIRED" popup
5. Nothing occurs. The submit button shows the loading circle and after few seconds it comes back to SUBMIT button
6. Nothing on logs (even with debug logs enabled)

**Expected behavior**
To show the next page

**Comment by alandtse** [comment]
Please fill the entire template.

**Comment by Cosby86** [comment]
I filled out all the information I have :(

**Comment by geoffrothman** [comment]
I've had this exact same issue the past 2 days :(

**Comment by alandtse** [comment]
You only get that page if you failed to [enable 2FA](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account). 2FA is required for any support.
