### ISSUE TITLE
Missing from Home Assistant Community Add-ons?

### ISSUE THREAD

**Issue by securityguy** [custom-components/alexa_media_player#1054]
I'm running the latest hassio on a pi4. I can't find Alexa Media Player in HACS. Is there an alternative store URL I can add?

It would be great to have this info in the wiki for people trying to install.

Thanks!

**Comment by alandtse** [comment]
No, it's there by default.

**Comment by securityguy** [comment]
I installed the latest Raspberry Pi image from https://www.home-assistant.io/hassio/installation/ and it does not appear. Searching for "Alexa" results in:

No results found in "Official add-ons."

No results found in "Home Assistant Community Add-ons."

It appears to be using https://addons.community if that helps.

**Comment by alandtse** [comment]
That is not HACS. https://hacs.xyz/

**Comment by alandtse** [comment]
It's a little confusing but HACS is for integrations and other things you can use regardless if you use Hassio. What you were searching is the add-ons for Hassio which is something else.
