### ISSUE TITLE
Old devices don't go away

### ISSUE THREAD

**Issue by jl0810** [custom-components/alexa_media_player#1056]
I recently moved my amazon devices to a new amazon account. Deleted this integration and re enabled with new account.  Old non-amazon devices (mainly Sonos speakers) still there and can't be deleted without deleting the integration. Note that I've tripled checked that Sonos is NOT enabled in my Amazon Alexa profile so I'm assuming this integration has just "remembered" the old devices (maybe in cache) and has not deleted them

**Comment by alandtse** [comment]
Remove unused entities through home assistant per HA standard practice.
