### ISSUE TITLE
TTS - No sound

### ISSUE THREAD

**Issue by Larnak23** [custom-components/alexa_media_player#1058]
Hello

I have installed the plugin without any difficulties and fount all my echos in my integrations.

Unfortunately, when I tried to use TTS through development / services with 

message: Le chat est entre
data:
  type: tts
target: media_player.echojeux

no sound appear in the echo ?

Any idea ?

**Comment by alandtse** [comment]
Please use the bug template.

**Comment by alandtse** [comment]
You're probably in the wrong domain.
