### ISSUE TITLE
notify.alexa_media is not working from Dev Tools, services

### ISSUE THREAD

**Issue by danielbrunt57** [custom-components/alexa_media_player#1059]
**Describe the bug**
`notify.alexa_media` is not working in Dev Tools, Services
`notify.alexa_media.echo_dot` does work.

**To Reproduce**
```
service: notify.alexa_media
target: '{{ states.sensor.last_alexa.state }}'
message: Test
data:
  type: tts
```

**Expected behavior**
Alexa Echo Dot should speak...

**Screenshots**
![image](https://user-images.githubusercontent.com/49846893/103335143-f1c07000-4a28-11eb-9cb7-2870697e543f.png)

![image](https://user-images.githubusercontent.com/49846893/103335168-10266b80-4a29-11eb-832b-63c1753bb6c9.png)

**System details**
 - Home-assistant (version): 2020.12.7
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): __version__ = "3.4.1"
 - alexapy (version from `pip show alexapy` or HA startup): Version: 1.17.2
 - Amazon [2FA is enabled] Yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**
Am I doing something wrong or is this not supported by HA?

**Comment by alandtse** [comment]
HA does not support templates in the dev tools last I checked. Regardless, that's an HA bug if templates don't work in dev tools.
