### ISSUE TITLE
power button bug

### ISSUE THREAD

**Issue by tirlip2020** [custom-components/alexa_media_player#1060]
hello
 after press pause alexa go to standby mode and vea alexa media player cant wake up as power button still shows power off in dev tools try call service media player on alexa wake up from standby mode. how to fix power button to trigger power on

**Comment by alandtse** [comment]
Please use the bug template.

**Comment by alandtse** [comment]
Power button doesn't do anything as there isn't a programatic way to turn on an Alexa device.
