### ISSUE TITLE
Stuck at "Required action"

### ISSUE THREAD

**Issue by JohannCR** [custom-components/alexa_media_player#1066]
Hi,

I've added 2FA App Key and confirmed the OTP code, but the integration is stuck at "Action required - Amazon will send a push notification"... No such notification received... What can I do ?
Thanks !

**Comment by cylonr** [comment]
I´ve the same problem too!
![Capturar](https://user-images.githubusercontent.com/34467765/103417182-8dfd8a80-4b81-11eb-97f5-530beaf8ba08.JPG)

**Comment by kolossboss** [comment]
same for me

**Comment by giuseppe0921** [comment]
I also have the same problem, I can't solve it in any way unfortunately.

**Comment by alandtse** [comment]
Enable 2FA. There is no support if you don't.

**Comment by kolossboss** [comment]
2FA is enabled via SMS Code and Auth app. Works for a few month now. But today I get this message. And nothing happened. To mail or field to input auth code.


```
Xxxx@xxxx.de - alexa.amazon.de
Amazon sendet eine Push-Benachrichtigung je folgender Nachricht. Bitte antworte sie vollständig, bevor Du fortfährst
```.

**Comment by JohannCR** [comment]
2FA is enabled for me too, so this isn't the problem ^^

**Comment by kolossboss** [comment]
Its working again with 3.4.4. Thanks al lot.

**Comment by poudenes** [comment]
After upgrade to 3.4.4 many users have problems see post:
https://github.com/custom-components/alexa_media_player/issues/1075

**Comment by yadavvineet** [comment]
2fa enabled, even then not working. stuck at this page
![image](https://user-images.githubusercontent.com/7949851/103445955-2853f000-4ca0-11eb-8b7f-6a6b5f0b93ad.png)
