### ISSUE TITLE
Unable to authenticate after first app installation 

### ISSUE THREAD

**Issue by alexanderfitu** [custom-components/alexa_media_player#1067]
**Describe the bug**
Unable to authenticate after installing the integration. 

I successfully fill in the 2fa screen, with the correct information (as per the wiki) but, I then receive a message that says:

![image](https://user-images.githubusercontent.com/3074998/103425483-80a8c600-4baa-11eb-98dc-c21b82b608af.png)

I never receive an Otp message, or notification on the web page, alexa app, amazon app, or SMS message. 

If I chose amazon.com as the auth domain, I can authenticate, but all the alexa devices created in HA show as unavailable with a red ! on them. 

**To Reproduce**
1. Install the integration via HASS
2. restart HA
3. add the integration 
4. configure the integration as per current instructions. 

**System details**
 - Home-assistant (latest version 2020.12.2): 
 - Hassio (no
 - alexa_media  (3.4.2 via HACS):
 - alexapy (not sure ):
 - Amazon [2FA is enabled] yes - Have tried via OTP or via SMS as primary source. 

**Logs**
`attached
[logs.txt](https://github.com/custom-components/alexa_media_player/files/5758259/logs.txt)

**Comment by alandtse** [comment]
I've confirmed. If you're seeing this use 3.4.1 until we release a fix. Apparently oauth may not work across all domains.
