### ISSUE TITLE
Password incorrect

### ISSUE THREAD

**Issue by BeBsCh** [custom-components/alexa_media_player#1071]
Hello,

today i updated on the latest version, 3.4.3, After Reboot notify.alexa were removed. I deinstalled Alexa Media Player, did a Reboot and made a new installation. Now it says "Password wrong". I changed the Password but it won't work.
Also Alexa Media doesn't send me 2-Factor-Codes for a long time. I'm using another Browser to let me send a 2-Factor-Code for Login in on Home Assistant.
But acutally it says "Password wrong"

**Comment by alandtse** [comment]
Type in the correct password. If it's in your configuration.yaml you need to change it too. We're sending you the message from Amazon.
