### ISSUE TITLE
TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by Pirol62** [custom-components/alexa_media_player#1072]
**Describe the bug**
Already updated to 3.4.3.
The entities were created but inactive

**System details**
 - Home-assistant (version): 2020.12.2
 - Hassio (Yes/No): yes
 - alexa_media  (version from `const.py` or HA startup): 3.4.3
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: 

**Logs**
````
Logger: homeassistant.config_entries
Source: custom_components/alexa_media/__init__.py:267
First occurred: 11:11:12 (1 occurrences)
Last logged: 11:11:12

Error setting up entry post@joerg-nauen.de - amazon.de for alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/alexa_media/__init__.py", line 267, in async_setup_entry
    await login.login(cookies=await login.load_cookie())
  File "/usr/local/lib/python3.8/site-packages/alexapy/helpers.py", line 141, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/alexapy/alexalogin.py", line 577, in login
    missing_params = self._populate_data(site, data)
  File "/usr/local/lib/python3.8/site-packages/alexapy/alexalogin.py", line 1251, in _populate_data
    self._password + securitycode
TypeError: can only concatenate str (not "NoneType") to str
````
**Additional context**
I tried to rollback to 3.4.2
The I have the bug handled in #1067

Went back to 3.4.1 - authentication worked and everything is fine so far.

By the way: does "Add oauth token refresh" mean, that we do not have to reauthenticate manually in future?
Is that the function which is used by this node red integration?

**Comment by alandtse** [comment]
I can't control Amazon but it's using oauth to log in like the app. Please provide logs leading up to this point so I know how you got here.

**Comment by Pirol62** [comment]
Hi, as my family visited us, I'm not flexible today🙄. Will deliver later.
But anyway: how to provide more logs when the error reported above is the result from a HA restart? 
Shall I activate debug mode, update media player and then restart?

**Comment by herveaurel** [comment]
Same problem 😢
Logger: homeassistant.components.alexa.state_report
Source: components/alexa/state_report.py:104 
Integration: Amazon Alexa (documentation, issues) 
First occurred: 11:06:05 (1 occurrences) 
Last logged: 11:06:05

Timeout sending report to Alexa

**Comment by alandtse** [comment]
@Pirol62 I may have a quick solution shortly.
@herveaurel the logs aren't for this component. You're providing logs for the official component.

**Comment by herveaurel** [comment]
> @ Pirol62 J'aurai peut-être une solution rapide sous peu. 
> @herveaurel les journaux ne sont pas pour ce composant. Vous fournissez des journaux pour le composant officiel.

yes I saw ! 😂 Sorry, it's difficult on January 1st!  And happy New Year !  (where are the logs?)

**Comment by herveaurel** [comment]
a fix will come?

**Comment by Pirol62** [comment]
@alandtse if you read that.
We had partly success.
Tried 3.4.4. again
No error log but I have to enter the captcha 5 Times. Then a message appears:
Translation:
“The ‘amazon forgotten password function’ detected. Amazon might need action before a new authentication can be started”
Rolled back to 3.4.1 - authentication works - everythings fine so far.

**Comment by herveaurel** [comment]
> @alandtse si vous lisez cela. 
> Nous avons eu en partie un succès. 
> Essayé 3.4.4. à nouveau 
> Pas de journal des erreurs mais je dois entrer le captcha 5 fois. Puis un message apparaît: 
> Traduction: 
> «La 'fonction de mot de passe oublié amazon' a été détectée. Amazon peut avoir besoin d'une action avant qu'une nouvelle authentification puisse être lancée » 
> J'ai essayé deux fois depuis un mobile et un PC. 
> Il semble que le captcha ne soit pas accepté par la fonction d'authentification.
> 
> Retour à 3.4.1 - la réauthentification a fonctionné - tout va bien jusqu'à présent.

Same problem with captcha. :(
