### ISSUE TITLE
Alexa media player addon is blank

### ISSUE THREAD

**Issue by womp666** [custom-components/alexa_media_player#1076]
latest HA and latest alexa_media_player when adding have no test except amazon.com and 60, a second smaller popup looks like it has 3 lines with a password on the first line. downloading the zip file and coping to the custom component folder. tried new clean installs and adding this first and still the same thing.

**Comment by alandtse** [comment]
Use the template please. I also don't understand what you're saying.

**Comment by womp666** [comment]
**Describe the bug**
When trying to add the Alexa Media Player intigration all lines are blank, no discription on the lines except "amazon.com and 60"

**To Reproduce**
Steps to reproduce the behavior:
1. Go to 'configuration, integrations'
2. Click on 'add integration'
3. Scroll down to 'Alexa Media Player'
4. pop up has no discriptions except "amazon.com and 60"

**Expected behavior**
I know the top line should say username or email and the second line should say password

**Screenshots**
1 added

**System details**
 - Home-assistant Home Assistant 2020.12.2: 
 - Hassio Home Assistant OS 5.9.
 - alexa_media  __version__ = "3.4.4":
 - alexapy could not find this
 - Amazon [2FA is enabled] yes

**Logs**
Please provide [logs]
Logger: homeassistant.loader
Source: loader.py:465
First occurred: 4:37:42 PM (1 occurrences)
Last logged: 4:37:42 PM

You are using a custom integration for alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
**Additional context**
from searchs it looks like it is not finding the .translation folder and/or the en.json file. I dont know how this process works but I have deleted the file translations and created a folder translations and still have the .translations folder, deleted the browser cache and the __pycache__ folder, full reboots not just restarts, deleted the root folder and readded the alexa_media folder, I have installed home assistaint in vmware and hyper on other systems and always get no text. 
![1](https://user-images.githubusercontent.com/59241768/103447071-7216e900-4c54-11eb-80f4-060387ba6d25.JPG)

**Comment by alandtse** [comment]
Hard refresh your browser cache. https://www.documate.org/automation/what-is-a-hard-refresh-how-to-do-a-hard-refresh-in-any-browser/

**Comment by womp666** [comment]
Thank you, I tried that a half dozen times yesterday with no luck.

**Comment by mwright-git** [comment]
I'm having the same problem (I had mistakenly created a duplicate issue)

I've tried reloading page, clearing cache and changing browsers - all to no avail.

**Comment by mwright-git** [comment]
I don't understand why this is closed when the issue has been explained as per the template and is still occurring for the OP and also myself.

**Comment by mwright-git** [comment]
Please accept my apologies - I have managed to sort the problem.

1) Because I downloaded the files and used the SAMBA share add-on to install the files, the Linux link from "translations" to ".translations" was broken. For a fix I deleted the file "translations", created a new directory of the same name and copied all the files from ".translations" to "translations"

2) After this I was getting login errors. Once I re-red the instructions I worked out that I was pasting the amazon 2FA key into the wrong field.

The integration has now installed properly and I can start to play with it.

As I said - please accept my apologies.
