### ISSUE TITLE
[Question] - Media controls

### ISSUE THREAD

**Issue by chemelli74** [custom-components/alexa_media_player#1081]
**Question**

I started using media card since a few days. I noticed that on my setup media controls doesn't work.
Based on the documentation instead, they should.

- Which controls  and when should work ?
- How can I investigate my setup ?

I also noticed that when I say "Alexa, stop" or "Alexa, stop music", the media player will be in `paused` mode and not in `standby`.
Can be a sign of the issue ?

Thx in advance for the time spent answering.

Simone

**Comment by alandtse** [comment]
When something is playing, the controls work. Outside of that I'm not too interested in what the UI does. Amazon will report something as paused but may not allow you to restart it.

Please feel free to document your findings on the wiki.

**Comment by broyuken** [comment]
I have found that the media controls do not work accurately at all lately. If I have something playing, it will display the track that is playing but it will say it is paused. This causes some of my automations to not fire correctly.

**Comment by alandtse** [comment]
@broyuken Make sure you're on the latest. There was a bug where updates failed after a while.

**Comment by broyuken** [comment]
Yep, updated last night and it’s good again, thank you

**Comment by chemelli74** [comment]
Working again here as well. Thx !

Simone

**Comment by broyuken** [comment]
Nope still broken. Was playing something again today and it said paused.
