### ISSUE TITLE
Unable to relog after amazon password change

### ISSUE THREAD

**Issue by patrickgmail** [custom-components/alexa_media_player#1083]
**Describe the bug**
I changed my amazon alexa password. So Home Assitant integration notified me that I have to re-enable my account.

The integration send an SMS code that I received, with an url to validate the new integration. I do it and in the web page, I get a message telling that the integration is approved. But in Home Assistant, the pop-up telling the steps never disapear.

I note that the link in SMS  is for amazon.com but I am an account on a different amazon.

I deleted the integration and re-install it by HACS but now, it doesn't appear anymore in my integrations. I'm lost and don't know what to do now.

Sorry for my appromative english.

**Comment by alandtse** [comment]
Enable 2FA. We don't provide support if you don't have 2FA.

Also fill out the full template.

**Comment by patrickgmail** [comment]
Thx. Enabling 2FA solved my problem! Many thanks
