### ISSUE TITLE
 Amazon Fire HD 8 and Amazon Fire Stick compatibility

### ISSUE THREAD

**Issue by diegolz83** [custom-components/alexa_media_player#1085]
I updated the Alexa media player to version 3.4.5 and it stopped detecting my Fire tablet and Fire Stick Tv devices. When I went back to version 3.4.1 the problem was fixed.

**Comment by alandtse** [comment]
We now only include devices as media players that report they have the capability to play music. Please provide the CAPABILITIES key from https://alexa.amazon.com/api/devices-v2/device for those devices.

**Comment by alandtse** [comment]
Also, what do you use them for?

**Comment by SchmDan** [comment]
I've the same issue. I use a wall mounted Fire Tablet with integrated Alexa for actionable notifications ([alexa_actions](https://github.com/keatontaylor/alexa-actions)). This extention relies on alexa_media_player and the device doesn't need the capability to play music. Moreover i use the tablet for making announcements via the notification component provided by alexa_media_player. This worked like charm until this change ([b9df09d](https://github.com/custom-components/alexa_media_player/commit/b9df09d34b7c6c20686bc4e68b4b651a88dd6943). I'd love if this would be more customisable. Like a whitelist of devices which should be always included, even without the music capability.

**Comment by SchmDan** [comment]
This is the object of my tablet (I've deleted all the id's)
```
{
    "accountName": "Dashboard",
    "appDeviceList": [],
    "capabilities": [
        "TIMERS_AND_ALARMS",
        "PERSISTENT_CONNECTION",
        "MICROPHONE",
        "SOUND_SETTINGS",
        "NO_TIME_ZONE_SETTING",
        "SUPPORTS_LOCALE",
        "REMINDERS",
        "CUSTOM_ALARM_TONE",
        "ASX_TIME_ZONE",
        "ASCENDING_ALARM_VOLUME",
        "DIALOG_INTERFACE_VERSION",
        "SUPPORTS_SOFTWARE_VERSION",
        "VOLUME_SETTING",
        "SUPPORTS_LOCALE_SWITCH"
    ],
    "charging": null,
    "clusterMembers": [],
    "deviceFamily": "TABLET",
    "deviceTypeFriendlyName": null,
    "essid": null,
    "language": null,
    "macAddress": null,
    "online": true,
    "parentClusters": [],
    "postalCode": null,
    "registrationId": null,
    "remainingBatteryLevel": null
}
```

**Comment by Duke-Box** [comment]
If this is correct then then this is an issue for me too.
I use the notify.alexa_media service a lot for announcements and some of my devices are tablets.
I have not upgraded to 3.4.5 yet as when I do, I cannot get past the authentication which I presume is because I don't use 2FA as it isn't mandatory ( is it now mandatory and that is why I can't get 3.4.5 to work?)
I am back on 3.4.1

Here is the capabilities key etc. of one of my tablets

"capabilities":[
	"CUSTOM_ALARM_TONE",
	"SUPPORTS_LOCALE_SWITCH",
	"MICROPHONE",
	"ASCENDING_ALARM_VOLUME",
	"SOUND_SETTINGS",
	"NO_TIME_ZONE_SETTING",
	"REMINDERS",
	"SUPPORTS_SOFTWARE_VERSION",
	"SUPPORTS_LOCALE",
	"ASX_TIME_ZONE",
	"DIALOG_INTERFACE_VERSION",
	"VOLUME_SETTING",
	"TIMERS_AND_ALARMS",
	"PERSISTENT_CONNECTION"
	],
	"charging":null,
	"clusterMembers":[],
	"deviceAccountId":"xxxxxxxxxxxxxxxxxxxxxxxxx",
	"deviceFamily":"TABLET",
	"deviceOwnerCustomerId":"xxxxxxxxxxxxxxxx",
	"deviceType":"xxxxxxxxxxxxxxx",
	"deviceTypeFriendlyName":null,
	"essid":null,
	"language":null,
	"macAddress":null,
	"online":false,
	"parentClusters":[],
	"postalCode":null,
	"registrationId":null,
	"remainingBatteryLevel":null,
	"serialNumber":"xxxxxxxxxxxxxxxxxx",
	"softwareVersion":"659655920"},

**Comment by alandtse** [comment]
PR should cover the tablets but still need Fire Stick info. Include_devices will override the capability filter too.
