### ISSUE TITLE
Alexa Media Player - Action Required

### ISSUE THREAD

**Issue by ronbentley9** [custom-components/alexa_media_player#1091]
When i authenticate i get this message. I approve the login on my phone but when i press submit. This screen re appears constantly 

Alexa Media Player - Action Required
myemail@gmail.com - alexa.amazon.co.uk
Amazon will send a push notification per the below message. Please completely respond before continuing.

To continue, approve the notification sent to:
Mobile number --**65
Application AmazonShopping, HUAWEI VOG-L09

**Comment by alandtse** [comment]
Enable [2FA](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account). We don't provide support if you don't have 2FA. Also fill out the full template.
