### ISSUE TITLE
Unable to login to amazon.com.au

### ISSUE THREAD

**Issue by oneseventhree** [custom-components/alexa_media_player#1092]
**Describe the bug**

**To Reproduce**
1. Upgraded through HACS: 
![1](https://user-images.githubusercontent.com/15043282/103974822-b6f7ce00-51c6-11eb-94d0-3fbb18aae418.png)

2.  When HA restarted it asked me to sign in again: 
![2](https://user-images.githubusercontent.com/15043282/103975080-659c0e80-51c7-11eb-9be7-2d0f02809623.png)

3. Went to Integrations and signed in: 
![3](https://user-images.githubusercontent.com/15043282/103975465-523d7300-51c8-11eb-853a-5a029e3f4175.png)

4. Then it took me to the other sign in page: 
![4](https://user-images.githubusercontent.com/15043282/103975513-6c775100-51c8-11eb-9a77-f788713922ee.png)

5. Then I got this error: 
![5](https://user-images.githubusercontent.com/15043282/103975518-6ed9ab00-51c8-11eb-9239-93e872cea504.png)

6. It still shows in integrations but my devices are all "unavailable": 
![6](https://user-images.githubusercontent.com/15043282/103975541-8022b780-51c8-11eb-8ce8-012304515015.png)

7. I tried downgrading back to 3.4.1 with no luck
8. I also tried deleting the component completely and starting fresh but it looks like it works and even shows the devices there so I know it connects to my account but the devices are still unavailable.

**Expected behavior**
Normal function

**Screenshots**

**System details**
 - Home-assistant (version):  2020.12.7
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup): 
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: Yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

Nothing in the logs.

**Additional context**
Had to use old snapshot file to revert back to 3.4.1 and everything works fine.

**Comment by alandtse** [comment]
Thanks. I found it. I'll release a new version shortly. However, 3.4.1 shouldn't be impacted by the changes. If it worked before for you it shouldn't have had any issues when you rolled back.

**Comment by brywithawhy** [comment]
I'm having the same issue trying to log into amazon.com.au with 3.4.8
Shall I open another issue?

**Comment by oneseventhree** [comment]
> I'm having the same issue trying to log into amazon.com.au with 3.4.8
> Shall I open another issue?

To confirm - this now works for me on 3.4.8 BUT I had to go back to an old backup/snapshot from when Alexa media player was working (3.4.1) and updated from there. 
When I didn’t update from a non working version(3.4.7) - maybe give that a go?

**Comment by alandtse** [comment]
The downgrade won't have any impact. Please open a new issue with logs.
