### ISSUE TITLE
Provide a sensor for the last received voice command

### ISSUE THREAD

**Issue by stieler-it** [custom-components/alexa_media_player#1105]
**Is your feature request related to a problem? Please describe.**
I would like to react on voice commands that are not sent to Home Assistant, e.g. if a third party skill is called.

**Describe the solution you'd like**
I would like to have a sensor that contains the string of the last received voice command for each Echo device. In openHAB this [value is called](https://www.openhab.org/addons/bindings/amazonechocontrol/#channels-2) `lastVoiceCommand`. I could then create Automations triggered by a state change of that sensor.

**Describe alternatives you've considered**

**Additional context**

**Comment by alandtse** [comment]
It won't be a sensor but another attribute on the media_player. `last_called_summary`

**Comment by stieler-it** [comment]
Thank you, I didn't expect it so fast 👍
