### ISSUE TITLE
Alexa Media Player Problem -TTS

### ISSUE THREAD

**Issue by shan3princ3** [custom-components/alexa_media_player#1106]
Hi Guys i am not sure if anyone can assist me with this Integration. I have managed to add the integration is home assistant but the Entity keeps jumping between standby and unavailable state. Also when i try the TTS Functionality i get no response from Alexa Media Player. I don't see any Logs being generated to identify a place to start looking for the issue. 
Home Assistant Core 2020.12.2 
Operating System 5.9

**Comment by alandtse** [comment]
Please fill out the template.

**Comment by shan3princ3** [comment]
Hi Alan can you send me the location for this template

**Comment by shan3princ3** [comment]
System details

    Home-assistant (version): 2020.12.2
    Hassio (Yes/No): yes
    alexa_media (version from const.py or HA startup): 3.4.7
    alexapy (version from pip show alexapy or HA startup):
    Amazon 2FA is enabled (y/n). We will not debug login issues if unanswered: yes

**Comment by alandtse** [comment]
That is not the complete template. The template also shows how to enable logging.

**Comment by shan3princ3** [comment]
I have enabled logging and received the logs. Do you want me to paste the entire output here

**Comment by alandtse** [comment]
Where is your Amazon account registered. It's reporting a domain mismatch which can break functionality. You need to log into the same domain as your account and devices are set up in.

**Comment by shan3princ3** [comment]
Hi Alan , My echo device is registered in amazon.com.au

**Comment by alandtse** [comment]
Does any functionality work? Your logs indicate a total lack of functionality. If you try to login to amazon.com does anything change?

**Comment by shan3princ3** [comment]
Hi Alan after re-registering the echo device and re-installing the integration the echo entity has cme online and tts is working fine now
