### ISSUE TITLE
problem volume group alexa echo

### ISSUE THREAD

**Issue by danilohassio** [custom-components/alexa_media_player#1108]
later update 3.4.7 or 3.4.8 i have problem volume group stop work 

volume work ok with 3.4.5

**Comment by alandtse** [comment]
Please fill out the template.

**Comment by danilohassio** [comment]
the volume group the all alexa does not show where the level is.
it always remains at 0
with version 3.4.5 I have no problem


entities:
  - entity: media_player.casa
    full_row: true
    max: 50
    min: 0
    step: 10
    type: 'custom:slider-entity-row'
title: VOLUME CASA
type: entities

**Comment by danilohassio** [comment]
I increase and decrease the volume at the echo group the all devices created by alexa the signal arrives volume change, but the cursor always remains fixed at 0

**Comment by danilohassio** [comment]
also with a new versione 3.5.0 continue no work good group all device volume
