### ISSUE TITLE
Problem configuring integration

### ISSUE THREAD

**Issue by mwright-git** [custom-components/alexa_media_player#1109]
I cannot seem to configure the integration after installing the custom_components files.

Once I select the alexa_media integration, the configuration screen shows up - but there are no labels on the fields! I can tell there are about 6 or 7 fields plus a number and a checkbox but I have no idea which field is which.

ANy ideas?

Thanks
<img width="311" alt="Screenshot 2021-01-16 125728" src="https://user-images.githubusercontent.com/35849157/104812487-787f9600-57fa-11eb-87da-bb520eb18d91.png">

**Comment by alandtse** [comment]
Dupe #1076
