### ISSUE TITLE
I'm having the same problem (I had mistakenly created a duplicate issue)

### ISSUE THREAD

**Issue by womp666** [custom-components/alexa_media_player#1110]
I'm having the same problem (I had mistakenly created a duplicate issue)

I've tried reloading page, clearing cache and changing browsers - all to no avail.

_Originally posted by @mwright-git in https://github.com/custom-components/alexa_media_player/issues/1076#issuecomment-761585210_
https://github.com/custom-components/alexa_media_player/issues/1076#issue-777348017

**Comment by womp666** [comment]
https://github.com/custom-components/alexa_media_player/issues/1076#issue-777348017

**Comment by alandtse** [comment]
I don't know what this issue is. Please follow the template.
