### ISSUE TITLE
Error connecting; check network and retry

### ISSUE THREAD

**Issue by Kosh42** [custom-components/alexa_media_player#1111]
**Describe the bug**
Unable to setup this integration. It was working (albeit intermittently with repeated re-authentication every few days). I uninstalled, tried to reinstall, and not have the above error every time I connect.

Step I have tried to resolve this:

- Setup 2FA with the Google Authenticator on my phone.
- Made sure the custom_components directory entry was deleted.
- Deleted the Alexa .pickle file in .storage
- Reinstalled via HACs, then rebooted Home Assistant twice before trying to add the integration.
- Manually installed the dev branch of the integration to custom_components.
- Copied cookies.text
- From the Terminal addon I can ping amazon.co.uk, so DNS and routing seems ok, and 0 packet loss.

And I am definitely using .co.uk and not .com

**Screenshots**
![Alexa Error](https://user-images.githubusercontent.com/58401509/104838402-9e687180-58b2-11eb-8b65-cabc55d5d912.png)

**System details**
 - Home-assistant (version): Home Assistant 2021.1.3
 - Hassio (Yes/No): Yes, restarted numerous times.
 - alexa_media  (version from `const.py` or HA startup): v3.4.8
 - alexapy (version from `pip show alexapy` or HA startup): I am very dense. Where can I find this HA startup?
 - Amazon [2FA is enabled]: Yes, with a separate app.

**Logs**
As the integration fails, unable to add component logs.

Odd question, when copying the uncommented lines from cookies.txt, what other fields should be filled in?

**Comment by alandtse** [comment]
Please use 3.5.0 and reopen if the issue persists.

**Comment by Kosh42** [comment]
Worked a treat. Thanks for your work on this excellent project.
