### ISSUE TITLE
After perfect working for weeks, now every time ask for reconfigure

### ISSUE THREAD

**Issue by poudenes** [custom-components/alexa_media_player#1115]
Hi All,

My Alexa Media Player was working for weeks perfect. Since today it ask me almost every time when my HA use Alexa Media Player to reconfigure.

I do the steps, everything goes well.. Captcha  work, gaineverything work. But when HA trigger the  device I must do everything again.

Im using Alexa Media Player 3.4.8 on HA 2021.1.4 (Docker)

**Comment by alandtse** [comment]
Update to 3.5.0 and reopen using the template if an issue.
