### ISSUE TITLE
Alex_media - Deauthorizing another machine when authorized

### ISSUE THREAD

**Issue by pittgo** [custom-components/alexa_media_player#1130]
I am having an intersting problem. have Alexa media player installed on two systems with two separate Amazon accounts and two separate Nabu Casa cloud accounts. When i register one machine with Amazon,,, it degegisters the other machine. What is noteworthy is that both machines at one time ran the same HA account amazon and Nabu Casa however was reconfigured when I replaced that machine with an RPI and then used the original to replace an older machine . They are not at the same address nor on a shared network in anyway. The Amazon account are not linked. No errors occur the only thing that happens is as we reauthorize the one the other location deauthorizes.

I have removed and resinstalled HACS and Alexa Media Player ( removing relevant files that i could find) on both machines thinking the accounts are linked some how but same problem

Is there a file i should be deleting specifically that is holding some of the previous Amazon account detail ?

Any help would be appreciated

G

**Comment by alandtse** [comment]
If both HAs have the same uuid, then you will have this problem. This is found in .storage/core.uuid. I don't know if HA supports changing it manually or if it'll break a system if you change it.  Every new HAwill generate a new uuid on first run which is supposed to be unique. I need to use this unique uuid to generate the serial number in a deterministic way so we don't keep creating more devices in Amazon.

Maybe I can make it so different accounts will change the uuid further but I'm not sure how much effort I should be spending if you HA isn't guaranteeing it's unique.

**Comment by pittgo** [comment]
Wow  that was fantastic!   It was indeed a dupe UUID  i didnt move that file when i changes the system   i only moved the yaml files .  Thank you  

G
