### ISSUE TITLE
Notify.Alexa_Media is no longer available for all devices

### ISSUE THREAD

**Issue by the4jaggz2** [custom-components/alexa_media_player#1138]
**Describe the bug**

Notify.Alexa_Media is no longer available for all devices

**To Reproduce**
This may be related to the most recent update of the Alexa Media Player or perhaps the most recent update of HA (v2021.1.5)...both were done together before a restart of HA.   I have approx 19 devices but the service : "notify.alexa_media" is only showing for 2 of them.  When I go into Configuration - Integrations - amazon alexa and reload, all of them show up under Developer Tools - Services but after playing once on a previously missing device/service, all of them disappear again with only 2 remaining.  

The log I get is the following:
--------------------
Logger: alexapy.alexalogin
Source: /usr/local/lib/python3.8/site-packages/alexapy/alexalogin.py:698
First occurred: 12:43:19 PM (2 occurrences)
Last logged: 12:50:40 PM

No access token found; falling back to credential login instead of oauth.
-----------------------

Not sure if this is a bug or I should try deleting the pickle file. I have tried removing the alexa-media folder in the custom-components folder and re-installing but it produces the same results.

**Comment by alandtse** [comment]
Please fill out the complete template.

**Comment by the4jaggz2** [comment]
Sorry...will complete although going to hold for a bit.  I just checked again and now 9 out of the 19 have become available without doing anything but leaving the system alone for the past hour.  Prior to that, I did restart home assistant multiple times  so that is not what is causing this service to become available.  Will advise further/fill out the form if no further ones come back over the next few hours.

**Comment by the4jaggz2** [comment]
Thank you for addressing this so quickly.  I noticed that a new version was published in HACs so I installed it and now all my devices are showing up with a "notify.alexa_media" service again. Well done!  And next time, I will ensure the template is fully completed to better help with troubleshooting.  :)
