### ISSUE TITLE
v3.6.2 no Captcha - Reconfigure

### ISSUE THREAD

**Issue by ottelo9** [custom-components/alexa_media_player#1144]
I updated to 3.6.2. Now I have to reconfigure the Integration, reinsert my password, 2FA Code and an Captcha. But at the top there is no image!

The link in the broken image icon:
https://opfcaptcha-prod.s3.amazonaws.com/XXXX.jpg?AWSAccessKeyId=XXXX&Expires=1611529053&Signature=XXXX

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Request has expired</Message>
<Expires>2021-01-24T22:57:33Z</Expires>
<ServerTime>2021-01-25T08:40:22Z</ServerTime>
<RequestId>XXXX</RequestId>
<HostId>XXXX</HostId>
</Error>
```

I "XXXX" the AWSAccessKeyId, Signature, RequestId and HostId out.
![Unbenannt](https://user-images.githubusercontent.com/33122175/105681614-9f705300-5ef1-11eb-8bf9-fd4e5ea66a24.PNG)

**Comment by PRES1005** [comment]
+1, same here!

**Comment by GazKez** [comment]
+1 thanks in advanced!

**Comment by Pirol62** [comment]
Did you try entering some letters and press submit?
That's what I'm doing in this case. With the second try, the picture aooears

**Comment by GazKez** [comment]
I did something similar, reinstall 2 differents version, restart home assistant and finally the picture appear.

**Comment by alandtse** [comment]
Submit anything. It will refresh then.

**Comment by iainmacthai** [comment]
Yep, I can confirm what the 3 prior posts suggest. Submit any garbage and it will refresh with a visible captcha.
