### ISSUE TITLE
Captcha does not work

### ISSUE THREAD

**Issue by herbert-roth** [custom-components/alexa_media_player#1154]
**Describe the bug**
Captcha is not displayed.

<img width="578" alt="Bildschirmfoto 2021-01-28 um 13 30 05" src="https://user-images.githubusercontent.com/10243739/106138870-f766be00-616c-11eb-82ae-d2961e074055.png">

Got Error from amazon:

<Error>
<Code>AccessDenied</Code>
<Message>Request has expired</Message>
<Expires>2021-01-28T11:11:15Z</Expires>
<ServerTime>2021-01-28T11:38:15Z</ServerTime>
<RequestId>59A3D1E6BA2012F5</RequestId>
<HostId>
3OlnftI+ri/9xd3pR3PdoY3hWkHk6QpOUYPX2Q0Iza1REfOexYgC4wZGDa2MDoOgV/NyrqtxVZQ=
</HostId>
</Error>

**System details**
 - Home-assistant : 2021.1.5
 - Hassio : Yes

**Comment by alandtse** [comment]
Please search. This is a dupe. Submit anything.
