### ISSUE TITLE
Open Website - Integration Installation - URL to access home assistant

### ISSUE THREAD

**Issue by scubasteve2365** [custom-components/alexa_media_player#1156]
Attempting to install. Using 2FA. Using authenticator app. All details entered into the Alexa Media Player configuration screen. When I hit submit with my local url to access Home Assistant, Alexa Media Player pops-up and says unable to connect to Home Assistant url. No problem, let me enter my remote url (duckdns.org) and it seems to go through but it wants to open a website. However when the "open website" button is pressed, a new tab on my browser opens, but it cannot connect. I get a "site can't be reached" notification.

**Comment by alandtse** [comment]
It must be an internal URL. Otherwise your firewall will likely block the attempt.

**Comment by honky-bear** [comment]
I have the same issue.  The issue appears to occur when using SSL and a certificate issued that includes the external domain.
When using the internal URL, the component seems to fail because the certificate isn't valid for the internal hostname.

**Comment by alandtse** [comment]
@honky-bear The latest version includes a test to try to connect to the provided internal url and should reject that url if there is a SSL cert error. If you are seeing an issue on the latest issue, please open a new issue since this one is closed.
