### ISSUE TITLE
not validate the integration

### ISSUE THREAD

**Issue by sleon76** [custom-components/alexa_media_player#1157]
**Describe the bug**

is there a problem with the integration? today it stopped working and does not validate the connection from my cell phone in amazon

**Screenshots**
![image](https://user-images.githubusercontent.com/76074686/106398174-adeacd00-6411-11eb-9d27-a119a35b0777.png)

**System details**
 - Home-assistant (2021.1.5): 
 - Hassio (2021.01.7):
 - 
**Logs**
Logger: homeassistant
Source: runner.py:99
First occurred: 22:21:18 (2 occurrences)
Last logged: 22:21:18

Error doing job: Unclosed client session
Error doing job: Unclosed connector

**Comment by alandtse** [comment]
Enable 2FA.
