### ISSUE TITLE
Delay in last_called update

### ISSUE THREAD

**Issue by Pirol62** [custom-components/alexa_media_player#1159]
**Describe the bug**
Last friday it became obvious, that alexa has performance issues.
I had to increase the delay from 1 second to 5 in oder to have the sensor.last_called_alexa updated
All media_players need up to 5 Minutes to update their states and attributes when for example playing music.
Yesterday the media player entities update needed 15! Minutes before showing the right state
I had a strange error in my logs this night, which I've never seen before

**To Reproduce**
I'm using 'alexa_media.update_last_called' in tons of scripts which all had problems. I had to increase the delay

**Expected behavior**
At least a sensor refresh time of less then 3 seconds

**Screenshots**

**System details**
 - Home-assistant (version): 2021.1.4    - update to 1.5 failed last week
 - Hassio (Yes/No): yes
 - RaspB3+. (Cpu between 3 and 8%, Memory 58%, SD Card utilization: 11%, DB 165MB)
 - alexa_media  (version from `const.py` or HA startup): 3.6.3
 - alexapy (version from `pip show alexapy` or HA startup): 
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: 2FA is activated

**Logs**
````
Logger: homeassistant.components.alexa.state_report
Source: components/alexa/state_report.py:126
Integration: Amazon Alexa (documentation, issues)
First occurred: 0:18:49 (5 occurrences)
Last logged: 5:19:53

Error when sending ChangeReport to Alexa: INVALID_ACCESS_TOKEN_EXCEPTION: Access token is not valid.
````

**Additional context**
My sensor:
````
last_called_alexa:
      value_template: >
        {{ expand(states.media_player.receiver, states.media_player.wohnzimmer, states.media_player.schlafzimmer, states.media_player.kuche, states.media_player.gastezimmer, states.media_player.office, states.media_player.fitnessraum,  states.media_player.bad_yvonne) | selectattr('attributes.last_called','eq',True) | map(attribute='entity_id') | first }}
````

**Comment by alandtse** [comment]
Please do not exaggerate the issue. You identified a single issue related to last_called update. Also, please do not report logs from the built in integration to me. They're totally unrelated.

**Comment by alandtse** [comment]
Please test the PR. This issue will go away with HA 2021.2.x anyway.

**Comment by Pirol62** [comment]
> Please do not exaggerate the issue. You identified a single issue related to last_called update. Also, please do not report logs from the built in integration to me. They're totally unrelated.

Hi Alantse, sorry, I wasn't shure if this error was related to alexa_media or the built in integration.
Thanks for your support.
I will test that out asap.

**Comment by Pirol62** [comment]
Tested it. The issue is solved. Thanks a lot!
