### ISSUE TITLE
Set Echo Show background | Defined Rules Needed

### ISSUE THREAD

**Issue by mbonaccors** [custom-components/alexa_media_player#1160]
The instructions for utilizing  "Set Background" are below:

You can set the background of an Echo Show using the media_player.play_media service with media_content_type set to image. The url must be a valid https image to be accepted. To undo, follow these instructions.

entity_id: media_player.echo_show
media_content_id: "https://home-assistant.io/images/cast/splash.png"
media_content_type: image

This stock media works when tested, however using other HTTPS images are not accepted by the media player. If there are specific SSL / HTTPS rules or perhaps graphic formatting rules for the images to be accepted by the Echo Show, can you please describe?

Currently, any images tested show a blank screen on the Echo Show device, followed by the "Echo" logo, and then reverting to the original background.

**Comment by alandtse** [comment]
I don't use it so I don't document it. It uses the same command as the official app.  Please feel free to update the wiki if you figure out any quirks.
