### ISSUE TITLE
Translation to pt-BR or pt-PT

### ISSUE THREAD

**Issue by DOWIT-JoelFrojmowicz** [custom-components/alexa_media_player#1161]
I'm available to translate the component to pt-BR or pt-PT.

**Comment by alandtse** [comment]
Thank you. Please follow the instructions here. https://github.com/custom-components/alexa_media_player/wiki/Translations
Do you want me to open both languages?

**Comment by alandtse** [comment]
Actually, both are opened now. Thanks again!
