### ISSUE TITLE
Unable to login stuck on integration page

### ISSUE THREAD

**Issue by jabshettys** [custom-components/alexa_media_player#1165]
Hi Team,

I am trying to install alexa media player but unable to get sccess.

Installed alexa media player through HACS. I am able to find the alexa media player in the integration page i filled the information as per the instruction
- amazon login email address
- amazon login password
- url amazon.in
- 2FA code blank
- built in 2fa(got it from amazon and pasted in this section)
- Enable outh token app method ( tried both checked and unchecked)
- Use login proxy method ( tried both checked and unchecked)

It is stuck on this screen and keeps on rotation at the bottom.

Log:
Logger: custom_components.alexa_media.config_flow
Source: custom_components/alexa_media/config_flow.py:493
Integration: Alexa Media Player (documentation, issues)
First occurred: 0:30:08 (1 occurrences)
Last logged: 0:30:08

Unknown error: Expecting value: line 1 column 1 (char 0)

Please someone help me.

Sorry for my english.

Sachin

**Comment by alandtse** [comment]
Please fill out the template.
