### ISSUE TITLE
Feature Request: Set Volume, Speak, Resume Volume

### ISSUE THREAD

**Issue by kreene1987** [custom-components/alexa_media_player#1177]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When coming from Echo Speaks, there was an option I used frequently that was a 3-step pattern:
1) Set Volume (for example, if volume is 3, then it would set volume to 6)
2) Speak (message at Volume 6)
3) Reset Volume back to original volume (say 3 per example above)

**Describe alternatives you've considered**
None

**Additional context**
https://tonesto7.github.io/echo-speaks-docs/devicesupport/commands/speech_commands/#setvolumespeakandrestorevolume_message

All other unique features of the Echo Speaks actions would be fantastic, but specifically the one above is one I am looking for.

For your consideration,

Kreene1987

**Comment by alandtse** [comment]
Thanks. This is one of the first scripts that people have written and you can probably find it in the wiki. This will be low priority.
