### ISSUE TITLE
Multiple integration entries for one account

### ISSUE THREAD

**Issue by silviudc** [custom-components/alexa_media_player#1179]
**Describe the bug**

Not sure why this is happening but when I connect my amazon.co.uk account I see two integrations for the same account, one has 3 devices and no entities and the other has 3 devices and 18 entities
If I removed either of them then my announcements stop working.

**To Reproduce**

Check Alexa integration under the Integrations page.

**Expected behavior**
I should only see one integration for one account and not two.

**Screenshots**
![image](https://user-images.githubusercontent.com/17740184/107532978-5b01da00-6bb6-11eb-8106-078298053578.png)

**System details**
 - Home-assistant (version): 2021.2.2
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug). Yes
 - alexa_media  (version from `const.py` or HA startup): 3.8.0
 - alexapy (version from `pip show alexapy` or HA startup): unknown
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: No

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.
Not yet

**Additional context**

**Comment by alandtse** [comment]
If you remove both and readd does it happen again? Please provide logs of your startup if it persists after the removal.

**Comment by silviudc** [comment]
Ok I think I may have figured something out.
I have deleted the integration that has just the 3 device son their own and then I tried doing a notification test and the script now fails. 
I believe it is related to this part of the config.yaml:

`notify:
  - name: alexa_media
    platform: alexa_media
`
The script which now fails:
`service: notify.alexa_media_kitchen_dot
data:
  data:
    type: tts
  target:
    - media_player.kitchen_dot
  message: This is an example of text-to-speech
`

And that is why it always comes back on HA restart after I remove it which means not a bug but user error.
In that case how do you suggest I proceed to just have one integration showing up? As without the notify, I am unable to send messages to the Echo dots.

**Comment by alandtse** [comment]
You shouldn't need anything in your configuration.yaml. Please remove anything there and use the integrations page. If you use the yaml it will auto create the integration.

**Comment by silviudc** [comment]
Ok removed and it did not come back.
Also the notify using notify.alexa_media works fine too.
Thank you and you can remove this issue as it is not one in fact.
