### ISSUE TITLE
Loop Argument Deprecated

### ISSUE THREAD

**Issue by pizzakid25** [custom-components/alexa_media_player#1182]
**Describe the bug**
Everything is working as it should. However, it appears that some of the Alexapy code needs to be updated before Home Assistant begins to use version 3.10 of Python later this year in October/November.

**To Reproduce**
View the core logs in supervisor.

**Expected behavior**
N/A

**Screenshots**
None

**System details**
 - Home-assistant (version): 2021.2.3
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): 3.8.0
 - alexapy (version from `pip show alexapy` or HA startup): 1.24.0
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: No

**Logs**
```
/usr/local/lib/python3.8/site-packages/alexapy/aiohttp/connector.py:999: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  hosts = await asyncio.shield(
/usr/local/lib/python3.8/site-packages/alexapy/aiohttp/locks.py:22: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  self._event = asyncio.Event(loop=loop)
```

**Additional context**
None

**Comment by larena1** [comment]
https://gitlab.com/keatontaylor/alexapy/-/tree/dev/alexapy/aiohttp

Something went wrong there. There's a folder with the new aiohttp version inside of the actual aiohttp folder.

And is it really necessary for alexapy to ship its own version of aiohttp?

**Comment by alandtse** [comment]
No that's right. We ship a patched version because the cookie handling is broken in aiohttp. https://github.com/aio-libs/aiohttp/issues/4486

**Comment by larena1** [comment]
Are you sure that's right? Because you're still using the version with deprecations

https://gitlab.com/keatontaylor/alexapy/-/blob/dev/alexapy/aiohttp/connector.py#L999

**Comment by alandtse** [comment]
Odd, aiohttp said they [fixed it](https://github.com/aio-libs/aiohttp/issues/4477) in master and I pulled from master. Feel free to hunt down which rev I should be pulling down and I'll update it.

Otherwise, this is low priority for me.

**Comment by alandtse** [comment]
Oh. Odd, the build script didn't copy the updated version in.

**Comment by larena1** [comment]
It did.

https://gitlab.com/keatontaylor/alexapy/-/tree/dev/alexapy/aiohttp/aiohttp

That's what I was referring to in my post before ;)
