### ISSUE TITLE
Broken Captcha Image

### ISSUE THREAD

**Issue by usedjeans818** [custom-components/alexa_media_player#1188]
**Describe the bug**
The Alexa Media Player integration is stating I need to Reconfigure the integration.  However, at the screen that is displayed, the Captcha Image, which is required to proceed, is broken.

**To Reproduce**
1. Go to 'Configuration' -> 'Integrations'
2. Click on 'RECONFIGURE'
3. The image tag which should display the Captcha is broken

**Expected behavior**
I expect to be able to see the Captcha in order to proceed with reconfiguring the integration

**Screenshots**
![alexa_attention_required](https://user-images.githubusercontent.com/74646319/108126862-32b72700-705f-11eb-9cab-b12dec868a42.png)

![alexa_reconfigure](https://user-images.githubusercontent.com/74646319/108126876-38ad0800-705f-11eb-864e-cab3e4e255ee.jpg)

**System details**
 - Home-assistant (version): core-2021.2.3
 - Hassio (Yes/No): Home Assistant OS 5.11
 - alexa_media  (version from `const.py` or HA startup): v3.8.1
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: Yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**
I have accessed this page using the public URL https://homeassistant.sample.net:3184 as well as the local IP https://192.168.1.9:8123 and the image is broken for both.  I have also tried on multiple devices (a desktop and a laptop) as well as browsers.

**Comment by usedjeans818** [comment]
Really weird...  I restarted HA to get logs and the Reconfigure requirement just disappeared!  I figured I'd leave this open for @alandtse to at least see.

![Screenshot_2021-02-16 Configuration - Home Assistant](https://user-images.githubusercontent.com/74646319/108128623-de617680-7061-11eb-945e-2a70a1031b4a.png)

**Comment by alandtse** [comment]
Please search. This is a common issue and you just need to submit anything.
