### ISSUE TITLE
Alexa Media player says it needs to be reconfigured

### ISSUE THREAD

**Issue by bturrie** [custom-components/alexa_media_player#1189]
**Describe the bug**
When I click on it , a page comes up called Alexa Media Player - Captcha. Not at all clear what that page wants. There appears to be placeholder for a "picture" but there's only a placeholder. I entered my password but it seems to want a something. Perhaps that place holder shows a captcha for me to enter. Cannot be sure but there is no way to proceed. When I click on the placeholder I see this:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Request has expired</Message>
<Expires>2021-02-16T22:46:39Z</Expires>
<ServerTime>2021-02-17T00:57:54Z</ServerTime>
<RequestId>BWBH9N3H9T0Z3G7Y</RequestId>
<HostId>spftrrdvfWvhJirXzInEP5pjJQ98gjYnulTSYDMVZUR657SY0LjiKENgfAgrgQADM9vKy33N+uk=</HostId>Captcha 

Maybe I need to delete alexa media player and start over. Not sure It's worth the effort if this is going to happen.

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details**
 - Home-assistant (version): 
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: 

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by alandtse** [comment]
Please search as this is a dupe.
