### ISSUE TITLE
Unhandled command: PUSH_LIST_CHANGE

### ISSUE THREAD

**Issue by klatka** [custom-components/alexa_media_player#1190]
**Describe the bug**
Unhandled command from alexa_media_player integration.

**To Reproduce**
1. Configure this integration
2. Clear a whole list through Alexa (e.g. shopping list)
3. Check logs
4. See warning

**Expected behavior**
No warning at all. Is there an event risen if a command is recognized, so I could react on the clear list?

**System details**
 - Home-assistant (version): 2021.2.3
 - Hassio (Yes/No): Yes (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup): 3.8.1
 - alexapy (version from `pip show alexapy` or HA startup): 1.22.3
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: -

**Logs**
`Unhandled command: PUSH_LIST_CHANGE with data {'destinationUserId': 'A**********IZA', 'listId': 'YW16bjEuYWNjb3VudC5BRUE3SUlDN1NIRUw3NEpTQlpKRUFSVUVHRVBRLVNIT1BQSU5HX0lURU0=', 'version': 1, 'eventName': 'listCleared'}. Please report at https://github.com/custom-components/alexa_media_player/issues`

**Comment by alandtse** [comment]
Thanks. We'll set this to ignore since we don't do anything with the shopping list.

**Comment by klatka** [comment]
Is it possible to raise an event with the unhandled commands and then do nothing more?
This could be a really nice interface that would make every IFTTT applet obsolete that I currently have.

**Comment by alandtse** [comment]
Yes it's possible. It's also really spammy which can saturate the HA logs. In not inclined to expose these events without an actual use case.

**Comment by klatka** [comment]
Okay, thanks. Maybe I'm going to open a feature request in the future because I would have a use case.

**Comment by alandtse** [comment]
Let's leave it open until I actually add it to the ignore list.
