### ISSUE TITLE
Feature Request: Set next_alarm through Home Assistant for an Alexa speaker

### ISSUE THREAD

**Issue by klatka** [custom-components/alexa_media_player#1194]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I'd like to set an alarm for an Alexa speaker through Home Assistant.

**Describe alternatives you've considered**

**Additional context**
I get different work times which Home Assistant reads through a calendar. I would like to create an automation which 
sets my alarm on my Alexa speaker in my bedroom every day.

**Comment by alandtse** [comment]
You can do this with a custom command.

**Comment by klatka** [comment]
My mistake, I read the wiki twice but didn't get this...
Is it possible to mute the answer after custom command?

**Comment by alandtse** [comment]
No. It's the same as speaking to the device.

**Comment by alandtse** [comment]
I guess you could set the volume to 0 before you issue the command.
