### ISSUE TITLE
TypeError('the JSON object must be str, bytes or bytearray, not NoneType')

### ISSUE THREAD

**Issue by iWPL** [custom-components/alexa_media_player#1196]
**Describe the bug**
- Websocket is closed following a JSON TypeError after asking (by voice) any Echo to play something, be it an Audiobook (from Audible) or Music (from Amazon Music) or the Radio (from Tunein). (Note: not tried other sources). 
- As a result the state is no longer correctly pulled into HA (i.e. Developer Tools). This is also reflected in the logs as they remain in 'Standby', 'Paused' or 'Idle' state regardless of what they are actually doing.
- Alexa Media Player falls back to polling for data every 5 minutes - however polling is disabled for all Echoes [2021-02-23 19:27:24].

Note: Pushing commands to the Echoes from NodeRed still works - e.g. the wake up routine of announcing the time (notify) and reading the weather/news (daily brief skill) still works just fine.

However, due to the crash, the automations that checks whether my daughters turn their Echoes back on after 'Lights Out' no longer works as the STATE is not reported. As such the sleep timer no longer functions.

The only data that appears to change is 'last_called'.

Also, FireTV state is not recognised before or after the crash but I suspect that this is not in scope even though it is included in the detected devices list.

**To Reproduce**
In the example from the attached logs ...
1. Have music playing on one Echo device
2. Restart HA
3. HA boots up and Alexa Media Player connects to Amazon and brings in the states of all Echo devices okay (e.g. the one echo shows 'Playing', all others 'Standby', 'Paused' or 'Idle') [2021-02-23 19:27:13].
4. FireTVs turn on and play Netflix. (STATE in HA and logs is NOT updated.) [2021-02-23 19:31:56 - 2021-02-23 19:32:03]
5. Node Red Automation runs that stops my daughters FireTVs playing. Alexa says 'Goodnight' on one Echo and 'See you in the morning' on another. [2021-02-23 19:45:00]
6. One daughter asks 'Alexa, Resume' to listen to her audiobook. [2021-02-23 19:45:13]
7. Errors immediately thrown and Websocket closed. STATE of any Echo is no longer updated into HA [2021-02-23 19:45:1]
8. Three further errors thrown every 5 minutes as can no longer communicate with the API [2021-02-23 19:45:20]
9. Further 'Good night' message sent by a different automation I thought I had turned off [2021-02-23 20:00:00] and communication resumes 
10. ... until the next polling when it cannot communicate with the API again [2021-02-23 20:05:35 and 2021-02-23 20:10:38]
11. ... but then starts polling again continuously. [2021-02-23 20:15:38]

**Expected behavior**
- Echo states to be pushed to Alexa Media Player and therefore reflected in HA (Developer Tools).
- Alexa Media Player/alexapy handles the malformed JSON better? (or is it the other way around?)
- Auto re-enable the websocket?
- If websocket fails, re-enable the disabled polling?

**Screenshots**

**System details**
 - Home-assistant (version): 2021.2.3
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).      I think so, yes. I'm running it on a Raspberry Pi 3b (Many, many, many restarts have happened and the issue persists).
 - alexa_media  (version from `const.py` or HA startup): 3.8.2
 - alexapy (version from `pip show alexapy` or HA startup): 1.24.2
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: Yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.
[home-assistant 210223-2020 red.log](https://github.com/custom-components/alexa_media_player/files/6032016/home-assistant.210223-2020.red.log)

**Additional context**

This does not appear to be a log in issue as I can send commands to the Echoes and, at least initially, receive push notifications from Amazon.

**Comment by alandtse** [comment]
Thanks. I'll look at the disconnect. There is supposed to be an attempt to reconnect the websocket. It will give up after 5 attempts and switch back to polling. Polling behavior is designed not to slam Amazon so it will only poll devices that it knows are actually playing. So you need to interact with HA for it to figure this out, otherwise it won't poll.

Can you please visit https://alexa.amazon.co.uk/api/activities?startTime=&size=10&offset=1 and let me know what you're seeing? The log is indicating the page is blank which is causing the alexaapi.get_last_device_serial function to break.

**Comment by iWPL** [comment]
Hi,

Thank you for taking a look at this. 

I restarted HA so I had a working HA and Alexa Media Player. I then asked 'She Who Must Not Be Named' to read my book triggering Alexa Media Player/Alexapy to fall over. I loaded the suggested link (probably about 10-20 seconds later after confirming the crash in the logs) and I've attached the output.  
[Amazon - Activities output.txt](https://github.com/custom-components/alexa_media_player/files/6039148/Amazon.-.Activities.output.txt)  
Note: The restart happened between the 3rd and 4th objects.

I tried it again after this to see if I could 'catch it out' and found that on the third or fourth F5 it came back with  
`{"message":"Rate exceeded"}`  
After a few seconds break from refreshing, pressing F5 once more returned the JSON data.  
I think this was because I was refreshing too frequently as even after another restart (and not crashing Alexa Media Player/Alexapy first) I got the same message by refreshing the page about 4 or 5 times within a couple of seconds. Guess this is me slamming Amazon! Oops!

I'm not sure where alexaapi.get_last_device_serial gets it's data from, but if it is the 'UtteranceId' then the most recent object has a 'null' here, as does the 9th object where a crash was triggered. Every other object has an 'UtteranceId' value.  
I did also wonder if the 'Follow-Up mode' may be at play here but I don't think so as it is consistent across Echoes that have this on (my echo) and others that have it off (my daughters echo).

**Comment by alandtse** [comment]
Thanks for the details. I think it's probably the rate exceeded message. We're not looking at the utterance_id.  I recently made changes to allow seeing the last utterance but that had the side effect of querying that page more often. I think you just managed to trip it with your use case. I can probably have it ignore the message, but it may mean in your use case the last called device and utterance info may be out of date when that happens.

**Comment by alandtse** [comment]
Can you please test the linked PR to see if it resolves the issue for you?

**Comment by genebean** [comment]
@alandtse do you still need the PR tested? If so, I can try to do so in the morning

**Comment by alandtse** [comment]
Yes please. Once tested I can release it.

**Comment by iWPL** [comment]
Hi,
Apologies for the delay in replying. I only saw this this morning. 

Not being sure how to properly use the change you made I literally copied and pasted it into the file on my RPi, restarted HA and tried to break it! 

Having requested my audiobook to be read, HA showed the correct status (yeay!) and the log showed the following lines :
[home-assistant 210227-1203 abr red.log](https://github.com/custom-components/alexa_media_player/files/6054407/home-assistant.210227-1203.abr.red.log)

I checked the Activities page and compared it to the info on the Developer Tools page. The 'last_called_timestamp' for when I asked 'her' to read my book was for the 3rd object (first three were all part of the same request, "Alexa"(3rd), "Read my book"(2nd), "_nothing_"(1st)) and when I asked her to stop, it was timestamped with the 1st object (first two were all part of the same request, "Alexa" (2nd), "Stop" (1st)) - as you predicted , a bit inconsistent.

I'll keep an eye on it this evening to see if it wobbles again when the automations are also active.

If it is too many requests too quickly that is causing it, is it worth (on capturing this problem) waiting a couple of seconds and trying again as it quickly started responding again after a short pause during my rapid manual refreshes? (or is that what the `await` bit does?)

Thank you!

**Comment by genebean** [comment]
I copied the change to my pi and restarted via server management. I'll keep an eye on it today.

**Comment by iWPL** [comment]
Hi,

Evening update ... The error message (as per the log from earlier today) is only appearing with Audiobooks (Audible) now. I cannot reproduce the issue with Music or Radio anymore.

The Websocket is not closed as it was before, the state in Developer Tools is updating and the automations run as expected.

Thank you.

**Comment by genebean** [comment]
Working good so far

**Comment by genebean** [comment]
I don't think audible is breaking mine fwiw. @alandtse I am happy to share the activities.json with you but don't really want to post it publicly... any preference on how I get it to you?

**Comment by iWPL** [comment]
`Resume` does not trigger the error (nor does `resume forever`!).  
When I have some examples in the activities log and HA log I will upload something. It seems Amazon only make the last 50 utterances available and most of these when I checked are ‘resume’ which did not trigger the error.  

If it is possible to post this data privately/directly to you, I agree with @genebean, that would be preferable.  It takes ages to sanitise the files! (Especially when I’m not sure what many of the random character strings represent!)

Many thanks

**Comment by iWPL** [comment]
Evening update:  
The keywords `play`, `resume` or `continue` do not trigger the error.  
The keyword `read` does seem to trigger the error regardless of what I put after it (e.g. `read my book` or `read [name of the book]` or just `read`.   
My lay person observation: If a **book** is `read` or `play`ed it always seems to generate an extra object which has a null 'Description' but a 'domainAttributes' value instead (note: only `read`ing the book generates the error).
Music by comparison does not do this and combines the 'Description' and 'domainAttributes' name/key pair in the same object.

**Comment by genebean** [comment]
Are you having it read kindle books (aka narrated by Alexa) or play audible books? I ask because we always tell the echo to “play” a book from audible but read ones that are nit audio books to start with? Also, does “read me a story” or “tell me a story” also cause the problem?

**Comment by iWPL** [comment]
Hi,

We are only listening to books from Audible, e.g. the Harry Potter series as read by Stephen Fry (not Jim Dale ;o).

You make an interesting point about reading vs playing Audible books. Audio generated on the fly verses pre-recorded. Although at the end of the day, should it matter who is 'reading' it? A computer algorithm or a professional narrator?

`read me a story` does trigger the error and plays the last audiobook that was playing.  
`tell me a story` does not trigger the error but asks whether we want to listen to a story from Alexa (The Potion) or Audible (an extract from Revolting Rhymes by Roald Dahl). A seemingly random selection from Amazon's catalogue.

I noted down the times of this evenings errors and compared them all to the Amazon Activities to see what Alexa was being asked at the time of the errors. I've attached the summary.  
[Todays error summary.xlsx](https://github.com/custom-components/alexa_media_player/files/6087052/Todays.error.summary.xlsx)
I appreciate this is somewhat less useful than the actual logs but shows a trend of sorts. Two strikes each time we ask Alexa to read something and one when it appears to be doing a scheduled refresh every 5 minutes.

**Comment by alandtse** [comment]
Thanks for the help. It was the null description. New build should resolve it and also should populate something in the summary.
