### ISSUE TITLE
Can't find Alexa Media in HACS

### ISSUE THREAD

**Issue by bturrie** [custom-components/alexa_media_player#1200]
**Describe the bug**
A clear and concise description of what the bug is. I uninstalled Alexa Media following the Wiki instructions. I did this to get rid of daily requests to re-authorize. When I went to HACS to reinstall it, I could not find the integration using search.

**To Reproduce**
1. Go to 'HACS'
2
2. Click on 'Integrations then Search for media'

**Expected behavior**
Alexa Media should appear in the list of integrations it does not. A search for Alexa snows no matches.

**Screenshots**

**System details**
 - Home-assistant (version): 
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: 

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by alandtse** [comment]
This is a HACS issue. Please report it there.
