### ISSUE TITLE
Captcha picture

### ISSUE THREAD

**Issue by Wat3rh3ad** [custom-components/alexa_media_player#1201]
The captcha picture is not showing up at all.
I have tried to restart the server and restart the app many times with no luck.
Thanks for all the hard work you put in to this wonderful project. 
                            Wat3rh3ad

**Comment by bjornstevens** [comment]
I have the exact same issue, what did you do to fix it?

**Comment by bjornstevens** [comment]
Never mind, a quick restart of HA seemed to fix it for me. 
Do note all the duplicates of this though lol
https://github.com/custom-components/alexa_media_player/issues/1188
