### ISSUE TITLE
Temperature sensor

### ISSUE THREAD

**Issue by Tonylolo** [custom-components/alexa_media_player#1202]
Hi

Is it possible to have value of temperature sensor from amazon device? Dot and dot plus.

Instead of a weather station, for interior of house it's a good alternative!

Thank you for development.

**Comment by alandtse** [comment]
Yes, dupe of #197 . Likely not to do it though since it would require polling the sensor.

**Comment by GTunney** [comment]
I've just updated my alexa media player, I have 2 4th gen echos, the temperature sensor is showing for one but the other one isn't.

Any suggestions as to why it's only added the entity for one device?

**Comment by Tonylolo** [comment]
> I've just updated my alexa media player, I have 2 4th gen echos, the temperature sensor is showing for one but the other one isn't.
> 
> 
> 
> Any suggestions as to why it's only added the entity for one device?

Hi

How do you have this in HA ?
