### ISSUE TITLE
BUG: error indicates auth process using IP not host name to do SSL verfiication

### ISSUE THREAD

**Issue by scyto** [custom-components/alexa_media_player#1203]
**Describe the bug & steps to repro** 

I setup integration via hacs.
Added integration in integrations panel
in the config i added my amazon username, password and external accessible hostname for home assistant (e.g. https://myname.mydomain.com  (this uses a wildcard cert issues by comodo and that is trusted by amazon)
was proxied  ~~redirected~~ to amazon
authenticated with amazon
was redirected back to https://[myextenraldnsname]/auth/alexamedia/proxy/ap/signin
then got this:
```
https://<internalip>/auth/foomedia/proxy/ap/signin/<redacted>; please retry: Cannot connect to host <internalip>:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '<internalip>'. (_ssl.c:1125)")] 
```
it needs to be using a host name, not the IP address..... or the SSL verification will never work.

**System details**
 - Home-assistant (version): `core-2021.3.2` `supervisor-2021.03.4`
 - Hassio (Yes): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media `v3.8.2`
 - alexapy `1.24.2`
 - Amazon [2FA is disabled] (using new proxy method)

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by scyto** [comment]
logs up next, needed to file and address something at work :-)

**Comment by scyto** [comment]
@alandtse thanks i am using config option 4.i here https://github.com/custom-components/alexa_media_player/wiki/Configuration#configure-ha - it clearly states one logs on using their UI, i am not using legacy method.

The IP address is my internal IP associated with https://internalname.domain.com; for the integration when prompted for URL i used https://externalname.domain.com

I installed alexapy manually via console provided by the community SSH/terminal add-on,

**Comment by scyto** [comment]
for further information this is what i fill out and it redirects me to amazon, where i auth, and then the redirect back to HA is the issue

![image](https://user-images.githubusercontent.com/11369180/110517669-002da680-80c0-11eb-91f0-60746f3fd178.png)

**Comment by alandtse** [comment]
Sorry, those aren't logs. The template had the instructions for enabling the logger component which enables the homeassistant.log. Please remember to scrub. You also need to provide me the very first proxy url.

`https://ha_external/auth/alexamedia/proxy?config_flow_id=44472f79e2b74104895838563b3b1852&callback_url=https://ha_external/auth/alexamedia/callback?flow_id%3D44472f79e2b74104895838563b3b1852`

**Comment by scyto** [comment]
that's where my `/config/home-assistant.log` file ends, at 'cookies:' not sure what to do to get you non-truncated?

this would seem to be one indicator of the issue from the logs - note it has the IP address in it? (this is line 12)
```
2021-03-09 11:51:10 DEBUG (MainThread) [authcaptureproxy.auth_capture_proxy] Received get: https://192.168.1.63/auth/alexamedia/proxy?config_flow_id=963167ba24de4e2b98714e297a99db62&callback_url=https://ha.REDACTED.com/auth/alexamedia/callback?flow_id%3D963167ba24de4e2b98714e297a99db62

```

**Comment by scyto** [comment]
is this better? i enabled all logging components (i turned off the previous because you said you didn't want those 4 files i sent).
[halog.txt](https://github.com/custom-components/alexa_media_player/files/6111238/halog.txt)

**Comment by alandtse** [comment]
Yes, the lines mentioning received get and post to the ip indicates the HA webserver is getting a get or post request targeting the IP address and not the domain. Can you please confirm the url in your browser has the domain instead of the ip? Do you have a proxy between you and the HA server that is changing the request to the ip?

Also, please remove the configuration.yaml entry for purposes of testing.

I may have a fix for this situation but you would need to install a custom version of authcaptureproxy. Would you be comfortable installing it?

**Comment by alandtse** [comment]
As an update, you can `pip install authcaptureproxy==0.7.0` and it might resolve this.

**Comment by scyto** [comment]
> As an update, you can `pip install authcaptureproxy==0.7.0` and it might resolve this.

yes that change fixed the IP address bug, do i need to fix these dependency issues too?

![image](https://user-images.githubusercontent.com/11369180/111216797-17720580-8592-11eb-83f4-b837d63dbe4e.png)

**Comment by alandtse** [comment]
No. But I'll leave this open until I propagate the fix.

**Comment by scyto** [comment]
oh and to answer your earlier question, there was no other proxy in my network and yes the URL in the browser had names and not ip.
