### ISSUE TITLE
Captcha not visibile: expire too quickly

### ISSUE THREAD

**Issue by chemelli74** [custom-components/alexa_media_player#1214]
**Describe the bug**
I was asked for relogin (after many weeks) and this time I was asked to enter the code from captcha, but the image is not visible.
I restarted HA in the hope to get a new one, but still nothing.

If I click on the broken image I get the response below: expired.

**To Reproduce**
1. Follow relogin request

**Expected behavior**
Would be possible to add a button to request a new one ?

**Screenshots**
![image](https://user-images.githubusercontent.com/57354320/111028940-3342a380-83fa-11eb-89d3-f48aa719596d.png)

**System details**
 - Home-assistant (version): 2021.3.3
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): v3.8.4
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

![image](https://user-images.githubusercontent.com/57354320/111028964-5a997080-83fa-11eb-9b2d-934ab5f6e0d2.png)

**Comment by jpdavidson** [comment]
Same problem, if I click on the invalid image, it just takes me to a web page displaying the XML page in the above report

**Comment by daveabbott007** [comment]
same here - Started 2 days ago for me.

**Comment by oudoulj** [comment]
Same here. Broke 10 days ago approx over here.
If you enter a random captcha (because of broken image) and submit, it'll fail but a captcha image will show up.
Even if you type that visible captcha, it'll fail as well though... #neverendingloop
Many people are facing this issue apparently.
Looking forward for a viable solution :|

**Comment by alandtse** [comment]
Submit anything. I can't control the image timeout without removing the automatic login attempt.

**Comment by chemelli74** [comment]
Thx for the suggestion, I fixed the issue.

Steps:

- send a casual code (as you don't see the image)
- send the right code for 3 times on 3 different images
- asked to enter 2FA code
- auth flow successfully completed

Hope it helps all the other with same issue.

Simone

**Comment by chemelli74** [comment]
@alandtse what if you add a line saying something like:

**_"If you don't see the image, submit a causal code to allow a reload of a new one"_**


And, if possible, could you consider hide the second line ? I'm referring to this one:

![image](https://user-images.githubusercontent.com/57354320/111042912-eda8c980-843f-11eb-93a6-1e1be004ea2b.png)

Is confusing and no one should need to change it.

Thx as always for your great  work,

Simone

**Comment by alandtse** [comment]
That's because it wasn't translated. I'll remove the key but someone needs to translate that. If you'd like to, please check the wiki for how to sign up.

**Comment by chemelli74** [comment]
> That's because it wasn't translated. I'll remove the key but someone needs to translate that. If you'd like to, please check the wiki for how to sign up.

If not translated, should EN be the fall back ?
Going to translate for IT right now.

Simone

**Comment by chemelli74** [comment]
All missing and unverified translations updated.

Only one missing because I cannot edit: [config::step::user::description ](https://app.lokalise.com/project/465185555eee18dd537ca6.39714580/?view=single&reference_lang_id=640&single_lang_id=734&filter=builtin_4)

Simone

**Comment by alandtse** [comment]
Thanks. I'll check on that one. Next release should have the new translations.

**Comment by alandtse** [comment]
Odd, it looks like a problem with lokalise as it just replaces the old version regardless of what you enter.

**Comment by alandtse** [comment]
Ok I think I changed it. Please confirm.

**Comment by chemelli74** [comment]
> Ok I think I changed it. Please confirm.

Great, that's fine!
Just a small typo already fixed.

Simone

**Comment by oudoulj** [comment]
> Hi, I notice this is closed but I have same problem. Its asking me to reauthenticate but there is no image displayed. Clicking the image takes me to an xml saying the capcha has already expired. So is this fixed or not fixed?

I ended up uninstalling the integration and removing the corresponding line in the configuration.yaml
I then successfully reinstalled the integration from scratch.
