### ISSUE TITLE
SKILL ID , where to find it?

### ISSUE THREAD

**Issue by Vendo232** [custom-components/alexa_media_player#1224]
regarding this comment "You can find skill ID's by inspecting the JSON when navigating to https://alexa.amazon.com and clicking on skills."

could you help me with little bit more information where to find the ID? spent 2h inspecting every Amazon page and could not find it.

**Comment by alandtse** [comment]
For help like this please use the [forum](https://community.home-assistant.io/t/echo-devices-alexa-as-media-player-testers-needed/58639/4946) as there is more traffic. I'll leave this open for a week before closing in case someone comes by to answer this.
