### ISSUE TITLE
Sensor to tell when Alexa Media requires reauthentication

### ISSUE THREAD

**Issue by scstraus** [custom-components/alexa_media_player#1225]
**Is your feature request related to a problem? Please describe.**
As the in-app notifications are always filled with irrelevant junk, I often miss the notification that alexa media needs reauthentication. I'd like to have a sensor that tells me when the authentication is down so that I can send a useful notification. 

**Describe the solution you'd like**
A normal hass sensor to be exposed to show authentication state of alexa media player.

**Describe alternatives you've considered**
Examined existing sensors to see if they would change state when authentication wasn't current. They didn't.

**Comment by alandtse** [comment]
There's already an event to capture. https://github.com/custom-components/alexa_media_player/wiki/Configuration%3A-Events#events and an example automation. https://github.com/custom-components/alexa_media_player/wiki/Examples%3A-Automation#notification-when-amazon-login-required

It doesn't make sense to use a sensor for this.

**Comment by scstraus** [comment]
Fair enough, thanks, that'll do the job.
