### ISSUE TITLE
Is there a way to control volume locally?

### ISSUE THREAD

**Issue by mnayef95** [custom-components/alexa_media_player#1226]
I'm using a lot of volume levels throughout the day, night, morning, evening, etc..., and I have automation that works based on group volume level, the issue is that when I change the volume either from a home assistant or Alexa app, it takes much time to be reflected on a home assistant, sometimes it takes more than 2 minutes so the automation, in this case, will be meaningless, also the volume takes more than 10 seconds to be reflected on Alexa devices and this is because of the slowness of the internet in my home.

**Describe the solution you'd like**
I would like to control and update the volume level locally, is that feature available from amazon?

**Describe alternatives you've considered**
If there this feature is not available by Amazon, so is there any way to update home assistant locally without the need to wait for the next polling interval?

for example, if I changed the volume level to 10% from home assistant so the value will be reflected instantly to the home assistant because it's done by the home assistant so no need to wait for the next interval to update home assistant values, is that make sense?

Now if I change the volume by home assistant then I checked this template `{{ state_attr('media_player.mohamed_s_room', 'volume_level') }}` it's will return the old volume level not the new one, it's should return the new one because it's done by home assistant not alexa app

**Comment by alandtse** [comment]
No. There is no local control for Alexa devices. You have to go to Amazon's cloud. However, the volume should be updating as soon as Amazon reports the value has changed. Obviously if you're doing it outside of the component, we're reliant on Amazon reporting it to the component. This can be seen by looking at the websocket logs. You can enable the logs and then change the volume on the device. As soon as the websocket is seen, it will update the HA state.
