### ISSUE TITLE
[FR]: Disable/Cancel wake-up call

### ISSUE THREAD

**Issue by chemelli74** [custom-components/alexa_media_player#1232]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**
I would like to cancel a wakeup call based on `binary_sensor.workday_sensor`

**Describe the solution you'd like**
A service call to cancel a wakeup call for the day after if the day is not a workday

**Describe alternatives you've considered**
Do it manually on Alexa App or by voice command

**Additional context**

**Comment by alandtse** [comment]
Can this be done by the app or by voice? Can it be done with a custom command?

**Comment by chemelli74** [comment]
> Can this be done by the app or by voice? Can it be done with a custom command?

More or less: what I do now it disable the wake up call and the day after enable it back.
So I was thinking about something similar.

Simone

**Comment by alandtse** [comment]
I mean can't you already do this using custom commands?

**Comment by chemelli74** [comment]
Maybe, but I cannot find my way with those.

Can you give me a sample ?

Simone

**Comment by alandtse** [comment]
Please ask the forum.

**Comment by alandtse** [comment]
If it turns out we can't do this with custom commands in and automation, then we can reopen

**Comment by chemelli74** [comment]
> If it turns out we can't do this with custom commands in and automation, then we can reopen

Do you mind considering adding this feature ?
I think #1238 may be more appropriate than reopening this one, but obviously I leave this to you.

Thx a lot in advance!

Simone
