### ISSUE TITLE
Unable to install integration due to missing module (typing_extensions)

### ISSUE THREAD

**Issue by Saggerus** [custom-components/alexa_media_player#1233]
**Describe the bug**
Installed integration quite a long time ago and had been working fine.  Then got a notification asking me to configure Alexa_Media.  When I tried to do this I had a similar issue to #1180 where it would loop when trying to add my details in the Integration page.  As I was using a really old version thought it might be that I needed to update so deleted the custom_components\alexa_media folder and cloned the latest release and copied the alexa_media folder from that into custom_components.  When I then went into the Integrations page in HA and tried to add it from the list it paused for a while with a message saying 'please wait while the integration is installed' before then returning to the list of available integrations and Alexa_media was not installed.  Checked the logs and it says  "Error occurred loading configuration flow for integration alexa_media: No module named 'typing_extensions'"  Have installed the module manually via pip and tried to install Alexa_media again but still get the same error

**To Reproduce**
1. Clone latest release of alexa_media from github
2. copy alexa_media folder from clone to custom_components
3. attempt to install Alexa Media Player integration from configuration/integrations/+ page
4. integration attempts to install but then returns to list of available integrations with no message displayed
5. check log & see error

**Expected behavior**
When trying to install the integration expected configuration screen for the integration to appear to allow me to enter my amazon credentials etc.  this does not happen.

**Screenshots**
NA

**System details**
 - Home-assistant (version): 0.110.7 
 - Hassio (Yes/No): No.
 - alexa_media  (version from `const.py` or HA startup): 3.8.5
 - alexapy (version from `pip show alexapy` or HA startup): 0.1.0
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: y

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.
2021-04-06 11:25:54 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-04-06 11:26:07 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration alexa_media: No module named 'typing_extensions'

**Additional context**

**Comment by alandtse** [comment]
Use HACS so it will actually install dependencies. Otherwise, just pip install everything in the manifest.json.
