### ISSUE TITLE
Exclude not working correctly on domains

### ISSUE THREAD

**Issue by thorrrr** [custom-components/alexa_media_player#1234]
HI Guys

Here is my yaml 
alexa:
  smart_home:    
    filter:
      exclude_domains:
        - binary_sensor
        - switch
      include_domains:
        - light

From reading your instruction and testing i went into Alexa app and removed all my  binary_sensor entries 35 of them plus many duplicates this keeps adding. I had 60 items left that i wanted when i re scan i went to 189 !!!!
The integration added switch, binary sensor, IKEA bulbs i have no IKEA hub or enable IKEA integration.
I would like it to work correctly i do not want to type 129 item to an exclude list when many are domains
![Laptop Screenshot- 210](https://user-images.githubusercontent.com/8170673/113701852-97dae080-96d0-11eb-9ebf-db7cf179825f.png)

**Comment by alandtse** [comment]
This is not the Alexa integration with HA. https://www.home-assistant.io/integrations/alexa/ Please ask at the HA forums.
