### ISSUE TITLE
Alexa Media Player not showing up in integrations after install through HACS

### ISSUE THREAD

**Issue by mbriney** [custom-components/alexa_media_player#1235]
**Describe the bug**
When I install Alexa Media Player through HACS the plugin installs with no issue, I'm able to restart without any issue and I can confirm in the HACS panel that the component installed.  However, when I go to integrations to add it Alexa Media Player does not show up in the listing.

**To Reproduce**
1. Go to HACS
2. Install Alexa Media Center
3. Restart
4. Go to Configuration > Integrations
5. Add Integration
6. Search for "Alexa"

**Expected behavior**
I was expecting to see it in the listing and then follow the steps in the repository readme to link it to my account.

**System details**
 - Home-assistant (version): core-2021.4.0
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).  Yes
 - alexa_media: 3.8.5
 - alexapy (version from `pip show alexapy` or HA startup): Not found
 - Amazon [2FA is enabled]: Yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

2021-04-08 01:22:00 WARNING (MainThread) [homeassistant.loader] You are using a custom integration alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
.

**Comment by wzwick** [comment]
Have you tried clearing your browser cache?
I read it as a work around on a different component - but it apples to lots of them.

**Comment by mbriney** [comment]
It took 4 restarts and 12 hours of sitting but it finally showed up.
