### ISSUE TITLE
Warnings for undefined variables in Templates

### ISSUE THREAD

**Issue by denniswham** [custom-components/alexa_media_player#1236]
**Describe the bug**
Warnings for undefined variables in Templates

**To Reproduce**
1. Default settings foe the logger integration
2. Restart Home Assistant
2. Check the log

**Expected behavior**
No warnings

**Screenshots**
![image](https://user-images.githubusercontent.com/43110823/114006709-f636c900-9860-11eb-9b3a-4f7803800269.png)

**System details**
 - Home-assistant (version): Home Assistant 2021.4.0
 - Hassio (Yes): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup): 3.8.5
 - alexapy (version from `pip show alexapy` or HA startup): 1.24.5
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: Y

**Logs**
```
Logger: homeassistant.helpers.template
Source: helpers/template.py:1335
First occurred: 11:45:17 AM (8 occurrences)
Last logged: 11:45:20 AM

Template variable warning: No first item, sequence was empty. when rendering '{{ expand(states.media_player.living_room,states.media_player.master_bedroom,states.media_player.lucas_room,states.media_player.timo_s_room,states.media_player.emilie_s_room,states.media_player.living_room_fire_tv_stick,states.media_player.master_bedroom_fire_tv_stick) | selectattr('attributes.last_called','eq',True) | map(attribute='entity_id') | first }}'

```

**Additional context**
This warning was mentioned in the release notes for Home Assistant 2021.4.0
https://www.home-assistant.io/blog#warnings-for-undefined-variables-in-templates

**Comment by alandtse** [comment]
Thanks. Please ask on the forums since there's more traffic there. This is not a technical issue with AMP but with template variable use in HA. I'll leave this up for 1 week in case someone has a fix.

**Comment by denniswham** [comment]
You're right, in my case it was the configuration of the Last Alexa Sensor. The sensor need to be given a default value by adding " | default" to the template. I've updated this page. https://github.com/custom-components/alexa_media_player/wiki/Examples%3A-Automation#last-alexa-sensor

No issue with the AMP, hence closing this item.

**Comment by alandtse** [comment]
Thanks for fixing the wiki!
