### ISSUE TITLE
Support lights(and other devices?) integrated into Alexa

### ISSUE THREAD

**Issue by blm126** [custom-components/alexa_media_player#1237]
I have several zigbee lights and motion sensors already integrated with my Echo. From the Alexa app I can control them and view the state of all of them. I would like for Alexa Media Player to expose them to Home Assistant.

I have already figured out the appropriate network requests and I'm certain that at least basic control over lights is possible. I would be willing to take a shot at the development work on this if the project is interested in the idea.

**Is your feature request related to a problem? Please describe.**
This isn't a problem, just a dream.

**Describe the solution you'd like**
I would like devices I have already integrated with Alexa to be added as entities to Home Assistant.

**Describe alternatives you've considered**
Integrating my lights directly into Home Assistant.

**Additional context**
I want this for a few reasons:
1. I don't want to buy a zigbee radio when my Echo already has one.
2. Alexa is completely solid. If my Home Assistant setup falls over, I lose advanced features but not basic control of my devices.
3. I can avoid setting up the smart home skill and still get voice control of my lights
4. I can run Home Assistant in the cloud

**Comment by alandtse** [comment]
I believe the official Alexa integration allows this. Have you checked? 

If it doesn't, the main issue is that to keep devices like this up to date, we'd have to poll the Alexa cloud. We try not to do that to avoid potentially overloading the Alexa account. If the information is exposed via websocket (enable alexapy.websocket logs) then it makes it easier to consider doing this. If you check the issues, we've had requests for the temperature sensor and for the Alexa switches. Obviously if you've found local API control, then I wouldn't have the same concerns.

If you did try to implement this, we should make it an option users have to enable. You'd have to first implement the API calls in [alexapy](https://gitlab.com/keatontaylor/alexapy) and then expose them up here in the custom integration.

**Comment by blm126** [comment]
The official Alexa integration does the opposite of what I'm trying to achieve. It can expose Home Assistant entities to Alexa. I want to expose Alexa entities to Home Assistant. 

I have checked the websocket interaction and there does not seem to be any message sent. This lines up with what the Alexa app shows as well. The device page in the app doesn't update until you leave it and come back.

It appears polling is the only option. Based on the code it looks like alexa media player polls either every 30 seconds or every 5 minutes depending on if websockets are working. That is fast enough for most use cases I want this for with Lights. I imagine that would be good enough for a temperature sensor as well.

The /api/phoenix/state POST call that gets this data appears to support batching. So, we are talking about one new call on the polling interval to support any number of added lights.

Has Amazon taken issue with polling in the past?

**Comment by alandtse** [comment]
No specific notice but we have seen 429s before. Since this is a reverse engineering of their API, we run the risk that if we get too high on their radar they can shut us out.

If it's a single pull to phoenix, then it may be getting pulled already during the check on the [guard state](https://gitlab.com/keatontaylor/alexapy/-/blob/dev/alexapy/alexaapi.py#L1325-1345). We pull that pretty frequently as it's on every known voice interaction ([based on websocket](https://github.com/custom-components/alexa_media_player/blob/dev/custom_components/alexa_media/alarm_control_panel.py#L199-L216)). It may make sense to generalize the data pull to get the other devices. People have in the past asked for [sensors of various things](https://github.com/custom-components/alexa_media_player/issues/1202) so it may make sense to address them too if it's the same endpoint.

The centralized polling is in the [data update coordinator](https://github.com/custom-components/alexa_media_player/blob/dev/custom_components/alexa_media/__init__.py#L315-L556) but people are getting [weird timeouts now](https://github.com/custom-components/alexa_media_player/issues/1213).

**Comment by blm126** [comment]
Yes, you get the data based on calls to phoenix state. It looks like just generalizing the existing call in alexapy is the way to go and that would avoid any new polling. I'm going to take a shot at this.

Here is my plan:

1. Add support in alexapy for getting a list of sensors (GET /api/phoenix)
2. Adjust alexapy's guard state call so it can batch in requests for arbitrary entity state
3. Add support in alexapy for controlling lights via PUT to /api/phoenix/state. Probably won't merge this with the guard state stuff since that would get confusing and batching seems much less useful here.
4. Create an "Include devices connected via Echo" setting in alexa media player. Off by default.

My plan is to limit this to only devices directly connected to an Echo either via zigbee or because they are part of the echo themselves(temperature sensor). That is all I have a setup to test and still seems useful in its own right.

**Comment by alandtse** [comment]
Seems reasonable. Yes, let's keep the commands separate but the data gathering can be generalized.  I think sharing update conditions of detected voice input still makes sense. I forgot if we have a general poll if the websocket isn't connected (but I think you saw it).

**Comment by blm126** [comment]
Just for historical reference in case anyone stumbles upon this: Lights and temperature sensors worked fairly well and I'm going to continue forward with that goal in my PR. I did give up on supporting motion sensors. I got it working and it was too slow to be useful without websockets. I removed it and moved on.

I also discovered as part of this that the Echo device is reporting all sorts of crazy sensors like "Dog Barking" and "Snoring". I think that is tied into all of the recent features in the Alexa app around sound detection. I did not bother to investigate further because it suffers from the exact same flaw as motion sensors. There is no websocket message so by the time home assistant notices the state your dog has probably stopped barking.

**Comment by alandtse** [comment]
Perhaps in the future we can present it as an "activity sensor". Without websocket it will be stale but perhaps people can use it as a sensor for occupancy detection.

**Comment by jriker1** [comment]
Sounds like this has been implemented.  So when I turn on "Include devices connected via Echo" how do I see the temperature sensor one of my Echo devices has?  I do not see any new entities even after reboot.  Do I need to do something additional with Amazon?

**Comment by blm126** [comment]
No, nothing additional should be required. If it doesn't appear, I would open a new issue with logs from alexapy. I'll need that to see what is different about your device.

**Comment by alandtse** [comment]
I'd suggest opening a new issue as the template will provide info on how to generate logs that @blm126 will need to help.
