### ISSUE TITLE
Switches for alarms

### ISSUE THREAD

**Issue by broyuken** [custom-components/alexa_media_player#1238]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I’d like to be able to turn on/off existing alarms on my Alexa devices through HA. 

**Describe alternatives you've considered**
Use custom commands, but there’s no way to track the alarms state. 

**Additional context**

**Comment by alandtse** [comment]
Don't custom commands let you do this?

**Comment by broyuken** [comment]
I’m sure you would be able to actually turn them off/on yes but not be able to see which ones are already set. It would make things significantly easier if you could somehow expose each of these alarms as switches or something.

**Comment by alandtse** [comment]
There are potentially hundreds of alarms because Amazon creates them and doesn't necessarily reuse them. We wouldn't expose them by default because people already complain about how many entities this creates.

However you can parse it out of the next alarm sensor using a template. There are posts on the forum with how to get them all out.

**Comment by alandtse** [comment]
I'll leave this open in case someone wants to implement it. Assuming there's a lot of people asking for it despite the fact there's the downside of multiple sensors, then maybe it'll get implemented.

**Comment by blm126** [comment]
Add me to the list of people who want something like this. 

However, my thinking is that it doesn't make sense to add a sensor automatically for every alarm and having both a sensor and switch for each alarm just doubles the mass of entities that would generate.  My thought is that what is really wanted is just a specific sensor added for some particular recurring alarm plus a little more state and services.

Given that, here is my suggestion:

1. Add a status attribute to every alarm sensor. It could be "ON", "OFF", "SNOOZED", etc.
2. Add a turn on/turn off services to alarm sensors. It is probably possible to get the HA generic turn on/off service to cover this?
2. Add a new option to the Option flow: "Create multiple alarm sensors". Still thinking on the label here.
3. Add a way to the yaml to configure the alarm sensors you want. This can filter on recurring pattern or id. This works like the existing sensor. If you have multiple alarms that match the given filter, the next one is used.
4. By default, if the option is on but the yaml isn't configured add 2 new entities: "Next Daily Alarm" and "Next Weekday Alarm".

I think that would strike a decent balance. If this plan seems like it would work for others, I can work on coding this up.

**Comment by alandtse** [comment]
My main concern is use of the yaml. That should be treated as deprecated. If you can figure out a good way to display it in the option flow then that may be good. Maybe they have a selection picker?

So you're basically suggesting allowing switches for recurring alarms? That may be make it manageable.

**Comment by blm126** [comment]
I investigated the option flow some more. Avoiding the yaml isn't so bad technically, but the UX is pretty poor. You basically have to make a multiple step flow and one of the steps need to repeat for each alarm the user wants to configure. I threw that flow together real fast, and I don't think its viable. The repeating aspect of it was fairly confusing. 

So, instead, I'm thinking to just do the naive thing and add 1 checkbox labelled "Create a sensor for each Alarm". I think the "version" field is a possible answer to the deluge of entities. That increments every time the user messes with an alarm. I think I can come up with rules about "dead" alarms that were used very rarely and far in the past. They will just be automatically removed from HA. 

I'm going to experiment with that idea a bit.

**Comment by chemelli74** [comment]
I investigated in the community for custom commands, like suggested ([comment on issue #1232](https://github.com/custom-components/alexa_media_player/issues/1232#issuecomment-814232655)) but didn't get any useful hint.

I would like as well having a switch for each alarm and a service to create/modify/delete alarms.

Those that are not interested can always disable the entities or been offered a option in the `config_flow `to not create such switches.

Thx for considering the addition.

Simone

**Comment by chemelli74** [comment]
Please consider adding the switches; maybe disabled by default.

Thx,

Simone

**Comment by chemelli74** [comment]
@alandtse , any hope to get it implemented ? Thx in advance as always for your great work so far.

Simone

**Comment by alandtse** [comment]
I don't intend to do it, so hoping and pinging me won't change that. You're free to submit a PR.

**Comment by chemelli74** [comment]
> I don't intend to do it, so hoping and pinging me won't change that. You're free to submit a PR.

Sorry didn't want to be picky.
I read that you were "available" to add such functionality if custom commands didn't work.

Can you be so kind to point me to the right direction, so I can try understand the underground API and make a PR ?

Simone
