### ISSUE TITLE
Template variable warning on restart

### ISSUE THREAD

**Issue by stiltjack** [custom-components/alexa_media_player#1240]
After the update to 2021.4 I get the following on restart:

`Logger: homeassistant.helpers.template
Source: helpers/template.py:1335
First occurred: 12:10:07 (6 occurrences)
Last logged: 12:10:17

Template variable warning: No first item, sequence was empty. when rendering '{{ expand(states.group.echos) | selectattr('attributes.last_called','eq',True) | map(attribute='entity_id') | first }}'`

**Comment by alandtse** [comment]
You need to fix your template. Please ask on the forums.
