### ISSUE TITLE
notify.alexa_media blueprints compatibility 

### ISSUE THREAD

**Issue by krestes** [custom-components/alexa_media_player#1246]
**Describe the bug**
Using blueprints target selector add entity_id: to line under target: field and target is detected as being blank.

**To Reproduce**
Create blueprint to use the notify service

**Expected behavior**
target: to accept a different entity_id: format. The blueprint function has no option that I can find to flatten device list. 

**Screenshots**
None

**System details**
 - Home-assistant (core-2021.4.4): 
 - Hassio No
 - alexa_media  (3.8.6):
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: Yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by alandtse** [comment]
What blueprint are you using?

**Comment by krestes** [comment]
Garage door open TTS announcer/reminderAuthor: doughecka  Sent from Mail for Windows 10 From: Alan TseSent: Saturday, April 17, 2021 10:14 PMTo: custom-components/alexa_media_playerCc: krestes; AuthorSubject: Re: [custom-components/alexa_media_player] notify.alexa_media blueprints compatibility (#1246) What blueprint are you using?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
