### ISSUE TITLE
send image echo show 8 but black screen appears

### ISSUE THREAD

**Issue by maverik80** [custom-components/alexa_media_player#1248]
evening guys, i am making a script that sends a sound and i would like to implement even an image for a few seconds to my echo shoe 8, but the result is black screen for about 1/2 second and then it returns to its normal screen, the code I use is the following, where am I wrong?

    - service: media_player.play_media
      data:
        entity_id: media_player.echo_show_di_vincenzo
        media_content_id: "https://i.ibb.co/dttJQV6/dog.jpg"
        media_content_type: image

**Comment by alandtse** [comment]
Please fill out the template.

**Comment by maverik80** [comment]
> Si prega di compilare il modello.

  cane:
    sequence:
    - service: notify.alexa_media
      data_template:
        target: media_player.{{ states('input_select.alexa_rooms') }}
        data:
          type: tts
          method: speak
        message: >-
           <audio src="soundbank://soundlibrary/animals/amzn_sfx_dog_med_bark_2x_01"/>
    - service: media_player.play_media
      data:
        entity_id: media_player.echo_show_di_vincenzo
        media_content_id: "https://i.ibb.co/dttJQV6/dog.jpg"
        media_content_type: image

**Comment by maverik80** [comment]
> > Si prega di compilare il modello.
> 
> cane:
> sequenza:
> - service: notify.alexa_media
> data_template:
> target: media_player. {{states ('input_select.alexa_rooms')}}
> data:
> type: tts
> metodo: speak
> message:> -
> 
> - service: media_player.play_media
> data:
> entity_id: media_player.echo_show_di_vincenzo
> media_content_id: " https://i.ibb.co/dttJQV6/dog.jpg "
> media_content_type: immagine
