### ISSUE TITLE
Emulated hue lights discovered as lights

### ISSUE THREAD

**Issue by alandtse** [custom-components/alexa_media_player#1251]
**Describe the bug**
With the inclusion of light support, [emulated_hue](https://www.home-assistant.io/integrations/emulated_hue/) lights are being detected and exposed. They should be filtered out since they already should exist in HA.

**To Reproduce**
1. Enable emulated hue for any existing switch in HA
2. Enable lights in options
3. Lights will be added to HA

**Expected behavior**
Emulated hue lights should be ignored

**Screenshots**

**System details**
 - Home-assistant (version): 
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup): dev
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: 

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by alandtse** [comment]
They are exposed to Alexa as:

```json
"1": {
"state": {
"on": true,
"reachable": true,
"mode": "homeautomation"
},
"name": "Abode Updates",
"uniqueid": "00:61:47:df:43:92:f1:39-af",
"manufacturername": "Home Assistant",
"swversion": "123",
"type": "On/Off light",
"productname": "On/Off light",
"modelid": "HASS321"
},
```

**Comment by blm126** [comment]
I think the best way is to go the other way around. I have some actual hue bulbs connected directly to my Echo. They report a capability of "Alexa.EndpointHealth". So, if there if a manufacturerName of "Royal Philips Electronics" AND it doesn't have that capability, its an emulated device.

PR coming shortly.

**Comment by alandtse** [comment]
I think you're right. That's a consistent filter on what I'm seeing in my system.

**Comment by alandtse** [comment]
Please note to rebase on dev, I've fixed the style.
