### ISSUE TITLE
Refuses to see the URL for my HomeAssistant

### ISSUE THREAD

**Issue by tre4b** [custom-components/alexa_media_player#1255]
Not sure what is causing this.   I have tried multiple different addresses for the Home Assistant server however as soon as I click submit it comes up to tell me "Unable to connect to Home Assistant url.  Please check the internal Url under Configuration -> General"

All of the address I tried work perfectly well if I put them into a browser however AMP does not seem to see the server.   I am running my server using HTTPS and a local certificate,    Not seeing anything in the Docs that says not to do that though so I assume this is okay.   This seems to happen immediately so there is no login or anything else attempted 

![Screenshot 2021-04-18 183006](https://user-images.githubusercontent.com/37894577/115154702-20b02f80-a074-11eb-8d7c-9913dafc6c70.png)

**Comment by alandtse** [comment]
Please use the template.

**Comment by tre4b** [comment]
Where do you find the template?  I clicked the "Open issue" on the three ... menu option on the Hacs integration block.  That took me to a page (below) that said new issue which just gave a free text entry with no sign or mention of a template.

![Screenshot 2021-04-19 085131](https://user-images.githubusercontent.com/37894577/115200771-7aecd700-a0ec-11eb-8aba-7b5e40ab6e73.png)

Where do I need to go to find the template you need filled in?   Would be good if you could put that in the pinned announcements so that we know it is necessary.

**Comment by alandtse** [comment]
https://github.com/custom-components/alexa_media_player/issues/new/choose

**Comment by alandtse** [comment]
You were ignored it when you clicked new issue.

**Comment by vks007** [comment]
There is hardly any information you have provided in your issue for someone to help you. Anyway, i opened the same issue yday and found that i was missing the port number in front of the HA URL. Pl see here #1290
