### ISSUE TITLE
Device Activity command (Alexa Event Node) not producing output anymore

### ISSUE THREAD

**Issue by flashbackpa** [custom-components/alexa_media_player#1259]
**Describe the bug**
Since couple months (I'm afraid I can't be more precise), Device Activity is not working anymore, no output produced.

**To Reproduce**
1. Add Alexa Event node
2. Choose Device Activity command
3. Put at its output a debug node
4. Fire any command to Alexa
5. Check that no output is created from the Device Activity node

**Expected behavior**
When it worked, i was able to detect which alexa (I have a few) was activated filtering node output with Json**.deviceSerialNumber, that allowed me to reproduce any subsequent answer exactly on the same device that was queried.
This is not possible anymore.
Frustrating.

**System details**
 - Home-assistant: 
 - Hassio (Yes/No): YES
 - alexa_media  Latest from HACS
 - alexapy Latest from HACS
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: YES

**Logs**
Should I uninstall and reinstall alexa hacs integration to activate debug ?

**Comment by alandtse** [comment]
I don't know what "Alexa Event Node" means. Are you talking about the official component? If so, it's not related to this component.

**Comment by flashbackpa** [comment]
Pardon me @alandtse , I'm definitely in the wrong place :D

**Comment by alandtse** [comment]
Ok no prob. I'll close this then.
