### ISSUE TITLE
JSONDecodeerror resurfaced

### ISSUE THREAD

**Issue by pkishino** [custom-components/alexa_media_player#1260]
**Describe the bug**
Recently  I'm seeing the following error message popping up in the logs, it looks very similar to #587 but from a different package previously. No idea when and how this occurs

**To Reproduce**
not sure

**Expected behavior**
No error

**Screenshots**
none

**System details**
 - Home-assistant (version): 2014.4.6
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): 3.8.6
 - alexapy (version from `pip show alexapy` or HA startup):1.25.0
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered:  yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.
Have enabled debug logging and will update when I get more..

```
2021-04-24 13:22:48 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/alexa/state_report.py", line 98, in async_entity_state_listener
await async_send_changereport_message(
File "/usr/src/homeassistant/homeassistant/components/alexa/state_report.py", line 154, in async_send_changereport_message
response_json = json.loads(response_text)
File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Additional context**

**Comment by alandtse** [comment]
This is coming from the official component. It is not related to AMP. Please report on core.

**Comment by pkishino** [comment]
my bad, sorry :/

**Comment by alandtse** [comment]
No biggie, you're not the first. You can tell because the path is:
`components/alexa`

**Comment by pkishino** [comment]
submitted to home-assistant/core#49618
in case anyone else stumbles on this ;)
