### ISSUE TITLE
New prompt: Please hit confirm to begin login attempt.

### ISSUE THREAD

**Issue by DPAmes** [custom-components/alexa_media_player#1262]
I'm attempting the usual re-login after losing connection. I get the notification that alexa_media needs setup, click the link, but instead of the usual first prompt with a captcha, I get the new prompt above with a "Confirm" button. The button blinks briefly when clicked, but otherwise nothing else happens. After clicking it several times with no progress, I tried logging in to amazon.com in a browser window, and got the demand to reset my password. Don't know if that was triggered by my clicking "Confirm" several times unsuccessfully or not, but trying again after the password reset didn't help, same issue.

**Comment by alandtse** [comment]
Please use the template.
