### ISSUE TITLE
media_player. anywhere

### ISSUE THREAD

**Issue by maverik80** [custom-components/alexa_media_player#1263]
hello guys, i'm experimenting with a multi-room, i would like to play web radio or sounds to my echo dot and show but when i insert the entity that directly creates the app alexa media_player.multiroom this commands the volume but never plays anything, i'm banging my head for a week but I don't understand what I'm wrong, also by sending an image on echo show 8 3rd gen it is not seen but I only receive a black image attached I leave you my package that I am compiling for my children
[13RqFMYS.txt](https://github.com/custom-components/alexa_media_player/files/6375442/13RqFMYS.txt)

**Comment by alandtse** [comment]
Please fill out the template and do not create duplicate issues on existing issues you've already posted or we will close them.
