### ISSUE TITLE
Documentation for Notificaiton Configuration is incomplete

### ISSUE THREAD

**Issue by ms998** [custom-components/alexa_media_player#1269]
**Describe the bug**
https://github.com/custom-components/alexa_media_player/wiki/Configuration%3A-Notification-Component shows code examples for all sections EXCEPT "Echo Show Output Example"

Not structlty a bug but couldn't find anywhere to flag this.

**Comment by alandtse** [comment]
Thanks. If you know what the code is, feel free to add it in. Otherwise we'll see if anyone wants to document it.
