### ISSUE TITLE
Temperature Sensor only showing for 1 Echo device

### ISSUE THREAD

**Issue by GTunney** [custom-components/alexa_media_player#1275]
**Describe the bug**
Logging a ticket here as discussed with @blm126 on the HA forums.

I have 2 4th Gen echo devices with embedded temp sensor. Only 1 of this devices adds a temperature sensor entity on HA.

Rhys Bedroom Echo - Working fine
Master Bedroom Echo - No temp sensor

**Expected behavior**
Temperature Sensor entity to appear in entity lists under Master Bedroom Echo temperature Sensor.

**System details**
 - Home-assistant (version): Home Assistant 2021.4.6
 - Hassio (Yes/No):  No
 - alexa_media  (version from `const.py` or HA startup): 3.10.0
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled]: Yes

**Logs**
Debug logs which you asked for on HA forums, hopefully I have captured logs from the correct place.

https://pastebin.com/QzCizhW2

**Comment by blm126** [comment]
Relevant data pulled out and edited for clarity:
```
{
    'driverIdentity': {'namespace': 'AAA', 'identifier': 'SonarCloudService'},
    'manufacturerName': 'Amazon',
    'friendlyDescription': 'Amazon smart device',
    'friendlyName': 'REMOVED Bedroom Echo',
    'additionalApplianceDetails': {'additionalApplianceDetails': {}},
    'firmwareVersion': '0',
    'capabilities': [{
        'capabilityType': 'AVSInterfaceCapability',
        'type': 'AlexaInterface',
        'version': '3',
        'properties': {
            'supported': [{'name': 'temperature'}],
            'proactivelyReported': True,
            'retrievable': True,
            'readOnly': False
        },
        'interfaceName': 'Alexa.TemperatureSensor'
    }],
    'applianceTypes': ['OTHER', 'ALEXA_VOICE_ENABLED'],
    'connectedVia': 'REMOVED Bedroom Echo',
    'alexaDeviceIdentifierList': [{'dmsDeviceSerialNumber': 'REMOVED', 'dmsDeviceTypeId': 'REMOVED_1'}],
    'applianceDriverIdentity': {'namespace': 'AAA', 'identifier': 'SonarCloudService'},
}
```
and 
```
{
    'driverIdentity': {'namespace': 'AlexaBridge', 'identifier': 'REMOVED_2},
    'manufacturerName': 'Amazon Inc.',
    'friendlyDescription': 'Alexa App from Amazon Inc.',
    'friendlyName': 'Master Bedroom Echo',
    'firmwareVersion': '0',
    'capabilities': [ {
        'capabilityType': 'AVSInterfaceCapability',
        'type': 'AlexaInterface',
        'version': '3',
        'properties': {
            'supported': [{'name': 'temperature'}],
            'proactivelyReported': True,
            'retrievable': True,
            'readOnly': False
        },
        'interfaceName': 'Alexa.TemperatureSensor'
    }],
    'applianceTypes': ['OTHER', 'ALEXA_VOICE_ENABLED'],
    'connectedVia': '',
    'alexaDeviceIdentifierList': [{'dmsDeviceSerialNumber': 'REMOVED', 'dmsDeviceTypeId': 'REMOVED_3'}],
    'applianceDriverIdentity': {'namespace': 'AlexaBridge', 'identifier': 'REMOVED_4},
}
```

I suspect that Amazon does something strange when you have multiple Echos. I think the key is driverIdentity. It looks like if you have two 4th gen Echos, Alexa treats one of them as the primary. In this case it is the "REMOVED Bedroom Echo". The second Echo "Master Bedroom Echo" is reported as a cloud device instead. It gets no connectedVia and a different manufacturerName. That causes AMP to ignore it.

I'll work on a fix for this. There is more than enough markers in there to tell when we are talking about an Echo temperature sensor.

**Comment by GTunney** [comment]
> Relevant data pulled out and edited for clarity:
> 
> ```
> {
>     'driverIdentity': {'namespace': 'AAA', 'identifier': 'SonarCloudService'},
>     'manufacturerName': 'Amazon',
>     'friendlyDescription': 'Amazon smart device',
>     'friendlyName': 'REMOVED Bedroom Echo',
>     'additionalApplianceDetails': {'additionalApplianceDetails': {}},
>     'firmwareVersion': '0',
>     'capabilities': [{
>         'capabilityType': 'AVSInterfaceCapability',
>         'type': 'AlexaInterface',
>         'version': '3',
>         'properties': {
>             'supported': [{'name': 'temperature'}],
>             'proactivelyReported': True,
>             'retrievable': True,
>             'readOnly': False
>         },
>         'interfaceName': 'Alexa.TemperatureSensor'
>     }],
>     'applianceTypes': ['OTHER', 'ALEXA_VOICE_ENABLED'],
>     'connectedVia': 'REMOVED Bedroom Echo',
>     'alexaDeviceIdentifierList': [{'dmsDeviceSerialNumber': 'REMOVED', 'dmsDeviceTypeId': 'REMOVED_1'}],
>     'applianceDriverIdentity': {'namespace': 'AAA', 'identifier': 'SonarCloudService'},
> }
> ```
> 
> and
> 
> ```
> {
>     'driverIdentity': {'namespace': 'AlexaBridge', 'identifier': 'REMOVED_2},
>     'manufacturerName': 'Amazon Inc.',
>     'friendlyDescription': 'Alexa App from Amazon Inc.',
>     'friendlyName': 'Master Bedroom Echo',
>     'firmwareVersion': '0',
>     'capabilities': [ {
>         'capabilityType': 'AVSInterfaceCapability',
>         'type': 'AlexaInterface',
>         'version': '3',
>         'properties': {
>             'supported': [{'name': 'temperature'}],
>             'proactivelyReported': True,
>             'retrievable': True,
>             'readOnly': False
>         },
>         'interfaceName': 'Alexa.TemperatureSensor'
>     }],
>     'applianceTypes': ['OTHER', 'ALEXA_VOICE_ENABLED'],
>     'connectedVia': '',
>     'alexaDeviceIdentifierList': [{'dmsDeviceSerialNumber': 'REMOVED', 'dmsDeviceTypeId': 'REMOVED_3'}],
>     'applianceDriverIdentity': {'namespace': 'AlexaBridge', 'identifier': 'REMOVED_4},
> }
> ```
> 
> I suspect that Amazon does something strange when you have multiple Echos. I think the key is driverIdentity. It looks like if you have two 4th gen Echos, Alexa treats one of them as the primary. In this case it is the "REMOVED Bedroom Echo". The second Echo "Master Bedroom Echo" is reported as a cloud device instead. It gets no connectedVia and a different manufacturerName. That causes AMP to ignore it.
> 
> I'll work on a fix for this. There is more than enough markers in there to tell when we are talking about an Echo temperature sensor.

No probs at all, I've removed the pastebin for now, sorry for posting such a huge log, I wasn't sure exactly what you needed so just posted that entire snippet you asked for. If you need any fresh logs just let me know.

Interesting take on the issue, seems a strange way for Amazon to do things. Even so when the Master bedroom was the first 4th gen echo I purchased so you'd think that would be primary.

**Comment by keatontaylor** [comment]
Not to be slightly off topic on an open issue,  but I am curious. Is this an embedded temperature sensor in the echo devices that we can now get the state from or is this more connected zigbee devices/etc that can poll the state over the Alexa API?

**Comment by blm126** [comment]
This is the embedded temperature sensor that is part of the Echo 4th gen. From an API perspective though, Amazon treats those sensors like a pre-discovered smart home device.
