### ISSUE TITLE
Unable to add integration

### ISSUE THREAD

**Issue by HumanSkunk** [custom-components/alexa_media_player#1279]
**Describe the bug**
I am unable to add the integration as per the instructions. I have generated the 2FA entry on Amazon and entered it into the integration setup. I then get the confirmation code and add that back into the 2FA key on amazon and I get a notification and email that it has added the authenticator to my account.

I then get a pop up to complete on the website (which doesnt seem to show in the instructions and set up). following through the various screens seemingly signing in a second time, adding a captcha I get the option to authenticate with either mobiles I have added or the auth app. No matter what I click here I get an error. I have taken screens at each stage.

Closing the web browser window doesnt continue the Integration setup and it simply shows the screen to "this step requires you to visit an external website to be completed"

Clearly I am doing something wrong here but unsure what is happening. 

**To Reproduce**
Steps to reproduce the error are in the screenshots below:

**Expected behavior**
I expect after confirming the first screenshot below that the I get the pop up to configure the integration into my setup rather than being diverted to a webpage.

**Screenshots**

After adding the details in the integration set up I get the pop up to confirm the addition of the auth app to my amazon account which added successfully:
<img width="629" alt="Screenshot 2021-05-08 at 10 33 42" src="https://user-images.githubusercontent.com/62327733/117534578-e8a06a80-afe9-11eb-827a-72f535bca989.png">

After completing the 2FA Auth I get this screen:
<img width="502" alt="Screenshot 2021-05-08 at 10 12 35" src="https://user-images.githubusercontent.com/62327733/117534174-3d42e600-afe8-11eb-8144-340e186d37af.png">

clicking the open website loads this:
<img width="466" alt="Screenshot 2021-05-08 at 10 15 38" src="https://user-images.githubusercontent.com/62327733/117534219-619ec280-afe8-11eb-973b-dc54c360d66a.png">

Signing in the first time then generates the captcha
<img width="474" alt="Screenshot 2021-05-08 at 10 15 52" src="https://user-images.githubusercontent.com/62327733/117534233-6f544800-afe8-11eb-84bb-a2009ae8eaec.png">

Finally I get this option to authenticate with the sign in
<img width="454" alt="Screenshot 2021-05-08 at 10 16 09" src="https://user-images.githubusercontent.com/62327733/117534246-78ddb000-afe8-11eb-9b66-3a337ba71c66.png">

Ultimately leading to this error which takes me back to the sign in
<img width="474" alt="Screenshot 2021-05-08 at 10 16 21" src="https://user-images.githubusercontent.com/62327733/117534264-86933580-afe8-11eb-8acc-430beffad653.png">

**System details**
 - Home-assistant (version): 2021.4.2
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug). No - Installed using HassOS
 - alexa_media  (version from `const.py` or HA startup): erm latest?
 - alexapy (version from `pip show alexapy` or HA startup): as above
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered:  Yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.
I enabled the debug logging at the integration setup but no logs are seemingly added to my homeassistnt log file. I am happy to paste them if I know where they are written to.

**Additional context**

**Comment by alandtse** [comment]
Once you select the option sign in again. Do not close the window. It will then use the selection from earlier.

**Comment by alandtse** [comment]
And if you're using the built in OTP generator, select that option.

**Comment by HumanSkunk** [comment]
> And if you're using the built in OTP generator, select that option.

I will try again but before I just went around in a loop of whatever selection I made. I would type my username and password in again to be presented with the two step again.

**Comment by HumanSkunk** [comment]
> And if you're using the built in OTP generator, select that option.

So it worked. Just had to go around the complete loop like you said, now have all the devices in the household added.
