### ISSUE TITLE
Entità echo dot non rilevate

### ISSUE THREAD

**Issue by ClaudioBonaccurso** [custom-components/alexa_media_player#1280]
Buonasera,
Dalla versione 3.9 non vengono più riconosciuti in automatico i dispositivi Echo Dot. 
Provato a disinstallare tutto e reinstallare ma nulla.
Per far funzionare tutto correttamente sono dovuto tornare alla versione 3.8.6. 

Come posso risolvere
Grazie mille

**Comment by alandtse** [comment]
Please use English and the template.
