### ISSUE TITLE
Integration reload/HA restart is not deleting old devices

### ISSUE THREAD

**Issue by danielbrunt57** [custom-components/alexa_media_player#1281]
**Describe the bug**
I've discovered duplicate devices for my media groups.  I've deleted my paired speaker groups as well as my multi-area groups and then reloaded the integration but the entities deleted in Alexa persist in the integration.  I've also restarted HA and they still persist.

**To Reproduce**
Delete an item in Alexa, reload the integration and the item is not removed from the integration

**Expected behavior**
The integration device list should match what is currently in Alexa.  These devices should not exist:
```
Everywhere
Amazon
WHA A3C9PE6TNYLTCH
Alexa Media Player
-
Upstairs
Amazon
WHA A3C9PE6TNYLTCH
Alexa Media Player
-
Office
Amazon
WHA A3C9PE6TNYLTCH
Alexa Media Player
-
Main floor
Amazon
WHA A3C9PE6TNYLTCH
Alexa Media Player
-
Main floor
Amazon
WHA A3C9PE6TNYLTCH
Alexa Media Player
-
Bedroom
Amazon
WHA AP1F6KUH00XPV
Alexa Media Player
-
Living Room
Amazon
WHA AP1F6KUH00XPV
Alexa Media Player
-
Living Room
Amazon
WHA AP1F6KUH00XPV
Alexa Media Player
-
Office
Amazon
WHA AP1F6KUH00XPV
Alexa Media Player
-
Office
Amazon
WHA AP1F6KUH00XPV
Alexa Media Player
-
```

**Screenshots**
![image](https://user-images.githubusercontent.com/49846893/118010123-928e3880-b303-11eb-9e16-e72edad9d0a8.png)

**System details**
 - Home-assistant (version): core-2021.5.3
 - Hassio (Yes/No): Home Assistant OS 5.13
 - alexa_media  (version from `const.py` or HA startup): 3.10.1
 - alexapy (version from `pip show alexapy` or HA startup): 1.25.1
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: Y

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.
[alexa_media-Log.txt](https://github.com/custom-components/alexa_media_player/files/6467781/alexa_media-Log.txt)

**Additional context**

**Comment by alandtse** [comment]
Do they appear on your region specific devices page? https://alexa.amazon.com/api/devices-v2/device We report everything Amazon lists there. If you remove them from HA, do they reappear?

**Comment by danielbrunt57** [comment]
No, they are not in that list.
![image](https://user-images.githubusercontent.com/49846893/118041622-dabf5200-b327-11eb-98ad-9185a8d834fb.png)

I can only remove the entities that were associated to the device, but not the device itself.
![image](https://user-images.githubusercontent.com/49846893/118042135-8bc5ec80-b328-11eb-9d66-a57299aa4d4b.png)

**Comment by alandtse** [comment]
And it you remove them from HA?

**Comment by danielbrunt57** [comment]
If I remove the removeable **_entities_** from HA (which are the ones associated with the **_devices_** that do not exist in the region specific devices page and should not exist in HA), they do not come back.  The problem though is these _**devices**_ need to be removed from HA since they are not in Alexa's device list and I have no way to do that:

![image](https://user-images.githubusercontent.com/49846893/118043168-df850580-b329-11eb-86c3-c2afcbd13671.png)

**Comment by alandtse** [comment]
This is an issue with HA not having a mechanism to remove old devices. https://community.home-assistant.io/t/how-can-i-delete-devices-i-dont-want-in-ha/236080

The logs show we're not adding these devices anymore. The workaround in the thread is to remove the integration and readd, disable in the UI, or to manually delete the info from .storage.

There's nothing to change in the custom integration.

**Comment by danielbrunt57** [comment]
Okay, I've edited .storage/core.device_registry and removed the entries.  There should be a method in HA for Integrations to be able remove old devices.  The integration has a list of current devices.  It should be able to compare that to current registry entries and remove what should not be there in addition to being able to create new ones that do not exist...

**Comment by alandtse** [comment]
I'm seeing if there's a way for integrations to handle this, but this really should be a HA fix.

**Comment by alandtse** [comment]
Apparently they did add some [functionality](https://github.com/dermotduffy/hass-motioneye/blob/main/custom_components/motioneye/__init__.py#L380-L389).

**Comment by danielbrunt57** [comment]
Looks promising!  Thanks.

**Comment by danielbrunt57** [comment]
Thank you Alan!  Tested and works like a charm!!

**Comment by Stooovie** [comment]
I do have the weird phantom device (WHA A3C9PE6TNYLTCH with name "Living Room") in https://alexa.amazon.com/api/devices-v2/device. I had two of these in Alexa Media Player integration but removing the integ and re-adding with only including my actual devices fixed that. But the phantom devices are still popping up (and duplicating!) in Spotify and Alexa app - do you have any idea how to get rid of these? They are NOT anywhere to be found at alexa.amazon.com.

I have reached out to both Amazon and Spotify to absolutely no avail. 

Thanks!

**Comment by alandtse** [comment]
We don't populate that so can't help. There is an API to create and remove WHA groups but we don't implement it. There are command line scripts that do that may help you. I believe one of them is Alexa command.

**Comment by Stooovie** [comment]
Thank you, that's something to go on!

**Comment by Stooovie** [comment]
Wasn't able to remove the phantom device, even with the command line script. I just can't get rid of it no matter what, and it sometimes keeps duplicating in my Spotify device picker. This morning I had SEVEN bogus Living Room groups in Spotify app that actually play to two of my three Echo Dots (and the group isn't defined anywhere).

**Comment by sammyke007** [comment]
@Stooovie were you ever able to remove it somehow? I'm in the same boat for years...

**Comment by Stooovie** [comment]
It's been a long time but I think I had to create a new Amazon account.

**Comment by danielbrunt57** [comment]
Did you perhaps removing LL the devices that **_used_** to be in that group and re-adding them back to Amazon?  That might clear the phantom group as I suspect the devices' group membership(s) might be store in the devices. ???

**Comment by Stooovie** [comment]
I tried a lot of things, including Amazon support, no dice.

**Comment by sammyke007** [comment]
I was chatting with support almost 1 hour today to explain the issue... They even asked my router type and model... It's escalated to tech support, but I think I can guess the outcome. The WHA speaker group is not in the Alexa app, but it's still visible at [https://alexa.amazon.co.uk/api/devices-v2/device](https://alexa.amazon.co.uk/api/devices-v2/device) as device 0:


device |  
-- | --
0 |  
accountName | "Downstairs"
appDeviceList | []
associatedUnitIds | null
capabilities |  
0 | "AMAZON_MUSIC"
1 | "PANDORA"
2 | "APPLE_MUSIC"
3 | "TUNE_IN"
4 | "TIDAL"
5 | "VOLUME_SETTING"
6 | "DEEZER"
7 | "AUDIBLE"
8 | "SIRIUSXM"
9 | "MUSIC_SKILL"
10 | "I_HEART_RADIO"
11 | "SALMON"
12 | "MICROPHONE"
13 | "KINDLE_BOOKS"
14 | "AUDIO_PLAYER"
charging | null
clusterMembers | []
deviceAccountId | "A04598553VRCRFHJ95VZF"
deviceFamily | "WHA"
deviceOwnerCustomerId | "A2M47F8056T3ZL"
deviceType | "A3C9PE6TNYLTCH"
deviceTypeFriendlyName | null
essid | null
language | null
macAddress | null
online | false
parentClusters | []
postalCode | null
registrationId | null
remainingBatteryLevel | null
serialNumber | "23a259ae96344d4fa979520e1c9f61a4"
softwareVersion | "0"

Clustermembers is empty
