### ISSUE TITLE
Manifest version key

### ISSUE THREAD

**Issue by serlinGi** [custom-components/alexa_media_player#1284]
Hi, 
My HomeAssistant signed error 
ERROR (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'alexa_media'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'alexa_media'
Thank's for your job

**Comment by alandtse** [comment]
Please use the latest version. We've had a key for a long time.

**Comment by serlinGi** [comment]
really sorry, forgive me.  
I was convinced that I had installed the custom via HACS and instead I had configured it manually, so I have not received notifications of updates;  since everything has always worked perfectly, I did not realize I was left behind.  
thanks for your immediate feedback
