### ISSUE TITLE
Unable to connect to Home Assistant url. Please check the Internal Url under Configuration -> General

### ISSUE THREAD

**Issue by vks007** [custom-components/alexa_media_player#1290]
**Describe the bug**
As required by the plugin I do always have to reauthenticate at regular intervals. I use the preferred method of 2FA as described in the documentation. But this time, it just refused to login, so I reinstalled the plugin. Since then I am unable to login with the error "Unable to connect to Home Assistant url. Please check the Internal Url under Configuration -> General". 

**To Reproduce**
1. Configure the plugin using the steps in the documentation under section "Built-in 2FA App". 
2. Enter the details as shown in the screenshot below. 
3. Click on submit 

**Expected behavior**
I expect the plugin to login into my amazon account, instead it returns an error message

**Screenshots**
![IMG 468](https://user-images.githubusercontent.com/3463359/118142405-fad63a80-b427-11eb-80e8-57163cda894c.jpg)
![IMG 466 - Copy](https://user-images.githubusercontent.com/3463359/118142431-00338500-b428-11eb-8beb-d1753fb5c512.jpg)
![IMG 469](https://user-images.githubusercontent.com/3463359/118142449-04f83900-b428-11eb-8aba-242450080940.jpg)

**System details**
 - Home-assistant (version): core-2021.4.0
 - Hassio : Yes
 - alexa_media  (version from `const.py` or HA startup): v3.10.1
 - alexapy (version from `pip show alexapy` or HA startup): couldn't find this? I am on latest as on today
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.
Logs for 2 cases where once I tried with login proxy method and then without it, both result in the same error.
```
2021-05-13 19:24:52 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Creating new login
2021-05-13 19:24:52 DEBUG (MainThread) [custom_components.alexa_media.helpers] v****2@y*******m: Returning uuid {'uuid': 'ef578axxxxxxxxxxxxxxxxxxxxx1e9c641d', 'index': 0}
2021-05-13 19:24:53 DEBUG (MainThread) [alexapy.alexalogin] Login created for v****2@y*******m - amazon.in
2021-05-13 19:25:24 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Unable to connect to provided Home Assistant url: https://xxxxx.duckdns.org

2021-05-13 19:29:40 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Using existing login
2021-05-13 19:29:40 DEBUG (MainThread) [alexapy.alexalogin] Creating TOTP for U************************************************ILQ
2021-05-13 19:29:40 DEBUG (MainThread) [alexapy.alexalogin] Generating OTP XXXXXX
2021-05-13 19:30:12 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Unable to connect to provided Home Assistant url: https://xxxxxx.duckdns.org

```
**Additional context**
My internal URL and External URL are mentioned properly , I have included the screenshot of the same too. I have also tried to put in the internal URL on the alexa_media login screen as the error mentions it, it results in the same error.

**Comment by alandtse** [comment]
Is your internal IP address https? That would typically be wrong. Copy and paste what you've entered in your browser and confirm they take you to HA.

**Comment by vks007** [comment]
> Is your internal IP address https? That would typically be wrong. Copy and paste what you've entered in your browser and confirm they take you to HA.

Thanks for responding. Yes the https is the correct internal URL. Once we use duckdns it will not allow any http access to HA. 
This is what I have in the browser - I normally do work on the internal URL on my computer : https://192.168.X.XXX:8123/config/core

**Comment by vks007** [comment]
Also, can you explain on why does the error message mention internal URL while the logs print the error for the external URL? Just for the sake of it , I did try using the http URL too, it resulted in the same logs as above. The log clearly mentions the ext URL.

**Comment by alandtse** [comment]
You're right, we didn't update the text. It's using the external url now. The component will attempt to connect to the url you provide. If it cannot, it will get the message you are describing.  Can the HA server access HA from the external url you have provided?

As an example only, you mentioned https://192.168.X.XXX:8123. But you only filled out https://192.168.X.XXX. that would not be reachable since you omitted the port. Have you put in the proper port for your external URL?

**Comment by vks007** [comment]
Ah! sorry for that, yes you're right the port number was missing. The login screen pre-populates the URL from HA and does not have the port no. I also never paid attention to it. I have added that and the flow was able to proceed forward only to get stuck at sending the OTP stage. When I press Send OTP is results in an error 
`There was a problem
Enter your email or mobile phone number
Enter your password`

But then let me try debugging that further to see where's the issue, I will close this one as the URL issue isnt anymore.

**Comment by vks007** [comment]
Thanks for your help and patience !
