### ISSUE TITLE
Media player state stops reporting correctly after a day or so restart

### ISSUE THREAD

**Issue by 1liminal1** [custom-components/alexa_media_player#1292]
**Describe the bug**
media player state not being reported, when playing music from a Echo Show 8 state shows as standyby

**To Reproduce**
No errors per se, just wont report correct state. 

![image](https://user-images.githubusercontent.com/10505942/118194809-5c7cc000-b48d-11eb-89f9-911237cc431e.png)
Here is spotify state, you can see the device playing. 

But when I look at the media player itself it shows 

![image](https://user-images.githubusercontent.com/10505942/118194964-9e0d6b00-b48d-11eb-9e27-9df78d8631a1.png)

**Expected behavior**
Device should display correct state

**Screenshots**
Above

**System details**
 - Home-assistant (version): Home Assistant 2021.5.0
 - Hassio (Yes/No): HASOS
 - alexa_media  (version from `const.py` or HA startup): v3.10.0
 - alexapy (version from `pip show alexapy` or HA startup): I cant seem to show that, but its installed though HACS if that helps?

**Logs**
Ill need to generate them. Also this does work for a couple of days after a restart 

**Additional context**

**Comment by alandtse** [comment]
Please show logs when it's at this state. Most likely your websocket has disconnected and was unable to reconnect. At that point, it will only poll if you issue commands in HA that indicate the device should be checked. It will stop polling as soon as the device stops until the next HA command. This is to avoid hammering the Alexa api and getting you throttled or banned.

**Comment by 1liminal1** [comment]
Ok thanks, 

Im just waiting for it to stop working, could be a couple of days. 

Just to add, other things like announcements ect still work.

**Comment by alandtse** [comment]
Yah it's probably a websocket disconnect at that point. Reload the integration to reconnect it.

**Comment by 1liminal1** [comment]
Thanks mate!

It hasn't failed yet, so If we can just keep this ticket open for a while. Ill test the reload when it happens and see how it goes. 

Ill let you know

**Comment by officiallybob** [comment]
I actually think this might be an issue between Amazon & Spotify and we are just able to actually see it better through using this integration. I can get it to happen fairly consistently if I skip a couple of tracks on Spotify. The reason I don't think this is related to this integration is that once I stop seeing the proper track playing through the Home Assistant front end, if I go to the Alexa app, the Alexa app no longer reports my Echo as playing media. Just something to consider.

**Comment by hokiebrian** [comment]
I experience the same issue, I use Alexa for Apple Music and SiriusXM. The state of the media player will stay in standby after roughly 24 hours or so. If I manually update the entity, it will refresh everything and the media_* info is accurate, but it won't refresh on a track / station change unless I manually refresh the media_player entity using the homeassistant.update_entity service. A restart of HA fixes the issue.

**Comment by frifd82** [comment]
I have a similar problem, sometimes it happens that calling "alexa" for any command does not update the status of the entity. I use the "last_called" attribute (or anyway it updates after a reboot).

**Comment by alandtse** [comment]
Again, I've already explained the [cause](https://github.com/custom-components/alexa_media_player/issues/1292#issuecomment-841740053) and how to resolve. I'll close this out since there's not much I can do for people if Amazon disconnects their websocket.
