### ISSUE TITLE
Option to change include and exclude configuration with removing and readding

### ISSUE THREAD

**Issue by brywithawhy** [custom-components/alexa_media_player#1294]
This is more of a feature request, not an issue.
Can the integration have the option to modify the ignored devices later?
For example, I set up the integration ages ago and have now added a Fire Stick, Echo Auto, and Alexa enabled Fit Bit, which I don't want in Home Assistant. I had to manually edit the core.config_entries file to add those to the exclusions.
Can this option be added to the configure screen where you can change the seconds to wait to queue items together?

**Comment by alandtse** [comment]
Remove and readd.

**Comment by alandtse** [comment]
I'll leave this open if someone wants to implement it as an option.
