### ISSUE TITLE
Strange disconnection when more than one account is set up

### ISSUE THREAD

**Issue by somar05** [custom-components/alexa_media_player#1300]
**Describe the bug**
Something happens when two accounts are configured: the setup process is ok, but the second account lost the entities after some minutes. The entities dissapear from the "configuration - integration - Alexa media player - account". A restart (or integration reload) fix temporally the issue, but  finally it happens again in minutes. Not sure since which version is happening this. Delete integrations for both accounts just solve the problem temporally, and the same if delete the integration and readed from HACS

**To Reproduce**
1. Add 1st account as usual
2. Check entities
3. Add 2nd account
4. Check entities
5. Wait minutes
6. Suddenly, the entities from 2nd account are not available

**Expected behavior**
More that one account working fine as always

**Screenshots**
![image](https://user-images.githubusercontent.com/38601295/118391324-0007d500-b634-11eb-80c8-767c92673a5e.png)

**System details**
 - Home-assistant (version): 2021.5.4
 - Hassio (Yes/No): yes
 - alexa_media  (version from `const.py` or HA startup): V3.10.4
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). Yes

**Logs**
I'll provide if request

**Additional context**
Amazon domain: .es

EDIT: testing with v3.10.0 and no issues by now

**Comment by alandtse** [comment]
Please provide startup logs up to the removal.

**Comment by somar05** [comment]
Sure. Please, let me the issue open meanwhile I find some time to unistall, reinstall, enable debug, etc
