### ISSUE TITLE
If the Alexa Media addon is enabled then home assistant crashes within 24 hours

### ISSUE THREAD

**Issue by dw20155** [custom-components/alexa_media_player#1303]
Describe the bug
I have an issue where if the Alexa Media addon is enabled and working, after sometime (usually within 24 hours) the Raspberry Pi becomes unreachable. 

It does not respond even to ping or SSH and the only way to restore service is to unplug and re-plug USB-C power from the Pi after which everything works fine again.

I cant capture any logs when the issue occurs because I cant access HomeAssistant webpage at all and the logs are all cleared out when the Pi is rebooted.

If I disable the Alexa Media addon from integrations then the crashing goes away -- I also found that if the addon is enabled but not authenticated with Amazon then there is no crashing as well.

To Reproduce
1. Enable the Alexa Media Addon
2. Wait around around 24 hours (it is not exactly after 24 hours but usually it will happen sometime within that time period)
3. after sometime you wont be able to access the HomeAssistant UI at all and you wont be able to connect to the device running HA.

System details
Home-assistant (version): core-2021.5.3
Hassio (Yes/No): Yes running on rPi 4B plugged in by Ethernet
alexa_media (version from const.py or HA startup): 3.10.1 (installed from HACS)
alexapy (version from pip show alexapy or HA startup): trying to work out how to get this
 Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). yes

Just wondering if anyone has had a similar issue or has any advice on how to troubleshoot further with no log access.

Maybe the best way is to just delete all of the Amazon configuration and rebuild it?

**Comment by alandtse** [comment]
Please use the template.

**Comment by alandtse** [comment]
Thanks. Please update to the latest. The homeassistant.log file in your config directory should survive reboots. Please pull that when it happens.

**Comment by dw20155** [comment]
Hi, unfortunately it seems that the homeassistant.log is overwritten when the pi is power cycled. Is there any way to prevent this and have it append instead?

**Comment by alandtse** [comment]
Disable auto restart of HA or you can ask the HA forums if you can append.

**Comment by dw20155** [comment]
I think we can close this issue - I found that the SD card holder on the RPI had been pried up slightly off of the circuit board.
So the real issue was that when it got to certain temperatures then the holder was not making the connection to the SD card and thus the crash with no logs at all

0_o;;
