### ISSUE TITLE
Removed integration files without uninstalling but it is still around

### ISSUE THREAD

**Issue by mazzy89** [custom-components/alexa_media_player#1308]
**Describe the bug**
I've made the mistake to not follow the wiki so I've first removed it on hacs. The result is that now I cannot remove the integration on the integration page. It is there and I do not have any button how to clean it. I've tried everything like removing pickle files etc... The integration is here and does not go away 

![FCF22882-D6F0-4DB5-98DE-E39A28F455A0](https://user-images.githubusercontent.com/5463218/118897430-8cebb080-b90a-11eb-8d5d-e6f9aed73b3c.jpeg)

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details**
 - Home-assistant (version): 
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: 

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by mazzy89** [comment]
When instead I tried to reinstall it via hacs I get the error
```
This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/alexa_media/__init__.py:16 
Integration: Alexa Media Player (documentation, issues) 
First occurred: 1:31:08 AM (1 occurrences) 
Last logged: 1:31:08 AM

Setup failed for alexa_media: unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 200, in _async_setup_component
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 485, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/alexa_media/__init__.py", line 16, in <module>
    from alexapy import (
  File "/usr/local/lib/python3.8/site-packages/alexapy/__init__.py", line 16, in <module>
    from .alexaapi import AlexaAPI
  File "/usr/local/lib/python3.8/site-packages/alexapy/alexaapi.py", line 23, in <module>
    from .alexalogin import AlexaLogin
  File "/usr/local/lib/python3.8/site-packages/alexapy/alexalogin.py", line 49, in <module>
    class AlexaLogin:
  File "/usr/local/lib/python3.8/site-packages/alexapy/alexalogin.py", line 221, in AlexaLogin
    def set_totp(self, otp_secret: Text) -> Optional[pyotp.TOTP]:
AttributeError: module 'pyotp' has no attribute 'TOTP'

```

**Comment by alandtse** [comment]
Remove and reinstall from HACS. 

The error you have is because it's not installing the correct version of pyotp. You can install it manually by reinstalling alexapy.

```console
pip install alexapy
```

**Comment by mazzy89** [comment]
This is what I've already done three times. I've removed from hacs but nothing. Furthermore I'm running home assistant os so I cannot run pip

**Comment by alandtse** [comment]
Install the ssh addon and you can access the container. Otherwise you can manually edit your .storage files to remove the component. Or ask HA for a mechanism to remove integrations you have removed uncleanly.

**Comment by mazzy89** [comment]
yes but indeed is a container so it doesn't manage dependencies like pip. I've already tried. so it did not work.

**Comment by alandtse** [comment]
I run hassos and can confirm pip works.

I'm going to close this since there's nothing for us to do on the component side and I've already stated your options.

**Comment by mazzy89** [comment]
Not fun here. You need to listen the issue of the people and not just replying that you have listed all your options. I told you clearly that pip does not run on the os

**Comment by alandtse** [comment]
First off, you're not my stakeholder. You wrote yourself you were removing the component. I maintain this for myself and the fact you can use it is because I believe in open source and sharing it for people who want to use it. I never asked you to use it nor did I sell it to you.  Frankly, I don't care if you use it. So please check your entitlements.

Second, please learn how to use your HA system. There are support channels in HA if you need help. Here's what you see using SSH & Web Terminal. Clearly it's possible and your attitude in this thread does not makes me want to help you further.
![image](https://user-images.githubusercontent.com/7086117/119032650-47a69d80-b961-11eb-830c-ca3ddda38290.png)

**Comment by mazzy89** [comment]
Again my invitation here to you is to listen up the people that use your code, product, whatsoever rather than just close quickly the issue asserting that you have listed all the possibile options because this want to prove to the others that you are smarter and the others dumber. It's about politiness that you haven't showed here. That's said have great coding.
