### ISSUE TITLE
Use HA shuffle and repeat services

### ISSUE THREAD

**Issue by vjversatile** [custom-components/alexa_media_player#1315]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**

Looking for track loop feature on Alexa media player.
https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-media-playqueue.html#setloop-directive

**Describe the solution you'd like**

I see there is a media_player.repeat_set feature but it does not work for even looping audio on Amazon music. I believe there is this feature that is required from developer.amazon
https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-media-playqueue.html#setloop-directive

**Describe alternatives you've considered**

No alternative, i have to orally call Alexa, track loop On to trigger media looping

**Additional context**

**Comment by alandtse** [comment]
Is this available in the official app?

**Comment by vjversatile** [comment]
> Is this available in the official app?

Yes, it is available in the app

**Comment by alandtse** [comment]
Show me what you're talking about. We already implement the repeat in the app.

**Comment by vjversatile** [comment]
![image](https://user-images.githubusercontent.com/12622121/120912690-01ff0a00-c6af-11eb-9895-21cabd97eb65.png)

Hi, talking about the loop feature above.

I have seen the repeat.set service that is available on Home assistant but that does not work like a few other have mentioned in this comment and the comment next to it. I have tried calling the service directly from Services on dev tools on HA and can see the event being recorded as well but it does nothing. Also, i am definitely triggering the Repeat set service when the audio is already playing.

[https://community.home-assistant.io/t/offer-option-to-loop-repeat-an-audio-file-on-the-media-player-play-media-service/180286/7](url)

Trying all of this for Amazon music which supports loop mode ON feature once audio track starts playing.

**Comment by alandtse** [comment]
And the repeat switch doesn't work?

**Comment by vjversatile** [comment]
> And the repeat switch doesn't work?

Yes, Repeat set doesn't work

**Comment by alandtse** [comment]
I just tested it and setting the repeat switch on is enabling it in Amazon's app. Please provide logs and the service call you are using.

**Comment by vjversatile** [comment]
Hmm, doesn't work for me no matter what i do. not getting enabled on the app.

the Home assistant logs don't show anything relevant, is there somewhere else i should look, plz guide.

This is the event that gets fired when i call the repeat service while the music is playing 
Event 52 fired 2:25 PM:
{
    "event_type": "call_service",
    "data": {
        "domain": "media_player",
        "service": "repeat_set",
        "service_data": {
            "repeat": "all",
            "entity_id": [
                "media_player.upstairs"
            ]
        }
    },
    "origin": "LOCAL",
    "time_fired": "2021-06-08T08:55:42.929654+00:00",
    "context": {
        "id": "xxxxxxxxxab17cba072fxxx9550d37228e",
        "parent_id": null,
        "user_id": "xxxxxxxxx8bce41b9a843b7964xxxxx98f"
    }
}

**Comment by alandtse** [comment]
And when you use the switch?

**Comment by vjversatile** [comment]
> And when you use the switch?

If i understood your question correctly, I am using the switch when the music has started playing on my alexa device via amazon music.

If i click on the loop button on the app it activates. but if i send the repeat set call to the same echo device, the loop is not activated.

**Comment by alandtse** [comment]
No. The switch in HA. `switch.upstairs.shuffle_switch`. What happens if you use that?

**Comment by vjversatile** [comment]
just tested, shuffle is working.

**Comment by alandtse** [comment]
Sorry I meant the repeat switch.

**Comment by vjversatile** [comment]
> Sorry I meant the repeat switch.

Apologies for the confusion, using the switch.upstairs.repeat_switch entity is **actually working based on my trials today**.  I have no understanding of how this is different from the service media_player.repeat_set and why one is workign while the other is not, any insights might help.

That said, i am able to use the switch entity above in my automation and achieve the end result i am expecting. i.e to start a track and put it in loop mode when i click on a button that i have setup. The repeat switch turns off automatically when the track is changed as expected.

**Comment by alandtse** [comment]
It's because we implemented repeat before HA had it and we never added the new HA method.

**Comment by vjversatile** [comment]
Ok, thanks. I'll close since we have an alternate method.
