### ISSUE TITLE
Integration not available in integration setup

### ISSUE THREAD

**Issue by michis0806** [custom-components/alexa_media_player#1316]
**Describe the bug**
After a update yesterday, the Alexa_media integration stopped working. I tried to uninstall/install it via hacs. But I'm not able to add the integration via the default workflow. The plugin seems to be found during startup...

**To Reproduce**
1. open HACS
2. Install Alexa Media Player
3. restart Home Assistant
4. Alexa Media Player is not available in integration setup

**Expected behavior**
Alexa Media Player should be able to set up via integration setup

**Screenshots**

**System details**
 - Home-assistant (version): 2021.6.0 
 - Hassio (Yes/No): No
 - alexa_media  3.10.5
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled] yes
 - 
**Logs**
2021-06-04 09:13:17 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

**Comment by alandtse** [comment]
Make sure you've hard refreshed your cache so it appears in your browser.

**Comment by michis0806** [comment]
OMG. Captain Obvious. 
Thanks, that fixed it. I still do not know why it stopped working in the first place, but it’s working again!

thanks 
Michael
