### ISSUE TITLE
Timer offset by timezone offset in HA 2021.6.x

### ISSUE THREAD

**Issue by JamieP83** [custom-components/alexa_media_player#1317]
**Describe the bug**
Hey,
ive noticed that my "next_timer" values are always out by 1hour? 
So if i start a timer at 7:20pm, to go off in 20min (7:40pm), it actually goes back one hour and says its "40min ago"

i'm pretty sure its the +1 daylight savings not being taken into account?

![image](https://user-images.githubusercontent.com/48566948/120902705-b8c0a300-c639-11eb-9e61-ed3f64b63061.png)

![image](https://user-images.githubusercontent.com/48566948/120902743-f9202100-c639-11eb-959a-9bc95e2b368f.png)

**To Reproduce**
1. set a new alexa time to go off in 30min
2. check out the result in home assistant, will be incorrect

**Expected behavior**
For the time to show the correct value

**Screenshots**
See above

**System details**
 - Home-assistant (version): supervisor-2021.05.4
 - Hassio (Yes/No): yes
 - alexa_media  (version from `const.py` or HA startup): "3.10.5"
 - alexapy (version from `pip show alexapy` or HA startup): 
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). y

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by alandtse** [comment]
If the value is correct in the UI then it's something with HA setup. You said it was 720pm? Does the timestamp have the right offset for your location?

**Comment by OnkelKeule** [comment]
Same problem here (for me it's 2h off - but I am GMT+2). 
Seems like there is an issue with the timestamp.

**Comment by kkellner** [comment]
I'm off by 6 hours on  since updating to 2021.6 -- I'm in MDT timezone which is UTC−06:00

I set a timer for 2 minutes at 10:09am.  The `next_timer` value showed this:
```
2021-06-06T16:11:04-06:00
```

So it seems to be giving me UTC time but saying the offset is `-06:00`

**Comment by bcmitri** [comment]
I was coming here to log this. Mine are out by three hours, but my time zone is UTC -3. 

As mentioned above, this started with Home Assistant version 2021.6, which I know had some changes to how timestamps are handled.

**Comment by alandtse** [comment]
Please confirm the settings here don't resolve this. https://www.home-assistant.io/blog/2021/06/02/release-20216/#time-format-settings

**Comment by JamieP83** [comment]
Hey
That’s just the format of how to show time right? 
that doesn’t help with the offsets overall?

**Comment by Silvenga** [comment]
> Please confirm the settings here don't resolve this. 

Can confirm, these setting don't appear to impact the UTC offset @alandtse.

**Comment by permissionBRICK** [comment]
Same Issue for me, the Timer Value always reads in UTC, despite having +02:00 flag at the end, which would indicate that the Value SHOULD already be adjusted for timezones, however it isn't. The same issue does not appear for Alexa Alarms.

**Comment by alandtse** [comment]
Thanks. is it only the timer that has the issue? Or are reminders/alarms also showing it?

**Comment by Silvenga** [comment]
Your latest release definitely resolves the timers in 2021.6.4. 

Thanks for your time and effort!

**Comment by permissionBRICK** [comment]
Yes, it is now fixed for me as well, thanks!

**Comment by DarkStarSword** [comment]
The fix for this has caused some regressions - toggle automations no longer work due to it now using cached data that hasn't been properly invalidated or updated to reflect the current state, and errors are thrown when turning lights on / off about comparing naieve and aware datetimes.
