### ISSUE TITLE
AttributeError: 'AsyncClient' object has no attribute 'cookie_jar'

### ISSUE THREAD

**Issue by ps-tfriedl** [custom-components/alexa_media_player#1318]
**Describe the bug**
My configuration stopped working a few days ago. When I now try to reconfigure it it always fails with an unknown error. 

**To Reproduce**
1. Go to the integrations page
2. Click on reconfigure
3. Use Login Proxy (without 2FA app key)
4. Unknown error is shown after submitting

**Expected behavior**
The integration should be configured correctly.

**System details**
 - Home-assistant (version): 2021.6.1
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup):  3.10.5
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: yes

**Logs**
2021-06-06 10:58:21 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Using existing login
2021-06-06 10:58:21 DEBUG (MainThread) [alexapy.alexalogin] Unable to generate OTP; 2FA app key not configured
2021-06-06 10:58:21 DEBUG (MainThread) [authcaptureproxy.auth_capture_proxy] Refreshed 3 modifiers: ['autofill', 'prepend_relative_urls', 'change_host_to_proxy']
2021-06-06 10:58:21 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Starting proxy for t****s@f********g - amazon.de
2021-06-06 10:58:21 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Found existing proxy_view
2021-06-06 10:58:21 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 202, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 155, in post
return await super().post(request, flow_id)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 63, in wrapper
result = await method(view, request, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
result = await self._flow_mgr.async_configure(flow_id, data)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 202, in async_configure
result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
File "/config/custom_components/alexa_media/config_flow.py", line 356, in async_step_user
return await self.async_step_start_proxy(user_input)
File "/config/custom_components/alexa_media/config_flow.py", line 383, in async_step_start_proxy
self.proxy.session.cookie_jar.update_cookies(
AttributeError: 'AsyncClient' object has no attribute 'cookie_jar'

**Comment by alandtse** [comment]
Your alexapy version is outdated. Please ensure its updated and you don't have a random version in your /config.

**Comment by ps-tfriedl** [comment]
I'm on alexapy==1.25.1. But I'm using HACS - so I never did any changes to alexapy myself?

**Comment by alandtse** [comment]
Remove and readd from HACS.

**Comment by nniehoff** [comment]
I have the same issue.  I have removed from HACS and re-added several times, no luck.  I have confirmed alexapy=1.25.1

**Comment by nniehoff** [comment]
Uninstalling from HACS, restarting, removing `/config/deps/lib/python3.8/site-packages/alexapy*`, reinstalling via HACS, restarting HA again seemed to clear it up for me

**Comment by ps-tfriedl** [comment]
I tried removing, restart, installing - without luck. Also I don't have the /config/deps folder as nniehoff has - it's empty.

What should be the correct alexapy version? Because it seems to me that 1.25.1 is the latest?!

**Comment by alandtse** [comment]
Remove and readd the integration in HA as the workaround.

**Comment by ps-tfriedl** [comment]
Works! Thanks!

**Comment by alandtse** [comment]
The true way to fix this is to switch to httpx or to remove the resume dialogue.

**Comment by paullessing** [comment]
Has anyone managed a successful workaround? I've tried all the above steps (remove, restart, readd) and not had any success so far. I always get to the final step of the configuration dialog where it asks you to confirm the generated 2FA code, and it fails with the above error.

**Comment by endsideX** [comment]
Unfortunately, I also have the same problem. A new installation and deleting the .pickle did nothing for me either.
My alexapy is up to date.

Has anyone already found a workaround?

**Comment by endsideX** [comment]
I finally got to work:

Install an Authenticator App on your phone.
Set up your Amazon account with 2FA.
Access Home Assistant using the mobile app on your phone.
-Enter Username ans Password
-Enter the CAPTCHA.
-Enter a 2FA code from your Authenticator App.

**Comment by cagnulein** [comment]
> Remove and readd the integration in HA as the workaround.
> 
> You may need to delete the .pickle file too.

thanks! This works to me too!

**Comment by guystreeter** [comment]
This problem is still happening. What is necessary to get it fixed? Manual deletion of files as a workaround for months now.

**Comment by guystreeter** [comment]
Where is "the .pickle file"? I don't see one.

**Comment by cagnulein** [comment]
> Where is "the .pickle file"? I don't see one.

login into ssh and then

<pre>cd config
find | grep .pickle</pre>

you will see it. Mine is under /config/.storage/

**Comment by paullessing** [comment]
I managed to get it to work with the most recent version (v3.10.10) after doing the following steps:
- remove integration in Home Assistant (Configuration -> Integrations -> Alexa Media -> Delete)
- uninstall integration from HACS (HACS -> Integrations -> Alexa Media Player -> Uninstall)
- check there is no pickle file (I think I deleted it in an earlier attempt)
- restart Home Assistant
- install v3.10.10 from HACS
- go to Configuration -> Integrations and then follow [installation instructions for the Integrations Page method](https://github.com/custom-components/alexa_media_player/wiki/Configuration#integrations-page) _exactly_

When following the installation instructions, I used the settings for Login Proxy and left the default setting for the oauth ("mobile") login method as it was.

That finally fixed it for me!

**Comment by guystreeter** [comment]
Configuration -> Integrations -> Alexa Media only shows a Reconfigure button. No way to delete it that I can find.

**Comment by paullessing** [comment]
@guystreeter while it was failing for me, I had two different entries for the failing integration. I think one of them had a "remove" function. However, it's possible I'm misremembering and I just ended up skipping that step and going straight to uninstall.

**Comment by jasonmadigan** [comment]
Has this ever been fixed? Encountering this endlessly today. Everything up-to-date.

**Comment by larena1** [comment]
@alandtse I'm also facing this issue. When is it planned for alexapy to switch to httpx? Alexapy shipping its own aiohttp was always a dirty hack causing issues like this unfortunately.

**Comment by alandtse** [comment]
> @alandtse I'm also facing this issue. When is it planned for alexapy to switch to httpx? Alexapy shipping its own aiohttp was always a dirty hack causing issues like this unfortunately.

The fact httpx doesn't have a websocket library may mean another path. The issue has nothing to do with the fact it has it's own aiohttp. Aiohttp didn't handle non-spec Amazon response with cookies so I had to patch it myself. That said, this can be easily fixed if someone figures out how to convert aiohttp cookies into a format that httpx can understand and back again. That's where this is breaking because I don't have any handoff code written yet. Actually, forcing authcaptureproxy down to 0.8.1 may be a workaround.

**Comment by larena1** [comment]
Handing cookies with httpx seems to be pretty straightforward. It allows for passing a cookiejar so you could share that between aiohttp and httpx

https://www.python-httpx.org/api/#cookies

**Comment by alandtse** [comment]
> Handing cookies with httpx seems to be pretty straightforward. It allows passing a cookiejar so you could share that between aiohttp and httpx
> 
> https://www.python-httpx.org/api/#cookies

Last I checked they weren't compatible. But if you figure it out, I will take a PR.

**Comment by larena1** [comment]
Seems that they're still not compatible as aiohttp is using its own implementation. How is the websocket authenticated? Cookie or authentication header? Couldn't you just use aiohttp for the websocket and httpx for everything else?

**Comment by alandtse** [comment]
> How is the websocket authenticated? Cookie or authentication header? Couldn't you just use aiohttp for the websocket and httpx for everything else?

It used to be cookies in the session object. However, the new websocket now explicitly calls for the cookies to be passed in the header. I haven't tested to see what happens if I clean the session object and only rely on the header cookies.

It seems really messy to include both. I may just revert auth_capture_proxy to use aiohttp since the only reason I swapped it was to avoid an issue with Tesla's interaction with aiohttp (that need is gone now). Aiohttp has little issues with random things so it seemed worth switching to avoid them.
