### ISSUE TITLE
Feature Request: Graceful Failure to avoid clobbering existing scripts/automations

### ISSUE THREAD

**Issue by nerdfoundrygaming** [custom-components/alexa_media_player#1322]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**
Related to #1321 

Essentially, when the component fails, my entire system becomes unusable, and fails all over the place due to not being able to locate the services that are expected to exist from this component.

Ex:
```
2021-06-15 13:11:20 ERROR (MainThread) [homeassistant.components.automation.lifecycle_zwave_ready] _Lifecycle - ZWave Ready: Error executing script. Service not found for call_service at pos 1: Unable to find service notify.alexa_media_codex_s_echo_show
```

**Describe the solution you'd like**
If there's the ability to determine pre-existing entities that had services created for them, if it'd act like other missing entities like when I remove a switch from the system, it requires me to manually delete them, and then behind the scenes if there's not a valid entity it could just noop?

I'm not certain what the capabilities are really, but the idea is to make it so existing automations don't fail when this component fails.

**Describe alternatives you've considered**
Completely removing the `alexa_media_player` from my setup, which I'd rather not do.

**Comment by alandtse** [comment]
Unfortunately, this is not something we can do. This is an HA issue when a service is not found. You'll need to request it there.
