### ISSUE TITLE
Shuffle play in Amazon Music don't works anymore

### ISSUE THREAD

**Issue by energywave** [custom-components/alexa_media_player#1327]
**Describe the bug**
Shuffle of Amazon Music playlist as documented in the following screenshot of the doc wiki stopped working time ago. Time to fix it :)
It's the same as if you don't specify shuffle. No shuffle is happening anymore. The playlist is reproduced in an ordered way.

![image](https://user-images.githubusercontent.com/2051567/122752358-25ba7680-d291-11eb-9c56-1595c4df5f9f.png)

**To Reproduce**
1. Go to device tools -> services 
2. Try the following code:
```
service: media_player.play_media
data:
  entity_id: media_player.pian_terreno
  media_content_id: 'shuffle playlist viral hits'
  media_content_type: AMAZON_MUSIC
```
3. Please note that Alexa starts ever with the first song and then the second, etc

**Expected behavior**
A randomized play of songs, like it was some versions ago (don't remember the version when it broke exactly). A workaround is to start the play, activate the shuffle entity and then go to next song but it's very ugly...

**Screenshots**

**System details**
 - Home-assistant (version): 2021.6.6
 - Hassio (Yes/No): yes
 - alexa_media  (version from `const.py` or HA startup): 3.10.6
 - alexapy (version from `pip show alexapy` or HA startup): 1.25.1
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: y

**Logs**
I don't think logs are needed as I'm sure it's not a problem of my installation. But if I have to I'll generate them.

**Additional context**

**Comment by alandtse** [comment]
If the command isn't working anymore that's an Amazon issue. We're just passing it to Amazon to process. Feel free to update the wiki with a link to this issue to indicate it has been removed from Amazon.

**Comment by energywave** [comment]
Done, I've added that info to the wiki. Please review my edit if you want. ...and keep on the great work!

**Comment by fearandloathinginithell** [comment]
Shuffle appears to be working now, at least with Apple Music

**Comment by dedors** [comment]
Working here too with spotify:
`media_content_id: "Suffle My Playlist PLAYLISTNAME"`
Enables shuffle AND starts playing a random song.

Thanks for leaving it in the docs! :)

**Comment by lymanepp** [comment]
> Working here too with spotify:
> `media_content_id: "Shuffle My Playlist PLAYLISTNAME"`
> Enables shuffle AND starts playing a random song.

Yes, that syntax works with Spotify. Thanks for sharing.
