### ISSUE TITLE
Hue Motion Sensor - paired with echo

### ISSUE THREAD

**Issue by sbur83** [custom-components/alexa_media_player#1335]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**
Indoor Hue Motion Sensor (zigbee) bridged with echo - displays motion and temperature in Alexa app.

**Is your feature request related to a problem? Please describe.**
Media player integrating temperature only - no motion sensor in Home Assistant entity list

**Describe the solution you'd like**
Would be sweet if anyone could get motion sensor to intergrate :)

**Describe alternatives you've considered**
not sure of a solution other than getting a hue bridge. EDIT: I have got the automation I wanted working in the Alexa app, duh dunno why I didn't think of this.

**Additional context**
nil - can give more info if needed

Thanks, for all you do, love this integration.

**Comment by 86lava** [comment]
I have a Sylvania 72923 zigbee motion (and temp) sensor paired to my Echo Plus.  The motion sensor does NOT appear in HA, but its temperature sensor does.

**Comment by sbur83** [comment]
> I have a Sylvania 72923 zigbee motion (and temp) sensor paired to my Echo Plus. The motion sensor does NOT appear in HA, but its temperature sensor does.

It's documented on the wiki that lights and temperature are only supported at this time. Would be cool if this can be done tho, I had a smart app that bridged it with smartthings hub using groovy IDE but it's not fully local control with the ST intergration. I can't code so will cross my fingers and toes that something eventuates here :)

**Comment by blm126** [comment]
Sadly, I don't believe this is currently doable. Alexa does not send websocket messages when a motion sensor is triggered. This means that polling would be necessary. The current polling interval is 10 minutes. Even if that got lowered to 10 seconds, that is probably still to slow to be useful. 

My current setup involves using Alexa routines to toggle a home assistant boolean input using the official Alexa integration.  That is the best workaround I have found.

**Comment by sbur83** [comment]
No worries, thanks for explaining :)
