### ISSUE TITLE
Suggestion: Change API

### ISSUE THREAD

**Issue by sgofferj** [custom-components/alexa_media_player#1340]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**
Not a problem but using the "unofficial API" has quite some limits when it comes to what it can tell an Echo to do.

**Describe the solution you'd like**
I would like to suggest the authors have a look at the OpenHAB "Amazon Echo Control" binding at https://github.com/openhab/openhab-addons/tree/main/bundles/org.openhab.binding.amazonechocontrol
OpenHAB can do a lot more with the Echos, such as use SSML, use all sounds from the library, it can tell an Echo to connect or disconnect to/from a bluetooth device, etc. etc..

**Describe alternatives you've considered**
As I wrote, I only would like to suggest the authors have a look. I wouldn't even consider it a feature "request", because I know it would be a crazy amount of work and I couldn't help because I don't speak Python. But it would bring Home Assistant a huge step further.

**Additional context**
N/a

**Comment by alandtse** [comment]
We use the same API they use. If you have a specific feature you'd like, please open a specific request and we can see if it's worth opening up.

**Comment by sgofferj** [comment]
Are you sure? In OpenHAB you can use e.g. all sounds from the Alexa developer docs, SSML, etc. If I try any of those in a service call in HA, I get an error back.
