### ISSUE TITLE
Include and Exclude problems

### ISSUE THREAD

**Issue by emufan** [custom-components/alexa_media_player#1354]
**Describe the bug**
First of all, include and exclude are more than welcome! Prefer this over the disabling in UI, because I have a lot of decives, which are found via alexa media player, but not working (e.g. all the Sonos tuples, ...) and other devices, which I do not want to have in HA. So great to have include and exlcude!

1. If I use include during setup and include either "Echo Dot Wohnzimmer" oder Echo Dot Wohnzimmer without "", the setup creates "Echo Dot Wohnzimmer", but my other device called "Wohnzimmer" as well. This is only not happening, if I exclude "Wohnzimmer" on top.

2. If I include only "Echo Dot Whatever", the integration only set up the entity/device "Echo Dot Whatever", but not the alarm, timer, ... entities. Bug or feature? What can I do, that the corresponding entities are set up as well?

**To Reproduce**
Use include and exclude during setup.

**Expected behavior**
ad 1., If I include only "Echo Dot Wohnzimmer", it should create only ""Echo Dot Wohnzimmer" (with corresponding additional entities)  and not the other device called "Wohnzimmer" as well. 

ad 2. If I include "Echo Dot Whatever", it should create this, but the corresponding additional entities as well.

**System details**
 - Home-assistant (version): 2021.8.2
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): Do not know how to find
 - alexapy (version from `pip show alexapy` or HA startup): Do not know how to find
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: y

**Comment by alandtse** [comment]
For 1, please provide logs showing startup. That will show what is being included or excluded.

For 2, please read the [documentation](https://github.com/custom-components/alexa_media_player/wiki/Configuration#inclusions). Include only includes what you specifically include-- Not related devices.

**Comment by emufan** [comment]
ad 2. I always read the documentation. ;-) But either, we are talking about different topics or the documentation can be improved. The include/exclude part is referring to include/exclude devices. And I'm talking about corresponding entities/sensors, where the documentation says
```
Each online media player that supports Notifications will create the following sensors:

sensor.media_player_next_alarm
sensor.media_player_next_timer
sensor.media_player_next_reminder
```
So I didn't find in this doc, that this is not only for devices, but for entities as well and that I have to include those entities as well. And in the referred part, that this is only happening, when including those explicitly during include as well. 

Because of this, I expected that I include/exclude devices and the integration setup theses additional entities for included (and supporting) devices.

But thank you. Beside this mix of devices and entities in the doc, it worked now, if I included the entity sensors as well during setup.
```
Echo Dot Wohnzimmer next Alarm
Echo Dot Wohnzimmer do not disturb switch
Echo Dot Wohnzimmer next Reminder
Echo Dot Wohnzimmer next Timer
Echo Dot Wohnzimmer repeat switch
Echo Dot Wohnzimmer shuffle switch
```

ad 1.
```
2021-08-08 09:16:41 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Setting up Alexa devices with {'oauth_login': True, 'email': 'xxx', 'password': 'yyy', 'url': 'amazon.de', 'debug': False, 'scan_interval': 60, 'include_devices': '"Echo Dot Wohnzimmer"', 'exclude_devices': '', 'oauth': {'access_token': 

and

2021-08-08 09:16:46 DEBUG (MainThread) [custom_components.alexa_media] xxx: Existing: [] New: ['Echo Dot Wohnzimmer', 'Wohnzimmer']; Filtered out by not being in include: ['Fire TV', "Sonos One", etc etc] or in exclude: []
```
So it adds "Wohnzimmer" as well whereas only "Echo Dot Wohnzimmer" should be included. And yes, tried this with and withoiut "", first without. This is only not happening, if I exlude "Wohnzimmer" on top.

**Comment by alandtse** [comment]
For 2, feel free to correct the wiki if you don't think it's clear enough.

For 1, please provide the specific "include_devices" setting you are using.

**Comment by emufan** [comment]
ad 1. Didn't get this anymore. I have described and posted it more than once: See last post.

> 'include_devices': '"Echo Dot Wohnzimmer"'

And "Echo Dot Wohnzimmer" is the only string, which I put in this case in the include textbox during integration setup.

That's it in this example/case. But it sets up "Echo Dot Wohnzimmer" **and** "Wohnzimmer". I assume, that the code uses **contains** or whatever and then Wohnzimmer is in the include "Echo Dot Wohnzimmer". But I do not know.

If you are not interested in this bug, please close it. I only made this effort to make you aware of this. My setup is now running with exluding Wohnzimmer (even if not included) on top of this.

ad 2. You are funny. I cannot change docs, if it is not clear if the docs or the program behavior are wrong? For me it is still unclear, but I can live with it. Either with the correct or wrong behavior. For me it is wrong. How should I know, which are the names and supporting entities to include them manually, if it described like 

> **Each** online media player that supports Notifications will create the following sensors

**Comment by alandtse** [comment]
I am reviewing item 1. Thank you for bringing it up.

For 2. It's a wiki. Anyone can change it to make it clearer. There's an edit button on every page.

**Comment by emufan** [comment]
I know, but anyone can only make it clearer, if it is clear how it should work and what is or is not a bug. ;-)

**Comment by alandtse** [comment]
Do "Echo Dot Wohnzimmer" and "Wohnzimmer" have the same serial number? Please check your devices [page](https://alexa.amazon.de/api/devices-v2/device):

The include language does not use contains and relies on a literal match.
https://github.com/custom-components/alexa_media_player/blob/dev/custom_components/alexa_media/__init__.py#L488

This is toy code that does the same test:
```python
include = ["Wohnzimmer"]
devices = ["Echo Dot Wohnzimmer", "Wohnzimmer"]
for device in devices:
     if device not in include:
            print("Device " , device, " filtered")

>>>
Device  Echo Dot Wohnzimmer  filtered
```

```python
include = ["Echo Dot Wohnzimmer"]
devices = ["Echo Dot Wohnzimmer", "Wohnzimmer"]
for device in devices:
     if device not in include:
            print("Device " , device, " filtered")

>>>
Device  Wohnzimmer  filtered
```
Please also confirm that Wohnzimmer's serial is not appearing under `appDeviceList` under `Echo Dot Wohnzimmer`. I'll probably think about how to try to reproduce it a few more days. Please also the 5 or so lines before:

```
2021-08-08 09:16:46 DEBUG (MainThread) [custom_components.alexa_media] xxx: Existing: [] New: ['Echo Dot Wohnzimmer', 'Wohnzimmer']; Filtered out by not being in include: ['Fire TV', "Sonos One", etc etc] or in exclude: []
```

As for the wiki, the instructions say that the sensors are included by default. If you start using advanced settings like the include and exclude filters, the defaults no longer apply. The only edit I can see is to be explicit that defaults only apply when advanced settings aren't in use, but that seemed clear to me. If it wasn't clear to you, then that may be a reason to update the wiki in a way that makes it clear to you since others may read it the same way. The wiki is maintained by the community with the hope that collectivity the documentation improves as people see areas to improve.

**Comment by emufan** [comment]
```
{"accountName":"Echo Dot Wohnzimmer","appDeviceList":[],"capabilities":["I_HEART_RADIO",etc.],"charging":null,"clusterMembers":[],"deviceAccountId":"APXEN5SABAFAO","deviceFamily":"ECHO","deviceOwnerCustomerId":"bbb","deviceType":"ccc","deviceTypeFriendlyName":null,"essid":null,"language":null,"macAddress":null,"online":true,"parentClusters":[],"postalCode":null,"registrationId":null,"remainingBatteryLevel":null,"serialNumber":"fff","softwareVersion":"669702920"}
```
and
```
  {"accountName":"Wohnzimmer","appDeviceList":[],"capabilities":["APPLE_MUSIC",etc.],"charging":null,"clusterMembers":[],"deviceAccountId":"aaa","deviceFamily":"THIRD_PARTY_AVS_MEDIA_DISPLAY","deviceOwnerCustomerId":"bbb","deviceType":"ddd","deviceTypeFriendlyName":"Sonos","essid":null,"language":null,"macAddress":null,"online":true,"parentClusters":[],"postalCode":null,"registrationId":null,"remainingBatteryLevel":null,"serialNumber":"eee","softwareVersion":"0"}
```
Wohnzimmer Echo Dot = Echo Dot
Wohnzimmer = Sonos ZP80 (without Alexa), but connected to Wohnzimmer Echo Dot as speaker device. But this is only playing if my audio receiver is on, so useless for announcements. 

So appDeviceList is empty in both devices and the serials are not equal, only deviceOwnerCustomerId is equal, see bbb=bbb.

```
2021-08-08 09:16:46 DEBUG (MainThread) [custom_components.alexa_media] Echo Dot Wohnzimmer: Locale de-de timezone Europe/Berlin
2021-08-08 09:16:46 DEBUG (MainThread) [custom_components.alexa_media] Echo Dot Wohnzimmer: DND False
2021-08-08 09:16:46 DEBUG (MainThread) [custom_components.alexa_media] Wohnzimmer: Locale en-us timezone None
2021-08-08 09:16:46 DEBUG (MainThread) [custom_components.alexa_media] Wohnzimmer: DND False
```

**Comment by mbcomer** [comment]
Has there been any progress looking into this?
