### ISSUE TITLE
Installed via HACS Doesn't show up in 'Set up a new integration'

### ISSUE THREAD

**Issue by Boomer50BMG** [custom-components/alexa_media_player#1367]
I installed via HACS and restarted HA.  I then go into  config/integrations and Add Integration.  Alexa  Media Player does not show up in the list to 'Set up a new integration'.   I do not see anything in the logs.   Still looking..

Any ideas?

Randy

**Comment by alandtse** [comment]
Please search. This is a dupe that's been answered many times. #1316
