### ISSUE TITLE
All Echo Show 5 entities labeled as "Not available"

### ISSUE THREAD

**Issue by Cr4z33** [custom-components/alexa_media_player#1368]
I just succesfully setup your integration and I've got 2FA enabled in my Amazon (Italy) account.

However ALL my Echo Show 5 (1st gen) entities are marked as "Not available".

Any chance to get everything working?

**Comment by alandtse** [comment]
Please fill out the template.

**Comment by Cr4z33** [comment]
@alandtse please forgive me, but... what template are you referring to? 😅

**Comment by alandtse** [comment]
https://github.com/custom-components/alexa_media_player/issues/new/choose

**Comment by alandtse** [comment]
Please reopen using a template when you have time. The most likely clause is your Login domain doesn't match whatever the echos are set to. E.g., you're logging into amazon.it but your devices are set to amazon.co.uk or amazon.com.

**Comment by Cr4z33** [comment]
> 
> 
> The most likely clause is your Login domain doesn't match whatever the echos are set to.

Indeed!!

As soon as I tried with amazon.com EVERY Amazon device is now available!
