### ISSUE TITLE
Intergrations Stopped Working unable to find what is blocking it

### ISSUE THREAD

**Issue by thorrrr** [custom-components/alexa_media_player#1371]
HI 
My devices will no longer respond to Alexa Voice and in the integration keep going on off line.
I have no doubt this is a configuration / Cloudflare Issue blocking url for this integration and rejecting correct Alexa urls

After turning on Cloudflare Full protection several hours later all Alexa apps no longer discovered by the integration.
The items work from HA but all showing red dots in integration.
I have HA with a CNAME in Cloudflare i also have the config in my yaml
If i login with 
 https://homeassistant.mydomainname.co.uk/auth/authorize i get [this](https://1drv.ms/u/s!Ao6WCX2miTCJjLFuYjp8DLk0Uv4ezQ?e=IhJDXS)
https://homeassistant.mydomainname.co.uk/auth/token i get a 405 Error

But i can fully login https://homeassistant.mydomainname.co.uk no issue on any platform.
I have no firewall filters blocking anything 
My account linking paths are correct see image below.
This has been working for 8 months no issue so it has something to do with block from some where or does HA need more details to accept it now?

**Expected behavior**
It should allow the integration through if i have CNAME in Cloudflare all my other Intergrations have no issue. I appreciate this is a lot more complex but having spent some 20 hours on many Discord servers nobody has any idea why it is not working.

**Screenshots**
![Dell - Screenshot 03-10-2021 - 01](https://user-images.githubusercontent.com/8170673/135756462-0a91a7ca-f6d5-4bbd-a08e-01776a3af653.jpg)
user-images.githubusercontent.com/8170673/135756452-8e18d0e3-579f-496a-a536-4306ccef24d4.jpg)
![Dell - Screenshot 03-10-2021 - 02](https://user-images.githubusercontent.com/8170673/135756522-939085ee-9867-4f09-84ef-0767e9f45d44.jpg)

**System details**
 - Home-assistant (Home Assistant 2021.9.7):  Home Assistant OS
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).  No
 - alexa_media  (version from `const.py` or HA startup): Ver v3.10.8
 - alexapy (version from `pip show alexapy` or HA startup): Sorry no idea what this means
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: Yes

**Logs**
See log here

**Additional context**
Add any other context about the problem [here](https://1drv.ms/t/s!Ao6WCX2miTCJjLFykgHo7P_ZFhxGiw?e=vsvYDE).

**Comment by charettepa** [comment]
as of a few hours ago mine is stuck needing reauthentication
correct info entered, says its accepted, then within seconds says its needs reauth again

**Comment by tteck** [comment]
re-authentication loop here also

**Comment by grandchamp** [comment]
Same here. Authentication loop. Together with Tuya offline today is not a good day for IoT world. 😅

**Comment by Warble68** [comment]
Also here. I'm just going to disable it for now, just so I don't lose my mind reauthenticating it every 5 minutes.  My guess, the problem is at Amazon and not Alexa Media Player.  I love this integration.

**Comment by rwarner** [comment]
Same here, also in an authentication loop after the integration says successfully re-authenticated.

**Comment by monsieurlatte** [comment]
Auth loop here too.

**Comment by alandtse** [comment]
The reported issue isn't an auth loop and is reporting a login issue with HA which I can't control. For those of you with a reauth issue, please follow the reported auth issue at #1373.

**Comment by thorrrr** [comment]
Hello i never said you can control it. I am asking as yours is the only intergration which will not sign in could you please tell me where it is failing? So i can go to the point of failure. I sent all the logs and info a requested

**Comment by poudenes** [comment]
I had same issue. When I restart HA then the integration can't load because of server down issue. When HA is restarted fully and I disable and reenable the integration its working again.

I use a Add-on Cloudflared to create a tunnel from Cloudflare and HA. on HA in use NPM to redirect subdomains to their right point. NPM also creates the SSL Certs. On Cloudflare I changed SSL/TLS to FULL so the certs from NPM will be used.

Why the intergration can't login by itself at a certain point after HA is restarted I don't know

**Comment by alandtse** [comment]
> I had same issue. When I restart HA then the integration can't load because of server down issue. When HA is restarted fully and I disable and reenable the integration its working again.
> 
> I use a Add-on Cloudflared to create a tunnel from Cloudflare and HA. on HA in use NPM to redirect subdomains to their right point. NPM also creates the SSL Certs. On Cloudflare I changed SSL/TLS to FULL so the certs from NPM will be used.
> 
> Why the intergration can't login by itself at a certain point after HA is restarted I don't know

Please open a new issue. OP's issues were tied to the `alexa` integration with cloudfare and also probably had some reauth tied to Amazon's switch on websocket implementations.
