### ISSUE TITLE
Multiple reauth requests after successful login

### ISSUE THREAD

**Issue by TheDarthFather** [custom-components/alexa_media_player#1373]
**Describe the bug** & **To Reproduce**

After the last restart, the integration asked for reauthentification.
After reauthentification, the integration apeared 3 times on the page (used to have 2  on the page since 1 year). 
I tried a few more times ... every time one more integration apeared.
The system works ... there is one connected instance .. but having another 6 disabled ones is 'not perfect' :)

**Expected behavior**
Have 1 instance of the integration .

**Screenshots**
![image](https://user-images.githubusercontent.com/23462204/135772285-d4591ff1-12fe-4fe3-a37e-8a145c4232a1.png)

**System details**
 - Home-assistant (version): core-2021.9.7
 - Hassio (Yes/No): No (docker)
 - alexa_media  (version from `const.py` or HA startup): 3.10.8
 - alexapy (version from `pip show alexapy` or HA startup): 1.25.1
 - Amazon [2FA is enabled]: Yes

**Logs**
alexaapi.get_guard_details((<alexapy.alexalogin.AlexaLogin object at 0x7f970071bee0>,), {}): An error occured accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments: ('Login error detected; not contacting API',)
11:34:18 PM – (WARNING) /usr/local/lib/python3.9/site-packages/alexapy/helpers.py - message first occurred at 11:29:09 PM and shows up 58 times
alexaapi.get_guard_details((<alexapy.alexalogin.AlexaLogin object at 0x7f970071bee0>,), {}): A login error occured: An exception of type JSONDecodeError occurred. Arguments: ('Expecting value: line 1 column 1 (char 0)',)
11:34:16 PM – (WARNING) /usr/local/lib/python3.9/site-packages/alexapy/helpers.py - message first occurred at 11:29:09 PM and shows up 6 times

**Comment by TomLyon** [comment]
Having the same issue all of a sudden, getting 2FA spammed on my phone.

**Comment by wzaatar** [comment]
I can confirm I'm having the same issue. Tried disabling 2FA and using username/password combo. Authenticates but then breaks a couple seconds later, generating a new instance.

**Comment by michaelkempin** [comment]
Same problem here. Thought it was because I was messing around with local Tuya. Glad to see I'm not the only one it went crazy one. Hoping to just remove it for now until it's fixed.

**Comment by alandtse** [comment]
Remove the integration, restart HA, and then readd.

**Comment by wzaatar** [comment]
@alandtse, done. Didn't fix the issue.

**Comment by alandtse** [comment]
Please generate a log showing the login. The template shows how to generate the login logs. Please make sure to scrub your logs of private info before posting.

**Comment by Warble68** [comment]
So.... just uninstall, reboot HA, then reinstall?  Is there any other data I need to remove before I reinstall?

**Comment by alandtse** [comment]
> So.... just uninstall, reboot HA, then reinstall? Is there any other data I need to remove before I reinstall?

If you are able to enable the logs before reboot, that may help show what is going on. Typically a uninstall and reinstall of the integration should solve the login errors but it will not clear any old notifications.

I saw the reauth issue this morning and had to relog again this afternoon (about 30 minutes ago). So at least in the US it looks like relogins are still working.

**Comment by tteck** [comment]
I think Amazon has an issue, same problem if you go to https://www.amazon.com/a/settings/approval

**Comment by wzaatar** [comment]
@alandtse, I think it's probably something that has to do with Amazon's authentication. They may have done something that breaks the existing implementation. I have 2 different instances not connected to each other using separate Amazon accounts that stopped working at the same time.

**Comment by charettepa** [comment]
having same issue here. removing readding did not help.

**Comment by wzaatar** [comment]
I disabled 2FA earlier in the day and just attempted to login. All came back online!

**Comment by tteck** [comment]
It appears Amazon has corrected their issues
everything works as it should

**Comment by TheDarthFather** [comment]
Indeed. 
I did not reinstalled anuthing - just reconfigure and login again on Amazon. 
Also, after a HA restart all my "invalid instances" of the integration disapearead.
