### ISSUE TITLE
Does not start after upgrade to 2021.10.0 - No module named 'authcaptureproxy'

### ISSUE THREAD

**Issue by cerebrate** [custom-components/alexa_media_player#1375]
**Describe the bug**

Integration does not start after Home Assistant is upgraded to 2021.10.0.

**To Reproduce**
1. Upgrade Home Assistant to 2021.10.0 (in my case, by changing Docker image spec to _ghcr.io/home-assistant/homeassistant:2010.10_ ).
2. Restart Home Assistant (in my case, updating the HA deployment above).
3. Check permanent notifications, which indicate that alexa_media could not be started and to check logs.

Note: issue persists after multiple restarts.

**Expected behavior**

Alexa Media Player loads and runs as before.

**System details**
 - Home-assistant (version):  2021.10.0
 - Hassio (Yes/No): No.
 - alexa_media  (version from `const.py` or HA startup): 3.10.8
 - alexapy (version from `pip show alexapy` or HA startup): 1.25.1
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: Yes.

**Logs**

The following error appears in the log:

2021-10-06 18:56:11 ERROR (MainThread) [homeassistant.setup] Setup failed for alexa_media: Unable to import component: No module named 'authcaptureproxy'

No integration-specific errors are seen.

**Comment by hudsonbrendon** [comment]
Same problem here, I reinstalled the component, reconfigured the integration, but it doesn't pass the login step on the amazon website.

**Comment by alandtse** [comment]
Closing since it's old and not really something I can address. The solution is to remove and readd the integration so HA will reinstall deps.
