### ISSUE TITLE
Persist volume_level after HA restart

### ISSUE THREAD

**Issue by chemelli74** [custom-components/alexa_media_player#1394]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**
At each HA restart, `volume_level` attribute is missing.
That means that all automations based on that fails until something is played on the device as this action add back the volume_level attribute.

**Describe the solution you'd like**
Make this attribute persiste between reboots.

**Describe alternatives you've considered**
Only known alternative is to send a fixed value to echo device to get the attribute back.

**Additional context**

**Comment by energywave** [comment]
Absolutely my support for this request! I believe the integration can persist the volume level between restart with more ease than we can do using automations that are a workaround.
I commented a previous issue of 2019 that was closed even if now in 2021 nothing is changed.
https://github.com/custom-components/alexa_media_player/issues/490#issuecomment-955687057

**Comment by ErikT80** [comment]
Absolutely agree! Great idea.. I now have a workaround where I set te volume levels of all echo's after a restart. This way the volume_level attribute is present again

**Comment by Reinqusito** [comment]
Tag along this!

**Comment by chemelli74** [comment]
avoid closing

**Comment by chemelli74** [comment]
Avoid stale

**Comment by chemelli74** [comment]
Avoid stale

**Comment by parker-hemphill** [comment]
Avoid going stale

**Comment by energywave** [comment]
Please reopen

**Comment by calas80** [comment]
Please reopen

**Comment by marco-hacs** [comment]
Absolutely my support for this request!

**Comment by jckickflip** [comment]
Still an issue
