### ISSUE TITLE
last_notification attribut

### ISSUE THREAD

**Issue by Pirol62** [custom-components/alexa_media_player#1397]
**Describe the solution you'd like**
I would like to have the last notification content stored in an attribut of the media_player entity "Last_notification_text"

**Describe alternatives you've considered**
I tried to put the output text into an input_text entity. (I know, when I want to store the targets and the time, then I need a variables entity). But doing this, it is necessary to write a script which manages all notifications and simply call the script instead of the notification service. I have around 50 alexa notifications. It will work but has at least one disadvantage: It works only for one single outut target. I don'T know, if the targets can be transferred as a list (In my tests it didn't work).
So in my architecture thinking the best place to keep the output is the function which calls the amazon service.

Use case:
I often have the situation, that alexa informed about something but I was on the phone or in the garden and could only recognize, that alexa said something but not what. Asking her what she already said would be great.

**Comment by alandtse** [comment]
I looked into this before. If I recall correctly it doubles the amount of queries we make to the API since every time there's a command we have to get the list of activities to extract the last command made. Given we're not sure why people are seeing so many reauth requirements, I'm reluctant to put further pressure on the API. However, if someone wants to add it as an optional feature that can be enabled, I won't oppose it.

**Comment by Pirol62** [comment]
Wouldn't it be an idea to simply catch the content before pushing it into the api? So that you can update that attribute later or provide a new entity 'sensor.alexa_whatelse_last_message'?

**Comment by alandtse** [comment]
You mean only the content provided to the component? That adds additional complexity to parse it intelligently and also means the component will have a local state untethered to Amazon's info. If it's going to be done, it's going to be scraping the information from Amazon I think.

**Comment by Pirol62** [comment]
For everyone who is interested. 
In germany alexa provides such a function. With: "alexa, what was your last reminder" you will get the information about it. 
I assume that it will work at least in USA and UK as well.
