### ISSUE TITLE
Every day asking for otp

### ISSUE THREAD

**Issue by antoweb** [custom-components/alexa_media_player#1398]
**Describe the bug**
After last update the component is asking me the otp every day almost 1 time for day

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details**
 - Home-assistant (version): 
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: 

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by ottelo9** [comment]
Same problem here! Germany.

**Comment by Nirolfix** [comment]
Hi there, I have the same problem.

**Comment by Foguet** [comment]
Hi, Another with the same problem (and I checked that my Amazon password is working) In my case show a warning that the password is incorrect, but I did double check and password is correct.

**Comment by RandomUser99** [comment]
Same. Asking for OTP which I put in and now it's saying my password is incorrect.

**Comment by CyberGrim** [comment]
I'm also experiencing the initial bug in this thread (having to reauthenticate every day). Reauthentication is successful, just a pain having to do it every day. Only been happening since this week, Monday/Tuesday maybe?

**Comment by alandtse** [comment]
Please +1 instead of a me too post unless you're able to add additional details. Please also provide logs. Amazon has been rejecting websocket connections again so the frequent reconnects could be the result of the increased polling when we're unable to establish a websocket (i.e., 1 minute vs 10 minutes). You can try reducing the polling frequency when you add the integration to see if Amazon is disconnecting frequent polling.

**Comment by antoweb** [comment]
I have configured the built in otp generating an apposite token for the integration but maybe is ignored

**Comment by chemelli74** [comment]
Hi, confirmed the issue here as well:

`2021-11-05 01:39:50 WARNING (MainThread) [alexapy.alexalogin] No access token found; falling back to credential login instead of oauth.`

**Comment by alandtse** [comment]
> `2021-11-05 01:39:50 WARNING (MainThread) [alexapy.alexalogin] No access token found; falling back to credential login instead of oauth.`

If you see this, you have to remove and readd the integration and make sure that you've enabled oauth token login. If you're not using oauth tokens, you'll have to reauth regularly.

**Comment by antoweb** [comment]
Reauth regularly but not every day :-)

**Comment by genebean** [comment]
I was having this too. I had set mine up before the OAuth token was available so I deleted and re-setup. Only mentioning in case knowing the old methodology was also impacted.

**Comment by bpallagi** [comment]
Hi, +1  having this problem almost every day.

**Comment by ucalegonte** [comment]
Same problem here. Asking for OTP every 1 or 2 days.

**Comment by jasonmadigan** [comment]
Seeing similar to others. Getting an `unknown error` on re-trying auth

Some logs:

```
Logger: aiohttp.server
Source: custom_components/alexa_media/config_flow.py:383
Integration: Alexa Media Player (documentation, issues)
First occurred: 17:36:03 (16 occurrences)
Last logged: 17:47:13

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 138, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 246, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 320, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/alexa_media/config_flow.py", line 356, in async_step_user
    return await self.async_step_start_proxy(user_input)
  File "/config/custom_components/alexa_media/config_flow.py", line 383, in async_step_start_proxy
    self.proxy.session.cookie_jar.update_cookies(
AttributeError: 'AsyncClient' object has no attribute 'cookie_jar'
```

**Comment by Nirolfix** [comment]
Hi,
This screenshot may help in somehow:

![Alexa](https://user-images.githubusercontent.com/40688216/141079678-36510e31-7744-4100-a4e2-195b029fb045.JPG)

As you can see below seems to be too many calls:
"**_Relogin required after 2 days, 20:48:07.953900 and 24242 api calls._**"

**Comment by gtjamesa** [comment]
@Nirolfix My api calls are also upwards of 20k when it asks for reauthentication

**Comment by rahaaas** [comment]
+1

On the initial reauthorisation dialog, entering the 2FA (via Authenticator), takes me to the larger ‘Legacy Configuration’ dialog, which continually gives a 'There was a problem Your password is incorrect’ error. 

It’s definitely correct. Have tried changing the password, but same error. Have managed to randomly reauth a couple of times, but now it’s stuck on this. Trying the Built-in 2FA gives the same error too.

Stuck like this, I can’t delete and reinstall the integration until it’s reauthorised. Would this be an additive option to provide?

**Comment by ottelo9** [comment]
at the moment I get no reauth messages. I removed and readd the Integration and fill the cookies section + use oauth token. I increase the polling time to 10minutes.

**Comment by bralez** [comment]
> +1
> 
> On the initial reauthorisation dialog, entering the 2FA (via Authenticator), takes me to the larger ‘Legacy Configuration’ dialog, which continually gives a 'There was a problem Your password is incorrect’ error.
> 
> It’s definitely correct. Have tried changing the password, but same error. Have managed to randomly reauth a couple of times, but now it’s stuck on this. Trying the Built-in 2FA gives the same error too.
> 
> Stuck like this, I can’t delete and reinstall the integration until it’s reauthorised. Would this be an additive option to provide?

Same for me, but after Core restart the integration works; this behavior every 2 or 3 days.

**Comment by PRich13** [comment]
+1 

frequent reauths and I get an "unknown error" when trying to reauth. I have to remove and re-add the intergration each time.

**Comment by iamandymcinnes** [comment]
I've also tried reinstalling the integration and tried both the 2FA code from authenticator and tried with the 2FA proxy. The former just asks for reauthentication every day and the latter fails at the last step of the auth flow when you click to say it registered successfully in your amazon app authentications.

**Comment by martin3000** [comment]
> 2021-11-11 14:38:12 DEBUG (MainThread) [alexapy.alexalogin] Successfully registered Martin's Alexa Media Player device with Amazon
> 2021-11-11 14:38:12 DEBUG (MainThread) [alexapy.alexalogin] New access token received which expires at 2021-11-11 15:38:12.588894 in 0:59:59.999958

The token is only valid for 1 hour!

**Comment by genebean** [comment]
Logs from just now:

```python 
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/alexa_media/config_flow.py:383 
Integration: Alexa Media Player (documentation, issues) 
First occurred: 3:59:50 PM (3 occurrences) 
Last logged: 4:00:44 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 92, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 138, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 246, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 320, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/alexa_media/config_flow.py", line 356, in async_step_user
    return await self.async_step_start_proxy(user_input)
  File "/config/custom_components/alexa_media/config_flow.py", line 383, in async_step_start_proxy
    self.proxy.session.cookie_jar.update_cookies(
AttributeError: 'AsyncClient' object has no attribute 'cookie_jar'
```

**Comment by chemelli74** [comment]
> I removed and readd the Integration and fill the cookies section + use oauth token. I increase the polling time to 10minutes.

What did you fill in the cookies section ? I never used it honestly.

Simone

**Comment by Pirol62** [comment]
Hmm..I'm confused a little. Here, I receive a 2FA code from amazon without having done something. Doday even 2 times at 07 and 08h. When I'm fast enough, I simply have to enter that and everything's fine (getting the 2FA via SMS). If not, then restart in order to receive a new 2FA, which appears even during the restart of HA. I never have to fill a captcha or something else.
Now, I already chaged the prefered methor to use an authenticator app in hope, that I can avoid the restart.
My question: do I have to reinstall the solution as well? Do I have too many api calls? I have no window, which shows this information.

**Comment by bralez** [comment]
Today the authorization dialog worked and no "Legacy Configuration", only OTP with authenticator (core restart required).

Here the notification dialog:
"Reauthenticate dummy@gmail.com on the Integrations page. Relogin required after **2 days**, 21:47:52.229177 and **24753 api calls**."

**Comment by MichalKurzewski** [comment]
anyone knows what is generating that many calls?
i use this integration like once or two times a day (as an announcment TTS) and still get like 3k between each reconfiguration prompt

**Comment by alandtse** [comment]
Every minute it makes six API calls to pull status on various things.

**Comment by Pirol62** [comment]
But that are 8600 calls a day and not 24000

**Comment by alandtse** [comment]
> But that are 8600 calls a day and not 24000

You're welcome to review the [code](https://github.com/custom-components/alexa_media_player/blob/dev/custom_components/alexa_media/__init__.py) to count how many it can be. The six is just the basic maintenance without any devices. Each device can add multiple calls to that number.

**Comment by Pirol62** [comment]
> > But that are 8600 calls a day and not 24000
> 
> You're welcome to review the [code](https://github.com/custom-components/alexa_media_player/blob/dev/custom_components/alexa_media/__init__.py) to count how many it can be. The six is just the basic maintenance without any devices. Each device can add multiple calls to that number.

Ah ok, that was not clear to me. Thank you. Then I see no chance to reduce the calls. If you have at least one device in each room, which is the basic idea, then you have a lot of api calls per household.
But that should not be a problem for AWS. I don't know what they are doing there....

**Comment by mcquaim** [comment]
Is there a solution for this?

It's really annoying, every morning at 6am I get the OTP code text from Amazon. It doesn't let me enter this code though.

I have to restart HA, this then prompts another OTP code, this then allows it's to be accepted. 

However, I still need another reboot of HA for the entities to be accessible.

Do I need to remove the integration and reinstall it for this to stop?

Thanks

**Comment by MichalKurzewski** [comment]
I did that and it didn't work

**Comment by Nirolfix** [comment]
Hi @mcquaim 

The same for me. I don't know if there is a solution. I think I give up and I'll uninstall this integration. As you just sai It's really annoying.

> Is there a solution for this?
> 
> It's really annoying, every morning at 6am I get the OTP code text from Amazon. It doesn't let me enter this code though.
> 
> I have to restart HA, this then prompts another OTP code, this then allows it's to be accepted.
> 
> However, I still need another reboot of HA for the entities to be accessible.
> 
> Do I need to remove the integration and reinstall it for this to stop?
> 
> Thanks

**Comment by Pirol62** [comment]
I already changed to build in authentication. I simply deleted the integration in the integrations screen and added it new. There are tutorials on YouTube available. Everything worked right after this procedure but I had errors with the API updates. These errors disappeared after a HA restart for 8 hours now. Let's see the next hours if it's stable.
