### ISSUE TITLE
[FR] Add reload menu to the integration page

### ISSUE THREAD

**Issue by chemelli74** [custom-components/alexa_media_player#1401]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**
Would be handy to have a reload integration menu to make this action easy and quick.

**Describe the solution you'd like**
Add the menu like per screenshot below.

**Describe alternatives you've considered**
Restarting HA.

**Additional context**

![image](https://user-images.githubusercontent.com/57354320/140603714-2ec3cf1f-ca5b-4106-8dc9-70abd043078b.png)

**Comment by alandtse** [comment]
That's controlled by HA. It is there already.

![image](https://user-images.githubusercontent.com/7086117/140623744-6a217aa1-6efa-4228-ba94-c761db293902.png)
