### ISSUE TITLE
Reauth pop up description says aborted even when successful

### ISSUE THREAD

**Issue by somar05** [custom-components/alexa_media_player#1404]
**Describe the bug**
It's not really a bug, because the integration still working properly. Just the description when a reauthentication is need it, say "Abort" in the tittle ('abortado' in spanish) even if the reauthentication has been satisfactory

**To Reproduce**
Follow reauthentication procedure when asking, and finish it

**Expected behavior**
Pop up title: succesfully

**Screenshots**
Sorry, not taken

**System details**
 - Home-assistant (version): 2021.11.1
 - Hassio (Yes/No): yes
 - alexa_media  (version from `const.py` or HA startup): 3.10.10
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled]: yes

**Logs**
This is not a log. It's a piece of translation file:
```
  "config": {
    "abort": {
      "forgot_password": "The Forgot Password page was detected. This normally is the result of too may failed logins. Amazon may require action before a relogin can be attempted.",
      "login_failed": "Alexa Media Player failed to login.",
      "reauth_successful": "Alexa Media Player successfully reauthenticated."
    },
```

**Additional context**
n/a

**Comment by eugeneniemand** [comment]
I came here to report the same

![image](https://user-images.githubusercontent.com/6813309/140701787-50aa5d69-5092-458d-840e-360e25244b6d.jpeg)

**Comment by alandtse** [comment]
Thanks, I should probably sticky this since it's been asked before. That language is coming from HA. They only allow "abort" for in-progress config flows last I checked so until they fix it to allow another way to end a config flow, I don't have control over that.

**Comment by allenporter** [comment]
For what it's worth is tracked in #47135 -- just came across this when searching.
