### ISSUE TITLE
State of Media Player card doesn't reflect the actual playing content

### ISSUE THREAD

**Issue by Stooovie** [custom-components/alexa_media_player#1408]
**Describe the bug**
States of Media Player cards (either the default one or the Mini Media Player custom card) do not update unless I interact with the card (open details, adjust volume slider or push any button). 

For example, I play Spotify Connect to a Echo Dot. State of the Echo Dot card does not reflect the song being played until I somehow interact with the card. 

Otherwise, the integration works fine. Other media integrations do not have this issue.

**To Reproduce**
1. play content to an Echo device
2. lovelace card of that Echo device doesn't reflect what's being played
3. push a button on that card, or adjust volume. The state will change

**Expected behavior**
State of the card reflects what's being played.

**Screenshots**
![Screen Shot 2021-11-10 at 16 58 58](https://user-images.githubusercontent.com/10572373/141149285-adfbba43-5e37-4d4d-8573-8680d64aceb8.jpg)

**System details**
 - Home-assistant (version): 2021.11.1
 - Hassio (Yes/No): Yes
 - alexa_media : 3.10.10
 - alexapy (version from `pip show alexapy` or HA startup): 1.25.1

**Logs**
https://0x0.st/-5GX.zip

**Comment by alandtse** [comment]
This is the result of the fact websocket is broken. The component only polls if you control the media player in HA so it knows its active. Outside changes will eventually desync since the component does not continue to poll a device once it stops playing.

So if you're interacting outside of HA, there is no way for the component to know and keep you synced.

**Comment by alandtse** [comment]
I'll try to fix the websocket, but won't be trying to fix this issue. If you want this component to update while in the broken websocket state, use the component only to control the media player. Otherwise rely on the external media player.

**Comment by Stooovie** [comment]
So there's nothing I can do about it, right?  Thanks for the info.

**Comment by alandtse** [comment]
If you only use the component to control media then it will know to poll and will keep itself updated. That's the only way.
