### ISSUE TITLE
Interrupção recorrente da funcionalidade da integração do Alexa Media Player

### ISSUE THREAD

**Issue by mdanilohome** [custom-components/alexa_media_player#1410]
A integração da Alexa Media Player está parando de funcionar frequentemente. Os scripts criados com as mensagens que compõem a automação, como por exemplo aviso de porta aberta, param de responder  de forma inesperada . Reinicio o Home Assistant e na aba de integração, na maioria das vezes aparece na integração da Alexa a mensagem de que não foi carregado. Para restabelecer o funcionamento, sou obrigado a excluir a integração e ao tentar instalar,  após digitar o código de verificação de duas etapas no site da Amazon, permanece indefinidamente numa tela " Carregamento do próximo passo da Alexa Media Player" e não conclui a integração.  Ao longo do dia sigo tentando repetidas vezes até que em um dado momento a integração é efetivada.

**Comment by alandtse** [comment]
I can only help you in English unfortunately and you'll need to use the template if you're reporting a bug.

**Comment by mdanilohome** [comment]
Alexa Media Player integration is crashing frequently. Scripts created with messages that make up an automation, such as an open door warning, unexpectedly stop responding. I restart Home Assistant and in the integration tab, most of the times the message that it has not been loaded appears in the Alexa integration. To get it back up and running, I am required to delete the integration and attempt to install, after entering the two-step verification code on the Amazon website, it remains indefinitely in a "Upload Alexa Media Player Next Step" screen and does not complete an integration. I continue throughout the day, trying again and again until, in a moment, an integration is effected.

**Comment by mdanilohome** [comment]
@alandtse The update didn’t solve it. Alexa Media Player integration stopped working again and ECHO devices are unavailable in Home Assistant. I deleted the integration and try to re-authenticate and the validation on the Amazon website doesn’t finish.

**Comment by mdanilohome** [comment]
@alandtse sorry for posting in topic #1048. I'm a beginner and I'm trying to find the best way to get help in solving my problem. I don't know if it's a bug. All I know is that the Alexa Media Player Integration is the only one that is crashing for no apparent reason. This started about 8 days ago. I created a specific thread under number #1410, but the only feedback I got was your only stating that you could only help me in English. I made a new post in english but got no response.

**Comment by alandtse** [comment]
Use the bug template as it gets things I need to help you like versions and logs. I've said this in multiple threads now. I won't be responding further.
