### ISSUE TITLE
Available attribute is not being updated in Echo Auto

### ISSUE THREAD

**Issue by burnworld3d** [custom-components/alexa_media_player#1413]
**Describe the bug**
available status is not being updated on alexa devices. first checked with an echo auto, then tested with regular echo dot's unplugging them, and sawing same behavior

**To Reproduce**
Unplug an echo device, wait 2 minutes, check on dev tools in HA that device status, and it will still report available: true

**Expected behavior**
available status should get updated

**Screenshots**
https://puu.sh/IoXEh/828a1f5e29.png

**System details**
 - Home-assistant (version):  latest
 - Hassio (Yes/No):  yes
 - alexa_media  (version from `const.py` or HA startup): latest
 - alexapy (version from `pip show alexapy` or HA startup): latest
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: y

Edit: After couple minutes, the echo dot's status got updated, and available was finally changed (removed), however, i can see still this bug with my Echo Auto, where it says available when is not.

**Comment by alandtse** [comment]
Does the app show status updates to the Echo Auto?

**Comment by burnworld3d** [comment]
> Does the app show status updates to the Echo Auto?

Yes, on Alexa mobile app the echo auto appears offline / online

**Comment by alandtse** [comment]
Please confirm that https://alexa.amazon.com/api/devices-v2/device (fix for your domain): 
1.  Lists the Echo Auto
2. Updates the online key
We are just checking that page.

**Comment by burnworld3d** [comment]
> Please confirm that https://alexa.amazon.com/api/devices-v2/device (fix for your domain):
> 
> 1. Lists the Echo Auto
> 2. Updates the online key
>    We are just checking that page.

Ok, after testing: 

1- Yes, it's listed on the json
2- Is not updating the online status for the echo auto, but it does for others

So looks like a bug on Amazon side, not updating device status for that device with the api. 
I will close the issue, as seems is not related with this component.

As curious note, it actually updates device status on the Alexa mobile android app, but it doesn't on the api one

**Comment by alandtse** [comment]
I wonder if the WebApp can see it changing. If it does, we could try to replicate it there. Otherwise someone would need to reverse the mobile apps.

The other thing to check would be to enable debugging on `alexapy.websocket` and see if any websocket messages come in now for the Echo Auto.

**Comment by burnworld3d** [comment]
> I wonder if the WebApp can see it changing. If it does, we could try to replicate it there. Otherwise someone would need to reverse the mobile apps.
> 
> The other thing to check would be to enable debugging on `alexapy.websocket` and see if any websocket messages come in now for the Echo Auto.

On the alexa.amazon.com webapp doesn't show neither the online nor offline status for echo auto, but it does for the rest of echo devices.

On the android alexa app, it does show the offline status of echo auto when is not connected with the mobile.
As for the reverse mobile app, is outside my skills.

If you have any config command or similar to enable debug on alexapy, i can try.

regards

**Comment by alandtse** [comment]
https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component
