### ISSUE TITLE
Alexa Media Reauthentication Required

### ISSUE THREAD

**Issue by Martynhsmith** [custom-components/alexa_media_player#1417]
I'm getting this regularly - about every 7 days when I go to reconfigure it shows this
![image](https://user-images.githubusercontent.com/11158209/141970415-c05d4c92-dfcf-49c5-bcf6-a27a19ab365b.png)

the captcha doesn't show - if I click on it it shows 
<Error>
<link type="text/css" rel="stylesheet" id="dark-mode-custom-link"/>
<link type="text/css" rel="stylesheet" id="dark-mode-general-link"/>
<style lang="en" type="text/css" id="dark-mode-custom-style"/>
<style lang="en" type="text/css" id="dark-mode-native-style"/>
<Code>AccessDenied</Code>
<Message>Request has expired</Message>
<Expires>2021-11-16T10:29:01Z</Expires>
<ServerTime>2021-11-16T10:36:56Z</ServerTime>
<RequestId>1TT34QG32QCDVF35</RequestId>
<HostId>TZKWeSOgSTaBhHfKlWuKPBE9RNMm9Jfhdq0sywGg44ctAGT2cndtcAOUp/HroF7ddOu2qWEHkJk=</HostId>
</Error>

I then go round in circles for a bit - till I give up and delete the integration and reinstall

What am I doing wrong!

Martyn

**Comment by Piston-Broke** [comment]
Hi
I have the same problem but if you restart home assistant and reauthenticate as soon as it starts up it is fine

**Comment by alandtse** [comment]
Or if you enter anything it will get a new Captcha without needing to reboot.

**Comment by Piston-Broke** [comment]
Not for me I just keep getting a broken image until I reboot
