### ISSUE TITLE
Connect call failed ("99.84.27.18", 443)

### ISSUE THREAD

**Issue by mdanilohome** [custom-components/alexa_media_player#1420]
**Describe the bug**

Alexa Media Player integration is crashing frequently. Scripts created with messages that make up an automation, such as an open door warning, unexpectedly stop responding. I restart Home Assistant and in the integration tab, most of the times the message that it has not been loaded appears in the Alexa integration. 
When I notice that the script messages don't work, I go into settings, integrations and try to reload the Alexa Media Player integration but it has a red outline and says "not loaded". I restart Home Assistant and it still doesn't work again. After restarting Home Assistant, all ECHO devices appear as unavailable in lovelace
To get it back up and running, I am required to delete the integration and attempt to install, after entering the two-step verification code on the Amazon website, it remains indefinitely in a "Upload Alexa Media Player Next Step" screen and does not complete an integration. I continue throughout the day, trying again and again until, in a moment, an integration is effected.

**Expected behavior**
I hope the integration works whenever any voicemail is requested.

**Screenshots**

**System details**
 - Home-assistant (version):  **Home Assistant core-2021.11.3**
 - Hassio (Yes/No): **No** (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  : **Version 3.10.11** (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup): **Version 3.10.11**
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). **Yes**  We will not debug login issues if unanswered: 

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.
**Error is appearing in config.yaml after trying enable debug logging for the component. Config.yaml is attached.**
[LOGs Fails ALEXA INTEGRRATION.pdf](https://github.com/custom-components/alexa_media_player/files/7554714/LOGs.Fails.ALEXA.INTEGRRATION.pdf)
[Error is appearing in config.yaml after trying enable debug logging.pdf](https://github.com/custom-components/alexa_media_player/files/7554715/Error.is.appearing.in.config.yaml.after.trying.enable.debug.logging.pdf)

**Comment by alandtse** [comment]
Your configuration.yaml included user/password info I have removed it from the post, but anyone could've seen it so I recommend you change passwords for anything in that pdf.

The only error in your log indicates a network issue with your HA installation. I can't help you if it can't even reach the server. Please fix the HA computer's network access and ensure the HA machine can connect to https://alexa.amazon.com.

For your logger configuration, you'll need to figure out how to configure that component to add the logging settings as described in the FAQ. PDF screenshots of the logs don't have enough info to really fix issues.

**Comment by mdanilohome** [comment]
Hi @alandtse .Thanks for removing the file. When I prepared the attachments I forgot to hide the passwords. Regarding your observation "network issue with your HA installation", if I understand your observation correctly, I have other integrations such as Tuya, Life 360, Spotify that work perfectly and do not load failure even when I restart HA. Also, every time the HA is restarted, I need to redo the Life 360 ​​integration and right after entering the username and password, the integration is validated. I understand that if there were any network problems, the other integrations would have problems. My problem is specifically communication with the Alexa API. Sorry if my account is not very clear, as I am from Brazil and my English is not very good. So, if I'm having trouble making myself understood, I'm sorry, because I really need your understanding and help. Thanks again for the help.

**Comment by alandtse** [comment]
Again, the logs report that your HA can't connect to alexa.amazon.com. I don't know why that is happening but it isn't anything the component can do since the issue is outside of the component. For all I know Amazon has blacklisted your IP address or you HA has a firewall block in place to Amazon. I will leave this issue open for now, but I can't resolve network issues like this for you.

**Comment by mdanilohome** [comment]
So the logs report the connection problem but still cannot identify the cause.
As for Amazon blacklisting my IP address, I don't believe it, first because I don't know why they would do it and also because I called Amazon support in parallel to try to identify the problem as well. There's a ticket open with Amazon, where support is also working to see what might be going on.

**Comment by alandtse** [comment]
They won't help you with the component but check your mobile app. We emulate that so if you're experiencing issues in the app, it's something tied to your network. If the app is fine, it's your HA machine.

**Comment by mdanilohome** [comment]
You mentioned an important question. In fact I'm also having a problem with the Alexa app, but it's not an ongoing problem. This is the main reason that made me call Amazon's support, because I know they can't help with Alexa Media Player because it's a customized and unofficial integration. It's an intermittent problem. Sometimes when I open the Alexa app, if I'm on the same network where my automation devices are paired, I can't see or command the devices. When I open the application from a different network than the network on which the devices operate, I can view and control these devices. As I mentioned, this is not a constant problem. I can, for example, open the application now on the same network as the devices and be able to view them. What seems strange to me is that this type of problem only happens in the Alexa app. If I open the Smart Life app or Ewelink at any time, while being on the same network as the devices, I can view and control these devices. This issue only happens with the Alexa app. That's why I can't see a fault in the wifi network as the cause of the problem.
