### ISSUE TITLE
Icon mdi:amazon was removed from MDI

### ISSUE THREAD

**Issue by monotonus** [custom-components/alexa_media_player#1421]
**Describe the bug**
I get this from time to time in my logs and I'm not quite sure if it comes this from Alexa Media Player of from Core / Nabucasa Cloud:

Logger: frontend.js.latest.202111090
Source: components/system_log/__init__.py:190
First occurred: 16:00:30 (2 occurrences)
Last logged: 16:33:12

Icon mdi:amazon was removed from MDI, please replace this icon with an other icon in your config, it will be removed in version 2021.12.

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details**
 - Home-assistant (version): 
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: 

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by alandtse** [comment]
We don't use that icon.
