### ISSUE TITLE
Way to figure out if this integration is working/no working in automations

### ISSUE THREAD

**Issue by pushpinder107** [custom-components/alexa_media_player#1431]
Is there a way to ge the state of this integration (working/error/re-auth needed etc) in an automation (as condition) so that I can use backup automations if Alexa Media Player is not working?

I need this because some of my automations require user input to turn off/on lights. If AMP fails due to re-auth, then my automations do not send actionable notifications and I need to run some other automation to toggle lights.

**Comment by alandtse** [comment]
There are [events](https://github.com/custom-components/alexa_media_player/wiki/Configuration%3A-Events) when a reauth is required. You can use that. The wiki has automations that use that.

**Comment by pushpinder107** [comment]
Perfect, got it: https://github.com/custom-components/alexa_media_player/wiki/Examples%3A-Automation#notification-when-amazon-login-required. Thanks.
