### ISSUE TITLE
Can't install because home assistant version not released yet

### ISSUE THREAD

**Issue by vquiering** [custom-components/alexa_media_player#1439]
This integration depends on home assistant 2021.12, but 2021.11.5 is the most recent stable version.

Error message (german): Du benutzt die Home Assistant-Version '2021.11.5', für dieses Repository muss jedoch die Mindestversion '2021.12.0' installiert sein.

https://github.com/custom-components/alexa_media_player/blob/39527160a8be8185a19fcfe338cb0bf66b586f89/hacs.json#L13

**Comment by moskyow** [comment]
Same here

**Comment by alandtse** [comment]
Then don't install it until released.

**Comment by Rappoman** [comment]
Hi Alan, is there a version that can be installed before the release of 2021.12.0?  I have just uninstall a version due to authentication issues and it would appear there is not a version to use.

**Comment by alandtse** [comment]
3.10.12.

**Comment by alandtse** [comment]
I went ahead and changed the 3.10.14 release to a prerelease. This should avoid the HACS bug that is blocking you from installing anything lower. You may have to restart HA so HACS refreshes the data.

**Comment by tteck** [comment]
Can't use with beta, `"homeassistant": "2021.12.0"`  needs to be `"homeassistant": "2021.12.0b0"`?
