### ISSUE TITLE
Echo status not current / updating

### ISSUE THREAD

**Issue by nappyjim** [custom-components/alexa_media_player#1443]
**Describe the bug**
The status of my echo device, for example media_player.echo_office will show as "Stand by", even though its currently playing.  Or if its been playing and I've stopped it, it will still show playing and shows me the last song that was played on it.  In screenshot below, I have been playing music on my echo for over 15 min and it still shows as standby.
 
**To Reproduce**
1. Ask Alexa to play a song
2. Check media_player status

**Expected behavior**
I expect the status to reflect what the actual status is

**Screenshots**
![2](https://user-images.githubusercontent.com/71914301/143637232-ef15fa95-83df-46be-aed8-6fff7e55a332.JPG)

**System details**
 - Home-assistant (version):  supervisor-2021.10.8
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): v3.10.12
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered:  Yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**
I know the overall status of the echo is being "broadcast" if you will because I also have alexa-remote-2 for node red.  And if I check status on that through a 'Get echo player info', it will correctly tell me if its playing or standy, pause, etc.

I dont know how media_player entities get their status vs node red; just wanted to point that out.

I do have these 2 warning in my logs:
[home-assistant.log](https://github.com/custom-components/alexa_media_player/files/7610706/home-assistant.log)
![image](https://user-images.githubusercontent.com/71914301/143651183-3d9bf555-01a8-4d79-904a-2800f5a4e514.png)

If I go to the entity and drag the volume slider, the echo responds accordingly. So I know there is some communication between the integration and my echo's.

[home-assistant.log](https://github.com/custom-components/alexa_media_player/files/7610712/home-assistant.log)

**Comment by sp3cialck** [comment]
Same is happening here, and the next_alarm sensor isn't working as it should, it only updates the state after a HA instance restart!

**Comment by alandtse** [comment]
It's warning you it can't use oauth. You need to remove and readd and ensure you've enabled oauth login. If we can't use oauth, we can't use websocket so the only way it knows to update is if you manually issue a command in HA. If you ask outside of HA, it has no idea that the state has changed.

**Comment by nappyjim** [comment]
@alandtse 

Ok, but did something change?  Cause nothing changed on my end that I know of.  Was working fine up until about 2 weeks ago.   And how do I enable oauth?

**Comment by alandtse** [comment]
Yes. Amazon changed their websocket requirement.

**Comment by nappyjim** [comment]
> Yes. Amazon changed their websocket requirement.

Ok.  When you say "remove and readd"  are you referring to my individual echo's IN the Alexa Media Player?  Or are you saying remove Alexa Media player entirely and re-add?

**Comment by nappyjim** [comment]
To anyone wondering:   

1.  Delete integration HA
2.  Delete integration in HACS
3.  If you have Alexa Media: entry in your config.yaml, delete it.
3. Restart
4. Add integration in HACS
5. Restart
6. Add integration in HA

**Comment by alandtse** [comment]
> To anyone wondering:
> 
> 1. Delete integration HA
> 2. Delete integration in HACS
> 3. If you have Alexa Media: entry in your config.yaml, delete it.
> 4. Restart
> 5. Add integration in HACS
> 6. Restart
> 7. Add integration in HA

Sorry, you can skip step 2 for removing from HACS. You just need to remove and readd to HA.
