### ISSUE TITLE
Unable to install integration from HACS

### ISSUE THREAD

**Issue by Omrizn** [custom-components/alexa_media_player#1451]
I have the latest beta release installed of HA
but still I can not install the integration:

![image](https://user-images.githubusercontent.com/9966076/144701433-001ad6c7-0723-4d21-93fb-23937a1b1959.png)

Thanks in advance!

**Comment by alandtse** [comment]
Enable beta releases and download 3.10.15.

**Comment by Omrizn** [comment]
> Enable beta releases and download 3.10.15.

I don't have this version

![image](https://user-images.githubusercontent.com/9966076/144725178-68e6c72a-10bf-4280-9c61-48fac905adb4.png)

**Comment by alandtse** [comment]
You need to update the information in HACS. It's a menu item on the component.
![image](https://user-images.githubusercontent.com/7086117/144725476-db27d82c-7aae-45f2-892d-6c373b0ba75f.png)

**Comment by alandtse** [comment]
Related to #1446
