### ISSUE TITLE
Announce / Notify service not working

### ISSUE THREAD

**Issue by lhilton** [custom-components/alexa_media_player#1460]
**Describe the bug**

**To Reproduce**
1. Go to Developer Tools -> Services
2. Click on `Go To YAML Mode`
3. Paste this sample YAML:
```yaml
service: notify.alexa_media_everywhere
data:
  message: This is a test
  ```
4. See error popup: `Failed to call service notify.alexa_media_everywhere. Unknown error`

**Expected behavior**
Audio to play through my Amazon Echo devices

**Screenshots**
[Screenshot](https://the.unexpectedreboot.com/1639095321/Screen-Shot-2021-12-09-16-14-42.02.png)

**System details**
 - Home-assistant (version): 2021.11.5
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): v3.10.12
 - alexapy (version from `pip show alexapy` or HA startup): 1.25.2
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

```
Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/alexa_media/notify.py:216
Integration: Alexa Media Player (documentation, issues)
First occurred: 4:09:23 PM (7 occurrences)
Last logged: 4:14:41 PM
websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'NoneType' object is not subscriptable

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 371, in _async_step
    await getattr(self, handler)()
  File "/usr/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 571, in _async_call_service_step
    await service_task
  File "/usr/lib/python3.9/site-packages/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/lib/python3.9/site-packages/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/lib/python3.9/site-packages/homeassistant/components/notify/legacy.py", line 221, in _async_notify_message_service
    await self.async_send_message(**kwargs)
  File "/config/custom_components/alexa_media/notify.py", line 216, in async_send_message
    if data["type"] == "tts":
TypeError: 'NoneType' object is not subscriptable
```

**Additional context**
Docker based installation

**Comment by alandtse** [comment]
Read the wiki. https://github.com/custom-components/alexa_media_player/wiki/Configuration%3A-Notification-Component
