### ISSUE TITLE
Next Alarm sensor not working

### ISSUE THREAD

**Issue by baker0408** [custom-components/alexa_media_player#1466]
I am no longer able to pull the alarm time from the sensor.alexa_device_next_alarm

It was working great until I updated to core-2021.12.1 yesterday. 

Thanks in advance!

**Comment by alandtse** [comment]
Please fill out the template.

**Comment by gkchim** [comment]
I am experiencing the same issue, although i am on Version | core-2021.11.3

**Comment by gkchim** [comment]
Although mine seems to be working now. , I restarted HA and when i went to reconfigure the integration i saw a new checkbox option which i ticked. the checkbox says:

'Include devices connected via Echo'

I'll see if this fix lasts, or i'll have to restart HA again soon
