### ISSUE TITLE
Error after upgrading to Home Assistant Core 2021.12.1

### ISSUE THREAD

**Issue by amorabito** [custom-components/alexa_media_player#1467]
**Describe the bug**
Alexa Media Player seems to be unable to start in latest Home Assistant Core version.

**To Reproduce**
1. Restart Home Assistant

**Expected behavior**
Alexa Media Player starts without ERROR

**Screenshots**
![image](https://user-images.githubusercontent.com/19326838/146430910-9ca6bb7c-4ede-44b0-962a-df4e025d40b2.png)

**System details**
 - Home-assistant (version): core-2021.12.1
 - Hassio (Yes/No): Yes? Running on Raspberry Pi 3B+ 64bit
 - alexa_media  (version from `const.py` or HA startup): __version__ = "3.10.8"
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: n, but login was working fine, seems component does not start up successfully

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

> This error originated from a custom integration.
> 
> Logger: homeassistant.setup
> Source: custom_components/alexa_media/__init__.py:16
> Integration: Alexa Media Player (documentation, issues)
> First occurred: 1:37:55 PM (1 occurrences)
> Last logged: 1:37:55 PM
> 
> Setup failed for alexa_media: unknown error
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/setup.py", line 181, in _async_setup_component
>     component = integration.get_component()
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 522, in get_component
>     cache[self.domain] = importlib.import_module(self.pkg_path)
>   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>   File "/config/custom_components/alexa_media/__init__.py", line 16, in <module>
>     from alexapy import (
>   File "/usr/local/lib/python3.9/site-packages/alexapy/__init__.py", line 16, in <module>
>     from .alexaapi import AlexaAPI
>   File "/usr/local/lib/python3.9/site-packages/alexapy/alexaapi.py", line 21, in <module>
>     from alexapy.aiohttp import ClientConnectionError, ClientResponse
>   File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/__init__.py", line 6, in <module>
>     from .client import (
>   File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/client.py", line 35, in <module>
>     from . import hdrs, http, payload
>   File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/http.py", line 7, in <module>
>     from .http_parser import (
>   File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/http_parser.py", line 15, in <module>
>     from .helpers import NO_EXTENSIONS, BaseTimerContext
>   File "/usr/local/lib/python3.9/site-packages/alexapy/aiohttp/helpers.py", line 667, in <module>
>     class CeilTimeout(async_timeout.timeout):
> TypeError: function() argument 'code' must be code, not str

**Additional context**

**Comment by amorabito** [comment]
This is my first bug related to any Home Assistant software so let me know if I left out anything important!

**Comment by ryanm77** [comment]
Try 3.10.15, it has fixes for HA for 2021.12.1 and beyond.

**Comment by geofffarmer** [comment]
I have this exact same problem. I'm not sure how to install 3.10.15 as suggested.

I go to HACS, Integrations, Explore and Download Repositories, Search for Alexa Media Player, Download this Repository with HACS, Download. Nothing seems to have changed. Restarting HA has no effect.

I can't delete the Alexa Media integration from Integrations either.

**Comment by amorabito** [comment]
@ryanm77 That seemed to work for me.
I went to HACS > Integrations and I did not have an Alexa Media Player integration show up there before.
Explore and Download Repositories, downloaded Alexa Media Player v3.10.15.
Restarted HA. Did not check till morning but Integration is now loading up.

Hope you find some luck @geofffarmer
