### ISSUE TITLE
Thumbs up/down for Pandora

### ISSUE THREAD

**Issue by fluxsmith** [custom-components/alexa_media_player#1470]
When playing from Pandora I have to go to my cell-phone app if I want to send a thumbs up or thumbs down.

I would like a way to add thumbs-up/down buttons to the mini-media player, but before that could even be possible I think the alexa media player would need new underlying capabilities?

**Comment by alandtse** [comment]
Does the Alexa app allow it?

**Comment by fluxsmith** [comment]
> Does the Alexa app allow it?

Yes, it does.  Both in hte app itself with thumbs up/down buttons, and by voice.
