### ISSUE TITLE
Question not error Multiple Amazon Profiles how to Switch

### ISSUE THREAD

**Issue by thorrrr** [custom-components/alexa_media_player#1476]
HI
We have a main Amazon account with all the devices attached.
But the other half who loves music on their account has Amazon Unlimited Music.
How do we best utilise this integration so we can play unlimited music content?

I know you show you can have two accounts but how do you switch over?
Or is it like we do in Amazon now say switch profiles?

**Comment by alandtse** [comment]
Use a custom command to switch profiles.

**Comment by thorrrr** [comment]
Hi Alan
What if we want to be able to do this on any of our devices. 
Do we have to set this custom comment up for each device eg we have 10 alexas so we have to do 10 separate custom commands?

**Comment by alandtse** [comment]
Yes unless you know of a way to do it using the Alexa app with less steps.
