### ISSUE TITLE
TTS stoped working (SOLVED)

### ISSUE THREAD

**Issue by mendoncart** [custom-components/alexa_media_player#1477]
I was about to submit a ticket, but I was able to solve my problem, and I decided to post this here in case of helping someone.
If this is completly useless, you guys can delete this post.

Well, my TTS were working but then stopped.
I've tried to reinstal the component, I reverted to backups when it worked, I followed the FAQ sugestions, nothing "helped".
I was literally writing this ticket when I noticed that my echos were "mute". I say mute in the literal sense of the word, not that my volume was low...
What I mean is: my echos were executing commands, such control the tv, enable/disable do not disturb (with audio effects), playing music everywhere, and so on. But if I asked anything, like "how is the weathe"r, or "what time it was", the ring light would spin and then turn off, and the echo wouldn't say anything, like it has lost its voice,... This happened simutaneosly with both my echos.
After noticing this, I restart both and they started speaking again, then I tested the TTS service and it worked like a charm.
I don't know why this have happened, but if your TTS stoped working, check if your device lost its voice before going in the home assistant rabit hole...

**Comment by alandtse** [comment]
Closed since it's resolved.
