### ISSUE TITLE
Wrong password

### ISSUE THREAD

**Issue by StifflersMoM69** [custom-components/alexa_media_player#1478]
Since today i can not log in anymore. It always says that my password is wrong although it is correct.
I used this integration for about 2 weeks without any problems.
Today i got informed, that i have to reconfigure the integration

**Comment by alandtse** [comment]
Please fill out the template.

**Comment by stueng** [comment]
I had this, had to restart HA to fix it

**Comment by loryanstrant** [comment]
Can confirm I had exactly this issue today. After an update it kept telling me my password was wrong, despite me validating that it still worked.
Found this thread and the previous answer from @stueng - restarted HA and the issue went away.
