### ISSUE TITLE
Text to Speak doesn't work

### ISSUE THREAD

**Issue by Angelos59** [custom-components/alexa_media_player#1488]
I begin by apologizing as I am new to this world. But when using the Text to speech service provided in the Lovelace card, Alexa responds that the service called is not the right one. When I manually use the one below it works. 

service: media_player.play_media
target:
  entity_id: media_player.porch_echo
data:
  media_content_type: custom
  media_content_id: 'play angelos radio on apple music'

I am not able to change this service in the media player but can someone knowledgable take a look and see it it can be done. 

Thanks.

**Comment by alandtse** [comment]
The UI provided by HA will never work with the component. This is documented in the wiki. https://github.com/custom-components/alexa_media_player/wiki#notification-service
