### ISSUE TITLE
sensor.echo_next_timer not updating

### ISSUE THREAD

**Issue by marc115uk** [custom-components/alexa_media_player#1496]
Have noticed when a timer is set on my echo devices, they no longer update, until I reload integration. Same when I stop timer or timer finishes, it carries on counting down then starts counting up until I reload integration. This used to work, showing remaining time on my timers and then going unavailable once timer had gone off or turned off. Think this stopped working on latest update.

**Comment by alandtse** [comment]
Please use the template.
