### ISSUE TITLE
Reconfigure fails to load Captcha

### ISSUE THREAD

**Issue by Hoosier-IT** [custom-components/alexa_media_player#1499]
![image](https://user-images.githubusercontent.com/8570961/151727399-f0972e01-ccc7-44ec-8f6d-83733573aa6b.png)

No way around this. Please resolve or provide work around.

Ping me if more details needed

**Comment by diegomontanaduarte** [comment]
Same issue here!

**Comment by majorsl** [comment]
Mine loads, but is not accepted no matter how carefully I type. But, fyi, seems Alexa is having a ton of issues right now which is probably why the reauth is popping up.

**Comment by pittgo** [comment]
all three of my home assistance installations started getting OTP sent by amazon and all require reauth however won't reauthorize

**Comment by egobuster1** [comment]
getting the same thing. I managed to finally get the captcha to load by typing it incorrectly but no matter what I do it won't auth again even though it says it's successful.

**Comment by alandtse** [comment]
It's been stated before. If you can't see the captcha, enter anything. As the reported issue is resolved, I'll close this. #777 #790
