### ISSUE TITLE
Feature request: Open URL in Silk

### ISSUE THREAD

**Issue by tunerooster** [custom-components/alexa_media_player#1500]
Is there any way to open silk to a specific url.

E.g.,
`Open yahoo.com`
`Open silk at yahoo.com`

I know Silk is supposed to return to the last visited url, but it forgets the last page after a day or so (who knows why).

I expect there is no way to do this, but I thought I would ask...

Thanks!

**Comment by alandtse** [comment]
I believe you're posting on the wrong GitHub.

**Comment by tunerooster** [comment]
Is this not the Alexa Home Assistant custom component project?  My question is concerning using the custom component to open a specific url.  If this is the wrong site, can you point me in the right direction...  Thanks.

**Comment by alandtse** [comment]
I have no idea what silk is. This is the Alexa Media customer component. Perhaps you want https://www.home-assistant.io/integrations/alexa/

**Comment by tunerooster** [comment]
Silk is one of two web browsers which are available in the Alexa Echo Show
devices...

From the wiki documentation it says:

You can now issue a voice command directly to a device as if you're
speaking to it.

service: media_player.play_media
target:
  entity_id: media_player.guest_room
data:
  media_content_type: custom
  media_content_id: 'what time is it'

I can do this:
  media_content_type: custom
  media_content_id: 'open Silk'

This opens Silk as if I had asked for it by voice, as expected.

What I need to do is "open Silk and go to page yahoo.com" , or whatever web
site (URL), or just "open yahoo.com".

There is no way I have found to do this by voice, so it is unlikely your
integration can do it, but I just wanted to ask in case there was a feature
I was not aware of.  Sorry for any confusion in my prior posts!

Thanks for any help you can provide!

**Comment by alandtse** [comment]
Oh. Ok thanks for explaining. If voice doesn't work, perhaps you can [see](https://github.com/custom-components/alexa_media_player/wiki/Developers%3A-Sequence-Discovery) if it can be done with the routines in the mobile app? If it can be done, we can then sniff out the command.

**Comment by tunerooster** [comment]
I checked the app as you suggested...  There is nothing direct, but because of your advice, I did run into an Alexa skill which seems to work for this (i.e., using voice and therefore your "custom" content type), so Thanks!
