### ISSUE TITLE
next_alarm sensor

### ISSUE THREAD

**Issue by sp3cialck** [custom-components/alexa_media_player#1503]
Describe the bug
The next alarm sensor isn't updating after i set an alarm, It updates only after a reload of the Alexa Media Player integration! 

To Reproduce

Set an alarm, checked the alarm status at developer tools tab, no change!
 
Expected behavior
It should change the status to the alarm time set! 

Screenshots

System details

Installation Type | Home Assistant Supervised
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.7
Operating System Family | Linux
Operating System Version | 4.19.0-18-amd64
CPU Architecture | x86_64
Timezone | Europe/Zurich

Home Assistant Cloud
Logged In | false
Reach Certificate Server | timeout
Reach Authentication Server | timeout
Reach Home Assistant Cloud | ok

(Online via AWS - Duckdns)

alexa_media (version from const.py or HA startup): 3.10.15
alexapy (version from pip show alexapy or HA startup): ????
Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). Yes
Logs

Logger: alexapy.alexawebsocket
Source: /usr/local/lib/python3.9/site-packages/alexapy/alexawebsocket.py:232
First occurred: 16:51:57 (1 occurrences)
Last logged: 16:51:57

mac_dms not detected; websocket likely won't connect

**Comment by alandtse** [comment]
Please fill out the template and provide startup logs. Websocket does not appear to be connecting.

**Comment by sp3cialck** [comment]
Unistalled again the integration, this time on the hacs too, installed again, and now it's working!

**Comment by sp3cialck** [comment]
It keeps loosing the connection to the Websocket! What could be?

**Comment by alandtse** [comment]
Lots of things. There's a reason I asked for logs even before you opened the issue. From my perspective, if you wanted help, you would've provided it at the beginning.

**Comment by sp3cialck** [comment]
> Lots of things. There's a reason I asked for logs even before you opened the issue. From my perspective, if you wanted help, you would've provided it at the beginning.

Hmm, i didn't know which log...   
This one?:

https://drive.google.com/file/d/1t0H8t0_ijJafLyiETKVMrURxr6-AeOHC/view?usp=sharing

**Comment by sp3cialck** [comment]
2022-02-07 16:51:40 DEBUG (MainThread) [alexapy.alexawebsocket] WebSocket Connection Closed. 0

Alexapy issue?

**Comment by alandtse** [comment]
You haven't enabled oauth app method login. There's no guarantee you will stay connected or even have websocket. Remove and enable it.

**Comment by alandtse** [comment]
Please delete the pickle file from the custom_component directory and remove and readd.
