### ISSUE TITLE
Temperature sensor not available?

### ISSUE THREAD

**Issue by atv2016** [custom-components/alexa_media_player#1505]
Could have sworn this was available before. 

![Screenshot 2022-02-03 at 06 10 12](https://user-images.githubusercontent.com/16917203/152290826-20cb0a2f-1b4c-4e69-8f00-c6aff0210f50.png)

This also doesn't look good. Overview dashboard shows temperature sensor as unavailable. I know the other sensors only show up when you configure them but pretty sure this one was available before.
![Screenshot 2022-02-03 at 06 11 44](https://user-images.githubusercontent.com/16917203/152290674-6b2ec9aa-7551-4d18-a1e7-484231c6a7cf.png)

I'll put in a official bug report if you need me to, but maybe you can give me some pointers here.
Thanks,

**Comment by alandtse** [comment]
You need to enable them.
![image](https://user-images.githubusercontent.com/7086117/152291129-74cf4275-599d-4cab-8794-0047d0191fa6.png)
