### ISSUE TITLE
ERROR: alexa state report

### ISSUE THREAD

**Issue by jmrocha88** [custom-components/alexa_media_player#1506]
The attributes aren't updating, It updates only after a reload of the Alexa Media Player integration!

Logger: homeassistant.components.alexa.state_report
Source: components/alexa/state_report.py:121
Integration: Amazon Alexa (documentation, issues)
First occurred: 01:21:29 (3 occurrences)
Last logged: 01:21:30

Error when sending ChangeReport to Alexa, could not get access token

Logger: alexapy.alexalogin
Source: /usr/local/lib/python3.9/site-packages/alexapy/alexalogin.py:696
First occurred: 2 de fevereiro de 2022 23:31:50 (13 occurrences)
Last logged: 09:16:50

No access token found; falling back to credential login instead of oauth.

Logger: alexapy.alexawebsocket
Source: /usr/local/lib/python3.9/site-packages/alexapy/alexawebsocket.py:232
First occurred: 2 de fevereiro de 2022 23:31:52 (13 occurrences)
Last logged: 09:16:51

mac_dms not detected; websocket likely won't connect

**Comment by alandtse** [comment]
Remove and readd the component to generate a token. Make sure you're not disabling "Enable oauth-token app method"
The title error about a "state report" isn't from this component anyway.
