### ISSUE TITLE
Missing Text on Setup

### ISSUE THREAD

**Issue by fyford** [custom-components/alexa_media_player#1509]
**Describe the bug**
Installing Alexa Media Player is not rendering any text as per screenshot. I've tried different browsers, template themes and I've tried deleting the whole directory from custom components, I have restarted several times - problem persists

**To Reproduce**
1. Install Alexa Media Player in HACS
2. Install Alexa Media Player in Integrations
3. See error

**Expected behavior**
Not have missing text

**Screenshots**
![image](https://user-images.githubusercontent.com/52793862/152545531-f70a3b05-8d62-49cc-b3d2-6bf7c6447881.png)

**System details**
 - Home-assistant (version): 2022.2.1
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug). Y
 - alexa_media  (version from `const.py` or HA startup): 3.10.15
 - alexapy (version from `pip show alexapy` or HA startup): - not sure how to get this?
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: no

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.
2022-02-04 14:32:24 ERROR (SyncWorker_2) [homeassistant.loader] The custom integration 'alexa_media' does not have a version key in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details
**Additional context**

**Comment by alandtse** [comment]
First try hard refreshing you browser cache. 

If that doesn't work, your installation looks incomplete. We've had a version key for [years](https://github.com/custom-components/alexa_media_player/blob/dev/custom_components/alexa_media/manifest.json#L4). Remove and reinstall using HACS. Ensure that it's completely gone from your `custom_components` folder.
