### ISSUE TITLE
Hue Lights Imported as Integration Alexa Media Player

### ISSUE THREAD

**Issue by mogodon** [custom-components/alexa_media_player#1511]
**Describe the bug**
Alexa Media Player integration "stealing" Hue Lights.

Rolled back to home assistant 2012-10 and couldn't work out why a few of my hue lights weren't working, like one spotlight in four. Looked at the entities list and Alexa Media Player seemed to be the owner of the affected lights! The actuals are still there just punted to light_area_2.

**To Reproduce**
Not sure you can, but just have Hue Lights and Alexa Media Player installed.

**Expected behavior**
In my setup only the Hue Integration should have hue light entities

**Screenshots**
Attached

**System details**
 - Home-assistant (version):  Core 2012-10
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).: No
 - alexa_media  (version from `const.py` or HA startup): alexa_media Version: 3.10.15
 - alexapy (version from `pip show alexapy` or HA startup): alexapy==1.25.3
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered:  No

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway. Not sure that it will show up in the log. Happy to "switch on" the debug logger if there something you wish me to try,

**Additional context**
I've added _amp as a suffix and disabled them so no harm done, just thought it was strange. Attached screenshot.
![amp](https://user-images.githubusercontent.com/14233963/153319775-95c1b48d-2bed-42c9-8ed7-05a7be3a3fbc.jpg)

**Comment by alandtse** [comment]
Disable the option "Include devices".
<img width="389" alt="image" src="https://user-images.githubusercontent.com/7086117/153770411-280c1d2b-cdca-45c7-9be6-7cdd78f0b320.png">

**Comment by mogodon** [comment]
O god, my apologies! Surpised there weren't more then!! Thanks
