### ISSUE TITLE
Question re latest release Not sure if it a bug or not

### ISSUE THREAD

**Issue by thorrrr** [custom-components/alexa_media_player#1516]
HI after latest update today i get this warning

Logger: alexapy.alexawebsocket
Source: /usr/local/lib/python3.9/site-packages/alexapy/alexawebsocket.py:232
First occurred: 08:35:00 (1 occurrences)
Last logged: 08:35:00

mac_dms not detected; websocket likely won't connect

My Ver

## System Health

version | core-2022.2.8
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.98
arch | x86_64
timezone | Europe/London

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4705
Installed Version | 1.22.0
Stage | running
Available Repositories | 977
Downloaded Repositories | 25

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.01.1
docker_version | 20.10.9
disk_total | 30.8 GB
disk_used | 16.3 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), Check Home Assistant configuration (3.10.0), SSH & Web Terminal (10.0.2), Home Assistant Google Drive Backup (0.105.2), Studio Code Server (4.1.0), MariaDB (2.4.0), InfluxDB (4.3.0), Grafana (7.4.1), Mosquitto broker (6.0.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 16
views | 75
mode | storage

</details>

**Comment by alandtse** [comment]
It means your login is messed up so you're using a compatibility layer that only does polling. Nothing will update quickly and the component will basically be command only (with limited updates). Remove and readd the integration to try to fix it and don't disable any default settings.
