### ISSUE TITLE
TTS not working on echo show

### ISSUE THREAD

**Issue by hanzala-123** [custom-components/alexa_media_player#1517]
Hi there, TTS works perfectly on all my echo dots but it does not work on my echo shows. It returns an error message instead. I can play local media through the echo dots and would like to on the shows tool 

Any help would be appreciated, kind regards

**Comment by adocampo** [comment]
Same issue here. Didn't try on echo dot, though, just on echo show and they don't work. It says to see the wiki page.
OTOH, on the service tab, it fails the tes with an unknow message.

**Comment by alandtse** [comment]
Please use the template and try again.

**Comment by adocampo** [comment]
which template? HA's one? 
It shows this
![image](https://user-images.githubusercontent.com/2266612/155135244-b537f941-ce2e-4d5d-9b41-dbb5fffaafda.png)
