### ISSUE TITLE
Fire TV (Cube): Volume Control (external speakers)

### ISSUE THREAD

**Issue by lullerboi** [custom-components/alexa_media_player#1519]
**Describe the bug**
It's not possible to control the volume of speakers connected through HDMI behind a Fire TV Cube

**To Reproduce**

Setup: Fire TV Cube -(HDMI)-> TV -(optical)-> HiFi Receiver
The Cube can control both devices (TV + Receiver). It also comes with the little "remote blaster" box.
Controlling the Volume with the included remote works flawlessly.

1. Set up the Plugin as advised
2. Add a Media Player Card for a Fire TV Device
3. Click on any of the volume Controls
4. The volume of the _internal speaker_ changes

Can only verify on a Fire TV Cube but I think any Fire TV will be affected. The setup should be pretty common.

**Expected behavior**
Volume of my HiFi Receiver should change.

This may of course be a limitation by Amazon because this requires the Cube to send a local command to another device. These devices (TV + Receiver) do not show up in HA when enabling the slider in the configuration menu (this would be even more awesome).
The speakers also don't show up as external speakers like i.e. bluetooth speakers do.

**Screenshots**
N/A

**System details**
 - Home-assistant (version): 2022.2.9
 - Hassio (Yes/No): Yes, running on HA Blue
 - alexa_media  (version from `const.py` or HA startup): 3.10.15 (HACS)
 - alexapy (version from `pip show alexapy` or HA startup): ? sorry, can't find
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: Yes

**Logs**
Nothing helpful as far as I can tell. The command is accepted and applied correctly, but _meant_ otherwise.

**Additional context**
Sorry for bothering if this is an Amazon limitation :)

GREAT work with this plugin, especially the setup through UI. Impressive! 👍 

**E: Work-Around for anyone with similar issues:**

1. Setup routines for "TV on/off" (Individual device(s)) and "Volume Up/Down" (Fire TV menu) in your Alexa App
2. Create scripts to call these routines: [I'm sorry, is there a proper way to quote yaml on github?]
> alias: Fernseher an
>sequence:
> - service: media_player.play_media
>    data:
>     media_content_id: Fernseher an # name from Alexa App
>      media_content_type: routine
>    target:
>      entity_id: media_player.fire_tv_cube
>mode: single
>icon: mdi:television
3. Create buttons in the UI to call the scripts

This does not allow remote mute, however. And it feels delayed, but it works.
Does anyone see a way to "remap" the internal volume control to use this logic if the problem can't be adressed otherwise?

:wave:

**Comment by alandtse** [comment]
Can you do it using the Alexa app? That is what gates what the component does.

**Comment by lullerboi** [comment]
I totally forgot to test that. No, I can't, it does the same (control the internal speaker).
So this is NOT a bug, I'm really sorry. You can of course close this.

But maybe it could be helpful to add my workaround to the docs for others?
This would still be awesome to have a working all-in-one solution:
> Does anyone see a way to "remap" the internal volume control to use this logic?

**Comment by alandtse** [comment]
Thanks. The wiki has open permissions so feel free to document it there.

Also for yaml, I've edited your original message so you can see how to quote it.
