### ISSUE TITLE
Alexa Media Player isn´t available at Integrations

### ISSUE THREAD

**Issue by rseniuk** [custom-components/alexa_media_player#1524]
Hello together,

after install HACS and Alexa Media Player, i can´t install Alexa Media Player at Integrations of Home Assistant.

**Comment by thermopesos** [comment]
You're not alone, it isn't showing up for me either.

**Comment by TammoHeeren** [comment]
Go the HCAS and search using Integrations from that page. You won't find it under HA Integrations.

**Comment by lullerboi** [comment]
Clear your browser cache.

**Comment by alandtse** [comment]
You need to reload your browser cache for it to display after restarting HA. This is a HA limitation. It would be on the Home assistant integrations page.
