### ISSUE TITLE
No option to enter credentials

### ISSUE THREAD

**Issue by TammoHeeren** [custom-components/alexa_media_player#1525]
**Describe the bug**
Upon installation following the guide and using HACS Alexa Media Player is installed but no option is presented to enter credentials..

**To Reproduce**
Install using HACS on latest Home Assistant.

**Expected behavior**
After installation an option to enter credentials is available.

**System details**
 - Home-assistant (version): 2022.02.9
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup): 3.10.15
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). Yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by alandtse** [comment]
It loads a local proxy webpage for Amazon. Please provide logs.
