### ISSUE TITLE
Is there a way to add Alexa to the HA media browser?

### ISSUE THREAD

**Issue by compujunk** [custom-components/alexa_media_player#1527]
Is there a way to add Alexa to the HA media browser?

**Comment by alandtse** [comment]
I'm not sure what you're asking. You mean stream Alexa only services to other devices? No. If you mean stream local files to Alexa, probably not since Alexa relies on services only.

**Comment by jstott1070** [comment]
This may be meaning - is there anyway to allow the media player to be used in conjunction with the new media library functions in HA? For example, at the moment we cant stream media from HA to alexa using this integration or use the medial library selection function if trying to play content as an automation action.

**Comment by compujunk** [comment]
yes I mean the new media library from HA.
You can now cast to googlehome from there but not to the amazon echoes.

**Comment by alandtse** [comment]
Again, Alexa does not let you stream local content and requires an intermediary web server. Until they allow it, you can only have small hacks like this. https://community.home-assistant.io/t/play-a-local-mp3-file-on-alexa-echo-dot/186187/62
