### ISSUE TITLE
Code for generating oauth tokens

### ISSUE THREAD

**Issue by ganlbarone** [custom-components/alexa_media_player#1536]
Is there any library for just generating the oauth token part of this? Just the login. I would like to be able to query the internal amazon apis the app uses but am having a hard time capturing the login flow in Fiddler. Thanks.

**Comment by alandtse** [comment]
This uses alexapy. https://pypi.org/project/alexapy/. Check alexalogin as that handles the token capture. Alternatively, authcaptureproxy may be a good example.
