### ISSUE TITLE
Add Audible audio book support

### ISSUE THREAD

**Issue by Kurisudes** [custom-components/alexa_media_player#1538]
Hello,

I am trying to trigger my Echo Dot to read my Audio book for sleeping with a sleep timer.
However, I cannot find a way to trigger Audible audio books. 
I followed the steps [here](https://github.com/custom-components/alexa_media_player/wiki/Developers%3A-Sequence-Discovery) and got this json
`[{"@type":"com.amazon.alexa.behaviors.model.Automation","automationId":"amzn1.alexa.automation.33f98506-eeb0-4fd0-aa9d-464a4772452a","name":"small brother","triggers":[{"payload":{"customerId”:"XXXXXXXX","utterance":"sequence","utterances":["sequence"],"locale":"en-JP","marketplaceId”:"XXXXXXXXXX"},"id":"amzn1.alexa.trigger.205471de-7ecc-4fdb-b2c3-6f5b5fe77322","type":"CustomUtterance","skillId":"amzn1.ask.1p.customutterance","timeLapse":null,"presentationDataList":null,"imageUrl":null,"clientData":null,"context":null}],"sequence":`

If I can support in the development, please contact me.

**Comment by alandtse** [comment]
A custom command should be able to do it. https://github.com/custom-components/alexa_media_player/wiki#run-custom-command

**Comment by Kurisudes** [comment]
It works! Thank you very much.

**Comment by alandtse** [comment]
It may be helpful for others with your question if you post the command here too as an example.

**Comment by Kurisudes** [comment]
This is my automation for now. But I am not satisfied 100% because it always announces the request and is not just starting like you would play music with home assistant.

`action:
  - service: media_player.volume_set
    data:
      volume_level: 0.03
    target:
      entity_id: media_player.echo_dot
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.bedroom_lamp_zha_group_0x0002
  - service: media_player.play_media
    data:
      media_content_type: custom
      media_content_id: Play Der kleine Bruder on Audible
    target:
      entity_id: media_player.echo_dot
  - delay:
      hours: 0
      minutes: 0
      seconds: 8
      milliseconds: 0
  - service: media_player.play_media
    data:
      media_content_type: custom
      media_content_id: Set a 15 minute sleep timer
    target:
      entity_id: media_player.echo_dot`

**Comment by Lyr3x** [comment]
I bring this up again as custom command stopped working a few days ago it seems. Some commands are working but e.g sleeptimer and start audible do not work anymore. Used that for roughly 3 years now but alexa only responds with something like i dont know what to do.

Anyone else?

**Comment by alandtse** [comment]
> I bring this up again as custom command stopped working a few days ago it seems. Some commands are working but e.g sleeptimer and start audible do not work anymore. Used that for roughly 3 years now but alexa only responds with something like i dont know what to do. Already tried different wording etc. but it just dont work anymore.
> 
> ```
> service: media_player.play_media
> target:
>   entity_id:
>     - media_player.alexa_wohnzimmer
> data:
>   media_content_type: custom
>   media_content_id: stelle einen Sleep Timer auf 30 Minuten
> ```
> 
> Anyone else?

When this happens, test using the Amazon app as a routine. If it doesn't work there, then it's an Amazon issue and the only way to resolve it is to raise it to Amazon.  If for some reason it works in the routine but not in the component, then we may have a bug we can fix. In that case, it's ok to open a new issue given the age of this one.
