### ISSUE TITLE
Deinstall

### ISSUE THREAD

**Issue by minimag450** [custom-components/alexa_media_player#1539]
Hello, when I started with HA I wanted to try many things. But I realised that I don't use players in HA. How can I uninstall the Alexa Media Player?
Regards, Andreas

**Comment by fpfuetsch** [comment]
@minimag450 Check this out: https://github.com/custom-components/alexa_media_player/wiki#uninstalling-integration

**Comment by alandtse** [comment]
@fpfuetsch Thanks!
