### ISSUE TITLE
After completing steps per documentation can’t use Alexa to get a text massage from HA

### ISSUE THREAD

**Issue by Zafrirshha** [custom-components/alexa_media_player#1542]
Hi 

After following the documentation steps only the below entities are available - other 5 no
What I would like to get from this integration is that on automation I will be able to call Alexa media service and that my eco device to use voice announcing what written in text. I get “unknown error” trying to fire the action.

Any idea what I’m doing wrong?
Thanks

 
zafrir's Echo Dot
media_player.zafrir_s_echo_dot
Alexa Media Player
Living Room

 
zafrir's Echo Dot do not disturb switch
switch.zafrir_s_echo_dot_do_not_disturb_switch
Alexa Media Player
Living Room

**Comment by Zafrirshha** [comment]
Found the issue. i used type = TTS instead of announce. now all ok

**Comment by jsantosdias** [comment]
Same problem! When I click call service, it appears to be OK, but alexa doesn't speak... What am I doing wrong? Also tryed TTS...

service: notify.alexa_media
data:
  message: Olá a todos!
  target: media_player.echo_dot_de_joao
  data:
    type: announce

**Comment by jsantosdias** [comment]
I found out my account domain was supposed to be amazon.com, where as I used amazon.es. after changing, it works fine. closing it
