### ISSUE TITLE
Can no longer authenticate

### ISSUE THREAD

**Issue by thefunkygibbon** [custom-components/alexa_media_player#1566]
So as usual HA has updated and Alexa integration seems to have stopped working.
When trying to reauth it doesn't seem to work because the captcha image never loads.  Seems to happen everytime and usually it needs this component to be updated.  But I don't see any other complaints about this so I've no clue why it happens all the time just for me?

Is it a me problem or ?

**Comment by thefunkygibbon** [comment]
If I click on the broken image of the captcha I get

<Error>
<Code>AccessDenied</Code>
<Message>Request has expired</Message>
<Expires>2022-04-11T12:17:38Z</Expires>
<ServerTime>2022-04-13T06:41:35Z</ServerTime>
<RequestId>blahblah</RequestId>
<HostId>blahblah=</HostId>
</Error>

**Comment by alandtse** [comment]
Please search.

**Comment by thefunkygibbon** [comment]
Yeah thanks for the helpful.  Unsurprisingly I have already searched and not found anything of use.  Restarting ha is about the only thing that I saw was a solution that 1 or 2 people suggested... Most other stuff was closed without a solution.   If this is something which happens a fair amount of times , shouldn't the actual solution , whatever that is, be stickied?

**Comment by alandtse** [comment]
Search for captcha. I've answered this tons of times. Github only allows 3 stickie.
