### ISSUE TITLE
Reconfiguration CAPTCHA missing

### ISSUE THREAD

**Issue by GitHubGoody** [custom-components/alexa_media_player#1574]
**Describe the bug**
I was prompted to reauthenticate and reconfigure Alexa Media Player, but the CAPTCHA is missing.

**To Reproduce**
1. Go to Integrations
2. Click on Reconfigure
3. See a placeholder instead of an actual image for the CAPTCHA

**Expected behavior**
A CAPTCHA for me to enter and reauthenticate.

CAPTCHA doesn't load during reauthentication

**Screenshots**
![AlexaMediaPlayerCAPTCHA](https://user-images.githubusercontent.com/46235745/164320073-a0d63bf7-57c3-4c62-9e36-b0d9b6218946.PNG)

**System details**
 - Home-assistant (version): 2022.4.5
 - Hassio (Yes/No): I'm using HA OS. Isn't "Hassio" an outdated term?
 - alexa_media  (version from `const.py` or HA startup): I don't understand where to get this.
 - alexapy (version from `pip show alexapy` or HA startup): I don't understand where to get this.
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: Yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway. N/A

**Comment by Bodge-IT** [comment]
Also if you click the "missing captcha" you get this:
AccessDeniedRequest has expired2022-04-21T16:07:13Z2022-04-22T11:07:51Z5GT0HVH440AFB0TJKFwHh5L2DeQAljK5YLvB53+4sNbI7APJAQ6oI03AlE=
_deleted many randon chars in case this is secret_

**Comment by alandtse** [comment]
This a dupe with a solution already posted. Please search before opening issues.

**Comment by Bodge-IT** [comment]
@alandtse @GitHubGoody posted this before

**Comment by GitHubGoody** [comment]
Sorry, I searched the repo, but not the **closed** issues. Since this is so common, why not update the repo?

It currently states:

![image](https://user-images.githubusercontent.com/46235745/165070806-1105b475-a948-4624-bfb4-bd339f85d2de.jpeg)

You could just add something like "If the CAPTCHA does not appear, enter anything (e.g. 123456) and submit. That should cause the CAPTCHA to appear. Then, you may need to enter the password, CAPTCHA, and 2FA and click submit multiple times before it is accepted."

**Comment by alandtse** [comment]
It's an open wiki. Feel free to edit it.

**Comment by GitHubGoody** [comment]
Oh, cool. I didn't know. I edited it. Thanks again!

**Comment by alandtse** [comment]
Great thanks for your contribution!
