### ISSUE TITLE
After update to 2022.4.6 the state of the media_player entities does not update

### ISSUE THREAD

**Issue by Pirol62** [custom-components/alexa_media_player#1576]
**Describe the bug**
All entities are shown as usual. 
But when i.e starting music the entity remains in standby thus, the volume can not be controlled as well.
Remindes, timers and alarms are not shown as well.

All other functions work as usual: custom commands, speech output etc.

**To Reproduce**

**Expected behavior**
show the state changes of entities

**Screenshots**
![image](https://user-images.githubusercontent.com/48820003/164967523-eeabadef-81e1-46fd-b8e8-8035de57eb58.png)
Last state update was before the HA update obviously

![image](https://user-images.githubusercontent.com/48820003/164967662-6cb5cf3a-5a60-4966-aafd-b17bb7b14614.png)
Spotify is playing - this alexa device should be active

**System details**
 - Home-assistant (version): 2022.4.6
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup): latest
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: y 

**Logs**
no log entries

**Comment by KHOne23** [comment]
same here

**Comment by alandtse** [comment]
Please generate logs or remove and readd the the component. Most likely your credentials are being rejected for the websocket, but again without logs I'm just guessing.

**Comment by chemelli74** [comment]
I have something similar I cannot understand:

```
Process timestamp:  25 aprile 2022, 02:37:17
Prior value:  25 aprile 2022, 07:15:00
Total active:  2
Total all:  2
```

I disabled the alarm at 2,37 this night, but the integration sees it still active ( status: ON ). And UI this morning reports:

![image](https://user-images.githubusercontent.com/57354320/165038227-84a1942e-d47f-45a2-96fd-5cfcc169b25d.png)

(which is exactly 7.15)

While I was expecting a "not available"

Simone

**Comment by Pirol62** [comment]
[alexa_logs.txt](https://github.com/custom-components/alexa_media_player/files/8552367/alexa_logs.txt)
Hi @alandtse, pls find enclosed the debug logs after a restart. Interestingly after todays restart, the issue seem to be solved without having changed anything exept activatig the debugging for alexapy and the component.

**Comment by alandtse** [comment]
If a reboot fixes it, then there's really nothing we can do until it happens again. Please open an issue and then provide logs.
