### ISSUE TITLE
Pip dependency conflict on HA 2022.5

### ISSUE THREAD

**Issue by drthanwho** [custom-components/alexa_media_player#1579]
**Describe the bug**

It looks like there's a pip depency conflict in the latest HA 2022.5 dev version. Beta will be release today too but I assume the conflict will still be there so opening this in advance.

**To Reproduce**
1. Update to HA core-2022.5.0.dev20220427
2. See error

**System details**
 - Home-assistant (version): core-2022.5.0.dev20220427
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): 3.11.2
 - alexapy (version from `pip show alexapy` or HA startup): 1.25.3
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered:  Yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.
```
2022-04-27 12:34:16 ERROR (SyncWorker_6) [homeassistant.util.package] Unable to install package alexapy==1.25.3: ERROR: Cannot install alexapy==1.25.3 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
WARNING: You are using pip version 22.0.3; however, version 22.0.4 is available.
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
2022-04-27 12:34:20 ERROR (SyncWorker_3) [homeassistant.util.package] Unable to install package alexapy==1.25.3: ERROR: Cannot install alexapy==1.25.3 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
WARNING: You are using pip version 22.0.3; however, version 22.0.4 is available.
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
2022-04-27 12:34:24 ERROR (SyncWorker_6) [homeassistant.util.package] Unable to install package alexapy==1.25.3: ERROR: Cannot install alexapy==1.25.3 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
WARNING: You are using pip version 22.0.3; however, version 22.0.4 is available.
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
2022-04-27 12:34:24 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration alexa_media: Requirements for alexa_media not found: ['alexapy==1.25.3'].
2022-04-27 12:34:24 ERROR (MainThread) [homeassistant.config] Platform error: notify - Integration 'alexa_media' not found.
```

**Additional context**

**Comment by IceBotYT** [comment]
Can confirm the issue remains on the beta.

**Comment by dougiteixeira** [comment]
> 
Also smelling problems in version 2022.5.0b0, but there is no error in the logs.

Then I will activate the debug and return here ...
![image](https://user-images.githubusercontent.com/31328123/165590453-b1f89fcd-3177-4eec-9148-bcaa5155c557.png)

**Comment by regevbr** [comment]
> > 
> 
> Also have problems in version 2022.5.0b0, but there is no error in the logs.
> 
> Then I will activate the debug and return here ... ![image](https://user-images.githubusercontent.com/31328123/165590453-b1f89fcd-3177-4eec-9148-bcaa5155c557.png)

Using that version as well - logs show the following error:

```
Unable to install package alexapy==1.25.3: ERROR: Cannot install alexapy==1.25.3 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts WARNING: You are using pip version 22.0.3; however, version 22.0.4 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
```

**Comment by gadgetchnnel** [comment]
By running the `pip` command which Home Assistant runs to install the package without the `--quiet` option I've got the following additional output:

```
The conflict is caused by:
    alexapy 1.25.3 depends on cryptography<36.0.0 and >=35.0.0
    The user requested (constraint) cryptography==36.0.2
```

So it looks like Home Assistant 2022.5 now has a dependency on version 36.0.0 of the cryptography module, while alexapy has a dependency on a version less than this so it will need its dependencies updating.

**Comment by joselito11** [comment]
Manual fix: https://github.com/custom-components/alexa_media_player/issues/1523#issuecomment-1050537525

**Comment by dreimer1986** [comment]
Changing alexapy version in manifest.json to 1.25.5 fixes the problem. Thanks for the quick fix :D

**Comment by jonathanathe** [comment]
> Changing alexapy version in manifest.json to 1.25.5 fixes the problem. Thanks for the quick fix :D

It worked!! Thank you

**Comment by jonathanathe** [comment]
> Changing alexapy version in manifest.json to 1.25.5 fixes the problem. Thanks for the quick fix :D

It worked!! Thank you

**Comment by IceBotYT** [comment]
Works for me as well.

**Comment by dreimer1986** [comment]
Do not thank me. I just watch the progress on alexapy and saw the new version and the fixes in it. Thank @alandtse

**Comment by tasi333** [comment]
> 

Found the manifest.json, in case anyone else is wondering:

/config/custom_components/alexa_media/manifest.json
