### ISSUE TITLE
Documentation Improvement - room aware alexa routines

### ISSUE THREAD

**Issue by ustrucx** [custom-components/alexa_media_player#1589]
Thank you for this great integration! 

**Describe the bug**
Following the documentation on https://github.com/custom-components/alexa_media_player/wiki/Examples:-Automation#room-aware-alexa-routines produces error "Entity ID is an invalid entity ID for dictionary value @ data['entity_id']".

**To Reproduce**
1. Create the echo group and sensor as per https://github.com/custom-components/alexa_media_player/wiki#setting-up-a-last-alexa-sensor
2. Create script for room aware light as per https://github.com/custom-components/alexa_media_player/wiki/Examples:-Automation#room-aware-alexa-routines
3. Execute the script.
4. See error.

**Expected behavior**
Light is turned on at the room the last_alexa echo is.

**System details**
 - Home-assistant (version): 2022.4.7
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): 
 - alexapy (version from `pip show alexapy` or HA startup): Using the SSH & Web Terminal app "pip show alexapy" says not installed.
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered:  Yes.

**Logs running the code below**
Logger: homeassistant.components.script.1651595706148
Source: helpers/script.py:1397
Integration: Script ([documentation](https://www.home-assistant.io/integrations/script), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+script%22))
First occurred: 1:39:49 PM (23 occurrences)
Last logged: 2:47:59 PM

alexa_turn_on_the_lights: Error executing script. Invalid data for call_service at pos 2: Entity ID is an invalid entity ID for dictionary value @ data['entity_id']
alexa_turn_on_the_lights: Error executing script. Invalid data for call_service at pos 1: Entity ID is an invalid entity ID for dictionary value @ data['entity_id']
alexa_turn_on_the_lights: Error executing script. Invalid data for call_service at pos 1: Entity ID # is an invalid entity ID for dictionary value @ data['entity_id']
alexa_turn_on_the_lights: Error executing script. Invalid data for call_service at pos 2: not a valid value for dictionary value @ data['entity_id']

** Log with lower case Area name **
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:146
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 1:21:56 PM (11 occurrences)
Last logged: 3:07:11 PM

[547116544448] Error handling message: extra keys not allowed @ data['data']. Got None (invalid_format)
[547080924128] Error handling message: Entity ID is an invalid entity ID for dictionary value @ data['entity_id']. Got None (invalid_format)
[547098989472] Error handling message: Entity ID is an invalid entity ID for dictionary value @ data['entity_id']. Got None (invalid_format)
[547081203424] Error handling message: Entity ID is an invalid entity ID for dictionary value @ data['entity_id']. Got None (invalid_format)

**Additional context**
This might be an update that made the example outdated so maybe this help other people stuck at the same place. I know the sensor and echo group works because I can send TTS responses to the last called echo and the last called echo will properly say the message, now the error happens on the script I exposed to Alexa via NabuCasa, my code:
```
service: homeassistant.turn_on
data_template:
  entity_id: >-
    {%- set room = states("sensor.last_alexa")|replace('media_player.','') -%}
    {%- if room == "Sala" -%}
      light.sala
    {%- elif room == "Cozinha" -%}
      light.sala
    {%- elif room == "Quarto" -%}
      light.quarto
    {%- elif room == "Suite" -%}
      light.mezanino
    {%- endif -%}
```

**Comment by alandtse** [comment]
The wiki is updated by the community. I'll leave this open, but I don't spend any time on this. Once it's fixed, please close this.

**Comment by Didgeridrew** [comment]
[ustrucx](https://github.com/ustrucx) I have reviewed and tested the example in the wiki and it is working in my instance.  And it works with any of the following as the variable key: `data`, `data_template`, or `target`.
 
In the example you posted, all the comparison values for the `room` variable start with a capital letter. As templated, the sensor will return a slug, so there should be no capitals, spaces, or punctuation other then `_`.  Please format your values as follows and re-test the script:

```yaml
service: homeassistant.turn_on
data:
  entity_id: >-
    {%- set room = states("sensor.last_alexa")|replace('media_player.','') -%}
    {%- if room == "sala" -%}
      light.sala
    {%- elif room == "cozinha" -%}
      light.sala
    {%- elif room == "quarto" -%}
      light.quarto
    {%- elif room == "suite" -%}
      light.mezanino
    {%- endif -%}
```
