### ISSUE TITLE
Component does not start since 2022.5 update

### ISSUE THREAD

**Issue by jtizzel** [custom-components/alexa_media_player#1591]
**Describe the bug**

Component does not start since 2022.5 update

**To Reproduce**
N/a

**Expected behavior**
N/a

**Screenshots**
N/a

**System details**
 - Home-assistant (version): 2022.5
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: Yes

**Logs**

Setup failed for custom integration alexa_media: Requirements for alexa_media not found: ['alexapy==1.25.3'].

**Additional context**

**Comment by saveriospeziali** [comment]
Same here

**Comment by saveriospeziali** [comment]
Downgrading to 2022.4.7 fixed the issue for me

**Comment by shortaj66** [comment]
Same here - Invalid Config after upgrade to 2022.5

Setup failed for custom integration alexa_media: Requirements for alexa_media not found: ['alexapy==1.25.3'].
6:04:14 AM – (ERROR) setup.py

**Comment by yakov-cohen** [comment]
same here
Setup failed for custom integration alexa_media: Requirements for alexa_media not found: ['alexapy==1.25.3'].

**Comment by yakov-cohen** [comment]
I updated the files and it fixed it

**Comment by shortaj66** [comment]
@yakov-cohen thanks for the tip...done the same and also now fixed

**Comment by jtizzel** [comment]
> I updated the files and it fixed it

Ah, yes. I presume you mean to redownload the repository in HACS, because that’s what I just did, and it’s working ok again. Thanks.

**Comment by roechas** [comment]
Yeah, I had same issue after core update to 2022.5. Went to HACS repository and saw I had an update. Updated, restarted, and now its working again.

**Comment by alandtse** [comment]
Yes, we release updates to solve issues. Please update before reporting prior bugs.
