### ISSUE TITLE
Unhandled command: PUSH_MEDIA_PREFERENCE_CHANGE when disliking some songs

### ISSUE THREAD

**Issue by rcesar89** [custom-components/alexa_media_player#1599]
When I'm listennig my musics using this custom functionality, occur the erros below:

Logger: custom_components.alexa_media
Source: custom_components/alexa_media/__init__.py:995
Integration: Alexa Media Player ([documentation](https://github.com/custom-components/alexa_media_player/wiki), [issues](https://github.com/custom-components/alexa_media_player/issues))
First occurred: 11:45:47 (1 occurrences)
Last logged: 11:45:47

Unhandled command: PUSH_MEDIA_PREFERENCE_CHANGE with data {'destinationUserId': 'A*********PDW', 'dopplerId': {'deviceType': 'A3C9PE6TNYLTCH', 'deviceSerialNumber': '7****************************350'}, 'mediaReferenceId': '06541882-cd78-4b55-b011-da52b0787d30:1', 'preference': 'DISLIKE_TRACK'}. Please report at https://github.com/custom-components/alexa_media_player/issues

**Comment by alandtse** [comment]
Thanks. It's reporting what your Echo devices are reporting to each other. I assume this happens when you dislike some media. The integration isn't do anything at this stage.

**Comment by alandtse** [comment]
This needs to be updated to ignore.
https://github.com/custom-components/alexa_media_player/blob/dev/custom_components/alexa_media/__init__.py#L991
