### ISSUE TITLE
Warning logged for deprecation of async_get_registry

### ISSUE THREAD

**Issue by drthanwho** [custom-components/alexa_media_player#1604]
**Describe the bug**
The use of `async_get_registry` to access area, device and entity registries is deprecated as of Feb 2021 and will be removed in the future.  With 2022.6 a warning will now be logged. `async_get` should be used instead. 

To avoid a lot of the same issues being created with the release of 2022.6 might be better to address this before its release.

**To Reproduce**
1. Update HA Core latest 2022.6 dev version
2. Look at the logs for deprecation warning

**System details**
 - Home-assistant (version): core-2022.6.0.dev20220524
 - Hassio (Yes/No):  Yes
 - alexa_media (version from `const.py` or HA startup): 3.11.3
 - alexapy (version from `pip show alexapy` or HA startup): 1.25.5
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: Yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

```
2022-05-24 15:26:36 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for alexa_media using this method at custom_components/alexa_media/__init__.py, line 625: device_registry = await dr.async_get_registry(hass)
```

**Additional context**

**Comment by alandtse** [comment]
Thanks.

**Comment by Wibias** [comment]
Can be done like this! https://github.com/IATkachenko/HA-SleepAsAndroid/commit/424bf0aeeb781f07a0c671fde03c924a6197a1b2

Had the same over at that component!

**Comment by Petro31** [comment]
Seems like I was late to this party, anways here's the log again

2022-05-26 19:22:34 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for alexa_media using this method at custom_components/alexa_media/__init__.py, line 625: device_registry = await dr.async_get_registry(hass)

**Comment by pedolsky** [comment]
In addition: This warning appeares 1 sec before the reported message:

```
Logger: alexapy.alexawebsocket
Source: /usr/local/lib/python3.9/site-packages/alexapy/alexawebsocket.py:232 
First occurred: 08:55:04 (1 occurrences) 
Last logged: 08:55:04

mac_dms not detected; websocket likely won't connect

```

**Comment by alandtse** [comment]
After some research, no need to bump HACS minimum version once this is fixed. https://github.com/home-assistant/core/commit/ed31cc363b3a457ed9249f7cf0386f2ec86e1850

> In addition: This warning appeares 1 sec before the reported message:

This is unrelated to this issue. Please search as you have reduced functionality when you get this warning.
