### ISSUE TITLE
After a restart yesterday, I started to receive setup errors

### ISSUE THREAD

**Issue by Pirol62** [custom-components/alexa_media_player#1606]
**Describe the bug**
since yesterday I receive setup error for the platform light, switch, alarm_control and sensor.

**To Reproduce**
yesterday: simply restart
today: out of nothing

**System details**
 - Home-assistant (version): 2022.5.5
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup): 3.11.3
 - alexapy (version from `pip show alexapy` or HA startup): latest
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: Y

**Logs**
````
Logger: homeassistant.components.light
Source: custom_components/alexa_media/light.py:78
Integration: Licht ([documentation](https://www.home-assistant.io/integrations/light), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+light%22))
First occurred: 10:16:31 (1 occurrences)
Last logged: 10:16:31

Error while setting up alexa_media platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/alexa_media/light.py", line 78, in async_setup_platform
    account = config[CONF_EMAIL] if config else discovery_info["config"][CONF_EMAIL]
KeyError: 'email'

````

**Comment by alandtse** [comment]
Reinstall. For some reason it lost your email address which is fatal.

**Comment by Pirol62** [comment]
Ok, thank you. 
But why do the media_player, the notify platform, and if services is a platform then services as well, work as usual?

**Comment by alandtse** [comment]
That's just an import and unrelated. The use of . says to load it from the component itself. So what is happening is:

Direct import (homeassistant.const import):
`homeassistant -> component`

AMP import (. import):
`homeassistant -> alexa_media -> component`

Functionally it's the same, but was just a style choice.

Now, why this doesn't break everything is unknown.

**Comment by Pirol62** [comment]
Thanks @alandtse . Got it.

The error disappeared by itself. Did nothing.
So we can close this.
