### ISSUE TITLE
Alexa has changed recurrence rules in the notifications API

### ISSUE THREAD

**Issue by alandtse** [custom-components/alexa_media_player#1608]
**Describe the bug**
Amazon no longer appears to use `recurringPattern` for many recurrences and instead uses `rRuleData`
https://alexa.amazon.com/api/notifications

This may not have any immediate impact but the sensors do not specifically handle this use case and should be monitored. The processing of recurrence rules used to be necessary to accurately handle a notification that hit the first instance. After that, the data in Amazon would point to the initial event in the past so the later recurrences had to be hand calculated.

If you are a user, and you notice an alarm/reminder, etc. does not accurately show after the first instance is hit, please provide details on which type of alarm. You should provide the `rRuleData` from https://alexa.amazon.com/api/notifications (fix your domain). See example below.

```json
"rRuleData": {
"byMonthDays": [
28
],
"byMonths": [],
"byWeekDays": [],
"flexibleRecurringPatternType": "EVERY_X_MONTHS",
"frequency": null,
"intervals": [
2
],
"nextTriggerTimes": [
"2022-07-28T07:00:00.000-07:00"
],
"notificationTimes": [
"07:00:00.000"
],
"offset": [],
"recurEndDate": null,
"recurEndTime": null,
"recurStartDate": "2022-05-28",
"recurStartTime": "00:00:00.000",
"recurrenceRules": [
"FREQ=MONTHLY;BYMONTHDAY=28;BYHOUR=7;BYMINUTE=0;BYSECOND=0;INTERVAL=2;"
]
},
```

**Comment by papo-o** [comment]
hello, 
state reminder with all day reccurence not return good timestamp
```
            "rRuleData": {
                "byMonthDays": null,
                "byMonths": null,
                "byWeekDays": null,
                "flexibleRecurringPatternType": "ONCE_A_DAY",
                "frequency": null,
                "intervals": [1],
                "nextTriggerTimes": ["2022-06-19T19:00:00.000+02:00"],
                "notificationTimes": ["19:00:00.000"],
                "offset": null,
                "recurEndDate": null,
                "recurEndTime": null,
                "recurStartDate": "2022-03-02",
                "recurStartTime": "00:00:00.000",
                "recurrenceRules": ["FREQ=DAILY;BYHOUR=19;BYMINUTE=0;BYSECOND=0;INTERVAL=1;"]
            },

```
