### ISSUE TITLE
Setup error after updated to v4.0.0

### ISSUE THREAD

**Issue by wiiNinja** [custom-components/alexa_media_player#1612]
**Describe the bug**

After updated to version 4.0.0, I keep getting this setup error:

Logger: homeassistant.setup
Source: custom_components/alexa_media/__init__.py:174
Integration: Alexa Media Player ([documentation](https://github.com/custom-components/alexa_media_player/wiki), [issues](https://github.com/custom-components/alexa_media_player/issues))
First occurred: 6:48:51 AM (1 occurrences)
Last logged: 6:48:51 AM

Error during setup of component alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/alexa_media/__init__.py", line 174, in async_setup
    CONF_OAUTH_LOGIN: account.get(CONF_OAUTH_LOGIN, True),
NameError: name 'CONF_OAUTH_LOGIN' is not defined

I had completely removed the integration, configuration, and attempted start from the beginning, but the same error occurs every time I restarted Home Assistant.

**To Reproduce**

* Add the integration using HACS
* Configure in configuration.yaml
* Boot up Home Assistant and I can see the error. No other steps are needed to duplicate the issue.

**Expected behavior**

I expect that when starting from scratch, I should be able to successfully add the integration and authenticate.

**Screenshots**

**System details**
 - Home-assistant (version): 2022.5.5
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup): 4.0.0
 - alexapy (version from `pip show alexapy` or HA startup): 4.0.0
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered:  Yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

The two files, alexa_media.(email).get.html  alexa_media.(email).post.html are NOT found because the setup never took place.

**Additional context**

I have tried to uninstall and re-install at least 3 times without success.

**Comment by PcOnline2004** [comment]
Me too. Same error.

**Comment by micium** [comment]
Me too. Same error.

**Comment by khal3d** [comment]
Same error here too!

**Comment by khal3d** [comment]
As a quick fix for us till it gets solved :)

1. Open `custom_components/alexa_media/const.py` and add the following to the line 48
    
    ```py
    CONF_OAUTH_LOGIN = "oauth_login"
    ```
2. Open `custom_components/alexa_media/__init__.py` and add the following to line 70
    ```
    CONF_OAUTH_LOGIN,
    ```


Restart Home Assistant, and open the integrations section as it might require to reauthenticate

**Comment by wiiNinja** [comment]
@khal3d - Yes that works. Thanks for the quick response.

**Comment by bmelim** [comment]
@khal3d - works for me.

**Comment by iMaiconP** [comment]
Thank you @khal3d will try now

**Comment by geeneo** [comment]
works for me 2 tx!

**Comment by micium** [comment]
after next HA reboot a new reathentication is required, is correct ? how to avoid reathentication after reboot? 
thanks in advance

**Comment by alandtse** [comment]
> after next HA reboot a new reathentication is required, is correct ? how to avoid reathentication after reboot? thanks in advance

It will now force a reauthentication if it detects a degraded login. Before, it would let you continue to login but disable features (but then people would open issues constantly saying random things weren't working). If the new behavior is a problem, you'll need to downgrade to the 3.x series.

**Comment by micium** [comment]
I continue to have authentication problems with version 4.0.1.
I did a roll-back to v3.11.3 and everything works fine .. 
Many thanks
