### ISSUE TITLE
Version 4.0 Error,  'Unable to connect to Home Assistant url. Please check the external URL ..'

### ISSUE THREAD

**Issue by RJ-Make** [custom-components/alexa_media_player#1616]
**Describe the bug**
After updating to 4.0, there was a request to re-authenticate. Trying to do so, results in the titled error. I have confirmed the HA instant is accessible via the NabuCasa external url. 

**To Reproduce**
1) Attempt to complete configuration with and without 2FA Perm key. 
2) Results in Titled Error.  

**Expected behavior**
The configuration to complete for a fully external accessible HA instance via NabuCasa

**Screenshots**

<img width="451" alt="2022-05-29_12-46-17" src="https://user-images.githubusercontent.com/8496835/170884303-ef8e48e3-308c-4fc8-aeb3-9392d7bc2157.png">

**System details**
 - Home-assistant (version): 
 Home Assistant Core 2022.5.5
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1

 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
HAOS 

 - alexa_media  (version from `const.py` or HA startup):
  - alexapy (version from `pip show alexapy` or HA startup):
Can no longer get past configuration

 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: 

Yes

**Comment by alandtse** [comment]
This is likely a dupe of #1326. Regardless, need the same level of info in #1326 to help you. The component is testing whether the url you are providing can be reached from the HA server.

**Comment by RJ-Make** [comment]
I uninstalled (and ripped every trace of the integration from the system) re-installed and it now authenticates.

**Comment by charettepa** [comment]
@RJ-Make 

can you please explain the steps you used
when you say you remove dthe integration, are you refering to the alexa integration?

I am experiencing the same issue
my cert is good
my ports are forwarded
my loopback is working
i have full internal access to all ha pages using the the ddns address
the only addresses not working are specifically those pointing to the alexa integration

alan told me to search for proxy issues as my question was off topic
any help would be appreciated

**Comment by stomko11** [comment]
Same here. Since v.4 I cannot connect, get: Unable to connect to Home Assistant url. Please check the External Url under Configuration -> General
My external URL is OK (externally accessible), I am using duckdns with nginx (locally http, externally https), I tried to completely remove the AMP and add it back, but no matter what I try, I still get this error.
I am on latest HAOS with Supervisor (running in VM)

**Comment by charettepa** [comment]
@stomko11 
try setting it up using http://ip:8123 address instead

after many attempts this seems to work
it should get you connected
however it will want to be resetup after avery reboot

**Comment by stomko11** [comment]
Right. This worked instantly.
But what's the permanent fix?

**Comment by charettepa** [comment]
@stomko11 

there does not seem to be one other than using the older 3.x version

**Comment by RJ-Make** [comment]
I believe these are the the steps I took. 

1) Removed the integration
2) Removed repository from HACS
3) Restarted HA
4) Reinstalled the repository
5) Restarted HA
6) Successfully completed config. 

I'm using NabuCasa for remote access.

**Comment by charettepa** [comment]
@RJ-Make 

those are the steps i performed
unfortunately for me, its still a no go on http access

does yours stay connected after a reboot?

**Comment by RJ-Make** [comment]
> @RJ-Make 
> 
> those are the steps i performed
> unfortunately for me, its still a no go on http access
> 
> does yours stay connected after a reboot?

Yes
