### ISSUE TITLE
Invalid Built-In 2FA key

### ISSUE THREAD

**Issue by bjbe70** [custom-components/alexa_media_player#1618]
**Describe the bug**

After every update I have to reconfirm the login credentials to the Amazon service. After reboot of HA I always got a new 2FA key from Amazon automatically and entered this in the HA-Alexa-Integration dialog. And it worked!

But after the last update I get the message "Invalid Built-In 2FA key" after submitting the login data and 2FA key. although I have entered the just received 2FA-Key via SMS from Amazon.

An ideas? Thanks!

**Comment by alandtse** [comment]
Dupe of #1617. Please search before opening new issues.
