### ISSUE TITLE
New connection method requires reauth on every reboot

### ISSUE THREAD

**Issue by charettepa** [custom-components/alexa_media_player#1620]
**Describe the bug**
New connection method requires re-auth/re-setup on every reboot

**Expected behavior**
for it to keep you authorised and remember your setup including the specified address/ip

HA 2022.5.5
Alexa media player 4.0.1

**Comment by sp3cialck** [comment]
Same here!

**Comment by HDP13** [comment]
Igual

**Comment by micium** [comment]
Alan, you already replied to me on Sunday - https://github.com/custom-components/alexa_media_player/pull/1614  :

It will now force a reauthentication if it detects a degraded login. Before, it would let you continue to login but disable features (but then people would open issues constantly saying random things weren't working). If the new behavior is a problem, you'll need to downgrade to the 3.x series.  

I did a roll-back to v3.11.3 and everything works fine ..

**Comment by charettepa** [comment]
> Please provide logs.

where do you get the specific alexa_media_player logs
I can only find host, system, add-ons but not integrations

**Comment by SpicyLimes** [comment]
Having the same issue. I even tried the method metioned in this post - [#1621](https://github.com/custom-components/alexa_media_player/issues/1612#issuecomment-1140448407) - this all started happening this morning after restarting Home Assistant. 

Here is my log output:
`Logger: alexapy.alexalogin
Source: /usr/local/lib/python3.9/site-packages/alexapy/alexalogin.py:237
First occurred: 1:32:40 PM (3 occurrences)
Last logged: 1:33:05 PM

Error creating TOTP; ****** likely invalid`

I even added Microsoft Authenticator to my Amazon account so as to have a backup option for 2FA. But just to be clear, I've tried both the code sent to my phone AND the code produced by Microsoft Authenticator - neither have alleviated this issue. 

See attached images for the GUI errors that I am getting.
![Screenshot 2022-05-31 134443](https://user-images.githubusercontent.com/66497450/171262417-311e848d-77d0-46eb-afbe-912a7dda9e47.png)
![Screenshot 2022-05-31 134100](https://user-images.githubusercontent.com/66497450/171262829-9e83089b-c7e9-4ccf-8614-0ea64f3b5939.png)

**Comment by alandtse** [comment]
@sp3cialck remove the entry from your configuration.yaml and add it manually through integrations. Does that resolve it?

**Comment by balkonrad** [comment]
> @sp3cialck remove the entry from your configuration.yaml and add it manually through integrations. Does that resolve it?

This is not the case here.

**Comment by alandtse** [comment]
> I had to downgrade 3.11.3, re-auth, and was able connect. Behavior I saw with 4.0.0 or 4.0.1 on 2022.05 or 2022.06 was the logs saying presumed invalid OTP. OTP accepted on 3.11.3. I could not get any OTP accepted on 4.0.0 or 4.0.1.

You're referencing an existing closed issue. Please review #1617 for the solution. I'll mark your comment offtopic for now.

**Comment by ashrafmn** [comment]
Having the same exact issue,, re authenticate after every reboot.

**Comment by tagz1979** [comment]
I think I found the fix for this issue. If you go to Settings-->System-->Network and under the Home Assistant URL you need to Make sure that Internet is set correctly. For example I am using DuckDNS and had to change that to the correct DuckDNS address. I had to do within my Configuration.YAML because I had other configurations as well.

**Comment by charettepa** [comment]
@tagz1979 

mine is already set to duckdns
using the NGINX Home Assistant SSL proxy
not the NGINX Home Proxy Manager
which one are you using?

my SSL cert is working properly for everything except this
however this particular issue is for the need to reauthorize at every reboot
unfortunately based on previous actions, both our posts will probably get flagged as off topic

**Comment by tagz1979** [comment]
I'm not usig a proxy manager and I was having the same issue when I rebooted I had to reauthenticate.

**Comment by charettepa** [comment]
> I'm not usig a proxy manager and I was having the same issue when I rebooted I had to reauthenticate.

how are you applying your duckdns cert to HA without NGINX

**Comment by tagz1979** [comment]
Sorry, I dont know what NGINX is I followed the instructions on how to configure DuckDNS in the documentation and there isn't anything in there about NGINX

**Comment by mikesalz** [comment]
@tagz1979 @charettepa I'm pretty sure it is an issue outside of DuckDNS/NGINX.  I don't use either, and I am having exactly the same problem.

**Comment by sp3cialck** [comment]
After the new HA update, it's working!
1. Updated HA
2. Removed the devices from devices/services
3. Removed Alexa Media Player from HACS
4. Restart
5. Installed Alexa Media Player Again
6. Restart
7. Config/Reauth... et voilá, it's working!

**Comment by charettepa** [comment]
@sp3cialck 

thanks for the tip
not quite what did it for me but got me in the right direction

no matter what i simply could not fully delete/remove
apparently i still had the old yaml entry and it was overiding everything

** if anyone else has this issue perform the steps mentioned by @sp3cialck , but after step 3 also make sure its not in your yaml
*** as a second note i also saw that the mac_dms could also occur if your configured contry does not match what amazon has
    ie. its common in Canada to use .com instead of .ca in order to get all apps
    *sarcasm* apparently english us/canada are not the same

I hope this addition helps other with the same struggles
its great to see the community/users sharing info and trying to work together on this

**Comment by HDP13** [comment]
¡Buenas!
Yo eliminé todo en más de 10 ocasiones, pero no me sale el modo proxy, por lo que cada vez que reinicio vuelve a pedirme registrarme, estoy loco, si alguien puede ayudarme seria de gran ayuda, gracias de ante mano

**Comment by mikesalz** [comment]
@charettepa Didn't work for me.  The only thing that works is downgrading the integration....

**Comment by HDP13** [comment]
Adjunto la cronología de lo que yo hago, no soy un experto claro está y puedo estar haciendo casi todo mal
<img width="490" alt="1_CAPTURA_ALEXA" src="https://user-images.githubusercontent.com/101067868/171886215-4ca678af-c7bc-4fb7-90fd-0dc08302ac67.png">
<img width="928" alt="2_CAPTURA_ALEXA" src="https://user-images.githubusercontent.com/101067868/171886248-cbf1b477-81e2-43cc-9ff3-48081163b450.png">
<img width="856" alt="3_CAPTURA_ALEXA" src="https://user-images.githubusercontent.com/101067868/171886288-fb6e510e-2637-4bb4-8690-520e1763e50f.png">
<img width="579" alt="4_CAPTURA_ALEXA" src="https://user-images.githubusercontent.com/101067868/171886322-71997721-a9f1-471d-b77e-61b071cf99f6.png">
<img width="885" alt="5_CAPTURA_ALEXA" src="https://user-images.githubusercontent.com/101067868/171886338-2d9cb8e8-7223-4028-aa3a-d17b10cc9e5c.png">
.

**Comment by J-T-W** [comment]
I think I am seeing the same thing, but not sure.  Every restart of HA (Host or Supervisor) requires a reconfiguration of Alexa Media Player.  Each time the configuration popup shows that the 2FA key is blank, I re-add it, then go through the new browser screen to OTA authenticate with the generated code, it completes successfully, etc.  Not sure if I need to do some other configuration somewhere to let it just authenticate in the back ground.

**Comment by mikesalz** [comment]
@alandtse We probably need to reopen this.  I upgraded to 4.0.2 and am still experiencing the same issue.  I have logged in and restarted multiple time, and am still prompted to reconfigure every single time.

**Comment by ashrafmn** [comment]
Yes ,, the issue still not fixed after the update

**Comment by rgroce** [comment]
** if anyone else has this issue perform the steps mentioned by @sp3cialck , but after step 3 also make sure its not in your yaml 

I had this issue until I removed my old alexa_media: config from my configuration.yaml and restarted.

**Comment by mikesalz** [comment]
@rgroce That did fix it for me.  I thought I had removed my yaml config, but nope.  Still there.  I pulled that out and followed the steps you mentioned and it is now working.  Thanks everyone!
