### ISSUE TITLE
Reauthentication requires Password Reset

### ISSUE THREAD

**Issue by MrSolo570** [custom-components/alexa_media_player#1621]
**Describe the bug**
After the latest update the compontent needs to requthenticate. I entered all required data and get forwared to the external login page from amazon. I can login into my Amazon Account but then it says I need to reset my password. If I confirm that I get sent back to Login Page and an endless cycle starts.

**To Reproduce**
start Reauthentication process

**Expected behavior**
Login and reauthenticate so the component is registered successfully

**Screenshots**
see below

**System details**
 - Home-assistant (version): 2022.5.5.
 - Hassio (Yes/No): yes
 - alexa_media  (version from `const.py` or HA startup): 4.0.1

![1653978570827](https://user-images.githubusercontent.com/61246489/171110263-20449c8d-5591-42d2-98a3-34f47699d2db.jpg)
![1653978570858](https://user-images.githubusercontent.com/61246489/171110269-8315439d-a3be-4830-b05b-c80e8de5ad17.jpg)
![1653978570879](https://user-images.githubusercontent.com/61246489/171110274-c10ec2ea-5cb6-43d9-aa0a-285e209efc7e.jpg)

 - Amazon [2FA is enabled]: yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by alandtse** [comment]
After a password reset you need to restart the authentication process from scratch so it sets up the proxy.

Is your HA hosted in the cloud? The proxy is triggering some fraud prevention mechanism from Amazon and forcing a password reset.

**Comment by MrSolo570** [comment]
Hello, as a matter of fact I cannot reset my password like this. When I hit the button it just redirects me back to the login page. 
At the component configuration page I have my Nabu Casa Cloud URL entered. Is that wrong? Should I change that to local IP?

**Comment by MrSolo570** [comment]
OK apparently amazon really wanted me to reset the password. I did that on a desktop and after that the plugin could reauthenticate with the new password withould a hassle. @devs: Please dont mind my spamming and keep up the good work!
