### ISSUE TITLE
Reauthentication does not work - Error fetching alexa_media data: Error communicating with API: Session is closed

### ISSUE THREAD

**Issue by lweberru** [custom-components/alexa_media_player#1623]
**Describe the bug**
Login was always an issue with this integration, but since this new version, ha opens a seperate browser window to login. After successfully login within that browser window nothing happens on ha side. The wizards popup just stays opened. Tried it by using the ios ha app and by using chrome directly

**To Reproduce**
1. Go to integration page
2. Click on reconfigure
3. Enter your authentication information like user and password
4. Login inside the opened browser window

**Expected behavior**
The wizard is somehow recognizing that login was successful and closes the wizard.

**Screenshots**

**System details**
 - Home-assistant (version): 2022.6.0.dev20220512
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): 4.0.1
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: no

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

all i see is the following, but not if its related:

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.alexa_media
Source: helpers/update_coordinator.py:223 
Integration: Alexa Media Player (documentation, issues) 
First occurred: 12:29:17 (1 occurrences) 
Last logged: 12:29:17

Error fetching alexa_media data: Error communicating with API: Session is closed

**Additional context**

**Comment by alandtse** [comment]
Please provide logs of the full login attempt.

**Comment by marcosamm** [comment]
I'm having a similar problem with HA 2022.6.1, HACS 1.25.5, and Alexa Media Player 4.0.2.

I filled the fields email address, password, and URL to access my Home Assistant. I put amazon.com in the domain field and put my 2FA code generated by MS Authenticator on my phone (it's working fine on the amazon website). Then, the following message was displayed: 

"Please confirm the information below. 
Invalid 2FA built-in key"

Logs:

Logger: alexapy.alexalogin
Source: /usr/local/lib/python3.9/site-packages/alexapy/alexalogin.py:237
First occurred: 09:38:02 (4 occurrences)
Last logged: 09:44:24

Error creating TOTP; ****** likely invalid

**Comment by alandtse** [comment]
> I'm having a similar problem with HA 2022.6.1, HACS 1.25.5, and Alexa Media Player 4.0.2.
> 
> I filled the fields email address, password, and URL to access my Home Assistant. I put amazon.com in the domain field and put my 2FA code generated by MS Authenticator on my phone (it's working fine on the amazon website). Then, the following message was displayed: 
> 
> "Please confirm the information below. 
> Invalid 2FA built-in key"
> 
> Logs:
> 
> Logger: alexapy.alexalogin
> Source: /usr/local/lib/python3.9/site-packages/alexapy/alexalogin.py:237
> First occurred: 09:38:02 (4 occurrences)
> Last logged: 09:44:24
> 
> Error creating TOTP; ****** likely invalid

You're off topic and you need to search all issues as your issue has been reported and explained multiple times.

**Comment by dibyadip-das** [comment]
The same is the case with me. I cannot reauthenticate Alexa Media Player

**Comment by octaviz** [comment]
I had that error, I removed the integration in hacs, I reinstalled everything and when I enter all the data it gives me an error:
Invalid Built-In 2FA key
The 2FA works perfectly on the Amazon website, but not on the integration.
HA Version 2022.6.3 core version without Supervisor
Alexa Media Player Version 4.0.2
I have tried both the domain and the internal url and it gives the same error

**Comment by moseisleydk** [comment]
I get the same error in the logs.

**Comment by dibyadip-das** [comment]
> I was having the same issue. I finally fixed it by specifying the local URL of HA instead of the remote one.

Did you set your internal URL as an external URL? I am not able to submit it with my internal IP address. Even I tried to remove and add it back

**Comment by emepetres** [comment]
> > I was having the same issue. I finally fixed it by specifying the local URL of HA instead of the remote one.
> 
> Did you set your internal URL as an external URL? I am not able to submit it with my internal IP address. Even I tried to remove and add it back

Not really, I have the external url from nabu casa as the internet url, and the http://192.X...:8123 as the local one
