### ISSUE TITLE
Invalid 2fa Key

### ISSUE THREAD

**Issue by YukiSuter** [custom-components/alexa_media_player#1640]
Now before you mark this as a dupe, I get the error when putting in the long 2fa app key, the one that has repeats of 4 digits, not the key from the authenticator app. Forgive me if an issue has been raised about this, but the issues section is so flooded with people who put the code from the authenticator app in the field...

I'm not going to reveal the 2fa app key but its in there and its correct so im unsure why im getting this error...

<img width="417" alt="image" src="https://user-images.githubusercontent.com/16707981/173437379-0cb45448-30b0-4796-a52e-1dc2ce755fba.png">

**Comment by Albruaje** [comment]
Same for me

**Comment by alandtse** [comment]
Please search. Dupe #1617

**Comment by YukiSuter** [comment]
> Please search. Dupe #1617 

If you read my post again, you'd know that's not the issue I'm having...

I am NOT inputting the code from my authenticator app in there. I am inputting the code given by Amazon when attempting to add a new authenticator...

**Comment by alandtse** [comment]
Please fill out the template and provide logs. It should obfuscate the key, but double check before posting.

**Comment by alandtse** [comment]
Please confirm you are following [this](https://github.com/custom-components/alexa_media_player/wiki/Configuration#built-in-2fa-app). An example key is included. The code checks the code to make sure it's cryptographically valid. That is the error you're likely seeing but can't figure it out without logs.

**Comment by Albruaje** [comment]
> Please confirm you are following [this](https://github.com/custom-components/alexa_media_player/wiki/Configuration#built-in-2fa-app). An example key is included. The code checks the code to make sure it's cryptographically valid. That is the error you're likely seeing but can't figure it out without logs.

I have follow [that](https://github.com/custom-components/alexa_media_player/wiki/Configuration#built-in-2fa-app), but not success.....If I would mannage with logs, I will be able to post them....

**Comment by YukiSuter** [comment]
Ok so upon not touching it for 2 weeks (exams), it seems to now be in the mood to work? So atleast from my end all is well now, though I'm not sure how long that will last...

**Comment by alandtse** [comment]
The other cause could be your system time wasn't updated so the key generation wouldn't sync, but who knows.

Glad it resolved itself.
