### ISSUE TITLE
Add support for Alexa IAQ device

### ISSUE THREAD

**Issue by CitizenRacer** [custom-components/alexa_media_player#1641]
it would be awesome to get support for the Alexa IAQ devices listed here: https://www.amazon.com/Introducing-Amazon-Smart-Quality-Monitor/dp/B08W8KS8D3

I'd love to see it be visible as a trigger for Home Assistant automatons.

**Comment by alandtse** [comment]
I don't have one but I'll leave this open for people to experiment on.

**Comment by sdaltons1** [comment]
I just got one of these and would love to see it added as well.
