### ISSUE TITLE
Include lights which are connected directly to an echo via bluetooth.

### ISSUE THREAD

**Issue by Lippiero** [custom-components/alexa_media_player#1643]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**
Lights which are connected directly to an echo via bluetooth doesn't show up, though 'Include devices connected via Echo' is active.

**Describe the solution you'd like**
Include lights which are connected directly to an echo via bluetooth. 

**Describe alternatives you've considered**
At the moment, I have a workaround in place: I installed the node-red add on in Homeassistant and added Alexa integration there (node-red-contrib-alexa-remote2-applestrudel). With this integration, I am only able to query/poll the state or send commands to  smart home devices, so I added a kind of proxy device to homeassistant and every event or command which reaches the proxy device is forwarded to the actual device via node-red and the 'alexa-remote2-applestrudel'. This solution is not really nice, because when I want to control the device via alexa, the proxy device has to be set up for this and it leads to 2 request roundtrips where only one could do the job. Besides that it's a  mess which, if the alexa-media-player integration would support those devices, wouldn't be necessary anymore.

**Additional context**
I have these bulbs: [LEDVANCE BLUETOOTH SMART+ CLASSIC LED LAMP RGBW MULTICOLOURED (EX 60W) 10W E27](https://shop.ledvance.com/en/products/ledvance-smart-led-bluetooth-lamp-with-e27-socket-rgb-colour-changing-dimmable-replaces-60-w-bulb-warm-white-compatible-with-apple-homekit-and-ledvance-smart-app-for-android-energy-class-a)
I think, this is a feature request and not a bug, because [here is written](https://github.com/custom-components/alexa_media_player/issues/1237) that the 'Include devices connected via Echo' only include zigbee devices on purpose.

**Comment by ehutch24** [comment]
My sengled bluetooth bulbs work in this way. The 'Include devices connected via Echo' works for those. Could it be brand specific or is this an isolated issue?

**Comment by Lippiero** [comment]
I can't tell... I tried to understand the relevant code snippets (parse_alexa_entities -> is_light -> is_local), but I couldn't manage it by mere review. If there's anything I can do - f.ex. providing logs. Please advise how to do it.
