### ISSUE TITLE
Connection Error! Please try refreshing. If this persists, please report this error to here: All connection attempts failed

### ISSUE THREAD

**Issue by brunoap** [custom-components/alexa_media_player#1644]
**Describe the bug**
After inserted email, 2fa key obtained from amazon and realized otp check, the error: Connection Error! Please try refreshing. If this persists, please report this error to [here](https://github.com/custom-components/alexa_media_player/issues):
All connection attempts failed

**To Reproduce**
After inserted email and 2fa ke obtained on amazon and checked otp, the error occurs.

**Expected behavior**

**Screenshots**

**System details**
 - Home-assistant (version): 
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: 

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.
![Screenshot_4](https://user-images.githubusercontent.com/53919718/174414259-bf484681-04ee-4401-a146-2f079a7ee649.png)

**Additional context**

**Comment by alandtse** [comment]
#1634 may have a workaround where you use your local IP for the proxy. If you'd like to add more info to try to hunt this down, please generate logs like in that issue and see if you're seeing a different result.

**Comment by J-T-W** [comment]
I experienced this yesterday after an HA restart, where the integration needed reauthentication (2FA code already configured and all configuration.yaml removed), but errored when attempting to complete the sign-in with a similar error.  This morning the authentication went as expected, and survived a system reboot.

**Comment by brunoap** [comment]
> #1634 may have a workaround where you use your local IP for the proxy. If you'd like to add more info to try to hunt this down, please generate logs like in that issue and see if you're seeing a different result.

Hi there. Used local URL for HA and it worked. Thanks.
