### ISSUE TITLE
Deactivate alexa alarm 

### ISSUE THREAD

**Issue by isibizi** [custom-components/alexa_media_player#1645]
Hey Dev, can you add the option to deactivate alexa alam?

I have the caldav integration in hassio. I have calender entries with “holidays” and “illness” when one of both condition is true, the alexa alarm should be stopped.

**Comment by alandtse** [comment]
Reading this request again, you're asking us to automatically disable an alarm based on your calendar? That we won't do. The Alexa API has no idea what your holidays are so is outside the scope of the component.

You'll need to do your own automations. Ask on the forum for help. You can use a custom command to verbally turn off alarms. 

If for some reason the [custom commands](https://github.com/custom-components/alexa_media_player/wiki#run-custom-command) can't disable alarms, then you can open up a feature request to disable alarms via the API, but it will be left open for someone who wants to do it to implement.
