### ISSUE TITLE
The screenshot shows that two accounts have been setup. If you only need one account, remove everything and start from scratch. Obviously if you've managed to install more than one account with the same credentials, you will force yourself to log out as Amazon won't support two logins with the same account/domain and each will kick the other out.

### ISSUE THREAD

**Issue by EspElement** [custom-components/alexa_media_player#1657]
The screenshot shows that two accounts have been setup. If you only need one account, remove everything and start from scratch. Obviously if you've managed to install more than one account with the same credentials, you will force yourself to log out as Amazon won't support two logins with the same account/domain and each will kick the other out.

Without logs, I can't tell what's going on.

_Originally posted by @alandtse in https://github.com/custom-components/alexa_media_player/issues/1656#issuecomment-1166768545_

I removed everything and started from scratch. So far it has accepted and I was able to send a TTS. So we will see if it lasts the night!

**Comment by alandtse** [comment]
Don't open unnecessary issues please.

**Comment by EspElement** [comment]
> Don't open unnecessary issues please.

Sorry, seems like another person learned from my post too. It started after an update so I thought something was wrong.

Best
