### ISSUE TITLE
Unknown Error on initial configuration/integration

### ISSUE THREAD

**Issue by fireheadman** [custom-components/alexa_media_player#1659]
Unsure what is causing this.... fresh install of the integration
![image](https://user-images.githubusercontent.com/19847195/177639611-99bb2c34-7aa5-47b1-a1d8-1aa261e9bcfd.png)

**Comment by fireheadman** [comment]
![image](https://user-images.githubusercontent.com/19847195/177640083-3afac8b3-2212-41ac-b45c-3c23e2bea258.png)

**Comment by fireheadman** [comment]
UPDATE:
Added my 2FA code per the instructions...   (did not remove the blanks from the long code).
Still get this error.    I have 2FA enabled on my account

![image](https://user-images.githubusercontent.com/19847195/177646824-e341bfa8-1571-46c1-9fdf-664f78154242.png)

**Comment by fireheadman** [comment]
update... the restore got me back to a working alexa media player.... although I am expecting an issue soon with 2FA not working since I removed and recreated it on the amazon side.

Unsure why a RELOAD does not pull in new devices and/or changed/renamed devices?

**Comment by kauthmbt** [comment]
Might be the case that he add-on needs some kind of adjustment now because from HA core-2022.7 onwards Python 3.10 is used...
[https://www.home-assistant.io/blog/2022/07/06/release-20227/#breaking-changes](url)

**Comment by alandtse** [comment]
Please fill out the template and edit your initial post. It will explains how to provide logs which are needed to figure out what's going on.

**Comment by fireheadman** [comment]
Being that I rolled Back, I cannot reproduce now.   You may close the issue or leave it open for another user to contribute
