### ISSUE TITLE
401: Unauthorized after amazon login page

### ISSUE THREAD

**Issue by quejoo** [custom-components/alexa_media_player#1660]
![Captura da Web_7-7-2022_211711_homeassistant alnugo com br](https://user-images.githubusercontent.com/61283274/177892386-c196c1db-fca3-4ef1-8aa7-9b9da8309c94.jpeg)
![Captura da Web_7-7-2022_211826_homeassistant alnugo com br](https://user-images.githubusercontent.com/61283274/177892391-3fda6587-cb19-4241-ae9e-bb1130e2b360.jpeg)
![Captura da Web_7-7-2022_211841_homeassistant alnugo com br](https://user-images.githubusercontent.com/61283274/177892395-cbcb8b8c-7d85-4399-aa75-6592e7aba217.jpeg)
![Captura da Web_7-7-2022_211927_homeassistant alnugo com br](https://user-images.githubusercontent.com/61283274/177892396-e577b1f0-86bf-4851-8220-5c55b1072ed1.jpeg)
![Captura da Web_7-7-2022_212052_homeassistant alnugo com br](https://user-images.githubusercontent.com/61283274/177892397-4fd612b5-1282-48dd-a3cb-c8224da00f66.jpeg)
![Captura da Web_7-7-2022_212523_homeassistant alnugo com br](https://user-images.githubusercontent.com/61283274/177892617-6bbaaf95-fad3-4624-847b-b746097e2626.jpeg)

In last step error the page "401: Unauthorized" and login attempt failed from home assistant home page

**Comment by alandtse** [comment]
If you use a local ip url as opposed to the external url in the field "Url to access Home Assistant", do you see the same error?

Please fill out the template and provide logs for the period right before you see the 401. 401 indicates that your HA is not accepting your credentials while going to the proxy view. That isn't controlled by the custom component at that point. If you're able to see the proxy view of the Amazon login at all, it shows the proxy view is working.

**Comment by quejoo** [comment]
> If you use a local ip url as opposed to the external url in the field "Url to access Home Assistant", do you see the same error?
> 
> Please fill out the template and provide logs for the period right before you see the 401. 401 indicates that your HA is not accepting your credentials while going to the proxy view. That isn't controlled by the custom component at that point. If you're able to see the proxy view of the Amazon login at all, it shows the proxy view is working.

No, that doenst happen when using local ip. Will check logs and attach here

**Comment by alandtse** [comment]
I'll close this for now. Please reopen it when you are able to provide logs.
