### ISSUE TITLE
Echo and Echo Plus Temperature Sensor in Celsius Only

### ISSUE THREAD

**Issue by jstinesnc** [custom-components/alexa_media_player#1661]
I recently upgraded to 2022.7.2 of Home Assistant and upgraded to the latest version of Alexa Media Player. I am in the USA and have my temp preference set as Fahrenheit Pounds Imperial in Home Assistant under Settings>System>General. Previously, my echo temperature sensors displayed in degree Fahrenheit, but now they only display in Celsius.

Under Entity states the sensor has the following attributes:
unit_of_measurement: °C
friendly_name: Dining Room Echo Plus Temperature

I tried customizing another sensor to see if it would display properly by manually adding the following:

sensor.utility_closet_echo_plus_temperature:
  device_class: temperature
  unit_of_measurement: °F
  state_class: measurement
  
This did not change the value to Fahrenheit,  but only changed the degree icon to °F.

I've also tried adding only the following customization (removing the unit of measure):

sensor.utility_closet_echo_plus_temperature:
  device_class: temperature
  state_class: measurement

This did not provide the ability to change the sensor from C to F. 

Other temperature sensors that are displaying properly show a dropdown setting for Unit of Measurement when clicking the gear icon for settings on the GUI dashboard. Alexa Media Player Echo Temperature Sensors don't display this dropdown.

![image](https://user-images.githubusercontent.com/58440965/178115860-f3d412d3-f182-41bd-b9de-87137c427598.png)

![image](https://user-images.githubusercontent.com/58440965/178115882-5d9c327d-5282-40ca-997a-802b669072f7.png)

This could be a bug in the new HA release, but I wanted to run it by you if perhaps something needs to be addressed in how the temperate sensor is created/defined through Alexa Media Player. Thanks.

**Comment by jstinesnc** [comment]
Could it possibly need native_unit_of_measurement to be set to °C and device_class set to temperature?

https://developers.home-assistant.io/docs/core/entity/sensor/#properties

**Comment by PJW58** [comment]
This seems to have started with a recent update to the Media Player, as I noticed this issue several days before upgrading HA to 2022.7.x

**Comment by rjdalga** [comment]
I can confirm and reproduce this issue as well.

**Comment by alandtse** [comment]
> Could it possibly need native_unit_of_measurement to be set to °C and device_class set to temperature?
> 
> https://developers.home-assistant.io/docs/core/entity/sensor/#properties
Yes, it's probably that. Happy to take a PR when someone submits it. I don't have any temperature sensors.

**Comment by driven4jed** [comment]
Can confirm same thing here. All other temperature sensors show F while Alexa's show C.  Also confirm it started with a recent update, I think 4.x in May.

**Comment by nerzakt** [comment]
mine too and it is driving me nuts

**Comment by nerzakt** [comment]
> Can confirm same thing here. All other temperature sensors show F while Alexa's show C. Also confirm it started with a recent update, I think 4.x in May.

i can confirm also it is driving me nuts hope there is a fix soon

**Comment by rhoskins61** [comment]
+1

**Comment by kdvlr** [comment]
Created PR https://github.com/custom-components/alexa_media_player/pull/1682 to fix this. @alandtse - Please review and let me know if you need anything else to be done.

**Comment by alandtse** [comment]
Fix is in dev now. I can't test it but you can load it in HACS or wait till the next release (after it's confirmed). Thanks @kdvlr

**Comment by kdvlr** [comment]
For reference, you can download the dev branch by selecting "dev" from the dropdown. Please test and let me know if you have any errors.

 <img width="579" alt="image" src="https://user-images.githubusercontent.com/19178546/183267437-b927bd3d-ea33-4c1b-9409-497c13d0010b.png">

**Comment by jstinesnc** [comment]
I am happy to test this, but I can't find where you are seeing this "Show beta versions" option window.  Is the only way to see this option to delete the existing integration and then re-download Alexa Media Player in HACS?

**Comment by jstinesnc** [comment]
Nevermind. I found it under re-download. Thanks.

**Comment by rhoskins61** [comment]
Not sure if related, but am now getting random Alexa Media re-authentication required. Going to roll back and see what happens.

**Comment by kdvlr** [comment]
It shouldn’t. The code does not make any changes in any authentication flow. @jstinesnc - were you able to test ?

**Comment by rhoskins61** [comment]
OK, thanks.. I did test and the C > F works. TY for that fix!

**Comment by driven4jed** [comment]
> 
Works great... Thank you*2!
