### ISSUE TITLE
Uninstalling Integration - instructions do not work.

### ISSUE THREAD

**Issue by bwims** [custom-components/alexa_media_player#1663]
**Describe the bug**
Documentation says "If you wish to uninstall this integration, you can click Uninstall on the component in HACS"

**To Reproduce**
1. There is no uninstall button in the HACS integration.  There are 3 dots at the top left, with a Remove option
2. Click on Remove
3. Nothing happens, no acknowledgement
4. Integration removed from Configuration > Integrations as documented
5. Restarted HA got the following warning

`2022-07-12 16:07:07 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant`

**Expected behavior**
Removal of Alexa Media Player

**Screenshots**

**System details**
 - Home-assistant (2022.4.6): 
 - Hassio (/No): 
 - alexa_media  (version from `const.py` or HA startup): Whatever was current version 2 days ago
 - alexapy (version from `pip show alexapy` or HA startup): ditto
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered:  This is not a login issue.
**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by bwims** [comment]
Extra information - note, no Uninstall button

![image](https://user-images.githubusercontent.com/18516073/178526381-a93b4d94-ce3f-4ea1-b817-92f1dd6b1692.png)


Again, no Uninstall button.  The "Remove" option is uneffective.

![image](https://user-images.githubusercontent.com/18516073/178526611-326f54fb-783b-4514-8d74-c3b21917d7d9.png)

I tried moving the alexa_media directory out of the custom_components directory, which stopped the error message on restart, but the component is still in HACS.

What do I do to get rid of it?

**Comment by bwims** [comment]
Hello? Anyone there?

**Comment by alandtse** [comment]
There's a "Remove" option. Please also consider submitting a PR to fix the documentation.

**Comment by bwims** [comment]
The "Remove" option does not appear to do anything. Now what?

**Comment by alandtse** [comment]
Your sense of entitlement makes it hard for me to care.

You need to delete it from HA via the integrations page.  The current option in HA is delete. 
<img width="429" alt="image" src="https://user-images.githubusercontent.com/7086117/180027978-cb65dc6a-879a-4fff-ad33-1966aaa7ecbd.png">

If it doesn't appear, that's a HA bug and I can't help you with that nor do I want to.

**Comment by bwims** [comment]
Perhaps my reaction to being brushed off and ignored by someone whose arrogance exceeds his empathy **might** appear as entitlement.

I'd want to know why my system was so buggy, personally.

Simple solution:

1. stop HA
2. backup .storage/hacs.repositories
3. edit, and delete the definition of Alexa Media Player
4. restart HA

When it reappears as an uninstalled repository, "Dismiss" it .  Problem solved,

For those of us who prefer Node Red to YAML, there is a much better package with far more bells and whistles than this "hac" (what an appropriate name):
[node-red-contrib-alexa-remote2-applestrudel](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel)
