### ISSUE TITLE
Echo Show integrated camera like a camera entity in Home Assistant

### ISSUE THREAD

**Issue by pom0391** [custom-components/alexa_media_player#1667]
One idea would be to create a camera entity in Home Assistant with streaming from the camera built into Amazon Echo Show. Is it possible?

**Comment by alandtse** [comment]
Does the app allow streaming video into an Echo? If not, probably not.

**Comment by alandtse** [comment]
I'll close this for now. I can disposition it further if you provide information about the app.

**Comment by Madelena** [comment]
> Does the app allow streaming video into an Echo? If not, probably not.

I think the request is to stream the camera built in the Echo, not to stream a camera feed to the screen of the Echo, no? With the new Home Monitoring feature on Alexa, you can stream that camera feed now, I think.

**Comment by allanpoppe** [comment]
Yeah, I want this feature too.

**Comment by gustavocunha76** [comment]
So do i

**Comment by Lelloxd** [comment]
This would be great : I have every camera inside hassio except for this One, its painful to open the Alexa app Just to check 1 feed.

**Comment by thefunkygibbon** [comment]
+1.  I don't even know if it's possible to read the camera via API or whatnot.  Hopefully it is

**Comment by fenn1c** [comment]
Any news on this? Also searching for a way to integrate the Echo Show camera live stream into Home Assistant.

**Comment by imushr00m1004** [comment]
I am interested, too. Would be great if you can give us an update, if there will be any solution in the future?!

**Comment by gerolori** [comment]
> I am interested, too. Would be great if you can give us an update, if there will be any solution in the future?!

I commented on august and since then couldn't find any API of sorts that would allow that. For the next future I'd say no. Everything is in Amazon's hand and they'll probably never do it on behalf of security bs.
The thing that might be unlocked is jailbraking of the echo show but that probably means that you'll loose every feature connected with amazon? I guess. So at that point an ip cam just works better

I wanted this to work too, it's a shame

**Comment by bbsports3** [comment]
Following

**Comment by eon0613** [comment]
me three.. i want to stream echo show camera into my home assistant

**Comment by sahilanguralla** [comment]
Following

**Comment by Jens-Wymeersch** [comment]
Is there any progress on this topic ?

**Comment by matte-oss** [comment]
+1

**Comment by victoriemini** [comment]
+1
