### ISSUE TITLE
Media Player Echo availability issue in HA when selecting wrong region

### ISSUE THREAD

**Issue by ionultd** [custom-components/alexa_media_player#1677]
**Describe the bug**
Echo becomes unavailable in the Echo Media Player integration

**To Reproduce**
Posting this as a possible bug in Git
Echo Firmware: 7416571524 (not Echo Dot)
My Echo appears also to be unavailable now.
Reinstall Integration
Restart HA
Both Echo playing music when HA restarted
Echo unavailable
Reload Integration
Echo unavailable
Restart Music
Echo unavailable
Restart HA
Music playing on echo
Echo unavailable
Restart Echo
Echo available for 45s then unavailable
Start a song or pause a song or change the volume
Echo available for ±3s (yes 3s) then unavailable
Echo play next song
Echo available for ±3s then unavailable

**Expected behavior**
Echo should always be available unless disabled or off

**Screenshots**
NA

**System details**
 - Home-assistant (version):  Home Assistant 2022.7.6 Frontend 20220707.1 - latest
 
- Hassio (Yes/No):  HA on UNRaid uses docker containers HA Core

 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup):  Name: alexapy Version: 1.26.1
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: 
I did do it so yes i guess?

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.
Logs attached
[HA-Alexa_media-Player.txt](https://github.com/custom-components/alexa_media_player/files/9173229/HA-Alexa_media-Player.txt)

**Additional context**

**Comment by alandtse** [comment]
Please provide a screenshot of the history of the echo along with it's entity name so I can check it in the logs. The logs are showing player state. Is it all devices? Just one, etc.

**Comment by ionultd** [comment]
There are two Echo's but the one I tested is called "Bedroom Echo"

To which echo history are you referring? I thought that was the logs.

**Comment by alandtse** [comment]
> There are two Echo's but the one I tested is called "Bedroom Echo"

No such echo exists. This is what is being detected. Did you rename them at some point? The closest echo is ` Echo`. That's a space before the name echo.

```
2022-07-23 18:04:20 DEBUG (MainThread) [custom_components.alexa_media.helpers] : Adding [<Entity Lounge Echo: unavailable>, <Entity  Echo: unavailable>, <Entity Everywhere: unavailable>, <Entity This Device: standby>]
```

**Comment by ionultd** [comment]
AAh right my oops! Sorry. It was sanitized for no reason....aaargh

**Comment by alandtse** [comment]
I'm a bit confused. Is that the echo I should be reviewing? The logs show it's updating status but if your HA is reporting an old entity that doesn't exist, then it will stay unavailable. In that case, you probably need to find the correct entity in HA.

**Comment by ionultd** [comment]
Sorry for the confusion. the " Echo" or the Echo with the "space', the plain Echo, is the one. Not the Lounge Echo

**Comment by alandtse** [comment]
Double check all the entities in HA. It says it's updating.

**Comment by ionultd** [comment]
Updated HA but Alexa Media Player still only shows Echo connected for a short while when activated for playing music or when she is asked a question. then the Echo becomes unavailable as in the image below.

![image](https://user-images.githubusercontent.com/24327887/181357266-b88af9a1-0c08-416b-a60b-a1155c43e840.png)

**Comment by alandtse** [comment]
Not sure what's going on. It should be updating but isn't calling the right url. `/api/np/player`. Perhaps uninstall it complete and clean out your device registry.

**Comment by alandtse** [comment]
Your log is missing all the requests to the Alexa servers. No idea why.

```
2022-07-27 17:30:48 DEBUG (MainThread) [alexapy.alexaapi] a******e@g*******m: GET: https://alexa.amazon.com/api/np/player?deviceSerialNumber=XXX&deviceType=AB72C64C86AW2&screenWidth=2560&_=1658968248355 returned 200:OK:application/json
```

**Comment by ionultd** [comment]
Ok thx for that update. What do you suggest I do next?

**Comment by jvb93** [comment]
I had the same issue as OP, resolved by factory resetting my echo dot, re-adding it to my amazon account, removing this integration, restarting HA, then going through AMP setup again.

**Comment by ionultd** [comment]
@jvb93 ok that sounds arduous! But i will have to try as that is the only suggestion offered so far. I will report back on its success or not :-)

**Comment by alandtse** [comment]
> is the only suggestion offered so far

I'm pretty sure I did tell you a potential [work around](https://github.com/custom-components/alexa_media_player/issues/1677#issuecomment-1197517302).

**Comment by MrockHunter12** [comment]
> > is the only suggestion offered so far
> 
> I'm pretty sure I did tell you a potential [work around](https://github.com/custom-components/alexa_media_player/issues/1677#issuecomment-1197517302).

Hi, I have the same issue. Could you explain how to do that ? I don't know how to clean the device registry.

**Comment by MrockHunter12** [comment]
So I removed the AMP integration and searched for devices in core.device_registry and core.entity_registry. But I still have enitites that are not available and can not delete them
![image](https://user-images.githubusercontent.com/88487145/182343904-9ae65436-95fd-4d14-ae9d-d37d8155d075.png)
Can someone help ?

**Comment by MrockHunter12** [comment]
okay I did an update of HA and it seems to solve the issue with the entities. Nevertheless, after reinstalling the AMP Integration the devices are still not available. So I can not confirm that uninstalling the integration and cleaning the device registry can not fix this issue on my side.
![image](https://user-images.githubusercontent.com/88487145/182359714-e5cb544b-4ae1-4687-b4cb-08382c787c36.png)

**Comment by MrockHunter12** [comment]
Since nobody answered my questions I will just do an update with what I have figured out. So I have removed the integration an readded it with correct region. In my case I had to use "amazon.de" instead of "amazon.com". After that all amazon devices worked fine for me.
@ionultd maybe that could be one possible issue

**Comment by jvb93** [comment]
See this section in the wiki

https://github.com/custom-components/alexa_media_player/wiki/FAQ#all-my-media_players-are-unavailable-and-the-component-doesnt-work

**Comment by ionultd** [comment]
Thanks for the replies @MrockHunter12 and @jvb93 but I believe my issue is not related to that as I am in NZ and my region is AUS the only one for us. I am have held off on doing what @jvb93 suggested till this upcoming weekend when I am able to do this. I will report back the results though. Again thx

**Comment by alandtse** [comment]
> I am in NZ and my region is AUS the only one for us

If this is true, you're not putting in the correct Alexa domain is all communications in your log are for .com and not .au. Your devices are also registered in the US and not in AUS. No idea what interactions you may see if you're doing that.
