### ISSUE TITLE
TTS not working 

### ISSUE THREAD

**Issue by tekstein** [custom-components/alexa_media_player#1679]
I have installed Haaska on my HA, and everything works except one feature. The TTS feature. Below is the error message I get in the developer tools when trying to test the feature. I have attached an screen of the error message. I have listed all my system specs below. Please let me know if you need any additional information. 

"Failed to call service notify.alexa_media_bedroom_echo_dot_2. Unknown error"

Home Assistant 2022.7.6
Supervisor 2022.07.0
Operating System 8.2
Frontend 20220707.1 - latest

Version | core-2022.7.6
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.10.5
Operating System Family | Linux
Operating System Version | 5.15.32-v8
CPU Architecture | aarch64
Timezone | America/Chicago
Configuration Directory | /config

This error originated from a custom integration.

Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/alexa_media/notify.py:238 
Integration: Alexa Media Player (documentation, issues) 
First occurred: 10:33:45 PM (5 occurrences) 
Last logged: 11:19:39 PM

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/notify/legacy.py", line 229, in _async_notify_message_service
    await self.async_send_message(**kwargs)
  File "/config/custom_components/alexa_media/notify.py", line 238, in async_send_message
    if data["type"] == "tts":
TypeError: 'NoneType' object is not subscriptable

**Comment by tekstein** [comment]
My apologies but where is the template? I'm very new to this. Thanks for your help.

**Comment by alandtse** [comment]
When you create a bug report it provides the template.

**Comment by tekstein** [comment]
Please see the updated report.

**Comment by alandtse** [comment]
You're not using the command correctly. Please consult the wiki. https://github.com/custom-components/alexa_media_player/wiki/Configuration%3A-Notification-Component

**Comment by alandtse** [comment]
Leaving open so someone can catch the error and provide a better error message.
