### ISSUE TITLE
'Invalid Built-In 2FA key' after Home Assistant update

### ISSUE THREAD

**Issue by mkanet** [custom-components/alexa_media_player#1680]
**Describe the bug**
Upgraded Alexa Media Player in HACS _(was perfectly working/authenticated via 2FA prior to upgrade)_, I am prompted to "reconfigure" the Integration.  When I click on "Reconfigure" for Alexa Media Player Integration; and re-enter a new 2FA App Key provided by my officially registered Amazon 2FA app, I am prompted IMMEDIATELY with the error: **Invalid Built-In 2FA key**.  It responds with that error so quickly; it doesn't even appear to check anything online.

**To Reproduce**
1. Go to Integrations 
2. Click on RECONFIGURE
3. Enter valid 2FA Key _(while still good)_
4. Prompted with "Invalid Built-in 2FA key" error

**Expected behavior**
It should authenticate after entering a valid 2FA key

**System details**
 - Home-assistant (version):   2022.7.7
 - Hassio (Yes/No):  Yes  (VirtualBox VM on Windows 10 host)
 - alexa_media  (version from `const.py` or HA startup): 4.1.0
 - alexapy (version from `pip show alexapy` or HA startup): Not sure
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). Y

**Logs**
[HomeAssistant-Log-Alexa.log](https://github.com/custom-components/alexa_media_player/files/9195745/HomeAssistant-Log-Alexa.log)

**Additional context**
I have already tried completely clearing all Web browser cache (cookies, files, images, etc.) before authenticating.  I enabled **advanced debugging** for this Integration:
[Advanced_Debug.zip](https://github.com/custom-components/alexa_media_player/files/9195916/Advanced_Debug.zip)

**Update:** The second Integration below (with my amazon email account) changed from red to normal after rebooting Home Assistant:
![Alexa](https://user-images.githubusercontent.com/811008/181183094-e2adbf5b-d43d-40c6-806f-7b91b277d8c9.png)

It switches back to red after a subsequent reboot of Home Assistant:
![Error](https://user-images.githubusercontent.com/811008/181187834-1d168339-a65f-40a6-86b5-f1b98f83f199.png)

It keeps switching back and forther after each subsequent reboot.

**Comment by alandtse** [comment]
That's for the Built in 2FA key, not for your 6 digit OTP. Leave it blank unless you want the component to manage your 2FA.

**Comment by mkanet** [comment]
> That's for the Built in 2FA key, not for your 6 digit OTP. Leave it blank unless you want the component to manage your 2FA.

OMG Thank you!  I literally tried everything to make this work; except for leaving that field blank!  I'm embarrassed to say how many hours I spent on this to make it work.

Is there any way you guys would **_please_** consider changing that field's description to say something like:
**Optional: For special cases only!**

It would prevent others from making the same mistake I did.  Thank you for your help and consideration.

**Comment by waharris007** [comment]
I had the exact same issue. It wasn’t clear to me at all that I was supposed to leave that blank. I definitely recommend putting some language in the box to leave it blank.

**Comment by jhalak1984** [comment]
Well I have left it blank but still doesn't work. The window doesn't go away, stays no matter how many times I click sybmit

**Comment by Finty23** [comment]
Hi guys, I have another problem, I don't write anything on 2FA field, and I click on send, but web does nothing, neither open a amazon web nor accept the rest of fields, but I don't receive any error.

So I have the same "error" that jhalak1984 said. Please help us
