### ISSUE TITLE
[Error] Connection Error when joining 2FA on configuration

### ISSUE THREAD

**Issue by Spirineu** [custom-components/alexa_media_player#1688]
**Describe the bug**
When doing the final step of the configuration it will show a external connection error
**To Reproduce**
**Steps to reproduce the behavior:**
1. Go to 'Configure' 
2. Try to add a Built-In 2FA key
3. When it's added and you submit it it will show "Connection Error!"
4. See error!

**Expected behavior**
Should be able to add the integration to home assistant
**Screenshots**
![image](https://user-images.githubusercontent.com/72891552/183767679-754bdc65-024f-4b63-bfff-fcd077443033.png)

****System details**
 - Home-assistant (version):** Home Assistant 2022.8.2
 **- Hassio (Yes/No):**Yes
 **- alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered**: Yes

**Logs**
**Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.**

Don't have any log since I can't install it by using the 2fa built in.

**Additional context**
Try to use the fuction of the 2FA built in since, by only using the SMS 2FA the entities would show up always as unavailable

**Comment by alandtse** [comment]
Please generate logs per the template. I can't really debug this without knowing what name isn't resolving. But you should verify your HA machine's DNS is working given the error message. It needs to connect to whatever Amazon domain you're authenticating to.

**Comment by Spirineu** [comment]
Hi @alandtse 

Thank you for answering back!

So, theres no logs, since I cannot pass the 2FA. It's all good since I'm even using Nabu Casa

**Comment by alandtse** [comment]
You need to enable logs per the instructions. Every step of authentication is logged.

**Comment by n2ocharged** [comment]
There's a problem with 4.1.0, I redownloaded the previous version and it worked to get me reconnected.

I understand the DEVs want logs, if you've provided them, thanks... if you're just looking to get up and running, download 4.0.3

**Comment by ellerar** [comment]
I have encountered the same issue.   I have ticked the box for debug when I created the connection which I assume creates the logs but I am not sure where I then find them to send to you?

**Comment by gmcaesar** [comment]
i get this same error: 

We can’t connect to the server at [myurl]


but can not find any report in my logs

**Comment by n2ocharged** [comment]
If you guys go back to 4.0.3 you won't have a problem with it.

**Comment by gmcaesar** [comment]
when i go back to 4.0.03 i get a different problem, based on the messages I'm seeing it's because I'm using a proxy, maybe I need to add an accepted address to the proxy list?
