### ISSUE TITLE
No 2 factor authentication code sent 

### ISSUE THREAD

**Issue by RamonBell** [custom-components/alexa_media_player#1689]
**Describe the bug**
Got a message in home assistant to reauthenticate Alexa media player configuration. This is happening every 3 or 4 months now. Normally when you click on it and you click reconfigure it brings the box up and Alexa will send a text message to my phone with a two-factor code. This time no two-factor code was sent. I've tried multiple times to figure out what the code is based off of other codes. But nothing is happening. Before you used to be able to delete Alexa media player and reinstall it and it would fix it. But now on the bottom of the three dots, the ability to delete the integration is not there anymore.

**To Reproduce**
Steps to reproduce the behaviors:
The steps are just try and reauthenticate. Every time you do it. It does not bring up the pop-up on the phone or on the computer to give a new two-factor app key.

**Expected behavior**
The expected behavior is that a code should pop up in a text box to give a new to factor app key but nothing comes up. Also, I am not able to delete the integration and reinstall like I have numerous other times to at least be able to enter my code and start over

**Screenshots**

**System details**
 - Home-assistant (version):  2022.8.3
 - Hassio (Yes/No):  No HA core
 - alexa_media  (version from `const.py` or HA startup): I would love to give you the media player version but I can't get to it because it won't let me reconfigure it or reauthenticate it.
 - alexapy (version from `pip show alexapy` or HA startup): same issue as before. When I restart it, it does not show that information.
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: Yes, I have two factor authentication enabled.

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by alandtse** [comment]
Update to the latest version.
