### ISSUE TITLE
Timers and reminders aren’t being recognized 

### ISSUE THREAD

**Issue by rlippmann** [custom-components/alexa_media_player#1690]
**Describe the bug**

The timer and reminder sensors show up as unavailable. When I look at the entities there’s a big red exclamation point next to all of them. 

**To Reproduce**

**Expected behavior**

**Screenshots**

https://share.icloud.com/photos/01cAi-XDKScd59mVayPLjRxoQ

https://share.icloud.com/photos/0c0YwTzGjQjZczab2Xbiabsjw

**System details**
 - Home-assistant (version): 2022.8.4
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug). No
 - alexa_media  (version from `const.py` or HA startup): 4.1.0
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: y

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by alandtse** [comment]
Did you create a timer?

**Comment by rlippmann** [comment]
Weird, it just starting working. I deleted and reinstalled, and reset 2FA and that seems to have done it.

**Comment by alandtse** [comment]
When there are no timers/alarms/reminders, the sensor is unavailable because it's a `next` alarm/timer sensor.
