### ISSUE TITLE
Shuffle buttons and other entities are unavailable.

### ISSUE THREAD

**Issue by oneseventhree** [custom-components/alexa_media_player#1694]
Hi,

For some reason my shuffle button entity is showing up like this:
<img width="334" alt="Screen Shot 2022-08-23 at 3 31 13 pm" src="https://user-images.githubusercontent.com/15043282/186077717-6c5eb6ff-6513-4779-8073-e4113fb18e1e.png">

I am not too bothered about the other entities but it would be nice to get them working too.

This is for a Echo Show

**Comment by alandtse** [comment]
They are active when you actually have something to shuffle or display.

**Comment by oneseventhree** [comment]
> They are active when you actually have something to shuffle or display.

My Echo has been playing my playlist for 10 minutes and the button hasn't become active the whole time.

Is there another way to shuffle Apple Music playlists?

**Comment by alandtse** [comment]
Is it active in the Alexa app?

**Comment by oneseventhree** [comment]
> Is it active in the Alexa app?

it isn't is this to do with Apple Music?

**Comment by alandtse** [comment]
Yes, we can only emulate what the Alexa app can do. If it's not available there, we can't do it.

**Comment by oneseventhree** [comment]
As a work around I made a routine that shuffles the playlist and ran it with this integration. The routine I made was 
Customised > "Alexa, shuffle playlist <PLAYLISTNAMEHERE>"
