### ISSUE TITLE
Announcements don’t work on the Alexa Windows Store app.

### ISSUE THREAD

**Issue by gaussey** [custom-components/alexa_media_player#1695]
**Describe the bug**
Announcements don’t work on the Windows Alexa PC App
**To Reproduce**
Create an automation to send an announcement to alexa_media.alexapc (or whatever the entity is called).

Announcements on “real” echo devices work fine.

**Comment by alandtse** [comment]
Can you do the announcement to those apps using the official Alexa app?

**Comment by malosaa** [comment]
Same problem here, on my smart fridge i can't use the announce but tts works
