### ISSUE TITLE
Using 2FA instead of proxy method

### ISSUE THREAD

**Issue by nayefag** [custom-components/alexa_media_player#1696]
Hi,

How can I go back to the 2FA method instead of proxy ? The documentation does not say how this can be done. Newer versions of alexa_media force proxy method (since ~ 2 months now). I don't see any setting (GUI or YAML) to switch back to 2FA.

I haven't been able to use proxy method due to getting "500 Internal Server Error" when it prompts me to log in to my Home Assistant instance after verifying my proxy App key.

Gave up on trying to get around this issue and want to use the older 2FA method (SMS) instead.

Thanks.

**Comment by alandtse** [comment]
Downgrade.
