### ISSUE TITLE
Multiple Errors

### ISSUE THREAD

**Issue by oneseventhree** [custom-components/alexa_media_player#1697]
Hi,

Without my HA server has been running properly for days but just today I have been getting these errors without anything changing on my end:

<img width="1392" alt="Screen Shot 2022-08-30 at 9 12 35 pm" src="https://user-images.githubusercontent.com/15043282/187422878-446e4e56-7536-4a39-81bc-2b96eef542e5.png">

First TTS stopped working but now thats back up and running but then I wasn't able to trigger routines even though TTS was working.

AS of 5 minutes ago everything seems to be working but things are out of service time to time

**Comment by Ottomaane** [comment]
same here

**Comment by AlexKusnezov** [comment]
same here

**Comment by AlexKusnezov** [comment]
same here

**Comment by brinzlee** [comment]
I keep getting Alexa Media Player Requires Attention....and the following in the log....
I have entered all the detail including OTP several times now.......works for an hour or so then bombs out...


`Logger: alexapy.helpers
Source: custom_components/alexa_media/media_player.py:618
Integration: Alexa Media Player ([documentation](https://github.com/custom-components/alexa_media_player/wiki), [issues](https://github.com/custom-components/alexa_media_player/issues))
First occurred: 2:35:43 PM (1 occurrences)
Last logged: 2:35:43 PM

alexaapi.get_state((<alexapy.alexaapi.AlexaAPI object at 0x7f6f3c7dc0>,), {}): An error occured accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments: ('Login error detected; not contacting API',)`

**Comment by dpgh947** [comment]
There may be problems at Amazon, I have had to keep re-authing Alexa daily for the past 3 days, twice today. Getting similar sorts of errors in my logs too.

**Comment by MikeGuest** [comment]
Well, this is interesting (may be same issue) - notice the correct integration to the right

Earlier today I logged into alexa on each of these and they disappeared as I did so - and now they're back again.

![cropped Screenshot from 2022-08-31 19-38-54](https://user-images.githubusercontent.com/12844043/187756549-8381a34e-6d55-455c-9669-4f6970081acf.png)

can raise it as a separate issue if required - but it sounds somewhat related given the recency of these other issues

**Comment by nima-1102** [comment]
I have exactly the same problems, if you want to reload the integration, the following message appears:

`Logger: homeassistant.config_entries
Source: custom_components/alexa_media/media_player.py:280
Integration: Alexa Media Player ([documentation](https://github.com/custom-components/alexa_media_player/wiki), [issues](https://github.com/custom-components/alexa_media_player/issues))
First occurred: 09:09:12 (1 occurrences)
Last logged: 09:09:12

Error unloading entry Amazon Alexa for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 496, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 430, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 174, in async_unload_entry
    await platform.async_reset()
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 687, in async_reset
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 798, in async_remove
    await self.async_will_remove_from_hass()
  File "/config/custom_components/alexa_media/media_player.py", line 280, in async_will_remove_from_hass
    coordinator.async_remove_listener(self.update)
AttributeError: 'DataUpdateCoordinator' object has no attribute 'async_remove_listener'`

**Comment by rremmelts** [comment]
Same error here after the latest HA update 😓

**Comment by SonnyBBQ** [comment]
Same issue here.  Have tried re-authing, but the issue returns same day.

Anything else we can do to add to the info?

**Comment by sammyke007** [comment]
+1

**Comment by coolhansen** [comment]
+1

**Comment by johnbubak** [comment]
+1

**Comment by dpgh947** [comment]
I've had a quick look at the changes in 4.1.0 and there's a lot in the auth/reauth area. I've reverted to 4.0.3 and been through some re-authentications (confirmed by watching "expires_in" in core.config_entries), and some full reboots too, and it seems to be behaving.

**Comment by oneseventhree** [comment]
mine has been OK since I posted this. Strange how we are all getting it at different times

**Comment by mfabiani53** [comment]
I am forced to reload the integration every morning and acter this fo r all the day i have no probs since the next morning.

**Comment by rahaaas** [comment]
Same issue. Multiple instances of reauth over last 12 hours. Announcements are working, strangely.

**Comment by dpgh947** [comment]
Could still be coincidence as this problem seems intermittent and possibly regional if it really is at the amazon end, but I've still had no problems and nothing in logs since I fell back to 4.0.3 yesterday.

**Comment by brinzlee** [comment]
I tried rolling back to 4.0.3. but that doesn't work for me. Got the same reauthentication message 4 hours later

**Comment by saveriospeziali** [comment]
Hi

Same problem for me, for the moment this automation help me:
- id: "restart_alexa"
  alias: "Restart ALEXA MEDIA PLAYER "
  description: ""
  trigger:
    - platform: time_pattern
      hours: "/1"
  condition: []
  action:
    - service: homeassistant.reload_config_entry
      data: {}
      target:
        entity_id: media_player.soggiorno
  mode: single

providing an existing Alexa Media Player entity to homeassistant.reload_config_entry cause the integration to reload but take into account the today in any case I had almost one authentication error

**Comment by dpgh947** [comment]
> 



> I tried rolling back to 4.0.3. but that doesn't work for me. Got the same reauthentication message 4 hours later

Ok, good to know. I'm just being lucky for some reason then...

**Comment by ziolelle** [comment]
I think also my error is related...
<img width="1619" alt="Screenshot 2022-09-04 at 01 27 27" src="https://user-images.githubusercontent.com/24245403/188290505-9e9f67c6-2b84-4f52-9264-cb5cee170bf8.png">

**Comment by dpgh947** [comment]
Well, that will teach me... After working fine for a day and a half, had to reauth 3 times in the past couple of hours. So definitely there on 4.0.3 too.

**Comment by Toggz** [comment]
I'm in the UK and constantly having to re-auth (given up). Changing the volume on an Echo for example triggers a re-auth. Sure it's a Amazon problem, hoping it'll be up and running tomorrow morning. :)
'AlexapyLoginError' throughout Log. eg...

`alexaapi.get_state((<alexapy.alexaapi.AlexaAPI object at 0x7f60cb59h6k0>,), {}): An error occured accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments: ('Login error detected; not contacting API',)`

**Comment by Pirol62** [comment]
Same here in Germany. After a restart of HA this morning alexa started this behaviour that I have to reauth once an hour. Two days ago it happened only two times and then it was stable until this night. I hoped that I'm not affected. It was wrong...

**Comment by dpgh947** [comment]
Completely broken for me now. Reauth, and the next alexa related event breaks it again.

**Comment by DJBenson** [comment]
> Hi
> 
> Same problem for me, for the moment this automation help me:
> 
> * id: "restart_alexa"
>   alias: "Restart ALEXA MEDIA PLAYER "
>   description: ""
>   trigger:
>   
>   * platform: time_pattern
>     hours: "/1"
>     condition: []
>     action:
>   * service: homeassistant.reload_config_entry
>     data: {}
>     target:
>     entity_id: media_player.soggiorno
>     mode: single
> 
> providing an existing Alexa Media Player entity to homeassistant.reload_config_entry cause the integration to reload but take into account the today in any case I had almost one authentication error

This seems to be holding it together for me - it seems to clear any pending reauthenticaton requests and suppresses new ones (so far...). You can pass multiple entities to the service so if you have multiple Echo devices you can call the service once for all of them.

**Comment by saveriospeziali** [comment]
> 



> > Hi
> > Same problem for me, for the moment this automation help me:
> > 
> > * id: "restart_alexa"
> >   alias: "Restart ALEXA MEDIA PLAYER "
> >   description: ""
> >   trigger:
> >   
> >   * platform: time_pattern
> >     hours: "/1"
> >     condition: []
> >     action:
> >   * service: homeassistant.reload_config_entry
> >     data: {}
> >     target:
> >     entity_id: media_player.soggiorno
> >     mode: single
> > 
> > providing an existing Alexa Media Player entity to homeassistant.reload_config_entry cause the integration to reload but take into account the today in any case I had almost one authentication error
> 
> This seems to be holding it together for me - it seems to clear any pending reauthenticaton requests and suppresses new ones (so far...). You can pass multiple entities to the service so if you have multiple Echo devices you can call the service once for all of them.
> 
> Conversely, rolling back to 4.0.3 alone did not solve the issue - immediately after setup I was presented with the re-auth prompts.

Hi, My intention was to reload the integration (in my case even a manual reload fixed te problem), I documented and using homeassistant.reload_config_entry seem the correct way, apparently to reload it is sufficient to pass a single entity among the existing ones..

Regards

**Comment by dpgh947** [comment]
I am getting multiple integrations appearing alongside the real one now. I tried going through configure for these 3, got down to one then the real one complained and I now have 4...

![image](https://user-images.githubusercontent.com/75258259/188322765-0b39e0c1-9a35-4c5e-8f9b-b93a65475242.png)

**Comment by alanmilinovic** [comment]
This is the automation that I have created not just for Alexa but for many other integrations that are not stable.

```
alias: "Reload: Reload Alexa Media Player on unavailable"
description: >-
  Check every 5 minutes if Alexa entity is unavailable for more than 1 minute.
  If yes, then reload Alexa integration.
trigger:
  - platform: time_pattern
    minutes: /5
condition:
  - condition: state
    state: unavailable
    for:
      hours: 0
      minutes: 1
      seconds: 0
    entity_id: media_player.alans_echo_dot
action:
  - service: homeassistant.reload_config_entry
    data: {}
    target:
      entity_id: media_player.alans_echo_dot
mode: restart

```

**Comment by Pirol62** [comment]
Very good idea, but:
Can we assume, that in case of Alexa all devices turn to unavailable so that we only monitor one of them? 
Then it would avoid a lot of errors due to unique key issues when Alexa reloads entities which already exists in case of simply reloading once an hour even it is not really necessary at that time

**Comment by alanmilinovic** [comment]
> Very good idea, but: Can we assume, that in case of Alexa all devices turn to unavailable so that we only monitor one of them? Then it would avoid a lot of errors due to unique key issues when Alexa reloads entities which already exists in case of simply reloading once an hour even it is not really necessary at that time

I just created the script and will monitor to see if the echo dot is unavailable. Might be also better to check for "device_tracker.amazon_alexa" entitiy instead, however, reloading every hour looks a bit too heavy to me.

**Comment by Pirol62** [comment]
Agree

**Comment by oneseventhree** [comment]
@alandtse can you tell us what issue # this a duplicate of so we can follow the progress?

**Comment by alandtse** [comment]
I assume #1701. Your initial report was incomplete so honestly not sure what the error is you're reporting, but all the replies have been tied to the EU auth issue.

If that's not what you're experiencing, please create a new issue with a complete template. Screenshots of issues aren't searchable.
