### ISSUE TITLE
Endless Authentifaction requests s

### ISSUE THREAD

**Issue by mash727** [custom-components/alexa_media_player#1704]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details**
 - Home-assistant (version): 
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: 

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by Friedi1970** [comment]
Already opened: https://github.com/custom-components/alexa_media_player/issues/1701

**Comment by JuergenEhret** [comment]
Same for me ...

**Comment by SGXander** [comment]
+1. sometimes it will stay for a few hours others, 10 minutes but endlessly asking for auth. tried resetting 2FA on my amzn account and using a new code/key but still the same after
