### ISSUE TITLE
Issue with Tunein playback request

### ISSUE THREAD

**Issue by alexisspencer** [custom-components/alexa_media_player#1708]
**Describe the bug**
When calling a Tunein radio station via alexa_media_player app, Alexa reports the station is unavailable on Tunein, however when manually asking Alexa to play the station, she plays it ok.

**To Reproduce**
1. Call service "media_player.play_media"
2. Add data "{
  "entity_id": "media_player.my_echo_show",
  "media_content_id": "radio metro 105.7",
  "media_content_type": "TUNEIN"
}"
3. Fire the service
4. Alexa responds "The radio station radio metro 105.7 is not available on Tunein"
5. Manually speak to Alexa: "Alexa, play radio metro 105.7 from Tunein"
6. Alexa plays the station

**Expected behavior**
Alexa should start playing the station

**Screenshots**
None to show

**System details**
 - Home-assistant (version): 2022.8.7
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): 4.1.0
 - alexapy (version from `pip show alexapy` or HA startup):  1.26.1
 - Amazon [2FA is enabled]:  y

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by alandtse** [comment]
This is the nature of the search function in Alexa. We are just passing your data directly to the  API. You can figure out the right function by trying it in the Alexa App routine using the "Music & Podcasts" option. If you're seeing different results, then we'll need to see your [routine](https://github.com/custom-components/alexa_media_player/wiki/Developers%3A-Sequence-Discovery).

If you just want to repeat what you do with your voice, use the [custom command](https://github.com/custom-components/alexa_media_player/wiki#run-custom-command).
