### ISSUE TITLE
Authentication fails with 500 Internal Server Error

### ISSUE THREAD

**Issue by stalakerob** [custom-components/alexa_media_player#1710]
**Describe the bug**
During installation the auth process fails with a "500 Internal Server Error"

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details**
 - Home-assistant (version): 2022.8.7
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug). No
 - alexa_media  (version from `const.py` or HA startup): latest version from today
 - alexapy (version from `pip show alexapy` or HA startup): using HA docker with alexapy 1.26.2
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: Yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.
got this error:
 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)

**Additional context**

**Comment by alandtse** [comment]
Please search. The cause and issue have been previously discussed.

**Comment by stalakerob** [comment]
I cannot find a discussion that talks about my situation. Some discussions about 500 errors that went away by itself and others are talking about input_number problems etc. Nothing that covers my problem with SSL. So can you tell where to find it?
