### ISSUE TITLE
Access to future notifications (reminders, alarms)

### ISSUE THREAD

**Issue by paoloantinori** [custom-components/alexa_media_player#1712]
**Is your feature request related to a problem? Please describe.**
I'd like to track my future reminders in Alexa. Currently, the integration supports only the *next* one.

**Describe the solution you'd like**
I'd like either a way to get the full list or to at least, receive a notification when a new one gets created/updated/deleted, so that I can use the event in my Automations

**Describe alternatives you've considered**
1. Performing a similar operation directly with https://alexa.amazon.com/api/notifications endpoint, which might be not too complicated to put together a HA Service to produce a full list of available future events. The complexity for an independent component would be to re-implement authentication.
2. Writing a custom Alexa skill, that can potentially access to the notification API from there, and send that information to HA

**Additional context**
My specific use case:
I want to be able to classify some of the reminders I give to Alexa (those related to an action I have to perform on a specific floor of the house) and be able to access that information from HA. Ex: when I go downstairs, a motion sensor detects me and reminds me to close the door and pick up a bottle of wine.

**Comment by alandtse** [comment]
The entire notifications json is exposed with the next_alarm as an attribute such as `Sorted active`. You can parse that. It's been discussed before with examples provide by the community so please search.
