### ISSUE TITLE
I can't communicate with alexa through the home assistant

### ISSUE THREAD

**Issue by samurai313131** [custom-components/alexa_media_player#1718]
Hi, I'm desperate..
one of the things I like the most about HA is the integration of the alexa media player to be able to communicate and send text messages, to then be produced on my echo dot and unfortunately I never managed to do it and I've done a little bit of everything... from uninstalling hacs , the integration of the alexa media player..I even deleted some accounts I had from amazon and made a new one at amazon.es and configured my " alexa " with that same account, hoping to solve it...but nothing and I don't understand why , even because I'm very new in this world of HA!
can anyone help me??
thanks in advance.

the error is this: This error originated from a custom integration.

Logger: alexapy.alexlogin
Source: custom_components/alexa_media/__init__.py:322
Integration: Alexa Media Player (documentation, issues)
First occurred: 11:42:37 (1 occurrences)
Last logged: 11:42:37

Domain amazon.es does not match reported account domain https://www.amazon.com; functionality is not likely to work, please fix

**Comment by alandtse** [comment]
Login to amazon.es instead of amazon.com

**Comment by samurai313131** [comment]
> Faça login em amazon.es em vez de amazon.com

yes that was enough...thanks a lot, which for some is basic, for those who have been in this world for a short time is difficult!
