### ISSUE TITLE
Use websocket data for player for EU

### ISSUE THREAD

**Issue by alandtse** [custom-components/alexa_media_player#1723]
**Describe the bug**
EU servers are kaput when querying the webplayer. Investigate alternative API or just use the limited websocket data. 

**To Reproduce**
Use EU domain. 

**Expected behavior**

**Screenshots**

**System details**

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.
Logs in linked issue.

**Additional context**
https://github.com/custom-components/alexa_media_player/issues/1711#issuecomment-1241657542

**Comment by ThijmenDam** [comment]
I wonder, why does the media player information (for EU domains) sometimes still come through, just very inconsistent? In my case every few minutes or so the media player shows the correct song, and then goes back to standby mode.

**Comment by TheRabbitOnTheRun** [comment]
I have this same issue here (UK) Call for music to play from Amazon, the echo will play fine, AMP will show the song information and set its state to playing for about 5 second then returns to standby state with the music still playing fine but no information/album cover art etc. this prevent any control of the player except for volume control. I'm hoping with someone's  help we can get it working again as AMP has been working so good for me.

**Comment by ThijmenDam** [comment]
Media player information seems to be working properly on EU since this morning. Will keep you posted.

**Comment by alandtse** [comment]
As mentioned in the linked comment, Amazon's servers are having internal errors randomly. We can't get info when that happens.

**Comment by WhimsySpoon** [comment]
Is anyone else experiencing this again, as of the past few days.

**Comment by TheRabbitOnTheRun** [comment]
> Is anyone else experiencing this again, as of the past few days.

Since this resolved last September, everything has been working ok with no issues (Uk)
