### ISSUE TITLE
notify.alexa_media doesn't work with stereo echos

### ISSUE THREAD

**Issue by viperxeno** [custom-components/alexa_media_player#1728]
@alandtse  Hi, i found bug on alexa media player, if i play a notification via the notify.alexa_media service on the "sala da pranzo"(see photo) group composed of 2 stereo echos + subwoofer the notification works fine, but if I play it on a "soggiorno"(see photo) group where there is the stereo echos + sub and another echo device the notification is only reproduced on the single echo device and not on the echo stereo + sub pair.  is it possible to fix this problem?  thank you

![Screenshot_20220917-064536_Amazon Alexa](https://user-images.githubusercontent.com/105608752/190841140-56914a0e-27d7-42b0-bfde-6b0550126c0f.jpg)

![Screenshot_20220917_070017](https://user-images.githubusercontent.com/105608752/190841370-bca16528-59ca-425d-8bc2-9d2cd870d581.jpg)

![Screenshot_20220917_064553](https://user-images.githubusercontent.com/105608752/190841433-52e301fe-84b8-42fd-95f2-b6c63a3fd9fc.jpg)

![Screenshot_20220917_065934](https://user-images.githubusercontent.com/105608752/190841381-47d6ea61-da9d-426c-a28a-42b0cb0df12d.jpg)

**Comment by alandtse** [comment]
Please use the template.

**Comment by alandtse** [comment]
Please use the template for bug reports. My response until then is what happens if you use a routine in the official app?

**Comment by jj-uk** [comment]
As far as I can see, in the Alexa app, you cannot create a routine to speak on more than one device, and cannot select a speaker group.

**Comment by viperxeno** [comment]
In official App Alexa I can't create a routine to speak on a speaker group.

**Comment by alandtse** [comment]
Ok. Then since we replicate the app, this isn't something we can solve since it's not supported by Amazon.

**Comment by jj-uk** [comment]
It's possible to send messages to speaker groups with alexa_media, but not with the app.
