### ISSUE TITLE
Feature Request: Wake up service

### ISSUE THREAD

**Issue by Risbo6** [custom-components/alexa_media_player#1731]
Would it be possible to wake up the device by calling a service from home assistant?

**Comment by alandtse** [comment]
I was not aware Alexa devices could sleep. Are you talking about the show? Can you find an option in the official Alexa app? If not, probably not.

**Comment by alandtse** [comment]
Is it available in the Amazon Alexa app?

**Comment by popy2k14** [comment]
I need this feature too.
On the echo shows you can say "Alexa Display off".
After that when you just say Alexa, it switches on the display and listening...

But when you send an custom command "Alexa Display on" it does not work.

Is there such a feature?

**Comment by alandtse** [comment]
> I need this feature too.
> On the echo shows you can say "Alexa Display off".
> After that when you just say Alexa, it switches on the display and listening...
> 
> But when you send an custom command "Alexa Display on" it does not work.
> 
> Is there such a feature?

https://github.com/custom-components/alexa_media_player/issues/1731#issuecomment-1264594021

**Comment by popy2k14** [comment]
> > I need this feature too.
> > On the echo shows you can say "Alexa Display off".
> > After that when you just say Alexa, it switches on the display and listening...
> > But when you send an custom command "Alexa Display on" it does not work.
> > Is there such a feature?
> 
> [#1731 (comment)](https://github.com/custom-components/alexa_media_player/issues/1731#issuecomment-1264594021)

Sadly, did'nt found way in the app to archive this.

**Comment by popy2k14** [comment]
bump
