### ISSUE TITLE
Sound detection

### ISSUE THREAD

**Issue by broyuken** [custom-components/alexa_media_player#1736]
Is there any way you can expose the new “sound detection” triggers to HA? I’m looking to be able to do things like turn on my bathroom fan when the humidity is above a threshold, but only if Alexa hears water running, and things like that.

**Comment by alandtse** [comment]
Is it available in the Amazon Alexa app?

**Comment by broyuken** [comment]
Sort of. You can use those sounds as triggers for routines. Not sure if there’s something you could expose or if I have to get creative with a binary sensor from HA and an alexa routine

**Comment by broyuken** [comment]
And this is not a dupe of 1741. My request is Alexa can listen for certain sounds like water running or babies crying. The other uses the ultrasonic sensor to detect presence.

**Comment by rocnydad** [comment]
Similarly the Echo Show devices can detect motion using their cameras.  I’m not sure if this is stored the same way as the ultrasonic motion detection. This would be a fantastic feature to add to Home Assistant.

Also, they have added this ultrasonic motion detection to the Gen 4 Echo Dots. Great for triggering lights when you enter a room, etc.

**Comment by broyuken** [comment]
Is this something you think would be possible to add or would I need to create an Alexa routine with those triggers and have them turn on binary sensors/buttons in HA?

**Comment by alandtse** [comment]
No idea. If you check the websocket traffic, does it provide access to the info? While it's exposed for Alexa routines, if we can't access it in real time then we can't.

**Comment by atv2016** [comment]
This would be interesting indeed, i believe Alexa calls it occupancy detection.

**Comment by benedikt-bartscher** [comment]
Having the occupancy detection available as a sensor would be awesome. Echo dots have a pretty good ultrasonic occupancy sensor.

**Comment by JonSilver** [comment]
> i believe Alexa calls it occupancy detection.

No, this is an entirely different feature from the ultrasonic occupancy detection. It's an AI feature that listens for specific sounds, like water running, baby crying or snoring. You can use it as a trigger for routines, and trigger HA when it happens.

**Comment by atv2016** [comment]
Which echo's have ultrasonic detection ?

But yeah, agreed would be nice to have sound or occupance detection.
________________________________

**Comment by tiagoroxo** [comment]
Documentation: https://www.amazon.com/gp/help/customer/display.html?nodeId=GSR22RYDWS3KBUYW

This is what look like from the app:
![IMG_20230124_122556 (1)](https://user-images.githubusercontent.com/251005/214292755-3f097cda-75c4-4ca9-8489-c622230250ff.PNG)

-> Is this information exposed via websocket traffic?

**Comment by broyuken** [comment]
No it’s not. I am talking about sound detection, not ultrasonic.

**Comment by neil1111** [comment]
Any progress on this?  I'm also having troubles with ultrasonic detection. The logs show many occurences of the following:

2023-02-05 08:43:29.205 DEBUG (MainThread) [homeassistant.helpers.ratelimit] Reached rate limit of 0:01:00 for Template("{{ is_state('switch.dining_room_dot_ultrasound_motion', 'on', 'off') }}") and deferred action until 2023-02-05 13:44:28.081826+00:00
2023-02-05 08:43:29.205 DEBUG (MainThread) [homeassistant.helpers.ratelimit] Reached rate limit of 0:01:00 for Template("{{ is_state('switch.bath_dot_ultrasound_motion', 'on', 'off') }}") and deferred action until 2023-02-05 13:44:28.100051+00:00

**Comment by broyuken** [comment]
Open a new ticket for ultrasonic detection. This issue has nothing at all to do with that. Stop posting ultrasonic stuff in this issue please.

**Comment by neil1111** [comment]
Sorry, I thought the root cause of the volume of data causing this error might be related. I will open it as a separate issue.
________________________________
