### ISSUE TITLE
Alexa stopped responding to scripts triggered by automations in Home Assistant. 

### ISSUE THREAD

**Issue by mdanilohome** [custom-components/alexa_media_player#1746]
Automations with voice actions are working normally but my Alexa devices have stopped responding. For example, when a port is opened, I have a script to warn the port open that runs but the Alexa device does not speak the configured phrase. This problem started to occur suddenly without any changes or new installations in Home Assistant.

**System details**
 - Home-assistant (version): 2022.9.4
 - alexa_media  :  4.1.2
 - alexapy (version from `pip show alexapy` or HA startup): 1.26.3
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). :  yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). 

**Additional context**

**Comment by mdanilohome** [comment]
I just restarted the Home Assistant once again and everything went back to normal.

**Comment by ThijmenDam** [comment]
This is not a problem of HA / AMP, but has something to do with Amazon's servers I think. Try your voice commands by physically saying them to your Alexa, and you should see the same issues.

**Comment by alandtse** [comment]
Ok, looks like this was a transient Alexa issue. Please reopen if it comes back and persists.
