### ISSUE TITLE
Unexpected error fetching alexa_media data: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by jocamane** [custom-components/alexa_media_player#1748]
Error:

This error originated from a custom integration.

Logger: custom_components.alexa_media
Source: custom_components/alexa_media/__init__.py:546
Integration: Alexa Media Player (documentation, issues)
First occurred: 13:00:53 (1 occurrences)
Last logged: 13:00:53

Unexpected error fetching alexa_media data: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/alexa_media/__init__.py", line 546, in async_update_data
    if "doNotDisturbDeviceStatusList" in dnd:
TypeError: argument of type 'NoneType' is not iterable

**System details**
Home Assistant 2022.9.7
Supervisor 2022.09.1
Operating System 9.0
Frontend 20220907.2 - latest
  
    "alexa_media": {
      "version": "4.1.2",
      "requirements": [
        "alexapy==1.26.3",
        "packaging>=20.3",
        "wrapt>=1.12.1"

**Comment by alandtse** [comment]
Does not use template.

**Comment by jocamane** [comment]
thanks for the reply, but please tell me what you mean by "Does not use template.".

This is a template ?

service: notify.alexa_media_alexa_da_sala
**data:
  message: >-
    <audio src="soundbank://soundlibrary/clocks/watches/watches_01"/> ATENTION <audio
    src="soundbank://soundlibrary/machines/power_up_down/power_up_down_02"/> 
  data:
    type: tts**

Thanks
