### ISSUE TITLE
Prefix for all added entities

### ISSUE THREAD

**Issue by mohoo** [custom-components/alexa_media_player#1749]
Precondition:
Hello, I have home assistant (2022.7.7) running and Alexa Smart integration enabled (https://www.home-assistant.io/integrations/alexa.smart_home/).
I have now installed alexa_media_player and successfully logged in with my amazon account. All my Alexa Echo devices have been created as Device / Entity. 

Issue:
Unfortunately, the Alexa Smart Integration grabs all entities and puts them as duplicates in Alexa. All Echos are duplicated, as well as the special entities created by alexa_media_player, like ".. shuffle switch" or ".. do not disturb switch".

Workaround:
It is clear that this problem can be worked around by adding all entity ids to the exclude list of the Alexa Smart Integration. However, it can be very annoying if there are a lot of devices, because each device creates multiple entities as known, so it is very tedious to enter all these entity ids into the exclude list. Furthermore this workaround is not safe against newly added devices or device renaming. 

Solution:
It would be wonderful if all entities that are added by alexa_media_player would get a prefix. Either a fixed prefix like "alexa_media" or an optional prefix that can be set in the configuration. 
This way all alexa_media_player entities could be excluded via the Alexa Smart integration configuration with one line. 
For example, with the setting exclude_entity_globs (https://www.home-assistant.io/integrations/alexa.smart_home/#exclude_entity_globs), one line could always exclude all current entities, all new entities added in the future, and all renamed entities: 
```yaml
alexa:
  smart_home:
    filter:
      exclude_entity_globs:
        - "*.alexa_media_*"
```

**Comment by techrajdeep** [comment]
Hey @alandtse , I am looking for an issue for my first contribution . Can you help me here.

**Comment by alandtse** [comment]
I thought I had responded, but the issue with renaming entities is that it'd be a major breaking change. We may allow it for an optional setting so users can decide whether they want to rename them all.
