### ISSUE TITLE
Unexpected error fetching alexa_media data: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by jocamane** [custom-components/alexa_media_player#1753]
**Describe the bug**
error message appears in the HA core log

**To Reproduce**

1. Go to LOGS
2. See error

**Expected behavior**
I hoped there was no error

**Screenshots**
![image](https://user-images.githubusercontent.com/32019937/195861744-fb9b0dbc-229e-4b88-a8ec-38cecc2a82b7.png)

**System details**
 - Home-assistant (version): 2022.9.7
 - alexa_media  (version from `const.py` or HA startup): 4.1.2
 - alexapy (version from `pip show alexapy` or HA startup): 1.26.3
 - Amazon [2FA is enabled]: YES

**Logs**
This error originated from a custom integration.

Logger: custom_components.alexa_media
Source: custom_components/alexa_media/__init__.py:546
Integration: Alexa Media Player (documentation, issues)
First occurred: 13:00:46 (1 occurrences)
Last logged: 13:00:46

Unexpected error fetching alexa_media data: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/alexa_media/__init__.py", line 546, in async_update_data
    if "doNotDisturbDeviceStatusList" in dnd:
TypeError: argument of type 'NoneType' is not iterable

**Additional context**
Random. I don't know when it happens

**Comment by JB09** [comment]
Same issue.  Started early/mid September.  After the issue occurs, I no longer get state updates (ie. paused, playing) for my Alexa media_player's, but notifications (announce, tts) still work.  Reloading the integration fixes the issue until the error appears again.  One other comment about my setup is that I do have one echo device that is only plugged occasionally (I use it outdoors), and maybe causing the API to return a 'None' object in the device list?

**Comment by jocamane** [comment]
> Same issue. Started early/mid September. After the issue occurs, I no longer get state updates (ie. paused, playing) for my Alexa media_player's, but notifications (announce, tts) still work. Reloading the integration fixes the issue until the error appears again. One other comment about my setup is that I do have one echo device that is only plugged occasionally (I use it outdoors), and maybe causing the API to return a 'None' object in the device list?

Hi, How can I test if in my case I don't have the state updates either?

**Comment by JB09** [comment]
> Hi, How can I test if in my case I don't have the state updates either?

If you see the error in your logs (and you haven’t re-loaded the Alexa Media integration) try playing music on an echo device and see if the state updates in the Developer Tools tab on HA.  If it doesn’t say playing, re-load only the Alexa Media integration and see if the state is now populated properly.

**Comment by JB09** [comment]
`Logger: homeassistant
Source: custom_components/alexa_media/__init__.py:784 
Integration: Alexa Media Player (documentation, issues) 
First occurred: October 12, 2022 at 7:01:05 PM (1 occurrences) 
Last logged: October 12, 2022 at 7:01:05 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/alexapy/alexawebsocket.py", line 263, in process_messages
    await self.on_message(cast(bytes, msg.data))
  File "/usr/local/lib/python3.10/site-packages/alexapy/alexawebsocket.py", line 274, in on_message
    await self.msg_callback(message_obj)
  File "/config/custom_components/alexa_media/__init__.py", line 1042, in ws_handler
    await update_dnd_state(login_obj)
  File "/config/custom_components/alexa_media/helpers.py", line 156, in _catch_login_errors
    result = await func(*args, **kwargs)
  File "/config/custom_components/alexa_media/__init__.py", line 784, in update_dnd_state
    if "doNotDisturbDeviceStatusList" in dnd:
TypeError: argument of type 'NoneType' is not iterable`

This also started showing up in the logs when I updated HA a few days ago.

**Comment by jocamane** [comment]
> > Hi, How can I test if in my case I don't have the state updates either?
> 
> If you see the error in your logs (and you haven’t re-loaded the Alexa Media integration) try playing music on an echo device and see if the state updates in the Developer Tools tab on HA. If it doesn’t say playing, re-load only the Alexa Media integration and see if the state is now populated properly.

Hi, in my case all work fine. when i put music state change to playing and when i stop change to paused
