### ISSUE TITLE
Echo device status no being updated

### ISSUE THREAD

**Issue by Peter-HVD** [custom-components/alexa_media_player#1759]
### Discussed in https://github.com/custom-components/alexa_media_player/discussions/1750

<div type='discussions-op-text'>

<sup>Originally posted by **Peter-HVD** October 11, 2022</sup>
All seems correctly set up, but if I (or a routine) starts something playing on an Echo device, the status in Home Assistant is not being updated. 

For example, in the History for a particular device, all that is ever shown is "Standby" and there are no Log Book events. And yet, for 3 hours last night I had a sleep sound playing, so it should have said, at the very least, "Playing".

Is there something I've missed?

Thanks</div>

I've done some extra digging and it appears that the problem is only with sounds played by skills.

For example - if I ask Alexa to play some music (for me, via Amazon Music) then the state updates to "playing" and the info for the song is displayed in the media player card. However, if I ask "Alexa, ask Ambient Sounds to play thunderstorms" then the state does not change from "Standby" and the media player card displays nothing.

I suspect this is an Amazon problem, but it's worth raising it as an issue as there might be something you can do.

Thanks.

**Comment by alandtse** [comment]
Please use the bug report template.

**Comment by Peter-HVD** [comment]
> Please use the bug report template.

Then maybe you should have a word with Github because I just used the "Create issue from discussion" button in the sidebar on my original post.
