### ISSUE TITLE
Alexa does not announce anymore using service call

### ISSUE THREAD

**Issue by atv2016** [custom-components/alexa_media_player#1774]
**IMPORTANT:  Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**
This does not work anymore:
```
service: notify.alexa_media_everywhere
data:
  data:
    type: announce
    method: all
  message: test test
```

**To Reproduce**

See above

**Expected behavior**
To have alexa announce on all alexas

**Screenshots**

**System details**
 - Home-assistant (version): 
 Home Assistant 2022.11.1
Supervisor 2022.10.2
Operating System 9.3
Frontend 20221102.1 - latest
 - alexa_media  (version from `const.py` or HA startup): 4.3.2
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). 

**Additional context**

**Comment by George2512** [comment]
I suddenly faced the same issue!!

**Comment by alandtse** [comment]
Does the app work still for you?

**Comment by atv2016** [comment]
This seems to have resolved it for me automagically. I guess you were right Alexa got itself in a fugue state. Disconnected them all and reconnected. Took a while but they are all now announcing in unison again. Good times.
________________________________
