### ISSUE TITLE
Use Nabu Casa Cloud TTS for Alexa 

### ISSUE THREAD

**Issue by butako** [custom-components/alexa_media_player#1775]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**
I would like to use the Nabu Casa Cloud TTS as an alternative to Amazon. Many posts on the internet say that is not possible, but after a bit of work I found one: https://community.home-assistant.io/t/tts-cloud-say-and-amazon-alexa/279085
The Nabu Casa TTS is nice because it offers several options for voice customization.

**Describe the solution you'd like**
Must have the Nabu Casa Remote UI enabled. Then use get_tts_url API to request the TTS and it returns an MP3 URL, which can then be sent to Amazon with the notify service. For Echo to play the file the URL domain must be the nabu.casa one. 

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by alandtse** [comment]
Given it's already possible without a code change as listed in that thread, I'm not sure what you want done.
