### ISSUE TITLE
Pull information from temperature sensor on Alexa Echo Plus

### ISSUE THREAD

**Issue by jcanales1926** [custom-components/alexa_media_player#1776]
The Alexa Echo plus has a temperature sensor that is available to read in the Alexa App. The request is to be able to pull the information from that sensor. With temperature I mean celcius/farenheit temperature. 

![IMG_BA357831B1D1-1](https://user-images.githubusercontent.com/105359688/200373024-80af05db-6ebd-40cc-81e9-370780bf5760.jpeg)

**Comment by alandtse** [comment]
We already pull it.
