### ISSUE TITLE
Alexa media players not updating status

### ISSUE THREAD

**Issue by berkansezer77** [custom-components/alexa_media_player#1777]
I have 3 echo dots 3rd generation, 1 echo show 5 and a FireTV setup. For the last 2 days all of my echo devices stopped updating status while playing spotify. If I start a spotcast music within home assistant for lets say my echo show 5, the music starts without a problem but when I check developer status it says its on standby.  If I move the volume slider from info screen the media player updates and status turns to "playing". After that if I transfer music to a different echo device, the device that was previously playing still shows as "playing" even thoug it is not. 

The only solution I have found for now is to force update media players with a time pattern automation.

**Comment by TBE4034** [comment]
I am having this same issue, though it appears specific to speaker groups.
If playing music on one specific echo, the state does update to "playing".
If playing music on the "everywhere group", all echos remain in "idle" or "standby state".
Force updating the entity also does not update the state.
