### ISSUE TITLE
Include information about which person is talking to Alexa

### ISSUE THREAD

**Issue by ndbroadbent** [custom-components/alexa_media_player#1783]
**Is your feature request related to a problem? Please describe.**

I am trying to set up a routine in Alexa so that I can say "Where's my phone?", and trigger a script in HA to call `icloud.play_sound` on my phone (though the iCloud "Find My" integration.) (This is way better and louder than Alexa's version.)

**Describe the solution you'd like**

I want to be able to detect which person is talking to Alexa and have this available as a sensor, so that my wife can also say "Where's my phone?", and it would play a sound on her phone instead of mine. Alexa is already doing voice detection to figure out which person is speaking, and the information is shown in the Alexa app.

**Describe alternatives you've considered**

I would have to set up specific voice routines such as "Where is Nathan's phone", but that doesn't feel as nice. I also have room presence detection working via bluetooth, so I could use this information, but it doesn't work if two people are in the same room.

Related:

* Old closed issue: #455

**Comment by alandtse** [comment]
I realize we didn't state it in the closed issue, but the prior investigation didn't show any usable information. You can try to look again now to see if it's provided. The same steps from before probably still apply.

**Comment by rlippmann** [comment]
https://developer.amazon.com/en-US/docs/alexa/custom-skills/add-personalization-to-your-skill.html

It looks like this information is only available to skills.

**Comment by rlippmann** [comment]
https://developer.amazon.com/en-US/docs/alexa/custom-skills/add-personalization-to-your-skill.html

It looks like this information is only available to skills.
