### ISSUE TITLE
Sensor for door bell notification

### ISSUE THREAD

**Issue by simphide** [custom-components/alexa_media_player#1784]
**Is your feature request related to a problem? Please describe.**
It would be great if there would be a sensor for door bell notifications. If somebody rings the door and for example a Ring device would notify through an alexa device it would be awesome if a sensor would change in HomeAssistant. Through that many automations could be created. By this we could also support Ring devices that are not (and probably won't be in near future) by the ring integration yet.

**Describe the solution you'd like**
A sensor that turns on for ~3 seconds when somebody rang the door

This is also already available as a trigger for Alexa routines

**Describe alternatives you've considered**
I think that should be the best way

**Additional context**
-

**Comment by alandtse** [comment]
Can this be seen in the Alexa app? Also, most doorbell sensors are events that you have to write automations against. Are you looking for that event?

**Comment by simphide** [comment]
I don't think it can be seen as a direct sensor but as an event like you mentioned. For example it can be used as a trigger inside the Alexa app for automations.

**Comment by alandtse** [comment]
Please [enable](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component) alexapy debugging and see if the doorbell actually generates an event.

**Comment by simphide** [comment]
> Please [enable](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component) alexapy debugging and see if the doorbell actually generates an event.

Currently I am not at home. I will try it out as soon as I am back on the 11th of December!

**Comment by simphide** [comment]
It sadly looks like there is no event generated...

**Comment by alandtse** [comment]
That's unfortunate. Based on that, the best I think that can be done is to use the routines to activate something that HA can see and trigger on that.
