### ISSUE TITLE
Play Everywhere not working for new and renamed devices.

### ISSUE THREAD

**Issue by sheminasalam** [custom-components/alexa_media_player#1787]
**IMPORTANT:  Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

I have added a new amazon echo show 8 and renamed an echo dot. When I use notify.alexa_media_everywhere to play tts everywhere, only the old devices plays tts. The newly added and renamed devices doen't work. But they work when I use there specific notify service.

**To Reproduce**

1. Add a new device or rename a device
2. call service notify.alexa_media_everywhere
3. The tts will not work for new or renamed devices.

**Expected behavior**
notify everywhere service should work for all devices.

**Screenshots**

**System details**
 - Home-assistant (version): Home Assistant 2022.11.5
 - alexa_media  (version from `const.py` or HA startup): 4.3.2
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : enabled

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). 

**Additional context**

**Comment by alandtse** [comment]
The Everywhere group is created by Amazon. Does it work in the app after you do this?

**Comment by sheminasalam** [comment]
As said the new echo show was missing in everwhere group. Thanks
