### ISSUE TITLE
Error after "Loading next step" and New access token received

### ISSUE THREAD

**Issue by Thyphus** [custom-components/alexa_media_player#1788]
**Describe the bug**
The integration of alexa media player doesn't arrive to finish the isntallation. After I authenticate my connexion with amazon, it loops in state "Loading next step for Alexa media player" until a pop-up "Error".
The authentication of the amazon credential seems to work, I have the sentence "success, you can close this windows".
I don't know if it's the cause of my issue but I change my router (my gateway was 192.168.0.1 and become 192.168.1.1). I connect all my echo to the new router wifi but the integration in HA is failed.
I only change the router and nothing about the configuration in HA.
With my old router the integration worked fine.

I uninstall the integration, remove from HACS, reboot and try again, but it's style has the same behaviour.

**To Reproduce**
Maybe changes the router or the gateway.

**Expected behavior**
I expected I retrieved all my device of my amazon echo and I can use TTS commands for example.

**Screenshots**
2 screenshots showing the 2 pop-up explained in description.

**System details**
 - Home-assistant (version): 2022.11.2
 - alexa_media  (version from `const.py` or HA startup): v4.3.2
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](y/n) : n

**Logs**
I join log's file and in the end of log we can see:
{"requested_extensions"}, {"Value":}
2022-12-02 11:20:24.715 DEBUG (MainThread) [alexapy.alexalogin] Successfully registered ***'s 16th Alexa Media Player device with Amazon
2022-12-02 11:20:24.715 DEBUG (MainThread) [alexapy.alexalogin] Received registration data:
{"success": ***}}
2022-12-02 11:20:24.716 DEBUG (MainThread) [alexapy.alexalogin] New access token received which expires at 2022-12-02 12:20:24.716127 in 0:59:59.999968

**Additional context**
The Alexa provided by home assistant works fine without changes everything.
I'm able to access to my HA outside of my private network.

![error](https://user-images.githubusercontent.com/90202991/205513780-389576d1-5d6b-4621-9064-ca34ff963d25.png)
![LoadInfinite](https://user-images.githubusercontent.com/90202991/205513782-48b283ba-dc91-4b30-be6b-49cc0044308b.png)
[Log.txt](https://github.com/custom-components/alexa_media_player/files/10149394/Log.txt)

**Comment by Thyphus** [comment]
It seems the Amazon authentication is a success but after we fall in timeout I think.

Is it a way to remove all modification or file create by the integration (maybe there is a part of file which use the old parameters)?

Can we add some trace to understand the problem?

**Comment by alandtse** [comment]
You'd need to use a python debugger if it's not proceeding. The code that is impacted is here:
https://github.com/custom-components/alexa_media_player/blob/dev/custom_components/alexa_media/__init__.py#L323-L330

This calls https://gitlab.com/keatontaylor/alexapy/-/blob/dev/alexapy/alexalogin.py#L456.

**Comment by alandtse** [comment]
So for some reason, the next call [exchange_token_for_cookies](https://gitlab.com/keatontaylor/alexapy/-/blob/dev/alexapy/alexalogin.py#L457
) is not completing.

It should look like this. I can't solve this without a debugger seeing why it's stalling and not continuing but this would likely be issues with aiohttp or the network infrastructure. Without the cookie exchange, we can't process anything so I can't bypass this state.

```
2022-12-29 03:41:26.997 DEBUG (MainThread) [alexapy.alexalogin] New access token received which expires at 2022-12-29 04:41:26.997375 in 0:59:59.999965
2022-12-29 03:41:27.184 DEBUG (MainThread) [alexapy.alexalogin] Exchange cookie json {'tokens': {'cookies': {'.amazon.com': [{'Path': '/', 'Secure': True, 'Value': '137-3920238-2274651', 'Expires': '24 Dec 2042 03:41:27 GMT', 'HttpOnly': False, 'Name': 'session-id'}, {'Path': '/', 'Secure': True, 'Value': '133-6287784-8917237', 'Expires': '24 Dec 2042 03:41:27 GMT', 'HttpOnly': False, 'Name': 'ubid-main'}, {'Path': '/', 'Secure': True, 'Value': '"SNIP"', 'Expires': '24 Dec 2042 03:41:27 GMT', 'HttpOnly': False, 'Name': 'x-main'}, {'Path': '/', 'Secure': True, 'Value': '"SNIP', 'Expires': '30 Dec 2022 03:41:27 GMT', 'HttpOnly': True, 'Name': 'at-main'}, {'Path': '/', 'Secure': True, 'Value': '"SNIP+4sY5E="', 'Expires': '30 Dec 2022 03:41:27 GMT', 'HttpOnly': True, 'Name': 'sess-at-main'}]}}} 
2022-12-29 03:41:27.185 DEBUG (MainThread) [alexapy.alexalogin] 5 cookies successfully exchanged for refresh token for domain .amazon.com
```

**Comment by Cmo2788** [comment]
will be following on here, if you guys need anything @ me, thanks for moving my issue over, i dont know how i missed this when i was looking for it earlier. :)

**Comment by Thyphus** [comment]
No problem to use the python debbuger but I need help to launch the debbuger with the good parameters :)
I need to use the python debbuger provided by HA?

I agree with you, it's the exchange_token_for_cookies which block.

I understand why I didn't see the debug trace in your code in my HA disk. It's because the file alexalogin.py is not accessible. Is it possible to modify the file? If the python debbuger is to difficult, I would to write debug trace before and after each function in  exchange_token_for_cookies.

I would add several new informations:
- I create another VM (my actual home assistant OS run into a VM in Truenas Scale), I use the same domain with another port to access my fresh HAOS. I have the same behaviour. So it's not my HA but like you said, aiohttp or the network infrastructure. I just change my router and everything works except this integration (I disable the firewall of the router but it's not work)
- I use amazon.fr
- I upgrade to 4.4.0 and I have a 404 error during the auth but we arrive to generate the token

`2022-12-30 08:18:53.400 DEBUG (MainThread) [authcaptureproxy.helper] POST: redirected from
https://www.amazon.com/ap/signin
2022-12-30 08:18:53.402 DEBUG (MainThread) [authcaptureproxy.helper] GET: 
[...]
returned 404:Not Found with response Headers([('content-type', 'text/html;charset=UTF-8'), ('transfer-encoding', 'chunked'), ('connection', 'keep-alive'), ('server', 'Server'), ('date', 'Fri, 30 Dec 2022 07:18:53 GMT'), ('x-amz-rid', 'XXX'), ('set-cookie', 'session-id=XXX; Domain=.amazon.com; Expires=Sat, 30-Dec-2023 07:18:53 GMT; Path=/; Secure'), ('set-cookie', 'session-id-time=2303104733l; Domain=.amazon.com; Expires=Sat, 30-Dec-2023 07:18:53 GMT; Path=/; Secure'), ('set-cookie', 'ubid-main=XXX; Domain=.amazon.com; Expires=Sat, 30-Dec-2023 07:18:53 GMT; Path=/; Secure'), ('set-cookie', 'session-token=XXX; Domain=.amazon.com; Expires=Sat, 30-Dec-2023 07:18:53 GMT; Path=/; Secure'), ('x-xss-protection', '1'), ('x-content-type-options', 'nosniff'), ('x-ua-compatible', 'IE=edge'), ('strict-transport-security', 'max-age=47474747; includeSubDomains; preload'), ('vary', 'Content-Type,Accept-Encoding,User-Agent'), ('p3p', 'policyref="http://www.amazon.com/w3c/p3p.xml",CP="CAO DSP LAW CUR ADM IVAo IVDo CONo OTPo OUR DELi PUBi OTRi BUS PHY ONL UNI PUR FIN COM NAV INT DEM CNT STA HEA PRE LOC GOV OTC "'), ('x-frame-options', 'SAMEORIGIN'), ('x-cache', 'Error from cloudfront'), ('via', '1.1 XXX.cloudfront.net (CloudFront)'), ('x-amz-cf-pop', 'MRS52-P3'), ('x-amz-cf-id', 'XXX')])
2022-12-30 08:18:53.402 DEBUG (MainThread) [authcaptureproxy.helper] Running coroutine test_amazon_url
2022-12-30 08:18:53.437 DEBUG (MainThread) [authcaptureproxy.auth_capture_proxy] Proxy data reset.
2022-12-30 08:18:53.437 DEBUG (MainThread) [authcaptureproxy.auth_capture_proxy] Test test_amazon_url triggered
2022-12-30 08:18:53.437 DEBUG (MainThread) [authcaptureproxy.auth_capture_proxy] Redirecting to callback: XXX
2022-12-30 08:18:53.450 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Checking proxy response for XXX - amazon.fr
2022-12-30 08:18:53.500 DEBUG (MainThread) [alexapy.alexalogin] Attempting to register with amazon.fr
[...]
2022-12-30 08:18:54.403 DEBUG (MainThread) [alexapy.alexalogin] Successfully registered XXX's 16th Alexa Media Player device with Amazon
2022-12-30 08:18:54.403 DEBUG (MainThread) [alexapy.alexalogin] New access token received which expires at 2022-12-30 09:18:54.403776 in 0:59:59.999970`

**Comment by Cmo2788** [comment]
fixed this on my end, disabling ipv6 let the integration install and discovered all devices.

**Comment by Thyphus** [comment]
I try to disable the ipv6 and it works too for me. I retrieve all my device and I can control them.
Thank you all for your help and Cmo2788 for the solution.

Alandtse you can reproduce the bug I think. I let you manage the issue.

**Comment by heyster** [comment]
@Cmo2788, thank you so much for the comment about IPv6. I disabled IPv6 in HA Network settings, restarted, and everything works again. I had been experiencing failure of the integration to startup for quite a while now. Suffering by myself, trying to debug, seeing the `aiohttp` timeout. Long time spent initializing, then usually failure, and many times telling me I needed to reauthenticate with Amazon. Other integrations were very slow to start until disabling IPv6. Now startup is fast. Thanks a bunch!

**Comment by rdbtn-no** [comment]
I am running into this problem.  Where did you disable ipv6?

**Comment by rdbtn-no** [comment]
@Cmo2788, thank you for figuring this out, and @heyster, thanks for describing exactly what you did, and where you did it!  My automations that rely on alexa_media_player worked again immediately after a restart of HA after disabling IPV6!

**Comment by jeffersonbernardo1981** [comment]
@Cmo2788 Perfeito fiz exatamente que vc comentou e deu certo, muito obrigado!

**Comment by mansouryaacoubi** [comment]
Thanks a lot! I've been searching for a fix quite a while but this workaround did the trick.
I was always getting a Gateway timeout Error but after disabling ipv6 in my Router everything works Like a Charm.
