### ISSUE TITLE
List the MemberDevices of a DeviceGroup

### ISSUE THREAD

**Issue by LunkwillAndFook** [custom-components/alexa_media_player#1798]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**
I'm not sure which APIs alexa_media_player is using but this *appears* to be doable via https://developer.amazon.com/en-US/docs/alexa/alexa-smart-properties/alexa-for-residential-device-group-mgt-api.html#list-groups. 

**Is your feature request related to a problem? Please describe.**
I want to iterate the Echos in the device group to set volume prior to playing media on the group. It would be awesome if the media players for Alexa Device Groups would list the Echos in the group as an attribute of the media player. This would allow me to easily iterate the devices in the device group and reset volumes prior to playing music via automation or script.

**Describe the solution you'd like**
List the Echo devices in the Device Group as an attribute of the Media Player for the Device Group.

**Describe alternatives you've considered**
My alternative is to maintain a manually configured Group integration in Home Assistant which is disconnected from the Device Group configured in the Alexa app. This is not an ideal workaround since they can very easily get out of sync if an echo is added or removed from the Device Group and also requires knowledge of YAML to rectify.

**Additional context**

**Comment by alandtse** [comment]
We don't use the developer API. We used an unpublished API used by the app. So you'd have to figure out if the Alexa App has something like this for us to try to reproduce.

**Comment by LunkwillAndFook** [comment]
@alandtse The app does this when you create and edit the device group, so it must be supported by the unpublished APIs as well.
![Screenshot_20221213-104344_Amazon Alexa](https://user-images.githubusercontent.com/8645580/207381263-0bc096f6-c5aa-4700-b164-6697def9e5cf.jpg)
