### ISSUE TITLE
Wiki example for timer announce requires time and date integration

### ISSUE THREAD

**Issue by rlippmann** [custom-components/alexa_media_player#1800]
**IMPORTANT:  Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

The timer announce trigger described in the wiki will always fail if time and date integration isn’t installed

**To Reproduce**

Copy and paste the trigger.  It will never be executed because sensor.time isn’t defined without the integration.

**Expected behavior**

Trigger should run

**Screenshots**

**System details**
 - Home-assistant (version): 
 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : 

HA 2022.12.1
**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). 

**Additional context**

This is probably just a documentation bug, but I’ve spent hours trying to debug it.  The remainder computation throws an exception if date and time integration aren’t set up.

I’ve tried replacing the state.time statement with now() but I don’t think that’s intended functionality. 

The timing computations could probably also be simplified a bit since you can subtract datetimes.

**Comment by alandtse** [comment]
Is the issue that the documentation should make it clear that the time and date integration are required? You can edit the wiki as appropriate. This doesn't seem to be a bug report related to the component.

**Comment by alandtse** [comment]
It'd also be good if you linked what you're looking at. I don't know which automation you're talking about as I don't maintain that. I'll leave this open in case someone wants to update the wiki with the requirement.

**Comment by rlippmann** [comment]
Oh, I thought this was like changing core where you needed to do PRs to change the documentation. 

The section in question is:

https://github.com/custom-components/alexa_media_player/wiki/Examples%3A-Automation#time-remaining-announcements-for-timers

It doesn’t really work for multiple timers.  I’ve been trying to debug/modify it, but I’m not a Jinja warrior so it’s a lot of trial and error.

I spent hours wondering why it wouldn’t even trigger until I figured out that the date/time sensor was required.

**Comment by alandtse** [comment]
Ahh ok. No, we're much less formal. I see you added the note so I'll close this. Thanks!

**Comment by rlippmann** [comment]
You’re welcome.

I’d like to fix this for multiple timers and maybe all devices.

Is sorted_active appears to be sorted based upon time created.  Is this the case?

**Comment by alandtse** [comment]
It's sorted by whatever key is relevant for the timer. https://github.com/custom-components/alexa_media_player/blob/dev/custom_components/alexa_media/sensor.py#L271

**Comment by rlippmann** [comment]
Umm, that’s pretty vague. 

It looks like it’s sorting by time remaining.

**Comment by alandtse** [comment]
I wrote this years ago. Each notification has a different type of property so it's sorted based on whatever property is relevant for that notification. I don't remember off the top of my head so I provided a link to where the relevant code is so you could look too.
