### ISSUE TITLE
Plug-in delays start-up of Home Assistant if an Alexa is unreachable.

### ISSUE THREAD

**Issue by codyc1515** [custom-components/alexa_media_player#1802]
**Describe the bug**
The plug-in can take a long time to load if one of the Alexa's is unavailable, for example due to being powered off. This delays start-up of Home Assistant considerably.

**To Reproduce**
1. Power off the Alexa
2. Restart Home Assistant

Observe that the start-up is delayed by the Alexa Media plug-in.

**Expected behavior**
Timeout threshold should be reduced drastically, perhaps also increasinging the number of retrys before timing out also.

**Screenshots**
TBC

**System details**
 - Home-assistant (version): 2023.1.0.dev20221222
 - alexa_media  (version from `const.py` or HA startup): TBC
 - alexapy (version from `pip show alexapy` or HA startup): TBC
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). Yes

**Logs**
TBC

**Additional context**
TBC

**Comment by codyc1515** [comment]
There may be enough information here to work on. But if not, I will get some more information from the template soon.

**Comment by alandtse** [comment]
Individual devices should not impact the load state of the integration. It is communicating directly with Amazon's servers which will return information based on what Amazon knows (and doesn't wait for local responses). You'll need to provide logs showing the issue.

**Comment by codyc1515** [comment]
This wasn’t fixed.
