### ISSUE TITLE
Sorry i am having trouble accessing your simon says now skill right now

### ISSUE THREAD

**Issue by sanderlv** [custom-components/alexa_media_player#1806]
**IMPORTANT:  Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**
It always used to work until a few weeks/months back. The MP3 files were fine and worked well. I now also tried to host them a jovo:
https://v3.jovo.tech/audio/3kaBnLzu-dog1-14s.mp3

Whatever I try I get Alexa to say:
Sorry i am having trouble accessing your simon says now skill right now

TTS does work well.

**To Reproduce**

1. Go to developer tools
2. Click on services
3. select service notify.alexa_media_office
4. message: <audio src='https://v3.jovo.tech/audio/3kaBnLzu-dog1-14s.mp3'/
5. click call service

**Expected behavior**
Alexa to play the mp3

**Screenshots**

**System details**
 - Home-assistant (version): Home Assistant 2022.12.8
 - alexa_media  (version from `const.py` or HA startup): v4.4.0
 - alexapy (version from `pip show alexapy` or HA startup): latest?
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : 

YES, eveything else works.

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). 

**Additional context**
none, it used to work well

**Comment by sanderlv** [comment]
I have found the error... It seems the issue is my letsencrypt certificate(s).

this does work as it does not use letsencrypt... (via nginx proxy manager)
https://automatiseer.eu/audio/kleine-wasjes-grote-wasjes.mp3

**Comment by alandtse** [comment]
This isn't an issue we can solve since it's the Amazon API.
