### ISSUE TITLE
offer the play_media service on each device

### ISSUE THREAD

**Issue by phirestalker** [custom-components/alexa_media_player#1807]
**Describe the solution you'd like**
I am trying to use my echo devices with the [Music Assistant homeassistant plugin](https://github.com/music-assistant/hass-music-assistant#usage-and-notes).
The link mentions that it detects media_play devices that offer the play_media service. I am not sure of the details of the implementation.

**Comment by alandtse** [comment]
Alexa does not allow playing of non-cloud media.  You would need to install a skill.

**Comment by phirestalker** [comment]
Does that mean it will not stream a media file from a link? Someone was able to use your skill to play an mp3 file from the web, but it was through the tts function. https://github.com/music-assistant/hass-music-assistant/discussions/431#discussioncomment-2978377
My hass instance has a valid certificate and is accessible through a public domain name if that makes a difference.

**Comment by alandtse** [comment]
Yes you can hack tts for certain links but HA does not have a media player that only streams links. If someone can figure out a way to do it with a PR, I'll consider it.
