### ISSUE TITLE
Add support for Echo Dot 5th Generation temperature sensor

### ISSUE THREAD

**Issue by nevado** [custom-components/alexa_media_player#1809]
Is it possible to add support for the new Echo Dot 5th generation temperature sensor?

**Comment by RobinBeismann** [comment]
In my eyes the Echo 4th Gen also have a temperature sensor, at least my 4th Gen Echos do show a temperature. I recall someone on the Iobroker Forum saying that this information is not exposed in the API through.

**Comment by nevado** [comment]
Apologies just found it is already supported, I hadn't enabled "Include devices connected via Echo" option in the integration configuration.
