### ISSUE TITLE
Invoke an alexa skill intent, not only a skill launch

### ISSUE THREAD

**Issue by malorezzanzo64** [custom-components/alexa_media_player#1810]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**
I currently use an alexa custom skill for actionable notification and another one for intents. I'd like to use only one.
The problem with this is that alexa skill intents have to be very generic in order to use it with Alexa Actions. This causes a lot of utterances conflicts.

**Describe the solution you'd like**
If it would be possible to directly launch an intent one custom alexa skill could handle both request made by voice interaction and requests made by Alexa Media Player without utterance conflicts.
The official Alexa REST API allows to do it, but as far as I know this custom component uses an unofficial API and I don't know if this unofficial API allows it.

**Describe alternatives you've considered**

**Additional context**

**Comment by alandtse** [comment]
I don't understand the request. Please rephrase or provide a simple example.

**Comment by malorezzanzo64** [comment]
Alexa media player allows to [trigger a skill](https://github.com/custom-components/alexa_media_player/wiki#triggering-a-skill). This can be used to launch [alexa actions custom skill](https://github.com/keatontaylor/alexa-actions).
[This other custom skill](https://gist.github.com/lpomfrey/97381cf4316553b03622c665ae3a47da) allows to trigger home assistant intents from the custom skill intents (instead of sending events like alexa actions does).
I'm trying to create a skill that merges the functionalities of these two custom skills, and it would be simpler to do it if it were possible to directly invoke an intent via alexa media player.

**Comment by alandtse** [comment]
Can the app do this?

**Comment by malorezzanzo64** [comment]
I don't understand. Which app? Do what?
