### ISSUE TITLE
Unable to configure Alexa Media Player

### ISSUE THREAD

**Issue by shak-il** [custom-components/alexa_media_player#1815]
I am running HA on a Raspberry Pi 2 with the latest version of HACS and HA. I am able to download the custom component from HACS and when I try to add the integration it allows me to enter my details as well as the 2FA. However once the authentication is complete it hangs at loading next step for Alexa Media Player configuration, then eventually says ERROR.

The logs show:

Logger: aiohttp.server
Source: runner.py:120
First occurred: 13:47:08 (1 occurrences)
Last logged: 13:47:08

Error handling request

**Comment by Ric199021** [comment]
I have this problem too, I've uninstall it then install it again without any success. It's not working anymore.

**Comment by mattes1007** [comment]
same to me. No Chance to install the plugin. Always end with "error"
