### ISSUE TITLE
Expose Echo temperature sensor data to Home Assistant

### ISSUE THREAD

**Issue by ColinSainsbury** [custom-components/alexa_media_player#1816]
Echo Dot (with clock) has temperature sensor which is exposed in the iOS Alexa App. Surfacing this data would provide an opportunity to create additional triggers/automations.
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**
Having paid for an Echo Dot (with clock) which includes a temperature sensor, I am loathe to buy a WIFI temperature sensor to capture/trigger in that room.

**Describe the solution you'd like**
Output of temperature sensor data as an entity that can be used to construct graphs for recording, triggers for automations etc.

**Describe alternatives you've considered**
Alternative is to buy a dedicated temperature sensor.

**Additional context**
Thanks for all your efforts.

**Comment by decompil3d** [comment]
This is supported already. See https://github.com/custom-components/alexa_media_player/wiki#discover-and-control-devices-connected-to-an-echo

**Comment by alandtse** [comment]
Thanks @decompil3d

**Comment by ColinSainsbury** [comment]
I believe that I have followed these instructions but I still do not see a thermometer or any other entity besides the standard media player.
![Alexa thermometer](https://user-images.githubusercontent.com/33755825/211156265-b4ababf2-5924-4d4c-b926-2232eac18500.png)
![alexa therm 2](https://user-images.githubusercontent.com/33755825/211156300-2ac6be20-60e1-4bc6-8ab4-a61adceb8adc.png)

**Comment by paolapersico1** [comment]
> I believe that I have followed these instructions but I still do not see a thermometer or any other entity besides the standard media player. ![Alexa thermometer](https://user-images.githubusercontent.com/33755825/211156265-b4ababf2-5924-4d4c-b926-2232eac18500.png) ![alexa therm 2](https://user-images.githubusercontent.com/33755825/211156300-2ac6be20-60e1-4bc6-8ab4-a61adceb8adc.png)

I had the same issue and I solved it this way:
1) I deleted the alexa_media.email.pickle file in config/.storage/
2) I removed the Alexa Media Player integration
3) I restarted HassOS
4) I repeated the procedure to add the Alexa Media Player but this time I left blank the include devices field in the integration configuration box

I can't guarantee this works for everybody but it's worth a try.
