### ISSUE TITLE
HA submission

### ISSUE THREAD

**Issue by starkillerOG** [custom-components/alexa_media_player#182]
@keatontaylor and @alandtse thank you so much for the greath work on this component.
It is awesom!
I mainly use it for the TTS feature and am really happy with it.

I was wondering when this component will be submitted as an official HomeAssistant component.
I have followed the "Alexa Media Player HA submission"project, but it has not been active for a while and it seems like the complete "to do" list has been finished.

Could you indicate a timeline for when (and if) the component will be submitted to HA?

**Comment by alandtse** [comment]
Submitting to HA actually will be a time consuming process and I think we're both wary of it. We're already aware that they think we're using the core HA functions incorrectly (see #171) and probably need to fix that before we could submit.

I think we'll probably do a 1.3 revision further cleaning stuff up before we consider the HA submission. Of course, if someone wants to help with the clean up and submission I don't think either of us would be opposed.

I plan to leave this issue open for a little while. It's not really a bug per se and I'd like to see what others have to say. I will probably close it after say a month of no action.

**Comment by starkillerOG** [comment]
@alandtse Thank you very much for the information!
I understand that those kinds of issues need to be resolved first.

Although I think making a Pull Request in HA would not hurt, since you would then get a revieuw telling at wich points you would need to improve before they merge it.
Besides often components are not fully complete when they are first introduced as an official component.
I have been following the adition of Heos to HA over the last month, and when it was first introduced their were a lot of functions missing and still a lot of errors beeing created. But since then their have been 15 aditional PR's fixing all the issues and adding features. Now it is a very nice component.

**Comment by starkillerOG** [comment]
@alandtse now that version 1.3 is released, is there an update towards the HA submission?

**Comment by alandtse** [comment]
Given the fact we have HACS, I'm not too inclined to submit this officially given the heavy lift that'd be and the fact we have limited time. I'd prefer to add features/fix bugs instead of wrestling with HA submission requirements.

**Comment by alandtse** [comment]
As a note, [HA's policy](https://github.com/home-assistant/architecture/blob/master/adr/0004-webscraping.md) will not accept AMP as a standard component because we are performing "webscraping". We are closing this issue for now.
