### ISSUE TITLE
Samsung familyhub available in HA but doesn't allow for TTS..even thought it participates in everywhere

### ISSUE THREAD

**Issue by atv2016** [custom-components/alexa_media_player#1821]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**
So our familyhub fridge got an alexa update a while ago. It even participates in the everywhere group somehow. I also see it on the HA dashboard as another regular alexa.

But i can’t seem to send it a message…:frowning: That would have been so nice :slight_smile:

I tried turning it on as well with media player turn on. no dice.

Anyone have any success with this ? Maybe i should ping it upfront ? Shame the samsung familyhub integration is not working anymore.

**Describe the solution you'd like**
Able to send it TTS

**Describe alternatives you've considered**

**Additional context**

**Comment by alandtse** [comment]
Can you send a TTS directly to it using the Alexa app? Third-party integrations are pretty random on what works or doesn't work.

**Comment by atv2016** [comment]
I actually got it to work with tts. Must have been a typo. Thanks, this can be closed.
________________________________
