### ISSUE TITLE
4.5.0 No data for alarm clock and reminder

### ISSUE THREAD

**Issue by herveaurel** [custom-components/alexa_media_player#1823]
Hello, since the January 12, 4.5.0 update, there is no data for alarm clocks and reminders (unknown or unavailable), but the music no problem. 

Thanks

**Comment by OwenBerg79** [comment]
Finding the same with next timer too.
It may be of note that I didn't upgrade to 4.5 until I'd noticed it wasn't working this morning.

Seems the last timer that reported for me was at just after 07:05 GMT

**Comment by Puddingpanzer** [comment]
Same here

**Comment by GRClark** [comment]
Same here.  Next timer, alarm and reminder all show as unavailable on all devices.

**Comment by isibizi** [comment]
Same here, 4.4.0 working.

**Comment by alandtse** [comment]
Please do not ignore the template requirement.

**Comment by isibizi** [comment]
> Please do not ignore the template requirement.

Which template requirement do you mean?

**Comment by OwenBerg79** [comment]
> > Please do not ignore the template requirement.
> 
> Which template requirement do you mean?

After looking around for HA template clues, I realised the request was for following the bug template - I've resubmitted with the template (just gathering logs)
