### ISSUE TITLE
Indoor Air Quality Monitor sensor - wrong sensors entities behavior

### ISSUE THREAD

**Issue by KC-inDomus** [custom-components/alexa_media_player#1827]
**Describe the bug**

Sensors:
- indoor air quality
- voc

even if they're number sensors, cannot generate charts on HA dashboard 

**To Reproduce**

open one sensor and see how integer number are not placed as graphical chart

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/52242036/212412686-6a60ab51-7a47-4bc2-8820-345531526fca.jpeg)

**System details**

- Home-assistant (version): 2023.1.4
- alexa_media (version from `const.py` or HA startup): 4.5.0

**Comment by alandtse** [comment]
I don't have one of these sensors so can't test it. But there's probably a [sensor setting (like device_class)](https://developers.home-assistant.io/docs/core/entity/sensor/) that is off which results in a non number graph for history.

**Comment by KC-inDomus** [comment]
Ok. Btw the other sensors are ok, if this could help.
