### ISSUE TITLE
No data update on Indoor Air Quality Sensor's sensors

### ISSUE THREAD

**Issue by KC-inDomus** [custom-components/alexa_media_player#1833]
Sorry @alandtse for bothering you once again, only trying help you debugging this new Indoor Air Quality Sensor integration - for which we all thank you.

**Describe the bug**

After 4.5.2 (which solved [unavalability problem](https://github.com/custom-components/alexa_media_player/issues/1830)) data polling happends only at startup. No new data seems to be collected while Home Assistant is running, while Alexa app reports some (the only way is to restart the component). Was working fine with 4.5.0.

**System details**

- Home-assistant (version):2023.4.1
- alexa_media (version from `const.py` or HA startup):  4.5.2

**Logs**
Checked, no warnings or errors come up.

**Comment by alandtse** [comment]
Thanks. This was caused by https://github.com/custom-components/alexa_media_player/commit/6017a62e4965d2dc5678b37fdaf61189049906e7#. Probably need to add an async_update function or figure out what HA uses now given the new default structures we switched to.
