### ISSUE TITLE
Local temperature not updating

### ISSUE THREAD

**Issue by Dixey-coder** [custom-components/alexa_media_player#1834]
Initial report is accurate.  Manual reload of alexa integration updates.  Does not update automatically.  Echo dot ver 5.

**Comment by alandtse** [comment]
Thanks. This was caused by https://github.com/custom-components/alexa_media_player/commit/6017a62e4965d2dc5678b37fdaf61189049906e7#. Probably need to add an async_update function or figure out what HA uses now given the new default structures we switched to.
