### ISSUE TITLE
Make Air Quality Monitor AQI & VOC numeric

### ISSUE THREAD

**Issue by nanobra1n** [custom-components/alexa_media_player#1836]
The Air Quality Monitor VOC and AQI sensors show up as text sensors instead numeric in HA because they have no `unit_of_measurement`.  From what little I  read, in this case `state_class` should be defined for them, allowing line graphs and statistics on the HA frontend.

**Comment by alandtse** [comment]
I don't know what those sensors from those abbreviations as I do not have those devices. Can you please identify what unit_of_measurement exactly each should be or submit a PR?

The specific code is:
https://github.com/custom-components/alexa_media_player/blob/dev/custom_components/alexa_media/sensor.py#L297-L299
and 
https://github.com/custom-components/alexa_media_player/blob/dev/custom_components/alexa_media/const.py#L122-L126.

HA docs on appropriate type. https://www.home-assistant.io/integrations/sensor/

**Comment by nanobra1n** [comment]
AQI = Air Quality Index
VOC= Volatile Organic Compounds

Both are unitless sensors, so them not having `unit_of_measurements` is valid. And since`state_class` seems to be set in   https://github.com/custom-components/alexa_media_player/blob/f55b39810485ed9df16eafec454f176a2191fb73/custom_components/alexa_media/sensor.py#L293 I am at a loss what the solution could be. 

My workaround is to set up template sensors in HA defining the appropriate `device_class` and `state_class` for these two

**Comment by nanobra1n** [comment]
Oh, never mind. I just realized that you just added this in in 4.5.2 and I am still on 4.5.0. Sorry for the noise

**Comment by alandtse** [comment]
There's a bug right now where it's not updating, but I should be able to fix the updates shortly. However, I think the issue is we're not using the right device classes yet.
https://github.com/custom-components/alexa_media_player/blob/f55b39810485ed9df16eafec454f176a2191fb73/custom_components/alexa_media/sensor.py#L292

I think we'll need to create a conversion table between whatever the sensor name is from Alexa to the HA recognized items.

**Comment by nanobra1n** [comment]
Here are my created sensors (minus temp & humidity) and what I think the appropriate  [device_class](https://www.home-assistant.io/integrations/sensor/#device-class) is. 
```
Sensor ending in                                 device_class

air_quality_monitor_particulate_matter           pm25
air_quality_monitor_carbon_monoxide              carbon_monoxide
air_quality_monitor_indoor_air_quality           aqi
air_quality_monitor_volatile_organic_compounds   volatile_organic_compounds
```
