### ISSUE TITLE
Timer to have state on/off 

### ISSUE THREAD

**Issue by oneseventhree** [custom-components/alexa_media_player#1840]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**
Yes and No. The new update changed the "off" state of the timer entity from "unavailable" to "unknown" which  means I have to change my lovelace(that doesnt accept attritubes in condtions card) to match.

**Describe the solution you'd like**
If timer is running state is 'on'. If timer is not running state is 'off'.
Replace state attritube 'status' for 'start_time' or similar?

**Describe alternatives you've considered**
N/A

**Additional context**
As always thanks for a great integration!

**Comment by alandtse** [comment]
The migration from timers to HA's new `SensorDeviceClass.TIMESTAMP` made it so Unavailable was no longer a valid response. I'll double check if there's any other option but we may be stuck.
