### ISSUE TITLE
Connection Issue / Fails to reauthenticate

### ISSUE THREAD

**Issue by haywiremk** [custom-components/alexa_media_player#1843]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

First the integration was looping on Retrying setup: Connection Error during login  

Saw new HACS version and updated to v4.5.3

So I deleted and re-added think auth issue.
Now I get

https://[REMOVED].ui.nabu.casa/auth/alexamedia/proxy?config_flow_id=[REMOVED]&callback_url=https://[REMOVED]ui.nabu.casa/auth/alexamedia/callback?flow_id%3D[REMOVED]

Connection Error! Please try refreshing. If this persists, please report this error to here:
[Errno -2] Name does not resolve

I removed what looked like identifiers in the [] sections.

In logs I see

2023-01-19 15:44:30.355 WARNING (MainThread) [alexapy.helpers] alexalogin.login((<alexapy.alexalogin.AlexaLogin object at 0xffff6a4a9570>,), {'cookies': {'session-id': <Morsel: session-id=134-6216317-5854068>, 'session-id-time': <Morsel: session-id-time=2304880743l>, 'lc-main': <Morsel: lc-main=en_US>, 'ubid-main': <Morsel: ubid-main=130-0508603-1063865>, 'session-token': <Morsel: session-token="[REMOVED]">, 'csrf': <Morsel: csrf=1140516181>, 'x-main': <Morsel: x-main="W1UHSIwiiAS5kRaDXnFIp1cw@iNDW7Ks">, 'at-main': <Morsel: at-main[REMOVED]>, 'sess-at-main': <Morsel:[REMOVED]">}}): A connection error occured: An exception of type ClientConnectorError occurred. Arguments:
(ConnectionKey(host='api.amazon.com', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=104579454608667430), gaierror(-2, 'Name does not resolve'))

But if I do a nslookup from my local network I get
Non-authoritative answer:
Name:    api.amazon.com
Address:  72.21.207.143

So maybe this is on the nabu casa side?

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details**

- Home-assistant (version): 2023.1.5
- alexa_media (version from `const.py` or HA startup): v4.5.3
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by alandtse** [comment]
The error is saying the component cannot connect to the amazon api. It shouldn't be related to Nabucasa. The logs provide info on what it's trying to connect to. You should confirm it can connect to those urls from your HA machine.

**Comment by haywiremk** [comment]
Today the setup worked as randomly as it stopped.  After much HA debug I had checked from the HA box with nslookup and resolved OK.  The issue was that even the external address below was reporting and error.  Not sure how nabu casa routes back into the device.  Anyhow will close since now working.

https://[REMOVED].ui.nabu.casa/auth/alexamedia/proxy?config_flow_id=[REMOVED]&callback_url=https://[REMOVED]ui.nabu.casa/auth/alexamedia/callback?flow_id%3D[REMOVED]

Connection Error! Please try refreshing. If this persists, please report this error to here:
[Errno -2] Name does not resolve
