### ISSUE TITLE
Add ability to send messages to Alexa account

### ISSUE THREAD

**Issue by wolfwander** [custom-components/alexa_media_player#1850]
It would be a good idea to have the ability to send text messages to an Alexa account using the Communication feature.
When you arrive at home and see the yellow ring blinking in your Echo devices, you can ask "what are my notifications" and it tells all text messages your automations left in your inbox.

**Comment by alandtse** [comment]
Is this doable via the current Alexa app?

**Comment by wolfwander** [comment]
> Is this doable via the current Alexa app?

Yes, it is!
In the Alexa app, you can enter in Communication tab, select Messages button and then select the contact you wish to send the message.

**Comment by wolfwander** [comment]
Hi! I haven't found which API could be called for this functionality.
Could anyone help?
