### ISSUE TITLE
Setting for Alarm-Clock

### ISSUE THREAD

**Issue by mericon** [custom-components/alexa_media_player#1852]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**
Please add the function to set the alarm clock to a specific time.

**Comment by alandtse** [comment]
Does HA actually have a clock feature? If not, just use a custom command. https://github.com/custom-components/alexa_media_player/wiki#run-custom-command
