### ISSUE TITLE
Echo Dot Do not disturb (DND) switches not showing proper state -- similar to closed issue #950

### ISSUE THREAD

**Issue by neil1111** [custom-components/alexa_media_player#1853]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

see this: https://github.com/custom-components/alexa_media_player/issues/950#issue-709696152

**To Reproduce**

Hi. I think we may need to re-open this issue. I'm running 2023.2.0 on an RPi/HAOS.  The Do Not Disturb button on our Echo Dot is not registering on the entity in HA.  Similarly, changing the entity's setting in HA doesn't affect the Dot. I am able to toggle the switch directly in HA, but that also does not affect the Dot.  This is a new use-case for me, so I can't say if it worked in a prior version of HA. I do have a backup from before updating and could check that if desired via a restore.  Thanks, please let me know.
**Expected behavior**

**Screenshots**

**System details**

- Home-assistant (version): 2023.2.0
- alexa_media :  4.6.0
- alexapy (version from `pip show alexapy` or HA startup): -- sorry, not sure where to look for this?  Please advise if needed. Thanks.
- Amazon 2FA is enabled

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

Which Logs are needed? I enabled logging on the Alexa integration.

**Additional context**
As noted above. Thank you.

**Comment by alandtse** [comment]
Logs of when you issue a DND switch.

**Comment by neil1111** [comment]
Thanks, here is the log exerpt. The entity_id=switch.neil_s_2nd_echo_dot_do_not_disturb_switch   and  "friendly_name":"Master Bath Echo Dot"

I noticed that some of the logs mention the DnD switch being disabled, but the following image shows that it is indeed Enabled:
![DnD is Enabled](https://user-images.githubusercontent.com/28867423/216825036-ccd765aa-c81d-4950-8af8-8c56b176e3a4.png)

Time stamps 2023-02-05 08:43:27.569 and 2023-02-05 08:43:27.851 mention the entity.

Attached is the log.  Thank you!

[Neil Log Cleaned v2.txt](https://github.com/custom-components/alexa_media_player/files/10611361/Neil.Log.Cleaned.v2.txt)

**Comment by alandtse** [comment]
You did enable debug logging right? You can enable it in the Integrations UI by using the hamburger button (in my case it's enabled already so the option says disable).
![image](https://user-images.githubusercontent.com/7086117/217744822-517f9b3c-d373-4f4e-9e94-821368945a6b.png)

 I'm not seeing any calls from alexapy. It should look like this when triggering the switch:
```
2023-02-08 23:19:13.307 DEBUG (MainThread) [alexapy.alexaapi] a******e@g*******m: Setting DND state: True data: {"deviceSerialNumber": "SNIP", "deviceType": "A3S5BH2HU6VAYF", "enabled": true}
2023-02-08 23:19:13.625 DEBUG (MainThread) [alexapy.alexaapi] a******e@g*******m: PUT: https://alexa.amazon.com/api/dnd/status returned 200:OK:application/json
2023-02-08 23:19:13.626 DEBUG (MainThread) [alexapy.alexaapi] a******e@g*******m: Success: True Response: {'deviceSerialNumber': 'SNIP', 'deviceType': 'A3S5BH2HU6VAYF', 'enabled': True}

```

**Comment by neil1111** [comment]
I thought I had, but perhaps not. So, I just enabled it.

The log page shows this:
Logger: homeassistant.helpers.service
Source: helpers/service.py:309
First occurred: 12:47:26 PM (6 occurrences)
Last logged: 6:38:50 PM

Unable to find referenced entities script.null or it is/they are currently not available

**Comment by alandtse** [comment]
Sorry, did you actually try to toggle the DND switches with this log? Please identify the timestamps. I'm not seeing any attempts in the log to toggle like I showed you earlier.

Is the issue you're toggling outside of HA? In that case, until the next poll (default 10 minutes) the component won't know because it's not aware any DND state has been changed. We have to balance the polling interval so we don't get banned by Amazon.  While some polls are constant, other polls will increase with the total number of echo devices available so we try to be very conservative.

**Comment by neil1111** [comment]
Ahhh!  I did not know that the physical DND button on the DOT only gets polled every 10 minutes.  I thought it would be "caught" by HA promptly upon being pressed, in the same manner as asking Alexa to do something is also caught.  My use case was to use the DND button like any other Zigbee or Zwave button -- to use it to trigger an automation.  Unless there is a way for pressing the physical DND button to trigger an intent that could be immediately caught by HA, I'll look for another solution for the current use case.

However, I have another use case where ~every 10 minutes would work well. Therefore, let's still confirm if it is working or not, please. To your questions -- I indeed pressed the physical DND button 4 times during the period of the log that I provided.  I searched through the logs overall for the example calls you listed: 

> 2023-02-08 23:19:13.307 DEBUG (MainThread) [alexapy.alexaapi] a******e@g*******m: Setting DND state: True data: {"deviceSerialNumber": "SNIP", "deviceType": "A3S5BH2HU6VAYF", "enabled": true}
> 2023-02-08 23:19:13.625 DEBUG (MainThread) [alexapy.alexaapi] a******e@g*******m: PUT: https://alexa.amazon.com/api/dnd/status returned 200:OK:application/json
> 2023-02-08 23:19:13.626 DEBUG (MainThread) [alexapy.alexaapi] a******e@g*******m: Success: True Response: {'deviceSerialNumber': 'SNIP', 'deviceType': 'A3S5BH2HU6VAYF', 'enabled': True}

However, I found no instance of "Setting DND" in the logs. The only lines with "DND" in them look like this:
190 DEBUG (MainThread) [alexapy.alexaapi] n****@g*******m: static GET: https://alexa.amazon.com/api/dnd/device-status-list returned 200:OK:application/json

Therefore, I wonder if it the alexaypy is properly working.  What do you advise, please? Thanks again.

**Comment by alandtse** [comment]
If you saw nothing in the logs when you hit the physical button, then we can't detect it. Also, I do not know if the physical DND switches are even linked to the software DND switch. What does the Amazon Alexa app say about the state?
