### ISSUE TITLE
Log Swamping

### ISSUE THREAD

**Issue by tre4b** [custom-components/alexa_media_player#1860]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

When I try and use my log to debug issues with other elements of home assistant I find it to be swamped with entries from Media Player,  such that it makes it really difficult to use the log effectively.   I checked to see if "Enable debug logging" was switched on but it is not.   When I look in the log however I see the word DEBUG next to a number of the items which suggests the integration does think debugging should be on.   I have tried turning debugging on and off again to see if that reset it but no effect.

I believe that the integration may be stuck in Debug logging mode despite the current setting of the integration

Go to the log and view,  see below for the output.

When Enble Debugging is not on I would expect to see a minor number of Alexa media player related log entries and no JSON output of all the elements.

I have added a copy of the log so that the problem can be seen and a screenshot of the integration menu that shows Enable Debug logging is not switched on.

Home Assistant 2023.2.5
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest

Alexa media version 4.6.0

Alexa media itself is working perfectly in all other aspects.  It is just trying to stop the additional log entries that I am interested in achieving.   Alexa is using 2FA and the log is included below.

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

![menu](https://user-images.githubusercontent.com/37894577/219602195-75ed1f68-595d-419f-b659-869e51979ea7.png)
[home-assistant_2023-02-17T09-03-16.684Z.log](https://github.com/custom-components/alexa_media_player/files/10765103/home-assistant_2023-02-17T09-03-16.684Z.log)

**Comment by alandtse** [comment]
Check your configuration.yaml `logger` setting. This is a configuration error and not related to the component. Please note that in your screenshot, it shows that at least within the integration panel you have it disabled. But that doesn't reflect whatever you may have in configuration.yaml.
