### ISSUE TITLE
volume_level attribute is missing after HA start/integration reload

### ISSUE THREAD

**Issue by klatka** [custom-components/alexa_media_player#1861]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Same to #1756 
"After HA restart, looking at my echo state, and the volume_level prop is missing.
so its not possible to know what is the current level.
The UI component show the slider at 0 positionin this case.

It will appear later in the state, only if i send a tts with volume"

**To Reproduce**

1. Setup Alexa Media Player
2. Restart HA/Reload integration
3. See error

**Expected behavior**

`volume_level` attribute is at least defined and in best case set to current volume level

**Screenshots**

**System details**

- Home-assistant (version): 2023.2.5
- alexa_media (version from `const.py` or HA startup): 4.6.0
- alexapy (version from `pip show alexapy` or HA startup): 1.26.4
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : y

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by alandtse** [comment]
Volume level only becomes available if the media player is playing supported music or receives some action that sets it. Before that point, the data is not available to the component, unfortunately. That's an amazon issue.
