### ISSUE TITLE
Next Alarm/Timer/Reminder Not Updating

### ISSUE THREAD

**Issue by GRClark** [custom-components/alexa_media_player#1862]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

Searched but didn’t find anything open/applicable. 

**Describe the bug**

**To Reproduce**

1. Set timers and alarms on Alexa devices
2. Checked states for each entity under developer tools.  
3. As well tried automations triggered by such and they’re not working. 

**Expected behavior**

**Screenshots**

entity should be updated, here is timer with no update.  Automation should also trigger and not happening. 

![](https://i.imgur.com/RfyK3ny.png)

**System details**

- Home-assistant (version): 2023.2.5
- alexa_media (version from `const.py` or HA startup): 4.6.0
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). :  Yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

Either no log output related or unsure where to obtain. Not showing under system / logs and debug logging is enabled. 

**Additional context**

**Comment by disconn3ct** [comment]
What solution did you find? I have to reload the integration at least once a week to stop it saying "next alarm: yesterday"
