### ISSUE TITLE
Why do I get these errors?

### ISSUE THREAD

**Issue by Pirol62** [custom-components/alexa_media_player#1865]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

I receive error log entries from alexa which have issues with a device and its sensors, which is deactivated on the alexa platform. This device is a tablet functioning as alarm clock running fully kiosk. Sometimes it looses connection to wlan. The tablet solves this itself by simply restarting wlan via tasker

**Expected behavior**

no error logs

**Screenshots**

**System details**

- Home-assistant (version): 2023.2.5
- alexa_media (version from `const.py` or HA startup): newest
- alexapy (version from `pip show alexapy` or HA startup): newest
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : y

**Logs**
````
Logger: homeassistant.components.alexa.capabilities
Source: components/alexa/capabilities.py:1624
Integration: Amazon Alexa (documentation, issues)
First occurred: 04:44:26 (5 occurrences)
Last logged: 12:59:38

Unexpected error getting Alexa.RangeController.rangeValue property from <state number.lenovo_tab_m8_screensaver_brightness=; min=0, max=255, step=1, mode=auto, friendly_name=Lenovo Tab M8 Screensaver Brightness @ 2023-03-01T04:44:26.278027+01:00>
Unexpected error getting Alexa.RangeController.rangeValue property from <state number.lenovo_tab_m8_screensaver_brightness=; min=0, max=255, step=1, mode=auto, friendly_name=Lenovo Tab M8 Screensaver Brightness @ 2023-03-01T09:46:25.610546+01:00>
Unexpected error getting Alexa.RangeController.rangeValue property from <state number.lenovo_tab_m8_screensaver_brightness=; min=0, max=255, step=1, mode=auto, friendly_name=Lenovo Tab M8 Screensaver Brightness @ 2023-03-01T10:00:48.280292+01:00>
Unexpected error getting Alexa.RangeController.rangeValue property from <state number.lenovo_tab_m8_screensaver_brightness=; min=0, max=255, step=1, mode=auto, friendly_name=Lenovo Tab M8 Screensaver Brightness @ 2023-03-01T12:38:57.554097+01:00>
Unexpected error getting Alexa.RangeController.rangeValue property from <state number.lenovo_tab_m8_screensaver_brightness=; min=0, max=255, step=1, mode=auto, friendly_name=Lenovo Tab M8 Screensaver Brightness @ 2023-03-01T12:59:38.613398+01:00>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/alexa/capabilities.py", line 263, in serialize_properties
    prop_value = self.get_property(prop_name)
  File "/usr/src/homeassistant/homeassistant/components/alexa/capabilities.py", line 1624, in get_property
    return float(self.entity.state)
ValueError: could not convert string to float: ''
````
**Additional context**

**Comment by alandtse** [comment]
This isn't related to this custom component. You need to report to HA for their component.
