### ISSUE TITLE
Warning"exceed maximum size of ... bytes"

### ISSUE THREAD

**Issue by ChristophCaina** [custom-components/alexa_media_player#1867]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Since the release of HomeAssistant 2023.03 I am getting the following warning in the logs.
It seems, that the echo_****_next_alarm does exceed a maximum size for writing information into the Database.

```
Logger: homeassistant.components.recorder.db_schema
Source: components/recorder/db_schema.py:491
Integration: Recorder (documentation, issues)
First occurred: 09:19:07 (4 occurrences)
Last logged: 10:01:36

State attributes for sensor.echo_schlafzimmer_next_alarm exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details**

- Home-assistant (version):
- alexa_media (version from `const.py` or HA startup):
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). :

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by alandtse** [comment]
So someone should gate the json data behind an option switch. HA actually does the right thing by disabling the logging otherwise the log will fill because of changing attribute data. This is actually safer than what happened in older HAs were the database would fill without warnings.

**Comment by alandtse** [comment]
You can search the comments. People asked for the json. Who knows who's using it.

**Comment by ChristophCaina** [comment]
so...
There was another comment about the same recorder issue with another integration on the HA Forum - with some information on how to exclude such attributes to be stored in the db - that might help... :)

https://github.com/home-assistant/core/blob/3e5e937541dd368f3d70c7557ceaa7a07fd284e2/homeassistant/components/unifiprotect/recorder.py

Unfortunately, I am not so familiar in the whole coding... just did some simple changes on code lines yet...
Else, I would consider doing a PR...

**Comment by alandtse** [comment]
Thanks. That's easy enough.
