### ISSUE TITLE
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by diazdeespada** [custom-components/alexa_media_player#1871]
**Integration Not loaded**

**Screenshots**

![image](https://user-images.githubusercontent.com/58042540/223148215-5b7af9fc-1384-4351-b043-c3081d77920a.png)

**System details**

- Home-assistant (version): Home Assistant 2023.3.1
- alexa_media (version from `const.py` or HA startup): 4.6.0

**Logs**
Home Assistant Core
Error handling request
15:55:48 – (ERROR) Alexa Media Player (custom integration) - message first occurred at 15:55:11 and shows up 2 times
Platform error: sensor - Requirements for ide not found: ['oligo[asyncio]==2.1.1'].
15:41:50 – (ERROR) config.py - message first occurred at 15:38:09 and shows up 3 times
Setup failed for custom integration alexa_media: Requirements for alexa_media not found: ['alexapy==1.26.4'].
15:40:51 – (ERROR) setup.py - message first occurred at 15:38:55 and shows up 3 times

**Comment by TsailunVR** [comment]
I have the same problem with the same version and logs, I have this problem after install last version

**Comment by Jaguaza** [comment]
I have the same problem with the same version and logs.

**Comment by Enriquejll** [comment]
After updating home assistant, I get the same error.
Is it going to be corrected or what request are they going to propose?

**Comment by alandtse** [comment]
Remove and readd the integration or just readd the integration and cancel after it instal alexapy. This is HA not installing custom component dependencies. Nothing I can do about it.

**Comment by TsailunVR** [comment]
> It is not possible to remove the Integration
> 
> ![image](https://user-images.githubusercontent.com/58042540/223362184-cc18dc5b-f0ef-4309-9e89-daceb9cf2ed2.png)
> 
> Press Delete and it doesn't nothing. How can I remove it?

Buenas!Por tus nick doy por hecho que eres Español. Eres cliente de Vodafone? hay un grupo en español en telegram que se llama "Domótica para todos" donde hemos visto que a los que nos fall es porque somos clientes de Vodafone y tenemos "Secure net" activado. Una vez desactivado me ha permitido actualizar y tenerla integracionistas correctamente . Por si te sirve!

**Comment by Enriquejll** [comment]
Sí, gracias por la respuesta.
Ya estoy haciendo el seguimiento.
Genial 👍

**Comment by diazdeespada** [comment]
Gracias, lo pruebo ahora mismo.

**Comment by diazdeespada** [comment]
Correcto, era un problema de Secure.net

Mil gracias

**Comment by Alethio36** [comment]
> Remove and readd the integration or just readd the integration and cancel after it instal alexapy. This is HA not installing custom component dependencies. Nothing I can do about it.

this worked for me. i think i accidently deleted the integration instead of reinstalling, but reinstalling was easy, just had to reset MFA code link. everything is working AFAICT
