### ISSUE TITLE
Sylvania Smart+ Wifi bulbs not supported

### ISSUE THREAD

**Issue by dfOhmslaw** [custom-components/alexa_media_player#1879]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**40 Sylvania Smart+ Wifi bulbs are fully usable and visible on the sylvania and alexa apps, however are not being discovered on home assistant alexa media player integration.**

**To Reproduce**
1) add bulbs to Sylvania Smart WIFI app
2) enable sylvania smart wifi alexa skill
3) confirm all bulbs are integrated as devices into alexa app and full control is possible.
4) update alexa media player integration in HA
5) confirm the bulbs do not show.
6) reinstall the alexa media player integration 
6) confirm the bulbs do not show

**Expected behavior**

40 new devices will appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/12566844/224364102-7d598ad2-28b5-4b8e-857e-610c2e1175c0.png)
![image](https://user-images.githubusercontent.com/12566844/224364280-0a7a7e1c-7eea-4650-b176-6c3700ee5b81.png)
![image](https://user-images.githubusercontent.com/12566844/224364547-b42bc698-433f-4d04-98f6-e1eb6321a924.png)
![image](https://user-images.githubusercontent.com/12566844/224364936-6762d598-3ff9-4796-991a-48a961e8adcb.png)

**Logs**

[home-assistant_alexa_media_2023-03-10T16-06-37.524Z.log](https://github.com/custom-components/alexa_media_player/files/10943832/home-assistant_alexa_media_2023-03-10T16-06-37.524Z.log)

**Comment by iceman73** [comment]
See Limitations Section:
https://github.com/custom-components/alexa_media_player/wiki#limitations

**Comment by alandtse** [comment]
Yup, no one has contributed lights yet.
