### ISSUE TITLE
Cannot call media_player.play with media_content_type: custom

### ISSUE THREAD

**Issue by rlippmann** [custom-components/alexa_media_player#1880]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**
Trying to call service.media_player with media_content_type custom yields error (see screenshot)

**To Reproduce**
See screenshot 

**Expected behavior**
A command should be issued to Alexa 

![IMG_0158](https://user-images.githubusercontent.com/70883373/224425282-670693e9-1513-4392-a45d-0110ae91d181.png)

**System details**

- Home-assistant (version): 2023.2.
- alexa_media (version from `const.py` or HA startup): latest
- alexapy (version from `pip show alexapy` or HA startup): latest
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y) :

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/script.py:409 
First occurred: 3:34:28 PM (1 occurrences) 
Last logged: 3:34:28 PM

websocket_api script: Error executing script. Invalid data for call_service at pos 1: extra keys not allowed @ data['media_content_type']

Also:

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:150 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 3:34:28 PM (1 occurrences) 
Last logged: 3:34:28 PM

[139988529526192] Error handling message: extra keys not allowed @ data['media_content_id']. Got None extra keys not allowed @ data['media_content_type']. Got None (invalid_format) from 73.129.38.53 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15)

**Additional context**

**Comment by alandtse** [comment]
That's not the right service. Use play_media like the wiki tells you. https://github.com/custom-components/alexa_media_player/wiki#examples-1
