### ISSUE TITLE
Unable to setup alexa_media_player through integrations menu

### ISSUE THREAD

**Issue by vivektiwari1986** [custom-components/alexa_media_player#1886]
**I get Unknown error occurred when trying to sign in and setup alexa media player through integrations menu**

**Expected behavior**

I should see a login screen for the alexa login

**Screenshots**
<img width="707" alt="Screen Shot 2023-03-13 at 1 55 25 PM" src="https://user-images.githubusercontent.com/5479627/224833259-7398fa2f-70c9-498e-8085-f4005c6c7e14.png">
![Screen Shot 2023-03-13 at 11 29 21 AM](https://user-images.githubusercontent.com/5479627/224833262-e9af04d5-4ae8-437d-b70f-29b5b2ba132e.png)
![Screen Shot 2023-03-13 at 11 29 28 AM](https://user-images.githubusercontent.com/5479627/224833264-9b415fb3-d439-4bdc-8343-ed831c9e86c7.png)
![Screen Shot 2023-03-13 at 11 30 31 AM](https://user-images.githubusercontent.com/5479627/224833266-b236b593-5058-4f4d-ad34-e33094882e39.png)

**System details**

- Home-assistant (version): 2023.3.3
- alexa_media (version from `const.py` or HA startup): 4.6.2
- alexapy (version from `pip show alexapy` or HA startup): 1.26.5
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : Yes. enabled using indepedent authenticator app

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).
Log setup
```
logger:
  default: info
  logs:
    custom_components.azurecv: debug
    custom_components.alexa_media: debug  
    alexapy: debug
    authcaptureproxy: debug
```

Log output:
```
2023-03-13 14:05:45.374 ERROR (MainThread) [frontend.js.latest.202303090] :0:0 Script error. [this happens when opening the integration]
2023-03-13 14:06:01.392 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Creating new login
2023-03-13 14:06:01.392 DEBUG (MainThread) [custom_components.alexa_media.helpers] v*************6@g*******m: Returning uuid {'uuid': '1************************d', 'index': 0}
2023-03-13 14:06:01.422 DEBUG (MainThread) [alexapy.alexalogin] Login created for v*************6@g*******m - amazon.com
```
Once the error is shown in the UI, there is no corresponding log entry for the error.

**Comment by alandtse** [comment]
Is that the full log? You may have to check the homeassistant.log file in the /config directory. If there's an Unknown error there should be more.
