### ISSUE TITLE
Sonoff Motion Switch Not Showing

### ISSUE THREAD

**Issue by nraimo1** [custom-components/alexa_media_player#1887]
**Describe the bug**
I brought some ZIGBEE sonoff switchs and temp sensors they are all connected via zigbee on my eero devices which acts as a zigbee hub with Alexa.

The temperature sensor is showing on the media player as an entity and working fine.

However, the motion switches are now showing as entities at all,  tried to unpair and repair,  showing on alexa app and working fine just won't come threw to Alexa media player.

1. Put switch into pairing mode
2. Ask Alexa to discover new devices
3. Change name of new device to make it easily findable
4. Check the Alexa media player plugin for entity and see its not showing under OLD or NEW name

**Comment by TusdardCart** [comment]
I have the same issue with Sonoff motion sensors using the Amazon Echo Zigbee hub. Does this mean that other Zigbee devices might not show up too?

**Comment by alandtse** [comment]
It's not implemented yet.
