### ISSUE TITLE
Changed Amazon-Account-Mail, possibility to change it in running config?

### ISSUE THREAD

**Issue by lbrnds** [custom-components/alexa_media_player#1888]
I've changed my Mail-Address of my Amazon Account. Is there a possibility to change the e-Mail of a running Integration or do I need to reconfigure it? I have lots of devices and automations running with the current config of the integration and don't want to reconfigure all the entity-names and device-names.

**Comment by alandtse** [comment]
Entity ids should be consistent. Remove and readd.  Alternatively edit the `/config/.storage/core.config_entries` file. No support if you break it though.
