### ISSUE TITLE
Entities from Alexa not available in HomeAssistant

### ISSUE THREAD

**Issue by snipestyle9410** [custom-components/alexa_media_player#1891]
**Describe the bug**
I got some lights and scenes connected via Alexa. In HomeAssistant i activated the option "Include devices connected via Echo"
Unfortunately those lights and scenes does not become available in HomeAssistant

**To Reproduce**
Just implement some Lights via Alexa. Activate the "Include devices connected via Echo" option in Homeassistant. Lights and scenes will not become visible

**Expected behavior**
Lights and scenes should be available in HomeAssistant

**Screenshots*

**System details**

- Home-assistant (version): 2023.3.6
- alexa_media (version from `const.py` or HA startup): 4.6.2
- alexapy (version from `pip show alexapy` or HA startup): 1.26.5
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n).: No

**Logs**
Currently no errors 

**Additional context**

**Comment by alandtse** [comment]
I don't know what lights you're talking about, but only some are supported. Happy to take a PR to include more.
