### ISSUE TITLE
Deceptive site ahead / detected phishing as result of login

### ISSUE THREAD

**Issue by matbrewer396** [custom-components/alexa_media_player#1892]
When re-login into the integration chrome Safe Browsing feature detected it as phishing. This was using the built-in 2FA method login method.
![image](https://user-images.githubusercontent.com/10374287/227790623-f4808a9f-e9b9-454e-8b3e-dcc1e0ffcdbd.png)

It would also seem I'm not the only one that had this problem:
https://community.home-assistant.io/t/deceptive-site-ahead-after-switching-to-duckdns/385989/19

**Comment by alandtse** [comment]
The login works by proxying your request to HA. This means using your HA to take the Amazon credentials and pass them to Amazon to login. This is by definition phishing but with your HA server. If your safebrowsing is blocking you, you need to confirm it's your server and if so, either ignore the warnings or get Google to safelist you.

**Comment by kozfelipe** [comment]
I had the same issue. Please consider adding a note advising against using the Chrome browser for this authentication process in order to prevent getting into Google's phishing list
