### ISSUE TITLE
Google Speaker version verses Echo Dot version

### ISSUE THREAD

**Issue by michaeldjjohnson** [custom-components/alexa_media_player#1896]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Shows Radio Station and not the Song Title

**To Reproduce**

Play Smooth

**Expected behavior**

Should show the Song Title and not the Radio Station

**Screenshots**

![Google Speaker](https://user-images.githubusercontent.com/109438168/229860097-4d722ad5-a012-47b9-9892-b9484a87595c.png)

![Echo Dot](https://user-images.githubusercontent.com/109438168/229860193-2651c65b-237e-4081-9e42-9241428d071c.png)

See the Google Speaker version verses Echo Dot version

**System details**

- Home-assistant (version):
- alexa_media (version from `const.py` or HA startup):
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). :

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

I would like to display the song title instead of the radio station name.

**Comment by alandtse** [comment]
What does the webapp display? alexa.amazon.com or your app? We mirror whatever it's showing.

**Comment by michaeldjjohnson** [comment]
Alan,

I checked and it shows the radio station and the artist. So you are indeed
mirroring what is being shown.
Is there a way to replace the radio station name with the song title? This
is something that is also present.

Regards and many thanks

Michael

**Comment by michaeldjjohnson** [comment]
I am grateful for your help. Please let me know if this is workable for you.

Regards


Michael

**Comment by alandtse** [comment]
I'll take a enhancement PR if offered.

**Comment by michaeldjjohnson** [comment]
Please let me know what is involved. How much will this cost please.

Regards


Michael

**Comment by michaeldjjohnson** [comment]
I would dearly like to have someone do this tweak for me. Do you have any
suggestions as who can assist?

Any guidance as to how I could do it?

Regards

Michael
