### ISSUE TITLE
expose timers as sensors

### ISSUE THREAD

**Issue by jazzmonger** [custom-components/alexa_media_player#1899]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**
Provide sensors for timers so you can display a countdown display in Lovelace and OpenHasp devices that require sensors for data.
**Describe the solution you'd like**

each time a new timer is created, list its attributes:
- name
- time set for
- time remaining

**Describe alternatives you've considered**
there are no alternative solutions

This gal created a .js lovelace resource and made it work, but ONLY in Lovelace.
(https://community.home-assistant.io/t/show-all-active-alexa-timers/408416/17)
this works, but does not create sensors that can be used in other devices or automations

**Additional context**

![image](https://user-images.githubusercontent.com/52110065/230177896-17353118-5102-4c53-b511-8e523472ccab.png)

**Comment by alandtse** [comment]
You can create template sensors as these are available via [attributes](https://github.com/custom-components/alexa_media_player/wiki#notifications). I think there have been some discussions on the exact templates you need to use on the forum or in the discussions. If you find them, please post here.

**Comment by jazzmonger** [comment]
If they were available as attributes, I wouldn't be asking for a feature request.  They are not.

and nobody has figured out how to create sensors for them.  This is such a basic function...

setting timers is the single biggest use on the Alexa platform after playing music.

**Comment by noxhirsch** [comment]
@jazzmonger This is how I configured my timer sensors - maybe that helps.
The output is the end time of the timer. You could change the template to calculate the relative time, but I wouldn't suggest that since that template then needs to be recalculated every second and spams the database.

```
template:
  - sensor: 
    - name: "Arbeitszimmer Timer 1"
      icon: mdi:timer-outline
      state: >
        {% if state_attr("sensor.alexa_arbeitszimmer_next_timer", "sorted_active") != None %}
          {% set sorted_active = state_attr("sensor.alexa_arbeitszimmer_next_timer", "sorted_active") | from_json %}
          {% if sorted_active[0] in sorted_active %}
            {{ sorted_active[0][1].triggerTime }}
          {% else %}unavailable{% endif %}
        {% else %}unavailable{% endif %}
      attributes:
        label: >
          {% if state_attr("sensor.alexa_arbeitszimmer_next_timer", "sorted_active") != None %}
            {% set sorted_active = state_attr("sensor.alexa_arbeitszimmer_next_timer", "sorted_active") | from_json %}
            {% if sorted_active[0] in sorted_active %}
              {{ sorted_active[0][1].timerLabel }}
            {% else %}unavailable{% endif %}
          {% else %}unavailable{% endif %}
    
    - name: "Arbeitszimmer Timer 2"
      icon: mdi:timer-outline
      state: >
        {% if state_attr("sensor.alexa_arbeitszimmer_next_timer", "sorted_active") != None %}
          {% set sorted_active = state_attr("sensor.alexa_arbeitszimmer_next_timer", "sorted_active") | from_json %}
          {% if sorted_active[1] in sorted_active %}
            {{ sorted_active[1][1].triggerTime }}
          {% else %}unavailable{% endif %}
        {% else %}unavailable{% endif %}
      attributes:
        label: >
          {% if state_attr("sensor.alexa_arbeitszimmer_next_timer", "sorted_active") != None %}
            {% set sorted_active = state_attr("sensor.alexa_arbeitszimmer_next_timer", "sorted_active") | from_json %}
            {% if sorted_active[1] in sorted_active %}
              {{ sorted_active[1][1].timerLabel }}
            {% else %}unavailable{% endif %}
          {% else %}unavailable{% endif %}
```

**Comment by jazzmonger** [comment]
Fascinating.  ok, so modifying my timer code gives me
```
        {% if state_attr("sensor.kitchen_original_next_timer", "sorted_active") != None %}
          {% set sorted_active = state_attr("sensor.kitchen_original_next_timer", "sorted_active") | from_json %}
          {% if sorted_active[0] in sorted_active %}
            {{ sorted_active[0][1].triggerTime }}
          {% else %}unavailable{% endif %}
        {% else %}unavailable{% endif %}

          {% if state_attr("sensor.kitchen_original_next_timer", "sorted_active") != None %}
            {% set sorted_active = state_attr("sensor.kitchen_original_next_timer", "sorted_active") | from_json %}
            {% if sorted_active[0] in sorted_active %}
              {{ sorted_active[0][1].timerLabel }}
            {% else %}unavailable{% endif %}
          {% else %}unavailable{% endif %}
```
And the output  from a 20 minute timer I set is
```
Result type: string
1686769139555
  None
``` 

you stated that "the output is the end time of the timer".  Do I need to convert the number string to something?

**Comment by noxhirsch** [comment]
The result is a timestamp (with milliseconds) which you can convert if you replace this:
`{{ sorted_active[0][1].triggerTime }}`
with that:
`{{ (sorted_active[0][1].triggerTime|int / 1000) | as_datetime }}`
Or you can subtract the current timestamp (`as_timestamp(now())`), get the time difference in seconds and convert that to hours:minutes:seconds.

The timerLabel is only available if you give the timer a name via Alexa (that's why you got "none" there).

**Comment by jazzmonger** [comment]
This is THE MOST helpful information I’ve seen on this function, ever!!

**Comment by alandtse** [comment]
If this is helpful, please consider adding it to the wiki for others. The issue will quickly be submerged.

**Comment by jazzmonger** [comment]
> If this is helpful, please consider adding it to the wiki for others. The issue will quickly be submerged.

Wiki?  How?

**Comment by alandtse** [comment]
![image](https://github.com/custom-components/alexa_media_player/assets/7086117/691feb74-ff33-4150-858b-f29716437007)

**Comment by jazzmonger** [comment]
Where are you defining the template: sensor?
I tried putting ia basic one in sensors.yaml where all my other template sensors are, but get errors
```
  - platform: template
    sensors:
      alexa_timer1:
        friendly_name: "Alexa Timer 1"
        state: >
          {% if state_attr("sensor.kitchen_original_next_timer", "sorted_active") != None %}
            {% set sorted_active = state_attr("sensor.kitchen_original_next_timer", "sorted_active") | from_json %}
            {% if sorted_active[0] in sorted_active %}
              {{ (sorted_active[0][1].triggerTime|int /1000 -  (as_timestamp(now()))) | timestamp_custom('%H:%M:%S', false)}}
            {% else %}unavailable{% endif %}
          {% else %}unavailable{% endif %} 
```
Invalid config for [sensor.template]: [state] is an invalid option for [sensor.template].

**Comment by jazzmonger** [comment]
Wiki updated

https://github.com/custom-components/alexa_media_player/wiki/Home/_edit#alexa-timers

**Comment by jazzmonger** [comment]
its interesting that you can only create 2 Timer Sensors.  You can set 3 timers and see the 3rd in the template viewer, but defining it in sensors_template.yaml has no effect.
```
  - name: "Alexa Timer 3"
    icon: mdi:timer-outline
    state: >
        {% if state_attr("sensor.kitchen_original_next_timer", "sorted_active") != None %}
          {% set sorted_active = state_attr("sensor.kitchen_original_next_timer", "sorted_active") | from_json %}
          {% if sorted_active[2] in sorted_active %}
            {{ (sorted_active[2][1].triggerTime|int /1000 -  (as_timestamp(now()))) | timestamp_custom('%H:%M:%S', false)}}
          {% else %}unavailable{% endif %}
        {% else %}unavailable{% endif %}   
```

**Comment by jazzmonger** [comment]
well, the wiki "was" updated.  my edits are now missing...

**Comment by noxhirsch** [comment]
@jazzmonger It got moved to "Examples": https://github.com/custom-components/alexa_media_player/wiki/Examples%3A-Sensors#alexa-timers
