### ISSUE TITLE
Connection Error!  (Errno -2) Name does not resolve

### ISSUE THREAD

**Issue by Momentum6890** [custom-components/alexa_media_player#1900]
I wanted to reinstall Alexa Media Player because I was having problems. Unfortunately it won't install anymore, I always get the error below. I have not changed anything on my system. Can anyone help?  

![Screenshot_20230408-161732](https://user-images.githubusercontent.com/95884912/230734649-e48f929d-6ece-433c-9b55-c3624f86677e.png)

**System details**

- Home-assistant (version): 2023.04.1
- alexa_media (version from `const.py` or HA startup): 4.6.2
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n).: yes

**Comment by jocamane** [comment]
in my case alexa is unavailable. what is up ?

![image](https://user-images.githubusercontent.com/32019937/230735697-6fb09a83-f32f-47d6-864a-1574e0ddfe5a.png)

Home Assistant 2023.3.6
Supervisor 2023.03.3
Operating System 9.5
Frontend 20230309.1 - latest
alexa_media (version from const.py or HA startup): 4.6.2
Amazon [2FA is enabled] (y/n).: yes

**Comment by nikosda** [comment]
I have the same problem.
After the update the Alexa Media Player no longer works. When trying to connect it again I get the same error. Tried with and without an MFA..

**Comment by iamtheeric** [comment]
Same Problem ober here since today... out of nowhere:

Connection Error! Please try refreshing. If this persists, please report this error to [here](https://github.com/custom-components/alexa_media_player/issues):
[Errno -2] Name does not resolve

Didn't update anything

**Comment by bonsaijogi** [comment]
> 

Thanks to iamtheeric, this works for me too

**Comment by alandtse** [comment]
I'll leave the issue open, but this is a HA DNS issue. The component doesn't control that.

**Comment by Momentum6890** [comment]
> Same Problem over here since today... out of nowhere. Everything was workong well since a few hours ago.
> 
> Connection Error! Please try refreshing. If this persists, please report this error to [here](https://github.com/custom-components/alexa_media_player/issues): [Errno -2] Name does not resolve
> 
> Didn't update anything
> 
> EDIT: this solved it:
> 
> I had some difficulty adding the Alexa integration (v4.3.2) in HA 2022.11.05. I followed the steps and got as far as entering the one time code and being taken to the Alexa website sign-in screen. But when tried to log in I got an error: cannot connect to host name ... does not resolve home assistant.
> 
> Here is what worked for me.
> 
> In HA, open Terminal (add-on)
> 
> From command line enter this command: ha dns options --servers dns://8.8.8.8
> 
> Then enter this command: ha dns restart
> 
> After doing this, I tried again to integrate Alexa Media Player and was able to make it all the way. Hope this helps someone.
> 
> [credits to](https://github.com/custom-components/alexa_media_player/discussions/1791)
> 
> not a clean solution at all but i'll habe to see what breaks now. Maybe the author can adjust this in the next release.


Thanks, that work for me too 👍🏻

**Comment by Momentum6890** [comment]
> I'll leave the issue open, but this is a HA DNS issue. The component doesn't control that.


Ok, thanks for the info 👍🏻👍🏻👍🏻

**Comment by thecem** [comment]
I tried your solution (8.8.8.8), it works, but all other integration connects servers on lokal network with the dns name looses the connection.

for servers there was no entry in `ha dns info` now it points to my router, to get my rest working. But now no connection for Alexa media….

**Comment by iamtheeric** [comment]
> I tried your solution (8.8.8.8), it works, but all other integration connects servers on lokal network with the dns name looses the connection.
> 
> for servers there was no entry in `ha dns info` now it points to my router, to get my rest working. But now no connection for Alexa media….

Strange. The change trough the terminal cmds didn't break any of my other intergrations and I have >10 integrations which rely on external servers/cloud services and about 15 integratioins that rely on local communication only. Not sure why this doesn't work for you. But I'm pretty new to HA (<3 months) and there are a lot of things I don't understand yet. Crossing fingers that you find a working solution for your installation.

**Comment by dongore** [comment]
For me, setting the Google DNS server doesn't help, the error persists. Btw, how can you remove the DNS entry from the server list?

**Comment by Hackashaq666** [comment]
Anyone know how to make the DNS change on homeassistant as container (docker)?
Thanks!

**Comment by Hackashaq666** [comment]
I did sometroubleshooting, if I rollback to v4.5.3 I can add the compomemt!
So, it seems like something changed in the v4..6.2 that prevents me from adding it.

**Comment by alandtse** [comment]
You can compare the code and submit a PR if you can find what we changed that would impact the dns. Happy for any help.
https://github.com/custom-components/alexa_media_player/compare/v4.5.3...v4.6.2
https://gitlab.com/keatontaylor/alexapy/-/compare/v1.26.4...v1.26.5?from_project_id=7993293&straight=false
