### ISSUE TITLE
Air Quality Sensor not connecting

### ISSUE THREAD

**Issue by gitrichhub** [custom-components/alexa_media_player#1902]
I have successfully added an Amazon Air Quality Monitor to my Amazon account. However even after checking the box to allow the connection to devices connected to echos, the sensors do not appear.  I do use the 'Include' function when configuring Alexa Media Player and have added the name given in the Alexa App for the AQM.  
I have also connected an echo device to the AQM for notifications in the Alexa App.

I am unsure how to determine the version of Alexa Media Player I am using, but it is the most current stable version as of today.

HASS is version 2023.3.6

**Comment by gitrichhub** [comment]
Was this closed because I didn't provide enough information? or am wrong that Alexa Media player connects to the amazon AQM?  Or you don't know me? Just curious.

**Comment by alandtse** [comment]
Closed for not using the mandatory template.

**Comment by gitrichhub** [comment]
Ok. Thanks for your help. Much appreciated. On Apr 13, 2023, at 8:53 PM, Alan Tse ***@***.***> wrote:﻿
Closed for not using the mandatory template.
