### ISSUE TITLE
Not all timers are passed to HA

### ISSUE THREAD

**Issue by snigehere** [custom-components/alexa_media_player#1905]
I use alexa to do things like turn on my dishwasher at a time of my choosing .. this is done via a smart plug which is exposed to alexa.  Alexa will accept the request and create a timer to show how long before its turned on 

eg "alexa, turn on the dishwasher at 08:30" 

In the timer display on my alexa app I will see a timer counting down to the start time:

hh:mm:ss 
dish washer - echo device name

This timer is not exposed in HA via sensor.echo device_next_timer .. if this is the only timer the entity state is "unknown"

But if I set a standard timer ...eg alexa, set egg timer 3 minutes this shows up in "timers" of the alexa app and is exposed to HA.

Is there some way for count down timer to be exposed via HA?

Thanks
![Screenshot_20230412_005542_Amazon Alexa](https://user-images.githubusercontent.com/104912027/231313432-5833b997-52a8-44cc-9af3-105e372622af.jpg)

**Comment by snigehere** [comment]
Hi @alandtse I see you tagged this as "Help wanted" - can you tell me what help you need?  Happy to help with testing etc, getting traces etc (with guidance) but I am unable to help with coding as its beyond my skills set.

Thanks for your continued suport.

**Comment by alandtse** [comment]
Yes looking for someone to help submit the fix.

**Comment by snigehere** [comment]
Ok - Thanks - clear - maybe I need to retrain!
Hope you get some help.
