### ISSUE TITLE
Get and Set Volume for Alarms, Timers, Notifications

### ISSUE THREAD

**Issue by oni-23** [custom-components/alexa_media_player#1908]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**
It's possible to set a different volume for alarms / reminders / timer, and it's possible to control this volume within the Alexa app. Sadly, It's not yet possible to control it via home assistant.

**Describe the solution you'd like**
As an Alexa media player user, I want to be able to control alarm volume within home assistant to use it in automations.

**Describe alternatives you've considered**
Using a routine / custom command to set it, but that will play a notification every time it's triggered, even when old and new alarm volume are the same.

**Additional context**
Friends of mine teach me what they can change with a short visit in my flat. Notification volume is kinda evil. Too loud and you get a shock with the next alarm – Too silent, and you miss waking up.

Where to find it on Android
Alexa App > Devices > _echo device_ > Settings > General: Sounds > Alarms, Timers, Notifications
<img src="https://user-images.githubusercontent.com/93731791/232330356-f3c84a09-c3a0-4aa7-a00e-b20d256e1b68.png" width="250px">

**Comment by alandtse** [comment]
Thanks for the great instructions on how to find the setting. Hopefully someone can submit a PR adding it.

**Comment by chemelli74** [comment]
Is just closed but not completed 🥲
