### ISSUE TITLE
alexa_media_last_called service name changes if device ends in digit

### ISSUE THREAD

**Issue by cryptk** [custom-components/alexa_media_player#1910]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

If the device name for the last called device ends with a numeric digit, the `notify.alexa_media_last_called` service has it's name changed to `notify.alexa_media_last_called_${email_address}`.  The code responsible is located at https://github.com/custom-components/alexa_media_player/blob/dev/custom_components/alexa_media/notify.py#L177-L179.

**To Reproduce**

1. Select an alexa media_player entity
2. Change it's device name in Home Assistant to have the last character in the name be a numeric digit
3. Speak to alexa via the device associated with that media_player entity
4. Look for the `notify.alexa_media_last_called` service and notice that it has an email address appended to it
5. Change the device name in Home Assistant so that it no longer ends in a numeric digit
6. Speak to alexa again via the device associated with that media_player entity
7. Observe that the `notify.alexa_media_last_called` service is now named as expected

**Expected behavior**

The name of this service should not change, this makes automations more difficult than they need to because the name of the service you need to call may be different than expected and documented based on the name of the device you are speaking to.

**System details**

- Home-assistant (version): Home Assistant 2023.4.4
- alexa_media (version from `const.py` or HA startup): 4.6.2
- alexapy (version from `pip show alexapy` or HA startup): 1.26.5
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : y

**Logs**
The logs for this aren't super useful for adding more context to the issue, but if you want logs while some specific action is being performed, let me know.

**Additional context**

I never would have noticed this if it weren't for my recent purchase of a Sonos Era 100 (who's name ends in a numeric digit). I am unsure if there is a reason why the service name should change if the target device has a name that ends in a number, but the behavior should be adjusted to keep the service name consistent, either with or without the email address (although without the email address would have it work in the way that is already documented).

**Comment by alandtse** [comment]
Thanks for the great bug report. Yah that's a weird corner case. I'll take any PRs to fix it. The code was handling the corner case where there are more than one last_called entities because of multiple accounts.

Workaround is to not allow entity names to end in numbers.
