### ISSUE TITLE
Integration spontaneously stops working and cannot be restarted again

### ISSUE THREAD

**Issue by baloo-gh** [custom-components/alexa_media_player#1912]
Running on latest HA with latest Alexa Media Player. Everything works perfectly, yet ever since I installed this, at some point in time the integration simply stops working (see screenshot), and cannot be reloaded. 

I tried an automated reload (every hour) which seems to be pushing out that problem for a few hours, yet sooner or later this happens again, which forces me to do a HA restart to fix this.

Any idea what's broken? As said, when it works, it works beautifully, yet sometimes it simply stops, and then only a HA restart can fix that.

![Alexa Media Player - not working](https://user-images.githubusercontent.com/45927782/233219573-33b2b2d9-d60b-4a84-8fec-b6bb7cd990ad.png)

**Comment by alandtse** [comment]
Use template if you want help.
