### ISSUE TITLE
Error when trying to add alexa media player integration

### ISSUE THREAD

**Issue by Hackashaq666** [custom-components/alexa_media_player#1914]
I have been using this integration for years,  Today I had to re-connect to it, and I keep getting the following error in a web page, after entering my credentials:

"Connection Error! Please try refreshing. If this persists, please report this error to here:
[Errno -2] Name does not resolve"

- Home-assistant (version): 2023.4.6 (container)
- alexa_media (version from `const.py` or HA startup): 4.6.2
- alexapy (version from `pip show alexapy` or HA startup):  NA
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : y

**Comment by Hackashaq666** [comment]
OK, I see this is a duplicate of #1900 

As I mentioned there, 

"I did some troubleshooting, if I rollback to v4.5.3 I can add the component!
So, it seems like something changed in the v4..6.2 that prevents me from adding it."

**Comment by alandtse** [comment]
Please follow the original.
