### ISSUE TITLE
notify.alexa_media broken after update (atomic notify working)

### ISSUE THREAD

**Issue by haplm** [custom-components/alexa_media_player#1917]
**Describe the bug**

After updating to the latest version (4.6.2), `notify.alexa_media` no longer works. However, addressing individual speakers (like `notify.alexa_media_martin_s_echo`) still works.

**To Reproduce**

Upgrade to latest version, restart

**Expected behavior**

Should work as usual, `notify.alexa_media` shouldn't throw an error

**System details**

- Home-assistant (version): 2023.4.6
- alexa_media (version from `const.py` or HA startup): 4.6.2
- alexapy (version from `pip show alexapy` or HA startup): 1.26.5
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account): YES

**Logs**

[home-assistant_alexa_media_2023-04-28T20-09-23.887Z.log.zip](https://github.com/custom-components/alexa_media_player/files/11356998/home-assistant_alexa_media_2023-04-28T20-09-23.887Z.log.zip)

**Comment by traktormichl** [comment]
Same here.

**Comment by mammy07** [comment]
Same here.

**Comment by mammy07** [comment]
Same

**Comment by kavierkoo** [comment]
+1

**Comment by alandtse** [comment]
Please provide the service call. The logs are reporting your targets is blank.

```
  File "/config/custom_components/alexa_media/notify.py", line 222, in async_send_message
    for target in targets:
TypeError: 'NoneType' object is not iterable
```

**Comment by haplm** [comment]
You are right, my bad. For some reason after upgrading Home Assistant marked all automations with notify.alexa_media as broken. And when I tried to test it, I forgot that target needs to be specified. I'm sorry.
