### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by wavesswe** [custom-components/alexa_media_player#1919]
The integration suddenly broke. Can not get it to work. I have tried to re install but still same issue.

I just get this

"Connection Error! Please try refreshing. If this persists, please report this error to [here](https://github.com/custom-components/alexa_media_player/issues):
All connection attempts failed"

**Comment by GitHubGoody** [comment]
+1

I get "Retrying setup: Connection Error during login"

**Comment by rafareusch** [comment]
+2 (maybe) 

I have two HA instances with similar configuration, both use this integration.
Both appeared "Attention Required" with the reconfigure button, when clicking the reconfigure button, this error pops up:
**"Config flow could not be loaded: Unknown error"**
In one of my instances I tried to reinstall the integration, removed from the integration page and added again, when I put all credentials and 2FA key, it opens browser and then I login in my account, then it goes back to HA and gets stuck saying "Loading next step for Alexa Media Player"  after some time it pop ups an error saying  "Error" (in the Title, with no other text)
I also tried removing the integration from HACS and redownloading, the account used in this installation works fine in a third instance, no luck.
