### ISSUE TITLE
Integration stopped working, cannot authenticate when re-setting up

### ISSUE THREAD

**Issue by mikedd732** [custom-components/alexa_media_player#1921]
I was having problems with my Integration, removed it and added it back. When authenticating, it gets to this point: 

![Screenshot 2023-05-04 at 8 24 12 AM](https://user-images.githubusercontent.com/77407180/236203237-03c645ff-eabf-4833-97a9-d603da149d5e.png)

But continues redirecting to URLs with a :0 as a port number. If manually removing those each time, you eventually get to a 500 Internal Server Error page being served by /auth/alexamedia/proxy/ap/signin/133-7493927-9707447 on the HA server.

**Comment by csongorfarago** [comment]
Same here, integration stopped working middle of the night, try to reconfigure and it throws 500: internal server error

**Comment by JoeKarlsson** [comment]
Yup - same boat. Good to see I'm not alone. When I click "submit", Firefox throws this error.
<img width="921" alt="Screenshot 2023-05-04 at 9 58 53 AM" src="https://user-images.githubusercontent.com/4650739/236247270-9c2664fb-7015-4019-8357-93b532febccc.png">

**Comment by henrybauer** [comment]
Same.  Reverting to v4.5.3 did not help

**Comment by zeldoy24** [comment]
I also have an issue. It seemed that with home assistant yellow it's using more cpu than it should making my entire home assistant slow.......cpu sitting close to 30 percent with integration enabled. the 2nd issue i have is it only works 20 percent of the time now....

**Comment by zeldoy24** [comment]
Unexpected error fetching alexa_media data: 'NoneType' object has no attribute 'split'

**Comment by SGC1990** [comment]
same problem cant get back enabled. after deleting and readding

**Comment by SGC1990** [comment]
> @SGC1990 did you notice your system slower as well (home assistant)

Yes I did something is wrong

**Comment by zeldoy24** [comment]
@SGC1990 ok so the slow system is not because of something i did.....my automations took longer than 10 seconds to activate then i checked in system settings for my home assistant and it boosted my cpu usage by 20 percent making the system very sluggish

**Comment by zeldoy24** [comment]
![log 1](https://user-images.githubusercontent.com/108962242/236309546-8a0374ff-ebd4-427b-80d9-65c376ecbfcc.png)
@SGC1990 look at this this is with alexa media player integration enabled....even added it's completley messing the system up

**Comment by zeldoy24** [comment]
@SGC1990 the alexa media integration add on you mean

**Comment by CrossfireCurt** [comment]
@zeldoy24 I don't think your issue is related to the one OP mentioned - probably worth opening a new issue so we don't clutter this one with potentially irrelevant/confusing information.

**Comment by zeldoy24** [comment]
@CrossfireCurt before couple days ago this wasn't an issue until i did  the update....which seems related to the alexa media integration. also worht noting i reverted back to the older HA instance and I still have the same issue with the "alexa media integration"

**Comment by SGC1990** [comment]
> @SGC1990 the alexa media integration add on you mean

yes I have it off and my system runs normail even add the new openai and have them running and in use now.

**Comment by CrossfireCurt** [comment]
@zeldoy24 I'm not doubting you're having a problem, but it sounds unrelated to being able to authenticate with the integration. You should open a new issue.

**Comment by SGC1990** [comment]
> Agreed. This is still an issue and this issue shouldn't be closed just because someone derailed the OG issue.

Reopened the Issue

**Comment by zeldoy24** [comment]
Clearly wasn't fixed no idea why he closed it.....

**Comment by SGC1990** [comment]
> Agreed. This is still an issue and this issue shouldn't be closed just because someone derailed the OG issue.

I opened a new one so there is nothing to do with being off topic

**Comment by mikedd732** [comment]
4.6.4 update looks to have resolved this issue.

**Comment by JoeKarlsson** [comment]
Agreed. 4.6.4 resolved this issue for me as well.

**Comment by henrybauer** [comment]
4.6.4 resolved this for me too, thanks!
