### ISSUE TITLE
Der Konfigurationsfluss konnte nicht geladen werden: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by Chris383838** [custom-components/alexa_media_player#1926]
Hi,

after  adding the integration I get the following error:

Der Konfigurationsfluss konnte nicht geladen werden: 500 Internal Server Error Server got itself in trouble.

I can not finde more in the Log.

Regards

Chris

**Comment by muerzo** [comment]
ho lo stesso problema non riesco a trovare la soluzione
