### ISSUE TITLE
Alexa authentication bug, url is wrong, Cannot load Integration 

### ISSUE THREAD

**Issue by jazzmonger** [custom-components/alexa_media_player#1927]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**
Unlike others, I'll provide as much info as I possibly can.  If you need something else, pls be **very** specific on how to get it for you.

The problem lies in the automated url generation for authorization 
```...ui.nabu.casa:0/auth/alexamedia...```
The ```:0 ```shouldn't be there.  If you remove it, you get a lot further, but it still won't authenticate 

**To Reproduce**

just try and add the Alexa Media Player

**Expected behavior**
Add the integration 

Authorize with a VALID url.
**Screenshots**

![961B2E10-4F02-4F9A-B6CB-290C24833FAE](https://user-images.githubusercontent.com/52110065/236579339-fc0446ec-3b35-444f-a81d-29248cca2bbe.jpeg)

**System details**

- Home-assistant (version):  2023.5.0
- alexa_media (version from `const.py` or HA startup): From HACS 4.6.2

- alexapy (version from `pip show alexapy` or HA startup): There is no way to tell.  Integration isn't available on startup.
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n)yes
:

**Logs** no way to provide logs if you can't even load the integration.
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by zeldoy24** [comment]
ah you beat me to it I was just creating a proper bug report...I also submitted another bug for when it is integrated.....

**Comment by jazzmonger** [comment]
> ah you beat me to it I was just creating a proper bug report...I also submitted another bug for when it is integrated.....

Are you seeing the same thing in the url?

**Comment by zeldoy24** [comment]
@jazzmonger yes.....and when i revert back to previous version when i did have the integration working it's eating up like more than half of my cpu making everything else super slow......like automations and etc....

**Comment by jazzmonger** [comment]
Revert using home assistant restore or load older version of Alexa Media Player?

**Comment by zeldoy24** [comment]
@jazzmonger older home assistant file..like 4.6 and older backups integrated it again

**Comment by zeldoy24** [comment]
however it made another issue arise "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/alexa_media/binary_sensor.py", line 36, in async_setup_platform
account = config[CONF_EMAIL] if config else discovery_info["config"][CONF_EMAIL]
KeyError: 'email'  @jazzmonger

**Comment by surya2302-droid** [comment]
facing the same error. downgrading HA core to 2023.4.1 seems to resolve the error as of now

**Comment by zeldoy24** [comment]
Not for me I'm facing an entire different problem ....like high CPU usage @surya2302-droid

**Comment by alandtse** [comment]
This is not a discussion forum. Please do not pollute it with off topic conversations. This makes it difficult for those who may want to read it to get to the information they may need. It also spams peoples emails with unnecessary info.

The port number is pulled from HA. We don't populate it. Please check your Settings -> Network:
![image](https://user-images.githubusercontent.com/7086117/236638870-2a2daef8-4d39-4a9b-86a6-c4d7627de1fe.png)

We have heard reports disabling for setup IPv6 can workaround networking errors with the auth proxy.

I can't do anything without [enabling debug logs](https://www.home-assistant.io/docs/configuration/troubleshooting/#enabling-debug-logging). You can obfuscate your HA url, but please leave the port intact. There's debug lines when it sets up the callback url.

**Comment by alandtse** [comment]
As a note, when configuring the component, it lets you check the url that it found. What is it saying there?
![image](https://user-images.githubusercontent.com/7086117/236641272-c1f3867e-231e-4242-9cc8-9afbf8f0ec76.png)

**Comment by iamehkri** [comment]
> This is not a discussion forum. Please do not pollute it with off topic conversations. This makes it difficult for those who may want to read it to get to the information they may need. It also spams peoples emails with unnecessary info.
> 
> The port number is pulled from HA. We don't populate it. Please check your Settings -> Network: ![image](https://user-images.githubusercontent.com/7086117/236638870-2a2daef8-4d39-4a9b-86a6-c4d7627de1fe.png)
> 
> We have heard reports disabling for setup IPv6 can workaround networking errors with the auth proxy.
> 
> I can't do anything without [enabling debug logs](https://www.home-assistant.io/docs/configuration/troubleshooting/#enabling-debug-logging). You can obfuscate your HA url, but please leave the port intact. There's debug lines when it sets up the callback url.



I changed my network to disable IPV6


> Traceback (most recent call last):
> File "/usr/local/lib/python3.10/site-packages/anyio/streams/tls.py", line 130, in _call_sslobject_method
> result = func(*args)
> File "/usr/local/lib/python3.10/ssl.py", line 917, in read
> v = self._sslobj.read(len)
> ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2578)
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
> File "/usr/local/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 34, in read
> return await self._stream.receive(max_bytes=max_bytes)
> File "/usr/local/lib/python3.10/site-packages/anyio/streams/tls.py", line 195, in receive
> data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
> File "/usr/local/lib/python3.10/site-packages/anyio/streams/tls.py", line 137, in _call_sslobject_method
> data = await self.transport_stream.receive()
> File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1265, in receive
> await self._protocol.read_event.wait()
> File "/usr/local/lib/python3.10/asyncio/locks.py", line 214, in wait
> await fut
> asyncio.exceptions.CancelledError
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
> File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
> yield
> File "/usr/local/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 32, in read
> with anyio.fail_after(timeout):
> File "/usr/local/lib/python3.10/site-packages/anyio/_core/_tasks.py", line 118, in __exit__
> raise TimeoutError
> TimeoutError
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
> File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
> yield
> File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
> resp = await self._pool.handle_async_request(req)
> File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
> raise exc
> File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
> response = await connection.handle_async_request(request)
> File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 90, in handle_async_request
> return await self._connection.handle_async_request(request)
> File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 116, in handle_async_request
> raise exc
> File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 95, in handle_async_request
> ) = await self._receive_response_headers(**kwargs)
> File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 159, in _receive_response_headers
> event = await self._receive_event(timeout=timeout)
> File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 195, in _receive_event
> data = await self._network_stream.read(
> File "/usr/local/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 31, in read
> with map_exceptions(exc_map):
> File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
> self.gen.throw(typ, value, traceback)
> File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
> raise to_exc(exc)
> httpcore.ReadTimeout
> The above exception was the direct cause of the following exception:
> Traceback (most recent call last):
> File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
> resp = await request_handler(request)
> File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
> resp = await handler(request)
> File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
> return await handler(request)
> File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
> return await handler(request)
> File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 94, in forwarded_middleware
> return await handler(request)
> File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
> return await handler(request)
> File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
> return await handler(request)
> File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
> return await handler(request)
> File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
> result = await result
> File "/config/custom_components/alexa_media/config_flow.py", line 886, in wrapped
> return await cls.handler(request, **kwargs)
> File "/usr/local/lib/python3.10/site-packages/authcaptureproxy/auth_capture_proxy.py", line 387, in all_handler
> resp = await getattr(self.session, method)(
> File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1754, in get
> return await self.request(
> File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1530, in request
> return await self.send(request, auth=auth, follow_redirects=follow_redirects)
> File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1617, in send
> response = await self._send_handling_auth(
> File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
> response = await self._send_handling_redirects(
> File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
> response = await self._send_single_request(request)
> File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1719, in _send_single_request
> response = await transport.handle_async_request(request)
> File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
> with map_httpcore_exceptions():
> File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
> self.gen.throw(typ, value, traceback)
> File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
> raise mapped_exc(message) from exc
> httpx.ReadTimeout

**Comment by iamehkri** [comment]
And the URL in the windows to "Access Home Assistant" matched my URL that I have for online access.

**Comment by jazzmonger** [comment]
![BC0BBEB7-49D6-44A2-892E-F53A82BC48DB](https://user-images.githubusercontent.com/52110065/236658328-74e28cbc-1969-4c2d-8233-a8bebdc18d2d.jpeg)
![887C76A1-50B2-41AA-BDB6-6CF38D53DA06](https://user-images.githubusercontent.com/52110065/236658331-b5ccf9d1-4eb7-479c-ae7d-c44e1e9fe761.jpeg)
![F98A5BAB-E95A-4119-8386-9C560B127987](https://user-images.githubusercontent.com/52110065/236658334-d40c88da-ba3a-4228-920b-0d4827ee813b.jpeg)

**Comment by jazzmonger** [comment]
Ok, more info.  If I change the home assistant URL to local, the web browser opens and I authenticate.  BUT, nothing happens in the home assistant app. The open browser pop up remains.
![8A53C034-3BA3-4F88-8F90-32E292D4C67A](https://user-images.githubusercontent.com/52110065/236659158-d3d924ff-2af0-4001-b09d-4a967f43019b.jpeg)
![847F7FD8-8C84-4D37-8B0F-29DCF56CA299](https://user-images.githubusercontent.com/52110065/236659159-5611ab13-f304-46a1-b27c-9da839c08412.jpeg)

**Comment by jazzmonger** [comment]
SUCCESS.  If I use a **web browser** (NOT the IOS ha app), **AND** I change the ha access URL to local from the default Nabucasa url, I'm able to authenticate and add the integration.

again, I'm happy to test further to help isolate the bug.

![4CA6DFB8-99AD-43C4-B846-34C42097BA5B](https://user-images.githubusercontent.com/52110065/236659422-cadc06fd-33a7-471b-b5f3-861a74c81279.jpeg)

**Comment by iamehkri** [comment]
The above method has worked for me as well.

**Comment by DaveStLou** [comment]
The local IP and port worked for me.

As an additional point of information, I was getting the error not only while using the NabuCasa url but **also** while using my Cloudflare redirected url. Neither of those use a port to get to my HA from outside my network.
