### ISSUE TITLE
This site can't be reached error

### ISSUE THREAD

**Issue by ofeksit** [custom-components/alexa_media_player#1935]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

I'm trying to configure the integration (I wrote the username, password and the 2FA code from amazon website), once I click on "submit" and the new tab site is open, I get "This site can’t be reached".

**To Reproduce**

1. Go to "Configure"
2. Click on "Submit" after filled up required fields.
3. See error

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/23336925/236783893-87888f6d-6053-4c76-9d55-6aae94b523ae.png)

**System details**

- Home-assistant (version): 2023.5.0
- alexa_media (version from `const.py` or HA startup): 4.6.4
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). Yes

**Logs**
Can't reach any logs...

**Comment by darksid3r** [comment]
I have the same issue. Seems to be related to the URL trying to access port 0 (:0) of the server

**Comment by ofeksit** [comment]
I'm using nabu casa, weird.

**Comment by ofeksit** [comment]
found the solution.
Use the internal address only.
