### ISSUE TITLE
Errors in automations using the notify service. alexa_media

### ISSUE THREAD

**Issue by edu24x** [custom-components/alexa_media_player#1940]
Greetings.

The system reports errors but there are no related entries in the Home Assistant log. 

However, the service and automations work perfectly.

**To Reproduce**

1. Go to /config/dashboard
2. Click on "Settings"
3. See error:
   "The automation 'Ainhoa llega a casa.' ( automation. llega_a_casa ) has an action that calls an unknown service: notify. alexa_media_echo_dot_de_edu_blanco .
This error prevents the automation from running correctly. Maybe this service is no longer available, or perhaps a typo caused it.
To fix this error, edit the automation and remove the action that calls this service. Click on SUBMIT below to confirm you have fixed this automation."

**Expected behavior**

The service is correct despite the errors.

**Screenshots**

![10-05-2023_07-28-44](https://github.com/custom-components/alexa_media_player/assets/67578427/3d106eda-174c-4fea-a0f1-926648e74ca3)

![10-05-2023_07-30-03](https://github.com/custom-components/alexa_media_player/assets/67578427/6e084e69-c33d-4eeb-bcdf-3b2e7d874d0b)

![10-05-2023_07-35-16](https://github.com/custom-components/alexa_media_player/assets/67578427/a37aac07-2e51-4d96-ba89-4f67f7a1a5a8)

![10-05-2023_07-37-30](https://github.com/custom-components/alexa_media_player/assets/67578427/ea554900-8c54-4c27-bdb3-28f73d5aa1a9)

**System details**

- Home-assistant: 2023.5.2
- alexa_media (version from `const.py` or HA startup): 4.6.4
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled]: Yes

**Logs**

[home-assistant_alexa_media_2023-04-28T20-09-23.887Z.log](https://github.com/custom-components/alexa_media_player/files/11440838/home-assistant_alexa_media_2023-04-28T20-09-23.887Z.log)

**Comment by sator86** [comment]
I have exactly the same issue

![image](https://github.com/custom-components/alexa_media_player/assets/55639966/a8ad9826-1847-48c8-add2-2579537134ec)

![image](https://github.com/custom-components/alexa_media_player/assets/55639966/211da84c-d29c-4511-916c-27e99534e8c1)

**Comment by alandtse** [comment]
If you call the services before the integration fully loads, you will get those errors. The service normally needs a few minutes after HA starts to fully load (depending on your hardware and integrations). Make sure your automations give enough time.

**Comment by edu24x** [comment]
> I had the same issue, and was able to solve it by going to Integrations, Alexa Media Player, and clicking Reload.

This doesn't work in my case. Is this supposed to make the repair notifications disappear?

Greetings.

**Comment by edu24x** [comment]
> If you call the services before the integration fully loads, you will get those errors. The service normally needs a few minutes after HA starts to fully load (depending on your hardware and integrations). Make sure your automations give enough time.

You mean add a delay to automation?

Greetings.
