### ISSUE TITLE
MIssing labeling  (what to type in)

### ISSUE THREAD

**Issue by MYLE-01** [custom-components/alexa_media_player#1941]
![image](https://github.com/custom-components/alexa_media_player/assets/4362345/2eef9241-721d-43cc-9440-4d39810e46f7)

its even in the dark theme

and it the Deafult theme

**Comment by alandtse** [comment]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**
