### ISSUE TITLE
Device status is no being updated

### ISSUE THREAD

**Issue by martinbeno** [custom-components/alexa_media_player#1944]
media_player entity doesn't update attributes of media status (standby/palying/paused and song metadata ...). It gets updated only if there is some other activity (like I say anything to Alexa, or send any command or notification from HA thru alexa_media integration.

However attributes like last_called_timestamp, last_called_summary, connected_bluetooth get updated flawlessly.

- Home Assistant 2023.5.2
- Supervisor 2023.04.1
- Operating System 10.1
- Frontend 20230503.3 - latest4. HA
- Using Echo Dot 5th gen.
- Tested with alexa_media v.4.6.3 and v4.6.4 (manual install, I don't use HACS)
- no errors in log

**Comment by martinbeno** [comment]
Hello,

I’m confused, you have closed this issue as completed without single comment??
Am I missing something? I’m sorry if so, I’m very new to all this.

Thank you for your help,

Regards,
Martin

**Comment by alandtse** [comment]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Comment by broyuken** [comment]
I have the same issue. No errors in the logs. I just enabled debug logging and if needed I can post a new issue that follows the template fully.

**Comment by martinbeno** [comment]
Im wandering, have you posted new issue? I would be monitoring that thread as well.

**Comment by broyuken** [comment]
Yes I opened https://github.com/custom-components/alexa_media_player/issues/1953
