### ISSUE TITLE
Device renamed on Alexa mobile app are not renamed in HA

### ISSUE THREAD

**Issue by chemelli74** [custom-components/alexa_media_player#1954]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

I renamed a Echo Dot in Alexa app, but unfortunately the updated info is not reflected in HA.
I didn't find a solution other that remove/readd the integration.

**To Reproduce**

1. Configure Alexa App
2. Add a Echo Dot to Alexa
3. Configure this integration
4. Check entities in HA are created with the same name as in Alexa
5. Rename the previous Echo Dot device in Alexa App
6. Check entities in HA are not updated
7. Reboot HA 
8. Check entities in HA are still not updated

**Expected behavior**

Entities to be renamed as in Alexa mobile app so to be always in sync.

**Screenshots**

**System details**

- Home-assistant (version): 2023.4.6
- alexa_media (version from `const.py` or HA startup): 4.6.4
- alexapy (version from `pip show alexapy` or HA startup): 1.26.8
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : Yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by alandtse** [comment]
Given this isn't a common use case, can be changed in HA, and how easy the workaround is, Ithis a feature request. Within HA entities are linked to the serial number so this won't affect functionality. In fact, changing the entity name will likely break HA automations/scripts. HA may need to add functionality to also update automations/scripts if the entity name changes.

Happy to take a PR to address this though.

**Comment by adampetrovic** [comment]
> Given this isn't a common use case, can be changed in HA

@alandtse how does one rename a service? Sure you can rename a media player, but the `notify.alexa_media_*` services retain their old name.
