### ISSUE TITLE
Notification repeating

### ISSUE THREAD

**Issue by ifflanb** [custom-components/alexa_media_player#1959]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

Since a recent update, my alexa announcement are repeating (announced twice in total). 

When using "Notifications: Send a notification with alexa_media" and with a type of "announce" and method of "all", try announcing to multiple devices, the announcement is announced twice.

**Expected behavior**

It announces once

**Screenshots**

**System details**

- Home-assistant (version):
- alexa_media (version from `const.py` or HA startup):
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). :

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by alandtse** [comment]
Please provide logs.

**Comment by beniffland** [comment]
I havent test this yet but I noticed that there were 2 integration entries in my Alexa media configuration. Looks suspicious. I'll try removing one. It may be from a password change that I did recently for Amazon.

**Comment by beniffland** [comment]
Yep that seems to have fixed it.

**Comment by alandtse** [comment]
Glad you figured it out.
