### ISSUE TITLE
Allow the possibility to repeat the last notification

### ISSUE THREAD

**Issue by martin3000** [custom-components/alexa_media_player#1961]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**
I use alexa very often for notifications from home assistant. But often, I do not understand what alexa said because I was talking to somebody or just entered the house. I would like to set up an alexa routine "say again" which switches an HA switch, which triggers an automation, which calls notify.alexa_media_my_echo_dot with "type: repeat".

**Describe the solution you'd like**
So this means that alexa_media_player internally remembers the last notification or it sets a sensor value to the last notification, which can then be used in a second notify.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by alandtse** [comment]
Seems easy enough for someone to submit a PR to do. It'd only be able to do it with what the component was last given; otherwise we'd have to keep polling the activities page which may be too much for the API.

**Comment by martin3000** [comment]
> otherwise we'd have to keep polling the activities page which may be too much for the API.

HA notifications do not appear in the alexa activities.

**Comment by jane-t** [comment]
What I do for notifications is I have a script which takes the text and the device to use.
I use this whenever I need to send tts to an Alexa.  The script sends to Alexa and at the same time sends to a MQTT topic the text and the Alexa ID.  This is picked up and put into a MQTT Sensor with the text in the attribute.

It is then easy to trigger a script which replays the last message to the alexa which played it.

**Comment by martin3000** [comment]
This can also be used if nobody is at home and the dish washer has finished. You could send the text in some kind of queue and when the people come home, alexa says the message.

**Comment by martin3000** [comment]
> I have a sensor which queues up messages, I did write some notes on it here: https://www.rjt.org.uk/home/archives/home-assistant-tip/setting-up-a-message-box-in-home-assistant/

Wow, this is interesting, thank you! I did not know that you can fire events from scripts.
