### ISSUE TITLE
alexapy must be reinstalled frequently

### ISSUE THREAD

**Issue by arrrghhh** [custom-components/alexa_media_player#1965]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

I believe whenever HA is updated, I have to manually reinstall alexapy per the FAQ.

Is there a way to automate this so I don't always have to install alexapy?

Can also recreate failure by doing a docker stop / docker rm on the container and then spinning up a new container.

**To Reproduce**

Update HA.  Error in logs about alexapy missing.  Follow directions from FAQ for docker container (exec /bin/bash, pip3 install aleaxapy).  Restart HA, problem solved.

**Expected behavior**

Each time HA is updated, alexapy should automatically reinstall itself.

**System details**

- Home-assistant (version): 2023.6.1
- alexa_media (version from `const.py` or HA startup):  4.6.4
- alexapy (version from `pip show alexapy` or HA startup): 1.26.8
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) Y

**Logs**

Unable to install package alexapy==1.26.8: ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: 'INSTALLER' Check the permissions. WARNING: You are using pip version 22.0.4; however, version 23.1.2 is available. You should consider upgrading via the '/lsiopy/bin/python3 -m pip install --upgrade pip' command.
Unable to install package alexapy==1.26.8: WARNING: Ignoring invalid distribution -iofiles (/lsiopy/lib/python3.11/site-packages) WARNING: Ignoring invalid distribution -iofiles (/lsiopy/lib/python3.11/site-packages) WARNING: Ignoring invalid distribution -iofiles (/lsiopy/lib/python3.11/site-packages) WARNING: Ignoring invalid distribution -iofiles (/lsiopy/lib/python3.11/site-packages) ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: 'INSTALLER' Check the permissions. WARNING: Ignoring invalid distribution -iofiles (/lsiopy/lib/python3.11/site-packages) WARNING: Ignoring invalid distribution -iofiles (/lsiopy/lib/python3.11/site-packages) WARNING: Ignoring invalid distribution -iofiles (/lsiopy/lib/python3.11/site-packages) WARNING: You are using pip version 22.0.4; however, version 23.1.2 is available. You should consider upgrading via the '/lsiopy/bin/python3 -m pip install --upgrade pip' command.
Unable to install package alexapy==1.26.8: WARNING: Ignoring invalid distribution -iofiles (/lsiopy/lib/python3.11/site-packages) WARNING: Ignoring invalid distribution - (/lsiopy/lib/python3.11/site-packages) WARNING: Ignoring invalid distribution -iofiles (/lsiopy/lib/python3.11/site-packages) WARNING: Ignoring invalid distribution - (/lsiopy/lib/python3.11/site-packages) WARNING: Ignoring invalid distribution -iofiles (/lsiopy/lib/python3.11/site-packages) WARNING: Ignoring invalid distribution - (/lsiopy/lib/python3.11/site-packages) WARNING: Ignoring invalid distribution -iofiles (/lsiopy/lib/python3.11/site-packages) WARNING: Ignoring invalid distribution - (/lsiopy/lib/python3.11/site-packages) ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: 'INSTALLER' Check the permissions. WARNING: Ignoring invalid distribution -iofiles (/lsiopy/lib/python3.11/site-packages) WARNING: Ignoring invalid distribution - (/lsiopy/lib/python3.11/site-packages) WARNING: Ignoring invalid distribution -iofiles (/lsiopy/lib/python3.11/site-packages) WARNING: Ignoring invalid distribution - (/lsiopy/lib/python3.11/site-packages) WARNING: Ignoring invalid distribution -iofiles (/lsiopy/lib/python3.11/site-packages) WARNING: Ignoring invalid distribution - (/lsiopy/lib/python3.11/site-packages) WARNING: You are using pip version 22.0.4; however, version 23.1.2 is available. You should consider upgrading via the '/lsiopy/bin/python3 -m pip install --upgrade pip' command.

Setup failed for custom integration alexa_media: Requirements for alexa_media not found: ['alexapy==1.26.8'].

**Additional context**

Perhaps I'm missing a config somewhere, entirely possible - I just keep having issues with this integration breaking, and each time I've fixed it by logging into the Docker container and running `pip3 install alexapy`.  Running HA in the official Docker container.  Tried to restart the Docker container, cannot reproduce issue.  Was only able to reproduce by rm'ing the container and starting a new one up.

**Comment by jameshcooper** [comment]
Please post as a HA - Docker issue in the official.  

The permission installing the packages in the container isn't due to alexapy, and occurs with other packages after upgrading HA.

**Comment by arrrghhh** [comment]
Huh, OK I can try - I just thought HACS or alexa_media isn't really supported by them so they will basically send me back here.

**Comment by alandtse** [comment]
The failure to install dependencies after update is a HA issue. We don't handle that code for dependency installation and the root cause is HA wipes all non core dependencies on update. Now HA is justified to treat custom components as second class but that's not my problem nor is it solvable from AMP because it's not even running yet because it doesn't have it's dependencies. That's the HA design. You need to install manually.
