### ISSUE TITLE
Feature Request: Alexa Temperature (Echo Plus Gen2)

### ISSUE THREAD

**Issue by Dielee** [custom-components/alexa_media_player#197]
Hello Guys, 

is it possible to get the temperature from Echo Plus Gen2 into HA ? 
Would be nice if this would work!

In the app it looks like this: 

![Screenshot_2019-05-28-08-13-33-933_com amazon dee app](https://user-images.githubusercontent.com/45101649/58455180-22d81080-8121-11e9-832a-954247d40813.png)

EDIT: I reverse engineered the alexa app. The endpoint from the temperature data is: `https://alexa.amazon.de/api/phoenix/state`

The cUrl fetch from charles works and looks like this:
`curl -H 'Cookie: x-amzn-dat-gui-client-v=1.24.205655.0; sid=; lc-acbde=de_DE; csrf=XXX; session-id-time=2082787201l; session-token="XXX"; session-id=XXX; ubid-acbde=XXX; x-acbde="XXX"; at-acbde="XXX"; sess-at-acbde="XXX";csrf=XXX' -H 'Accept: application/json; charset=utf-8' -H 'x-amzn-RequestId: XXX' -H 'User-Agent: PitanguiBridge/2.2.271281.0-[PLATFORM=Android][MANUFACTURER=Xiaomi][RELEASE=9][BRAND=Xiaomi][SDK=28][MODEL=MIX 3]' -H 'csrf: XXX' -H 'Accept-Language: de-DE' -H 'Cache-Control: no-cache' -H 'Content-Type: application/json; charset=utf-8' -H 'Host: alexa.amazon.de' --data-binary '{"stateRequests":[{"entityId":"AAA_SonarCloudService_XXX","entityType":"APPLIANCE"}]}' --compressed 'https://alexa.amazon.de/api/phoenix/state'`

Payload is:
```

{
  "deviceStates": [
    {
      "entity": {
        "entityId": "AAA_SonarCloudService_XXX",
        "entityType": ""
      },
      "capabilityStates": [
        "{\"namespace\":\"Alexa.TemperatureSensor\",\"name\":\"temperature\",\"value\":{\"value\":23,\"scale\":\"CELSIUS\"},\"timeOfSample\":\"2019-05-28T08:26:56.997Z\",\"uncertaintyInMilliseconds\":0,\"deepQuery\":true,\"timeOfStateChange\":\"\"}",
        "{\"namespace\":\"Alexa.AcousticEventSensor\",\"name\":\"glassBreakDetectionState\",\"value\":{\"value\":\"NOT_DETECTED\"},\"timeOfSample\":\"2018-12-10T05:28:01.283Z\",\"uncertaintyInMilliseconds\":10000,\"deepQuery\":true,\"timeOfStateChange\":\"\"}",
        "{\"namespace\":\"Alexa.AcousticEventSensor\",\"name\":\"detectionModes\",\"value\":{\"smokeAlarm\":{\"overallMode\":\"DISABLED\",\"cloudVerificationMode\":\"DISABLED\"},\"glassBreak\":{\"overallMode\":\"DISABLED\",\"cloudVerificationMode\":\"DISABLED\"}},\"timeOfSample\":\"2018-12-10T05:28:01.28Z\",\"uncertaintyInMilliseconds\":0,\"deepQuery\":true,\"timeOfStateChange\":\"\"}",
        "{\"namespace\":\"Alexa.AcousticEventSensor\",\"name\":\"smokeAlarmDetectionState\",\"value\":{\"value\":\"NOT_DETECTED\"},\"timeOfSample\":\"2018-12-10T05:28:01.283Z\",\"uncertaintyInMilliseconds\":10000,\"deepQuery\":true,\"timeOfStateChange\":\"\"}",
        "{\"namespace\":\"Alexa.ModeIndicator\",\"name\":\"securityMode\",\"value\":\"DISABLED\",\"timeOfSample\":\"1970-01-01T00:00:00Z\",\"uncertaintyInMilliseconds\":0,\"deepQuery\":true,\"timeOfStateChange\":\"\"}",
        "{\"namespace\":\"Alexa.AcousticEventSensor\",\"name\":\"overallMode\",\"value\":\"DISABLED\",\"timeOfSample\":\"2018-12-10T05:28:01.279Z\",\"uncertaintyInMilliseconds\":0,\"deepQuery\":true,\"timeOfStateChange\":\"\"}"
      ],
      "error": null
    }
  ],
  "errors": []
}

```

**Comment by alandtse** [comment]
Any thoughts on the appropriate HA component for this? I'm leaning toward a sensor.  

One reason I'm hesitant to add is this requires polling which is something we spent time getting away from so we don't get throttled by Amazon.  If you enable `alexapy.alexawebsocket` debugging, you may be able to see if the Echo Plus is reporting temperature changes through the websocket connection.

**Comment by Dielee** [comment]
Yes, sensor sounds good. 

For now I'm polling my temperatures with a litte bash script and push the temperature via mqtt in my broker. This runs every 5 minutes for now more than 20 days without any issue. 

So, maybe amzon doesn't throlle an five minute poll intervall. 

But I will enable alexawebsocket debugging and looking for the temperature.

**Comment by Dielee** [comment]
Checked if alexapy.websocket reporting temperature, unfortunately it doesn't.

Debug output:
```
2019-06-19 11:20:35 DEBUG (Thread-3) [alexapy.alexawebsocket] Received WebSocket MSG.
2019-06-19 11:20:35 DEBUG (Thread-3) [alexapy.alexawebsocket] Received b'MSG 0x00000362 0x8aadf701 f 0x00000001 0x470f9e1c 0x00000277 GWM MSG 0x0000b479 0x0000005c urn:tcomm-endpoint:service:serviceName:DeeWebsiteMessagingService:domain:prod:realm:USAmazon 0x0000006e urn:tcomm-endpoint:device:customerId:XXXXT1JG9WDF:deviceType:ALEGCNGL9K0HM:deviceSerialNumber:-000067000 {"payload":"{\\"destinationUserId\\":\\"A3TALTT1JG9WDF\\",\\"mediaReferenceId\\":\\"XXXXX-XXX-4505-a056-afb4d0a4c5a4:1\\",\\"dopplerId\\":{\\"deviceSerialNumber\\":\\"XXXXX8362013E\\",\\"deviceType\\":\\"A18O6U1UQFJ0XK\\"},\\"error\\":false,\\"audioPlayerState\\":\\"PLAYING\\",\\"errorMessage\\":null}","commmand":"PUSH_AUDIO_PLAYER_STATE"}FABE'
```

**Comment by alandtse** [comment]
Do you see any link between the `entityId` and the Echo [device](https://alexa.amazon.com/api/devices-v2/device) (whether by serial or something else)? I'm not seeing any correlation between those in my system and the only link I can see it the `friendlyName` which isn't my first choice. I'm about to introduce sensors showing alarms, so we may be able to address this feature request.

**Comment by Dielee** [comment]
No, i don't see any link between entityId and the eco service. 
Checked mac and serial, nothing matches.

I think using the frienldy name is the only option.

**Comment by Dielee** [comment]
Any updates for this ? My solution stopped working..

**Comment by cristopher87** [comment]
I was searching exactly the same feature when I got into this. 
I also opened a forum thread:
https://community.home-assistant.io/t/amazon-echo-plus-temperature-sensor/162565
but seems there is no way at the moment. 
Why your solution stopped working?

**Comment by jaimemrjm** [comment]
The curl "way" does work fine for me, but it's a unstable reverse engineered solution. It would be nice to get a more elegant solution. Maybe it's possible to get a valid cookie as first step and to get the IdentityId as second step.

**Comment by aneisch** [comment]
> The curl "way" does work fine for me, but it's a unstable reverse engineered solution. It would be nice to get a more elegant solution. Maybe it's possible to get a valid cookie as first step and to get the IdentityId as second step.

How are you retrieving the unique entityId for your device?

**Comment by jaimemrjm** [comment]
By using https://mitmproxy.org/ with an iOS client.
