### ISSUE TITLE
Echo Devices show up as Unavailable

### ISSUE THREAD

**Issue by Starf0x** [custom-components/alexa_media_player#1985]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

I've installed this integration, and after everything went fine, and then a extra reboot, all the echo devices show up as Unavailable.

**To Reproduce**

1. Go to HACS
2. Click on Integrations
3. Add Alexa Media Player
4. Reboot
5. goto settings > devices and services
6. add integration > Alexa Media Player and follow the steps
7. Select at the end the Echo Devices
8. Reboot
9. goto settings > devices and services
10. Click Alexa Media Player
11. Click on Devices and select 1 device
12. It shows Unavailable

**Expected behavior**

Available devices

**Screenshots**

![image](https://github.com/custom-components/alexa_media_player/assets/920981/e1ff07a5-c742-412b-922f-76c600b200f9)

**System details**

Home Assistant 2023.7.2 
Supervisor 2023.07.1 
Operating System 10.3 
Frontend 20230705.1 - latest 

- alexa_media > latest: 4.6.5
- Amazon [2FA is enabled] Is Enabled

**Logs**
This error originated from a custom integration.

Logger: alexapy.alexalogin
Source: custom_components/alexa_media/__init__.py:327
Integration: Alexa Media Player (documentation, issues)
First occurred: 2:45:36 PM (2 occurrences)
Last logged: 3:03:29 PM

Domain amazon.com does not match reported account domain https://www.amazon.co.uk; functionality is not likely to work, please fix

**Comment by alandtse** [comment]
Use the UK domain instead. I'm not sure how to make the error message clearer but happy to take suggestions.
