### ISSUE TITLE
Map product codes to model names

### ISSUE THREAD

**Issue by lymanepp** [custom-components/alexa_media_player#1988]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**
User is presented with product codes (e.g., ECHO A2DS1Q2TPDJ48U) instead of model names (e.g., Echo Dot Clock (Gen5)).

**Describe the solution you'd like**
It would be nice to have the actual product model instead of the product code

I found a nice mapping from the code to model in a Hubitat project at https://github.com/tonesto7/echo-speaks/blob/master/apps/echo-speaks.groovy

They don't have a license published so that might be an impediment until resolved.

**Describe alternatives you've considered**
None.

**Additional context**
None

**Comment by alandtse** [comment]
Happy to take a PR to add this. You might want to start with getting them to publish a license though.
