### ISSUE TITLE
Device not compatible with this command. Only for covers

### ISSUE THREAD

**Issue by wilotas** [custom-components/alexa_media_player#1991]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Hi, 

3 days ago I noticed Alexa is not recognizing voice commands for cover devices. For instance, "Please Alexa, cover at 50%" always returns a voice message from Alexa "This command is not compatible". 

It has been working for 3 years. All cover devices are shelly relays.

**To Reproduce**

Just saying one voice command for covers to Alexa.

**Expected behavior**

Alexa performs the action.

**Screenshots**

**System details**

- Home-assistant (version): Home Assistant 2023.7.3
- alexa_media (version from `const.py` or HA startup): 4.6.5
sion from `pip show alexapy` or HA startup):

**Additional context**

All other voice commands work without problem.

**Comment by alandtse** [comment]
This component has nothing to do with how Alexa responds to your voice. Please contact Amazon.
