### ISSUE TITLE
Device entity States not updating 

### ISSUE THREAD

**Issue by colinnewman2000** [custom-components/alexa_media_player#1992]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

The states for devices are not updating. It seems to be all sates EXCEPT for the volume, including DND, Next Alarm, Next Timer etc.

A restart of HA or a reload of the Integration picks up the state changes correctly. 

**To Reproduce**

1. Set an Alarm on an Amazon device (or change the DND setting for example)
2. In HA, open the associated device and look at the entities, or use Developer Tools to look up the Entity.
3. It will be seen that the state has not changed. 
4. Either a restart of HA or a reload of the integration followed by a repeat of step 2 above, will show the entity state correctly. 

**Expected behavior**

When changing something on the Amazon device, it used to reflect almost immediately in the HA entity state. 

**Screenshots**

Can be provided if needed. 

**System details**

- Home-assistant (version): 2023.7
- alexa_media (version from `const.py` or HA startup): 4.6.5
- alexapy (version from `pip show alexapy` or HA startup): WARNING: Package(s) not found: alexapy
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) Yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).
[home-assistant_alexa_media_2023-08-01T16-26-55.225Z.log](https://github.com/custom-components/alexa_media_player/files/12231910/home-assistant_alexa_media_2023-08-01T16-26-55.225Z.log)

**Additional context**

**Comment by fefris** [comment]
Have the exact same issue. The states do not update, i have been playing Ken loggins for about 18 hours at this point according to Home Assistant... I have not ;-)

Seem that things like play and pause still work on my Echo pop, but nothing ever updates in the interface, the pause button never turns to a play after clicking, the playing state never changes, the media picture never changes on song change.

**Comment by tvizzotto** [comment]
Yep, another one here. I am able to change the volume on Alexa using HA dashboard, so I can confirm Alexa Media Player is connected and working.
But when I set up a timer or alarm on Alexa, the "next alarm" entitie does not change in HA (keep showing "unknow"). It only change when I perform a reload on Alexa Media Player integration.

**Comment by prankousky** [comment]
Same here.

When I set a timer, it will not show as `<name>_next_timer`. If I manually reload the integration, the timer **will** show up. But otherwise it stays `unknown`.

**Comment by dpgh947** [comment]
I too am seeing timer updates not reaching HA, and I am also seeing very odd behaviour in the maintenance of the "last_called" attribute, I use to see which device was last spoken to. It stopped updating reliably for me yesterday. Sometimes an update will eventually get through after several minutes. If I monitor all the media_player entities in node red and speak to a device, I see updates to that device come through, but it is not updating last_called on those updates. So all my custom alexa phrases which cause HA to respond with TTS spoken to the appropriate device are suddenly useless.

**Comment by colinnewman2000** [comment]
I have worked around this for now. For those interested who don't already know, you can restart the Integration on a regular basis using an automation. Not much use for real time things such as timers, but for Alarms that are set less frequently it could be useful. 

Use the homeassistant.reload_config_entry service and pass the config ID of the Integration to it. 

The Config ID can be found by going to the Integrations Page, opening the integration by clicking on it's name, and then clicking on either devices or entities. It will look something like this:

https://stuffandstuff.duckdns.org/config/devices/dashboard?historyBack=1&config_entry=**_<the config ID of the integration>_**

**Comment by chrishas35** [comment]
I am seeing this with Glow lights (device connected via Echo).  I can tell HA to turn off a light and it immediately does so in person, but the state in HA ticks back on.  Curiously, I also have Hue devices connected through Alexa and they not only respond immediately, but the state updates in HA correctly.

A glow device that does not update state produces the following debug logs:
```
2023-08-02 17:16:13.310 DEBUG (MainThread) [alexapy.alexaapi] a****n@c******************t: static PUT: https://alexa.amazon.com/api/phoenix/state returned 200:OK:application/json
2023-08-02 17:16:13.310 DEBUG (MainThread) [alexapy.alexaapi] a****n@c******************t: set_light_state response: {'controlResponses': [{'code': 'SUCCESS', 'message': None, 'data': None, 'entityId': 'bbbd2ad8-c6be-4cad-956e-e2b86ab83098'}], 'errors': []} for data: {"controlRequests": [{"entityId": "bbbd2ad8-c6be-4cad-956e-e2b86ab83098", "entityType": "ENTITY", "parameters": {"action": "turnOff"}}]}
```

A request to turn on a Hue bulb which works correctly updates state produces the following:
```
023-08-02 17:17:17.879 DEBUG (MainThread) [alexapy.alexaapi] a****n@c******************t: static PUT: https://alexa.amazon.com/api/phoenix/state returned 200:OK:application/json
2023-08-02 17:17:17.879 DEBUG (MainThread) [alexapy.alexaapi] a****n@c******************t: set_light_state response: {'controlResponses': [{'code': 'SUCCESS', 'message': None, 'data': None, 'entityId': '1db928df-6661-43eb-a6b0-302f2bcc754d'}], 'errors': []} for data: {"controlRequests": [{"entityId": "1db928df-6661-43eb-a6b0-302f2bcc754d", "entityType": "ENTITY", "parameters": {"action": "turnOn"}}]}
2023-08-02 17:17:17.879 DEBUG (MainThread) [custom_components.alexa_media.alexa_entity] Coordinator data for 1********************************54d is too old to be returned.
2023-08-02 17:17:17.879 DEBUG (MainThread) [custom_components.alexa_media.alexa_entity] Coordinator data for 1********************************54d is too old to be returned.
2023-08-02 17:17:17.880 DEBUG (MainThread) [custom_components.alexa_media.alexa_entity] Coordinator data for 1********************************54d is too old to be returned.
```

Consistently I see the "Coordinator data for ... too old to be returned messages" after a Hue request, but not on the Glows.

**Comment by UglyBob79** [comment]
Just installed this and same for me, all my alwxa media players seem stuck in their initial states.

**Comment by zgadson** [comment]
+1 Unfortunately I don't have anything to add, except that the thing is happening to me even after a complete reinstall of Home Assistant on my RPi4. Alexa devices will always update to the correct status upon rebooting the Alexa integration itself, but no status changes happen beyond that.

**Comment by WhimsySpoon** [comment]
> I have worked around this for now. For those interested who don't already know, you can restart the Integration on a regular basis using an automation. Not much use for real time things such as timers, but for Alarms that are set less frequently it could be useful.
> 
> Use the homeassistant.reload_config_entry service and pass the config ID of the Integration to it.
> 
> The Config ID can be found by going to the Integrations Page, opening the integration by clicking on it's name, and then clicking on either devices or entities. It will look something like this:
> 
> https://stuffandstuff.duckdns.org/config/devices/dashboard?historyBack=1&config_entry= **the config ID of the integration**

Good work-around, but please use this option sparingly. An error in a script or automation could result in a significant increase of traffic to Amazon which may cause them to create additional headaches.

For this particular issue, it's happened in the past and has been a result of Amazon changing their API, or for users in the EU such as myself, the websocket connection temporarily stopped working due to issues on Amazon's side.

**Comment by alandtse** [comment]
For media player state, please provide a log showing when you issued some sort of voice command and please point out the timestamp to track how the component responds.

If you're talking about timer states, that's already discussed in #1976 so track that.

**Comment by colinnewman2000** [comment]
This is related to timer states and I have subscribed to #1976 and #1974 which also seems to be related.

My apologies for raising a new issue unnecessarily. Have now closed this thread and suggest other subscribe to the above discussions.
