### ISSUE TITLE
last_called_summary - not updating status

### ISSUE THREAD

**Issue by FaboThePlayer** [custom-components/alexa_media_player#1993]
**Describe the bug**
Sometimes it won't automatically update last_called_summary for a while. Using service "alexa_media.update_last_called" helps, to show last called command, but when I say another command, I just need to press call service again. It's not updating only for last_called_summary. For example, when I say "alexa volume up", the volume_level gets up, but last_called_summary remains the same.

**System details**
Amazon 2FA is enabled, I'm using the newest version of HA 2023.07.3 however the problem persists for a while. Addon is on version 4.6.4.

**Comment by Risbo6** [comment]
I have the exact same issue since today (I used to have this issue in the past but a HA reboot would fix it, it's not the case anymore).
Forcing an update through the service successfully update the last_called_summary.

This is a bit problematic for me since I was checking a change in this field to trigger my automations !

**Comment by dpgh947** [comment]
It's not updating "last_called" reliably or even at all either, so any TTS responses to custom commands invariably go to the wrong device, since yesterday for me.

**Comment by FaboThePlayer** [comment]
For a weird workaround until they repair the issue I created kind of dumb script, which repeatedly runs service to force last call update for every 5 secs.
![Screenshot_2023-08-04-19-23-12-682_io homeassistant companion android](https://github.com/custom-components/alexa_media_player/assets/111151942/bde744e4-73ea-4834-8b75-6213e34e1d33)

**Comment by npa-homeassistant** [comment]
FWIW I'm seeing a very similar problem is trying to identify the last_called device to use in responses.

**Comment by dpgh947** [comment]
> FWIW I'm seeing a very similar problem is trying to identify the last_called device to use in responses.

If you use node red, try this, it is working well for me. It watches all media_player entity updates using a trigger:state node, and whenever it sees one that is NOT already marked last_called, it calls the update_last_called service. It has two delay filters, the first only allows 1 message through every 5 seconds so it doesn't issue loads of service calls (or end up in a never ending loop), and the second one delays 2 seconds, I found this was needed to allow amazon to update the info before the service call.

![image](https://github.com/custom-components/alexa_media_player/assets/75258259/e5663787-c7d3-4b10-b3fa-c06a06e83e77)

I hope this export works, I took out my own server settings before I exported this so that it is ready to be customised:

```
[{"id":"79671212adfba56d","type":"trigger-state","z":"0bbbfaa0d8aeaa39","name":"Alexa last called watcher","server":"","version":2,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":"Last Alexa Update Control"},{"property":"icon","value":""}],"entityid":"media_player.","entityidfiltertype":"substring","debugenabled":false,"constraints":[{"targetType":"this_entity","targetValue":"","propertyType":"property","propertyValue":"new_state.attributes.last_called","comparatorType":"is_not","comparatorValueDatatype":"bool","comparatorValue":"true"}],"inputs":0,"outputs":2,"customoutputs":[],"outputinitially":false,"state_type":"str","enableInput":false,"x":150,"y":1960,"wires":[["88be33391b521e3e"],[]],"info":"I found that using regex to filter the media\r\nplayer entities was much slower than using\r\nsubstring"},{"id":"88be33391b521e3e","type":"delay","z":"0bbbfaa0d8aeaa39","name":"","pauseType":"rate","timeout":"5","timeoutUnits":"seconds","rate":"1","nbRateUnits":"5","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":true,"allowrate":false,"outputs":1,"x":400,"y":1960,"wires":[["9cda3bfa6fae77d3"]]},{"id":"9cda3bfa6fae77d3","type":"delay","z":"0bbbfaa0d8aeaa39","name":"","pauseType":"delay","timeout":"2","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"allowrate":false,"outputs":1,"x":600,"y":1960,"wires":[["d3aa307e77a7bf4c"]]},{"id":"d3aa307e77a7bf4c","type":"api-call-service","z":"0bbbfaa0d8aeaa39","name":"","server":"","version":5,"debugenabled":false,"domain":"alexa_media","service":"update_last_called","areaId":[],"deviceId":[],"entityId":[],"data":"","dataType":"jsonata","mergeContext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":850,"y":1960,"wires":[[]]}]
```

**Comment by npa-homeassistant** [comment]
> > FWIW I'm seeing a very similar problem is trying to identify the last_called device to use in responses.
> 
> If you use node red, try this, it is working well for me. It watches all media_player entity updates using a trigger:state node, and whenever it sees one that is NOT already marked last_called, it calls the update_last_called service. It has two delay filters, the first only allows 1 message through every 5 seconds so it doesn't issue loads of service calls (or end up in a never ending loop), and the second one delays 2 seconds, I found this was needed to allow amazon to update the info before the service call.
> 
> ![image](https://user-images.githubusercontent.com/75258259/258581518-e5663787-c7d3-4b10-b3fa-c06a06e83e77.png)
> 
> I hope this export works, I took out my own server settings before I exported this so that it is ready to be customised:
> 
> ```
> [{"id":"79671212adfba56d","type":"trigger-state","z":"0bbbfaa0d8aeaa39","name":"Alexa last called watcher","server":"","version":2,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":"Last Alexa Update Control"},{"property":"icon","value":""}],"entityid":"media_player.","entityidfiltertype":"substring","debugenabled":false,"constraints":[{"targetType":"this_entity","targetValue":"","propertyType":"property","propertyValue":"new_state.attributes.last_called","comparatorType":"is_not","comparatorValueDatatype":"bool","comparatorValue":"true"}],"inputs":0,"outputs":2,"customoutputs":[],"outputinitially":false,"state_type":"str","enableInput":false,"x":150,"y":1960,"wires":[["88be33391b521e3e"],[]],"info":"I found that using regex to filter the media\r\nplayer entities was much slower than using\r\nsubstring"},{"id":"88be33391b521e3e","type":"delay","z":"0bbbfaa0d8aeaa39","name":"","pauseType":"rate","timeout":"5","timeoutUnits":"seconds","rate":"1","nbRateUnits":"5","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":true,"allowrate":false,"outputs":1,"x":400,"y":1960,"wires":[["9cda3bfa6fae77d3"]]},{"id":"9cda3bfa6fae77d3","type":"delay","z":"0bbbfaa0d8aeaa39","name":"","pauseType":"delay","timeout":"2","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"allowrate":false,"outputs":1,"x":600,"y":1960,"wires":[["d3aa307e77a7bf4c"]]},{"id":"d3aa307e77a7bf4c","type":"api-call-service","z":"0bbbfaa0d8aeaa39","name":"","server":"","version":5,"debugenabled":false,"domain":"alexa_media","service":"update_last_called","areaId":[],"deviceId":[],"entityId":[],"data":"","dataType":"jsonata","mergeContext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":850,"y":1960,"wires":[[]]}]
> ```

I don't use Node Red (yet) but I have also come up with a workaround which seems to work reliably. This is the script which I'm now using which is currently working well.

```
alias: Alexa Response
sequence:
  - service: alexa_media.update_last_called
    data: {}
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
  - service: notify.alexa_media
    data:
      target: " {{ states('sensor.last_alexa') }} "
      message: " {{ message }} "
      data:
        type: tts
mode: single
icon: mdi:speaker-play
```
Basically, I call the script with a message and the script first forces an update, waits (currently) 500ms and then outputs the message.

**Comment by alandtse** [comment]
I need logs showing an interaction and what the component is doing. As for the OP, you cut out too much of the template. Don't do that again.

**Comment by alandtse** [comment]
Actually, changed my mind. Closing for failure to search for duplicates.
