### ISSUE TITLE
Alexa Media Player Integration Fails to Install

### ISSUE THREAD

**Issue by rereloluwa89** [custom-components/alexa_media_player#1996]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Alexa Media Player integration fails with a message "ERROR" 

**To Reproduce**

1. Setup a new configuration
2. Entered my configuration (email, password, region=amazon.com, my built-in 2FA secret)
3. Click Submit to validate config
4. Verify 2FA code is valid / in-sync with 2FA app
5. Login via amazon.com / pass 2FA step
6. Configuration errors out and integration is never added.

**Expected behavior**
custom integration would be configured, and added to my list of integration.

**Screenshots**

![image](https://github.com/custom-components/alexa_media_player/assets/138394359/aab4f058-e186-4da1-8d96-d6ff882eeb56)

![image](https://github.com/custom-components/alexa_media_player/assets/138394359/bbe73314-55b9-4ee5-9477-1a9dc33019ac)

![image](https://github.com/custom-components/alexa_media_player/assets/138394359/09596ee6-2418-4918-9a9b-aded1ee76792)

**System details**

- Home-assistant (version):
- alexa_media (version from `const.py` or HA startup): 4.6.5
- alexapy (version from `pip show alexapy` or HA startup): 1.26.8
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : yes

**Logs**
Logger: zigpy_znp.uart
Source: /usr/local/lib/python3.11/site-packages/zigpy_znp/uart.py:74
First occurred: 8:12:52 PM (4 occurrences)
Last logged: 8:13:01 PM

Received an exception while passing frame to API: TransportFrame(payload=GeneralFrame(header=CommandHeader(id=0xB2, subsystem=Subsystem.ZDO, type=CommandType.AREQ), data=b'\x5E\x82\x84'))
Received an exception while passing frame to API: TransportFrame(payload=GeneralFrame(header=CommandHeader(id=0xB2, subsystem=Subsystem.ZDO, type=CommandType.AREQ), data=b'\x05\x16\x84'))
Received an exception while passing frame to API: TransportFrame(payload=GeneralFrame(header=CommandHeader(id=0xB2, subsystem=Subsystem.ZDO, type=CommandType.AREQ), data=b'\xD5\xF2\x84'))
Received an exception while passing frame to API: TransportFrame(payload=GeneralFrame(header=CommandHeader(id=0xB2, subsystem=Subsystem.ZDO, type=CommandType.AREQ), data=b'\xEA\x11\x84'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/zigpy_znp/types/commands.py", line 417, in from_frame
    params[param.name], data = param.type.deserialize(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zigpy/types/struct.py", line 302, in deserialize
    value, data = field.type.deserialize(data)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zigpy/types/basic.py", line 190, in deserialize
    raise ValueError(f"Data is too short to contain {byte_size} bytes")
ValueError: Data is too short to contain 1 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/zigpy_znp/uart.py", line 72, in data_received
    self._api.frame_received(frame.payload)
  File "/usr/local/lib/python3.11/site-packages/zigpy_znp/api.py", line 830, in frame_received
    command = command_cls.from_frame(frame, align=self.nvram.align_structs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zigpy_znp/types/commands.py", line 424, in from_frame
    raise ValueError(
ValueError: Frame data is truncated (parsed {'Src': 0x825E, 'Status': <Status.NOT_SUPPORTED: 132>}), required parameter remains: Param(name='Routes', type=<class 'zigpy.zdo.types.Routes'>, description='Routes', optional=False)

![image](https://github.com/custom-components/alexa_media_player/assets/138394359/7e9f83e1-67a2-4f56-ae15-29ceadadf01a)

**Comment by alandtse** [comment]
Those logs are unrelated to the install. You need to [enable logging](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component) and then try to install.

**Comment by alandtse** [comment]
I'll close this out; we can reopen once you are able to generate some logs.
