### ISSUE TITLE
Send notification to group of speaker not work anymore.

### ISSUE THREAD

**Issue by wes1993** [custom-components/alexa_media_player#1997]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

When i try to send a notification to notify.alexa_media_all nothing happen.

alexa_media_all is a group of all my speakers created in the alexa app.

**To Reproduce**

Send a notification to group of speaker instead of one speker.

**Expected behavior**

All speaker tell the notification in the same time.

**Screenshots**

**System details**

- Home-assistant (version): Home Assistant 2023.8.1
- alexa_media (version from `const.py` or HA startup): V. 4.6.5
- alexapy (version from `pip show alexapy` or HA startup): 1.26.8
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : y

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).
Unfortunately also with debug enabled no log...

**Additional context**

**Comment by smartmints** [comment]
I am having a similar issue. The integration is "failed setup, will retry". " Connection error during login. I am on Home Assistant version 2023.7.3. Here is a part of the log A connection error occurred: An exception of type ClientConnectorError occurred. Arguments: (ConnectionKey(host='alexa.amazon.in', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=-1065991443596278329), gaierror(-5, 'Name has no usable address'))

**Comment by smartmints** [comment]
I am having an issue which I think is related with this post. Alexa is able to execute scripts from home assistant when I tell it to, but I cannot send tts or do volume control from home assistant. 
Home Assistant version : 2023.7.3 
OS : 10.3
Log : 
 alexaapi.get_state((<alexapy.alexaapi.AlexaAPI object at 0x7fb560139ad0>,), {}): A connection error occurred: An exception of type ClientConnectorError occurred. Arguments: (ConnectionKey(host='alexa.amazon.in', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0x7fb572488a70>, proxy=None, proxy_auth=None, proxy_headers_hash=-1065991443596278329), gaierror(-5, 'Name has no usable address'))

**Comment by KyleStilkey** [comment]
I wanted to add to this as I am having the same issue, if I send a direct notification to the speaker group or a group alone it seems to work for me, if I say want to send it a a group I have set in my office and then another device in another room, the groups just refuse to work.

**Comment by smartmints** [comment]
For me the below is also not working.
`service: notify.alexa_media_beau_hall
data:
  message: this is test
  data:
    type: ttsservice: notify.alexa_media_beau_hall
data:
  message: this is test
  data:
    type: tts`

**Comment by smartmints** [comment]
I think my issue is unrelated to this. Will start a new issue since all the services the integration exposes are not working

**Comment by alandtse** [comment]
`TTS` cannot send to Alexa managed groups. You have to use `announce`. Please see the wiki. https://github.com/custom-components/alexa_media_player/wiki/Configuration%3A-Notification-Component#functionality

As for sending to multiple groups, please provide logs. I also don't know what "Doesn't Work" means. Does it play on the non-group device? The group? None? As the original issue will be closed, please feel free to open a new issue covering the permutation of group + device.
