### ISSUE TITLE
Annoucement no long works.

### ISSUE THREAD

**Issue by bindedig** [custom-components/alexa_media_player#2002]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

service: notify.alexa_media_everywhere
data:
  message: Dinner time
  data:
    announce: tts

No longer works, however;

service: notify.alexa_media_living_room_hub
data:
  message: Take you medicine
  data:
    data: tts

Does work.

**To Reproduce**

**Expected behavior**

Up until about 3 weeks ago the Dinner time would play 'annouce' on all speakers in the 'Everywhere' channel. Now there is nothing.

**Screenshots**

N/A

**System details**

- Home-assistant (version): Home Assistant 2023.8.3 Supervisor 2023.08.1 Operating System 10.5 Frontend 20230802.1 - latest
- alexa_media (version from `const.py` or HA startup): Not sure how to find that
- alexapy (version from `pip show alexapy` or HA startup): Not sure how to find that
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). Y

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by alandtse** [comment]
TTS has never worked for everywhere. You must use announce for WHA groups. Please reference the wiki. https://github.com/custom-components/alexa_media_player/wiki/Configuration%3A-Notification-Component#functionality
