### ISSUE TITLE
Cannot control fire tv and see status changes

### ISSUE THREAD

**Issue by Nik92-github** [custom-components/alexa_media_player#2003]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

<Unable to control Fire TV from the alexa_media_player device list, but all the echo devices can be controlled>

**To Reproduce**

1. Go to 'Integrations'
2. Click on 'Alexa Media Player.'
3. Click on 'devices'
4. Select any 'Fire TV device'.
5. In the Controls section, Fire TV status is shown as standby even though the TV is ON and doesn't change when you click on it.

**Expected behavior**

Fire TV status should be updated to reflect current status and should change when clicked on from Controls section

**Screenshots**

See attached image
<img width="257" alt="Screenshot 2023-08-24 232726" src="https://github.com/custom-components/alexa_media_player/assets/116492522/b2a6751e-efa5-498d-8f69-297f20173b1f">

**System details**

- Home-assistant (version): 2023.8
- alexa_media (version from `const.py` or HA startup): 4.6.5
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : y

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

Echo devices behave as expected. Only Fire TV couldn't be controlled.

**Comment by alandtse** [comment]
Can you control it via the Alexa app?

**Comment by Nik92-github** [comment]
I cannot use Fire TV as a trigger for my routines in the alexa app. But I was able to switch on/off fire tv based on some other triggers. So yes, I was able to control it.

**Comment by alandtse** [comment]
Does it show up as a media player in the app with controls? I'm not talking about triggers. We can only emulate the app so if it's not supported in the app we can't do more.

**Comment by Nik92-github** [comment]
Oh, now i understand. No, I don't see it as a media player. So then I guess there's no way to control the fire tv then?? For example, see if it's off/on? I only want to use the status of Fire tv as a trigger in my HA automations.

**Comment by alandtse** [comment]
So yah, probably can't determine it's status. The status for the device comes from the media player which is whether it's playing etc. We may need to specifically exclude fire tv devices from populating the media player. I just don't recall if other functionality works for them like notifications. If they do get those, then perhaps we leave them in for those purposes. I'll leave this open as an enhancement request because maybe someone can find some other way the app reports the actual status and can do a PR, but otherwise I won't be doing anything else on it.

**Comment by tech2mar** [comment]
Same issue, can't control anything and the reporting is stuck.




![Screenshot_20230902_105507_Home Assistant.jpg](https://github.com/custom-components/alexa_media_player/assets/52455293/df1278a8-05b5-4353-b53d-6a282960f3dc)

**Comment by Nik92-github** [comment]
@alandtse , Alright. Thanks for the quick response. I ended up using the Android debug bridge integration for getting the Fire TV status.

**Comment by DanielRitter75** [comment]
I'got the same issue. Can't control the Fire TV Stick via this integration. But with Android debug bridge it works.
