### ISSUE TITLE
The installation proces is stuck on Loading next step for Alexa Media Player

### ISSUE THREAD

**Issue by victoroos** [custom-components/alexa_media_player#2015]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

The installation proces is stuck on Loading next step for Alexa Media Player

**To Reproduce**

(Alexa didn't work anymore so, I should have checked the FAQ first..):)
Remove the integration via HACS. Restart HA. Reinstall integration via HACS. Start setup.
Get the 2FA key, set the domain (I didn't change it from the default)

**Expected behavior**

**Screenshots**

**System details**

- Home-assistant (version): 2023.7.0
- alexa_mediav4.6.5
- alexapy  couldn't find
- Amazon [2FA is enabled] yes

**Logs**
Please provide only error I could find was:
23-09-06 12:07:19.117 WARNING (MainThread) [alexapy.alexalogin] Error creating TOTP; d**************ase likely invalid

**Additional context**

**Comment by alandtse** [comment]
The error is saying you're trying to put something weird into the "Built in 2FA key" field. That should be like 60 characters. If you're doing your 2FA key, wait till it asks you. However, without more details on where it's stuck loading, I'm not sure I can help. See how to enable logging here. https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component

**Comment by alandtse** [comment]
Without more info, I assume it's this. https://github.com/custom-components/alexa_media_player/issues/1788#issuecomment-1368308162.
