### ISSUE TITLE
Can't see the current volume but volume_set works

### ISSUE THREAD

**Issue by rafareusch** [custom-components/alexa_media_player#2018]
**Describe the bug**

In one of my HA instances, the alexa media player, alexa entity wont show the volume commands (see screenshot) but still accept volume set service commands.

**To Reproduce**

1. Play media using spotify in alexa speaker 
2. increase volume of spotify player (which increases the volume of the alexa)
3. no volume/source information is shown on card

**Expected behavior**

Like every other instance I have, I expect volume controls are shown normamly
Issue:
![image](https://github.com/custom-components/alexa_media_player/assets/12521587/066f9f1e-092b-4ae7-8d83-bb2d34880094)

Expected:
![image](https://github.com/custom-components/alexa_media_player/assets/12521587/60dd0778-b366-47a3-b3db-2c5d5f48b991)

**System details**

- Home-assistant (version):  2023.8.1
- alexa_media (version from `const.py` or HA startup): 4.6.5
- alexapy (version from `pip show alexapy` or HA startup): 1.26.8
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). Yes

**Logs**
[logs.txt](https://github.com/custom-components/alexa_media_player/files/12555494/logs.txt)

**Additional Context**
Tried manytimes reloading integration, updating entity manually, or restarting Ha or Host

**Comment by AndreGraca3** [comment]
same

**Comment by popy2k14** [comment]
+1
Sadly it has Todo with changes Amazon has made.
No sensor really works 😕

**Comment by Wibias** [comment]
Yup... Messed up my gradually increaded volume automation..

**Comment by drened** [comment]
Same Problem

**Comment by ziolelle** [comment]
same problem

**Comment by danneliezer** [comment]
here too...

**Comment by M3d1c5** [comment]
me too

**Comment by alandtse** [comment]
Follow #1953 for update. Closing dupe.
