### ISSUE TITLE
missing translation key

### ISSUE THREAD

**Issue by Ludy87** [custom-components/alexa_media_player#2024]
the key for 'public_url' is not present in any translation, so only an empty field is displayed, which confuses the user (including me), please fix it, thanks.

**Comment by Ludy87** [comment]
@alandtse Sorry for the ping, but it's not a classic error.

**Comment by alandtse** [comment]
Ok, key should be in lokalise. We actually load the translations on each build so I'll wait a little bit for your fix to give people time to make updates.

**Comment by alandtse** [comment]
Actually, I went ahead and let the AI fill in a bunch. I'll push a release now
