### ISSUE TITLE
Weekday alarms showing up on weekends 

### ISSUE THREAD

**Issue by broyuken** [custom-components/alexa_media_player#2042]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Alarm set for weekdays shows up on weekends as well
**To Reproduce**

Create weekday alarm
Wait for Saturday 
See that alarm says it will go off on Saturday

**Expected behavior**
Alarm only shows up on weekdays

**Screenshots**

![image](https://github.com/custom-components/alexa_media_player/assets/1593391/113f2d03-a924-4437-a730-08705626b36c)

**System details**

- Home-assistant (version): 2023.9.3
- alexa_media (version from `const.py` or HA startup): 4.7.3
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled] yes
- (https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). :

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by broyuken** [comment]
Note, I updated to the latest version and my media player entities update immediately again, but the alarms aren’t correct.

**Comment by alandtse** [comment]
Closed by #2044
