### ISSUE TITLE
cannot import name 'formatargspec' from 'inspect'

### ISSUE THREAD

**Issue by dgarozzo** [custom-components/alexa_media_player#2049]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

When attempting to add integration, I am presented with the following error:

Error
Config flow could not be loaded: {"message":"Invalid handler specified"}

Looking in the logs, I see this:

Logger: homeassistant.config_entries
Source: config_entries.py:864
First occurred: 5:03:25 PM (1 occurrences)
Last logged: 5:03:25 PM

Error occurred loading flow for integration alexa_media: cannot import name 'formatargspec' from 'inspect' (/usr/local/lib/python3.11/inspect.py)

**To Reproduce**

I followed the FAQ to completely remove, and then I re-added from HACS. Clicked Add Inegration, and error message appears.

**Expected behavior**

Successful installation.

**Screenshots**

**System details**

- Home-assistant (version): Home Assistant 2023.9.2, Frontend 20230911.0 - latest
- alexa_media (version from `const.py` or HA startup): __version__ = "4.6.5"
- alexapy (version from `pip show alexapy` or HA startup): 1.27.4
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by alandtse** [comment]
Confirm the version of `wrapt` you have. HA is on python 3.11 requires 1.14.0 and above. 

```
pip list | grep wrapt
wrapt                            1.15.0
```

**Comment by dgarozzo** [comment]
wrapt 1.12.1.  I guess that's the problem, but I'm running HA from the stable docker tag. How could it be wrong there?

**Comment by dgarozzo** [comment]
Found another post or two about this. Looks like the manifest.json file for AMP says:

{
  "domain": "alexa_media",
  "name": "Alexa Media Player",
  "codeowners": ["@alandtse", "@keatontaylor"],
  "config_flow": true,
  "dependencies": ["persistent_notification", "http"],
  "documentation": "https://github.com/custom-components/alexa_media_player/wiki",
  "iot_class": "cloud_polling",
  "issue_tracker": "https://github.com/custom-components/alexa_media_player/issues",
  "loggers": ["alexapy", "authcaptureproxy"],
  "requirements": ["alexapy==1.27.4", "packaging>=20.3", "wrapt>=1.12.1"],
  "version": "4.6.5"
}

I change it to wrapt>=1.14.0, and it started up. Should probably change that in the source.

**Comment by alandtse** [comment]
HA should have chosen it because of python 3.11. Regardless, PRs are welcome.

**Comment by dgarozzo** [comment]
PR submitted

**Comment by alandtse** [comment]
Thanks!
