### ISSUE TITLE
'last_called_timestamp:'

### ISSUE THREAD

**Issue by oneseventhree** [custom-components/alexa_media_player#2052]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**
Feature request

**Describe the solution you'd like**
eg:
Change:
'last_called_timestamp: 1696216658724'
to
'last_called_timestamp: 2023-10-02 15:52:41.235132+11:00'

**Describe alternatives you've considered**
Templating it but I have no idea what those numbers are

**Additional context**
'media_position_updated_at:' has the right formatting
![image](https://github.com/custom-components/alexa_media_player/assets/15043282/47f4fad7-2dd2-4a3e-92a1-3511379fb128)

**Comment by guardianbs** [comment]
Try this in the Developer Tools - Template editor

{%set echo_time = state_attr('media_player.study_echo_dot', 'last_called_timestamp')|default(0)|string %}
{{(echo_time[0:10]~'.%0.6d'|format(echo_time[10:]|int(0)))|int(0)|timestamp_custom("%Y-%m-%d %H:%M:%S")}}

Adjust timestamp_custom format to suit your needs.

**Comment by oneseventhree** [comment]
> Try this in the Developer Tools - Template editor
> 
> {%set echo_time = state_attr('media_player.study_echo_dot', 'last_called_timestamp')|default(0)|string %} {{(echo_time[0:10]~'.%0.6d'|format(echo_time[10:]|int(0)))|int(0)|timestamp_custom("%Y-%m-%d %H:%M:%S")}}
> 
> Adjust timestamp_custom format to suit your needs.
> 
> (obviously replace 'media_player.study_echo_dot' with the name of your own echo device )

Thanks - I ended up doing: 
```
        {{ expand('media_player.alexa_sonos_beam', 'media_player.alexa_echo_show', 'media_player.alexa_echo_spot', 'media_player.alexa_echo_dot')
            | selectattr('attributes.last_called_timestamp', 'is_number')
            | sort(attribute='attributes.last_called_timestamp', reverse=true)
            | map(attribute='attributes.last_called_timestamp') | map('multiply', 0.001) | map('timestamp_custom', '%d/%m/%y %H:%M:%S') | first }} ```
