### ISSUE TITLE
Integration pulling in non-Alexa Sonos speakers as of HA 2023.10.0

### ISSUE THREAD

**Issue by billmoseley** [custom-components/alexa_media_player#2058]
**Describe the bug**

Today I upgraded to HA 2023.10.0 and had to reconfigure alexa_media_player and it now seems to bring in entities it didn't before -- namely all my older Sonos speakers that are not Alexa equipped.

For example, these are old Play:1s w/o Alexa.

<img width="812" alt="Screenshot 2023-10-04 at 15 14 41" src="https://github.com/custom-components/alexa_media_player/assets/2183629/1381ad7b-eec7-4d4a-8343-90b59bcab9f4">

**Update:**

I can see by calling https://alexa.amazon.com/api/devices-v2/device that Amazon is returning all my Sonos speakers and I assume that is because I have the Sonos skill installed on my Alexa account.

Should this integration pull in non-Alexa devices as entities?

These are the capabilities listed for that non-Alexa Sonos speaker in the image above:

```
    {
      "accountName": "Living Play1s",
      "appDeviceList": [
        
      ],
      "associatedUnitIds": null,
      "capabilities": [
        "I_HEART_RADIO",
        "AUDIO_PLAYER",
        "SIRIUSXM",
        "DEEZER",
        "APPLE_MUSIC",
        "REMINDERS",
        "TIDAL",
        "ADAPTIVE_LISTENING",
        "SUPPORTS_CONNECTED_HOME_CLOUD_ONLY",
        "PANDORA",
        "VOLUME_SETTING",
        "TUNE_IN",
        "CHANGE_NAME",
        "MUSIC_SKILL",
        "AMAZON_MUSIC"
      ],
```

A Sonos speaker that is Alexa-enabled looks like this:

```
      "capabilities": [
        "SOUND_SETTINGS",
        "SUPPORTS_LOCALE",
        "MULTI_WAKEWORDS_SUPPORTED",
        "EARCONS",
        "SIRIUSXM",
        "GOLDFISH",
        "TIMERS_ALARMS_NOTIFICATIONS_VOLUME",
        "SLEEP",
        "FAR_FIELD",
        "HANDS_FREE",
        "SET_LOCALE",
        "TIDAL",
        "KINDLE_BOOKS",
        "AUDIBLE",
        "SUPPORTS_CONNECTED_HOME_CLOUD_ONLY",
        "TUNE_IN",
        "CHANGE_NAME",
        "DEREGISTER_DEVICE",
        "SUPPORTS_LOCALE_SWITCH",
        "DIALOG_INTERFACE_VERSION",
        "MUSIC_SKILL",
        "SET_TIME_ZONE",
        "I_HEART_RADIO",
        "AUDIO_PLAYER",
        "DEEZER",
        "APPLE_MUSIC",
        "TIMERS_AND_ALARMS",
        "REMINDERS",
        "PERSISTENT_CONNECTION",
        "CUSTOM_ALARM_TONE",
        "DREAM_TRAINING",
        "ASCENDING_ALARM_VOLUME",
        "SPEECH_RECOGNIZER_USS",
        "ADAPTIVE_LISTENING",
        "VOLUME_SETTING",
        "MICROPHONE",
        "AMAZON_MUSIC"
      ],
```

**To Reproduce**

For me, simply reconfiguring.

**Expected behavior**

Not creating entities for non-Alexa devices, I would assume.

**System details**

- Home-assistant: 2023.10.0
- alexa_media: v4.76 in HACS UI (4.6.5 in /config/custom_components/alexa_media/const.py)
- alexapy: 1.27.4
- Amazon:  Yes, 2FA is enabled

**Comment by alandtse** [comment]
Happy to take a PR to fix this; but I probably wont' work on this since I don't use Sonos. We already allow excluding devices and HA allows you to disable entities as a workaround.

**Comment by billmoseley** [comment]
After looking at this for a few days I'm not sure what the correct behavior is.

The main reason is I have not found where https://alexa.amazon.com/api/devices-v2/device, and specifically, the "capabilities" are documented to clearly indicate what would work with this integration, which is used in [\_\_init.py\_\_ ](https://github.com/custom-components/alexa_media_player/blob/c6bc025616972d5c5a7231f43628dba87c80c3f7/custom_components/alexa_media/__init__.py#L540) to decide what devices to include.

There's two ways to bring Sonos speakers into Alexa:

1. The [Sonos skill](https://www.amazon.com/Sonos-Inc/dp/B072ML3N6K) allows playing music on Sonos speakers ("Play music on living room sonos"). All the Sonos speakers in the household will end up in the Alexa "device" API response.
2. If you have an Alexa-compatible Sonos speaker, you can use the Sonos App to add the Alexa voice service to the speaker. But, this process also adds the Sonos skill so it creates all the devices that the skill brings in above, but ALSO creates a device for the Sonos Alexa device. 

The alexa_media_player integration uses the device API call to fetch the list of all Alexa devices. So, it's looping through not only true Alexa-compatible devices, but also Sonos speakers that cannot be used by the integration.

Currently, \_\_init.py\_\_ does this:

```
            if (
                dev_name not in include_filter
                and device.get("capabilities")
                and not any(
                    x in device["capabilities"]
                    for x in ["MUSIC_SKILL", "TIMERS_AND_ALARMS", "REMINDERS"]
                )
            ):
                # skip devices without music or notification skill
                _LOGGER.debug("Excluding %s for lacking capability", dev_name)
                continue
```
I saved the "capabilities" from my Alexa Dot, Alexa Show, a Sonos Alexa device, and a non-Alexa Sonos speaker brought in from the Sonos skill in these files:
```
$ ls *.cap
dot.cap				sonos-alexa.cap
show.cap			sonos-kitchen-NOT-Alexa.cap
```
BTW, the *sonos-alexa.cap* and *sonos-kitchen-NOT-Alexa.cap* are physically the same speaker -- but there's two entries in the devices API response.

```
$ fgrep -l MUSIC_SKILL *.cap
dot.cap
show.cap
sonos-alexa.cap
sonos-kitchen-NOT-Alexa.cap
```
The *sonos-NOT-Alexa* device has the MUSIC_SKILL but alxea_media_player cannot play music on it (or run "custom" commands, obviously). 

It doesn't seem like "MUSIC_SKILL" is enough to know that "Alexa.Music.PlaySearchPhrase" can be used to play media -- OR if that is a bug in the Sonos skill that the device is created with the MUSIC_SKILL capability, when it shouldn't. (Which is why I'm not sure what the fix to prevent loading these non-Alexa devices is, if any.)

And testing the other two:
```
$ fgrep -l TIMERS_AND_ALARMS *.cap
dot.cap
show.cap
sonos-alexa.cap

$ fgrep -l REMINDERS *.cap
dot.cap
show.cap
sonos-alexa.cap
sonos-kitchen-NOT-Alexa.cap
```
Looks like of the three "capabilities" tests only TIMERS_AND_ALARMS is in the Alexa-compatible devices. Doesn't sound like a good test. Do all Alexa devices that can issue "custom" commands have a microphone?

```
$ fgrep -l MICROPHONE *.cap
dot.cap
show.cap
sonos-alexa.cap
```
Again, I'm not sure what is the correct "capabilities" tests to know if the device works with this integration. Without that, your advice to just include specific devices is probably best.

**Comment by alandtse** [comment]
Thanks for the thorough research. Third party devices with Alexa have always been weird. Any solution though should not impact standard Alexa devices so I'd be concerned of doing a capabilities test that would exclude them. Personally, if there was some brand identifier I'd just exclude them based on that. I guess we could add the complexity of having a include_devices override stuff excluded this way if someone really wants it.

**Comment by billmoseley** [comment]
Not sure it's worth mucking around -- especially if what comes back from the Alexa API isn't well documented and consistent.  I just used "exclude_devices" in configuration.yaml to remove all the non-Alexa Sonos rooms.

```
alexa_media:
  accounts:
  - email: !secret alexa_username
    password: !secret alexa_password
    url: amazon.com
    exclude_devices:
      - "Bar"
      - "Living Room"
      - "Family Room"
      - "Back Bedroom"
      - "Kitchen"
      - "This Device"
```


But FYI, in the device response json I see this for my non-Alexa speakers:

```
deviceFamily": "THIRD_PARTY_AVS_MEDIA_DISPLAY",
```

And for the Alexa enabled devices:
```
"deviceFamily": "THIRD_PARTY_AVS_SONOS_BOOTLEG",
```

But, I would think the correct approach is to test the capabilities. If you could trust it to be right.

I think closing this issue and sticking with the "exclude_devices" is the best way to go.
