### ISSUE TITLE
Can't Login after last update v4.7.7

### ISSUE THREAD

**Issue by djcrawleravp** [custom-components/alexa_media_player#2067]
After the update the integration won't log in so I deleted id and re-added using these method (Also tried using my local HA address but It always worked with nabu.casa)

<img width="583" alt="Screen Shot 2023-10-09 at 17 41 04" src="https://github.com/custom-components/alexa_media_player/assets/12896341/91a6643e-3323-4228-8c4c-7f79e501be18">

After putting the 2fa auth key (without spaces) the process works fine (opening the amazon website, putting the OTP and getting the "you may close this window" message" I get this message:

<img width="434" alt="Screen Shot 2023-10-09 at 17 46 49" src="https://github.com/custom-components/alexa_media_player/assets/12896341/83bbdc31-4e5e-46bd-a870-b170c68feb77">

**System details**

- Home-assistant (version):  2023.10.1
- alexa_media (version from `const.py` or HA startup): 4.6.5
- alexapy (version from `pip show alexapy` or HA startup): 1.27.6
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : YES

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

[home-assistant_alexa_media_2023-10-09T21-14-41.431Z.log](https://github.com/custom-components/alexa_media_player/files/12850895/home-assistant_alexa_media_2023-10-09T21-14-41.431Z.log)

**Comment by alandtse** [comment]
Your logs are noting an SSL failure. 

```
[SSL: CERTIFICATE_VERIFY_FAILED] 
```

Are your SSL certs up to date on your HA machine?

**Comment by djcrawleravp** [comment]
Actually I don’t use ssl on my environment, maybe it’s a nabu casa thing?

**Comment by alandtse** [comment]
No, these are the SSL logs for when you're trying to connect to amazon.

**Comment by alandtse** [comment]
Oh, you're on an old version. Please update to 4.7.7.

**Comment by djcrawleravp** [comment]
In fact, I have updated the version and worked until today I rebooted my HA

<img width="1258" alt="Screen Shot 2023-10-11 at 13 50 32" src="https://github.com/custom-components/alexa_media_player/assets/12896341/0c3f2d9e-1a5f-451b-829b-ef3325125c80">

**Comment by alandtse** [comment]
Same error. Your ssl isn't working. That's outside of this component unfortunately. Make sure your client certs are updated on the HA machine.

**Comment by djcrawleravp** [comment]
api.amazonalexa.com was blocked on pihole  :/

**Comment by candrea77** [comment]
I'm trying to update to 4.7.7 , but anytime i'll do it , the integration cannot start.
See image below

![image](https://github.com/custom-components/alexa_media_player/assets/26028217/84475fc4-6e81-4543-b975-e4a078ecea48)
