### ISSUE TITLE
Alexa Integration requires constant re-authorizations 

### ISSUE THREAD

**Issue by def1149** [custom-components/alexa_media_player#2068]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Everyt ime I try to call the Alexa music service i get persistent notification to re-authorize

**To Reproduce**

Call Music Service

**Expected behavior**

**Screenshots**

**System details**

- Home-assistant (version):
- alexa_media (version from `const.py` or HA startup):
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). :

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by alandtse** [comment]
Please provide logs of the call causing the reauth request.

**Comment by blindguynar** [comment]
Had to do this 3 times now in the last four days.

**Comment by dgarozzo** [comment]
I'm having the same problem.

**Comment by alandtse** [comment]
Actually, just realized the template was not filled out at all and was gaming the system.

**Comment by def1149** [comment]
Removing Alexa media player as defective until fixed

**Comment by doctorkb** [comment]
Roll back to 4.7.3 - I don't have the issue there.
4.7.6 is problematic -- unsure if it is resolved in 4.7.7, but the Changelog doesn't identify anything directly.
