### ISSUE TITLE
Alexa media player got stucked and doesnt load devices. Then it ends with an error

### ISSUE THREAD

**Issue by dmartella** [custom-components/alexa_media_player#2073]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**
HA OS running on a virtual box.
I complete the Amazon authentication successfully but it doesn't load the devices. 

**To Reproduce**

The usual onboarding procedure. I have another instance of HA working correctly that actually it works and load all the devices.

**Expected behavior**
Checking the logs in the instance that works correctly, the next step should be: ) [alexapy.alexalogin] Exchange cookie json . This is not happening in the HA running in the Virtual Box.

**Screenshots**

Just the configuration interface remains stucked and it doesn't proceed.

**System details**

- Home-assistant (version): 2023.10.3
- Supervisor 2023.10.0
- Operating System 11.0
-  Frontend 20231005.0 - latest 
- 
- alexa_media 4.7.7
- alexapy (version from `pip show alexapy` or HA startup): not present the pip in terminal. Not found the alexapy== in both the instances logs.
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). :
Yes it is enabled
**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).
Debug enabled logging for mediaplayer shared 

**Additional context**
Thanks for what you do.

[home-assistant_2023-10-14T08-27-41.646Z.log](https://github.com/custom-components/alexa_media_player/files/12903831/home-assistant_2023-10-14T08-27-41.646Z.log)

**Comment by alandtse** [comment]
https://github.com/custom-components/alexa_media_player/issues/1788#issuecomment-1368308162

**Comment by dmartella** [comment]
Thanks alandtse.  In case someone have the same issue:  it is enough to disable the IPV6 of the bridged ethernet created for the virtual box. Thanks Again.
