### ISSUE TITLE
Alexa media player stopped working

### ISSUE THREAD

**Issue by peter-sounthararajah** [custom-components/alexa_media_player#2075]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

** all of my alexas are shown as unavailable **

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details**

- Home-assistant (version):
- alexa_media (version from `const.py` or HA startup):
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). :

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by peter-sounthararajah** [comment]
![Screenshot_20231015_101005_Home Assistant](https://github.com/custom-components/alexa_media_player/assets/65864766/bdc184fa-98e5-41b0-b8b8-8114273692e4)

**Comment by peter-sounthararajah** [comment]
Didn't mean to close

**Comment by alandtse** [comment]
https://github.com/custom-components/alexa_media_player/wiki/FAQ#all-my-media_players-are-unavailable-and-the-component-doesnt-work

Please fill out the template if you actually want help and that doesn't resolve it. This is your one warning.
