### ISSUE TITLE
Alexa Media player two-factor authentication error

### ISSUE THREAD

**Issue by freggel2** [custom-components/alexa_media_player#2078]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

The bug is that everytime I reboot HomeAssistant I need to re-authenticate my Alexa Media Player. This happened a few weeks ago. Before that it always worked flawlessly after every reboot.

After every reboot of HomeAssistant my alexa players become unavailable.

**To Reproduce**

1: restart home assisant
2: restart

**Expected behavior**

Expected that my devices stay available. Instead they become unavailable.

**Screenshots**

**System details**

- Home-assistant (version):

- Home Assistant 2023.10.3
Supervisor 2023.10.0
Operating System 11.0
Frontend 20231005.0 - latest

- alexa_media (version from `const.py` or HA startup):
version__ = "4.6.5

- alexapy (version from `pip show alexapy` or HA startup):

- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). 

Yes, 2FA is enabled. :

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

It worked before. Suddenly (I don't know how long) the Alexa  devices are unavailable after an reboot from home assistant.
I don't know if it happened after an reboot. I don't often reboot my HomeAssistant.
When I re-authicate my devices they are available and work again. After an reboot from homeassistant they become unavailable.

**Comment by dudu631** [comment]
Same here! Working perfectly for months, suddenly I'm getting "please reauthenticate" prompts every day.

**Comment by gveloce** [comment]
Same here since last week Following...

**Comment by alandtse** [comment]
Please make sure you're updated to the 4.7.7. That should've fixed this issue. Please reopen if 4.7.7 gives the issue.
