### ISSUE TITLE
Alexa Media Players don't "create" devices after found in logs, error ("'str' object has no attribute 'get'",)

### ISSUE THREAD

**Issue by rafareusch** [custom-components/alexa_media_player#2079]
**Describe the bug**

All AMP entities have gotten unavailable and an error was presented:

alexaapi.get_last_device_serial((<alexapy.alexalogin.AlexaLogin object at 0x7fc9c62c25d0>,), {}): An error occurred accessing AlexaAPI: An exception of type AttributeError occurred. Arguments:
("'str' object has no attribute 'get'",)

When trying to delete and re-add the integration, no devices or entities are found and the same error is thrown (plus other errors)

**To Reproduce**

Add the integration using 2FA 

**Expected behavior**
AMP detect all devices and entities

**System details**

- Home-assistant (version): 2023.10.1 (also tried 2023.10.3)
- alexa_media (version from `const.py` or HA startup): 4.6.5
- alexapy (version from `pip show alexapy` or HA startup): 1.27.6
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). Y

**Logs**
[advancedLogs.txt](https://github.com/custom-components/alexa_media_player/files/13037372/advancedLogs.txt)

**Additional context**
Another issue with the same exception suggested creating www/alexatts (or something like that). In my instance that folder was already there.
Seems that the devices are detected in the logs but the error appears afterwards.
AMP  was working fine until about 20h ago. No updates or restarts were made when the entities went to unavailable state.

**Comment by rafareusch** [comment]
More Context:
I Added this amazon account to another HA instance and it also didn't work.

**Comment by alandtse** [comment]
Update HA to latest. Old versions are not supported.
