### ISSUE TITLE
Cannot add via Integrations - CAPTCHA issue?

### ISSUE THREAD

**Issue by thomas-mm** [custom-components/alexa_media_player#2080]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Trying to add this component via the integrations method. After some time, the component appears to give up with "Unknown error occurred".

I have verified that the component generates the correct 2FA TOTP string using oathtool and have successfully used this to login to my amazon account.

Of note, if I login to amazon using a fresh browser session (eg using private/incognito mode) Amazon consistently asks me to solve a CAPTCHA before proceeding to allow me to login (I suspect my IP address triggers this). The component doesn't appear to ever ask for a CAPTCHA response on trying to add it.

**Expected behavior**

Login should work. If necessary the CAPTCHA should be forwarded for me to solve.

**System details**

- Home-assistant (version): 2023.10.3
- alexa_media (version from `const.py` or HA startup): tried both the 4.7.7 release zip and git master (both say 4.6.5 in const.py)
- alexapy (version from `pip show alexapy` or HA startup): 1.27.6
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : yes

**Logs**

Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

```
2023-10-19 12:07:54.437 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Creating new login
2023-10-19 12:07:54.437 DEBUG (MainThread) [custom_components.alexa_media.helpers] [Amazon login email REMOVED]: Returning uuid {'uuid': '7a07b89a705fe2bbfcb73d4124fbdcdd', 'index': 0}
2023-10-19 12:07:54.459 DEBUG (MainThread) [alexapy.alexalogin] Creating TOTP for [2FA key REMOVED]
2023-10-19 12:07:54.459 DEBUG (MainThread) [alexapy.alexalogin] Generating OTP [TOTP 6-digit number REMOVED]
2023-10-19 12:07:54.459 DEBUG (MainThread) [alexapy.alexalogin] Login created for [Amazon login email REMOVED] - amazon.co.uk
```

Nothing further appears in the home assistant log after this before the error appears.

**Additional context**

**Comment by MKSEagle75** [comment]
I am having the same issues

**Comment by alandtse** [comment]
Please enable logging of authcaptureproxy per the logs link.

**Comment by alandtse** [comment]
Closing in favor of #2103

**Comment by Saarlothri** [comment]
Problem with Captcha always here also with 4.7.9 (amazon.de)

**Comment by Doldak** [comment]
same here
