### ISSUE TITLE
I can't play Spotify music to my Alexa devices

### ISSUE THREAD

**Issue by MnemoBRMC** [custom-components/alexa_media_player#2082]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Hi
I am trying to play music from spotify in my Alexa Devices but it does nothing.
I enabled the debug logging, but it logs nothing

**To Reproduce**

This is what I am trying to run:
```- service: media_player.play_media
    target:
      entity_id: media_player.echo_show
    data:
      media_content_id: spotify:playlist:******************
      media_content_type: spotify://playlist
    metadata: {}
``` 

**Expected behavior**

It should start playing but it does nothing

**Screenshots**
I have no screenshots

**System details**

- Home-assistant (version):  2023.10.3
- alexa_media (version from `const.py` or HA startup): 4.7.7
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : yes

**Logs**
There are no logs

**Additional context**

**Comment by alandtse** [comment]
https://github.com/custom-components/alexa_media_player/wiki#examples (expand Spotify)
