### ISSUE TITLE
Unable to find service notify.alexa_media_last_called

### ISSUE THREAD

**Issue by ahahamyan** [custom-components/alexa_media_player#2093]
**Describe the bug**

My scripts are all failing when the step to call the service is called - resulting in "Unable to find service notify.alexa_media_last_called"

Service notify.alexa_media_last_called is very key as it is a key component used when Alexa routines call HA scripts (as scenes) and HA scripts return response information back to the actual echo devices that was spoken into, thus emulating a request/response experience as close as possible.

**To Reproduce**

In HA try to create a script that uses the service notify.alexa_media_last_called - which used to exist before and now it does not.

**Expected behavior**

The service should be restored as it is the way for the HA scripts to announce response data to the echo device that was spoken to.

**Screenshots**

![image](https://github.com/custom-components/alexa_media_player/assets/15948531/a92538b7-ea36-4ce7-97a5-ac4d8086e77a)

**System details**

- Home-assistant (version): 2023.10.5
- alexa_media (version from `const.py` or HA startup): 4.7.7
- alexapy (version from `pip show alexapy` or HA startup): 4.7.7
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). y

**Logs**

Logger: homeassistant.components.script.activate_who_is_home
Source: helpers/script.py:1783
Integration: Script (documentation, issues)
First occurred: 11:14:03 AM (1 occurrences)
Last logged: 11:14:03 AM

Activate Who is Home: Error executing script. Service not found for call_service at pos 3: Unable to find service notify.alexa_media_last_called

**Additional context**

**Comment by djcrawleravp** [comment]
Same thing here, should we rollback?

**Comment by kenwiens** [comment]
See issue 2089

https://github.com/custom-components/alexa_media_player/issues/2089

**Comment by zSprawl** [comment]
> Same thing here, should we rollback?

No. 

The issue is that things changed on the Amazon side.
