### ISSUE TITLE
Alexa Media Player status (attributes) in HA not updating

### ISSUE THREAD

**Issue by Scoff123** [custom-components/alexa_media_player#2097]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Using voice commands with either of my 2 Amazon Echo dots, calling for music to play from Spotify via Alexa. The Alexa media player entity in HA updates to show the currently playing media correctly. 
Upon stopping the media via voice command to Alexa, the media stops playing as expected. HA entity shows the media player state as 'paused' and all the media information still shows, the same as when it is playing. 
12 hours or more later, the media information still shows. This information shows indefinitely, until a manual call to the Home Assistant Update Entity service is made on the Alexa media player entity, 

**To Reproduce**

1. Ask Alexa to play spotify music on echo device. Music starts playing 
2. State of Alexa Media Player entity in HA updates correctly to show playing and attributes contain media information
3. Ask Alexa to stop playing music on echo device. Music stops playing. 
4. Check state of Alexa Media Player entity in HA. State shows 'paused' and all media information remains within attributes.
5. Media information remains in attributes indefinitely, unless a manual call to homeassistant.update_entity is made on the Alexa Media Player entity, at which point the entity updates correctly and the media information is no longer contained within the attributes.

**Expected behavior**

Alexa Media Player attributes are updated correctly after stopping media from playing on Alexa device. 

**Screenshots**

<img width="400" alt="image" src="https://github.com/custom-components/alexa_media_player/assets/96984460/4d89a6c8-597e-45fd-b718-78bbbfb0c7ba">

Above screenshot taken at 10:58 on 30/10/2023

After calling homeassistant.update_entity on 'kitchen echo dot'

<img width="406" alt="image" src="https://github.com/custom-components/alexa_media_player/assets/96984460/a5e5caf2-08a3-4bad-af67-88950ee4617e">

**System details**

- Home-assistant (version): 2023.10.5
- alexa_media (version from `const.py` or HA startup): 4.6.5
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : Yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**
[Alexalogs.txt](https://github.com/custom-components/alexa_media_player/files/13204733/Alexalogs.txt)

**Comment by alandtse** [comment]
This is how Alexa works historically. It'll show the last played song for like 3-4 hours and eventually clear it. I believe you'll see the same behavior in the official app.

As we are just reflecting the API, we won't manually override that.  Your logs show that it's successfully updating the settings when playing so not much more we can do unfortunately.

**Comment by Scoff123** [comment]
Unfortunately the issue was closed before I could respond. I understand what you are saying. The problem is, however, that although the media details do show in the Alexa app for some time after ceasing playing, they do eventually clear - but HA holds onto the media details INDEFINITELY and the media details DO NOT CLEAR. The only way to clear them is to manually call the update entity service, so it sounds like the integration isn't actually reflecting the API completely/100%.

**Comment by alandtse** [comment]
Write an automation to update. There is no actual rhyme or reason to when the API removes it so there's nothing for us to know when to check to refresh the data.
