### ISSUE TITLE
Transfer to custom_components project

### ISSUE THREAD

**Issue by alandtse** [custom-components/alexa_media_player#238]
@keatontaylor should we just [transfer](https://help.github.com/en/articles/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account) it to the [custom_components project](https://github.com/custom-components). It looks like this repo was setup to [help curate custom_components](https://github.com/custom-components/information). All links should redirect automatically as long as you don't recreate `alexa_media_player` in your own repo.

I think we'd be able to handle the redirection because @ludeeus runs that repo and is an admin on the forums anyway. I got him to help us change the first post to point to the wiki.

**Comment by keatontaylor** [comment]
Do we want to spend the effort to transfer this over or take the leap to get this supported as an official component?

**Comment by alandtse** [comment]
I think official inclusion will be more time consuming than just relocating. With HACS I see less of a reason to even submit it.
