### ISSUE TITLE
Failed to call service configurator/configure expected string or bytes like object

### ISSUE THREAD

**Issue by alandtse** [custom-components/alexa_media_player#310]
**Describe the bug**
With 2FA disable, Alexa will request a OTP using the claimspicker form. Selection of `sms` or `email` result in `Failed to call service configurator/configure expected string or bytes like object` and the configurator does not advance.

**To Reproduce**
1. Begin log in process and fill out captcha
2. Receive authentication request
3. Enter any option

**Expected behavior**
Configuration completes.

**Screenshots**

**System details**
 - Home-assistant (version): 
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup): 2.0.0
 - alexapy (version from `pip show alexapy` or HA startup): 1.0.0

**Additional context**
```
2019-08-27 08:29:44 DEBUG (MainThread) [alexapy.alexalogin] Verification method requested: Authentication required
We will send you a One Time Password (OTP) to authenticate your request.
, Option: sms = As a text message - +1******xxxx.
Option: email = In an email - x**x@xxxxxxx.com.

2019-08-27 08:29:44 DEBUG (MainThread) [custom_components.alexa_media] Testing login status: {‘claimspicker_required’: True, ‘claimspicker_message’: ‘Option: sms = As a text message - +1******xxxx.\nOption: email = In an email - x**x@xxxxxxx.com.\n’}
2019-08-27 08:29:44 DEBUG (MainThread) [custom_components.alexa_media] Creating configurator to select verification option
2019-08-27 08:30:22 DEBUG (MainThread) [custom_components.alexa_media] Status: {‘claimspicker_required’: True, ‘claimspicker_message’: ‘Option: sms = As a text message - +1******xxxx.\nOption: email = In an email - x**x@xxxxxxxx.com.\n’} got captcha: w6geea securitycode: None Claimsoption: sms AuthSelectOption: None VerificationCode: None
2019-08-27 08:30:22 DEBUG (MainThread) [alexapy.alexalogin] No valid cookies for log in; using credentials
2019-08-27 08:30:22 DEBUG (MainThread) [alexapy.alexalogin] Loaded last request to https://www.amazon.com/ap/cvf/request?arb=c7cf42eb-f42b-43a1-b10b-0b471447xxxx
```
https://community.home-assistant.io/t/echo-devices-alexa-as-media-player-testers-needed/58639/3069
https://community.home-assistant.io/t/echo-devices-alexa-as-media-player-testers-needed/58639/3079
https://community.home-assistant.io/t/echo-devices-alexa-as-media-player-testers-needed/58639/3084
https://community.home-assistant.io/t/echo-devices-alexa-as-media-player-testers-needed/58639/3089

**Comment by nonkronk** [comment]
<img width="716" alt="Screenshot 2019-08-28 19 42 18" src="https://user-images.githubusercontent.com/29120359/63856520-01125200-c9cc-11e9-96be-5babb9e7da9e.png">
Same issue here...
i just upgraded the component yesterday through hacs

**Comment by mattnewham** [comment]
I have this error, I dont even get verification method, just throws the error as soon as I hit confirm. I've put the new alexapy folder in /config and no fix.

**Comment by LCerebo** [comment]
I have a similar error as the one described by @mattnewham: after updating the component through hacs at version 2.0.0, I receive the notification that ask me to configure my account, then the pop-up appears but after pressing the "confirm" button nothing happens. 
No 2FA configured, running home-assistant 0.97.2 through docker.
<img width="1283" alt="Screenshot 2019-08-28 at 23 48 13" src="https://user-images.githubusercontent.com/31437530/63895061-6a0ac180-c9ee-11e9-9889-5934a713bc88.png">

**Comment by alandtse** [comment]
Please try replacing alexalogin with what I linked and provide logs. It's possible the /config may not work unless you do a pip install.

**Comment by kjake** [comment]
Seeing the same issue as @LCerebo after restarting HASS today.  I don't know where to put @alandtse's files - I'm running a HASS.io/HASSOs image, so have limited access to things.

Also noted an alexa_media[email].pickle file in /config that contains:
'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

Rolling back to v1.4.1 in HACS fixed it

**Comment by mattnewham** [comment]
Hassio installs don’t like pip install, so previously the solution was to put alexapy in the config folder, which didn’t work for me.

Also rolling back doesn’t seem to work for me either. I rolled back to 1.4 (which previously worked) then on the config thing I click the button and a second empty dialog box appears and then disappears. I think this was a bug back then too?

**Comment by alandtse** [comment]
No, I don't think this was reported in 1.4.1. We may just have to push out the code to get better logs to figure out what is happening.

**Comment by GHSTUDIO1** [comment]
I installed using Hass  configure option...,.,just create a file in the config folder....that's the one that you see with automations, scripts, etc folders.  Copy Alan's code...I used windows copy/paste.....Save  the file.

delete any pickle files that refer to your alexas....

restart....

Fixed my problem which was identical to lCerebo and Kjake.....

**Comment by humphrep** [comment]
I can't get past this error:
Failed to call service configurator/configure. expected string or bytes-like object

That pops up every time I try to put in sms or email.  I tried putting the new alexalogin.py file in the /config directory.  I am running HASSIO.

Not sure how to grab the logs, is there a link to instructions for grabbing the appropriate logs?

**Comment by kjake** [comment]
Thanks @GHSTUDIO1, that made sense.
I used Configurator in Hass.io to create a new file in /config, named it alexalogin.py, pasted the text from GitLab and saved the file. Then, I deleted the .pickle file I found. Then, went to HACS and upgraded to v2.0.0 again and restarted Home Assistant.
After restarting, a notification was showing to begin the login for Alexa. I confirmed it, and it closed, but a new notification showed up for the capatcha - the image loaded, I typed it in, hit confirm and it finished the login.  I was able to send TTS after that without any API errors.

**Comment by humphrep** [comment]
I am back and running as well.  I uninstalled from HACS, and manually put on 1.4.1.  I went through the prompts to get the one time code.  Then I was able to upgrade to 2.0.0 via HACS. I didn't have to put the alaexalogin.py file in the /config directory.
