### ISSUE TITLE
CONFIGURATOR - Click button to configure Alexa Media Player - Begin 

### ISSUE THREAD

**Issue by tukadafoonday** [custom-components/alexa_media_player#315]
Have just updated to Hassio .98 and have since had a notification to click the button to login to Alexa Media Player

No matter how many times I click the button it is still showing up as a notification.

No alexa media players are showing up either.

![image](https://user-images.githubusercontent.com/47523450/64027427-0a461f00-cb84-11e9-9529-87ccec399085.png)

**Comment by tukadafoonday** [comment]
Never mind - sorry...  My pickle was out of date.

**Comment by glassbase** [comment]
Bet you restart HA and it will ask you to begin setup again. At least that’s what’s happening with me. 

I have to delete pickle and and restart again and then do setup. If I restart HA, do it all again.

**Comment by voydz** [comment]
> Bet you restart HA and it will ask you to begin setup again. At least that’s what’s happening with me.
>
> I have to delete pickle and and restart again and then do setup. If I restart HA, do it all again.

Same after updating to version 2.0.0.

Thank you guys for this great component. Is there anything we can help you with. To get this issue sorted out?

**Comment by SeanPM5** [comment]
Same issue here for the last two or three days.

I get the first prompt that says "Please hit confirm to begin login attempt." and it seems like the second prompt and persistent notification is dismissed immediately. So I can never progress.

**Comment by alandtse** [comment]
Please provide logs or we can't solve this. Please consolidate to #307.

**Comment by mauriziomontanaro** [comment]
I've got the same problem. Can you help me?
thanks
Maurizio
