### ISSUE TITLE
HA v0.98+ If you disable alexa_media created switches they will still be reported to HA 

### ISSUE THREAD

**Issue by skynet01** [custom-components/alexa_media_player#317]
**Describe the bug**
Disable an alexa_media sensor using the new entities feature. For example a shuffle switch entity like: _switch.alexa_dot_shuffle_switch_ 

**To Reproduce**
1. Go to 'entities under config, find an alexa media switch entity and disable it'
2. Click on 'entity like switch.alexa_dot_shuffle_switch'
3. reboot HA
4. See error in console:

`Entity switch.alexa_dot_shuffle_switch is incorrectly being triggered for updates while it is disabled. This is a bug in the alexa_media integration.`

**Expected behavior**
no error

**Screenshots**
see error in console

**System details**
 - Home-assistant (0.98.1): 
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): 2.0.0
 - alexapy (version from `pip show alexapy` or HA startup): latest

**Additional context**

**Comment by alandtse** [comment]
Issue is entities must check self.enabled before attempting to update state.
```python
        if self.enabled:
            _LOGGER.debug("Event %s (%s)", self.name, self._device.modelType)
            self.async_schedule_update_ha_state()
```
See [example](https://github.com/home-assistant/home-assistant/commit/cf3bb300e69b53ba7fddd9409a8811d28b10cc44#diff-549a23b6d8a72e52c87abba4d271201dR80).

**Comment by holdestmade** [comment]
Same issue here
