### ISSUE TITLE
Disable/enable/login HomeAssistant Skill

### ISSUE THREAD

**Issue by starkillerOG** [custom-components/alexa_media_player#320]
Is it possible to use the alexa API that alexa_media_player uses to disable, enable and/or login to the HomeAssistant Skill?

I would love to have a homeassistant service that can reconnect the HomeAssistant skill to the nabu casa account. (now I have to do that through the amazon website: https://alexa.amazon.com --> go to skills --> your skills --> HomeAsssitant --> disable the skill, then re-enable and login to the nabu casa account).

Sometimes for some reason home assistant cloud does not work for me anymore, and going through the above steps by re-connecting the homeassistant skill to my nabu casa acount seems to solve it.

**Comment by alandtse** [comment]
This seems like an issue to resolve with the standard `alexa` component. We can investigate enabling/disabling skills but since they require third-party authentication, it's probably a lot of work and won't be a priority.

**Comment by starkillerOG** [comment]
@alandtse thank you for the quick replay!
It would be awesom if at some point you would have time to look into enabling/disabling skills.
I think the required documentation of the API is here:
[https://developer.amazon.com/docs/smapi/skill-operations.html](https://developer.amazon.com/docs/smapi/skill-operations.html)

Does Alexa_media_player uses the https://api.amazonalexa.com endpoint with requests like `GET  /v1/skills/{skillId}/stages/{stage}/manifest`?

**Comment by alandtse** [comment]
No. We're webscraping so we're not using the official API. Again, the fact we'd have to handle a third-party auth means it's very unlikely. It's a lot of work when you could just log into the official alexa webpage to do it.

**Comment by keatontaylor** [comment]
> @alandtse thank you for the quick replay!
> It would be awesom if at some point you would have time to look into enabling/disabling skills.
> I think the required documentation of the API is here:
> https://developer.amazon.com/docs/smapi/skill-operations.html
> 
> Does Alexa_media_player uses the https://api.amazonalexa.com endpoint with requests like `GET /v1/skills/{skillId}/stages/{stage}/manifest`?

I believe this is for programmatically creating and deleting new skills for use in the skills store. Not accessing skills on the consumer/user side

**Comment by alandtse** [comment]
Closing as this isn't something available through the API.
