### ISSUE TITLE
Feature request: add function to connect to paired bluetooth device

### ISSUE THREAD

**Issue by alandtse** [custom-components/alexa_media_player#322]
The Source List in the media_player UI is intended to only be bluetooth audio sources. We recently fixed a bug in #317 where sometimes we weren't enforcing this distinction. 

Some users have been using it as a way to pair devices with their Alexa device so this will break their use case. One use case below:

---
Ok, I get your point and if you put it like that than the bluetooth device should never show on that source property whatsoever. As you say it should be a new feature.
My usecase was like so:
Whenever I say "Alexa play music",
I detect this event in HA, 
I trigger my sound system bt pair,
Alexa pairs to sound system,
And music plays on my sound system

btw, if you fix this bug without adding the new feature, my usecase will break :)

_Originally posted by @danielmihalache1983 in https://github.com/custom-components/alexa_media_player/issues/316#issuecomment-526866992_

**Comment by alandtse** [comment]
Oh wait, the media_player.select_source should still work for selecting the source. You just need to know the friendlyName of your paired device. That can be found in the Alexa app or from the [Alexa json](https://alexa.amazon.com/api/bluetooth?cached=false).

**Comment by danielmihalache1983** [comment]
Ok, I get it. Your point is that you won`t list the BT devices in HA interface.
