### ISSUE TITLE
Won’t configure after update to 2.0.1

### ISSUE THREAD

**Issue by garnern2** [custom-components/alexa_media_player#330]
This addon won’t configure after updating through HACS to 2.0.1.

When I restart, I get the configuration notification, but when I click “Configure,” it loads for a bit then returns to the same configuration page.

How can I help debug this?

**Comment by scottsweb** [comment]
Seeing the same issue. The configurator shows the notification, first pop up appears. Clicking 'confirm' shows the spinner then closes the pop up and back to where I started. No captcha is shown and it means I can no longer get setup.

No errors in the logs or UI as far as I can see. 

Home Assistant:  0.98.2

**Comment by Frinatic** [comment]
Having the same issue here! Let's hope there is a fix soon :)

**Comment by alandtse** [comment]
See #307

**Comment by garnern2** [comment]
I hate to sound rude, but if you will read the issue you linked, it is not resolve, so I’m not sure why the issue should be closed. It worked for me at 2.0.0, not 2.0.1.

**Comment by alandtse** [comment]
It's the same issue. There's no point in having more than one thread open for the same fundamental issue. #307 is still open and I am working to fix it.

**Comment by alandtse** [comment]
Also reason to point to other thread is there is a workaround listed there for those who need it immediately working.
