### ISSUE TITLE
WARNING (Recorder) Event is not JSON serializable: <Event platform_discovered[L]:

### ISSUE THREAD

**Issue by alandtse** [custom-components/alexa_media_player#336]
**Describe the bug**
Recorder provides a json warning because of passing of discovered info.

**To Reproduce**
1. Enable recorder for platform_loaded events
2. Update to 2.1.0
3. See error

**Expected behavior**
No warning

**Screenshots**

**System details**
 - Home-assistant (version): 0.98.2
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): 2.1.0
 - alexapy (version from `pip show alexapy` or HA startup): 1.0.2

**Additional context**
This only appears at startup for all four components.
* media_player
* switch
* notify
* alarm_control_panel

**Comment by sephrioth** [comment]
Same here.

**Comment by lockyt** [comment]
ditto

(I had also lost my install from HACS for some reason, although alexa was still working.  Just had to hit install again but was a bit weird - hence why now on 2.1.0)

**Comment by ehendrix23** [comment]
FYI, same here. :-)

**Comment by dentafrice** [comment]
Seeing this as well. 

It's a warning so setting the recorder component logger to > warning should silence it enough to not have your password all out there in plaintext:
```
logger:
  logs:
      homeassistant.components.recorder: error
```
