### ISSUE TITLE
Alexa Guard Triggered State

### ISSUE THREAD

**Issue by bryeartem** [custom-components/alexa_media_player#337]
Would it be possible to monitor when Alexa Guard detects a smoke/co or glass break event in HA?  The Alexa app gets a notification so I’m assuming it’s pushing something but I don’t have the knowledge to grab the info.

It would be awesome if a binary sensor could be created for the smoke/co glass break events that we could then tie into HA especially for use with the new “Critical Alerts” for the iOS 2.0 app.

**Comment by alandtse** [comment]
Unfortunately no. The APIs we use don't report when they're triggered.

**Comment by alandtse** [comment]
Closing until we find a mechanism.
