### ISSUE TITLE
Alexa is not installed after Setup!

### ISSUE THREAD

**Issue by calas80** [custom-components/alexa_media_player#338]
**Describe the bug**
After installing the alexa component, and after configuring configuration.yaml, the media component is not found

**To Reproduce**
1. Go to HACS
2. Click on Alexa Media Player
3. Install (I installed the latest version, performing a reboot. I have also tried to install every single version, from the oldest to the newest, restarting each time)
4. See error:

he following components and platforms could not be set up:
- alexa-media
- alexa-media.notify
Please check your config.

**System details**
 - Home-assistant (version): 0.98.2
 - Hassio (Yes/No): No, Home Assistant, raspberry pi3+ Raspbian
 - alexa_media  (version from `const.py` or HA startup): 2.1.0
 - alexapy (version from `pip show alexapy` or HA startup): ???

**Comment by alandtse** [comment]
Please provide logs.

**Comment by metalloid14** [comment]
Hi,
I have similar behavior, but on HA 0.97.2 and on 0.98.3. Tried to installed it through HACS and manually.
It used to work on HA 0.95...
I've tried and removed the login cookie file, but it still doesn't work. And it does not create a new one...

When I restart HA, in the notifications, the error is:
The following components and platforms could not be set up:
. Alexa_media
Please check your config

Tried to restart several times, same behavior. I never receive the notification to do the Captcha challenge, only the above error.

Logs: 

> 2019-09-04 21:04:08 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.

> 2019-09-04 21:04:11 INFO (SyncWorker_5) [homeassistant.util.package] Attempting install of alexapy==1.0.2
> 2019-09-04 21:04:42 INFO (MainThread) [homeassistant.setup] Setting up alexa_media
> 2019-09-04 21:04:42 INFO (MainThread) [custom_components.alexa_media] 

> alexa_media
> Version: 2.1.0
> This is a custom component
> If you have any issues with this you need to open an issue here:
> https://github.com/custom-components/alexa_media_player/issues
> 
> 2019-09-04 21:04:42 INFO (MainThread) [custom_components.alexa_media] Loaded alexapy==0.4.2
> 2019-09-04 21:04:42 DEBUG (MainThread) [alexapy.alexalogin] Trying cookie from file /config/alexa_media.xxxxxxxx@xxxxx.com.pickle
> 2019-09-04 21:04:42 DEBUG (MainThread) [alexapy.alexalogin] Error loading pickled cookie from /config/alexa_media.xxxxxxxx@xxxxx.com.pickle: An exception of type FileNotFoundError occurred. Arguments:
> (2, 'No such file or directory')
> 2019-09-04 21:04:42 DEBUG (MainThread) [alexapy.alexalogin] No valid cookies for log in; using credentials
> 2019-09-04 21:04:44 DEBUG (MainThread) [alexapy.alexalogin] Get to https://alexa.amazon.com/api/devices-v2/device was redirected to https://www.amazon.com/ap/signin?showRmrMe=1&openid.return_to=https%3A%2F%2Falexa.amazon.com%2Fapi%2Fdevices-v2%2Fdevice&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=amzn_dp_project_dee&openid.mode=checkid_setup&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&
> 2019-09-04 21:04:44 DEBUG (MainThread) [alexapy.alexalogin] Preparing post to https://www.amazon.com/ap/signin/130-7691657-9248113 Captcha: None SecurityCode: None Claimsoption: None VerificationCode: None
> 2019-09-04 21:04:44 DEBUG (MainThread) [alexapy.alexalogin] Cookies: <RequestsCookieJar[<Cookie session-id=130-7691657-9248113 for .amazon.com/>, <Cookie session-id-time=2198347483l for .amazon.com/>]>
> 2019-09-04 21:04:44 DEBUG (MainThread) [alexapy.alexalogin] Submit Form Data: {'appActionToken': 'NdLHvnxLck1rFDA3ra08Cr9HgKAj3D', 'appAction': 'SIGNIN', 'openid.return_to': 'ape:aHR0cHM6Ly9hbGV4YS5hbWF6b24uY29tL2FwaS9kZXZpY2VzLXYyL2RldmljZQ==', 'prevRID': 'ape:RkpBQlBXMEdNSlRFSDJWUTkzOFc=', 'workflowState': 'eyJ6aXAiOiJERUYiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiQTI1NktXIn0.cNNN-ENCJ1OvP8w61VfHSq1oS1j0jLZSquZvBLxv-cdqpYLulfppHg.wy0Hya6DzeYjsg15.mHDtuG_ZPBX9V5GQqD0lHZzyILbVlwT2lA_0rRTw2F8WeTAeYf35kRF50OM6YxdJo1Zkt9-w57tpU87QoWa2rnmGhlpcWMZyrIoq5delASLAl3fU0tAlk6fv6VTp8kCY8dbywViOXb7GQBf-tad2mKtQfTL1oyOIcmMolpLlc4Zdi8nW_yAdIN9fJr6iOEN0AzvtqGkjBcleQyqdMZZBIjms5DwAPpWaNG677zvz_RKGVI0dcauZZNSFjyekDVx3jE3ppKGptU0MVLYJB1SzQZkH5ijpI90NLIHveV6C6Dbhk6I.a2cSZ8M-6B4E36IvG7B23w', 'email': b'xxxxxxxx@xxxxx.com', 'password': b'xxxxxxxxxxx', 'showPasswordChecked': 'false', 'rememberMe': b'true'}
> 2019-09-04 21:04:44 DEBUG (MainThread) [alexapy.alexalogin] Header: {'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml, application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': '*', 'Referer': 'https://www.amazon.com/ap/signin?showRmrMe=1&openid.return_to=https%3A%2F%2Falexa.amazon.com%2Fapi%2Fdevices-v2%2Fdevice&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=amzn_dp_project_dee&openid.mode=checkid_setup&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&', 'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8'}
> 2019-09-04 21:04:45 DEBUG (MainThread) [alexapy.alexalogin] Performing second login to: https://www.amazon.com/ap/signin
> 2019-09-04 21:04:47 DEBUG (MainThread) [alexapy.alexalogin] Error message: Important Message!
>             To better protect your account, please re-enter your password and then enter the characters as they are shown in the image below.
>           
> 2019-09-04 21:04:47 DEBUG (MainThread) [alexapy.alexalogin] Captcha requested
> 2019-09-04 21:04:47 DEBUG (MainThread) [alexapy.alexalogin] Trying cookie from file /config/alexa_media.xxxxxxxx@xxxxx..com.pickle
> 2019-09-04 21:04:47 DEBUG (MainThread) [alexapy.alexalogin] Error loading pickled cookie from /config/alexa_media.xxxxxxxx@xxxxx..com.pickle: An exception of type FileNotFoundError occurred. Arguments:
> (2, 'No such file or directory')
> 2019-09-04 21:04:47 DEBUG (MainThread) [alexapy.alexalogin] No valid cookies for log in; using credentials
> 2019-09-04 21:04:47 DEBUG (MainThread) [alexapy.alexalogin] Loaded last request to https://www.amazon.com/ap/signin/130-7691657-9248113 
> 2019-09-04 21:04:47 DEBUG (MainThread) [alexapy.alexalogin] Preparing post to https://www.amazon.com/ap/signin Captcha: None SecurityCode: None Claimsoption: None VerificationCode: None
> 2019-09-04 21:04:47 DEBUG (MainThread) [alexapy.alexalogin] Cookies: <RequestsCookieJar[<Cookie session-id=130-7691657-9248113 for .amazon.com/>, <Cookie session-id-time=2198347483l for .amazon.com/>, <Cookie session-token="9C79yvG8fmvWtuZx74Ytmoq6o+i5BNQD5sdthTdmG4+6YrhQrg+xyk+1MMD6NJjtKO9trz7pNmsv9uUKod7p2Ybu0H+WRxpUpPT9ZUSAyz8UUII9lo404qB9gfw9IIuFmANRZeGcQZaLCIA8VR9nH3LTujS5t9eIDK+uAdaftMPT/RLsnl+qpz2Sy+DHiQMbRQAjefmrenAdFBFeskoh0A==" for .amazon.com/>, <Cookie ubid-main=130-8486002-3622800 for .amazon.com/>]>
> 2019-09-04 21:04:47 DEBUG (MainThread) [alexapy.alexalogin] Submit Form Data: {'appActionToken': 'NdLHvnxLck1rFDA3ra08Cr9HgKAj3D', 'appAction': 'SIGNIN', 'ces': 'ape:QUNTX3VUMzRlSUd2Q2RaRWV3SUl1MXJTSjM5L2YzOEFBQUFBQUFBQUFRZE90SFFhMWVWNkd3WHNkbzB4UmR0bmZDdDhodTIySG02YjIwcWp6aDhXUmVYcW52YWR1ZGRFN3lpeHBVeDV0Wk5XaWRhTVhVazZIR1ZaOSs2N0F0MzFoNnFLdHU0ajVHWEk4M0hqVUxoSDk1Sk9JcXl5L29MMEJZVVoxellKWlA1MkFBbXBZNWppTGZQRk14VmhzdG5YRHdzK3c5cVoveHBxckNzZVJvMzd5N3liaHBNc3FkK3VVdVg5K29NMjNZZnh3VGxITW5IK1lkaDQrV1g4TTg4Y081VU5rTlliYVQxZUhGUFpXVHRRb2lOUmFZM2NwZ29lbDc0Y1E1MUNMZXJPZGhGZFF0OWp5YWpKZnRCZ2ZUWVQ0c1ljTnpXVGRLUDZvL3JGNENUbys5blUxaWFCTkEvcjNmVXE0d2tUbU16LzR2WFVNU0t1emZtdmdxQW00TlU9', 'openid.return_to': 'ape:aHR0cHM6Ly9hbGV4YS5hbWF6b24uY29tL2FwaS9kZXZpY2VzLXYyL2RldmljZQ==', 'prevRID': 'ape:RkJUSjY4UUVNNTg5QlFWV1lNSFQ=', 'workflowState': 'eyJ6aXAiOiJERUYiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiQTI1NktXIn0.sXQ6cSdCe6iHOkWS-DqMdPIZddGGd76FY19L6SpsKU7I7dMvi2-Jqg.3CdF6_uVz0a1sTJ1.SMQgooOsfVtH2jTG21Qoz_SZywW4o9cUm-S3kck147CVpsA0UFEGBXXftIfGKghpinsH41rmPyS90oeddkrTkLg8x6LTWOgiEazQ1QFNnY18F64k37awLfdpGGBPzKFC8uFNBStMsMP6WGNC9Dgs6beZyUEMROLzXTWifwg8Oct6VHJ45XYpxCzpKWVDxZ2E6Gvn0FCW5EvjUBApTHPc3COpj01aSmCSQlXgw_HpYBhfJjji7ei9Ofg6SRDRWzSyQtB_5BDkKoOhWkbv7t8gS9IllchxsH7afYaZXyVsK6x4MUeF45dPwzG3CEusnmPXsgVEDGWC2h5rLUTU9eXvC4reBsohcASVt3YatXRVSF1Q1yuZi4VnIAbeew5PBYBhX6ZhJQCvalK0xvmIAKz9xnMNQXhwq14jGSGIcKaNCA5Nx6-TrmFGEykke4CMLtdBtaYzllM-j9oLm3EuaoIZjW7BnQJFg3KUytEOuzpeq_lpIa04izpIpbzokSI6hSOjgtqTiIjPvgz7_Of2R6ggnQ.DmLget4RsKiGpNYRyb9CMQ', 'email': b'xxxxxxxx@xxxxx.com', 'password': b'xxxxxxxxxxx', 'showPasswordChecked': 'false', 'rememberMe': b'true', 'use_image_captcha': 'true', 'use_audio_captcha': 'false', 'guess': ''}
> 2019-09-04 21:04:47 DEBUG (MainThread) [alexapy.alexalogin] Header: {'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml, application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': '*', 'Referer': 'https://www.amazon.com/ap/signin/130-7691657-9248113', 'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8'}
> 2019-09-04 21:04:47 DEBUG (MainThread) [alexapy.alexalogin] Error message: There was a problem
>             Enter the characters as they are given in the challenge.
>           
> 2019-09-04 21:04:47 DEBUG (MainThread) [alexapy.alexalogin] Captcha requested
> 2019-09-04 21:04:47 ERROR (MainThread) [homeassistant.setup] Error during setup of component alexa_media
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/setup.py", line 168, in _async_setup_component
>     hass, processed_config
>   File "/config/custom_components/alexa_media/__init__.py", line 133, in async_setup
>     await login.login_with_cookie()
> TypeError: object NoneType can't be used in 'await' expression

**Comment by alandtse** [comment]
@metalloid14 you have a really old version `0.4.2` of alexapy which is not compatible. Did you install a custom version in your /config directory? Please delete it and restart HA or install the latest version `1.0.2` manually.

**Comment by metalloid14** [comment]
hi @alandtse, I've uninstalled everything, installed manually again the latest version, but somehow the alexapy version loaded is 0.4.2.
I'm running HA in a docker container, so I've run inside the container the command to check the alexapy version, and it showed I'm running version 1.0.2... So, I have no clue where the 0.4.2 version comes from. Of course, from an old installation, but where??
What I did was:
1) removed the alexa_media folder from the custom_components folder
2) removed the alexa_media integration from HACS
3) removed the cookie file from the HA config folder
4) then run the uninstall command (pip uninstall alexapy) on the HA container
5) removed the alexa_media configuration in the configuration.yaml file
6) finally restarted Home Assistant
THEN, after HA online, I've:
1) created again the folder alexa_media on custom_components
2) and the alexa_media configuration in the configuration.yaml file
3) restart Home Assistant.

and same error... in the logs I can see first:

2019-09-05 20:07:04 INFO (SyncWorker_4) [homeassistant.util.package] Attempting install of alexapy==1.0.2

and then, some seconds later:

2019-09-05 20:07:21 INFO (MainThread) [custom_components.alexa_media] Loaded alexapy==0.4.2

So, something is wrong, not loading the right version (1.0.2) that I can see is installed on the container...

**Comment by alandtse** [comment]
I don't use docker so I can't really help you on that front. Please check your custom_components directory to ensure there isn't an old version of alexa_media.  Also, make sure there aren't any subdirectories in your config directory with alexapy.

You may have to search the file system to see where it's storing alexapy.

**Comment by metalloid14** [comment]
@alandtse it was in "/deps/lib/python3.7/site-packages/"...
Removed the directory and **finally** it loaded the right version! :)

**Comment by alandtse** [comment]
@metalloid14 That's odd that you couldn't remove it. Did you do a `sudo pip` at some point? That may have installed it as root and then when HA tries to replace it it doesn't have the privilege.

**Comment by eugeneniemand** [comment]
Ok I'm also using docker raspberrypi 3 version 98.4 image and have same issues. I connected to container and did a pip list and noticed the current version of alexapy on the image is 0.5.0 . I have now restarted HA and now I get this error:
```
The following components and platforms could not be set up:

- alexa_media.alarm_control_panel
- alexa_media.switch
- alexa_media.media_player

Please check your config.
```

**Comment by alandtse** [comment]
@eugeneniemand you need to delete the old version of alexapy. The logging issue is a known bug #336

**Comment by eugeneniemand** [comment]
@alandtse where do I need to delete the old copy? I have tried `pip uninstall alexapy'? I dont have a alexapy in my custom_components folder

**Comment by alandtse** [comment]
@eugeneniemand as noted above I don't use docker so not sure. You'll need to search. Perhaps @metalloid14 can provide guidance on how he found it.

**Comment by metalloid14** [comment]
Hi @eugeneniemand, if it's a problem regarding an old version still in your system, check if its there somewhere.
What I've done.
I've connected to my docker container (after I ssh to my HA machine, and changed to a super user account...):
docker exec -it <my_container_name> /bin/bash
then performed a find command:
find -name alexapy
It reported two instances, mine were on:
./deps/lib/python3.7/site-packages/alexapy
./deps/lib/python3.7/site-packages/AlexaPy-0.4.2.dist-info
The only one that I think really mattered was the first one, but I've removed both to be on the safe side. So I've removed the folders:
rm -r AlexaPy-0.4.2.dist-info/
rm -r alexapy/
and then a Home Assistant restart. After that, all worked, the right version 1.02 loaded correctly, it could not before because of the old version being stuck there...

**Comment by eugeneniemand** [comment]
@alandtse  & @metalloid14 thanks for trying to help. I'm still facing issues.

Everything loads and looks like it logs in from the logs however home assistant is complaining about the media_player and alarm_control_panel config. `Platform not found (No module named 'custom_components.alexa_media.helpers'`

```
2019-09-08 20:59:23 INFO (MainThread) [custom_components.alexa_media] 
-------------------------------------------------------------------
alexa_media
Version: 2.1.0
This is a custom component
If you have any issues with this you need to open an issue here:
https://github.com/custom-components/alexa_media_player/issues
-------------------------------------------------------------------

2019-09-08 20:59:23 INFO (MainThread) [custom_components.alexa_media] Loaded alexapy==1.1.2
2019-09-08 20:59:23 DEBUG (MainThread) [alexapy.alexalogin] Trying to load pickled cookie from file /config/alexa_media.eugene.niemand@gmail.com.pickle
2019-09-08 20:59:29 DEBUG (MainThread) [alexapy.alexalogin] cookie loaded:
...
Existing: [] New: ['Kitchen', 'Master', 'Bose QC35 II', 'Everywhere', 'Jayden', 'Lounge', 'Downstairs', 'Upstairs', 'This Device', "Eugene's Alexa Apps", 'This Device', "Hailey's Alexa Apps"]; Filtered out by not being in include: [] or in exclude: []
2019-09-08 20:59:50 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform alexa_media.alarm_control_panel: Platform not found (No module named 'custom_components.alexa_media.helpers').
2019-09-08 20:59:50 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform alexa_media.media_player: Platform not found (No module named 'custom_components.alexa_media.helpers').
2019-09-08 20:59:50 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.co.uk/api/activities?startTime=&size=10&offset=1 <CIMultiDictProxy('Host': 'alexa.amazon.co.uk', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml, application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': '*', 'Referer': 'https://alexa.amazon.co.uk/api/bootstrap', 'Origin': 'https://alexa.amazon.co.uk', 'Accept-Encoding': 'gzip, deflate', 'Cookie': 'at-acbuk=Atza|IwEBIEP_on3tTOLwVIc4b10O_61EuOBmj1OhdnZdLKfRWqfdRvWSew1-FflxwQPck8-iauzyEZuJmBcOaZes3vN3m7wJ4lGmRa2KHqNUycCD4-kqpvVozZMC1TQvr3omMl8Fx1nY1oXWXddew6wQaHLz82Us0ZeDwGPI_GlNliyM9Yu_P5X64WVo98d-BxmxbSfhI4ax3r8DgdHhbdS18u7RW_ciS4mcLLrPrMCGJ-b4dtjk6rBpwG8YZi4kYsADPMDJvfxAaRIoZOxNfIMiriYOZR0qH1G9-aMnjuQZXOaPKQWEPfiRpTKI1b0qAPcLqUxdsohGAUEHGc3Z65t7SQuifvqogLpC3TkZsg-hRXBV-JY-6XVNjgqgRQDHVrK5lccR7QoQAJGFrk12QZcQBTQfOeOdcIp40XwSuwTt49TfVvpxxw; csrf=-858083414; sess-at-acbuk="m8xhhcJfX+ju8C8vSjQY7RK5zpJzKbQngRL0PyHKPqE="; session-id=260-5386876-7655044; session-id-time=2193347466l; session-token="YR9dlPaURBWJjznPjPZmT6Iycwfd/862TMSFP+LbeHGTWqsUEjD8JwSBomg0LFVB2et7Itx6bhFA/HuoqSIs7mA5ZdplVB3uhiL4D2feECkW0pAUePR6aCRjVzvFD/x8SSq2dcKHnvsr/5v+rjgcTGZ5i4CJ9ZdF8/DPiy5WkEqch3WJXj23tbO7kTajYs9FREBF+qJc1ro6DyPDMAp13nZJovVB08Zi9EQwefKJ06s="; sid="65AIE1+A8YNrayP2G1e9+Q==|kGa+He5wb1Smw6AYBebtz2YMKeQWcpPYZhDth+aS454="; sst-acbuk=Sst1|PQGHrmjBCjANSrVeHDobAbeZC92Hff5WcfyN5ZgwaHAj73oZBt2UYoJn4W_AcFtobLZgaIrvaBykHSjdLqxueeVlPBMok6pMWWOEl0puibH1RwabIlFojfNsxdGq9ECMHr9ZGnWvrEzt0e32IRdhtjKw0Mz0klFkN646cNfx-U1NRFYbzN7Fa5HOprcwDhPOYWdltJhBbvQBgxuWJ10uilEfpt2D4ZGwIEOpUQnTV6uFZslu0uF9_xuqKcTIdIJ8c1pp73oJZ9T3PQAJJWO4jgzwD20h9-1eOoR1Xm56jFR1Glj1QSbhRZo_LKG96o0RmJ-1YzTDyZIJpuwUcAENF91mgg; ubid-acbuk=260-2916601-6722167; x-acbuk="IVV1bP?KWh2x?94ExoGuQSO?oa3X4z8U"')> returned 200:OK:application/json
2019-09-08 20:59:50 DEBUG (MainThread) [custom_components.alexa_media] e************d@g*******m: Updated last_called: {'serialNumber': 'G************RL5', 'timestamp': 1567964900379}
2019-09-08 20:59:50 DEBUG (MainThread) [custom_components.alexa_media] e************d@g*******m: last_called changed:  to {'serialNumber': 'G************RL5', 'timestamp': 1567964900379}
```

**Comment by alandtse** [comment]
Are you manually installing? You're missing files and your versions don't match. You're missing the `helpers.py` file.

**Comment by eugeneniemand** [comment]
Yes this was a manual install and the docs did not mention that file. I have now updated the docs

**Comment by alandtse** [comment]
@calas80 I'll close this now as we are on 2.1.2. Please reopen if you are having issues still and provide logs.
