### ISSUE TITLE
The HA log is flooded with error messages

### ISSUE THREAD

**Issue by KennethLavrsen** [custom-components/alexa_media_player#339]
**Describe the bug**
I have used the alexa_media_player for months but a recent update has started flooding the Home Assistant log with the same message over and over again

I cannot see anything not working. I just get the error all the time

**To Reproduce**
Wait and watch the HA log grow

**Expected behavior**

**Screenshots**

**System details**
 - Home-assistant (version): 0.98.2
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug). hass.io installed on Ubuntu
 - alexa_media  (version from `const.py` or HA startup): 2.1.0
 - alexapy (version from `pip show alexapy` or HA startup):  I see 0.1.0 when putting this in the host Ubuntu. 

**Additional context**

```
2019-09-03 20:06:08 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/alexa/state_report.py", line 45, in async_entity_state_listener
    hass, smart_home_config, alexa_changed_entity
  File "/usr/src/homeassistant/homeassistant/components/alexa/state_report.py", line 103, in async_send_changereport_message
    response_json = json.loads(response_text)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) 
```

**Comment by KennethLavrsen** [comment]
After having looked further there are things that are broken

The alarm panel for guard is unavailable.

All the device switch entities that alexa media player created recently are unavailable.

But TTS works. 

It is a bit in pieces. I tried to remove the pickle file and restart and new capcha. But still after that nothing works. I deleted the old alarm panel entity. But no new is added.

**Comment by KennethLavrsen** [comment]
The missing features is due to the changes done to how things are included and excluded. See https://github.com/custom-components/alexa_media_player/issues/340. All these have nothing to do with the many errors in the HA log.

**Comment by alandtse** [comment]
These errors are with the HA standard component not the custom_component. Please report there.

**Comment by KennethLavrsen** [comment]
My bad. Sorry for waiting your time. I should have seen that.
