### ISSUE TITLE
Cannot get captcha to work 2.1

### ISSUE THREAD

**Issue by rlust** [custom-components/alexa_media_player#345]
**Describe the bug**
I have been using the previous versions for a long time.
Captcha not accepted.
I have tried to enter captcha 20 times and I am getting the following message in my logs.

I have removed everything and reinstalled, same problems. I do not have a pickle file.

**To Reproduce**
`2019-09-05 21:06:58 DEBUG (MainThread) [alexapy.alexalogin] Captcha requested
2019-09-05 21:06:58 DEBUG (MainThread) [alexapy.alexalogin] Found post url to https://www.amazon.com/ap/signin
2019-09-05 21:06:58 DEBUG (MainThread) [alexapy.alexalogin] Preparing post to https://www.amazon.com/ap/signin Captcha: 46nada SecurityCode: None Claimsoption: None  AuthSelectOption: None VerificationCode: None
2019-09-05 21:06:59 DEBUG (MainThread) [alexapy.alexalogin] Processing https://www.amazon.com/ap/signin
2019-09-05 21:06:59 DEBUG (MainThread) [alexapy.alexalogin] Error message: There was a problem`
**Expected behavior**

**Screenshots**

**System details**
 - Home-assistant (version): 
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by alandtse** [comment]
Need more logs to figure out what the issue is. The logs you submitted don't provide enough information.

**Comment by rlust** [comment]
[home-assistant.log](https://github.com/custom-components/alexa_media_player/files/3581908/home-assistant.log)

**Comment by rlust** [comment]
I closed this by mistake

**Comment by rlust** [comment]
[home-assistant.log](https://github.com/custom-components/alexa_media_player/files/3582031/home-assistant.log)
Here is my log file.

**Comment by alandtse** [comment]
Do you have the right email address? The logs are saying Amazon is reporting:
> We cannot find an account with that email address

This happens when the captcha is right and you have the wrong email.

**Comment by rlust** [comment]
Thanks so much!! Problems with my secret file. All is well!
