### ISSUE TITLE
Cannot Activate Routine

### ISSUE THREAD

**Issue by mikenabhan** [custom-components/alexa_media_player#346]
**Describe the bug**
Trying to initiate a routine stopped working after update.

**To Reproduce**
1. Go to developer tools
2. Click on dervices
3. Enter data
"Call-service API error. Error Message: 0, message='Attempt to decode JSON with unexpected mimetype: text/html'"
**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/13139061/64451189-e82b3000-d0a0-11e9-8c2a-3472e0fc474c.png)

**System details**
 - Home-assistant (version):   0.98.4
 - Hassio (Yes/No): yes
 - alexa_media  (version from `const.py` or HA startup):  '2.0.1'
 - alexapy (version from `pip show alexapy` or HA startup): 1.0.1

**Logs**
Call-service API error. Error Message: 0, message='Attempt to decode JSON with unexpected mimetype: text/html'

**Additional context**
This automation was previously working fine.  Happens when the service is called via node-red or direct from home assistant.

**Comment by mikenabhan** [comment]
I will also say that I can still do anything else with the component just fine.

**Comment by mikenabhan** [comment]
I am also confirming the issue happens with alexapy 1.0.2

**Comment by drzuki** [comment]
having the same thing here

**Comment by alandtse** [comment]
Thanks. The issue is the cookie may be expired so the next time you restart it'll probably force you to relogin. There may be a bug with the cookie creation in 2.0.1 that I found last night not to mention a login issue for some regions.  If you run into that, 1.4.1 should recreate the cookie properly.

**Comment by broyuken** [comment]
I’m having the same issue, it’s not asking me to re-login.

**Comment by alandtse** [comment]
Ok, I've confirmed the bug. Looking into it.

**Comment by alandtse** [comment]
Funny, Amazon changed the content-type on the automation page. Ok I should be able to work around it.

**Comment by broyuken** [comment]
Thank you, when will this fix be available in hacs?

**Comment by alandtse** [comment]
There's a bug that stopped the full release. You can see it under beta releases until we fix it for everyone. Issue is you have to delete your .pickle file before starting or it will have an error.  The cookie migration code for the 1.x cookie had a bug in it that I want to fix before a full release.

**Comment by alandtse** [comment]
2.1.2 should resolve. No need to delete pickle.
