### ISSUE TITLE
Add the ability to use Amazon Freetime to pause devices

### ISSUE THREAD

**Issue by boojew** [custom-components/alexa_media_player#349]
**Is your feature request related to a problem? Please describe.**
One of the cool features in the Amazon ecosystem is to use Amazon Freetime to pause devices on-demand for a fixed period of time.

**Describe the solution you'd like**
I would love to see a boolean switch added to HomeAssistant that would allow me to set freetime on/off for a device. 

**Describe alternatives you've considered**
I currently do this by blocking the device at the firewall level, but that breaks the device entirely. Freetime allows it to continue to function for services like announcements and dropin

**Additional context**

**Comment by alandtse** [comment]
We can look into it. Features have been backlogged as we try to work through the login issues.  One thing that would be helpful is if someone could figure out the API call to the Alexa website. That will be the first step.

**Comment by alandtse** [comment]
Specifically, I'd need someone to capture the API traffic to enable or disable on a device. You can probably [use Chrome](https://developers.google.com/web/tools/chrome-devtools/network/) with the [webapp](alexa.amazon.com).  I just don't happen to have FreeTime on my devices.

**Comment by airdrummingfool** [comment]
I have been looking for a way to "mute" Alexa devices (so they stop listening) via the API, and this seems like a good workaround for the lack of Mute API.

I was able to grab some requests from the API using Chrome. Note that I've removed my device type, device ID, and device serial number.

Here's the API command to disable FreeTime:
```
Request URL: https://alexa.amazon.com/api/unassign-device-from-child/DEVICE_SERIAL_NUMBER/DEVICE_TYPE
Request Method: POST
Host: alexa.amazon.com
Origin: https://alexa.amazon.com
Pragma: no-cache
Referer: https://alexa.amazon.com/spa/index.html
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
X-Requested-With: XMLHttpRequest

Body: {deviceType: "DEVICE_TYPE", deviceSerialNumber: "DEVICE_SERIAL_NUMBER"}
```

Here's my guess at the API-ish call that actually enables a call. Note that the `childDirectedId` field is formatted like this (partially obscured): `amzn1.account.ABCDEFG1H2IJK3ABC7ABCD436ABC`
```
Request URL: https://parents.amazon.com/ajax/enable-device-services
Request Method: POST
Host: parents.amazon.com
Origin: https://parents.amazon.com
Pragma: no-cache
Referer: https://parents.amazon.com/deviceOobeSuccess?deviceId=DEVICE_ID&deviceTypeId=DEVICE_TYPE_ID&experience=BYOD&childDirectedId=CHILD_DIRECTED_ID
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
X-Requested-With: XMLHttpRequest

Body: {"deviceId":"DEVICE_ID","deviceTypeId":"DEVICE_TYPE_ID","childDirectedId":"CHILD_DIRECTED_ID","deviceServices":["ELF","COMMS","ThirdPartyMusic","FirstPartyMusic"]}
```

**Comment by airdrummingfool** [comment]
Actually, FreeTime doesn't seem to be the great workaround for muting a device that I hoped it would.

Unfortunately when I disable the device using FreeTime, Alexa still responds with "Sorry, I can't play right now" when I say the wake word and then a command - so she's still listening.

**Comment by alandtse** [comment]
Thanks @airdrummingfool. Do you see any other API call that is grabbing the child id list? I'm assuming this won't work unless you identify the kids that need to be blocked.

**Comment by eddedre** [comment]
I’m actually looking for the functionality to be able to pause/resume freetime on my kids Alexa. I would be willing to capture any data needed to get the feature reopened.
