### ISSUE TITLE
Not working with alert component

### ISSUE THREAD

**Issue by alekslyse** [custom-components/alexa_media_player#355]
**Describe the bug**
Trying to get this integration working with the native "Alert" integration of Home Assistant, but it seem not be possible to use the notification integration as intended

**To Reproduce**
Add an alert with the regular service data used in the service tab or automation on notification. HA will fail sending the TTS / Announcement by not being able to get the target list 

**Expected behavior**
Work as notification works in service and automations

**Screenshots**

**Comment by alandtse** [comment]
You need to provide a list of targets. Please read the wiki.
