### ISSUE TITLE
Integration alexa_media not found (Hass.io)

### ISSUE THREAD

**Issue by rogersmj** [custom-components/alexa_media_player#359]
**Describe the bug**
After installing the component (via HACS) and restarting three times, I continue to get the following errors in my log:
![image](https://user-images.githubusercontent.com/20134/64746175-8facc600-d4d8-11e9-9931-1c22e5d83005.png)

**To Reproduce**
1. Have a Hass.io installation with HACS
2. Install the alexa_media_player custom component via HACS
3. Restart HA three times over the course of 5-10 minutes, as per the instructions because you have Hass.io

**System details**
 - Home-assistant (version): 0.98.5
 - Hassio (Yes/No): Yes (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup): 2.1.2
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.
`ModuleNotFoundError: No module named 'alexapy'`.

**Additional context**
As noted above, it looks like alexapy is not getting installed. I can't install it via SSH terminal, because pip/pip3 is not available -- I'm trying to run a clean Hass.io system and only use plugin and package managers, so I'd really rather not go hacking around directly installing python packages if I can avoid it. Maybe there's no other way around this but wanted to check.

**Comment by alandtse** [comment]
[*](https://github.com/custom-components/alexa_media_player/wiki/Installation-and-Configuration#alexapy-dependency)

**Comment by chickenandpork** [comment]
Did this get resolved, or just closed?  Were there any suggestions in case it happens to someone again?  (Hass.io, Hass version 1.102.3, HACS 0.20.8)

```
Error: Testing configuration at /config
INFO:homeassistant.util.package:Attempting install of uuid
INFO:homeassistant.util.package:Attempting install of aiofiles==0.4.0
INFO:homeassistant.util.package:Attempting install of aiogithubapi==0.4.3
INFO:homeassistant.util.package:Attempting install of backoff==1.10.0
INFO:homeassistant.util.package:Attempting install of hacs_frontend==20200104192235
INFO:homeassistant.util.package:Attempting install of integrationhelper==0.2.2
INFO:homeassistant.util.package:Attempting install of semantic_version==2.8.4
INFO:homeassistant.util.package:Attempting install of pykevocontrol==2.0.0
Failed config
  General Errors: 
    - Component error: alexa_media - Integration 'alexa_media' not found.
```
