### ISSUE TITLE
Invalid config - The following components and platforms could not be set up: alexa-media

### ISSUE THREAD

**Issue by zibous** [custom-components/alexa_media_player#363]
**Describe the bug**
Restart HA - .. The following components and platforms could not be set up: alexa-media

**To Reproduce**
1. Stop HA 
2. Delete alexa_media.******.pickle
3. Start HA Configurator ..  Click button to configure Alexa Media Player - Begin...
![Bildschirmfoto 2019-09-14 um 16 01 11](https://user-images.githubusercontent.com/30198737/64910604-7db96600-d718-11e9-9f02-45e3aa861117.jpg)

4. Works
5. RESTART HA
6. Invalid config - The following components and platforms could not be set up: alexa-media

**System details**
 ```
arch | armv7l
dev | false
docker | false
hassio | false
os_name | Linux
python_version | 3.7.3
timezone | Europe/Vaduz
version | 0.98.5
virtualenv | true
```

**HACS installed Alexa Media Player version: | v2.1.2**

**Logs**
```
Sep 14 17:32:54 rb3b hass[12190]: -------------------------------------------------------------------
Sep 14 17:32:54 rb3b hass[12190]: alexa_media
Sep 14 17:32:54 rb3b hass[12190]: Version: 2.1.2
Sep 14 17:32:54 rb3b hass[12190]: This is a custom component
Sep 14 17:32:54 rb3b hass[12190]: If you have any issues with this you need to open an issue here:
Sep 14 17:32:54 rb3b hass[12190]: https://github.com/custom-components/alexa_media_player/issues
Sep 14 17:32:54 rb3b hass[12190]: -------------------------------------------------------------------
Sep 14 17:32:54 rb3b hass[12190]:
Sep 14 17:32:54 rb3b hass[12190]: 2019-09-14 17:32:54 INFO (MainThread) [custom_components.alexa_media] Loaded alexapy==1.1.2
Sep 14 17:32:54 rb3b hass[12190]: 2019-09-14 17:32:54 DEBUG (MainThread) [alexapy.alexalogin] Trying to load pickled cookie from file /home/homeassistant/.homeassistant/alexa_media.....
Sep 14 17:32:56 rb3b hass[12190]: 2019-09-14 17:32:56 DEBUG (MainThread) [alexapy.alexalogin] cookie loaded:....
Sep 14 17:32:58 rb3b hass[12190]: 2019-09-14 17:32:58 DEBUG (MainThread) [alexapy.alexalogin] Trying to load aiohttpCookieJar to session
Sep 14 17:32:58 rb3b hass[12190]: 2019-09-14 17:32:58 DEBUG (MainThread) [alexapy.alexalogin] Updating self._cookies with amazon.de session cookies:
Sep 14 17:32:58 rb3b hass[12190]: amazon.de: session-id=259-9115812-9018616
Sep 14 17:32:58 rb3b hass[12190]: amazon.de: session-id-time=2199193391l
Sep 14 17:32:58 rb3b hass[12190]: amazon.de: ubid-acbde=258-4470430-8796302
....
Sep 14 17:32:58 rb3b hass[12190]: amazon.de: csrf=2092436387
Sep 14 17:32:58 rb3b hass[12190]:
Sep 14 17:32:58 rb3b hass[12190]: 2019-09-14 17:32:58 DEBUG (MainThread) [alexapy.alexalogin] Loaded 9 cookies

```

HA release 0.97.2 - August 11, 2019 all is working w/o any errors.

**Comment by alandtse** [comment]
Can you provide the rest of the logs please? The logs don't show any problems where you've stopped.

**Comment by zibous** [comment]
@alandtse 

See here:

**HA-98-5-home-assistant restart**
https://privatebin.at/?eaeaec0a9380f125#4L33cpeZ9Ypj842mifagXHY836oiGkRTKe2uTbrzKSTt

**HA-98-5-home-assistant first start**
https://privatebin.at/?fbc6ed11036537b2#J2pBcLxQgk1ogC4kSqX8tX4Kz9Sky1JPXZQCT4JNu2o4

**HA-97-2-home-assistant - works**
https://privatebin.at/?44dcc444168693b1#HhJsvyn6DMhT75Xd3RE42LMJrNcyRRuYN81hyuKZw6QX

**Comment by alandtse** [comment]
Thanks. Ok. That's weird. So on reboot the logs just stop? Does HA load immediately or does it take some period of time before the UI shows up?

**Comment by zibous** [comment]
@alandtse 

No, the logging goes on after a while and I see everyone else. 

HA starts normal only that I see the message "Invalid config - The following components and platforms could not be set up: alexa-media" see.

But if I delete **alexa_media. ******. pickle** and then reboot HA then it will work to the next restart. 

Therefore, I always have to delete this when I restart.

**Comment by alandtse** [comment]
Ok, the logging continues but it doesn't say anything else from alexa_media? Normally it should say something in the logs if it's giving you the "invalid config" message.

**Comment by zibous** [comment]
@alandtse 
No more messages for alexa_media only from others - only the: **Invalid config**

I have a behavior in the web interface, which comes closer to this.

With this URL it works:
https://**alexa.amazon.de**/spa/index.html?#cards

Here I can sign in, but there is no content:
https://**alexa.amazon.com**/spa/index.html?#cards

Could it be that there is a problem with the domains?

**Comment by alandtse** [comment]
I don't think it's a domain problem as that's the normal way it works when you try the webapp with the wrong domain. Sometimes Amazon will redirect you sometimes just the blank page.

Can you please enable [advanced debugging](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-advanced-debugging-to-debug-login-issues) for the second restart?  Please run until you see the invalid config error in the UI so I have a bit more in logs.

**Comment by zibous** [comment]
@alandtse 

**Log New installation**
https://privatebin.at/?54bde0ce945547b0#CvnALZxdPTMBnKr55T6roRCwyq988Gx39THkKHqbjjkK

**Log Restart**
https://privatebin.at/?d25af102a91a352c#9SmzFZGYQVhbpGJkDRYRfAKbAaR84ZApXubyfqxQFmPN

```
successfully installed 
  homeassistant-0.98.5 
  importlib-metadata-0.19 
  python-slugify-3.0.3 
  pyyaml-5.1.2 
  ruamel.yaml-0.15.100 
  voluptuous-0.11.7 
  voluptuous-serialize-2.2.0

alexa_media:
  accounts:
  - email: !secret alexa_user
    password: !secret alexa_pass
    url: amazon.de
    debug: True
    include_devices:
      - Esszimmer
      - Wohnzimmer
      - Office
      - Fitnessraum
      - Bad
    exclude_devices:
      - "Peter's Alexa Apps"
      - "Peters Alexa Apps"
      - "This Device"
```

**Comment by alandtse** [comment]
Ahh, you're having an SSL error. According to the [aiohttp thread](https://github.com/aio-libs/aiohttp/issues/3535), you need to update to python 3.7.4. Anyway you can try that?

**Comment by zibous** [comment]
@alandtse 

OK, you're right. On **HA 0.97.2** I do not see this error message.

Not so good, because upgrading from Python 3.7.3 to Python 3.7.4 for Debian 10 (Buster) on a Rasperry is a challenge and not so easy.

If I switch to Python 3.7.4, then I have to compile Python myself and lose the apt updates.
I still have to think about whether I would rather not stay on the HA version 0.97.2.

Thanks for the support.

**Comment by alandtse** [comment]
This may be tied to the connection errors people have been reporting. I'll continue to look at a solution from the component level.

**Comment by zibous** [comment]
@alandtse 
Thanks 👍

**Comment by maxwroc** [comment]
I have just experienced the same problem. It happened just after upgrade to HA 0.99.0 (on HassOS 2.12). 

Strange thing is that it fixed itself after couple HA restarts. And I didn't have to delete *.pickle (as @zibous was saying).

After first restart (just after the upgrade) I saw notification about invalid configuration (same as the title of this issue). I have noticed that there is 2.2.0 update for alexa-media integration (I was on 2.1.2) so I've upgraded it as well.

Second restart and notification about "new devices detected" appeared ("invalid configuration" one was gone). Though all my alexa media player entities were unavailable.

Decided to do another restart (just in case - before trying to delete pickle file) and surprisingly everything worked.

I'm wondering what could be the reason here... maybe python was upgraded to 3.7.0 within 0.99.0 HA release? I see a ```Deprecate Python 3.6.0``` note, in HA release notes, but I'm not sure if this means an upgrade or not.

**Comment by alandtse** [comment]
Please try 2.2.1 and let me know if it persists.

> I'm wondering what could be the reason here... maybe python was upgraded to 3.7.0 within 0.99.0 HA release? I see a `Deprecate Python 3.6.0` note, in HA release notes, but I'm not sure if this means an upgrade or not.
That was a specific version of 3.6. The min version is 3.6.1 now, so it's not related.

**Comment by zibous** [comment]
@alandtse 


Thank you, until now it works with the new version. 
I have updated HA 0.97.2 to the latest version. 
After the reboot notify.alexa_media works fine again.

```
arch 	armv7l
dev 	false
docker 	false
hassio 	false
os_name 4.19.66-v7+ armv7l
python_version 	3.7.3
timezone 	Europe/Vaduz
version 	0.99.2
virtualenv 	true
Raspbian GNU/Linux 10 (buster)
```
