### ISSUE TITLE
Alexa Switch Profile

### ISSUE THREAD

**Issue by matbrewer396** [custom-components/alexa_media_player#364]
Hello

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when my echos are in wrong to profile.  So I have an Alexa routine setup that I can call from home assistant, that changes the volume and starts playing whatever I was last playing on Spotify. However, if the echo is not in my profile it uses the wrong Spotify account and therefore the wrong music.

**Describe the solution you'd like**
I would like the ability to force and Alexa device to which profiles. 

**Describe alternatives you've considered**
Nothing in Alexa routine that allows you to do this and there no option in https://alexa.amazon.com.

Cheers

**Comment by alandtse** [comment]
I'm not sure what Alexa Profiles are. Are you saying profiles in Spotify?  Please note, we mimic what the apps can do. If they don't have the same thing we may not be able to do it.

**Comment by SqyD** [comment]
If @matbrewer396 means different Alexa users, I would love to see that as well, but this is not exposed in the app, so I'm not sure if it's available in the API. Changing users between members of the household is currently still a pain by just using voice. Having the ability to automate it would be awesome, but I wouldn't hold your breath for it.
