### ISSUE TITLE
Error loading component.

### ISSUE THREAD

**Issue by tulindo** [custom-components/alexa_media_player#366]
Hello, I've a home assistant installation on a debian buster linux.
HA has been installed using this guide: https://www.home-assistant.io/docs/installation/virtualenv/

I've installed the alexa_media_player (version 2.1.2) using HACS (version 0.13.3). 
This the error I'm getting after the configuration of the component in configuration.yaml

Regards,
 Paolo

------------------------------------------------------
ERROR (MainThread) [homeassistant.setup] Error during setup of component alexamedia
Traceback (most recent call last):
File "/home/hassio/lib/python3.7/site-packages/homeassistant/setup.py", line 168, in async_setup_component
hass, processed_config
File "/home/hassio/.homeassistant/custom_components/alexa_media/__init.py", line 132, in async_setup
await login.login_with_cookie()
File "/home/hassio/lib/python3.7/site-packages/alexapy/alexalogin.py", line 165, in login_with_cookie
await self.login(cookies=self._cookies)
File "/home/hassio/lib/python3.7/site-packages/alexapy/alexalogin.py", line 384, in login
site = await self._process_page(await post_resp.text(), site)
File "/home/hassio/lib/python3.7/site-packages/alexapy/alexalogin.py", line 578, in _process_page
site)
File "/usr/lib/python3.7/re.py", line 183, in search
return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object

**Comment by roblandry** [comment]
Same issue with hassio

**Comment by sparkyx64** [comment]
Also seeing the same issue with hassio docker install and HACS - same error log as OP, with addition of an error when trying to run the captcha

`[homeassistant.components.websocket_api.http.connection.139930585929104] expected string or bytes-like object
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1235, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/configurator/__init__.py", line 235, in async_handle_service_call
    await self.hass.async_add_job(callback, call.data.get(ATTR_FIELDS, {}))
  File "/config/custom_components/alexa_media/__init__.py", line 165, in configuration_callback
    login, callback_data)
  File "/config/custom_components/alexa_media/__init__.py", line 155, in setup_platform_callback
    await login.login(data=callback_data)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexalogin.py", line 384, in login
    site = await self._process_page(await post_resp.text(), site)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexalogin.py", line 578, in _process_page
    site)
  File "/usr/local/lib/python3.7/re.py", line 183, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
2019-09-17 23:27:37 ERROR (MainThread) `

**Comment by tulindo** [comment]
Just some other information that hope can help.
I've configured amazon.it (from other different issues I've seen that there should be issues with amazon.it)
I've also seen that in developer tool I can see the configuration entity and I can launch it. No popup appears but the pickle file get created. Restarting HA after the creation of the pickle file, it complains that it took more than 60 seconds to activate.

I've also uninstalled alexa_media 2.1.2 and installed 1.4.1 (deleted also the pickle file). With this version the configuration entity get created without errors, but restart fails (pickle file get created).
Upgraded to 2.1.2 (with pickle file created by 1.4.1) and it took again more than 60 seconds to activate.
Two phase authentication is not enabled in my amazon.it profile

**Comment by alandtse** [comment]
@tulindo #357

**Comment by tulindo** [comment]
Are you going to make a 2.1.3 version of alexa_media?

**Comment by alandtse** [comment]
2.2.0, but yes.

**Comment by tulindo** [comment]
I just tried (modifying the manifest as you did in your fix)... capcha is correctly displayed but the 60 seconds to activate is still there.

**Comment by alandtse** [comment]
All, update to 2.2.0 and let me know if this persists. I'll plan to close this in a week unless someone says it's still an issue.

@tulindo You can't fix the 60 second problem with just changing the manifest. That was a different issue.
> A little question: I don't (yet) have an amazon echo device but I'm testing alexa integrations using the alexa app on my smartphone. Is your component working on the app as well or it needs the "real" device?
We can do some stuff with an app (I think send notifications; build and run routines, etc.). It's not the primary use case so I honestly don't know what you'll be able to do. Does the App let you play music? I think if you have the Amazon Music app we can actually control it when it's active but I haven't tried.

**Comment by tulindo** [comment]
Just updated to 2.2.0 (tried this either with upgrade than by uninstall and reinstall).
I also deleted the pickle file.
Once I start HA it shows me a notification claiming that a new component has been discovered. It links me to settings -> integration
There I see a configure link close to Alexa media player. Clicking on it nothing happens :(
When I click the configure button an error is displayed on the console
 https://hostname/frontend_latest/chunk.43dcfc6e5b8d18714299.js:1007:164 Uncaught TypeError: Cannot read property 'item' of undefined

No entity has been created.

Tried both with amazon.com and amazon.it

**Comment by alandtse** [comment]
Try refreshing your browser on the page. What language is your HA set to? You may have to swap it to English until we get the translation file.

**Comment by alandtse** [comment]
Wait nevermind. I don't think that's the issue. I'll need logs.

**Comment by tulindo** [comment]
What kind of log do you need? How do I enable them?

**Comment by alandtse** [comment]
[Logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

Please post your config setting with proper quotes \``` (mask your sensitive info).

**Comment by tulindo** [comment]
[logs.zip](https://github.com/custom-components/alexa_media_player/files/3630610/logs.zip)
Here you are.
 Paolo

**Comment by roblandry** [comment]
Seems to have fixed my issue. Will report back in a few days if there are any more errors. Thank you!

**Comment by alandtse** [comment]
@tulindo Thanks for the logs. This is covering when you click configure and see the error? If you manually add the component does it display the captcha? The logs indicate it's waiting for that.

**Comment by tulindo** [comment]
The log is taken from startup to click in the configure button.

**Comment by alandtse** [comment]
In the bottom right of integrations is a plus sign where you can add a new entry. Are you able to add Alexa media manually or do you get the same error?

**Comment by tulindo** [comment]
Adding the integration manually works. Well... I think it works ;)
First it showed me a popup asking for configuration information (mail, password and amazon domain). Then it showed the captcha window. After the captcha discovered the alexa devices.
I'm confused: why is he asking for the amazon account? Isn't this information stored in the configuration.yaml file?
No more 60 seconds startup problem.

I then deleted everything related to alexa media from configuration.yaml and started again.
HA started with a notification telling me to insert the capcha. I did it and the capcha window was different from before (same as version 2.1.2)

I discovered than  that the integration was already there. Does this mean that the integration configuration file is kept somewere else instead configuration files (I suppose in home_assistant_v2.db). Is this correct?

Then I deleted the integration, pickle files and restarted again (without alexa media informations in the configuration file). Result:
* No notification appears
* Integration can be added manually.

As far as I've understood (I'm new with HA) manually adding integrtions store configurations in the HA db. 
2.2.0 version is not able (at least with my configuration) to complete the configuration.yaml file information (by asking capcha).

One information once aythenticated it shows me 2 alexa devices:
* one is my mobile app (Paolo's Alexa app)
* one is "This Device"
What is this "This Device"?
Thanks

**Comment by alandtse** [comment]
> I discovered than that the integration was already there. Does this mean that the integration configuration file is kept somewere else instead configuration files (I suppose in home_assistant_v2.db). Is this correct?

Yes, config entries are stored in the internal database. Specifically in the `.storage/config_entries` file.
> 2.2.0 version is not able (at least with my configuration) to complete the configuration.yaml file information (by asking capcha).

Yes, that is the bug I'm trying to resolve now. For some reason it's not showing the window for the captcha.

> * one is my mobile app (Paolo's Alexa app)
> * one is "This Device"
>   What is this "This Device"?

`This Device` is a catch-all for various apps in the Alexa Ecosystem. This can be the shopping app or the music app, or whatever you have.

**Comment by tulindo** [comment]
Thanks alan, very clear.
Just another question about your component: is also working with a non echo device? I other words can I tell alexa running on my smartphone to play some music?

**Comment by alandtse** [comment]
These type of questions are better for the HA community thread. I don't have that use case. As for other non-echo devices. It depends on the device. See #285 where it may not work. I'll mark this last part of the thread as offtopic since others may want to solve the initial issue and may add relevant info.

**Comment by tulindo** [comment]
Just tried with newly released HA 0.99.2.
In the case of alexa_media configuration written in configuration.yaml the notification (that says new device discovered) links you to the integrations part.
Now the configure button displays a popup asking for the amazon configuration part (username, password and domain). I think it should link you to the captcha popup keeping values from configuration.yaml

**Comment by alandtse** [comment]
Yes, it's something to potentially fix but since config entries are still new it's not clear how to access it when it's in the middle of an authentication session. You'll note the logs know it's already at the captcha stage; but we can't access it directly yet.

**Comment by tulindo** [comment]
Just another question. Is it now possible to exclude some Alexa devices from appearing in HA?

**Comment by alandtse** [comment]
[Yes in HA](https://www.home-assistant.io/blog/2019/08/28/release-98/#entity-management) or [through the component](https://github.com/custom-components/alexa_media_player/wiki/Installation-and-Configuration#configuring-inclusions-or-exclusions-versions--096). I'll close this out since I think the original issue is resolved.

Btw, the configure issues you've raised should be fixed in the next release.

**Comment by tulindo** [comment]
alexa media 2.3 and HA 0.99.3 (same wit 0.99.2)
Having component configured in configuration.yaml I'm getting the same error in the log  (TypeError: expected string or bytes-like object)
Tried with both amazon.com and .it
Do you want me to open a new issue?

**Comment by alandtse** [comment]
Please start a new thread and make sure you identify the alexapy version and that you're not using an old one.
