### ISSUE TITLE
Select Bluetooth speaker for Alexa output

### ISSUE THREAD

**Issue by SqyD** [custom-components/alexa_media_player#367]
**Is your feature request related to a problem? Please describe.**
I would love to have the option to select a bluetooth speaker as for Alexa output. 

**Describe the solution you'd like**
Sometimes I would like to switch some of my Alexa devices to switch to an (otherwise dumb) external bluetooth speaker in another room. These could be added to the Sources list and selected just like the other audio input bluetooth devices. As touched upon in #316 the "Source" term is a bit confusing but as some other integrations like the Spotify one do use it to switch the music output device. 

**Describe alternatives you've considered**
If we want to stick to defining a "source" as an input, could we expose selecting an output device as a service or switch?

Thanks a lot to all contributing.

**Comment by alandtse** [comment]
The service `media_player.select_source` will allow selection of an output Bluetooth. We only restrict it in the UI.

**Comment by SqyD** [comment]
Ah, that's great info and works just fine for me. I've added it to this [wiki page with automation examples](https://github.com/custom-components/alexa_media_player/wiki/Automation-examples#selecting-bluetooth-speakers-for-alexa-output)

Thanks for the quick reply. This component is now officially my favorite one. Awesome work!

**Comment by theHasp** [comment]
alexa_disconnect_kitchen_speaker:
  sequence:
    - service: media_player.select_source
      data:
        entity_id: media_player.echo_living_room
        source: "Local Speaker."

I think (maybe I'm wrong) it should be
alexa_disconnect_kitchen_speaker:
  sequence:
    - service: media_player.select_source
      data:
        entity_id: media_player.echo_living_room
        source: "Local Speaker"

WITHOUT the dot after Local Speaker ...
