### ISSUE TITLE
Unable to setup Integrationen. HA 0.99.0, alexa_media_player 2.2.0

### ISSUE THREAD

**Issue by Marlor** [custom-components/alexa_media_player#373]
Clicking on configure in Integrations does nothing, even after multible restarts.

Errorlog:
2019-09-19 15:42:24 ERROR (MainThread) [frontend.js.latest.201909181] https://xxx.duckdns.org/frontend_latest/chunk.43dcfc6e5b8d18714299.js:1007:141 TypeError: e.model is undefined

**Comment by alandtse** [comment]
Please provide logs for when you're clicking.

**Comment by Marlor** [comment]
Thats the home-assistant.log, every click gets a new frontend "e.model is undefined" error.
Is there another log you need?

**Comment by alandtse** [comment]
See this probably the same as #366.

**Comment by alandtse** [comment]
Are you able to install the integration manually? Please check the other thread for instructions.

**Comment by alandtse** [comment]
Oh, if you were on HA 0.99.0 there was at least one bug related to Integrations. Make sure you're on 0.99.2

**Comment by Marlor** [comment]
Delete/reinstalled everything related to HACS and Alexa and now it works. So there was probably something wrong with my installation, sorry.

Love that you now can configure alexa_media_player without touching the configuration.yaml, thank you.
