### ISSUE TITLE
Alexa Media does not make status changes

### ISSUE THREAD

**Issue by Dielee** [custom-components/alexa_media_player#374]
**Describe the bug**
Alexa Media does not make status changes
as seen in #369 

**System details**
 - Home-assistant (version): 0.99
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): 2.2.0
 - alexapy (version from `pip show alexapy` or HA startup): 1.2.0

**Logs**
https://cloud.linusdietz.eu/index.php/s/rX6USo7jj1evikT

**Comment by alandtse** [comment]
Are other functions working?

**Comment by alandtse** [comment]
Media player changes show up in the app right? Can you try with Amazon music too?

**Comment by Dielee** [comment]
Media player changes show up in app, yes.
In Amazon music all works fine. It displays the right state.

**Comment by alandtse** [comment]
Ok. The logs aren't showing any obvious errors. The websocket connection isn't reporting changes which would result in the behavior you're seeing.  Can you try renaming your pickle file and trying to recreate it?

Separately I think this may be related to the disconnect errors (#362) others are seeing as a disconnect would have a similar issue. I'm not sure why it isn't explicitly providing an error message though.

**Comment by Dielee** [comment]
I already tried that. Unfortunately it doesn't help.
But if I restart HA and play a player it will be displayed correctly afterwards. But only until the next change comes (pause, play). Then the status doesn't change anymore.

**Comment by alandtse** [comment]
Yah the lack of updates is expected. Basically it thinks it's still connected to websockets which disables any polling code (which is a fallback mechanism to at least give some updates).

**Comment by Dielee** [comment]
Anything I could do ?

**Comment by eifinger** [comment]
I see the same behaviour. Also no errors in logs.

**Comment by alandtse** [comment]
Are you comfortable directly editing your alexalogin.py? If so, I want to see what happens if you make each of these edits.
It should be at line [55](https://gitlab.com/keatontaylor/alexapy/blob/master/alexapy/alexalogin.py#L55) to add one additional line.

Original:
```python
        self._ssl = ssl.create_default_context(
            purpose=ssl.Purpose.SERVER_AUTH, cafile=certifi.where()
        )
        self._cookies: Optional[Dict[Text, Text]] = {}
```
Option 1 (False):
```python
        self._ssl = ssl.create_default_context(
            purpose=ssl.Purpose.SERVER_AUTH, cafile=certifi.where()
        )
        self._ssl = False
        self._cookies: Optional[Dict[Text, Text]] = {}
```
Option 2 (None):
```python
        self._ssl = ssl.create_default_context(
            purpose=ssl.Purpose.SERVER_AUTH, cafile=certifi.where()
        )
        self._ssl = None
        self._cookies: Optional[Dict[Text, Text]] = {}
```

I'm wondering if all the disconnect errors are from enforcing SSL. When we had requests in the v1.x branch, we basically didn't check the SSL cert.

**Comment by Dielee** [comment]
I have tried both and nothing changed. 

After the changes I have done an HA reboot, right ?

**Comment by alandtse** [comment]
Ok, try replacing your alexawebsocket with this [version](https://gitlab.com/keatontaylor/alexapy/blob/49666e47adc1922cf4cbc825b8da6701e7cc9856/alexapy/alexawebsocket.py).

You can remove the other change for now. 

Yes please HA reboot.

**Comment by Dielee** [comment]
This seems to be working!

**Comment by alandtse** [comment]
@Dielee Great! Oddly enough, for German domains it shouldn't have changed anything since we were hardcoding for Germany detection. Please monitor as you may run into the connection reset bug and that may also cause this behavior.

**Comment by Dielee** [comment]
Thank you! I will monitor my ha log for the next few days.

**Comment by Beertje135** [comment]
I think this maight be a solution.
When I don't have the ConnectionReseterror The states are reported!

thank you! great work

**Comment by manuelrosa87** [comment]
Hi, with version 2.2.1 you have solved!!! Thanks!!
