### ISSUE TITLE
Change "standby" status to "idle"

### ISSUE THREAD

**Issue by SqyD** [custom-components/alexa_media_player#394]
**Describe the bug**
The media_player entities provide by this component currently report their state as "standby" when nothing is playing. Changing this to "idle" will make it conform better to HA standards and make a universal media player that includes an alexa as a child behave as expected.

**To Reproduce**
* Create a universal media player: https://www.home-assistant.io/components/universal/
* Add an Alexa media player as the first child and at least one other one of any platform.
* Check that the Alexa device is in standby.
* Start any other child media player.
* The active_child attribute will remain the first alexa device, in "standby"

**Expected behavior**
You would expect to have the universal player switch to the active player when another device is on "idle". Workaround: a state_template that replaces standby for idle, it works as expected.

**System details**
 - Home-assistant (version): 99.2
 - Hassio (Yes/No): yes
 - alexa_media  (version from `const.py` or HA startup): 2.2.1
 - alexapy (version from `pip show alexapy` or HA startup): 1.2.1

**Comment by alandtse** [comment]
Do you have a document from HA that shows the difference between idle and standby? We currently use idle to indicate that there's a playlist loaded and it's not paused or playing. Standby is the default state without any playlist loaded.

**Comment by alandtse** [comment]
One thing to note, it's possible the Universal player needs to be updated to recognize the standby state as an OFF state. It currently [doesn't](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/universal/media_player.py#L86). It's an older component so who knows if standby existed when it was first added.

**Comment by SqyD** [comment]
On the [Universal media player documentation page](https://www.home-assistant.io/components/universal/) it states "The Universal Media Player will control the first child on the list that is active (not idle/off)."

**Comment by SqyD** [comment]
Agreed. That would be a more sustainable option. I'll file a feature request with the HA project. Thanks again for your amazing work on this!

**Comment by alandtse** [comment]
If they don't want to make the change, let me know. I'm not rejecting the idea, I just want to make sure we're consistent. One thing is we are actually following how Alexa indicates its current state.

**Comment by mustafaguven** [comment]
how about this option? it seems still not working
