### ISSUE TITLE
Multiple events are sent when a timer is created or completed

### ISSUE THREAD

**Issue by Infi-St** [custom-components/alexa_media_player#399]
Multiple events, all with the state of the next_timer object being milliseconds apart are created.
Here are a few examples:
https://i.imgur.com/SS64QUA.png
https://i.imgur.com/Z8k0Pcs.png

Maybe change the resolution of the timer down to the second? or dont send multiple updates for the same timer?

**Comment by alandtse** [comment]
This is what Alexa does. It sends multiple updates. Just take the latest.

**Comment by alandtse** [comment]
So the clarify, if you look at the logs you'll see that Alexa will create multiple websocket events as it creates or deletes a sensor. However, the events only indicate something was changed; not what actually happened.  We are updating on every such event so as to not lose any information and that is what is being exposed.

The way to use the timestamp is probably to set a timer at that time and before triggering your event, verify it's still live. It'll only disappear from the sensor if you manually stop it.

**Comment by Infi-St** [comment]
Thanks for the information.  I can use that to workaround it.
