### ISSUE TITLE
Unknown error: expected string or bytes-like object during configuration

### ISSUE THREAD

**Issue by tulindo** [custom-components/alexa_media_player#401]
Home Assistant 0.99.3, alexy py 1.3.1, alexa media player 2.3.0

Adding alexa media player informations (username, password and amazon domain) in configuration.yaml and starting HA, I correctly get a notification saying that a new device needs to be configured.
Click configure and capcha popup appears but when I insert the capcha I'm getting a red message:
Unknown error, please report with logs

Please find log attached.
  Paolo
PS: Same error in case of manual integration

[home-assistant.log](https://github.com/custom-components/alexa_media_player/files/3670957/home-assistant.log)

**Comment by alandtse** [comment]
Do you see the pop-up asking you to select sms or email? Or does that not show up at all?

I may also need you to enable Advanced Debugging and then provide the post.html and get.html file that is in your config directory right as you get this error.

**Comment by tulindo** [comment]
Hi Alan, sorry for delay. The popup does not appear.
Here you are the requested files.

[files.zip](https://github.com/custom-components/alexa_media_player/files/3681745/files.zip)

**Comment by mattnewham** [comment]
Same here - after every HA reboot the component attempts to re-authorise with Amazon but nothing appears in the popup. Pressed it a couple of times then the notification disappeared but still doesnt work (nothing plays from the device when triggering my automation)

**Comment by alandtse** [comment]
The issue appears to be we're not properly handling the verification page through the config_flow. This will be my next item before next release.
