### ISSUE TITLE
next_alarm not parsed correctly for MusicAlarm

### ISSUE THREAD

**Issue by ronmichel** [custom-components/alexa_media_player#402]
**Bug description**: next_alarm not parsed correctly if  `"type":"MusicAlarm"`

- Alarm is set and ON
- Following data is shown on https://alexa.amazon.de/api/notifications:
`{"notifications":[{"alarmTime":1569993300000,"automationId":null,"createdDate":1564129492110,"deferredAtTime":null,"deviceSerialNumber":"X010XX123456789X","deviceType":"A3S5BH2HU6VAYF","extensibleAttribute":null,"geoLocationTriggerData":null,"id":"A3S5BH2HU6VAYF-G090LF107185157H-be6e3935-5132-3df4-949d-4e2cc032ecae","lastOccurrenceTimeInMilli":0,"lastUpdatedDate":0,"musicAlarmId":"6f8c50e0-382b-4445-b201-73bd5f312982","musicEntity":"BAYERN 3","notificationIndex":"be6e3935-5132-3df4-949d-4e2cc032ecae","originalDate":"2019-10-02","originalTime":"07:15:00.000","personProfile":null,"provider":"TuneIn","rRuleData":null,"recurrenceEligibility":false,"recurringPattern":"XXXX-WD","remainingTime":0,"reminderAppLabel":null,"reminderLabel":null,"reminderSubLabel":null,"skillInfo":null,"snoozedToTime":null,"sound":{"displayName":"Simple Alarm","folder":null,"id":"system_alerts_melodic_01","providerId":"ECHO","sampleUrl":"https://s3.amazonaws.com/deeappservice.prod.notificationtones/system_alerts_melodic_01.mp3"},"status":"ON","targetPersonProfiles":null,"timeZoneId":null,"timerLabel":null,"tmwNotificationProperties":null,"triggerTime":0,"type":"MusicAlarm","version":"424"}]}`
- Sensor in HA shows:
```
state: null
recurrence: null
total_active: 0
total_all: 0
sorted_active: []
sorted_all: []
friendly_name: Echo next Alarm
icon: mdi:alarm
device_class: timestamp
```
**Expected**: 1 active alarm, set at 7:15 weekdays (together with and like `"type": "Alarm"`)

**Comment by alandtse** [comment]
Didn't know those existed. What are the steps to create one so I can replicate?

**Comment by alandtse** [comment]
Just to confirm, the preference would be to just group this with the Alarm sensor and not create a special run right?

**Comment by ronmichel** [comment]
Yes, just group together with Alarm sensor. You cannot create this alarm in the app.
To replicate use: `Alexa, wake me up at 7:30 with [any Tunein Radio Station or Amazon Music Title]`
