### ISSUE TITLE
Is it possible to know who last talked to alexa?

### ISSUE THREAD

**Issue by Infi-St** [custom-components/alexa_media_player#404]
if i ask alexa, "who am i?" she knows my name.  Is it possible to get that information, eg a last_called_by attribute?

volume_level: 0.5
is_volume_muted: false
media_content_type: standby
media_position_updated_at: 2019-10-01T22:10:52.787389+00:00
source: Local Speaker
source_list: Local Speaker
available: true
last_called: true
friendly_name: Office echo dot
supported_features: 56253

**Comment by alandtse** [comment]
No idea. 
Does this [page](https://alexa.amazon.com/api/activities?startTime=&size=10&offset=1) show you anything you think that relates to you specifically?  You may have to change the region domain.

The other question is whether websockets shows anything. I don't actually have voices defined so no idea if there's an identifier being stored somewhere on Alexa's [endpoints](https://github.com/custom-components/alexa_media_player/wiki/Known-Endpoints). If you see something to hook into, we can try to expose it.

**Comment by Infi-St** [comment]
Nope. Nothing there that exposes who was talking.  Thanks for looking into it.
