### ISSUE TITLE
Notification Priority

### ISSUE THREAD

**Issue by MYeager1967** [custom-components/alexa_media_player#407]
I have noticed that notifications using the "push" mode for mobile devices can be seriously delayed. Is there any chance that Amazon has any kind of priority flag that can be set so that notifications are nearly immediate?

**Comment by alandtse** [comment]
Not that I can see. How serious is the delay? Like minutes or longer? It's possible that it is queuing up requests if you have a lot of devices that are also updating. I can investigate whether that queue can be manipulated.

**Comment by MYeager1967** [comment]
Well, there was a 14 minute difference between a notification reaching my phone, and my wife's. That said, I believe it to be an Android issue with the phone possibly sleeping. Might have to look for a more insistent type of notification that comes through anyhow (like an SMS) for important notifications. Most of what I'm using it for is a daily report on solar production (after sunset) and an afternoon notification of pool and domestic hot water temperatures. 

I was wanting to use it for garage door notices (especially left open)...

**Comment by MYeager1967** [comment]
I was trying to get separate notifications to two different phones for different things, now I'm getting two of each notification on each phone. Any idea how to get back to just one notification each? I had added the second account but have since removed it when I couldn't get it to only send to one phone.
