### ISSUE TITLE
Some Active_Timers never disappear

### ISSUE THREAD

**Issue by Infi-St** [custom-components/alexa_media_player#408]
Im not sure how to reproduce, or how to fix.  But i created multiple "Grill" timers, and one of them never left the sorted_active array.  I have worked around this by ignoring timers that have expired in the past.. but thought it should be reported.

recurrence: Never Repeat
total_active: 1
total_all: 3
sorted_active: [["ad06d77a-6062-3e98-bf96-cd3b5940753a", {"alarmTime": 0, "automationId": null, "createdDate": 1570228425936, "deferredAtTime": null, "deviceSerialNumber": "G190LF1182140XT0", "deviceType": "A4S5BH2HU6VAYF", "extensibleAttribute": null, "geoLocationTriggerData": null, "id": "A4S5BH2HU6VAYF-G190LF1182140XT0-ad06d77a-6062-3e98-bf96-cd3b5940753a", "lastOccurrenceTimeInMilli": 0, "lastUpdatedDate": 0, "musicAlarmId": null, "musicEntity": null, "notificationIndex": "ad06d77a-6062-3e98-bf96-cd3b5940753a", "originalDate": null, "originalTime": null, "personProfile": null, "provider": null, "rRuleData": null, "recurrenceEligibility": false, "recurringPattern": null, "remainingTime": 0, "reminderAppLabel": null, "reminderLabel": null, "reminderSubLabel": null, "skillInfo": null, "snoozedToTime": null, "sound": {"displayName": "Simple Timer", "folder": null, "id": "system_alerts_melodic_02", "providerId": "ECHO", "sampleUrl": "https://s3.amazonaws.com/deeappservice.prod.notificationtones/system_alerts_melodic_02.mp3"}, "status": "ON", "targetPersonProfiles": null, "timeZoneId": null, "timerLabel": "Grill", "tmwNotificationProperties": null, "triggerTime": 0, "type": "Timer", "version": "2", "date_time": "None None"}]]
sorted_all: <<<<Edit: See History if you need this array>>>>
friendly_name: Hallway next Timer
icon: mdi:timer
device_class: timestamp

**Comment by alandtse** [comment]
Interesting. Do you see the extra timer on the notifications page? https://alexa.amazon.com/api/notifications if so what state is it under?

**Comment by Infi-St** [comment]
It does show up there, status is OFF

{"alarmTime":0,"automationId":null,"createdDate":1570231093203,"deferredAtTime":null,"deviceSerialNumber":"G190LF1182140XT0","deviceType":"A4S5BH2HU6VAYF","extensibleAttribute":null,"geoLocationTriggerData":null,"id":"A4S5BH2HU6VAYF-G090LF1182140XT0-96c60ca9-9f5c-322f-bf96-681c96ccb0c9","lastOccurrenceTimeInMilli":0,"lastUpdatedDate":0,"musicAlarmId":null,"musicEntity":null,"notificationIndex":"96c60ca9-9f5c-322f-bf96-681c96ccb0c9","originalDate":null,"originalTime":null,"personProfile":null,"provider":null,"rRuleData":null,"recurrenceEligibility":false,"recurringPattern":null,"remainingTime":0,"reminderAppLabel":null,"reminderLabel":null,"reminderSubLabel":null,"skillInfo":null,"snoozedToTime":null,"sound":{"displayName":"Simple Timer","folder":null,"id":"system_alerts_melodic_02","providerId":"ECHO","sampleUrl":"https://s3.amazonaws.com/deeappservice.prod.notificationtones/system_alerts_melodic_02.mp3"},"status":"OFF","targetPersonProfiles":null,"timeZoneId":null,"timerLabel":null,"tmwNotificationProperties":null,"triggerTime":0,"type":"Timer","version":"4"},

**Comment by Infi-St** [comment]
Restarting HA seems to have fixed it.  Ill close this for now, and if i run into again, ill get some better data. Thanks
