### ISSUE TITLE
The status of the battery-powered devices is not updated when turned on

### ISSUE THREAD

**Issue by funkschrauber** [custom-components/alexa_media_player#420]
**Describe the bug**
Devices that are turned on will still be displayed as unavailable.
I have a battery powered echo with switch. If this is switched on, the status will not be available.

**To Reproduce**
1. Turn on the echo
2. Status not available

**Expected behavior**
When I turn on my battery powered echo, it should be displayed as Available. That is not so. Even the currently playing radio station is no longer displayed.

**Screenshots**

**System details**
 - Home-assistant (version): 0.99.3
 - Hassio (Yes/No): YES
 - alexa_media  (version from `const.py` or HA startup): 2.3.1
 - alexapy (version from `pip show alexapy` or HA startup): 1.3.2

**Logs**
[halog.txt](https://github.com/custom-components/alexa_media_player/files/3707016/halog.txt)

Continuation from #397

**Comment by alandtse** [comment]
What's the entity name of the battery powered device in the logs?

**Comment by funkschrauber** [comment]
By switch garten and garage are turned on.
On the page, all devices are displayed as online: False. 
Only the two Fire TV sticks are displayed as online.

**Comment by alandtse** [comment]
To confirm you fixed the domain to .de when looking at the page?

**Comment by funkschrauber** [comment]
OK. Then the status is online.

**Comment by alandtse** [comment]
Can you please generate logs where you turn on the `garten` or `garage` devices and then change their volume or force them to play? And only those items? They are being discovered by the component and should update as soon as a websocket event is detected. 

Please search by their serial number after you've confirmed they report as online. If you let me know the last 3 serial numbers digits I can then also review your logs.

**Comment by funkschrauber** [comment]
Here is the desired file.
The device garden was switched on (last 3 serial numbers digits 8k9) at 10:53, then select radio KW, louder per speak and then over key press.

[alexa_log.log](https://github.com/custom-components/alexa_media_player/files/3720421/alexa_log.log)

**Comment by alandtse** [comment]
Is it not updating still? The logs are reporting changes.
```
2019-10-12 10:54:54 DEBUG (MainThread) [custom_components.alexa_media.media_player] Garten state update: PLAYING
```

**Comment by funkschrauber** [comment]
No, status remains unavailable.

![bild](https://user-images.githubusercontent.com/53475532/66699055-b6326c80-ece3-11e9-8a8c-be6c10d9c583.JPG)

**Comment by funkschrauber** [comment]
Here is a more recent file, where garage (f3j) was turned on, but otherwise there were no other functions performed.
Then garten was switched on again and played radio KW. Volume up by button.

[home-assistant.log](https://github.com/custom-components/alexa_media_player/files/3720459/home-assistant.log)


![bild](https://user-images.githubusercontent.com/53475532/66699186-c1d26300-ece4-11e9-99e4-2b6973823ed3.JPG)

**Comment by alandtse** [comment]
Please test #431

**Comment by funkschrauber** [comment]
During reboot, both devices are displayed offline (are switched off). After a while both devices will be displayed as standby, even though they are switched off.

[home-assistant.log](https://github.com/custom-components/alexa_media_player/files/3721605/home-assistant.log)

**Comment by alandtse** [comment]
We need a websocket event showing they turned off. Do you see anything?

**Comment by funkschrauber** [comment]
As I wrote above, I did a reboot. Thereafter, the devices were displayed as offline (are also off)
After a while without me doing anything, they are on standby.
Log file hangs.

[home-assistant.log](https://github.com/custom-components/alexa_media_player/files/3721614/home-assistant.log)

**Comment by funkschrauber** [comment]
![bild2](https://user-images.githubusercontent.com/53475532/66715529-b8202c80-edc4-11e9-9c7c-a51627af0254.JPG)


[home-assistant.log](https://github.com/custom-components/alexa_media_player/files/3721715/home-assistant.log)

Here is a current log file.
HA Reboot. Garten and Garage shows in HA Standby, on the other side they are offline (see Picture)
Garage was switched on, garden was switched on.
Radio KW was played on garten and finished again.
Garten shut off, garage shut off.

After that:
The status on both sides stays online

![bild3](https://user-images.githubusercontent.com/53475532/66715623-b99e2480-edc5-11e9-9b1a-3b5ce2a4265e.JPG)

**Comment by alandtse** [comment]
Moving the issue to a new thread since.
