### ISSUE TITLE
Alexa components not updating

### ISSUE THREAD

**Issue by cunninr2** [custom-components/alexa_media_player#430]
**Describe the bug**
The alexa devices in my house have stopped updating the media status and associated meta data.

**To Reproduce**
1. Wipe alexa media player from home assistant installation. remove all references in configuration files and remove pickle file.
2. Install alexa media player from HACS and then add the integration and enter credentials with amazon.co.uk as the services url.
3. reboot Hassio twice as recommended
4. instruct echo dot to play song from amazon music.
5. songs plays and media player component shows the status as playing and the correct meta data for the song
6. ask echo dot to pause. Echo dot does pause, but home assistant component status does not change.
7. ask echo dot to play new song. echo dot plays new song but media component in home assistant does not update.

**Expected behavior**
expected metadata to update within a few seconds of media changing.

**Screenshots**

**System details**
 - Home-assistant (version): 0.100.1
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): __version__ = '2.3.2'
 - alexapy (version from `pip show alexapy` or HA startup): v2.3.2

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

log attached. 

[log file.txt](https://github.com/custom-components/alexa_media_player/files/3720959/log.file.txt)
![Capture](https://user-images.githubusercontent.com/25829766/66705384-e0088500-ed1d-11e9-9960-7bf2d63f0501.PNG)

**Additional context**

**Comment by alandtse** [comment]
Thanks. It looks like #397 is still an issue.

**Comment by alandtse** [comment]
Please try 2.3.3 and reopen if issue still exists.

**Comment by cunninr2** [comment]
Thank you. Working again.
