### ISSUE TITLE
Feature Request: Ability to enable/disable alarms

### ISSUE THREAD

**Issue by gadgetchnnel** [custom-components/alexa_media_player#437]
**Is your feature request related to a problem? Please describe.**
I will sometimes forget to disable an Alexa alarm if I don't need to get up early the next day (e.g. I am on holiday or it is a public holiday) or, if I o remember to disable it, I forget to re-enable it when I need it.

**Describe the solution you'd like**
If this is possible via the Alexa API, I would like a way to disable or re-enable an alarm, either by some sort of switch or a service call. A service call would probably be the most practical as there may be multiple alarms configured on a device and there would need to be a way to pass the id of the alarm to disable/enable. This would allow an automation to disable or enable alarms based on things such as calendar events, etc.

**Describe alternatives you've considered**
I am currently using an alternative method, in which I use an automation (which takes calendar events into account) to trigger a routine on the Alexa device using this component but I would like to be able to make use of the standard Alexa alarm functionality.

**Additional context**

**Comment by alandtse** [comment]
If you can find the API call I can add it in. I believe some of the Alexa remote projects may have figured it out.

**Comment by gadgetchnnel** [comment]
I've tested using the Alexa website, and it looks like enabling/disabling an alarm is done by making a **PUT** request to this URL:

https://alexa.amazon.*domain*/api/notifications/*alarm_id*

Where *alarm_id* is the value of the **id** property of the JSON object for the alarm you want to enable or disable (this appears to be a compound id in the format *deviceType*-*serialNumber*-*unique alarm id*).

The body of the request appears to be JSON object retrieved for that alarm with the **status** property set to "ON" or "OFF" depending on what you want to enable or disable the alarm.

It looks like other things, such as the alarm sound and the time of the alarm could also be changed in the same way, by setting the updated values in the JSON.

**Comment by jaburges** [comment]
+1 this would be great to tap into the Alexa wake up alarm. I like many wake up at different times each morning, and simply setting the alarm via Alexa is great.....BUT.... it doesn't allow me to trigger anything (like brighten lights etc) when it goes off (or even smarter intercept the alarm time, and use node-red to start a wake sequence 10ish minutes before).

**Comment by gadgetchnnel** [comment]
@jaburges If what you want to do is trigger things in Home Assistant based on the alarm going off, you can use the alarm time sensors (sensor.*device_name*_next_alarm) for this. Here is an automation I created, which turns on a light when the alarm goes off:

```
- id: alarm_clock_goes_off
  alias: Alarm Clock Goes Off
  trigger:
  - platform: template
    value_template: '{{ states.sensor.date_time_iso.state == as_timestamp(states.sensor.bedroom_next_alarm.state)
      | timestamp_local | replace('' '',''T'') }}'
  action:
  - entity_id: light.bedside_light
     service: light.turn_on
```
This requires this sensor:

```
- platform: time_date
  display_options:
    - 'date_time_iso'
```

I don't use Node-RED, but you should probably also be able to make use of the sensors using that to trigger something to happen at or slightly before the alarm time.

**Comment by alandtse** [comment]
As I believe the official [HA component allows](https://github.com/home-assistant/core/pull/32616) this now, I'll close this. Please let me know if I'm wrong.

**Comment by broyuken** [comment]
> @jaburges If what you want to do is trigger things in Home Assistant based on the alarm going off, you can use the alarm time sensors (sensor._device_name__next_alarm) for this. Here is an automation I created, which turns on a light when the alarm goes off:
> 
> ```
> - id: alarm_clock_goes_off
>   alias: Alarm Clock Goes Off
>   trigger:
>   - platform: template
>     value_template: '{{ states.sensor.date_time_iso.state == as_timestamp(states.sensor.bedroom_next_alarm.state)
>       | timestamp_local | replace('' '',''T'') }}'
>   action:
>   - service: light.turn_on
>     entity_id: light.bedside_light
>      
> ```
> 
> This requires this sensor:
> 
> ```
> - platform: time_date
>   display_options:
>     - 'date_time_iso'
> ```
> 
> I don't use Node-RED, but you should probably also be able to make use of the sensors using that to trigger something to happen at or slightly before the alarm time.

How would you do this to start the automation say 10 minutes before the alarm goes off? Is there a way to say like 

as_timestamp(states.sensor.bedroom_next_alarm.state - 00:10:00 

or something like that?

**Comment by alandtse** [comment]
@broyuken Yes. Subtract 600 seconds. 
```
- id: alarm_clock_goes_off
  alias: Alarm Clock Goes Off
  trigger:
  - platform: template
    value_template: '{{ states.sensor.date_time_iso.state == as_timestamp(states.sensor.bedroom_next_alarm.state) - 600
      | timestamp_local | replace('' '',''T'') }}'
  action:
  - service: light.turn_on
    entity_id: light.bedside_light

**Comment by gadgetchnnel** [comment]
@alandtse I looked at this and realised that the functionality which was added in the official Alexa component in the linked PR is actually the opposite of this request. The official component allows Home Assistant timers to be enabled/disabled from Alexa, rather than allowing Alexa timers or alarms to be enabled/disabled from Home Assistant.
