### ISSUE TITLE
BBC sounds does not display on media player entity

### ISSUE THREAD

**Issue by lonebaggie** [custom-components/alexa_media_player#438]
All BBC radios  stations have now been removed from tunein which works perfectly with the media player 

Now BBC stations do not appear on the media player when played via BBC sounds , it  just displays standby. 

This is now the default behaviour of  all BBC stations in the UK when invoked by alexa . "Alexa play BBC radio 1"  this will only  play via BBC sounds 

Is  this an issue with the BBC app ?

**Comment by alandtse** [comment]
Does it display in the Alexa app?

**Comment by lonebaggie** [comment]
It appears in the activity menu  with the correct bbc logo, but it does not appear in the play (music and books)  recently played list

tune-in radio stations  do appear  recently played list

**Comment by alandtse** [comment]
Unfortunately, we're basically limited to the now playing functionality to show up as a media player.

**Comment by alandtse** [comment]
Closing out the issue since it's a BBC app issue. You may consider asking them to make it work with  the Now Playing section
