### ISSUE TITLE
[Feature Request] :- SSML Audio Tag

### ISSUE THREAD

**Issue by Datulipan** [custom-components/alexa_media_player#439]
First off... This component is AWESOME!

I would really love to be able to announce with a tone from the Alexa Skills Kit Sound Library.
https://developer.amazon.com/docs/custom-skills/ask-soundlibrary.html

I'm working an an alteration of Hook-up's Doorbell and I'd like to use Alexa to announce that someones at the door. But don't want Alexa to speak the announcement.

If anyone has an alternative to the SSML Audio Tag, to play tones and not permanently interrupt Alexa from playing whatever it's playing, then I love to hear it... 

Sooner rather than later please as I don't want the misses to pull the project :)

**Comment by alandtse** [comment]
This is not supported by Amazon so I don't think we can provide that support. As soon as you can run a routine doing what you want in the Alexa App, we can then simulate it.

**Comment by alandtse** [comment]
Closing; please reopen as soon as Amazon allows support through routines.

**Comment by tiagofreire-pt** [comment]
@alandtse , is possible to add support for MP3 playing, through SSML?

https://github.com/dabblelab/dabblelab-youtube-channel/tree/master/2017-tutorials/2017-08-11-playing-mp3-files

```
data:
  type: announce
  method: all
message: "<audio src='https://s3.amazonaws.com/cdn.dabblelab.com/audio/one-small-step-for-man.mp3'>"
```

This triggers the Echo Dot blue ring but no MP3 sound is emitted.

**Comment by alandtse** [comment]
@tiagofreire-pt I don't think so. The tutorial you linked is about programming a custom skill. Since amp isn't a skill, but instead mimicking the web client, I don't think we have the same access to SSML. I did try your example playing with different escaping and had same issue you reported of it announcing without any sound.
