### ISSUE TITLE
All next alarms are stored in wrong timezone after time change

### ISSUE THREAD

**Issue by mammuth** [custom-components/alexa_media_player#452]
In Germany a (recurring) time change happened on 27.10.2018. One hour was added to the time, moving Germany's timezone from UTC+2 to UTC+1.

My sensor for the next alarm was still in UTC+2 and thus one hour earlier than the real alarm on the echo. 
The alarm was created after the time change occured. 

Alarms I created just now for testing purposes are still stored with the wrong timezone. A restart of home assistant did not resolve this issue. 
The echo devices report the time correctly and also trigger the alarms at the correct time. 

Edit: after some more testing around the original alarm is now suddenly reported with the correct timezone. It didn't trigger yet on the echo device (but other test alarms did). I'm not sure what caused it to be correct now.

**Comment by alandtse** [comment]
The timezone is collected from the individual echo devices on startup. It's possible there was an issue with propagating the timezone based off when the information was pulled.

Let me know if the issue persists; if it looks like it self resolved, please close.

**Comment by mammuth** [comment]
Well it's resolved for now, but as you described the process, it will be broken again for some people at the next times change I assume.

**Comment by alandtse** [comment]
@mammuth It's not an expensive request per se, but it seems wasteful to check it constantly given how seldom time zone changes happen and how often HA tends to get rebooted. It's under a different API than the [alarms](https://alexa.amazon.com/api/notifications) so it's not like it's free though. Perhaps we can pull it once a day assuming it actually has the info.

We are checking for the time zone by going to [device-preferences](https://alexa.amazon.com/api/device-preferences) and pulling the `timeZoneId`. Can you please pull your current value to see if it has anything in it that shows a timezone change?  The US just had a timezone change and it doesn't look like that value has anything showing the timezone.

**Comment by mammuth** [comment]
`"timeZoneId":"Europe/Berlin"`
It sadly doesn't directly provide the timezone offset (eg. `UTC+1` or the like). In my case it would probably always be `Europe/Berlin` (before and after the time change).

**Comment by alandtse** [comment]
Thanks for checking. I think this will be a hard one to debug since we'd need to have data from before and after the time change to figure out how Amazon is handling the time change. My guess since it self-resolved for you is that the Amazon device is responsible for handling the change.

**Comment by skyrider456** [comment]
I had this issue on the US Eastern Time Zone too. The Echo device reported the time correctly when viewed directly, but it was skewed an hour when converted to a timestamp and then back into a time:   (as_timestamp(states(''sensor.echo_dot_next_alarm'')) | timestamp_custom(''%Y-%m-%d,
      %H:%M''))
I ultimately worked around it by adding 3600 before the |

**Comment by mammuth** [comment]
Should be still an issue. In Germany the envy time zone change is at October 25th.
