### ISSUE TITLE
Multiple TTS requests works sporadically due to http 429 Too Many Requests

### ISSUE THREAD

**Issue by Flight777** [custom-components/alexa_media_player#454]
Hi all,

First of all, thanks for your efforts in getting Alexa more integrated in our home automation set-ups :)

I've encountered a small, but annoying issue, making the TTS component quite unreliable at the moment.

Using latest versions of HassIO, NodeRed and Alexa Media Player.

My Alexa devices are a mix of Sonos One speakers and Echo devices. I've created a mixed group of 6 devices in my group.yaml.

Now I'm invoking the notify service in TTS mode (due to the non working announcement on Sonos currently). This seems to work sporadically. Sometimes all speakers are activated, as they should, sometimes only one or a few and sometimes none. This is especially if it's triggered in relative short successions (like 1-2 min in between triggers) with testing.

It's kind of essential to work always, because I want to let Alexa announce that somebody rang the doorbell XD

How can I best troubleshoot this to give you the information you need?

Thanks,

Rob

**Comment by poudenes** [comment]
I have similar problem. I only have 1 Echo Dot. Sometimes it speak out the announcements and sometimes I only see white line (change volume). Since I put a delay between volume change and the annoucements of 5 seconds this seems to be solved.

**Comment by Flight777** [comment]
How did you do that exactly?

**Comment by alandtse** [comment]
@Flight777 please provide logs per the template showing the attempt to send TTS. One thing to confirm is that it isn't related to hitting all the different devices. Is it possible to reduce it to a single device to see if we can get that consistent at least?

Another issue is that if you issue too many commands, I think Amazon may throttle what comes in at a time. This is particular an issue if you do volume changes before TTS.

**Comment by Flight777** [comment]
@alandtse Please see attached log file, I hope this gives you some more info? 👍 
[Alexa_Media_Player_Log.txt](https://github.com/custom-components/alexa_media_player/files/3811335/Alexa_Media_Player_Log.txt)

**Comment by alandtse** [comment]
Ok I see the error. Amazon is rejecting the multiple requests because they're coming too close to each other. 
```
429:Too Many Requests:text/html
```
While we could include logic to retry the send, the issue would be this may result in the TTS being delayed. Would your use case break assuming there were further delays for the TTS? While I know TTS doesn't work on your Sonos, I may recommend that you do an announce to an Amazon group for all other devices (which should be a single call) and then separately send a TTS for the Sonos device.

**Comment by Flight777** [comment]
@alandtse  
Thanks for checking and spotting that.

Do you mean the TTS is delayed for each individual speaker? Depending on the time of delay that is not an immediate problem per se, as long as I get the notification everywhere in the house that the doorbell is ringing within a few second from it being pressend.

Thanks for the suggestion, that would've worked but the majority of my set-up is Sonos, only a few real Echo Devices.

**Comment by alandtse** [comment]
@Flight777 There's currently an update staged for [alexapy](https://gitlab.com/keatontaylor/alexapy/merge_requests/92) that should try to queue multiple sequences at once including notify commands. If you're on the latest version of alexa_media, please see if this helps.

**Comment by alandtse** [comment]
I believe this should be closed by 2.4.x, please open a new issue if it hasn't been.
