### ISSUE TITLE
Feature request: Bluetooth device tracker

### ISSUE THREAD

**Issue by alandtse** [custom-components/alexa_media_player#456]
Anyone see any value in having a bluetooth device tracker? This would need to be tested to make sure it didn't break anything so I wouldn't implement this without some volunteers to test it.

**Comment by alandtse** [comment]
Biggest downside I could see is that it requires sending a command to each echo device through Amazon so it might be too spammy to Amazon's API.

**Comment by phillprice** [comment]
Willing to test. It could be limited to an action based POST, rather than on an interval (say a door opens and I'm currently home then wait a few minutes then scan etc.

**Comment by jeroenjoosse** [comment]
If an Alexa bluetooth scan would return enough data to use it with [monitor](https://community.home-assistant.io/t/monitor-reliable-multi-user-distributed-bluetooth-occupancy-presence-detection/68505), it could be really awesome for presence detection. Monitor has previously been used with Google home until Google changed their API.

**Comment by gadgetchnnel** [comment]
I'd love to test something like this if it would allow in house device tracking if we have Alexa devices in different rooms.

**Comment by mrand** [comment]
While I would hope that they wouldn't complain (and might not even notice), I'd hate for the device tracker feature to create so much traffic that Amazon changes some rules about things - or worse, deletes some features.

**Comment by CMaxim77** [comment]
I would absolutely love to implement this, it’s the missing piece to true automations

**Comment by donnlee** [comment]
I use room-assistant on a Pi Zero W for room-to-room presence. If AMP can do something like that, then I could remove the Zero W's in rooms that have Echo devices.  That would be nice

**Comment by skynet01** [comment]
Another vote for this. I think a lot of us have more then one Alexa in our homes would be amazing if we can also use them just like Pi Zero W - Monitor scripts you can then have fairly accurate room presence detection. Not sure how that's possible but would be amazing :)

**Comment by mrand** [comment]
Can feature requests be left open?
