### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by eifinger** [custom-components/alexa_media_player#463]
**Describe the bug**
Since today the component logs stracktraces

**To Reproduce**
1. Restart homeassistant

**Expected behavior**
No stacktraces.

**Screenshots**
N/A

**System details**
 - Home-assistant (version): 0.98.5
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): 2.3.4
 - alexapy (version from `pip show alexapy` or HA startup): 1.32

**Logs**
```
Update for sensor.kevins_echo_dot_oben_next_alarm fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 261, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 439, in async_device_update
    await self.async_update()
  File "/config/custom_components/alexa_media/sensor.py", line 274, in async_update
    self._all = list(map(self._fix_alarm_date_time, self._all))
  File "/config/custom_components/alexa_media/sensor.py", line 174, in _fix_alarm_date_time
    naive_time = dt.parse_datetime(value[1][self._sensor_property])
  File "/usr/src/homeassistant/homeassistant/util/dt.py", line 133, in parse_datetime
    match = DATETIME_RE.match(dt_str)
TypeError: expected string or bytes-like object
```

**Additional context**
N/A

**Comment by rwarner** [comment]
Am also getting this problem. Repeats over and over and over.

HomeAssistant 101.3
Alexa_media 2.3.4

**Comment by alandtse** [comment]
Are you still getting the error? I may need to get some specific logs to see what's causing the error.

**Comment by eifinger** [comment]
Seems to have disappeared from the logs

**Comment by alandtse** [comment]
I'll plan to close this in a few days unless someone is still seeing this.

**Comment by rwarner** [comment]
I also have not seen this error since... strange. Will report back if I do though. Still on 101.3 and upgraded to v2.3.6 alexa_media
