### ISSUE TITLE
One-time Password for Amazon account

### ISSUE THREAD

**Issue by k1ng440** [custom-components/alexa_media_player#464]
**Describe the bug**
Amazon account suddenly logged out and asking for OTP.

**To Reproduce**
1. try to authenticate using integrations

**System details**
 - Home-assistant (version):  0.101.3
 - Hassio (Yes/No): yes

**Logs**
```
2019-11-16 02:24:25 INFO (MainThread) [homeassistant.setup] Setting up alexa_media
2019-11-16 02:24:25 INFO (MainThread) [homeassistant.setup] Setup of domain alexa_media took 0.0 seconds.
2019-11-16 02:24:25 INFO (MainThread) [custom_components.alexa_media] 
-------------------------------------------------------------------
alexa_media
Version: 2.3.4
This is a custom component
If you have any issues with this you need to open an issue here:
https://github.com/custom-components/alexa_media_player/issues
-------------------------------------------------------------------

2019-11-16 02:24:25 INFO (MainThread) [custom_components.alexa_media] Loaded alexapy==1.3.2
```

**Comment by alandtse** [comment]
Provide the otp. Check your email as Amazon may have sent it there.

**Comment by k1ng440** [comment]
> Provide the otp. Check your email as Amazon may have sent it there.

I dont see any options to provide otp

**Comment by alandtse** [comment]
Remove the integration and relogin. It'll ask for the OTP there.

**Comment by k1ng440** [comment]
I have removed the integration and reinstalled component and then restarted the home assistant. still not asking for OTP
