### ISSUE TITLE
Can't use text to talk

### ISSUE THREAD

**Issue by closewall** [custom-components/alexa_media_player#467]
I'm running alexa_media_player from Home Assistant (via Docker Container), and whenever I enter something into text to speech, the Alexa says text to speech is only available with the notify.alexa service. How do I set this up? It wasn't anywhere in the installation instructions.

I do not understand this solution:

https://github.com/custom-components/alexa_media_player/issues/398

**Comment by alandtse** [comment]
Read the [documentation](https://github.com/custom-components/alexa_media_player/wiki/Notification-Component) please.

**Comment by closewall** [comment]
This documentation is utterly useless and doesn't explain anything I'm asking about. I don't even know how to add a service.

**Comment by closewall** [comment]
> 
> 
> Read the [documentation](https://github.com/custom-components/alexa_media_player/wiki/Notification-Component) please.

This documentation is utterly useless and doesn't explain anything I'm asking about. I don't even know how to add a service.
