### ISSUE TITLE
Using "Include" causes sensor.* to not be created

### ISSUE THREAD

**Issue by steve28** [custom-components/alexa_media_player#470]
**Describe the bug**
When configuring the integration if you use the "Include" list, then non of the sensor.* entities are created.

**To Reproduce**
Configure the integration and fill in an Echo in the "Include" field

**Expected behavior**
Timer sensor entries should be created

**Screenshots**

**System details**
 - Home-assistant (version): 0.102.3
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): 2.3.4
 - alexapy (version from `pip show alexapy` or HA startup): 1.3.2

**Logs**
N/A

**Additional context**
N/A

**Comment by alandtse** [comment]
Thanks. Include the sensors you want. This is how `include` [works](https://github.com/custom-components/alexa_media_player/wiki/Installation-and-Configuration#configuring-inclusions-or-exclusions-versions--096).

**Comment by alandtse** [comment]
If it turns out after following the documentation for identifying the timer sensor names it doesn't show up, then please reopen and we can debug it. We'll need your startup logs to see what's going on.
