### ISSUE TITLE
[Feature Request] Alexa plug support

### ISSUE THREAD

**Issue by borisfeldman** [custom-components/alexa_media_player#471]
It would be great to expose Alexa plugs to Home Assistant

**Comment by alandtse** [comment]
As I don't have any Alexa plugs, I'm not sure how to communicate with them. Once we get the information, we can try adding them.

**Comment by walthowd** [comment]
@alandtse I have a single Amazon Smart plug (US version) that I have no plans to ever use. If you are interested I'll pop it in the mail for you.

**Comment by alandtse** [comment]
@walthowd Thanks! That's generous of you. If your'e on the HA forums you can DM me and I'll provide my address or you can DM me on Discord alandtse#5464.

**Comment by walthowd** [comment]
@alandtse Sent you a message on Discord

**Comment by nkgilley** [comment]
I've been able to sniff my smart plug device ids and endpoints using HTTP Canary for android.  I am able to control them with curl commands.  I'm not sure how to get the device ids without manually sniffing though...

Here are my status and on/off commands:
```
device_status()
{
${CURL} ${OPTS} -s -b ${COOKIE} -A "${BROWSER}" -H "DNT: 1" -H "Connection: keep-alive" -L\
 -H "Content-Type: application/json; charset=UTF-8" -H "Referer: https://alexa.${AMAZON}/spa/index.html" -H "Origin: https://alexa.${AMAZON}"\
 -H "csrf: $(awk "\$0 ~/.${AMAZON}.*csrf[ \\s\\t]+/ {print \$7}" ${COOKIE})" -X POST\
 "https://${ALEXA}/api/phoenix/state" -d '{"stateRequests":[{"entityId":"'${STATUSID}'","entityType":"APPLIANCE"}]}'
}

device_on()
{
${CURL} ${OPTS} -s -b ${COOKIE} -A "${BROWSER}" -H "DNT: 1" -H "Connection: keep-alive" -L\
 -H "Content-Type: application/json; charset=UTF-8" -H "Referer: https://alexa.${AMAZON}/spa/index.html" -H "Origin: https://alexa.${AMAZON}"\
 -H "csrf: $(awk "\$0 ~/.${AMAZON}.*csrf[ \\s\\t]+/ {print \$7}" ${COOKIE})" -X PUT\
 "https://${ALEXA}/api/phoenix/state" -d '{"controlRequests":[{"entityId":"'${ONID}'","entityType":"APPLIANCE","parameters":{"action":"turnOn"}}]}'
}

device_off()
{
${CURL} ${OPTS} -s -b ${COOKIE} -A "${BROWSER}" -H "DNT: 1" -H "Connection: keep-alive" -L\
 -H "Content-Type: application/json; charset=UTF-8" -H "Referer: https://alexa.${AMAZON}/spa/index.html" -H "Origin: https://alexa.${AMAZON}"\
 -H "csrf: $(awk "\$0 ~/.${AMAZON}.*csrf[ \\s\\t]+/ {print \$7}" ${COOKIE})" -X PUT\
 "https://${ALEXA}/api/phoenix/state" -d '{"controlRequests":[{"entityId":"'${OFFID}'","entityType":"APPLIANCE","parameters":{"action":"turnOff"}}]}'
}
```

**Comment by alandtse** [comment]
@nkgilley thanks. You can query the phoenix api with a get to https://alexa.amazon.com/api/phoenix. It's how we get the Guard mode.

While we could initiate some sort of poll on the sensor, it's disfavored since you start really hammering the API per device. It'd be best if we could see some sort of websocket messaging at least for the state updates.

**Comment by alandtse** [comment]
Thanks to @walthowd I've confirmed there isn't any websocket info. We'll likely have to do some polling with the rest api.

**Comment by 89jd** [comment]
Any update on this? Tried to do some reverse engineering, and found same as above. I wanted to be able to communicate with the plug directly, but don't think its possible to sniff the traffic from the plug, as it seems to use certificate pinning

**Comment by alf1e** [comment]
Any news on this?
