### ISSUE TITLE
[Feature Request] Show playing state of Individual alexa devices if group is playing media

### ISSUE THREAD

**Issue by almostserious** [custom-components/alexa_media_player#472]
I'd like to throw this into the hat:

Current behaviour:
When an Alexa group is playing media, the individual players (within the Group) are shown as being on standby.

Expected behaviour:
When an Alexa group is playing media, all the individual players show the state of the playing media.

This is the same behaviour as we currently see for the Google Cast integration.

**Comment by almostserious** [comment]
I tried this pull request. The behavior of the individual players did not change for me. It is still the same as before, while the group is playing, the single players in the group are shown as on standby.

**Comment by alandtse** [comment]
See if #504 helps. You'll need to be already on 2.4.1.

**Comment by almostserious** [comment]
Tried it with #504 while being on 2.4.1.
However, neither with Spotify nor with Prime Music do the individual members of the group report as playing. Only the group itself

**Comment by alandtse** [comment]
Check 2.5.2 please.

**Comment by almostserious** [comment]
Confirmed working in 2.5.2. Thanks!
