### ISSUE TITLE
Alarm control panel stopped working in 0.103

### ISSUE THREAD

**Issue by arsaboo** [custom-components/alexa_media_player#474]
Just updated to the 0.103.b0 and realized that the alarm control panel is not working. The only thing that I see in the logs is:
```bash
2019-12-06 11:32:39 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Setup of platform alexa_media is taking longer than 60 seconds. Startup will proceed without waiting any longer.
```

The media player works fine. 

BTW, there was a similar error with alarm panel with another custom component ([Aarlo](https://github.com/twrecked/hass-aarlo/issues/131)) that had to be fixed.

**Comment by arsaboo** [comment]
I added the following to `alarm_control_panel.py` and it fixes the error. 

```python
    @property
    def supported_features(self) -> int:
        """Return the list of supported features."""
        """Make this non-dynamic later..."""
        try:
            c = __import__("homeassistant.components.alarm_control_panel.const",fromlist=['SUPPORT_ALARM_ARM_HOME', 'SUPPORT_ALARM_ARM_AWAY', 'SUPPORT_ALARM_ARM_NIGHT', 'SUPPORT_ALARM_TRIGGER'])
            _LOGGER.debug('supported: ' + str(c.SUPPORT_ALARM_ARM_HOME | c.SUPPORT_ALARM_ARM_AWAY | c.SUPPORT_ALARM_ARM_NIGHT | c.SUPPORT_ALARM_TRIGGER))
            return c.SUPPORT_ALARM_ARM_HOME | c.SUPPORT_ALARM_ARM_AWAY | c.SUPPORT_ALARM_ARM_NIGHT | c.SUPPORT_ALARM_TRIGGER
        except ModuleNotFoundError:
            _LOGGER.debug('not supported')
            return 0
```
[Here's](https://github.com/arsaboo/homeassistant-config/blob/master/custom_components/alexa_media/alarm_control_panel.py#L252) the updated file. I can create a PR if that is the best approach.

**Comment by alandtse** [comment]
Thanks. Probably need to just do `SUPPORT_ALARM_ARM_AWAY`. It's a fairly simple fix.

**Comment by DeviousPenguin** [comment]
I'm getting the same error

`2019-12-12 10:36:28 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Setup of platform alexa_media is taking longer than 60 seconds. Startup will proceed without waiting any longer.`

I'm not using the alarm_control_panel however, it's just making my HA take an extra minute to start currently.
