### ISSUE TITLE
The state of the component doesn't seem to update after stopping/pausing

### ISSUE THREAD

**Issue by Flavien** [custom-components/alexa_media_player#475]
**Describe the bug**
The state of the component doesn't seem to update after stopping/pausing.

**To Reproduce**
1. Play something by saying e.g. "Play XXX on deezer".
2. Ask Alexa to stop playing.
3. Ask Alexa for a news update.
4. The Alexa app doesn't show anything as currently playing anymore. Yet, the state of the media player is still `paused` with all the attributes still reflecting what was playing initially:
- media_content_type
- media_duration
- media_position
- media_position_updated_at
- media_title
- media_artist
- media_album_name

Trying to resume playing from Home Assistant fails.

**Expected behavior**
The state of the media player component should no longer be `paused` (it should be back to `idle` or `standby`).

**System details**
 - Home-assistant (version): 0.101.3
 - Hassio: No
 - alexa_media: 2.3.4
 - alexapy: 1.3.2

**Comment by alandtse** [comment]
This is expected behavior as Alexa does not update media player information when you do a non-media command like a news update. Please check the official Alexa app and you'll notice it'll also retain the media info with news.  It's paused because it should be able to resume the media playback if it hasn't timed out.

**Comment by Flavien** [comment]
That doesn't seem correct, at least on my Echo.

After I start playing the news update, the app shows a 3 dots loading icon instead of the track that was playing. Then after a while doesn't show anything playing anymore.

If I ask Alexa to resume playing, it resumes the news update, not the music. And resuming from Home Assistant has no effect.

During all that time Home Assistant shows it's still paused on the initial song.

**Comment by alandtse** [comment]
I'm actually referring to the [webapp (fix domain)](https://alexa.amazon.com). We are pulling the player information from that webapp. Perhaps the behavior has changed, so let me know.

**Comment by Flavien** [comment]
Yes looking at the Alexa SPA, there is nothing shown as playing on the Echo:

![image](https://user-images.githubusercontent.com/296540/70429911-85677d00-1a71-11ea-8098-976b49c2b78a.png)

But the alexa_media_player component on Home Assistant is still showing the track from yesterday in `paused` state:


**Entity**: `media_player.living_room_echo`
**State**: `paused`
**Attributes**:
```
volume_level: 0.23
is_volume_muted: false
media_content_type: music
media_duration: 256
media_position: 20
media_position_updated_at: 2019-12-08T22:43:51.978561+00:00
media_title: Bullet with Butterfly Wings
media_artist: The Smashing Pumpkins
media_album_name: Deezer
source: Local Speaker
source_list: Local Speaker,Pixel
available: true
last_called: true
friendly_name: Living Room Echo
entity_picture: https://cdns-images.dzcdn.net/images/cover/47b57429aca9ab083da83654f7a0529e/500x500-000000-80-0-0.jpg
supported_features: 56253
```

**Comment by alandtse** [comment]
Can you please confirm that it showed the right info before the news command and it then goes blank after the news command?

**Comment by Flavien** [comment]
So while I am playing, it shows the song playing (if I pause, it shows the media as paused):

![image](https://user-images.githubusercontent.com/296540/70538861-afe13500-1b5a-11ea-8482-20deb0e5d6f0.png)

When I start the news update, the track doesn't disappear from the page by itself, but if I refresh the page, I get the screen above showing no media playing.

**Comment by alandtse** [comment]
Ok thanks. There's something the online player is able to check on the refresh that we're missing. I'll see if I can find it to replicate it. Our current behavior is the non refresh example.

**Comment by alandtse** [comment]
#491 may actually address this. Let me know if it does.

**Comment by Flavien** [comment]
No that's not resolved.

**Comment by Flavien** [comment]
Just pointing out that this PR didn't solve the issue, so this should probably be reopen.

I think it would make sense that if playback is paused for over an hour (or some amount of time), the component should consider playback stopped. It's a bit irritating when the component shows as paused on the song I was playing 3 days ago.

**Comment by Flavien** [comment]
Can you reopen the issue, or should I create a duplicate? This is not resolved.

**Comment by alandtse** [comment]
You can recreate. However, this will be low priority since it's cosmetic.

**Comment by Flavien** [comment]
Ok I've recreated https://github.com/custom-components/alexa_media_player/issues/617. I'd argue it's not just cosmetic as the component is in the wrong state.
