### ISSUE TITLE
Volume not 'Sticking'

### ISSUE THREAD

**Issue by 3ative** [custom-components/alexa_media_player#477]
**Describe the bug**
When setting the Volume, via either ***Mini Media Player*** slider, ***Buttons*** on the device itself or via an ***Automation/Script*** the ***Mini Media Player*** slider jumps back to 0.

I have also noticed on the ***States*** page a ***volume_level:*** attribute briefly pops up but, disappears almost immediately.

**To Reproduce**
1. Described above

**Expected behavior**
As above :)

**System details**
 - Home-assistant (version):  0.102.3
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): 2.3.4
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**
Last working version was: 2.3.2

**Comment by alandtse** [comment]
Please provide logs including alexapy showing the attempt to set the volume.

**Comment by 3ative** [comment]
@alandtse 
Sadly I've gone back to previous install so, I don;t have any logs of issue. :(

**Comment by 3ative** [comment]
... I can re-install and try again if needed.

**Comment by alandtse** [comment]
No need to reinstall. If you run into it again we can try to debug it then. I'll close it for now.

**Comment by 3ative** [comment]
@alandtse 
Cheers. I'll wait for the next update and try again. For the moment this version does everything I want/need it to do. 
See ya soon! LOL

**Comment by 3ative** [comment]
With this latest update (v2.3.6) there's no longer an issue - cheers.
