### ISSUE TITLE
Use config flow instead of configurator for configuration

### ISSUE THREAD

**Issue by alandtse** [custom-components/alexa_media_player#48]
The use of the configurator is very hackish right now. It appears there is a push for components to move to config flow which appears in the [integrations panel](https://www.home-assistant.io/blog/2018/09/28/release-79/).

I haven't found the definitive dev guide on config flow yet, but it's mentioned in the [integration score guide](https://developers.home-assistant.io/docs/en/integration_quality_scale_index.html).

Here's [one component](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/simplisafe/config_flow.py) that uses it.

If anyone sees the right document or thread, please post it here.

**Comment by keatontaylor** [comment]
This should be the priority going forward, last remaining item before we can move this component into review for being officially included.

**Comment by alandtse** [comment]
Actually, this may have to happen after the initial submit to HA. Config flow requires editing `homeassistant/config_entries.py` (a later release may expose it).

I wonder if we should keep the component separate from the `alexa` built in or if we should try to integrate with it.

**Comment by ronmichel** [comment]
Config flow for custom components is possible now (see [https://github.com/home-assistant/home-assistant/pull/24946](https://github.com/home-assistant/home-assistant/pull/24946)).

**Comment by alandtse** [comment]
@ronmichel thanks. I've been waiting for this.

**Comment by alandtse** [comment]
I've done some testing; the big issue is we can't pass image urls to config_flow so there's no way to show a captcha. I may just implement config_flow just to enter credentials and rely on configurator to handle the rest of the login (captcha, 2FA, OTP).

**Comment by keatontaylor** [comment]
I've thought about this for a while, solution for now might be to just give them the captcha link and let them copy and paste it into another browser tap.

Alternatively, we can see about seeing if we can convince one of the config-flow maintainers to add the ability to show images.

**Comment by alandtse** [comment]
Nevermind, I figured out how to use config flow with placeholders which will replace `{}` in the strings.json file. This may be doable after all.

**Comment by alandtse** [comment]
For those who are brave and want to help me test; I have a [version](https://github.com/alandtse/alexa_media_player/tree/configflow) that appears to be working in my dev environment.  It requires the [alexapy version currently being merged](https://gitlab.com/keatontaylor/alexapy/merge_requests/67).  Everything is working for me except for properly unloading everything when you remove the integration. Still working through some of those issues.  Also #317 is still a problem.
