### ISSUE TITLE
TTS service don't work using "states.sensor.last_alexa.state"

### ISSUE THREAD

**Issue by daekka** [custom-components/alexa_media_player#480]
The service "notify.alexa_media" don't work if i use "states.sensor.last_alexa.state"

Configuration:

**### This config don't work (the sensor "last_alexa" works).**
![image](https://user-images.githubusercontent.com/16415892/70834606-11bfca00-1dfb-11ea-91ae-2d84cb84d4bd.png)

**### This config work:**
![image](https://user-images.githubusercontent.com/16415892/70834891-c9ed7280-1dfb-11ea-98ce-3093961ebba5.png)

**Comment by alandtse** [comment]
This is an HA issue as I don't believe the dev tool Services will process yaml templates. Please review the Wiki examples to make sure you have the proper syntax.
