### ISSUE TITLE
Support the Echo Flex Motion Sensor Add-on

### ISSUE THREAD

**Issue by birdie60** [custom-components/alexa_media_player#484]
I have the new Echo Flex with Motion Sensor add-on, see https://www.amazon.com/Echo-Flex/dp/B0814BKDJ8?th=1 .

While Alexa app can trigger events in HA when motion is detected (or no motion is detected for a configurable time span), I'd like to have a presence detection and/or motion sensor integration in HA.

Any plans to add features for Echo Flex Add-ons to the project?

Another Flex Add-on, which I do not own, is Smart Night Light. There may come more.

**Comment by alandtse** [comment]
If you can generate `alexapy.alexawebsocket` logs that show the motion sensor is reporting itself, then we may have an ability to add a motion sensor. It's possible it's not exposed externally.

**Comment by birdie60** [comment]
Thanks for your reply. 
Alas, I have no idea how to generate alexapy.alexawebsocket logs. Is there a description for this somewhere, so I can try to generate it?

**Comment by alandtse** [comment]
See [here](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). You can specifically enable `alexapy.alexawebsocket`.

**Comment by birdie60** [comment]
OK, I'll do that when I come back from holidays!

**Comment by birdie60** [comment]
OK, I now have 40 pages of logs. What kind of data is of interest? How would I find the right log entries for you?

**Comment by alandtse** [comment]
See if there are any websocket logs that happen when motion happens. It may be easiest to watch the logs while trying to trigger the motion sensor.

You should be seeing something like
```
 2020-01-01 00:56:35 DEBUG (MainThread) [alexapy.alexawebsocket] Received WebSocket MSG.
```
