### ISSUE TITLE
Next alarm improperly showing cancelled recurring alarm

### ISSUE THREAD

**Issue by Molodax** [custom-components/alexa_media_player#488]
**Describe the bug**
I have an alarm set up for weekdays and the component works usually fine showing the correct alarm time. However, if I cancel the alarm only for the next day, the component still shows as if the alarm set for the next day.
**To Reproduce**
1. Set up repeated alarm, e.g. each weekday. 
2. Ask Alexa to cancel alarm for the next day, but keep alarm for other days.
3. See that the component still shows alarm for the next day.

**Expected behavior**
I would expect that the component would show time/date for the next scheduled and active alarm. Not sure if it the Alexa limitation or some bug.
**Screenshots**

**System details**
 - Home-assistant (version): 0.103.x
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by alandtse** [comment]
Can you please provide the json information for the alarm both with a cancelled alarm and without? It should be from this [url](https://alexa.amazon.com/api/notifications) (fix the domain).

**Comment by Molodax** [comment]
Without cancelled alarm:
`{"notifications":[{"alarmTime":1577059200000,"automationId":null,"createdDate":1576694481571,"deferredAtTime":null,"deliveryType":null,"deviceName":null,"deviceSerialNumber":"G090VC1883660B71","deviceType":"A32DOYMUN6DTXA","extensibleAttribute":null,"geoLocationTriggerData":null,"id":"A32DOYMUN6DTXA-G090VC0783650B82-c0265e2e-ceb4-389d-8c0b-17b809f9edec","lastOccurrenceTimeInMilli":0,"lastUpdatedDate":0,"musicAlarmId":null,"musicEntity":null,"notificationIndex":"c0165e2e-ceb4-389d-9c0b-17b809f9edec","originalDate":"2019-12-23","originalTime":"07:45:00.000","personProfile":null,"provider":null,"rRuleData":null,"recurrenceEligibility":false,"recurringPattern":"XXXX-WD","remainingTime":0,"reminderAppLabel":null,"reminderLabel":null,"reminderSubLabel":null,"skillInfo":null,"snoozedToTime":null,"sound":{"displayName":"Clarity","folder":null,"id":"system_alerts_melodic_05","providerId":"ECHO","sampleUrl":"https://s3.amazonaws.com/deeappservice.prod.notificationtones/system_alerts_melodic_05.mp3"},"status":"ON","targetPersonProfiles":null,"timeZoneId":null,"timerLabel":null,"tmwNotificationProperties":null,"triggerTime":0,"type":"Alarm","version":"1076"}]}`

Cancelled alarm for the next day:
`{"notifications":[{"alarmTime":1577059200000,"automationId":null,"createdDate":1576694481571,"deferredAtTime":null,"deliveryType":null,"deviceName":null,"deviceSerialNumber":"G090VC1883660B71","deviceType":"A32DOYMUN6DTXA","extensibleAttribute":null,"geoLocationTriggerData":null,"id":"A32DOYMUN6DTXA-G090VC0783650B82-c0265e2e-ceb4-389d-8c0b-17b809f9edec","lastOccurrenceTimeInMilli":0,"lastUpdatedDate":0,"musicAlarmId":null,"musicEntity":null,"notificationIndex":"c0165e2e-ceb4-389d-9c0b-17b809f9edec","originalDate":"2019-12-23","originalTime":"07:45:00.000","personProfile":null,"provider":null,"rRuleData":null,"recurrenceEligibility":false,"recurringPattern":"XXXX-WD","remainingTime":0,"reminderAppLabel":null,"reminderLabel":null,"reminderSubLabel":null,"skillInfo":null,"snoozedToTime":null,"sound":{"displayName":"Clarity","folder":null,"id":"system_alerts_melodic_05","providerId":"ECHO","sampleUrl":"https://s3.amazonaws.com/deeappservice.prod.notificationtones/system_alerts_melodic_05.mp3"},"status":"ON","targetPersonProfiles":null,"timeZoneId":null,"timerLabel":null,"tmwNotificationProperties":null,"triggerTime":0,"type":"Alarm","version":"1078"}]}`

Looks like it is the same, though, if I ask Alexa about next alarm, she replies that it is scheduled every weekday but cancelled for the next morning.

**Comment by alandtse** [comment]
Thanks. Can you please check the [webapp](https://alexa.amazon.com/spa/index.html#timersAndAlarms/alarms) to see if it knows it's cancelled. We're using the notifications page for our data so may be stuck if it's not available elsewhere.

**Comment by Molodax** [comment]
> Thanks. Can you please check the [webapp](https://alexa.amazon.com/spa/index.html#timersAndAlarms/alarms) to see if it knows it's cancelled. We're using the notifications page for our data so may be stuck if it's not available elsewhere.

It seems like the webapp doesn't show cancelled the recurring alarm. Interesting if it is possible to report this bug/flaw to Amazon :/

**Comment by alandtse** [comment]
As a note, in working on other alarm issues with recurring alarms, it looks like Amazon may update the notifications at midnight PST in the backend. Of course, this still makes it hard for the component to do anything since the source data is wrong.
