### ISSUE TITLE
New Alexa Emotions and Speaking Styles

### ISSUE THREAD

**Issue by tiagofreire-pt** [custom-components/alexa_media_player#492]
**Is your feature request related to a problem? Please describe.**

New feature for natural language speech styles and emotions:

https://developer.amazon.com/en-US/blogs/alexa/alexa-skills-kit/2019/11/new-alexa-emotions-and-speaking-styles

**Describe the solution you'd like**

    Excited (High Intensity)
    Excited (Medium Intensity)
    Excited (Low Intensity)
    Disappointed (High Intensity)
    Disappointed (Medium Intensity)
    Disappointed (Low Intensity)

Is this possible to integrate on this custom component, please?

**Comment by ochlocracy** [comment]
As far as I know everything in the [SSML](https://developer.amazon.com/en-US/docs/alexa/custom-skills/speech-synthesis-markup-language-ssml-reference.html) except for the audio tag works with announce. 

I recently just added several [interjections ](https://developer.amazon.com/en-US/docs/alexa/custom-skills/speechcon-reference-interjections-english-us.html) into all my announcements. 

> Alexa, do {name of custom routine that's handled by HA}. 

```xml
<speak>
    Yes Master,<say-as interpret-as="interjection">as you wish!</say-as>.
</speak>
```

**Comment by alandtse** [comment]
Thanks @ochlocracy. 
@tiagofreire-pt I think what you're looking for is already supported to the extent we can. Please reopen if it's not.

**Comment by tiagofreire-pt** [comment]
@alandtse, I'm sorry but I couldn't understand how to use this kind of vocal control with the current implementation of this custom component. Do you have any instruction on how to use it?

Thanks.
