### ISSUE TITLE
Ability to Toggle Display & Change Brightness for Alexa Echo Dot With Clock

### ISSUE THREAD

**Issue by codycodes** [custom-components/alexa_media_player#497]
**Is your feature request related to a problem? Please describe.**
It's great that Amazon created an Echo with a clock which has some behaviors that can be controlled through the Alexa app/voice, but of course since this is Home Assistant I want to automate these behaviors so I can do things like turn the display off when leaving.

**Describe the solution you'd like**
Include a service to:
- Set the display on/off
- Change the brightness setting of the display
- Turn on/off the display's adaptive brightness setting

Include attributes to:
- See the state of the display (on/off)
- See the brightness setting of the display (0 - 10)
- See if the display has adaptive brightness turned on/off

**Describe alternatives you've considered**
Voice control is only partially implemented for the Echo Dot With Clock's display behaviors; notably missing is the ability turn on/off adaptive brightness (this can only be controlled in the app). There is no interface which I've found to be suitable for automating these behaviors besides using something like _alexa_media_player_. There may be a way in the future to automate this behavior by using Alexa Routines, but I haven't found anything alluding to this possibility in the app yet.

**Additional context**
I have no idea if this is possible; on the mobile app these options are exposed, but I didn't find them through a precursory glance at my Echo Dot With Clock device on [alexa.amazon.com](https://alexa.amazon.com). If there is a method for finding these options/configuration, I will be happy to attempt implementing the behavior and submit a PR!

In general I'm also wondering if it'd ever be possible to create a timer from Home Assistant for an Alexa device as it seems to be a function which occurs locally per-device, so there is no automation for this behavior. If this changing the display settings idea is similar (only works locally) can you please let me know? Also if there are any workarounds to this (even if they're hacky and rely on invoking Alexa from itself via TTS or something), I would be happy if you'd share them with me! Thanks for everything. Love this component!

**Comment by alandtse** [comment]
I haven't done much reverse engineering of apps, but if you can figure out the API call it is making to the servers we can then replicate it here.

For the timer, there is an API to create and edit, we just haven't implemented it because that seems easier to do with the device's UI and app. There is currently no known way to control an Alexa vocally unless you use another TTS with another bluetooth speaker.

**Comment by codycodes** [comment]
Thanks for your prompt response, and Happy New Year!

Wow, is there some documentation or hints you can give me for the timer functionality? I would really love this feature as well; given that most Alexa devices support timers this would probably be more useful than my initial feature request. One of the cool features about the Dot With Clock is that it can count down on the display if the timer is < 1 hr. Honestly the coolest would be a way to reverse engineer the display API and send whatever text you want to it; alas, one can dream...

For the following, if you have any info on this let me know, but a reply isn't required! For this issue, since I can find the setting on mobile but not on the web, is it advisable to run a program to inspect the requests from the phone somehow (maybe wireshark?) or do you think (based on your experience) I can discover the API from the browser and use dev tools to find the requests?

**Comment by alandtse** [comment]
The wiki has some [notes](https://github.com/custom-components/alexa_media_player/wiki/Known-Endpoints). Feel free to add more info as you discover it. It looks like a standard REST api.  Wireshark may work if it's not https, if it is, you'd need to do a man in the middle proxy. Typically the app has more features than the webapp. Webapp is much easier to figure out because of the browser dev tools.

**Comment by codycodes** [comment]
Thank you for this information! I'll update here if/when I get anything working :)

**Comment by codycodes** [comment]
Hi, I just wanted to followup with what I did to get this mostly working (but not through my original plan)!

I ended up leveraging the ability to invoke [automation routines](https://github.com/custom-components/alexa_media_player/wiki#automation-routines) from alexa_media_player and simply set up some routines to get the behavior I want. Currently, at the end of a routine, you can have a single action to "tell Alexa" what you'd like it to do. So you can just create a routine that is able to turn on the display, another routine to change its brightness to a pre-configured level (you could create ten routines for ten levels if you really want to), and another routine to turn off the display.

The only drawbacks of using this method are:
* The need to create a routine for each individual action (and get them set up in Home Assistant with the correct names)
* No support for toggling adaptive brightness that I've found thus far through voice actions (this still needs to be configured directly from the Alexa Echo settings page)

For my use case, getting 2/3 of the original functionality I wanted (and really, the only functionality I actually need), definitely resolves this issue for me at least! I now have nifty automation to turn the display off when leaving the room/going to bed and to turn it on when I wake up. When waking up I actually use two routines, one to turn on the display, and another to display the temperature (which hooks into the clock's display). Working great for over a month now.

Thanks again for this amazing software, and for taking the time to address how to attempt to decipher the API if I were to go that route (I did try it, but it ended up being more complex/difficult than I first thought). Appreciate all your help and support for this community!

**Comment by alandtse** [comment]
Thanks for reporting back. Are you aware you can issue [voice commands](https://github.com/custom-components/alexa_media_player/wiki#run-custom-command) directly now?
