### ISSUE TITLE
TTS not working for everywhere entity

### ISSUE THREAD

**Issue by ashoktvm** [custom-components/alexa_media_player#500]
**Describe the bug**
The notification entity for Alexa everywhere is not working. But notification entity for a particular device is working. I tried to play notification when my Washing Machine has stopped washing and gave a notification on Alexa devices. When I select notification for each device it plays notification. But when I select notification for Alexa everywhere it does not play notification at all

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details**
 - Home-assistant (version): 
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by alandtse** [comment]
Please provide more details about what your'e trying to do and what is happening. There is a template you didn't fill out to provide some basic details about your situation. Please include that detail.

**Comment by ashoktvm** [comment]
I tried to play notification when my Washing Machine has stopped washing and gave a notification on Alexa devices. When I select notification for each device it plays notification. But when I select notification for Alexa everywhere it does not play notification at all

**Comment by alandtse** [comment]
Please fill out the template completely and provide logs of the specific notification when you try to send to everywhere.  This should include `alexapy` logs too.

**Comment by ashoktvm** [comment]
Looks like announcement is working, but tts is not working. Not much of an issue though

**Comment by alandtse** [comment]
Apparently TTS isn't available in the app. This looks like an Amazon issue.
