### ISSUE TITLE
Possible to play a simple chime or tone using tts?

### ISSUE THREAD

**Issue by roger-** [custom-components/alexa_media_player#505]
I know I can get a simple one using `announce` but is there any other way to play simple sounds, perhaps using SSML?

**Comment by alandtse** [comment]
[No](https://github.com/custom-components/alexa_media_player/wiki/Notification-Component#announce). But you can [play some sounds](https://github.com/custom-components/alexa_media_player/wiki#play-sounds-versions--240).

**Comment by roger-** [comment]
Perfect, thanks. 

Any idea how to play sounds like `soundbank://soundlibrary/alarms/beeps_and_bloops/bell_06`? I tried various `media_content_id` values and none worked.
