### ISSUE TITLE
Regularly requesting captcha

### ISSUE THREAD

**Issue by marrold** [custom-components/alexa_media_player#506]
**Describe the bug**
Every few weeks my alexa_media_player is logged out and I am prompted to re-enter the captcha

**Expected behavior**
Ideally alexa_media_player should stay logged in without constantly requiring a captcha to be entered. 

**System details**
 - Home-assistant (version):  0.103.3.
 - Hassio (Yes/No): Yes
 - alexa_media : 2.3.4
 - alexapy: Unknown

Thanks

**Comment by alandtse** [comment]
This is unfortunately something Amazon controls. We are trying to mimic the app but there's no guarantee Amazon can't figure out this isn't an official app and log you out. As a point of comparison, my production system hasn't been logged out for over a year. You may want to review Amazon's history it has on your logins and clean out any old devices as perhaps that's a trigger.

**Comment by alandtse** [comment]
I'll close this, but if you saw something in your log you think that may be causing the log out issue, please feel free to reopen.
