### ISSUE TITLE
Unknown error during configuration

### ISSUE THREAD

**Issue by jpcanovas** [custom-components/alexa_media_player#512]
Hi all. I have installed all files in custom components, reboot home assistant and go to integrations and add an Alexa media integration. Then the configuration panel appears and I introduce my email, password and Amazon server. But when i press "Send" the panel cleans and this error appears in home-assistant.log:

`2020-01-15 12:34:11 WARNING (MainThread) [custom_components.alexa_media.config_flow] Unknown error: int() argument must be a string, a bytes-like object or a number, not 'datetime.datetime'`

The same if I edit configurations.yaml.

Environment:
- Home Assistant 0.102.3 on Docker
- Custom component Alexa-media from git clone on 2020/01/15 (2.5.0)
- Alexapy 1.4.1 (Home Assistant auto installed it)

Any idea to solve it? Thanks

**Comment by MattKaboom** [comment]
Same error after updating to v2.5.0

**Comment by brinzlee** [comment]
Same error here too...I couldn't revert back to previous version either....thank heavens for snapshots

**Comment by brandon-dacrib** [comment]
thirded. something broke.
