### ISSUE TITLE
problem with alexa integration after upgraded to 2.5.0

### ISSUE THREAD

**Issue by pilot1981** [custom-components/alexa_media_player#513]
**Describe the bug**
problem with alexa integration after upgraded to 2.5.0

**To Reproduce**
on HASSIO 0.103.6 upgrade alexa from 2.4.0 to 2.5.0 using HACS 0.20.8

**Expected behavior**
working integration with alexa

**Screenshots**
NA

**System details**
- HASSIO 0.103.6
 - alexa_media  2.5.0
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
Platform error notify.alexa_media - Integration 'alexa_media' not found.

**Additional context**

**Comment by Krocko** [comment]
I have the same problem.

**Comment by pilot1981** [comment]
I think this issue is related to HACS: I found only file .zip in alexa directory of my HASSIO...

**Comment by Krocko** [comment]
But downgrade is working

**Comment by bobsiopener** [comment]
I get the following error in the log while trying to configure
Unknown error: int() argument must be a string, a bytes-like object or a number, not 'datetime.datetime'
