### ISSUE TITLE
ERROR: Could not build wheels for multidict which use PEP 517 and cannot be installed directly

### ISSUE THREAD

**Issue by pilot1981** [custom-components/alexa_media_player#526]
**Describe the bug**
All woks fine before upgrading to 2.5.0 or 2.5.1 or 2.5.2 versions...now I have Alexa inactive in my lovelace interface...something is broken from 2.5.x version...

**To Reproduce**
Using HACS upgrade from 2.4.1 to 2.5.0 or 2.5.1 ro 2.5.2

**Expected behavior**
I expect to have alexa integration working fine as in precedent version.

**Screenshots**
<img width="286" alt="Schermata 2020-01-17 alle 08 48 24" src="https://user-images.githubusercontent.com/46350465/72593853-52cd6180-3906-11ea-9706-81807518ab7f.png">

**System details**
 - HASSIO 0.104.1
 - alexa_media  (version from `const.py` or HA startup): "2.5.2"
 - alexapy (version from `pip show alexapy` or HA startup): Package(s) not found: alexapy!!!!

**Logs**
sometimes this one: Setup of default_config is taking over 10 seconds.
sometimes this one: Setup of Alexa_media is taking over 10 seconds.

**Additional context**
I don't have any alexapy library in my /config/deps directory...so I executed these command in CLI:
```
# apk add --no-cache python3
# python3 —V
# pip3 install --upgrade pip
# pip3 install alexapy
```
but it returned this error:
```
Collecting alexapy
  Using cached https://files.pythonhosted.org/packages/15/9e/2c5140fdf2b4c43c6d2ad3cc0146e40354194a9d6de4ee0d9de20ba981da/AlexaPy-1.4.2-py3-none-any.whl
Collecting aiohttp
  Using cached https://files.pythonhosted.org/packages/c2/f7/f0ad3dbace4762fef5d80aa4124b41bf218e4c4dd6d387a86cede707d9a4/aiohttp-3.6.2-py3-none-any.whl
Collecting simplejson
  Using cached https://files.pythonhosted.org/packages/98/87/a7b98aa9256c8843f92878966dc3d8d914c14aad97e2c5ce4798d5743e07/simplejson-3.17.0.tar.gz
Collecting yarl
  Using cached https://files.pythonhosted.org/packages/d6/67/6e2507586eb1cfa6d55540845b0cd05b4b77c414f6bca8b00b45483b976e/yarl-1.4.2.tar.gz
Collecting bs4
  Using cached https://files.pythonhosted.org/packages/10/ed/7e8b97591f6f456174139ec089c769f89a94a1a4025fe967691de971f314/bs4-0.0.1.tar.gz
Collecting requests
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting certifi
  Using cached https://files.pythonhosted.org/packages/b9/63/df50cac98ea0d5b006c55a399c3bf1db9da7b5a24de7890bc9cfd5dd9e99/certifi-2019.11.28-py2.py3-none-any.whl
Collecting backoff
  Using cached https://files.pythonhosted.org/packages/f0/32/c5dd4f4b0746e9ec05ace2a5045c1fc375ae67ee94355344ad6c7005fd87/backoff-1.10.0-py2.py3-none-any.whl
Collecting aiofiles
  Using cached https://files.pythonhosted.org/packages/cf/f2/a67a23bc0bb61d88f82aa7fb84a2fb5f278becfbdc038c5cbb36c31feaf1/aiofiles-0.4.0-py3-none-any.whl
Collecting multidict<5.0,>=4.5
  Using cached https://files.pythonhosted.org/packages/b6/22/ae21cedaa0e6d35e84e8ab57700dcf3d4609421ebe113e1aaafc468eec42/multidict-4.7.4.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting async-timeout<4.0,>=3.0
  Using cached https://files.pythonhosted.org/packages/e1/1e/5a4441be21b0726c4464f3f23c8b19628372f606755a9d2e46c187e65ec4/async_timeout-3.0.1-py3-none-any.whl
Collecting attrs>=17.3.0
  Using cached https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Collecting chardet<4.0,>=2.0
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting idna>=2.0
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting beautifulsoup4
  Using cached https://files.pythonhosted.org/packages/cb/a1/c698cf319e9cfed6b17376281bd0efc6bfc8465698f54170ef60a485ab5d/beautifulsoup4-4.8.2-py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached https://files.pythonhosted.org/packages/b4/40/a9837291310ee1ccc242ceb6ebfd9eb21539649f193a7c8c86ba15b98539/urllib3-1.25.7-py2.py3-none-any.whl
Collecting soupsieve>=1.2
  Using cached https://files.pythonhosted.org/packages/81/94/03c0f04471fc245d08d0a99f7946ac228ca98da4fa75796c507f61e688c2/soupsieve-1.9.5-py2.py3-none-any.whl
Building wheels for collected packages: multidict
  Building wheel for multidict (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3.8 /usr/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpbhucbwp2
       cwd: /tmp/pip-install-iexeel3s/multidict
  Complete output (43 lines):
  **********************
  * Accellerated build *
  **********************
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv7l-3.8
  creating build/lib.linux-armv7l-3.8/multidict
  copying multidict/_multidict_base.py -> build/lib.linux-armv7l-3.8/multidict
  copying multidict/_multidict_py.py -> build/lib.linux-armv7l-3.8/multidict
  copying multidict/_compat.py -> build/lib.linux-armv7l-3.8/multidict
  copying multidict/__init__.py -> build/lib.linux-armv7l-3.8/multidict
  copying multidict/_abc.py -> build/lib.linux-armv7l-3.8/multidict
  running egg_info
  writing multidict.egg-info/PKG-INFO
  writing dependency_links to multidict.egg-info/dependency_links.txt
  writing top-level names to multidict.egg-info/top_level.txt
  reading manifest file 'multidict.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files found matching 'multidict/_multidict.html'
  warning: no previously-included files found matching 'multidict/*.so'
  warning: no previously-included files found matching 'multidict/*.pyd'
  warning: no previously-included files found matching 'multidict/*.pyd'
  no previously-included directories found matching 'docs/_build'
  writing manifest file 'multidict.egg-info/SOURCES.txt'
  copying multidict/__init__.pyi -> build/lib.linux-armv7l-3.8/multidict
  copying multidict/_multidict.c -> build/lib.linux-armv7l-3.8/multidict
  copying multidict/py.typed -> build/lib.linux-armv7l-3.8/multidict
  creating build/lib.linux-armv7l-3.8/multidict/_multilib
  copying multidict/_multilib/defs.h -> build/lib.linux-armv7l-3.8/multidict/_multilib
  copying multidict/_multilib/dict.h -> build/lib.linux-armv7l-3.8/multidict/_multilib
  copying multidict/_multilib/istr.h -> build/lib.linux-armv7l-3.8/multidict/_multilib
  copying multidict/_multilib/iter.h -> build/lib.linux-armv7l-3.8/multidict/_multilib
  copying multidict/_multilib/pair_list.h -> build/lib.linux-armv7l-3.8/multidict/_multilib
  copying multidict/_multilib/views.h -> build/lib.linux-armv7l-3.8/multidict/_multilib
  running build_ext
  building 'multidict._multidict' extension
  creating build/temp.linux-armv7l-3.8
  creating build/temp.linux-armv7l-3.8/multidict
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Os -fomit-frame-pointer -g -Os -fomit-frame-pointer -g -Os -fomit-frame-pointer -g -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/include/python3.8 -c multidict/_multidict.c -o build/temp.linux-armv7l-3.8/multidict/_multidict.o -O2 -std=c99 -Wall -Wsign-compare -Wconversion -fno-strict-aliasing -pedantic
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for multidict
  Running setup.py clean for multidict
Failed to build multidict
ERROR: Could not build wheels for multidict which use PEP 517 and cannot be installed directly

```

**Comment by alandtse** [comment]
Are you able to install with:
`pip3 install alexapy --no-binary`

What's the base device you're running hassio on? Raspberry pi?

**Comment by pilot1981** [comment]
on Raspberry Pi3+:

~ $ pip3 install alexapy --no-binary

Usage:   
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

--no-binary option requires 1 argument

**Comment by alandtse** [comment]
Could be a hassio [bug](https://community.home-assistant.io/t/cant-update-hass-io-error-failed-building-wheel-for-multidict/162580).
Try installing multidict 4.7.3 before doing alexapy
```
pip3 install multidict==4.7.3
pip3 install alexapy
```

**Comment by pilot1981** [comment]
another error during building...

Collecting multidict==4.7.3
  Downloading https://files.pythonhosted.org/packages/84/96/5503ba866d8d216e49a6ce3bcb288df8a5fb3ac8a90b8fcff9ddcda32568/multidict-4.7.3.tar.gz (50kB)
     |████████████████████████████████| 51kB 1.3MB/s 
Installing collected packages: multidict
    Running setup.py install for multidict ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-d3hmq3_j/multidict/setup.py'"'"'; __file__='"'"'/tmp/pip-install-d3hmq3_j/multidict/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-op2ncmvx/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-d3hmq3_j/multidict/
    Complete output (44 lines):
    **********************
    * Accellerated build *
    **********************
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-3.8
    creating build/lib.linux-armv7l-3.8/multidict
    copying multidict/_multidict_base.py -> build/lib.linux-armv7l-3.8/multidict
    copying multidict/_multidict_py.py -> build/lib.linux-armv7l-3.8/multidict
    copying multidict/_compat.py -> build/lib.linux-armv7l-3.8/multidict
    copying multidict/__init__.py -> build/lib.linux-armv7l-3.8/multidict
    copying multidict/_abc.py -> build/lib.linux-armv7l-3.8/multidict
    running egg_info
    writing multidict.egg-info/PKG-INFO
    writing dependency_links to multidict.egg-info/dependency_links.txt
    writing top-level names to multidict.egg-info/top_level.txt
    reading manifest file 'multidict.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files found matching 'multidict/_multidict.html'
    warning: no previously-included files found matching 'multidict/*.so'
    warning: no previously-included files found matching 'multidict/*.pyd'
    warning: no previously-included files found matching 'multidict/*.pyd'
    no previously-included directories found matching 'docs/_build'
    writing manifest file 'multidict.egg-info/SOURCES.txt'
    copying multidict/__init__.pyi -> build/lib.linux-armv7l-3.8/multidict
    copying multidict/_multidict.c -> build/lib.linux-armv7l-3.8/multidict
    copying multidict/py.typed -> build/lib.linux-armv7l-3.8/multidict
    creating build/lib.linux-armv7l-3.8/multidict/_multilib
    copying multidict/_multilib/defs.h -> build/lib.linux-armv7l-3.8/multidict/_multilib
    copying multidict/_multilib/dict.h -> build/lib.linux-armv7l-3.8/multidict/_multilib
    copying multidict/_multilib/istr.h -> build/lib.linux-armv7l-3.8/multidict/_multilib
    copying multidict/_multilib/iter.h -> build/lib.linux-armv7l-3.8/multidict/_multilib
    copying multidict/_multilib/pair_list.h -> build/lib.linux-armv7l-3.8/multidict/_multilib
    copying multidict/_multilib/views.h -> build/lib.linux-armv7l-3.8/multidict/_multilib
    running build_ext
    building 'multidict._multidict' extension
    creating build/temp.linux-armv7l-3.8
    creating build/temp.linux-armv7l-3.8/multidict
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Os -fomit-frame-pointer -g -Os -fomit-frame-pointer -g -Os -fomit-frame-pointer -g -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/include/python3.8 -c multidict/_multidict.c -o build/temp.linux-armv7l-3.8/multidict/_multidict.o -O2 -std=c99 -Wall -Wsign-compare -Wconversion -fno-strict-aliasing -pedantic
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-d3hmq3_j/multidict/setup.py'"'"'; __file__='"'"'/tmp/pip-install-d3hmq3_j/multidict/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-op2ncmvx/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.


very strange...any idea?

**Comment by alandtse** [comment]
Honestly, I'm not sure. It's complaining it can't find `gcc` which is a bigger issue. That would be a hassio bug.

**Comment by pilot1981** [comment]
~ $ pip3 install gcc
ERROR: Could not find a version that satisfies the requirement gcc (from versions: none)
ERROR: No matching distribution found for gcc

very strange HASSIo don't have gcc installed and very strange I can't install gcc...?!

**Comment by alandtse** [comment]
gcc isn't a python package. It's an underlying tool in Linux. Normally you'd have to do an `apt get gcc` but I'm not too familiar with the linux hassos is running.

**Comment by pilot1981** [comment]
I don’t understand: without alexapy package Alexa announce work fine but if I go in Lovelace interface I’m not able to play music...which difference there is?

**Comment by alandtse** [comment]
No idea. It shouldn't function at all without alexapy.

**Comment by pilot1981** [comment]
this is link of my issue opened on GitHub repository of HASSIO:

https://github.com/home-assistant/home-assistant/issues/30997

**Comment by pvizeli** [comment]
https://github.com/home-assistant/custom-components-wheels

**Comment by alandtse** [comment]
@pvizeli I'm not understanding what you are trying to say with the link.  Alexa_media has an entry and the links redirect to the latest version of the manifest.json.  Are you saying HASSOS does not understand http 302 redirects?

**Comment by pvizeli** [comment]
There is nothing pointing to Hass.io or HassOS. We build python wheels for our images overall system. If you did not update the repository from the link above. Your custom component will still work only on virtualenvs. But please remove the old manifest in this repository.

**Comment by alandtse** [comment]
@pvizeli Thanks. Should I submit a PR to update the documentation to mention 302 will not be followed? The repo didn't say anything about that.

**Comment by pilot1981** [comment]
I don't understand...what I have to solve this issue on my HASSIO? I have to wait for new release of alexa media player plugin?

**Comment by alandtse** [comment]
@pvizeli will have to confirm but you may have to wait till the next version of hassio. That said, the changes have been pushed so you can try installing again.

**Comment by pilot1981** [comment]
V2.5.3 seems work fine: I test it!

**Comment by arivictor** [comment]
Encountered this issue, what fixed my problem:

```
$ pip install --upgrade pip setuptools-scm
```
