### ISSUE TITLE
Do Not Disturb state doesn't update

### ISSUE THREAD

**Issue by aidanblack** [custom-components/alexa_media_player#529]
SUMMARY:
Do Not Disturb toggle on Echo devices works fine when you control it from HA but when the status changes on the device or from the Alexa iOS app, the updated state doesn't reflect in HA.

DETAILS:
When HA restarts it gets the correct Do Not Disturb state from all Echo devices. When you change the state from HA, the device updates correctly. However, if you tell the device "Alexa do not disturb" or set Do Not Disturb for a device from the Alexa iOS app, the state change doesn't get updated in HA.

EXPECTATION:
Setting Do Not Disturb should update the state in HA.

SYSTEM:
Raspberry Pi 3B+ running HassIO (v0.104.0). The Alexa Media Player add-on is installed through HACS (v2.5.1).

LOGS:
There are no errors in the logs or entries in the Logbook

ADDITIONAL:
I have a total of 6 Echo devices, plus several Fire TV and Kindle devices.

**Comment by alandtse** [comment]
Unfortunately, DND updates are tricky if you do it outside of HA in that the only way we can determine it changes it by polling Amazon. There is no specific event to check from websocket. To avoid spamming Amazon we'll probably only be able to get the updated state every 10 minutes. Hopefully that's enough visibility.

**Comment by aidanblack** [comment]
Makes sense, although more frequently than 10 minutes would be preferable. I understand if that isn't possible. What are the limits on the Alexa API?

**Comment by alandtse** [comment]
It isn't an API restriction specifically. We're just being conservative because we're not using the official API and don't want Amazon to shut it down because they notice people are over polling them.

**Comment by aidanblack** [comment]
Thanks for addressing this - much appreciated 

Aidan

**Comment by dibyadip-das** [comment]
Is this bug released because still my DND status doesn't get update especially showing the off state.
