### ISSUE TITLE
Unhandled command : Push_content_focus_change

### ISSUE THREAD

**Issue by toe7685** [custom-components/alexa_media_player#536]
**Describe the bug**
it says in the logs to report here 
**To Reproduce**
Not sure i just restarted my home assistant
**Expected behavior**
I guess no log warning
**Screenshots**

**System details**
 - Home-assistant (version): 104.2
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): 2.52
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

```
Unhandled command: PUSH_CONTENT_FOCUS_CHANGE with data {'destinationUserId': 'A**********OSS', 'clientId': '{value=Domain:Phatic:AlexaOriginals}', 'dopplerId': {'deviceSerialNumber': '9************2SV', 'deviceType': 'AB72C64C86AW2'}, 'deviceComponent': 'com.amazon.dee.device.capability.audioplayer.AudioPlayer'}. Please report at https://github.com/custom-components/alexa_media_player/issues
```

**Additional context**

**Comment by alandtse** [comment]
Thanks. Was there any particular action you were doing that caused it?

**Comment by toe7685** [comment]
no i just restarted homeassistant

**Comment by alandtse** [comment]
Was Alexa being used during the restart? For example, was it playing music, etc?

**Comment by toe7685** [comment]
To my knowledge no. it hasn't showed up since the reboot. I only use Alexa on the echos for tv control so no music

**Comment by monsieurlatte** [comment]
I can add that I randomly get these in my logs, I am unable to narrow down what's causing it or what's triggering it.  I havent seen any ill effect from it either sadly.

**Comment by alandtse** [comment]
Thanks there's no ill effects. It's just a potential command we could be using to track something once we identify what causes it.

**Comment by toe7685** [comment]
just letting yall know it showed up again @5:30am nothing was happening at that time. heres the logs
Mon Jan 20 2020 05:25:34 GMT-0600 (Central Standard Time)
Unhandled command: PUSH_CONTENT_FOCUS_CHANGE with data {'destinationUserId': 'A**********OSS', 'clientId': '{value=Domain:Phatic:AlexaOriginals}', 'dopplerId': {'deviceSerialNumber': '9************2SV', 'deviceType': 'AB72C64C86AW2'}, 'deviceComponent': 'com.amazon.dee.device.capability.audioplayer.AudioPlayer'}. Please report at https://github.com/custom-components/alexa_media_player/issues This reloads the data of all repositories HACS knows about, this will take some time to finish.
Are you sure you want to continue?
No  Yes

**Comment by alandtse** [comment]
What type of echo device is this happening on?

**Comment by monsieurlatte** [comment]
Alandtse, hard to tell, I have 4 Echos, 1 Dot, 1 Show, 1 firetv cube.

**Comment by alandtse** [comment]
The logs provide a serial number you can check against your device. You can find a list of devices in json here. https://alexa.amazon.com/api/devices-v2/device (fix the domain)

**Comment by alandtse** [comment]
I found it in my logs and it looked like it happened when Amazon asked if I wanted to upgrade to Prime Music. It may be related to Prime in some way but I'd like to get a confirmation before we ignore it entirely.

**Comment by tommyjlong** [comment]
I have been getting this quite a bit, I'd say over the last few weeks.  From the last two days it has occurred 8 times.  Looking at the logs, the times are random, including 3:39am.  However they are all coming from one particular device which is my original ECHO.  My Echo-dot, and several others which are of different types are not showing this.

**Comment by Seechay** [comment]
I also have an original echo which is generating these logs as well. Mine alternates between two slightly different messages.


`Unhandled command: PUSH_CONTENT_FOCUS_CHANGE with data {'destinationUserId': 'A**********BI7', 'deviceComponent': 'com.amazon.dee.device.capability.audioplayer.AudioPlayer', 'clientId': '{value=Domain:Phatic:AlexaOriginals}', 'dopplerId': {'deviceType': 'AB72C64C86AW2', 'deviceSerialNumber': 'B************20U'}}. Please report at https://github.com/custom-components/alexa_media_player/issues`

`Unhandled command: PUSH_CONTENT_FOCUS_CHANGE with data {'destinationUserId': 'A**********BI7', 'deviceComponent': 'com.amazon.dee.device.capability.audioplayer.AudioPlayer', 'clientId': '{value=Dee-Domain-Music}', 'dopplerId': {'deviceType': 'AB72C64C86AW2', 'deviceSerialNumber': 'B************20U'}}. Please report at https://github.com/custom-components/alexa_media_player/issues`
