### ISSUE TITLE
KeyError: 'notifications'

### ISSUE THREAD

**Issue by Tadimsky** [custom-components/alexa_media_player#544]
**Describe the bug**
I'm seeing this error in my logs:

```
KeyError: 'notifications'
  File "/config/custom_components/alexa_media/__init__.py", line 445, in update_devices
    raw_notifications = await AlexaAPI.get_notifications(login_obj)
  File "alexapy/alexaapi.py", line 761, in get_notifications
    return (await response.json(content_type=None))['notifications']
```
![image](https://user-images.githubusercontent.com/1149244/73140210-16e37c00-402b-11ea-9f00-abe52187e03f.png)

It looks like the Alexa API returned a 500 error.

**To Reproduce**
Unknown, noticed in the logs.
Looks like Alexa API was having issues.

**Expected behavior**
Error is not thrown when indexing a property that may not exist.

**Screenshots**

**System details**
 - Home-assistant (version):   0.104.3
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): v2.5.2
 - alexapy (version from `pip show alexapy` or HA startup):

**Comment by alandtse** [comment]
Thanks. What are you using to show the log output? Yes, we probably need to catch the Amazon 500 error but it should only stop that update request and should resume normal operation once Amazon stops with the error.

**Comment by Tadimsky** [comment]
That was Sentry - I recently set it up so ever error in my logs generates an issue.
I've just been sharing the issues with folks for visibility.
Yeah, it's not causing any troubles as far as I can tell :)
