### ISSUE TITLE
[Feature Request] iHeartRadio support

### ISSUE THREAD

**Issue by nkgilley** [custom-components/alexa_media_player#545]
**Is your feature request related to a problem? Please describe.**
Unable to play iHeartRadio stations

**Describe the solution you'd like**
I'd like to be able to play iHeart stations with the media_player.play_media service

**Describe alternatives you've considered**
Right now I have it working with a modified version of alexa_remote_control.sh

**Additional context**
Here is the curl commandI'm using:
```
${CURL} ${OPTS} -s -b ${COOKIE} -A "${BROWSER}" -H "DNT: 1" -H "Connection: keep-alive" -L\
 -H "Content-Type: application/json; charset=UTF-8" -H "Referer: https://alexa.${AMAZON}/spa/index.html" -H "Origin: https://alexa.${AMAZON}"\
 -H "csrf: $(awk "\$0 ~/.${AMAZON}.*csrf[ \\s\\t]+/ {print \$7}" ${COOKIE})" -X POST\
 "https://${ALEXA}/api/iheartradio/queue-and-play-live-station" -d '{"deviceSerialNumber": "'${DEVICESERIALNUMBER}'", "deviceType": "'${DEVICETYPE}'", "stationId": "'${IHEARTID}'", "mediaOwnerCustomerId": "'${MEDIAOWNERCUSTOMERID}'"}'
```

**Comment by alandtse** [comment]
Are you sure it doesn't work? This works for me right now.

```
entity_id: media_player.great_room
media_content_id: kiss
media_content_type: I_HEART_RADIO
```

**Comment by nkgilley** [comment]
@alandtse that does work for me, thanks!  I had tried IHEART and IHEARTRADIO.
