### ISSUE TITLE
Unknown error when configuring alexa media player in integrations

### ISSUE THREAD

**Issue by T-Luyten** [custom-components/alexa_media_player#550]
When installing the custom component using HACS everything is fine and is showing up in HACS
However after restart when i'm adding my credentials in the integration menu an unknown error pops up.  My login credentials are correct. 

The log only contains the following information 
Unknown error: 21:41 custom_components/alexa_media/config_flow.py (WARNING) 

No alexa media players are added to home assistant.

**Expected behavior**
media players to be added to home assistant after configuring them in the integrations menu 

**System details**
I'm running Home Assistant 0.104.3 
have HACS 0.20.9 installed 
alexa media player v2.5.4

**Comment by alandtse** [comment]
Please provide the logs as you try to login as it will show the details of what is happening. Instructions were in the template you deleted.

**Comment by T-Luyten** [comment]
Ok, sorry about that.  It's the first time i'm using github to fix something in my set-up.  Hopefully i'm giving you the correct information now.

**Screenshots**
![image](https://user-images.githubusercontent.com/50836642/73590531-cd3fd900-44e3-11ea-94cd-b016dc6e8475.png)

**System details**
 - Home-assistant (version): 0.104.3
 - Hassio (Yes)
 - alexa_media  (version from `const.py` or HA startup): v2.5.4
 - alexapy (version from `pip show alexapy` or HA startup): ?

**Logs**
I'm not good at these things so i'm just going to paste the file hopefully without any of my private details.
[home-assistant.log](https://github.com/custom-components/alexa_media_player/files/4142437/home-assistant.log)

**Comment by T-Luyten** [comment]
Hopefully giving you the correct information now.  If i'm reading this right it's says my credentials are wrong.  I am using the correct login details so not sure why that is.

System details
Home-assistant (version): 0.104.3
Hassio (Yes)
alexa_media (version from const.py or HA startup): v2.5.4
alexapy (version from pip show alexapy or HA startup): ?

Logs
I'm not good at these things so i'm just going to paste the file hopefully without any of my private details.
[home-assistant.log](https://github.com/custom-components/alexa_media_player/files/4142453/home-assistant.log)

**Comment by alandtse** [comment]
Thanks. Please do the following:

1. Remove the account info from integrations if it exists.
2. Delete any `alexamedia.*.pickle` files in your config directory.
3. Provide the beginning of the logs at startup when alexa_media reports its version info.
4. When entering your credentials in the configuration screen, enable "Advanced debugging". This will create some `alexamedia.*.html` files in your login page that you should submit.

**Comment by T-Luyten** [comment]
Ok,
So I managed to delete the alexamedia.*.pickle file and tried again and now everything worked fine when adding my credentials in the configuration screen.  Thanks for the assistance.
