### ISSUE TITLE
When calling TTS in a group, devices go one after another instead of all at once

### ISSUE THREAD

**Issue by rdariolemes** [custom-components/alexa_media_player#551]
**Describe the bug**
When using notify.alexa_media in a group of media players, notification fires in one device at the time following the next device in a group instead of all at once. See configuration below

**To Reproduce**

1. Create Automation using notify.alexa_media type TTS
2. Fire automation
3. Detect TTS in 1st device on the list, then 2nd and so on instead of all at once/

Able to reproduce behavior with HA automations and node red also

**Expected behavior**
TTS to fire in all devices at once instead of one at the time.

**System details**
 - Home-assistant (version): 195
 - Hassio (Yes/No): Yes. Restarted several times already
 - alexa_media  (version from `const.py` or HA startup): v2.5.4
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
No error logs.

**Additional context**
Automation Config:
`- id: '1580684509429'
  alias: Kitchen_Door_Open_Announcement
  description: ''
  trigger:
  - entity_id: binary_sensor.kitchen_door_sensor
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      data:
        type: tts
      message: Kitchen door open
      target: group.all_alexa
    service: notify.alexa_media`
Groups:
`all_alexa:
  name: all_Alexa
  entities:
    - media_player.ac_speaker
    - media_player.dinning_room_speaker
    - media_player.kitchen
    - media_player.stairs`

**Comment by alandtse** [comment]
That's an Amazon issue. It doesn't allow for specifying more than one target for `simon_says` so they have to be processed in sequence.

**Comment by alandtse** [comment]
Actually, may have a hack to work around it.

**Comment by rdariolemes** [comment]
Thanks u for the fix
