### ISSUE TITLE
Being able to play a local mp3 file

### ISSUE THREAD

**Issue by morrydavis** [custom-components/alexa_media_player#554]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by morrydavis** [comment]
If this is possible I haven't found how to do it I have it setup to do a tts when my favorite team scores and thought it would be cool if it could play the team fight song

**Comment by alandtse** [comment]
Not doable. It's an amazon limitation.
