### ISSUE TITLE
media_player entities don't play text to speech

### ISSUE THREAD

**Issue by morrydavis** [custom-components/alexa_media_player#557]
When  ever I try to use these entities I get Sorry

**To Reproduce**
1. Go to a media_player entity on your home page
2. Click on '...'
3. enter some text in the text to speech field
4. pres the << button
5. hear "Sorry, text to speech can only be called with the notify.alexa_media service."

**Expected behavior**

**Screenshots**

**System details**
 - Home-assistant (version): 
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by morrydavis** [comment]
Using version 105.2 of HA
Not sure how  to get version of media_player

**Comment by alandtse** [comment]
That is not a bug but a limitation in the HA UI. Use the [notify component.](https://github.com/custom-components/alexa_media_player/wiki/Notification-Component)
