### ISSUE TITLE
TTS of numbers

### ISSUE THREAD

**Issue by sheminasalam** [custom-components/alexa_media_player#560]
I use this component to announce my electric bill and I have noticed one thing with it. While announcing numbers, for example 2358, alexa instead of reading it as two thousand three hundred and fifty eight, reads as twenty three fifty eight. I have noticed this with 4 digit numbers and not aware of what happens with 5 or others. why is it so?

**Comment by alandtse** [comment]
You'll have to ask Amazon. You can see if [SSML](https://developer.amazon.com/en-US/docs/alexa/custom-skills/speech-synthesis-markup-language-ssml-reference.html#say-as) can help you.
