### ISSUE TITLE
Alexa Media Player captcha blank

### ISSUE THREAD

**Issue by Anon0ne** [custom-components/alexa_media_player#561]
I cannot get the captcha to refresh. It always says expired if I try to load the resource manually (copy/paste URL).

Any ideas other than removing integration and restarting?
![Screenshot_20200212-074230](https://user-images.githubusercontent.com/41264521/74336006-751e9780-4d6b-11ea-8cb3-873c2cbd7207.png)

**Comment by alandtse** [comment]
Enter anything and it'll issue a new captcha.
