### ISSUE TITLE
"next_alarm" not updated for timers with recurrence

### ISSUE THREAD

**Issue by chemelli74** [custom-components/alexa_media_player#566]
**Describe the bug**
After a alarm fire, value show past data, like "2 hours ago".

**To Reproduce**
1. Set a recurring alarm
2. Wait for it to fire
3. HA shows "1 hour ago"

**Expected behavior**
After a alarm fire, I would epect "next_alarm" to show the next one.
I think this is down to the way refresh is done.

**Screenshots**
![image](https://user-images.githubusercontent.com/57354320/74916972-0ffc1f00-53c7-11ea-9aa1-fdbf137cde9c.png)

**System details**
 - Home-assistant (version): 0.105.2
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): 2.5.5
 - alexapy (version from `pip show alexapy` or HA startup):

**Comment by chemelli74** [comment]
As expected, now that the refresh occured the sensor is updated:

![image](https://user-images.githubusercontent.com/57354320/74929971-e8b04c80-53dc-11ea-8eed-f3eae4fd17fd.png)

So the question is: how often is refreshed ? Can I force a more frequent refresh ?

Simone

**Comment by alandtse** [comment]
Every 10 minutes or on hearing a command.

**Comment by chemelli74** [comment]
> Every 10 minutes or on hearing a command.

That's not the case as I can clearly see "3 hours ago".

Simone

**Comment by alandtse** [comment]
Please provide logs (check wiki for info). We'll be looking for the following lines:
```
2020-02-20T09:10:39.014678506Z 2020-02-20 01:10:39 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.com/api/notifications returned 200:OK:application/json
2020-02-20T09:10:39.018985876Z 2020-02-20 01:10:39 DEBUG (MainThread) [custom_components.alexa_media] a******e@g*******m: Found 10 devices, 10 bluetooth
2020-02-20T09:10:39.020897547Z 2020-02-20 01:10:39 DEBUG (MainThread) [custom_components.alexa_media] a******e@g*******m: Updated 14 notifications for 6 devices at 2020-02-20 01:10:39.019570-08:00
```
We'll also need to see the json output from https://alexa.amazon.com/api/notifications (fix the region) for the specific alarm that isn't updating.

**Comment by chemelli74** [comment]
Accessing the site gives me the following page:

![image](https://user-images.githubusercontent.com/57354320/75100710-bca9ec80-55d1-11ea-81ea-5172e8ddb734.png)

Simone

**Comment by alandtse** [comment]
First, you'll need to update the url to the domain you are using to connect to Amazon (e.g., alexa.amazon.it if you're in Italy). Second, if you are seeing that on the correct domain, you have connectivity issues to Amazon and of course the component won't work.

**Comment by chemelli74** [comment]
> Please provide logs (check wiki for info). We'll be looking for the following lines:
> 
> ```
> 2020-02-20T09:10:39.014678506Z 2020-02-20 01:10:39 DEBUG (MainThread) [alexapy.alexaapi] static GET: https://alexa.amazon.com/api/notifications returned 200:OK:application/json
> 2020-02-20T09:10:39.018985876Z 2020-02-20 01:10:39 DEBUG (MainThread) [custom_components.alexa_media] a******e@g*******m: Found 10 devices, 10 bluetooth
> 2020-02-20T09:10:39.020897547Z 2020-02-20 01:10:39 DEBUG (MainThread) [custom_components.alexa_media] a******e@g*******m: Updated 14 notifications for 6 devices at 2020-02-20 01:10:39.019570-08:00
> ```

I see the GET (with 200 OK) but not the "udpated notifications" in my debug log.

Simone

**Comment by alandtse** [comment]
Can you please provide the json from the notifications page for the missing alarm?

**Comment by chemelli74** [comment]
> Can you please provide the json from the notifications page for the missing alarm?

Sure, how should I capture it ?

Simone

**Comment by alandtse** [comment]
@chemelli74 
> We'll also need to see the json output from https://alexa.amazon.com/api/notifications (fix the region) for the specific alarm that isn't updating.

**Comment by chemelli74** [comment]
taken at 09:36 (Rome)


{"notifications":[{"alarmTime":1584057600000,"automationId":null,"createdDate":1583795024866,"deferredAtTime":null,"deliveryType":null,"deviceName":null,"deviceSerialNumber":"xxxxxxxxxx","deviceType":"A1RABVCI4QCIKC","extensibleAttribute":null,"geoLocationTriggerData":null,"id":"A1RABVCI4QCIKC-xxxxxxxxx-8a3e70ce-c774-4909-98b6-082681e25c4b","lastOccurrenceTimeInMilli":0,"lastUpdatedDate":0,"musicAlarmId":null,"musicEntity":null,"notificationIndex":"8a3e70ce-c774-4909-98b6-082681e25c4b","originalDate":"2020-03-13","originalTime":"08:00:00.000","personProfile":null,"provider":null,"rRuleData":null,"recurrenceEligibility":false,"recurringPattern":"XXXX-WD","remainingTime":0,"reminderAppLabel":null,"reminderLabel":null,"reminderSubLabel":null,"skillInfo":null,"snoozedToTime":null,"sound":{"displayName":"Simple Alarm","folder":null,"id":"system_alerts_melodic_01","providerId":"ECHO","sampleUrl":"https://s3.amazonaws.com/deeappservice.prod.notificationtones/system_alerts_melodic_01.mp3"},"status":"ON","targetPersonProfiles":null,"timeZoneId":null,"timerLabel":null,"tmwNotificationProperties":null,"triggerTime":0,"type":"Alarm","version":"19"},{"alarmTime":1583798400000,"automationId":null,"createdDate":1581459338506,"deferredAtTime":null,"deliveryType":null,"deviceName":null,"deviceSerialNumber":"xxxxxxxxx","deviceType":"A1RABVCI4QCIKC","extensibleAttribute":null,"geoLocationTriggerData":null,"id":"A1RABVCI4QCIKC-xxxxxxx-9ef5918c-06ba-4a54-ba93-b7f1ab9d538f","lastOccurrenceTimeInMilli":0,"lastUpdatedDate":0,"musicAlarmId":null,"musicEntity":null,"notificationIndex":"9ef5918c-06ba-4a54-ba93-b7f1ab9d538f","originalDate":"2020-03-10","originalTime":"07:00:00.000","personProfile":null,"provider":null,"rRuleData":null,"recurrenceEligibility":false,"recurringPattern":"XXXX-WD","remainingTime":0,"reminderAppLabel":null,"reminderLabel":null,"reminderSubLabel":null,"skillInfo":null,"snoozedToTime":null,"sound":{"displayName":"Simple Alarm","folder":null,"id":"system_alerts_melodic_01","providerId":"ECHO","sampleUrl":"https://s3.amazonaws.com/deeappservice.prod.notificationtones/system_alerts_melodic_01.mp3"},"status":"OFF","targetPersonProfiles":null,"timeZoneId":null,"timerLabel":null,"tmwNotificationProperties":null,"triggerTime":0,"type":"Alarm","version":"81"},{"alarmTime":0,"automationId":null,"createdDate":1581717987717,"deferredAtTime":null,"deliveryType":null,"deviceName":null,"deviceSerialNumber":"xxxxxxx","deviceType":"A1RABVCI4QCIKC","extensibleAttribute":null,"geoLocationTriggerData":null,"id":"A1RABVCI4QCIKC-xxxxxx-ac4f1bee-cd90-33b4-bbbe-4c20c1d191f1","lastOccurrenceTimeInMilli":0,"lastUpdatedDate":0,"musicAlarmId":null,"musicEntity":null,"notificationIndex":"ac4f1bee-cd90-33b4-bbbe-4c20c1d191f1","originalDate":"2020-02-15","originalTime":"09:00:00.000","personProfile":null,"provider":null,"rRuleData":null,"recurrenceEligibility":false,"recurringPattern":null,"remainingTime":0,"reminderAppLabel":null,"reminderLabel":null,"reminderSubLabel":null,"skillInfo":null,"snoozedToTime":null,"sound":{"displayName":"Simple Alarm","folder":null,"id":"system_alerts_melodic_01","providerId":"ECHO","sampleUrl":"https://s3.amazonaws.com/deeappservice.prod.notificationtones/system_alerts_melodic_01.mp3"},"status":"OFF","targetPersonProfiles":null,"timeZoneId":null,"timerLabel":null,"tmwNotificationProperties":null,"triggerTime":0,"type":"Alarm","version":"3"},{"alarmTime":1583798400000,"automationId":null,"createdDate":1582700396167,"deferredAtTime":null,"deliveryType":null,"deviceName":null,"deviceSerialNumber":"xxxxxxxx","deviceType":"A1RABVCI4QCIKC","extensibleAttribute":null,"geoLocationTriggerData":null,"id":"A1RABVCI4QCIKC-xxxxxxx-f76fc3fc-768d-490d-afb0-a9ec92ce0e4f","lastOccurrenceTimeInMilli":0,"lastUpdatedDate":0,"musicAlarmId":null,"musicEntity":null,"notificationIndex":"f76fc3fc-768d-490d-afb0-a9ec92ce0e4f","originalDate":"2020-03-10","originalTime":"07:15:00.000","personProfile":null,"provider":null,"rRuleData":null,"recurrenceEligibility":false,"recurringPattern":"XXXX-WD","remainingTime":0,"reminderAppLabel":null,"reminderLabel":null,"reminderSubLabel":null,"skillInfo":null,"snoozedToTime":null,"sound":{"displayName":"Simple Alarm","folder":null,"id":"system_alerts_melodic_01","providerId":"ECHO","sampleUrl":"https://s3.amazonaws.com/deeappservice.prod.notificationtones/system_alerts_melodic_01.mp3"},"status":"OFF","targetPersonProfiles":null,"timeZoneId":null,"timerLabel":null,"tmwNotificationProperties":null,"triggerTime":0,"type":"Alarm","version":"81"}]}

**Comment by alandtse** [comment]
Thanks, can you identify which ones wasn't showing up that should've been showing up?

**Comment by chemelli74** [comment]
> Thanks, can you identify which ones wasn't showing up that should've been showing up?

Alarm was 8:00 am for working days

Simone

**Comment by alandtse** [comment]
Can you please provide the attributes for the next_alarm sensor in HA for that item? Is sorted_active empty?

**Comment by alandtse** [comment]
Never mind. Was able to reproduce it and have a fix.

**Comment by alandtse** [comment]
As a further note, Amazon does update the alarm json at midnight so any timers will show the next day's timers.
