### ISSUE TITLE
FR: show time/date in next_alarm

### ISSUE THREAD

**Issue by chemelli74** [custom-components/alexa_media_player#567]
**Is your feature request related to a problem? Please describe.**
Currently alarm is indicated as "in X hours"

![image](https://user-images.githubusercontent.com/57354320/74930104-35942300-53dd-11ea-9e5c-53a375c8a7c6.png)

**Describe the solution you'd like**
Would be nice to show "Tomorrow at 7:00am"

**Comment by alandtse** [comment]
This is controlled by Home Assistant.
