### ISSUE TITLE
How to Update New Devices and Group Changes with Echo Devices

### ISSUE THREAD

**Issue by mdframe** [custom-components/alexa_media_player#569]
I recently upgrade two of my echo devices with the latest version however I kept the same name.  I also created a new group.  Neither of these updates are reflected in the Home Assistant Hass.IO instance I run within docker.  I have the update switch set to "on" in my integrations and have restarted a few times.  I have tried turning the update switch on and off but still no luck. 

I know this is an end user issue however I have been unable to figure out how to force the updates for the Alexa Media plug-in from HACS appropriately.   

Thank you.

**Comment by alandtse** [comment]
You either manually change them in customization in HA or you have to manually delete them from the `config/.storage/core.entity_registry` and they can be readded with whatever the component gets from Amazon. Manual editing and deletion from the entity registry is dangerous so make sure you back up the file as you may break your HA.

**Comment by mdframe** [comment]
How would I add the new Echo group?  I have done a number of steps.  Echo and Alexa are using the new group just fine but nothing is updated in Home Assistant with it.  

I understand how to rename in Home Assistant and I did get the issue where I replaced the devices to begin working correctly but I just can get anything new to show up.

**Comment by alandtse** [comment]
After you remove it in HA, you reboot and the component will add it again when discovered.

**Comment by mdframe** [comment]
How would I remove a new item that was created in the Alexa system that has not shown up in HA to remove it so it can add it back?

**Comment by alandtse** [comment]
You delete the old entry because it's tied to the serial number.

**Comment by mdframe** [comment]
I don't have an old entry to delete.  At this point its only the NEW entry that is not showing.  The two devices I updated are correct and working now.  The new entry never showed up.

**Comment by alandtse** [comment]
Check this [page (use appropriate domain)](https://alexa.amazon.com/api/devices-v2/device). Does the device appear?

**Comment by gigios** [comment]
I have the same problem.
I have received a new Echo Show in these days but it's not available in the integration.
I have checked the alexa page linked by @alandtse and the device is available.
I have also tried to delete all the echo devices from the entity_registry and, after the reboot, I have again the older devices but not the new one.

**Comment by alandtse** [comment]
Please provide logs. There is a particular step where it identifies all media players it finds and will add.

**Comment by gigios** [comment]
The current workaround that I found is to remove the integration and after re-add and reconfigure. In this way I'm able to see also the new Echo Show in the available devices.

**Comment by alandtse** [comment]
Closing as stale. We can resume when you have time to provide logs.
