### ISSUE TITLE
Support Sleep Timer for Playback (PlaySearchPhrase)

### ISSUE THREAD

**Issue by embeddeddev** [custom-components/alexa_media_player#574]
**Is your feature request related to a problem? Please describe.**
Idea is to support Sleep Timer function like configurable for Play Music operation in Alexa App

**Describe the solution you'd like**
Support field ``waitTimeInSeconds`` for payload of existing play music type ``Alexa.Music.PlaySearchPhrase``

**Additional context**
A simple request looks like following.
The field ``waitTimeInSeconds``, that indicates the time to play until playback is stopped automatically, should be supported by HA YAML configration. Its contents below is just a working sample.

```json
{
  "@type": "com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode",
  "type": "Alexa.Music.PlaySearchPhrase",
  "skillId": null,
  "operationPayload": {
    "deviceType": "XXX",
    "waitTimeInSeconds": 1800,
    "sanitizedSearchPhrase": "XXX",
    "searchPhrase": "XXX",
    "customerId": "XXX",
    "locale": "XXX",
    "musicProviderId": "XXX",
    "deviceSerialNumber": "XXX"
 }
```

**Comment by alandtse** [comment]
Thanks. HA won't allow this info to be passed through I believe because the `play_media` service doesn't allow additional arguments. If that's changed, please let me know and I'll look into it.

**Comment by embeddeddev** [comment]
OK, that's really sub-optimal.

But ever thought of by-passing the direct use of ``media_player.play_media`` and to provide some wrapper service calls for "media playback" w/ extended arguments (e.g. ``alexa_media.play_media_ex`` or similar) like those for sleep timer above and others if possible.

It would be even an option to implement the TTS support (see #573) and many other functionality.

**Comment by alandtse** [comment]
If HA decides to provide that capability, then I'll look into it.
