### ISSUE TITLE
Can video be incorporated?

### ISSUE THREAD

**Issue by mikesalz** [custom-components/alexa_media_player#581]
This is a question/feature request: Can video be incorporated into an automation using this component?  For example, I have arlo cameras in my kids' rooms.  I already have them integrated into HA.  I would like to create an automation that displays video on an Echo Show when sound is detected in their rooms.  Is this possible?  Thanks in advance!

**Comment by alandtse** [comment]
If the Alexa mobile app allows it, then we potentially can. If not, then we probably can't. Do you know if the Alexa app can?

**Comment by mikesalz** [comment]
Truthfully, I don't know.  Alexa has always been my red-headed step child in the world of home automation.  :)  I will investigate further and let you know if I have any luck.  Thanks for getting back to me!

**Comment by alandtse** [comment]
I'll close this now, but please feel free to reopen if you find out anything.
