### ISSUE TITLE
Uninstallation Not Completed in Full

### ISSUE THREAD

**Issue by IIAIronWolf** [custom-components/alexa_media_player#583]
After realizing that there was not much functionality available (to include lack of ability to send text to speech notifications), I uninstalled the alexa_media integration from the HACS store, Integrations page. Now everytime I restart my Home Assistant, I get the following message: 
"The following integrations and platforms could not be set up:

alexa_media
Please check your config."

There is nothing related to this integration visible in the config/ folder, configuration.yaml, or in the custom_components folder.
My entities are now also flooded with media players, since I use a Family Amazon account. All my family's Alexa devices are showing up on my Home Assistant.

1. Restart Home Assistant after uninstalling the Alexa addon from the HACS store.
2. Click on 'Notifications'
3. Error appears as: 
"The following integrations and platforms could not be set up:

alexa_media
Please check your config."

**Comment by IIAIronWolf** [comment]
Found the fix, I think. There was still the entire collection of Alexa devices in Configuration > Integrations > Alexa Media Player

**Comment by IIAIronWolf** [comment]
I see this is closed, but might want to add it to the instructions or add an uninstallation script...

**Comment by alandtse** [comment]
Thanks. People will either find this issue or you can update the [wiki](https://github.com/custom-components/alexa_media_player/wiki).
