### ISSUE TITLE
Alexa stays silent on Announcement and message

### ISSUE THREAD

**Issue by dreimer1986** [custom-components/alexa_media_player#584]
**Describe the bug**
Since a few days I cannot send and text to say to Alexa anymore

**To Reproduce**
I removed the configuration.yaml part as test and used the Integration one. (Pickle removed too) Added all my amazon.de settings I have for my account and some exclusions. It was saved nicely and three devices are returning. So far so good.

**Expected behavior**
Messages and Announcements should do something.

**Screenshots**

**System details**
 - Home-assistant (version): 0.106.5
 - Hassio (Yes/No): yes
 - alexa_media  (version from `const.py` or HA startup): HACS head one
 - alexapy (version from `pip show alexapy` or HA startup): HACS head one

**Logs**
```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/alexa/state_report.py", line 46, in async_entity_state_listener
    hass, smart_home_config, alexa_changed_entity
  File "/usr/src/homeassistant/homeassistant/components/alexa/state_report.py", line 79, in async_send_changereport_message
    properties = list(alexa_entity.serialize_properties())
  File "/usr/src/homeassistant/homeassistant/components/alexa/entities.py", line 264, in serialize_properties
    for prop in interface.serialize_properties():
  File "/usr/src/homeassistant/homeassistant/components/alexa/capabilities.py", line 231, in serialize_properties
    prop_value = self.get_property(prop_name)
  File "/usr/src/homeassistant/homeassistant/components/alexa/capabilities.py", line 674, in get_property
    current = math.floor(int(current_level * 100))
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```
```
Timeout sending report to Alexa.
```
```
Error when sending ChangeReport to Alexa: THROTTLING_EXCEPTION: Request could not be processed due to throttling.
```
**Additional context**
A automation not working anymore:
```
- id: nas-temp-automation
  alias: 'NAS Temp Automation'
  trigger:
  - platform: time_pattern
    minutes: '/5'
  condition:
  - condition: state
    entity_id: binary_sensor.hdd_temp
    state: 'on'
  action:
  - service: notify.alexa_media
    data:
      target: 
        media_player.daniels_echo
        media_player.daniels_echo_dot
      data:
        type: announce
      message: 'WARNUNG! NAS Festplatten Temperatur zu hoch!'
  - service: notify.telegrambot
    data:
      message: 'WARNUNG! NAS Festplatten Temperatur zu hoch!'
```

**Comment by alandtse** [comment]
The log errors are coming from the official component and not from `alexa_media`. Are you seeing logs from the custom component? Can you do a test service call at all with logs for alexapy? Again, the wiki has instructions for how to enable.

One thing to note, if the official component is having problems, you may be having other issues with Alexa too.

**Comment by dreimer1986** [comment]
Will try later at home. Funfact, when my doorbell is ringing, Alexa is outputting a bell sound with your addin. That works fine...

**Comment by dreimer1986** [comment]
Ok... That is my own stupidity.... Cleaning up the automation yaml trying to make it home assistant web ui suppportive made the - vanish in the target section... Readding them and all is fine...
