### ISSUE TITLE
FR: Correctly handle 2nd alarm

### ISSUE THREAD

**Issue by chemelli74** [custom-components/alexa_media_player#592]
**Is your feature request related to a problem? Please describe.**
Adding an alarm that will fire before the previous one, doesn't update "next_alarm" accordly.

**Describe the solution you'd like**
"next_alarm" should always reflect the first alarm firing if more than one alarm are configured.

**Describe alternatives you've considered**
None

**Additional context**
Current behaviour:

- set an alarm at 8am
- wait for HA to show it
- set **additional** alarm at 7am
- HA never update to the new alarm even if it's the first in time

**Comment by alandtse** [comment]
How are you creating the alarms? Are you doing it via voice are you doing it via the app?

**Comment by chemelli74** [comment]
Depends; usually I do the recurring ones via app and the one time exception via voice.

Simone

**Comment by chemelli74** [comment]
@alandtse I found another edge situation: 

- ask Alexa to enable a recurring alarm for workdays at 7am
- ask Alexa to delete next alarm. Will ask to do it for all workdays, says just "no"
- ask Alexa to add a alarm for tomorrow at 9am

Automations that fire 10 minutes after "next_alarm" will fire at 7.10 and not at 9.10

Available for debugging, if needed.

Simone

**Comment by alandtse** [comment]
Can you please pull the notifications page for this?
https://alexa.amazon.com/api/notifications

The second use case is probably the same as #488 where Amazon doesn't update cancelled alarms until midnight US time.

**Comment by chemelli74** [comment]
> Can you please pull the notifications page for this?
> https://alexa.amazon.com/api/notifications

`{"notifications":[{"alarmTime":0,"automationId":null,"createdDate":1565469683960,"deferredAtTime":null,"deliveryType":null,"deviceName":null,"deviceSerialNumber":"xxxxx","deviceType":"A1RABVCI4QCIKC","extensibleAttribute":null,"geoLocationTriggerData":null,"id":"A1RABVCI4QCIKC-xxxxx-864dfab5-5822-3ba5-ada6-ab81950e6166","lastOccurrenceTimeInMilli":0,"lastUpdatedDate":0,"musicAlarmId":null,"musicEntity":null,"notificationIndex":"864dfab5-5822-3ba5-ada6-ab81950e6166","originalDate":"2019-08-11","originalTime":"08:00:00.000","personProfile":null,"provider":null,"rRuleData":null,"recurrenceEligibility":false,"recurringPattern":null,"remainingTime":0,"reminderAppLabel":null,"reminderLabel":null,"reminderSubLabel":null,"skillInfo":null,"snoozedToTime":null,"sound":{"displayName":"Simple Alarm","folder":null,"id":"system_alerts_melodic_01","providerId":"ECHO","sampleUrl":"https://s3.amazonaws.com/deeappservice.prod.notificationtones/system_alerts_melodic_01.mp3"},"status":"OFF","targetPersonProfiles":null,"timeZoneId":null,"timerLabel":null,"tmwNotificationProperties":null,"triggerTime":0,"type":"Alarm","version":"5"},{"alarmTime":0,"automationId":null,"createdDate":1566241761147,"deferredAtTime":null,"deliveryType":null,"deviceName":null,"deviceSerialNumber":"xxxxxx","deviceType":"A1RABVCI4QCIKC","extensibleAttribute":null,"geoLocationTriggerData":null,"id":"A1RABVCI4QCIKC-xxxxxx-8a3ce67f-6647-3b65-9c36-e0b7f70996eb","lastOccurrenceTimeInMilli":0,"lastUpdatedDate":0,"musicAlarmId":null,"musicEntity":null,"notificationIndex":"8a3ce67f-6647-3b65-9c36-e0b7f70996eb","originalDate":"2019-08-20","originalTime":"04:15:00.000","personProfile":null,"provider":null,"rRuleData":null,"recurrenceEligibility":false,"recurringPattern":null,"remainingTime":0,"reminderAppLabel":null,"reminderLabel":null,"reminderSubLabel":null,"skillInfo":null,"snoozedToTime":null,"sound":{"displayName":"Simple Alarm","folder":null,"id":"system_alerts_melodic_01","providerId":"ECHO","sampleUrl":"https://s3.amazonaws.com/deeappservice.prod.notificationtones/system_alerts_melodic_01.mp3"},"status":"OFF","targetPersonProfiles":null,"timeZoneId":null,"timerLabel":null,"tmwNotificationProperties":null,"triggerTime":0,"type":"Alarm","version":"5"}]}
` 
> The second use case is probably the same as #488 where Amazon doesn't update cancelled alarms until midnight US time.

Do you know the time zone used for the update ?

Simone

**Comment by alandtse** [comment]
The notifications you posted don't match the use case you mentioned. They show two inactive alarms.  Can you please provide a notifications page for the relevant use case? You may have to change the domain to what you log into.

> Do you know the time zone used for the update ?

PST.

**Comment by chemelli74** [comment]
HI, actions performed a few minutes ago:

- ask Alexa to delete next alarm (7:30am). Will ask to do it for all workdays, says just "no"
- ask Alexa to add a alarm for tomorrow at 8:00am

notifications:

`{"notifications":[{"alarmTime":0,"automationId":null,"createdDate":1590323611699,"deferredAtTime":null,"deliveryType":null,"deviceName":null,"deviceSerialNumber":"xxxxx","deviceType":"A1RABVCI4QCIKC","extensibleAttribute":null,"geoLocationTriggerData":null,"id":"A1RABVCI4QCIKC-xxxxxx-27d075d8-b531-32aa-8110-6e1ccaae6758","lastOccurrenceTimeInMilli":0,"lastUpdatedDate":0,"musicAlarmId":null,"musicEntity":null,"notificationIndex":"27d075d8-b531-32aa-8110-6e1ccaae6758","originalDate":"2020-05-24","originalTime":"14:38:00.000","personProfile":null,"provider":null,"rRuleData":null,"recurrenceEligibility":false,"recurringPattern":null,"remainingTime":0,"reminderAppLabel":null,"reminderLabel":null,"reminderSubLabel":null,"skillInfo":null,"snoozedToTime":null,"sound":{"displayName":"Simple Alarm","folder":null,"id":"system_alerts_melodic_01","providerId":"ECHO","sampleUrl":"https://s3.amazonaws.com/deeappservice.prod.notificationtones/system_alerts_melodic_01.mp3"},"status":"OFF","targetPersonProfiles":null,"timeZoneId":null,"timerLabel":null,"tmwNotificationProperties":null,"triggerTime":0,"type":"Alarm","version":"4"},{"alarmTime":0,"automationId":null,"createdDate":1590234497602,"deferredAtTime":null,"deliveryType":null,"deviceName":null,"deviceSerialNumber":"xxxxxx","deviceType":"A1RABVCI4QCIKC","extensibleAttribute":null,"geoLocationTriggerData":null,"id":"A1RABVCI4QCIKC-xxxxxxxx-3e9bb581-51a6-4a22-9687-41135c77ffa1","lastOccurrenceTimeInMilli":0,"lastUpdatedDate":0,"musicAlarmId":null,"musicEntity":null,"notificationIndex":"3e9bb581-51a6-4a22-9687-41135c77ffa1","originalDate":"2020-05-23","originalTime":"14:00:00.000","personProfile":null,"provider":null,"rRuleData":null,"recurrenceEligibility":false,"recurringPattern":null,"remainingTime":0,"reminderAppLabel":null,"reminderLabel":null,"reminderSubLabel":null,"skillInfo":null,"snoozedToTime":null,"sound":{"displayName":"Simple Alarm","folder":null,"id":"system_alerts_melodic_01","providerId":"ECHO","sampleUrl":"https://s3.amazonaws.com/deeappservice.prod.notificationtones/system_alerts_melodic_01.mp3"},"status":"OFF","targetPersonProfiles":null,"timeZoneId":null,"timerLabel":null,"tmwNotificationProperties":null,"triggerTime":0,"type":"Alarm","version":"4"},{"alarmTime":0,"automationId":null,"createdDate":1585498621746,"deferredAtTime":null,"deliveryType":null,"deviceName":null,"deviceSerialNumber":"xxxxxxxxxxx","deviceType":"A1RABVCI4QCIKC","extensibleAttribute":null,"geoLocationTriggerData":null,"id":"A1RABVCI4QCIKC-xxxxxxxxxxxxx-45c50c9d-6744-360b-94d9-b782efdaf2eb","lastOccurrenceTimeInMilli":0,"lastUpdatedDate":0,"musicAlarmId":null,"musicEntity":null,"notificationIndex":"45c50c9d-6744-360b-94d9-b782efdaf2eb","originalDate":"2020-03-29","originalTime":"19:30:00.000","personProfile":null,"provider":null,"rRuleData":null,"recurrenceEligibility":false,"recurringPattern":null,"remainingTime":0,"reminderAppLabel":null,"reminderLabel":null,"reminderSubLabel":null,"skillInfo":null,"snoozedToTime":null,"sound":{"displayName":"Simple Alarm","folder":null,"id":"system_alerts_melodic_01","providerId":"ECHO","sampleUrl":"https://s3.amazonaws.com/deeappservice.prod.notificationtones/system_alerts_melodic_01.mp3"},"status":"OFF","targetPersonProfiles":null,"timeZoneId":null,"timerLabel":null,"tmwNotificationProperties":null,"triggerTime":0,"type":"Alarm","version":"3"},{"alarmTime":0,"automationId":null,"createdDate":1586779388215,"deferredAtTime":null,"deliveryType":null,"deviceName":null,"deviceSerialNumber":"xxxxxxxxxxxx","deviceType":"A1RABVCI4QCIKC","extensibleAttribute":null,"geoLocationTriggerData":null,"id":"A1RABVCI4QCIKC-xxxxxxxxxxxxxxx-4ab3672f-3926-3b08-b0d6-b69b942a7842","lastOccurrenceTimeInMilli":0,"lastUpdatedDate":0,"musicAlarmId":null,"musicEntity":null,"notificationIndex":"4ab3672f-3926-3b08-b0d6-b69b942a7842","originalDate":"2020-04-13","originalTime":"14:25:00.000","personProfile":null,"provider":null,"rRuleData":null,"recurrenceEligibility":false,"recurringPattern":null,"remainingTime":0,"reminderAppLabel":null,"reminderLabel":null,"reminderSubLabel":null,"skillInfo":null,"snoozedToTime":null,"sound":{"displayName":"Simple Alarm","folder":null,"id":"system_alerts_melodic_01","providerId":"ECHO","sampleUrl":"https://s3.amazonaws.com/deeappservice.prod.notificationtones/system_alerts_melodic_01.mp3"},"status":"OFF","targetPersonProfiles":null,"timeZoneId":null,"timerLabel":null,"tmwNotificationProperties":null,"triggerTime":0,"type":"Alarm","version":"3"},{"alarmTime":1585180800000,"automationId":null,"createdDate":1585210278243,"deferredAtTime":null,"deliveryType":null,"deviceName":null,"deviceSerialNumber":"xxxxxxxxx","deviceType":"A1RABVCI4QCIKC","extensibleAttribute":null,"geoLocationTriggerData":null,"id":"A1RABVCI4QCIKC-xxxxxxxxxxxxxx-a398ba4f-9b67-3a7a-ba1f-53cd54c6f0c6","lastOccurrenceTimeInMilli":0,"lastUpdatedDate":0,"musicAlarmId":null,"musicEntity":null,"notificationIndex":"a398ba4f-9b67-3a7a-ba1f-53cd54c6f0c6","originalDate":"2020-03-26","originalTime":"16:00:00.000","personProfile":null,"provider":null,"rRuleData":null,"recurrenceEligibility":false,"recurringPattern":null,"remainingTime":0,"reminderAppLabel":null,"reminderLabel":null,"reminderSubLabel":null,"skillInfo":null,"snoozedToTime":null,"sound":{"displayName":"Simple Alarm","folder":null,"id":"system_alerts_melodic_01","providerId":"ECHO","sampleUrl":"https://s3.amazonaws.com/deeappservice.prod.notificationtones/system_alerts_melodic_01.mp3"},"status":"OFF","targetPersonProfiles":null,"timeZoneId":null,"timerLabel":null,"tmwNotificationProperties":null,"triggerTime":0,"type":"Alarm","version":"4"},{"alarmTime":0,"automationId":null,"createdDate":1586209673441,"deferredAtTime":null,"deliveryType":null,"deviceName":null,"deviceSerialNumber":"xxxxxxxxxx","deviceType":"A1RABVCI4QCIKC","extensibleAttribute":null,"geoLocationTriggerData":null,"id":"A1RABVCI4QCIKC-xxxxxxxxxxxxx-08e58aed-1dc0-30e4-b275-f0579c62ee61","lastOccurrenceTimeInMilli":0,"lastUpdatedDate":0,"musicAlarmId":null,"musicEntity":null,"notificationIndex":"08e58aed-1dc0-30e4-b275-f0579c62ee61","originalDate":"2020-05-25","originalTime":"08:00:00.000","personProfile":null,"provider":null,"rRuleData":null,"recurrenceEligibility":false,"recurringPattern":null,"remainingTime":0,"reminderAppLabel":null,"reminderLabel":null,"reminderSubLabel":null,"skillInfo":null,"snoozedToTime":null,"sound":{"displayName":"Simple Alarm","folder":null,"id":"system_alerts_melodic_01","providerId":"ECHO","sampleUrl":"https://s3.amazonaws.com/deeappservice.prod.notificationtones/system_alerts_melodic_01.mp3"},"status":"ON","targetPersonProfiles":null,"timeZoneId":null,"timerLabel":null,"tmwNotificationProperties":null,"triggerTime":0,"type":"Alarm","version":"35"},{"alarmTime":0,"automationId":null,"createdDate":1585518423582,"deferredAtTime":null,"deliveryType":null,"deviceName":null,"deviceSerialNumber":"xxxxxxxxxxxx","deviceType":"A1RABVCI4QCIKC","extensibleAttribute":null,"geoLocationTriggerData":null,"id":"A1RABVCI4QCIKC-xxxxxxxxxxxxxx-1aa44aa7-deb0-30d7-9416-3606bf0e43d5","lastOccurrenceTimeInMilli":0,"lastUpdatedDate":0,"musicAlarmId":null,"musicEntity":null,"notificationIndex":"1aa44aa7-deb0-30d7-9416-3606bf0e43d5","originalDate":"2020-03-30","originalTime":"07:30:00.000","personProfile":null,"provider":null,"rRuleData":null,"recurrenceEligibility":false,"recurringPattern":null,"remainingTime":0,"reminderAppLabel":null,"reminderLabel":null,"reminderSubLabel":null,"skillInfo":null,"snoozedToTime":null,"sound":{"displayName":"Simple Alarm","folder":null,"id":"system_alerts_melodic_01","providerId":"ECHO","sampleUrl":"https://s3.amazonaws.com/deeappservice.prod.notificationtones/system_alerts_melodic_01.mp3"},"status":"OFF","targetPersonProfiles":null,"timeZoneId":null,"timerLabel":null,"tmwNotificationProperties":null,"triggerTime":0,"type":"Alarm","version":"3"},{"alarmTime":1585267200000,"automationId":null,"createdDate":1585235020908,"deferredAtTime":null,"deliveryType":null,"deviceName":null,"deviceSerialNumber":"xxxxxxxxxxxx","deviceType":"A1RABVCI4QCIKC","extensibleAttribute":null,"geoLocationTriggerData":null,"id":"A1RABVCI4QCIKC-xxxxxxxxxxxxxx-8a3e70ce-c774-4909-98b6-082681e25c4b","lastOccurrenceTimeInMilli":0,"lastUpdatedDate":0,"musicAlarmId":null,"musicEntity":null,"notificationIndex":"8a3e70ce-c774-4909-98b6-082681e25c4b","originalDate":"2020-03-27","originalTime":"07:00:00.000","personProfile":null,"provider":null,"rRuleData":null,"recurrenceEligibility":false,"recurringPattern":"XXXX-WD","remainingTime":0,"reminderAppLabel":null,"reminderLabel":null,"reminderSubLabel":null,"skillInfo":null,"snoozedToTime":null,"sound":{"displayName":"Simple Alarm","folder":null,"id":"system_alerts_melodic_01","providerId":"ECHO","sampleUrl":"https://s3.amazonaws.com/deeappservice.prod.notificationtones/system_alerts_melodic_01.mp3"},"status":"OFF","targetPersonProfiles":null,"timeZoneId":null,"timerLabel":null,"tmwNotificationProperties":null,"triggerTime":0,"type":"Alarm","version":"65"},{"alarmTime":1590364800000,"automationId":null,"createdDate":1585235015377,"deferredAtTime":null,"deliveryType":null,"deviceName":null,"deviceSerialNumber":"xxxxxxxxxxxxx","deviceType":"A1RABVCI4QCIKC","extensibleAttribute":null,"geoLocationTriggerData":null,"id":"A1RABVCI4QCIKC-xxxxxxxxxxxxxx-9ef5918c-06ba-4a54-ba93-b7f1ab9d538f","lastOccurrenceTimeInMilli":0,"lastUpdatedDate":0,"musicAlarmId":null,"musicEntity":null,"notificationIndex":"9ef5918c-06ba-4a54-ba93-b7f1ab9d538f","originalDate":"2020-05-25","originalTime":"07:30:00.000","personProfile":null,"provider":null,"rRuleData":null,"recurrenceEligibility":false,"recurringPattern":"XXXX-WD","remainingTime":0,"reminderAppLabel":null,"reminderLabel":null,"reminderSubLabel":null,"skillInfo":null,"snoozedToTime":null,"sound":{"displayName":"Simple Alarm","folder":null,"id":"system_alerts_melodic_01","providerId":"ECHO","sampleUrl":"https://s3.amazonaws.com/deeappservice.prod.notificationtones/system_alerts_melodic_01.mp3"},"status":"ON","targetPersonProfiles":null,"timeZoneId":null,"timerLabel":null,"tmwNotificationProperties":null,"triggerTime":0,"type":"Alarm","version":"268"}]}`

Simone

**Comment by alandtse** [comment]
What does the app show. Per the notifications json, it should have two alarms active. 7:30 and 8:00 AM for 2020-05-25.

**Comment by alandtse** [comment]
Ok, this is looks like the same behavior as #488, a cancelled recurring Alarm doesn't show any indication it's cancelled in the notifications page. This is an Amazon issue. 

I also realized you changed the issue in the thread. I will mark everything about the second issue as offtopic.  The first issue I can't reproduce. It works fine in my system. You need to provide logs for the first issue.

**Comment by chemelli74** [comment]
I see you marked some comments as off-topic. How should we proceed now to debug the issue, if it's possible to debug ?

Simone

**Comment by alandtse** [comment]
I still need the notifications json for the actual issue reported in the thread.

**Comment by chemelli74** [comment]
Works fine since some versions.
Sorry I did a very late report :-(

Simone
