### ISSUE TITLE
Allow Volume setting on notify.alexa_media

### ISSUE THREAD

**Issue by phrfpeixoto** [custom-components/alexa_media_player#593]
**Is your feature request related to a problem? Please describe.**
It's annoying when your automation plays a loud sound just because you listened to a loud music the day before.

**Describe the solution you'd like**
Allow Volume setting on _notify.alexa_media_ service. They way we can set the announces to be played using a specific volume

**Describe alternatives you've considered**
One could use media_player.volume_set, but there's no straightforward way of restoring the previous setting

**Additional context**
N/A

**Comment by alandtse** [comment]
How would you propose exposing this in HA? I'm not aware of any volume set service for notifications to leverage.

**Comment by phrfpeixoto** [comment]
I opened a similar issue on the alexapy lib, since all of your Alexa API consumption is based on it. Their response is that this API is currently undocumented, so we can't have a way to know whether or not the volume parameter is possible.

What we can so is handle this programatically:
- Store the current volume (as you do on `async_mute_volume`)
- Set the volume to the requested one
- Play the TTS
- Restore the previous volume.

The downside is that it would turn the TTS playback into 3 different API calls.
I'll try to make a PR about this.

**Comment by alandtse** [comment]
Seems awfully complicated given you can do it with automations. Also, you haven't said how it'd be exposed in HA. The `play_media` service doesn't allow for keyword passing. Are you proposing another service?

**Comment by alexborro** [comment]
I second that feature. I have the same problem: sometimes listening to music in low volume, but want announces to be played louder.
I thought about adding extra fields to data dictionary, like:

```
data_template:
  data:
    type: announce
    **volume: 0.8**
  message: 'My Message'
service: notify.alexa_media_my_echo_dot
```

**Comment by alandtse** [comment]
Good news, it looks like HA just enabled the ability to add something like this in 0.115.4. I'll look into adding it.
