### ISSUE TITLE
Unable to find alexapy when restoring configuration directory

### ISSUE THREAD

**Issue by faspina** [custom-components/alexa_media_player#597]
**Describe the bug**
I get this in the log when I try to install Alexa Media from integration
loading configuration flow for integration alexa_media: cannot import name 'AlexapyLoginError' from 'alexapy' (/config/deps/lib/python3.7/site-packages/alexapy/__init__.py)

**To Reproduce**
1. Installed VIA hacs
2. Click on confuration>>integration
3. Click + For Alexa Media Player , just does back to integration list 
4. See error in logg
loading configuration flow for integration alexa_media: cannot import name 'AlexapyLoginError' from 'alexapy' (/config/deps/lib/python3.7/site-packages/alexapy/__init__.py)

**Expected behavior**
I had to redo my entire HA app after some Zwave errors on 0.107  so I reinstalled the config director from backup, this is the last thing i need to get working. tried to take it all out and put it back in but still getting this error.  I am not getting notified of a Captcha

**Screenshots**

**System details**
 - Home-assistant (version): 
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by alandtse** [comment]
If you reinstalled from backup then multiple things are likely broken. Uninstall it from HACS and reinstall. Make sure you don't have an old version of `alexapy` in your config directory.
