### ISSUE TITLE
Bluetooth cant be selected from dropdown 

### ISSUE THREAD

**Issue by theHasp** [custom-components/alexa_media_player#598]
**Describe the bug**
Everything is working great. So I added a bluetooth connection to my echoDot AFTER it was allready connected to homeassistant. Result expected: Dropdown does show bluetooth ... Reality: it is not shown ...

**Comment by theHasp** [comment]
BY the way: it would be awesome if I could switch to bluetooth and back via automation.

**Comment by alandtse** [comment]
Is the bluetooth connection of a bluetooth `source` (input) or of a `sink` (output). The component [will not show `sinks`](https://github.com/custom-components/alexa_media_player/issues/367).

**Comment by alandtse** [comment]
And yes, you can connect using the [service to bluetooth sources and sinks](https://github.com/custom-components/alexa_media_player/wiki/Automation-examples#selecting-bluetooth-speakers-for-alexa-output).

**Comment by theHasp** [comment]
AWESOME 

that was exactly what I was searching for ...
THANKS
