### ISSUE TITLE
Getting 403 Forbidden on CAPCHA image

### ISSUE THREAD

**Issue by aidanblack** [custom-components/alexa_media_player#606]
**Describe the bug**
When trying to configure the component after updating to HA Core 107.5 the CAPCHA image doesn't display. Web Inspector in Safari indicates the image fails to load with a 403 Forbidden response.

**To Reproduce**
1. Click on Notifications
2. Click Configure button
3. Configurator pop-up displays
4. Image is not shown in the pop-up

**Expected behavior**
CAPCHA image should display in order to complete configuration

**Screenshots**
![Screen Shot 2020-03-23 at 17 52 33](https://user-images.githubusercontent.com/867786/77370645-57136200-6d2f-11ea-81cb-343b77e98441.png)

**System details**
 - Home-assistant (version): 107.5
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): v2.5.8

**Comment by alandtse** [comment]
Hit confirm and it'll refresh it. Safari would of course fail because Safari doesn't have the session token. Only the alexa_medium has the appropriate session tokens to show it.

**Comment by aidanblack** [comment]
Pressing Confirm just dismissed the pop-up. Clicking Configure again results in the same thing. This happens in Safari, Chrome, and the iOS app.

**Comment by aidanblack** [comment]
In the end I had to completely remove the integration

**Comment by jeepotvin** [comment]
I had the same problem. Hitting CONFIRM did not bring back a new captcha to be resolved.
Restarting Home Assistant did the trick.
