### ISSUE TITLE
Online Status of Echo Devices

### ISSUE THREAD

**Issue by Sajivve** [custom-components/alexa_media_player#608]
Hi, I have a situation where I have an Echo Dot installed in a Postbox to welcome the Postman.

I needed automation which can trigger a message on the home Echo that the Echo is offline.

I can't seem to find the Variable or State to monitor.

Can someone help me with an automation Example?

Regards

**Comment by alandtse** [comment]
You likely won't get automation support in the GitHub. I'll leave it open for a bit to see if anyone offers but your best bet is in the community thread.

**Comment by cgc007** [comment]
`{{ states("media_player.family_room") }}` doesn't work?

Mine report standby, or playing. However, they're all powered 24/7. Not sure what the state would be if it were off. Some testing could be done obviously.

Perhaps this helps you find the right spot?

**Comment by alandtse** [comment]
They will go `unavailable` same as if you pull the plug on them.
