### ISSUE TITLE
Dont see option to add in integrations

### ISSUE THREAD

**Issue by gbdavidx** [custom-components/alexa_media_player#609]
Using latest version of home-asssitant, try to add but the option isnt in there 
https://imgur.com/a/NC67iwv

**Comment by alandtse** [comment]
Refresh your browser cache.

**Comment by gbdavidx** [comment]
dude, i tried ingognito mode....

**Comment by alandtse** [comment]
How did you [install](https://github.com/custom-components/alexa_media_player/wiki/Installation-and-Configuration) the component?
