### ISSUE TITLE
The media player state doesn't clear after pausing and running another audio command

### ISSUE THREAD

**Issue by Flavien** [custom-components/alexa_media_player#617]
**Describe the bug**
The state of the component doesn't seem to update after stopping/pausing.

**To Reproduce**
1. Play something by saying e.g. "Play XXX on deezer".
2. Ask Alexa to stop playing.
3. Ask Alexa for a news update.
4. The Alexa app doesn't show anything as currently playing anymore. Yet, the state of the media player is still `paused` with all the attributes still reflecting what was playing initially:
- media_content_type
- media_duration
- media_position
- media_position_updated_at
- media_title
- media_artist
- media_album_name

Trying to resume playing from Home Assistant fails.

**Expected behavior**
The state of the media player component should no longer be `paused` (it should be back to `idle` or `standby`).

**System details**
 - Home-assistant (version): 0.107.7
 - Hassio: No
 - alexa_media: 2.5.6
 - alexapy: 1.5.1

**Comment by alandtse** [comment]
Please update it with the latest information. I'm not doing any work on the code that old.

**Comment by alandtse** [comment]
To respond to the statement that it's not cosmetic, as long as Amazon is reporting the device is playing through the mediaplayer json, then the component is reporting the proper state. If you see that the mediaplayer json actually clears, then it'll be something I can look at.

**Comment by Flavien** [comment]
Yes it's reporting this:

```
{"playerInfo":{"hint":null,"infoText":null,"isPlayingInLemur":false,"lemurVolume":null,"lyrics":null,"mainArt":null,"mediaId":null,"miniArt":null,"miniInfoText":null,"playbackSource":null,"playingInLemurId":null,"progress":null,"provider":null,"quality":null,"queueId":null,"state":null,"template":null,"transport":null,"upNextItems":null,"volume":null}}
```

The `alexa_media_player` component is still reporting its state is paused.

**Comment by alandtse** [comment]
Please provide logs for `alexa_media` and `alexapy` following the steps you highlighted and please annotate the timestamps for when you perform each step.

**Comment by Flavien** [comment]
I don't see any log entry related to `alexa_media_player` or `alexapy` in the Home Assistant server logs. Do they need to be enabled?

**Comment by alandtse** [comment]
Yes, the template has instructions on how to enable.

**Comment by Flavien** [comment]
[Here](https://gist.github.com/Flavien/3c22140c5b30890542d5fd88a36bbde4) are the logs with a repro of the issue, including the JSON response from the API at each step. The point at which each command is issued is marked in the file.

1. "**Play XXX on Deezer**", `state_1.json` shows the state as playing
2. "**Stop**", `state_2.json` shows the state as paused. The `alexa_media_player` component updates its state to reflect this.
3. "**Play the news**", `state_3.json` is now cleared, yet the `alexa_media_player` component remains in paused state.

**Comment by alandtse** [comment]
Thanks. Downloaded the logs if you wan to remove them.

**Comment by alandtse** [comment]
Is the news command the only one you're seeing doing this?

**Comment by Flavien** [comment]
> Just to confirm, the steps are you vocally saying this to the playing Echo?

Yes that's the commands I'm saying to the Echo.

> I'm seeing some commands but they don't necessarily line up to the annotation (but perhaps you were just identifying large sections, which might explain it).

These are the only 3 commands I said, but Deezer moved to the next song on the playlist on its own. It might be what you saw.

> Is the news command the only one you're seeing doing this?

No, it's the same with various different commands. For example, if I ask for the weather.

**Comment by alandtse** [comment]
Please test the PR.

**Comment by Flavien** [comment]
Thanks @alandtse. It's working great now.
