### ISSUE TITLE
hide email

### ISSUE THREAD

**Issue by vMeph** [custom-components/alexa_media_player#625]
is there plans to hide the our emails from integrations?
![1](https://user-images.githubusercontent.com/12812111/78308370-340f5c00-7540-11ea-9650-ddab8e2184e6.png)
also in configuration folder?
![2](https://user-images.githubusercontent.com/12812111/78308390-3f628780-7540-11ea-99f2-fadad304b798.png)

**Comment by alandtse** [comment]
No. What's the concern about people with access to HA?

**Comment by vMeph** [comment]
there is no concerns just was wondering why would it need to show in integrations

**Comment by alandtse** [comment]
Some people have multiple Amazon accounts. They need a way to differentiate which integration or pickle is for which account.
