### ISSUE TITLE
Hass 0.108 (now beta) logo brand missing.

### ISSUE THREAD

**Issue by sagitt** [custom-components/alexa_media_player#626]
Missing brands for this integration.

https://rc.home-assistant.io/blog/2020/03/27/release-108/

Integration logos & icons
We have created a new repository on GitHub containing all the brand icons and logos Home Assistant is able to integrate with. These images are, for example, used in our documentation.

In 0.108, we made a start on using the content from this repository in the Home Assistant frontend. The device information page got a layout update and the integrations page as well.

These pages will now show the icons and logos matching the integration.

**Comment by alandtse** [comment]
Do you know if custom components can use the repository? There's already an official app we'd just take their logo from.

**Comment by sagitt** [comment]
> Do you know if custom components can use the repository? There's already an official app we'd just take their logo from.

I don’t know, but i think is a goog thing if every integration have an icon.

**Comment by alandtse** [comment]
Confirmed this isn't possible for custom components yet. Please reopen if it becomes available.
