### ISSUE TITLE
Two Amazon Accounts Breaks Media Player Functionality

### ISSUE THREAD

**Issue by SawKyrom** [custom-components/alexa_media_player#630]
**Describe the bug**
The Alexa Media Player custom components works fine for one Amazon account.  After adding my wife's Amazon account to the Integrations, all functionality of the media player breaks (tts and announce).   None of the previously functioning automations/scripts work.  Logs show activation of automation, but no announcement or tts occurs.  The devices (echo dots) are all silent.  No error logs.  Attempts at manual calls via Developer Tools Service function also results in no response/no error.  Nothing occurs.  Rebooting HA several times (x3) no change.  Developer Tools logs shows "Entity ID already exist" error on boot for every Amazon entity (see log below).  Deletion of second account integration restores function.  Accounts are linked in Amazon (same household).

**To Reproduce**
Steps to reproduce the behavior: (With working media player installed via HACS and Integrations...)
1. Go to 'Configuration'
2. Click on 'Integrations'
3. Select "=" add new integration
4. Select Alexa Media Player
5. Enter information
6. Reboot x3

**Expected behavior**
Previously working function prior to addition of second media player integration

**Screenshots**
![Screenshot (158)](https://user-images.githubusercontent.com/34008245/78594717-66ee7400-780e-11ea-98d1-51aa6ff36450.png)

**System details**
 - Home-assistant (version): 107.7
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug). YES
 - alexa_media  (version from `const.py` or HA startup): v2.5.11
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

2020-04-06 13:19:26 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 425, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: switch.kitchen_echo_dot_repeat_switch. Platform alexa_media does not generate unique IDs
**Additional context**

**Comment by alandtse** [comment]
Are the echo devices under both accounts?

**Comment by SawKyrom** [comment]
All of the echo devices are capable of switching accounts.  Amazon allows multiple accounts per household under one plan (Two adults and up to 4 children I believe.)  Each account has it's own email address to allow for customization of media and orders.  In the echo environment, you can tell Alexa to switch accounts, to which she will reply, "now in FILL_IN_THE_BLANK account".  

It may not be so much as a media player component issue, but rather a Alexa Home Assistant interface issue since I can only get one Alexa account (i.e. mine) to control devices.  However, when I do attempt to add my wife's account in the Media Player Integration, the functionality breaks.  It does not like having two separate media player accounts on the same HA device.

I've discovered that the echo devices will announce/TTS regardless of which Alexa account is currently selected on the echo.  So, the issues is not without resolution.  However, it begs to question why adding an additional account would break the component?  Any thoughts?  Thank you for the integration and fielding my question.  Much appreciated!

**Comment by alandtse** [comment]
Would need the `alexapy` logs to understand what is happening. What is possibly happening is the component uses the serial number as a unique key. When there's a collision from two identical accounts, it'll potentially overwrite the existing reference to a media player which then fails to load because HA also thinks it's already loaded: `Entity id already exists`. That way HA no longer has access to the echo device.

**Comment by AtomicLaser** [comment]
I too have this issue, two Alexa accounts being used in the house, if one account is assigned to a notification,  it sends fine, but after adding in the devices for the other account, none of them will trigger.   I'll get a log posted when I figure how to do it :)

**Comment by alandtse** [comment]
Please note that I don't think HA even supports calling notify using different accounts so there's no way for the component to know who is calling it. Right now, it assumes the account that added a component is the one to use.

I'm not sure what you're trying to do by adding two accounts that share the same echo devices. The workaround is to use `include_device` or `exclude_device` so the individual devices are only loaded by the respective accounts.

**Comment by SawKyrom** [comment]
@alandtse Thanks for the reply and looking into this matter.  To answer you question:

> I'm not sure what you're trying to do by adding two accounts that share the same echo devices.

Amazon creates individual accounts (i.e. email) for each member of a household that use the same echo devices, versus every member needing to have their own unique/separate device.  The benefit of having HA respond to multiple accounts, is so that you do not lose functionality of the echo devices regardless of the household member account that is currently active.  You can easily switch the accounts locally with command "Alexa switch to FILL_IN_THE_BLANK account", but that becomes cumbersome having to force the device into a specific account every time you want to control a local device.   

Prior to HA, I was with SmartThings.  After a forced firmware update that bricked my device, I switched to open source home automation control of HA.  SmartThings was capable of controlling local lights/devices with Alexa regardless of the household account assigned as long as that account had activated the feature in the Alexa app.  It grouped all household accounts into one system and would implement the command.  I feel that there must be a way for HA to have this same functionality, however I personally lack the understanding on how to implement this task.  I was hoping that you or someone on the development team would know.

Also, the HA Alexa Media github page:  https://github.com/custom-components/alexa_media_player/wiki/Configuration
seems to imply that multiple accounts can be utilized.  

`Multiple accounts can be added:

alexa_media:
  accounts:
    - email: your amazon email
      password: your amazon password
      url: amazon.com
    - email: your second email
      password: your amazon password
      url: amazon.com`

I just can't get it to work.  Thanks again for your feedback.

**Comment by alandtse** [comment]
If you have two accounts with the same exact devices, you only need to add one account. There is no benefit to adding both accounts because HA and this component does not allow per account control of devices yet. We allow multiple accounts because people have devices that only exist in each account. Any overlap has to be properly excluded to avoid this issue.

If you have a specific use case you can't do, then we may see about adding it. But you may have to make sure HA supports it first.

**Comment by SawKyrom** [comment]
@alandtse Thanks for the reply and the explanation!  In summary, 

> HA and this component does not allow per account control of devices yet.

and this is the limiting factor for multiple account control.  I do have specific use cases, as does @AtomicLaser and any other two or more adult family that utilizes the Amazon Alexa environment.  If you need any logs or beta testers for this application, please notify me.  I would really like to help.  Again, thank you for your assistance!  Cheers.

**Comment by AtomicLaser** [comment]
To be fair, this HAS worked in the past - Two different amazon accounts are assigned to Home Assistant and TTS/Notifications has worked from HA to both amazon accounts.

Something has changed recently which has stopped this from working as expected.

**Comment by SheriffOfNotts** [comment]
I am also having a similar issue - TTS to devices on my account work fine. If I then include a device registered to another account there is no error, the script is notified as run, but nothing happens..
