### ISSUE TITLE
[FR] Add "previous_alarm" sensor

### ISSUE THREAD

**Issue by chemelli74** [custom-components/alexa_media_player#637]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**
I would like to be able to use an action with a delay on the timer.
The idea is to be able to fire the action after 10 minutes from the "last_alarm".
Now that the refresh is fixed, is too quick and action doesn't work any more. 

**Describe the solution you'd like**
Introduce a new sensor that stores latest value to be used in such use case.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by alandtse** [comment]
Can't you just set the second action before the timer goes off? The component can only do so much for you.

**Comment by chemelli74** [comment]
You mean fire the action as soon as the alarm is current time and then add somehow a wait 10 minutes  ?
Or if you have another idea, please share it.
Thank you in advance,

Simone

**Comment by alandtse** [comment]
Yes, since you're scripting an action, you can also script an action that will fire after a delay.

**Comment by chemelli74** [comment]
Can you be so kind to show an automation code where the action starts with a delay ? Seems I cannot find a way to do.
I was able to insert a delay between you service but not start with it.

Simone

**Comment by chemelli74** [comment]
No idea ?

Then this FR makes sense 😉

Simone

**Comment by chemelli74** [comment]
@alandtse, so how should I proceed from the automation point of view ?

Simone

**Comment by chemelli74** [comment]
Can you consider adding the requested sensor ?
Unfortunately No other way to get a solution :-(

Simone

**Comment by chemelli74** [comment]
I finally got the time to test and unfortunately it doesn't work for me. Please let me know if I'm doing something wrong.

What I did ?

- I asked Alexa to set a timer for today at 14:00.
- Alarm fired.
- I asked Alexa to cancel the alarm in order to stop getting the notification sound.
- I opened HA and checked the "" that was null.

Evidence from HA:

![image](https://user-images.githubusercontent.com/57354320/82730359-36e82b00-9cff-11ea-905f-7521d47fde80.png)
 
Info from https://alexa.amazon.it/api/notifications:

`[{"alarmTime":0,"automationId":null,"createdDate":1590234497602,"deferredAtTime":null,"deliveryType":null,"deviceName":null,"deviceSerialNumber":"xxxxxx","deviceType":"A1RABVCI4QCIKC","extensibleAttribute":null,"geoLocationTriggerData":null,"id":"A1RABVCI4QCIKC-xxxxxxxx-3e9bb581-51a6-4a22-9687-41135c77ffa1","lastOccurrenceTimeInMilli":0,"lastUpdatedDate":0,"musicAlarmId":null,"musicEntity":null,"notificationIndex":"3e9bb581-51a6-4a22-9687-41135c77ffa1","originalDate":"2020-05-23","originalTime":"14:00:00.000","personProfile":null,"provider":null,"rRuleData":null,"recurrenceEligibility":false,"recurringPattern":null,"remainingTime":0,"reminderAppLabel":null,"reminderLabel":null,"reminderSubLabel":null,"skillInfo":null,"snoozedToTime":null,"sound":{"displayName":"Simple Alarm","folder":null,"id":"system_alerts_melodic_01","providerId":"ECHO","sampleUrl":"https://s3.amazonaws.com/deeappservice.prod.notificationtones/system_alerts_melodic_01.mp3"},"status":"OFF","targetPersonProfiles":null,"timeZoneId":null,"timerLabel":null,"tmwNotificationProperties":null,"triggerTime":0,"type":"Alarm","version":"4"}`

Simone

**Comment by alandtse** [comment]
Canceling Alarms can cause issues because it makes multiple changes to the Alarm that we can't filter. If you tell it to stop the alarm, does it cause the same issue?

**Comment by chemelli74** [comment]
Unfortunately with stop the behavior is the same. In the mean time I also updated to v2.8.1 but no change:

![image](https://user-images.githubusercontent.com/57354320/82754588-133fe600-9dce-11ea-95d1-23afdf6aebdc.png)

Simone

**Comment by chemelli74** [comment]
Hi, may I help debugging somehow ?

Simone

**Comment by chemelli74** [comment]
I quickly looked at the code and found something at line 168 of **sensor.py**:

`self._prior_value = self._next if self._active else None`

I think "prior_value" should be set to "next_alarm" value exactly when next_alarm fires.
That way I have in that variable the value of the previous alarm as long as a new one fires up.

What you think ?

Simone

**Comment by alandtse** [comment]
You're welcome to edit the code and test it. We don't know when the alarm fires as Amazon does not provide an event. It provides a change event through websocket but it can trigger 2-3x around the time an alarm should fire. If you can figure out how to tell if it's a cancelled alarm or an actually triggered alarm, then we would gladly accept a PR.

**Comment by chemelli74** [comment]
I'm trying to understand what are the possibilities,  so I may be completely wrong.

What you think about this rest api https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/avs-rest-alarms.html ?

Simone

**Comment by chemelli74** [comment]
Today I did an interesting finding: prior value for the first time was not none and the automation worked :-)

Thinking of what changed, I remembered that I deleted all non active alarms from my Alexa app.
So now I only have 1 recurring alarm for workdays.

Something that can help debugging ?
Let me know if and how I can help.

Simone

**Comment by chemelli74** [comment]
Two days in a row that it works 👍 

Simone

**Comment by chemelli74** [comment]
Final solution was to create a **binary_sensor** with the "**delay_off:**" of 15 minutes.

I think that, if there are no other use cases, you can remove this feature.

Thank you so much for your support.

Simone
