### ISSUE TITLE
Can't seem to install the add-on

### ISSUE THREAD

**Issue by gamilevin** [custom-components/alexa_media_player#645]
(This is the first time I'm reporting an issue and a 2 days user to HA so please bear with me)
Can't seem to be able to configure the integration and login properly.

**To Reproduce**
1. I've updated to the latest version 
2. I've added debug: True after my credentials in configuration.yaml
3. I've restarted HASS.IO twice
4. I go to 'notifications' and start UI configuration of the add-on
5. I get a pop-up with Captcha challenge
6. I re-enter my Amazon's password and enter the captcha and click submit
7. I get to the Alexa Media Player - Verification Method enter 'sms' and submit
8. I get a weird empty pop up and then I'm stuck

**Expected behavior**
I was expected for the login to work

**Screenshots**
![AMP1](https://user-images.githubusercontent.com/63460575/79050660-453d2480-7c34-11ea-822c-ec33b840be59.png)
![AMP2](https://user-images.githubusercontent.com/63460575/79050669-538b4080-7c34-11ea-8019-ee50a9ee48c5.png)

**System details**
 - Home-assistant 0.108.2
 - Hassio Yes
 - alexa_media  2.5.13
 - alexapy - sorry, I couldn't understand that, in HACS I also see it as 2.5.13

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**
I've managed to get to the configuration screen when I entered '0' or '1' in the verification screen but just got the captcha again and couldn't complete the process.

I didn't manage to get any OPT messages ((email nor SMS).

Thanks!! :)

**Comment by alandtse** [comment]
See work arounds in #568.  You may have to delete  Ami's 5th Android Device to get past this at this point or setup 2FA on your app.

**Comment by alandtse** [comment]
Oh and welcome to HA and the component.

**Comment by gamilevin** [comment]
Thank you so much Alan for the quick response and the warm welcome!! :)

What do you mean by  'delete Ami's 5th Android Device'?
Delete it from where? How can I do it?

I don't even understand what device is it referring? 
could it be the Alexa app installed on my android smartphone?

Since I live in Israel I think I had to do a workaround in order to install Alex (maybe I downloaded an APK file. can't really remember)

**Comment by alandtse** [comment]
It's described in the thread I linked. You can delete it from the website but again check the thread.

**Comment by gamilevin** [comment]
Thank you so much Alan.
I've managed to do it with the 2FA.

What will happen if I now disable 2FA from amazon website. Will the add-on continue to work?

**Comment by alandtse** [comment]
Yes. It may ask you again to relog in after a couple of months.

**Comment by gamilevin** [comment]
Thanks Alan.
Since I had one echo dot which I gave as a gift registered on me I had to remove the add-on and re-install it. Now I have relevant only devices (I think).

The thing is that they look like this:
![AMP3](https://user-images.githubusercontent.com/63460575/79053536-d74e2880-7c46-11ea-9989-fbfc3be13717.png)
Is it OK? did I've managed to break it?

**Comment by alandtse** [comment]
No it's fine. Those will become available if relevant information is available.
