### ISSUE TITLE
Apple Music, loop instead of repeat

### ISSUE THREAD

**Issue by Apple2T4ch** [custom-components/alexa_media_player#649]
**Is your feature request related to a problem? Please describe.**
Repeat switch doesn't work for Apple Music.

**Describe the solution you'd like**
Create a service to call to loop music instead of repeat.

**Describe alternatives you've considered**
I've tried calling a service alexa.play_media, didn't work.

**Additional context**
Link I found on Amazons Developer website : https://developer.amazon.com/en-GB/docs/alexa/music-skills/api-setloop.html

**Comment by alandtse** [comment]
We can't use the Amazon music-skills API. Does it work in the Amazon Alexa webapp?

**Comment by Apple2T4ch** [comment]
Tried too, unfortunately no.

**Comment by alandtse** [comment]
If it doesn't work in the Webapp, we can't do it in this component. I'll close this for now but if it ever works there, then we can try to add it.
