### ISSUE TITLE
Alexa Online Status is not being updated

### ISSUE THREAD

**Issue by Sajivve** [custom-components/alexa_media_player#650]
Hi

I have Alexa Media OPlayer Installed.

However, the Online Status in Home Assistant is not being updated.

Despite the fact that my Echo Speaker Shows OFFLINE on Alexa Website it shows Available in Home Assistant.

Please advise a solution.

Regards
Sajive

media_player.sajive_s_echo_speaker | standby | is_volume_muted: false media_content_type: standby media_position_updated_at: 2020-04-19T10:01:34.259485+00:00 available: true last_called: null last_called_timestamp: null friendly_name: Echo supported_features: 56253
-- | -- | --

**Comment by alandtse** [comment]
Fill out the template.

**Comment by Sajivve** [comment]
Which template are you referring to? Can you please point me in the direction?

**Comment by alandtse** [comment]
The template for bug reports.

**Comment by alandtse** [comment]
Closing as stale. Please reopen when ready to provide info.
