### ISSUE TITLE
Missing DND on new Echo Flex devices

### ISSUE THREAD

**Issue by photinus** [custom-components/alexa_media_player#657]
**Describe the bug**
After adding two new Echo Flex devices to my account, there are no switches created for the devices

**To Reproduce**
1. Add Echo Flex to amazon account
2. Restart HA

**Expected behavior**
Echo Flex added to the device list with typical switches (dnd, shuffle, etc...)

**System details**
 - Home-assistant (version): 0.108.5
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): 2.5.14
 - alexapy (version from `pip show alexapy` or HA startup): 1.6.0

**Logs**
Log Snippit:
Error while setting up alexa_media platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/alexa_media/switch.py", line 117, in async_setup_entry
    hass, config_entry.data, async_add_devices, discovery_info=None
  File "/config/custom_components/alexa_media/switch.py", line 65, in async_setup_platform
    and not account_dict["devices"]["switch"][key].get("dnd")
KeyError: 'CC3A61BEC54A'

**Comment by alandtse** [comment]
Thanks. Go ahead and delete the logs from pastebin. I've downloaded them. Can you please get me the json info from your [device page (fix domain)](https://alexa.amazon.com/api/devices-v2/device) with the Key `CC3A61BEC54A`?

**Comment by photinus** [comment]
https://pastebin.com/hrb9yQq6

Posted the logs as guest apparently so I cant delete them, but not too woried about it, think I got all the juicy details out of them. The devices page there should be unlisted and expires

**Comment by alandtse** [comment]
Thanks. The key is for an app. I've posted a potential fix for what your logs reported, but it may not be a complete fix. Can you try it?

**Comment by Krocko** [comment]
@alandtse I have also problems with the dnd switch on echo dots gen2
```
Logger: homeassistant.components.switch
Source: custom_components/alexa_media/switch.py:65 
Integration: Schalter (documentation, issues) 
First occurred: 13:12:26 (1 occurrences) 
Last logged: 13:12:26

Error while setting up alexa_media platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/alexa_media/switch.py", line 117, in async_setup_entry
    hass, config_entry.data, async_add_devices, discovery_info=None
  File "/config/custom_components/alexa_media/switch.py", line 65, in async_setup_platform
    and not account_dict["devices"]["switch"][key].get("dnd")
KeyError: 'Alcatrazxxxxxxxxxxxxxx'
```

**Comment by photinus** [comment]
I have it installed via HACS, switched to the dev branch and the error persists. Do I need to do a manual install to test the fix?

**Comment by photinus** [comment]
Disregard my previous comment, pulled the switch.py file out of the pull and dropped it into my install. Seems to be working fine. All the other switches created successfully and no longer getting an error.

**Comment by Krocko** [comment]
I can confirm, this commit is solving the problem.

**Comment by alandtse** [comment]
Thanks for confirming and helping to track down this bug. Fix will be in the next release.
