### ISSUE TITLE
Shuffle only works using the switch-gui - not by code

### ISSUE THREAD

**Issue by me1337me** [custom-components/alexa_media_player#667]
**Describe the bug**
I use node-red and set up a call service to let my echo dot play a playlist.
Then I wanted to have it shuffle. Therefore I set up another call service node as follows:

![grafik](https://user-images.githubusercontent.com/63295847/80572325-5f318200-89fe-11ea-95df-61256f717f63.png)

That didnt work, neither before or after the play_media node.

I also tried to use the switch, before and after the play_media. I tried toggle, turn_on and a combination of first turn_off then turn_on
![grafik](https://user-images.githubusercontent.com/63295847/80572473-a1f35a00-89fe-11ea-87b5-052d23c337d3.png)

None of these worked ;(

But when I go to devices in Hass.io, select the switch and toggle it, shuffle is true (checked in "states")

What am I doing wrong?

**System details**
 - Home-assistant (version): 0.108.9
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): 2.5.15
 - alexapy (version from `pip show alexapy` or HA startup): ???

**Comment by alandtse** [comment]
The shuffle switch is only active when the media player allows it. Are you using the node_red  when it is in fact available? Does it work in the dev tools services tab?

**Comment by me1337me** [comment]
Someone from HA forum told me how to solve it. I had to add "shuffle" to the command string to play the playlist:
{"media_content_id":"**shuffle** playlist nu metal and rock songs","media_content_type":"AMAZON_MUSIC"}

**Comment by alandtse** [comment]
Closing as solved.
