### ISSUE TITLE
Pickle file in root

### ISSUE THREAD

**Issue by larena1** [custom-components/alexa_media_player#670]
The pickle file should be moved to the storage directory. It's a file not meant be be human-readable or human-editable and thus should not pollute the root of the HA config directory. 

That's what the storage directory was introduced for last year.

**Comment by alandtse** [comment]
Ok, this will be in the next release.

**Comment by larena1** [comment]
Is pickle really needed after all? It can be slower than json and json fits better with the overall approach of home assistant. And it's just a cookie so nothing complicated.
