### ISSUE TITLE
2.6.0 throws  AttributeError: 'AlexaNotificationService' object has no attribute 'email' errors

### ISSUE THREAD

**Issue by stalakerob** [custom-components/alexa_media_player#674]
**Describe the bug**
V 2.6.0 throws  AttributeError: 'AlexaNotificationService' object has no attribute 'email' errors
This did not happen with the previous version

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details**
 - Home-assistant (version): 0.109.2
 - Hassio (Yes/No): No (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup): 2.6.0
 - alexapy (version from `pip show alexapy` or HA startup): 1.7.1 

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.
`May 02 10:46:13 raspi4 hass[4108]: 2020-05-02 10:46:13 ERROR (MainThread) [homeassistant.components.script] Alexa says or announces message: Error executing script. Unexpected error for call_service at pos 1: 'AlexaNotificationService' object has no attribute 'email'
May 02 10:46:13 raspi4 hass[4108]: Traceback (most recent call last):
May 02 10:46:13 raspi4 hass[4108]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/script.py", line 153, in _async_step
May 02 10:46:13 raspi4 hass[4108]:     self, f"_async_{cv.determine_script_action(self._action)}_step"
May 02 10:46:13 raspi4 hass[4108]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/script.py", line 623, in _async_call_service_step
May 02 10:46:13 raspi4 hass[4108]:     *self._prep_call_service_step(), blocking=True, context=self._context
May 02 10:46:13 raspi4 hass[4108]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1247, in async_call
May 02 10:46:13 raspi4 hass[4108]:     task.result()
May 02 10:46:13 raspi4 hass[4108]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1282, in _execute_service
May 02 10:46:13 raspi4 hass[4108]:     await handler.func(service_call)
May 02 10:46:13 raspi4 hass[4108]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/notify/__init__.py", line 119, in async_notify_message
May 02 10:46:13 raspi4 hass[4108]:     await notify_service.async_send_message(**kwargs)
May 02 10:46:13 raspi4 hass[4108]:   File "/home/homeassistant/.homeassistant/custom_components/alexa_media/notify.py", line 181, in async_send_message
May 02 10:46:13 raspi4 hass[4108]:     self.email
`

**Additional context**

**Comment by alandtse** [comment]
Oops. Sorry. Should have a fix.
