### ISSUE TITLE
V2.6.1: first call to notify.alexa_media returns "Too many requests" error

### ISSUE THREAD

**Issue by stalakerob** [custom-components/alexa_media_player#678]
**Describe the bug**
The first time the notification service is used results in a "Too many requests" error.
Calling this service again throws no error.

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details**
 - Home-assistant (version): 0.109.2
 - Hassio (Yes/No): No (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup): 2.6.1
 - alexapy (version from `pip show alexapy` or HA startup): 1.7.1

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by stalakerob** [comment]
Forgot the logs:
`May 02 13:45:59 raspi4 hass[18395]: 2020-05-02 13:45:59 ERROR (MainThread) [homeassistant.components.script] Alexa says or announces message: Error executing script. Unexpected error for call_service at pos 1: Too Many Requests
May 02 13:45:59 raspi4 hass[18395]: Traceback (most recent call last):
May 02 13:45:59 raspi4 hass[18395]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/script.py", line 153, in _async_step
May 02 13:45:59 raspi4 hass[18395]:     self, f"_async_{cv.determine_script_action(self._action)}_step"
May 02 13:45:59 raspi4 hass[18395]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/script.py", line 623, in _async_call_service_step
May 02 13:45:59 raspi4 hass[18395]:     *self._prep_call_service_step(), blocking=True, context=self._context
May 02 13:45:59 raspi4 hass[18395]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1247, in async_call
May 02 13:45:59 raspi4 hass[18395]:     task.result()
May 02 13:45:59 raspi4 hass[18395]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1282, in _execute_service
May 02 13:45:59 raspi4 hass[18395]:     await handler.func(service_call)
May 02 13:45:59 raspi4 hass[18395]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/notify/__init__.py", line 119, in async_notify_message
May 02 13:45:59 raspi4 hass[18395]:     await notify_service.async_send_message(**kwargs)
May 02 13:45:59 raspi4 hass[18395]:   File "/home/homeassistant/.homeassistant/custom_components/alexa_media/notify.py", line 229, in async_send_message
May 02 13:45:59 raspi4 hass[18395]:     await asyncio.gather(*tasks)
May 02 13:45:59 raspi4 hass[18395]:   File "/home/homeassistant/.homeassistant/custom_components/alexa_media/helpers.py", line 148, in wrapper
May 02 13:45:59 raspi4 hass[18395]:     result = await func(*args, **kwargs)
May 02 13:45:59 raspi4 hass[18395]:   File "/home/homeassistant/.homeassistant/custom_components/alexa_media/media_player.py", line 1053, in async_send_tts
May 02 13:45:59 raspi4 hass[18395]:     await self.alexa_api.send_tts(message, customer_id=self._customer_id, **kwargs)
May 02 13:45:59 raspi4 hass[18395]:   File "/srv/homeassistant/lib/python3.7/site-packages/alexapy/alexaapi.py", line 490, in send_tts
May 02 13:45:59 raspi4 hass[18395]:     queue_delay=queue_delay,
May 02 13:45:59 raspi4 hass[18395]:   File "/srv/homeassistant/lib/python3.7/site-packages/alexapy/alexaapi.py", line 302, in send_sequence
May 02 13:45:59 raspi4 hass[18395]:     await self.run_behavior(node_data, queue_delay=queue_delay)
May 02 13:45:59 raspi4 hass[18395]:   File "/srv/homeassistant/lib/python3.7/site-packages/alexapy/alexaapi.py", line 247, in run_behavior
May 02 13:45:59 raspi4 hass[18395]:     await self._post_request("/api/behaviors/preview", data=data)
May 02 13:45:59 raspi4 hass[18395]:   File "/srv/homeassistant/lib/python3.7/site-packages/alexapy/alexaapi.py", line 118, in _post_request
May 02 13:45:59 raspi4 hass[18395]:     return await self._request("post", uri, data)
May 02 13:45:59 raspi4 hass[18395]:   File "/srv/homeassistant/lib/python3.7/site-packages/alexapy/alexaapi.py", line 111, in _request
May 02 13:45:59 raspi4 hass[18395]:     raise AlexapyTooManyRequestsError(response.reason)
May 02 13:45:59 raspi4 hass[18395]: alexapy.errors.AlexapyTooManyRequestsError: Too Many Requests
M`

**Comment by stalakerob** [comment]
In the meantime I figured out that this error occurs when waiting for some time (probably > 1 min) and then calling the service. Calling it again right after the error throws no error (strange). Then waiting for a while and calling again throws the error. Seems that there is something happening that is time dependant.

**Comment by alandtse** [comment]
This is an Amazon issue unfortunately. All you can do is wait and try again.

**Comment by stalakerob** [comment]
In the meantime I observed that increasing the queue delay option to 3 secs reduces the number of errors significantly. I'm confused because my expectation was that this is only used to avoid multiple successive calls at a high call rate. But I don't have this. I only have a single notify call and then quite some time (many secs) before the next one. Does this makes sense?

BTW: I dont't  want to sound negative. Actually, THANK YOU very much for your efforts to make this component available. Really appreciated!

**Comment by alandtse** [comment]
It queues multiple potential calls to the API if they are queueable. There are multiple api calls particularly when starting up. Also, we can't control what else might be hitting Amazon for your account like for each echo/apps.

One way to check is to log the alexapy logs. It will show you each request it makes and you can see how many you hit the API with at a time.

**Comment by stalakerob** [comment]
I realized that alexa_media finds 9 devices. Turning on the logs I see that there a many "Testing item xxx against entity yyy" messages for a single TTS call. Are those sent to amazon? If yes, I can imagine that this is an issue. Is there way to hide devices that I don't want to use with alexa_media?

**Comment by alandtse** [comment]
No, that's local only.

**Comment by stalakerob** [comment]
Thanks. Just to let know that the problems are pretty much gone. Maybe it was because I did a lot of home assistant restarts the last couple of days.

**Comment by alandtse** [comment]
Ok, I'm going to close this out. Please open a new issue if you see anything else.
