### ISSUE TITLE
Uninstalling gives errors

### ISSUE THREAD

**Issue by danlun** [custom-components/alexa_media_player#681]
**Describe the bug**
When uninstalling the integration (stoped using Echo) i get a configuration error after restart (see screenshot. Is there anything else I need to remove or is this a bug?

**To Reproduce**
1. Go to HACS 
2. Click on 'Uninstall´
3. Restart

**Expected behavior**
No error message after restart

**Screenshots**
![InkedSkärmklipp 2020-05-03 17 11 21_LI](https://user-images.githubusercontent.com/50021823/80919512-3395fb00-8d62-11ea-9523-776dad6fa29b.jpg)
![InkedSkärmklipp 2020-05-03 17 16 14_LI](https://user-images.githubusercontent.com/50021823/80919518-3e509000-8d62-11ea-811f-78f1e39194cd.jpg)

**System details**
 - Home-assistant (version): 109.3
 - Hassio (Yes/No): YES
 - alexa_media  (version from `const.py` or HA startup): latest
 - alexapy (version from `pip show alexapy` or HA startup): ?

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by alandtse** [comment]
You also have to remove it from HA. HACS does not actually do anything other than deleting the files. You may have to delete it from your configuration.yaml or delete from the integrations page. If it's on your integrations page, the files must be available or it can't uninstall itself.

**Comment by danlun** [comment]
Ahh, that wasnt clear for me at all. So the order I do this is of importance. Have missed that in all I have been reading around HA, sorry. My solution was to reinstall via HACS, delete integration and the uninstall via HACS. 
I assume it works like this for all HACS install. lesson learned, not 100% user friendly but that is of course not your fault, system implementation.  
Thanks for the help. I close the case.
