### ISSUE TITLE
Possible rootkit: zaRwT.KiT - network TCP port 60922

### ISSUE THREAD

**Issue by zibous** [custom-components/alexa_media_player#684]
**Describe the bug**

**To Reproduce**

**Expected behavior**
```txt
Warning: Network TCP port 60922 is being used by /usr/bin/python3.7. Possible rootkit: zaRwT.KiT
         Use the 'lsof -i' or 'netstat -an' command to check this.
```
**Screenshots**

**System details**
 - Home-assistant (version): 
Home Assistant 0.109.4
Frontend-Version: 20200427.2 - latest
```txt
arch | x86_64
-- | --
dev | false
docker | false
hassio | false
os_name | Linux
os_version | 5.3.0-51-generic
python_version | 3.7.5
timezone | Europe/Vaduz
version | 0.109.4
virtualenv | true

```
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest 
version of alexapy after an update. This looks like a HA bug).
NO
 - alexa_media  (version from `const.py` or HA startup):
Installed: v2.6.1
 - alexapy (version from `pip show alexapy` or HA startup):
```txt
Name: alexapy
Version: 1.7.1
Summary: Python API to control Amazon Echo Devices Programatically.
Home-page: https://gitlab.com/keatontaylor/alexapy
Author: Keaton Taylor
Author-email: keatonstaylor@gmail.com
License: Apache-2.0
Location: /srv/homeassistant/lib/python3.7/site-packages
Requires: simplejson, requests, yarl, aiofiles, bs4, certifi, aiohttp, backoff
Required-by:
```
**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**
```txt
hass      10997   homeassistant   29u  IPv4 10512362      0t0  TCP hass.home:60922->205.251.243.55:https (ESTABLISHED)

whois 205.251.243.55

#
# ARIN WHOIS data and services are subject to the Terms of Use
# available at: https://www.arin.net/resources/registry/whois/tou/
#
# If you see inaccuracies in the results, please report at
# https://www.arin.net/resources/registry/whois/inaccuracy_reporting/
#
# Copyright 1997-2020, American Registry for Internet Numbers, Ltd.
#


NetRange:       205.251.192.0 - 205.251.255.255
CIDR:           205.251.192.0/18
NetName:        AMAZON-05
NetHandle:      NET-205-251-192-0-1
Parent:         NET205 (NET-205-0-0-0-0)
NetType:        Direct Allocation
OriginAS:       AS16509, AS39111, AS7224
Organization:   Amazon.com, Inc. (AMAZON-4)
RegDate:        2010-08-27
Updated:        2015-09-24
Ref:            https://rdap.arin.net/registry/ip/205.251.192.0

OrgName:        Amazon.com, Inc.
OrgId:          AMAZON-4
Address:        1918 8th Ave
City:           SEATTLE
StateProv:      WA
PostalCode:     98101-1244
Country:        US
RegDate:        1995-01-23
Updated:        2020-03-31
Ref:            https://rdap.arin.net/registry/entity/AMAZON-4

```
I have received this message since the update to Home Assistant 0.109.4 and the latest version of Alexa Media Player. This message did not come before.

**Comment by alandtse** [comment]
You'll need to work with HA to figure this out. This component does not open any ports.

**Comment by alandtse** [comment]
Looking at it closer, there isn't an open port. Your warning is saying some python client is using 60922 to connect to amazon.com which some random rootkit happens to use.  You need to do your own investigation to figure out whether it is actually a rootkit. Try restarting HA, or rebooting or something.

**Comment by zibous** [comment]
@alandtse 
Thanks for the review. I stopped the home assistant and installed the new version 0.109.5. After the restart, port 60922 to amazon.com was no longer opened.
Hope it was fixed with the new version, but will continue to watch it.
