### ISSUE TITLE
Trigger entity

### ISSUE THREAD

**Issue by Gt1ult** [custom-components/alexa_media_player#685]
Dear All,

Please might you explain me how to trigger an entity. I would like to trigger a switch with alexa. Is it possible?

Thank you!

**Comment by alandtse** [comment]
Please review the forum or wiki.

**Comment by Gt1ult** [comment]
Thank you for the answer. I think I have reviewed it. I have seen the wiki as you suggested nut I was not able to find the solution. What I would like to do is ask to alexa to trigger an entity, i.e. "Alexa, ask to hassio to turn on the light". Is it possible? Thank you in advance.
