### ISSUE TITLE
TTS stopped working on Sonos as initiated by routines

### ISSUE THREAD

**Issue by Molodax** [custom-components/alexa_media_player#687]
**Describe the bug**
TTS stopped working on Sonos. It worked flawlessly for a year or more prior to version 2.6.x or till May. 
There is nothing remarkable in the component log, no errors, however, I've noticed that in the Alexa history,  TTS previously was initiated via "simon says [message]", however, now it is "activity initiated by routines [message]". It has always been the case though that Alexa routines have not been supported on Sonos for some odd reason. So it seems like a culprit.

**To Reproduce**
1. Alexa enabled Sonos
2. Use this or similar script

```
    - service: notify.alexa_media
      data_template:
        target: >-
          {% if where == 'last' %}
            {{ states('sensor.last_alexa') }}
          {% else %}
            {{ 'media_player.' ~ where }}
          {% endif %}
        message: "{{ what }}"
        data:
          type: tts
```
**Expected behavior**
TTS functionality became vital and worked perfectly, so it would be so important to fix it if possible.

**Screenshots**

**System details**
 - Home-assistant (version): 0.109.x
 - Hassio (Yes/No): Yes.
 - alexa_media  (version from `const.py` or HA startup): 2.6.1
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
```
2020-05-06 18:37:30 DEBUG (MainThread) [alexapy.alexaapi] Creating sequence for 1 items
2020-05-06 18:37:30 DEBUG (MainThread) [alexapy.alexaapi] Running behavior with data: {"behaviorId": "PREVIEW", "sequenceJson": "{\"@type\": \"com.amazon.alexa.behaviors.model.Sequence\", \"startNode\": {\"@type\": \"com.amazon.alexa.behaviors.model.SerialNode\", \"nodesToExecute\": [{\"@type\": \"com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode\", \"type\": \"Alexa.Speak\", \"operationPayload\": {\"deviceType\": \"A2OSP3UA4VC85F\", \"deviceSerialNumber\": \"23e1fc4eb42233a29ba209aabc3da382\", \"locale\": \"en-gb\", \"customerId\": \"A25OGU4IGOF9UU\", \"textToSpeak\": \"As for the weather for the day, it can be degreeslear throughout the day. The current air temperature feels like 12point1 degrees, water temperature in the sea is 10point5 degrees. In the next couple of days we can expect No precipitation throughout the week.\", \"target\": {\"customerId\": \"A25OGU4IGOF9UU\", \"devices\": [{\"deviceSerialNumber\": \"23e1fc4eb42233a29ba209aabc3da382\", \"deviceTypeId\": \"A2OSP3UA4VC85F\"}]}, \"skillId\": \"amzn1.ask.1p.saysomething\"}}]}}", "status": "ENABLED"}
2020-05-06 18:37:30 DEBUG (MainThread) [alexapy.alexaapi] POST: https://alexa.amazon.co.uk/api/behaviors/preview returned 200:OK:application/octet-stream
2020-05-06 18:37:31 DEBUG (MainThread) [alexapy.alexawebsocket] Received WebSocket: MSG 0x00000362 0x0dea5dce f 0x00000001 0x1469abf7 0x00000237 GWM MSG 0x0000b479 0x0000005c urn:tcomm-endpoint:service:serviceName:DeeWebsiteMessagingService:domain:prod:realm:USAmazon 0x00000081 urn:tcomm-endpoint:device:customerId:A25OGU4IGOF9UU:deviceType:ALEGCNGL9K0HM:deviceSerialNumber:260-4509644-0286745-1588671329000 {"payload":"{\"destinationUserId\":\"A25OGU4IGOF9UU\",\"timestamp\":1588783051408,\"key\":{\"registeredUserId\":\"A25OGU4IGOF9UU\",\"entryId\":\"1588783051389#A2OSP3UA4VC85F#23e1fc4eb42233a29ba209aabc3da382\"}}","command":"PUSH_ACTIVITY"}FABE
2020-05-06 18:37:31 DEBUG (MainThread) [alexapy.alexawebsocket] Received Standard MSG.
2020-05-06 18:37:31 DEBUG (MainThread) [custom_components.alexa_media] k*****j@l*****l: Received websocket command: PUSH_ACTIVITY : {'destinationUserId': 'A**********9UW', 'timestamp': 1588783051408, 'key': {'registeredUserId': 'A25OGU4IGOF9UU', 'entryId': '1588783051389#A2OSP3UA4VC85F#23e1fc4eb42233a29ba209aabc3da382'}}
2020-05-06 18:37:31 DEBUG (MainThread) [custom_components.alexa_media] k*****j@l*****l: Updated last_called: {'serialNumber': '2****************************381', 'timestamp': 1588783051408}
2020-05-06 18:37:31 DEBUG (MainThread) [custom_components.alexa_media] k*****j@l*****l: last_called changed: {'serialNumber': '2****************************381', 'timestamp': 1588782947307} to {'serialNumber': '2****************************381', 'timestamp': 1588783051408}
2020-05-06 18:37:31 DEBUG (MainThread) [custom_components.alexa_media.media_player] Kxx's 2nd Sonos One is last_called: 2****************************381
2020-05-06 18:37:31 DEBUG (MainThread) [custom_components.alexa_media.media_player] Room checking for potential state update due to push activity on 2****************************381
2020-05-06 18:37:33 DEBUG (MainThread) [custom_components.alexa_media.media_player] k*****j@l*****l: Refreshing Room
2020-05-06 18:37:33 DEBUG (MainThread) [custom_components.alexa_media.media_player] Room: Last_called check: self: 8****************************214 reported: 2****************************381
2020-05-06 18:37:34 DEBUG (MainThread) [alexapy.alexaapi] GET: https://alexa.amazon.co.uk/api/np/player?deviceSerialNumber=8cc56b7229d94393aee74b914c516214&deviceType=A15ERDAKK5HQQG&screenWidth=2560 returned 200:OK:application/json
```

**Additional context**
TTS works as before on another Alexa enabled device that supports Alexa routines.

**Comment by alandtse** [comment]
If you do it through an App routine does it work and does the history say the same thing? We haven't changed anything on this, so it may be a Sonos/Amazon change.

If the routine works, please follow this [guide](https://github.com/custom-components/alexa_media_player/wiki/Developers%3A-Sequence-Discovery) to get the info we need to fix it.

**Comment by alandtse** [comment]
I just realized you said it didn't work in the routines. Is there an app functionality that does this? We can only do what the app does unfortunately.

**Comment by 5and0** [comment]
TTS has randomly started working again for me on Sonos

**Comment by Molodax** [comment]
Indeed, it spontaneously started working again and the Alexa history shows it was initiated via "simon says [message]" again.
Though, there is change and no respect for periods or semicolons anymore, so sentences are monotonous and quick, difficult to get the sense. Interestingly, punctuation marks were present in the previous Alexa history, now the same sentences don't have them even the TTS message is the same.

**Comment by alandtse** [comment]
The lack of punctuation looks like a general issue. #724

**Comment by alandtse** [comment]
As this issue seems to have resolved, I'll close for now.

**Comment by Molodax** [comment]
It seems like the issue has recommenced.

**Comment by Molodax** [comment]
> As this issue seems to have resolved, I'll close for now.

It would be good to reopen it since it is the same again.

**Comment by alandtse** [comment]
I can reopen it, but I don't think there's anything we can do. It looks like an Amazon issue as we haven't changed any code.

**Comment by Molodax** [comment]
> I can reopen it, but I don't think there's anything we can do. It looks like an Amazon issue as we haven't changed any code.

Yeah, understand that it is not the component issue, it is mostly for others awareness.

**Comment by puttemanp** [comment]
TTS on Sonos has worked for me while I was testing it. Stopped working somewhere last week. 
Sonos is rolling out a new OS for their speakers as of today (Sonos S2). 
Culprit is probably a change on Sonos side.

**Comment by Molodax** [comment]
> TTS on Sonos has worked for me while I was testing it. Stopped working somewhere last week.
> Sonos is rolling out a new OS for their speakers as of today (Sonos S2).
> Culprit is probably a change on Sonos side.

I think it is just a guess whether Amazon or Sonos side. It stopped working in early May/end April than recovered for a few weeks. My Sonos have S2 OS from today but it doesn't solve the issue. So it is not obvious.

**Comment by baldus88** [comment]
Hi.
I have the same problem with my sonos beams.
I have HA Core installation 0.110.6
alexa media player v2.8.4
I have already installed the new OS for Sonos S2.

From few week the speaker via tts don't work but the echo dot is working fine.

We will waiting a good news for us.

Regards

**Comment by quagmired** [comment]
Just wanted to verify if it's the same problem I've encountered, as my Sonos One which was previously working via TTS doesn't work now, while the Echo Dots are still fine.

Thing is, there are no errors. The notify service call for the Sonos is actually processed normally, but nothing is actually played on the speaker. I've checked its volume and settings and they're all correct; I've not changed them.

Is this the same problem being discussed here?

(Also, it's the same whether I'm using TTS or Announce.. Plays fine on Echo Dots, nothing on Sonos One.)

**Comment by Molodax** [comment]
> May I verify if it's the same problem I've encountered, as my Sonos One which was previously working via TTS doesn't work now, while the Echo Dots are still fine.
> 
> Thing is, there are no errors. The notify service call for the Sonos is processed normally, but nothing is actually played on the speaker. I've checked its volume and settings and they're all correct; I've not changed them.
> 
> Also, it's the same whether I'm using TTS or Announce type - plays fine on Echo Dots, but nothing is heard on the Sonos One.
> 
> Is this the same problem being discussed here?
> 
> (I'm on Alexa Media Player v2.8.4, using Sonos S1 app as I've got some older speakers in my system.)

You are experiencing the same issue as discussed here. It exclusively relates to Sonos Alexa-enabled devices.

**Comment by quagmired** [comment]
> You are experiencing the same issue as discussed here. It exclusively relates to Sonos Alexa-enabled devices.

Thanks for confirming. I wasn't sure the notify service looked to have called normally.

I'll keep a close eye on this issue then, cheers!

**Comment by alandtse** [comment]
If someone gives me the alexapy logs for the tts call when it doesn't work for a Sonos I may be able to provide an error back. It just depends if Amazon's servers give any feedback. I'm really only looking for this one line where it works on my dots (and gives a HTTP 200).

```
 2020-06-14 03:26:49 DEBUG (MainThread) [alexapy.alexaapi] POST: https://alexa.amazon.com/api/behaviors/preview returned 200:OK:application/octet-stream
```

**Comment by jwelvaert** [comment]
This is what I get after trying TTS through my Sonos:
`2020-06-14 07:03:27 DEBUG (MainThread) [alexapy.alexaapi] GET: https://alexa.amazon.com/api/np/player?deviceSerialNumber=xxxxxxxxxxxxxxxxxxx&deviceType=A15ERDAKK5HQQG&screenWidth=2560 returned 200:OK:application/json`

**Comment by puttemanp** [comment]
One thing I have noticed since TTS stopped working is that Alexa audio routines are now failing as wel on Sonos devices 

I had created a routine in Alexa ap to close the blinds, Set the lights to a certain colour and play a playlist on Deezer.

Works on an echo dot. Sonos devices have always given a spoken error ‘audio routines are not currently supported on this device’ but it worked anyway.
Since TTS stopped working the routine now fails when started from a Sonos device.

P.

**Comment by mikesalz** [comment]
I don't know if this is related, but TTS stopped working on my Sonos Move.  But this is not initiated via a routine; Just via a standard HA automation.

```
    - service: notify.alexa_media
      data:
        target: media_player.sonos_move
        data:
          type: tts
        message: "Someone is at the front door.  Who could it be?"
```

**Comment by Molodax** [comment]
> I don't know if this is related, but TTS stopped working on my Sonos Move. But this is not initiated via a routine; Just via a standard HA automation.
> 
> ```
>     - service: notify.alexa_media
>       data:
>         target: media_player.sonos_move
>         data:
>           type: tts
>         message: "Someone is at the front door.  Who could it be?"
> ```

If you go to log of your Alexa account,  you'll find out that it is initiated via Alexa routine, however, Sonos doesn't support routines and, therefore,  it doesn't work.

**Comment by mikesalz** [comment]
Thanks @Molodax.  But strangely, it DID work about a week ago when I first set it up.  Has something changed?

**Comment by Molodax** [comment]
> Thanks @Molodax. But strangely, it DID work about a week ago when I first set it up. Has something changed?

It worked as stated above. Apparently, Sonos (likely) or Amazon has changed something.

**Comment by quagmired** [comment]
> If someone gives me the alexapy logs for the tts call when it doesn't work for a Sonos I may be able to provide an error back. It just depends if Amazon's servers give any feedback. I'm really only looking for this one line where it works on my dots (and gives a HTTP 200).
> 
> ```
>  2020-06-14 03:26:49 DEBUG (MainThread) [alexapy.alexaapi] POST: https://alexa.amazon.com/api/behaviors/preview returned 200:OK:application/octet-stream
> ```

This is what I got, which looks similar to yours and my Echo Dots too.

`2020-06-16 23:18:23 DEBUG (MainThread) [alexapy.alexaapi] POST: https://alexa.amazon.com/api/behaviors/preview returned 200:OK:application/octet-stream`

There's no error on the service call, but nothing actually plays on the Sonos.

**Comment by oneseventhree** [comment]
Such a shame if amazon removed this. It shows that the Sonus can in fact to voice commands.

**Comment by alandtse** [comment]
> There's no error on the service call, but nothing actually plays on the Sonos.

That's unfortunate. We won't be able to show any messaging then.

**Comment by quagmired** [comment]
Has this started working again for anyone else recently? My Sonos One seems to be playing TTS messages fine again since yesterday; I haven't changed anything in my config.

**Comment by oneseventhree** [comment]
> Has this started working again for anyone else recently? My Sonos One seems to be playing TTS messages fine again since yesterday; I haven't changed anything in my config.

you got me excited but no. I even just updated to Alexa Media Player v2.10.6 from v2.10.4 with no luck. Which version are you running?

Also I have a Sonus Beam which it used to work on

**Comment by quagmired** [comment]
I haven't updated in a long while, I'm still on v2.8.4.

I just always had a message I regularly played broadcast via TTS to two devices - an Echo Dot and a Sonos One. All these months it's just been playing on the former, but yesterday it began playing on both. No idea how that happened.

**Comment by Molodax** [comment]
It has been working for me for a week or so but it's not related to the component as I can see.

**Comment by oneseventhree** [comment]
> I haven't updated in a long while, I'm still on v2.8.4.
> 
> I just always had a message I regularly played broadcast via TTS to two devices - an Echo Dot and a Sonos One. All these months it's just been playing on the former, but yesterday it began playing on both. No idea how that happened.

I just tried to roll back and no luck. Must be a sonus BEAM thing

**Comment by jwelvaert** [comment]
> Has this started working again for anyone else recently? My Sonos One seems to be playing TTS messages fine again since yesterday; I haven't changed anything in my config.

Same here. Maybe Sonos changed something on their end?

**Comment by henripalmroth** [comment]
@quagmired are you using old or new app from Sonos? I think firmware is also updated on devices in case you migrate to new app. It would be good to understand which one you are running on.

**Comment by quagmired** [comment]
> @quagmired are you using old or new app from Sonos? I think firmware is also updated on devices in case you migrate to new app. It would be good to understand which one you are running on.

Was just about to bring that up too. I've got some older Sonos speakers in my system, so I'm still using the S1 app.

**Comment by jwelvaert** [comment]
> > @quagmired are you using old or new app from Sonos? I think firmware is also updated on devices in case you migrate to new app. It would be good to understand which one you are running on.
> 
> Was just about to bring that up too. I've still got some older Sonos speakers in my system, so I'm using the S1 app.

What's weird is that neither I nor @quagmired changed anything and ours both started working on the same day. I'm using the S1 app also (11.2.2 last updated a month ago), Alexa Media Player 2.10.6 and Home Assistant 0.114.4.

**Comment by oneseventhree** [comment]
> > > @quagmired are you using old or new app from Sonos? I think firmware is also updated on devices in case you migrate to new app. It would be good to understand which one you are running on.
> > 
> > 
> > Was just about to bring that up too. I've still got some older Sonos speakers in my system, so I'm using the S1 app.
> 
> What's weird is that neither I nor @quagmired changed anything and ours both started working on the same day. I'm using the S1 app also (11.2.2 last updated a month ago), Alexa Media Player 2.10.6 and Home Assistant 0.114.4.

What sonus product do you have that its work on now?

**Comment by jwelvaert** [comment]
> > > > @quagmired are you using old or new app from Sonos? I think firmware is also updated on devices in case you migrate to new app. It would be good to understand which one you are running on.
> > > 
> > > 
> > > Was just about to bring that up too. I've still got some older Sonos speakers in my system, so I'm using the S1 app.
> > 
> > 
> > What's weird is that neither I nor @quagmired changed anything and ours both started working on the same day. I'm using the S1 app also (11.2.2 last updated a month ago), Alexa Media Player 2.10.6 and Home Assistant 0.114.4.
> 
> What sonus product do you have that its work on now? Sonus One?

Sorry, Yes Sonos One purchased 6-8 months before the whole S2 app change.

**Comment by Molodax** [comment]
It's not the first time when it starts working. Again, it is either Sonos' or Amazon's side.
Sonos One and Beam are curently working in my configuration, though, I'd be sceptical that will last long based on the previous experience.

**Comment by oneseventhree** [comment]
> It's not the first time when it starts working. Again, it is either Sonos' or Amazon's side.
> Sonos One and Beam are curently working in my configuration, though, I'd be sceptical that will last long based on the previous experience.

your beam is working? Damn, mine isnt! What are you running? and are you using "notify.alexa_media_xxxx" and:

```
data:
  type: tts
message: xxxx
```

**Comment by puttemanp** [comment]
Started working for me again also. Sort of.
Using the old CLI script when listing my devices I see:
 config ./alexa_remote_control.sh -a
the following devices exist in your account:
Patrick's Sonos Beam
Living
Cuisine
Patrick's Sonos One Second Edition
Patrick - Echo Dot
Couloir
Patrick's 2nd Sonos One Second Edition
Patrick's 3rd Sonos One Second Edition
Garden
Patrick's Sonos Move
Salle De Bain
Echo Chambre
Living Sonos
Patrick - Echo Show
This Device
Patrick's Alexa Apps

It works on the 'generic' names. 
Patrick's 2nd Sonos One Second Edition is the same as Couloir.
When using 'Couloir' nothing happens, when using "Patrick's 2nd Sonos One Second Edition' the tts works.
It doesn't work on groups either. Living are 2 sonos one and one beam grouped as a surround system. 
Tried on the beam alone, no luck.

P.

**Comment by baldus88** [comment]
Hi.
I have retested today my sonos beams and work properly for this test script:
message: This is a test message
title: Titolo
data:
  type: tts
target : media_player.matteo_s_sonos_beam


Good news!!

**Comment by oneseventhree** [comment]
> I can reopen it, but I don't think there's anything we can do. It looks like an Amazon issue as we haven't changed any code.

Alan, I think this is working now and can be closed. Mine WASN'T working this morning but then I noticed there was two "Sonus beams" I am no sure why this is so maybe you can shine some light on this:
<img width="426" alt="Screen Shot 2020-09-20 at 10 18 44 am" src="https://user-images.githubusercontent.com/15043282/93691612-d0e3a700-fb2a-11ea-8d04-aecc864f3f7e.png">

I have ALWAYS used 'notify.alexa_media_sonus_beam' and my code hasn't changed from day one but I have now switched to 'notify.alexa_media_alexa_sonos_beam' and it now works.

If anyone is having trouble with their Sonus Beam make sure that you don't have two options and if you do then try the other one. Good luck!

**Comment by alandtse** [comment]
That list is autogenerated based on the speakers. Is there a media_player that matches each entry? I'll close this for now, but we all  know it may go back the other way. I'll open it up then.

**Comment by Takkuz** [comment]
Just to bring my experience to this absurd issue:
I've always used this code
```
- service: notify.alexa_media
  data:
    target:
      - media_player.alexa_bathroom
    data:
      type: tts
    message: "All right"
```

And it works.
Keep in mind that "media_player.alexa_bathroom" wasn't the "media_player.sonos_bathroom" that I use to manage Sonos. It's the Cast entity discovered by Alexa Media.

As said before it stops working and than starts again and stops again.

Today I've updated HA and Alexa Media and found this thing:
Alexa Media discovered the casting device as before but now, as @oneseventhree points out, I have 2 services for each of them: "notify.alexa_media_bathroom" and "notify.alexa_media_sonos_bathroom".

I've tried with many combination but it starts to work only with the latest one:

```
- service: notify.alexa_media_sonos_bathroom
  data:
    data:
      type: tts
    message: "All right"
```

Even using `service: notify.alexa` with target `notify.alexa_media_sonos_bathroom` doesn't work and, of course, even with any other target.

**Comment by kjake** [comment]
I don't have long-term evidence that this keeps working, but using the device serial number allows me to use both TTS and Announce for my Sonos One speakers, use the notify.alexa_media service, and specify more than one speaker as 'target'.

The easiest way to get the serial number (this doesn't match what Sonos shows in their app, but what Alexa shows), I used the Devices section on Amazon: https://www.amazon.com/hz/mycd/digital-console/alldevices and then selected the device I was after to see its detail to see the serial number.

Then, this works with notify.alexa_media:

```
data:
  type: announce
message: "Testing"
target: media_player.family_room_dot, 0001227e34a74791b90741deadbeef
```

**Comment by thegitcat** [comment]
Hi Guys,

First comment here, but I wanted to share this as I was also sending TTS using notify.alexa_media to Sonos and it was not working anymore.

I settle this with 75$ setup: Bought an old Sonos Connect for 50$, then a Echo Flex from Amazon for 25$.

Echo flex has an output, Sonos Connect an input.

All others compatibles Sonos equipment will then be able to play Alexa by choosing "Line In" of your Sonos Connect, without relying on Sonos or Amazon integration.

You can use a script to send TTS to all your Sonos, as well as all supported features from notify.alexa_media supported by Echo Flex.

The only thing for the moment is if you notify all devices at once (All Echos, All Sonos), there will be a small delay for Sonos as they have a to stream twice (Alexa-> Sonos Connect -> All Sonos devices) and echo devices only once (Alexa->Echo devices)

Probably can do something about it but I decided to rely only on Sonos for TTS notify (from Alexa) because I have more, and because they sound better.

Thanks guys. (and girls)

**Comment by daytonturner** [comment]
Sorry to jump on a dead thread here but curious what the current day consensus is, as its now two years later..

I was trying to get actionable notifications working via my sonos move's, and while it works great for actual "Echo" devices, nothing plays on the Move.  So, i tried basic TTS and notice there's simply no audio coming out.

The activity log in the Alexa app shows the correct speaker was addressed, but is labelled "Activity initiated by routines. No voice data stored" So, clearly the request is making it from HA to Amazon, Alexa sees it addressing the correct speaker, but no audio comes out of it.

Happy to provide any information I can, if it would help - I'm mostly curious if anyone is _successfully_ using Alexa_Media_Player TTS+Sonos together?  Playing music or observing play status/interacting with the transport controls works fine too.

**Comment by oneseventhree** [comment]
> Sorry to jump on a dead thread here but curious what the current day consensus is, as its now two years later..
> 
> I was trying to get actionable notifications working via my sonos move's, and while it works great for actual "Echo" devices, nothing plays on the Move. So, i tried basic TTS and notice there's simply no audio coming out.
> 
> The activity log in the Alexa app shows the correct speaker was addressed, but is labelled "Activity initiated by routines. No voice data stored" So, clearly the request is making it from HA to Amazon, Alexa sees it addressing the correct speaker, but no audio comes out of it.
> 
> Happy to provide any information I can, if it would help - I'm mostly curious if anyone is _successfully_ using Alexa_Media_Player TTS+Sonos together? Playing music or observing play status/interacting with the transport controls works fine too.

Have you tried
```
data:
  data:
    type: tts
  message: Testing 1 2 Testing
service: notify.alexa_media_echo_beam
```

I am able to use TTS on my Sonos Beam using the above code and Alexa Media Player

**Comment by daytonturner** [comment]
tried this - still same failing behavior, unfortunately.  Perhaps I'll try on an Arc or One instead of just trying the Move's..
