### ISSUE TITLE
This device has now disconnected from .... avoid?

### ISSUE THREAD

**Issue by pkishino** [custom-components/alexa_media_player#689]
Hey all, just wondering if anyone has come up with a good way to make alexa shut up about bluetooth disconnection? 
I have it working soso by reducing volume just before speaker switches of bluetooth, then repeat volume change , switch to local speaker etc..
sometimes alexa will remain quiet, but more often than not there will be some words said, at a different volume (usually higher) than is actually set.
thanks

**Comment by alandtse** [comment]
I don't think we can control that. That's an Amazon issue. I'll leave this open for a bit to see if anyone chimes in but it may make sense to ask on the forum.

**Comment by pkishino** [comment]
which forum ? alexa dev forum?

**Comment by alandtse** [comment]
No, the HA [community](https://community.home-assistant.io/t/echo-devices-alexa-as-media-player-testers-needed/58639/3899) forum.

**Comment by pkishino** [comment]
ah,posted there as well, I'll close this or now
