### ISSUE TITLE
Add support for `Alexa.DeviceControls.Stop` sequence.

### ISSUE THREAD

**Issue by brgerig** [custom-components/alexa_media_player#692]
Requesting support for the `Alexa.DeviceControls.Stop` sequence. In the Routine creation, it's the "Stop Audio" action. It's almost the basic operationPayload, but can accept multiple devices.

Advantage: Skills that play audio aren't necessarily playing media, and therefore cannot be stopped by media_stop. (As an example, see the Sleep Sounds skills.) The Alexa.DeviceControls.Stop sequence does stop the audio from these skills.

Payload JSON:
```
{
"@type":"com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode",
"type":"Alexa.DeviceControls.Stop",
"skillId":"amzn1.ask.1p.alexadevicecontrols",
"operationPayload":
    {"customerId":"**************",
    "devices": 
         [{"deviceType":"AWZZ5CVHX2CD",
        "deviceSerialNumber":"************"}],
    "isAssociatedDevice":false},
"tag":null,
"name":null
}
```

Can also stop audio on all devices using this payload:
```
"@type":"com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode",
"type":"Alexa.DeviceControls.Stop",
"skillId":"amzn1.ask.1p.alexadevicecontrols",
"operationPayload":
    {"customerId":"**************",
    "devices": 
         [{"deviceType":"ALEXA_ALL_DEVICE_TYPE",
        "deviceSerialNumber":"ALEXA_ALL_DSN"}],
    "isAssociatedDevice":false},
"tag":null,
"name":null
}
```

**Comment by alandtse** [comment]
I tested this earlier and at the time it actually failed to stop media playback which was a non-starter since that was a core feature of the component. Have you tested it to confirm it works for at least that base case?

**Comment by brgerig** [comment]
You're right; media_stop fails with a NotImplementedError.

media_pause does work, though.

**Comment by alandtse** [comment]
I was referring to testing the stop command in a routines using the Amazon app to make sure it properly stops everything.

**Comment by brgerig** [comment]
Ah! Sorry, misunderstood.

I just tested it by creating an Alexa routine that runs Stop Audio, targeted to the show next to me. I then used play_media on HASS to execute that routine. It successfully stopped both Spotify, and the sleep sounds skill that we use at night. I didn't test it with echo speaker groups, or with "All devices" as the target in the routine.

**Comment by alandtse** [comment]
Please test and let me know if it works for you.

**Comment by brgerig** [comment]
It works! Thank you!

I tested it on a device playing Spotify, and one playing a sleep sound skill, both at the same time, and Spotify on a speaker group. All of them worked. I wasn't sure if there was a way of targeting "All devices" without listing them all individually in the entity_ids.
