### ISSUE TITLE
Calling skills with v2.7

### ISSUE THREAD

**Issue by bhchew** [custom-components/alexa_media_player#693]
Notice that the latest version 2.7 added a feature to call skills.

Can it call generic skills instead of custom skills?

If so how can we figure out the skill id of generic skills?

**Comment by keatontaylor** [comment]
Hey @bhchew it can indeed call any skill. We do not collect an exhaustive list of Skill IDs, but it should be simple enough to fetch it using browser developer tools while you're looking at the https://alexa.amazon.com skills page. 

Otherwise, post the skill you're interested in and I'll try and hut the ID down for you.

**Comment by bhchew** [comment]
Hi @keatontaylor, that's great to know!

Nice work on this and also on the actionable notifications! It's a great addition to the many features already available :)

**Comment by keatontaylor** [comment]
Glad to help, I'll go ahead and close this issue.

**Comment by 3ative** [comment]
@keatontaylor 
I hope you're still viewing this thread. I'm looking for the 'Skill ID' for this:
https://alexa.amazon.co.uk/spa/index.html#skills/dp/B078MR9JY4/?ref=skill_dsk_skb_sr_0&qid=8d59fbfd-088e-4a2f-85da-900dd8f6b56c

But, I having real trouble trying to work out how to do it.

**Comment by nnthinh912** [comment]
@keatontaylor I'm also not sure how exactly to do this. I would love to get the Skill ID for this https://alexa.amazon.co.uk/spa/index.html#skills/dp/B07SVY2RMT/?ref=skill_dsk_skb_ys

I tried searching for "amzn1." (all skill IDs should contain this part) in the HTML but got no results.

@3ative have you managed to figure this out?

**Comment by 3ative** [comment]
@nnthinh912 Yeah, I kinda did... it's a bit long to type out, I'll try and make a tutorial ASAP.
In the meantime, the id for that skill is: amzn1.ask.skill.bb0f7827-ecdd-4829-b95b-b09db13d1e5d

**Comment by nnthinh912** [comment]
Hey @3ative , thank you for your response. I managed to find the instructions here: https://community.home-assistant.io/t/echo-devices-alexa-as-media-player-testers-needed/58639/3995.

**Comment by 3ative** [comment]
@nnthinh912 No worries.
The trouble with those instructions is not every skill uses "**_ask.skill..._**" Some use "**_echo-sdk-ams.app..._**" :)
The way I do it will find any.
