### ISSUE TITLE
Text To Speech Doesn't Work

### ISSUE THREAD

**Issue by GeoCyberwolf** [custom-components/alexa_media_player#695]
**Describe the bug**
When sending a text to speech to an alexa device it responds with "Sorry text to speech can only be called with the notify.alexa_media service."

**To Reproduce**
Try to send text to speech to an alexa device

**Expected behavior**
Text to speech plays on the alexa device

**Comment by alandtse** [comment]
Use the [Notify service](https://github.com/custom-components/alexa_media_player/wiki/Configuration%3A-Notification-Component).
