### ISSUE TITLE
Lost connection to all devices

### ISSUE THREAD

**Issue by langelguy** [custom-components/alexa_media_player#696]
**Describe the bug**
Devices were connected and now shows error:

The following integrations and platforms could not be set up:
alexa_media
Please check your config.

Tried to update from 2.5.11 in the HACS store and when I hit update and restart HA it doesn't update.  Stays on 2.5.11 and devices aren't connected
**System details**
 - Home-assistant (version): 0.109.6
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug). yes
 - alexa_media  (version from `const.py` or HA startup):2.5.11
 - alexapy (version from `pip show alexapy` or HA startup):?

**Additional context**
Was working fine before.  Cannot delete the integration from the integrations page as well.

**Comment by alandtse** [comment]
Uninstall from HACS and reinstall.

**Comment by langelguy** [comment]
Tried that and same issue.  Integration remains as well even when it’s removed from HACS

**Comment by alandtse** [comment]
HACS would not remove the integration from HA. You have to do that manually. Please provide start up logs. It sounds like your files are messed up.

**Comment by langelguy** [comment]
Had to reinstall and it allowed me to remove the integration.  Then uninstalled from HACS and reinstalled everything.  It's working now.  Thanks!
