### ISSUE TITLE
Fails at start with TypeError: __init__() missing 1 required positional argument: 'request_refresh_debouncer'

### ISSUE THREAD

**Issue by paoloantinori** [custom-components/alexa_media_player#697]
**Describe the bug**
After an apparent succesfull 2FA, I get this error upon restart:
```
2020-05-09 21:58:54 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry XXXXX@gmail.com - amazon.it for alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 215, in async_setup
    hass, self
  File "/config/custom_components/alexa_media/__init__.py", line 221, in async_setup_entry
    if await test_login_status(hass, config_entry, login, setup_alexa):
  File "/config/custom_components/alexa_media/configurator.py", line 180, in test_login_status
    await hass.async_add_job(alexa_setup_callback, hass, config_entry, login)
  File "/config/custom_components/alexa_media/__init__.py", line 880, in setup_alexa
    seconds=scan_interval * 10 if websocket_enabled else scan_interval
TypeError: __init__() missing 1 required positional argument: 'request_refresh_debouncer'
```

**To Reproduce**
1. Just restart

**System details**
 - Home-assistant (version): `0.105.4`
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): `v2.7.0`
 - alexapy (version from `pip show alexapy` or HA startup): `1.8.2`

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by paoloantinori** [comment]
Nevermind. Gremlin has gone. God knows.

**Comment by alandtse** [comment]
Please update to HA 106 or greater. 105 is not supported for later versions of `alexa_media` that use the DataUpdateCoordinator. If you were using HACS, then there's probably a bug we need to report as it should've [prevented the install](https://github.com/custom-components/alexa_media_player/blob/dev/hacs.json#L13). 

While your PR got it to load, I don't know if there's other things that may have been broken. You're more than welcome to keep debugging the older version and I can accept PRs if they don't break things in later versions.

**Comment by alandtse** [comment]
Closing this out since it's related to using the component with an unsupported version of HA.
