### ISSUE TITLE
Full support for 0.110.x: components deprecated

### ISSUE THREAD

**Issue by chemelli74** [custom-components/alexa_media_player#699]
**Describe the bug**
0.110.x change some components, plugin needs an update.

**To Reproduce**
1. Install 0.110.x dev build
2. Install Alexa_media_player plugin
3. Check home-assistant.log

**Expected behavior**
Update plugin to offer full compatibility since the beginning of 0.110.x

**Screenshots**

**System details**
 - Home-assistant (version): 0.110.x
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): v2.7.0
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

```
2020-05-10 18:56:45 WARNING (MainThread) [homeassistant.components.media_player] MediaPlayerDevice is deprecated, modify AlexaClient to extend MediaPlayerEntity
2020-05-10 18:56:46 WARNING (MainThread) [homeassistant.components.switch] SwitchDevice is deprecated, modify AlexaMediaSwitch to extend SwitchEntity
2020-05-10 18:56:46 WARNING (MainThread) [homeassistant.components.alarm_control_panel] AlarmControlPanel is deprecated, modify AlexaAlarmControlPanel to extend AlarmControlPanelEntity
```

**Additional context**

**Comment by alandtse** [comment]
This change in HA looks entirely [cosmetic](https://github.com/home-assistant/core/pull/34592). We'll probably address it in a couple of releases but for backwards compatibility people will have to live with this warning.

**Comment by chemelli74** [comment]
> We'll probably address it in a couple of releases but for backwards compatibility people will have to live with this warning.

No problem.
JFYI, at ShellyForHass we fixed it to leave log clean and it works for both 0.109x and 0.110.x

Simone

**Comment by sagitt** [comment]
i have these errors

![Schermata 2020-05-17 alle 21 55 10](https://user-images.githubusercontent.com/169086/82158725-e2215c00-9889-11ea-8773-ba62d0ff130f.png)
![Schermata 2020-05-17 alle 21 54 51](https://user-images.githubusercontent.com/169086/82158726-e3eb1f80-9889-11ea-8bd1-f30f81b95002.png)

**Comment by CiquattroFPV** [comment]
I have this error AlarmControlPanel is deprecated, modify AlexaAlarmControlPanel to extend AlarmControlPanelEntity

**Comment by lbouriez** [comment]
+1

**Comment by steve-gombos** [comment]
Just want to add all that I am seeing in my logs.

```
Logger: homeassistant.components.switch
Source: components/switch/__init__.py:73
Integration: Switch (documentation, issues)
First occurred: 9:40:28 AM (4 occurrences)
Last logged: 9:40:28 AM

SwitchDevice is deprecated, modify AlexaMediaSwitch to extend SwitchEntity
SwitchDevice is deprecated, modify DNDSwitch to extend SwitchEntity
SwitchDevice is deprecated, modify ShuffleSwitch to extend SwitchEntity
SwitchDevice is deprecated, modify RepeatSwitch to extend SwitchEntity
```

```
Logger: homeassistant.components.media_player
Source: components/media_player/__init__.py:333
Integration: Media player (documentation, issues)
First occurred: 9:40:27 AM (1 occurrences)
Last logged: 9:40:27 AM

MediaPlayerDevice is deprecated, modify AlexaClient to extend MediaPlayerEntity
```

```
Logger: homeassistant.components.alarm_control_panel
Source: components/alarm_control_panel/__init__.py:96
Integration: Alarm control panel (documentation, issues)
First occurred: 9:40:28 AM (1 occurrences)
Last logged: 9:40:28 AM

AlarmControlPanel is deprecated, modify AlexaAlarmControlPanel to extend AlarmControlPanelEntity
```

**Comment by JoeStratton** [comment]
same issue here 

2020-05-20 08:29:25 WARNING (MainThread) [homeassistant.components.alarm_control_panel] AlarmControlPanel is deprecated, modify AlexaAlarmControlPanel to extend AlarmControlPanelEntity

**Comment by alandtse** [comment]
Please thumbs up the first post if you have this and do not add a new comment. This is cosmetic for now but fixing it may break the component for older HAs. We will likely fix it around HA 112 to give people time to migrate.

**Comment by N1c093** [comment]
You can also add backwards compatibility, so it wouldn't break the integration in older HA: https://developers.home-assistant.io/blog/2020/05/14/entity-class-names/

**Comment by alandtse** [comment]
@N1c093 thanks. I hadn't seen that link.
