### ISSUE TITLE
last Alexa Not working in v2.7.1

### ISSUE THREAD

**Issue by pdgithub78** [custom-components/alexa_media_player#706]
**Describe the bug**
After upgrading to v2.7.1 the last_Alexa stopped working. After reverting back to v2.7.0 it worked again. 

**System details**
 - Home-assistant (version): 0.109.6
 - Hassio (Yes/No): Yes (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup): 2.7.0
 - alexapy (version from `pip show alexapy` or HA startup):

**Comment by alandtse** [comment]
This is likely related to #705. However, without logs I don't know.

**Comment by alandtse** [comment]
Try 2.7.2 and let me know if it still has a problem.

**Comment by timota** [comment]
still not working. 
What kind of logs do you need ?
