### ISSUE TITLE
High bandwidth usage incoming from Amazon servers

### ISSUE THREAD

**Issue by snicker** [custom-components/alexa_media_player#707]
I recently updated my Ubiquiti EdgeMAX router to enable traffic analysis and was quite surprised to see that HA was several gigabytes of incoming data each day. I decided to chase this down today and found that 90% of traffic is incoming from these two IP addresses:

52.26.216.60 Amazon.com, Inc. (AS16509) | ec2-52-26-216-60.us-west-2.compute.amazonaws.com
34.215.231.14 Amazon.com, Inc. (AS16509) | ec2-34-215-231-14.us-west-2.compute.amazonaws.com

I just updated to the latest version of Alexa Media Player moments before submitting this issue.

I don't seem to have any other integrations or applications running on this machine that could be making this much contact to Amazon's servers.

Is there any way to curtail this bandwidth usage? Is this a function of the number of Amazon devices in my household?

**System details**
 - Home-assistant (version): 0.109.2
 - Hassio (Yes/No): No
 - alexa_media: 2.7.1
 - alexapy: 1.8.3

**Logs**
Here's a snip from the Darkstat output running on the same machine has HA for only a few minutes 
![image](https://user-images.githubusercontent.com/221540/81597895-466c8900-937b-11ea-8dae-d8d3eb5eb850.png)

**Comment by snicker** [comment]
Update: I've recorded nearly 1.15Gb of incoming data in 75 minutes

**Comment by alandtse** [comment]
Disable alexa_media and see if it persists. The data downloaded should not be this much.

**Comment by snicker** [comment]
Yep, not AMP... my apologies for not investigating a little further. off to bang my head on a new wall

**Comment by snicker** [comment]
FYI, this was my own Zwift component, 🤦, sorry @alandtse

**Comment by alandtse** [comment]
No biggie. Glad you figured it out.
