### ISSUE TITLE
ERROR alexaapi._static_request:An error occured accessing AlexaAPI: An exception of type RuntimeError occurred.

### ISSUE THREAD

**Issue by monotonus** [custom-components/alexa_media_player#716]
**Describe the bug**
After the latest updates I receive these messages massively in syslog when restarting home assistant:

May 12 22:38:17 homeassistant hass[3109]: 2020-05-12 22:38:17 ERROR (MainThread) [alexapy.helpers] alexaapi._static_request:An error occured accessing AlexaAPI: An exception of type RuntimeError occurred. Arguments:
May 12 22:38:17 homeassistant hass[3109]: ('Session is closed',)

The CPU load goes very high and it takes some time to stop/start or restart home assistant service.

Currently reinstalled version v.2.7.0 without thes errors.

**To Reproduce**
1. Update Alexa Media Player to v2.7.2 - 4
2. Restart Home Assistant
3. Check syslog live via tail -f /var/log/syslog

**Expected behavior**

**Screenshots**

**System details**
 - Home-assistant (version):  0.109.6 / virtualenv / Proxmox Debian LXC
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): n/a
 - alexapy (version from `pip show alexapy` or HA startup): n/a

**Comment by alandtse** [comment]
Thanks for the detailed report. This is a dupe and I'm working on resolving in #711
