### ISSUE TITLE
List connected Bluetooth speakers

### ISSUE THREAD

**Issue by mdm2207** [custom-components/alexa_media_player#718]
I used to use the source list to detect if certain Bluetooth speakers were connected as part of a room presence automation, but I can see from the wiki that this is now only for inputs. 

Is it no longer possible to get this info?

Thanks

**Comment by alandtse** [comment]
You want to know the connected bluetooth device? The source list only ever showed the paired devices. It never identified a list of connected devices. You're referring to the `source` attribute right?

**Comment by mdm2207** [comment]
Ah yes I am. The use case is that I have a shower speaker that connects automatically when turned on and I used the attribute to tell HA where I was. I tried it today and it didn’t update from Local Speaker.

I guess it’s not really a source but could be a new attribute maybe?

**Comment by alandtse** [comment]
Yah I think we could expose an attribute.

**Comment by mdm2207** [comment]
That would be amazing thank you!

**Comment by alandtse** [comment]
Please test and see if this is what you wanted.

**Comment by mdm2207** [comment]
I won’t be able to test until the weekend (once I’ve figured out how to apply the changes) but if it exposes the Bluetooth speaker in any way then I’m happy :)

Ps I really appreciate the help and quick response 👍🏻

**Comment by mdm2207** [comment]
Works perfectly, thanks again
