### ISSUE TITLE
Unable to login to amazon account

### ISSUE THREAD

**Issue by clsferguson** [custom-components/alexa_media_player#723]
**Describe the bug**
I made the mistake of running out of hd space on my server drive. Since then I have had several issues. I was able to resolve most fairly easily. But now I am having issues getting this component to work.

When first got home assistant out of safe mode, there was a notification that said "click here to log in" it would not do anything, and my alexa stuff would not be accessible. First I tried to reinstall the component (2.7.5). same issue, so I removed the pickle files and uninstalled the component. then rebooted, reinstalled.

now when i try to add the integration and click the "sign in" button I have the same problem still. I disabled 2fa on my amazon account to be sure, no luck. I tried to down grade to 2.7.1. still no luck.

logs are minimal

**System details**
 - Home-assistant (version): 0.109.6
 - Hassio (Yes/No): yes

**Logs**
Logger: alexapy.helpers
Source: custom_components/alexa_media/config_flow.py:218
First occurred: 2:03:26 PM (1 occurrences)
Last logged: 2:03:26 PM
alexalogin.login:An error occured accessing AlexaAPI: An exception of type AssertionError occurred. Arguments: ()

**Comment by alandtse** [comment]
Can you please enable advanced debugging and add logging per the template? If you post here, please scrub for your email/password. The instructions explain other things to look out for. Alternatively you can dm me on the forums or discord.

**Comment by mrcasablr** [comment]
I have the exact same error. Unable to integrate Alexa with HA 0.110 (even 0.109 or less did not work).  Let me see if I can get you all the details that would help

**Comment by mrcasablr** [comment]
Following the steps here fixed this issue for me - https://github.com/custom-components/alexa_media_player/issues/733

**Comment by alandtse** [comment]
Please try the PR #744.
