### ISSUE TITLE
2.7.5 not triggering routines

### ISSUE THREAD

**Issue by oneseventhree** [custom-components/alexa_media_player#728]
Had to move back to 2.7.4

**Comment by alandtse** [comment]
Please provide logs. There wasn't any change to the routine playback between 2.7.4 and 2.7.5.

**Comment by alandtse** [comment]
Add use the template. I won't respond further otherwise.

**Comment by alandtse** [comment]
We can reopen when your'e ready to provide more information. Thanks!
