### ISSUE TITLE
Speaker group device missing service data

### ISSUE THREAD

**Issue by chemelli74** [custom-components/alexa_media_player#734]
**Describe the bug**
Service data sample not shown

**To Reproduce**
1. Go to 'developer tools -> services'
2. Select a device representing a group of speakers
3. Service data are empty

**Expected behavior**
Same service data as physical device should be shown

**Screenshots**

![image](https://user-images.githubusercontent.com/57354320/82344148-fa14ef00-99f3-11ea-9a39-f2cff2565aca.png)

**System details**
 - Home-assistant (version): 0.110.b4
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): 2.8.0
 - alexapy (version from `pip show alexapy` or HA startup):

**Comment by alandtse** [comment]
You need to fill in the service data yourself. We don't generate or save that. Your browser may sometimes cache that from prior entries.

**Comment by chemelli74** [comment]
It was probably a cache than, sorry for the misleading report.
Anyway, would be nice to add something like that:

![image](https://user-images.githubusercontent.com/57354320/82349517-78748f80-99fa-11ea-8b03-80ee2068434a.png)

Simone

**Comment by alandtse** [comment]
Not possible for custom components using the notify service. You can only do it for services for your own platform. It's possible it's changed but this was how it was the last time I looked like a year ago.

**Comment by bachoo786** [comment]
@alandtse I have grouped my echo dots via the HA UI and I am trying to play an mp3 file which is in the correct format and less than 240 seconds. However the mp3 file does not play but when I play it on an individual echo dot it does play. What am I doing wrong? I have no error logs in my log either.
