### ISSUE TITLE
Alarms and Timers are not discovered using HACS

### ISSUE THREAD

**Issue by lweberru** [custom-components/alexa_media_player#745]
**Describe the bug**
I installed the integration with HACS and added it via integration page. The Echo Devices itself got listed in the positive list there. The 5 devices where found but not one timer or alert sensor got created as explained in the documentation.

**To Reproduce**
1. Go to 'HACS'
2. Click on 'Install Alexa Media Player'
3. Follow Link to 'Integration Page'
4. Add 'Alexa Media Player'
5. Enter email, password and the list of the real alexa device names

**Expected behavior**
Discovery of the selected devices + all correcsponding alarms and timers.

**Screenshots**
![image](https://user-images.githubusercontent.com/20902204/82727234-8b80ab80-9ce9-11ea-9865-bfad1acff79e.png)

**System details**
 - Home-assistant (version): 0.110.0
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): 2.8.0
 - alexapy (version from `pip show alexapy` or HA startup): 1.10.0

**Logs**
Logs show neither errors nor things explaining why these alarms and timers are not created.

**Additional context**

**Comment by alandtse** [comment]
Did you use `include_device` or `exclude_device`? Do you have any active timers?

Please provide startup logs.

**Comment by alandtse** [comment]
I saw your post in the main forum. Please read the include_device [documentation](https://github.com/custom-components/alexa_media_player/wiki/Configuration#configuring-inclusions-or-exclusions-versions--096) carefully. If you didn't include the timers/switches manually, then of course they are being filtered per your configuration.

**Comment by lweberru** [comment]
Hmm, there is nothing told how to "include" all needed "add-on" sensors and things via include. It is said, that you have to name the devices as they are named within alexa. And inside alexa I have no sensors and things like that. And it is said in documentation, that for all found devices timers and alerts are beeing generated. Can you give some examples how to include these additional components?

**Comment by alandtse** [comment]
Disable the `include_device` filter and you'll see all the names.
