### ISSUE TITLE
No captcha image - can't login

### ISSUE THREAD

**Issue by Stooovie** [custom-components/alexa_media_player#748]
**Describe the bug**
HA notification asks me to configure the addon. Required captcha never displays 

**To Reproduce**
Steps to reproduce the behavior
1. Click Notifications 
2. Click Configure on the notification
3. Click "confirm" to refresh as requested 
4. Captcha is not displayed 

**Expected behavior**
Captcha displays properly 

**Screenshots**

**System details**
 - Home-assistant (version): 0.110.1
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): 2.8.1l
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway

**Comment by chemelli74** [comment]
Seems I suffer for the first time of the same issue:

![image](https://user-images.githubusercontent.com/57354320/82766203-55dcdf00-9e1d-11ea-8885-c69295a54224.png)

Simone

**Comment by timelf123** [comment]
The captcha url is 5 hours expired for me and results in
> AccessDeniedRequest has expired

**Comment by Stooovie** [comment]
It Eventually just worked for me 🤷‍♂️ try many times, it'll probably work at some point

**Comment by chemelli74** [comment]
I did some testing, image is always corrupted on first opening then works fine.

Simone
