### ISSUE TITLE
Alexa Media Player integration doesn't work

### ISSUE THREAD

**Issue by maciej-szalaj** [custom-components/alexa_media_player#749]
Hi,

Can anyone help to solve my issue with the integration? I did follow all instruction how to run it on my Home Assistant (Raspberry Pi 4; HassOS 3.13). I can see all entities and devices (4 Echo Dot 3rd Gen.) but cannot make Alexa to speak. When running service media_player nothing happens. State of my Echo Dot's remains unavailable or standby.
I'm completely new with HA so please let me know if more information would be required to solve me issue.  

![image](https://user-images.githubusercontent.com/65733177/82794891-79cb0f80-9e73-11ea-938f-ea2196be617c.png)

![image](https://user-images.githubusercontent.com/65733177/82794824-5f913180-9e73-11ea-81e9-0a31981b022a.png)

**Comment by alandtse** [comment]
Please review the [notify](https://github.com/custom-components/alexa_media_player/wiki/Configuration%3A-Notification-Component) service documentation.

**Comment by maciej-szalaj** [comment]
I did what was suggested by @alandtse but no change. My Echo Dot remains speechless. I'm pasting my current configuration. I have already try to remove this integration and start from the begging, but there was not CAPTCHA request during new installation. Could be that there is too much Echo's in my network (4 pcs) so I did try to exclude 3 and keep only 1 in HA - no success. Any ideas how to sole it? I would really appreciate as making Alexa speak would be really awesome part of automations I would like to implement into my HA. 

tts:
  - platform: google_translate
  
notify:
  - platform: alexa_media
    name: alexa_media
    
    
alexa_media:
  accounts:
    - email: my email
      password: my password
      url: amazon.de
      exclude_devices:
      - "Echo Dot Bathroom"
      - "Echo Dot Lena's room"
      - "Echo Dot Bedroom"

**Comment by alandtse** [comment]
Please identify the service call you are using to test under dev_tools. Also, please provide logs showing the attempt. The original template for bug reports provided instructions on how to generate the logs.

**Comment by maciej-szalaj** [comment]
It seems to be much more difficult than I expected. Have no idea how to generate logs. I did follow the instruction how to modify configuration (see below) but no files available under config\custom_components\alexa_media available. Regarding which service call I'm using to test this integration see below:

![image](https://user-images.githubusercontent.com/65733177/83341609-89b87880-a2e5-11ea-9137-885416a42388.png)


`tts:
  - platform: google_translate
  
notify:
  - platform: alexa_media
    name: alexa_media
    
    
alexa_media:
  accounts:
    - email: my_mail
      password: my_password
      url: amazon.de
      exclude_devices:
      - "Echo Dot Bathroom"
      - "Echo Dot Lena's room"
      - "Echo Dot Bedroom"
      debug: true
      
logger:
  default: critical
  logs:
    custom_components.alexa_media: debug`

**Comment by alandtse** [comment]
I've edited your post so it'd properly quote the information you're providing. Please note how I did that. I've also edited the configuration to provide information I'll need.

Please check your Developer Tools -> Logs page (Click Load Full Homeassistant Logs). That's where you should start seeing items for alexa_media.
https://HA/developer-tools/logs

You should save the logs to a text file and then quickly scan it to remove your email/passwords/ or other sensitive information.

**Comment by maciej-szalaj** [comment]
Hi,

Here is the log for Alexa Media Player. Thank you very much for supporting me with this.

[Alexa media log.txt](https://github.com/custom-components/alexa_media_player/files/4707354/Alexa.media.log.txt)

**Comment by alandtse** [comment]
Can you please also add the debug line for alexapy? I added the setting in your response earlier. The component is detecting websocket information so should be able to update information. It also saw that you were playing spotify on the speaker before you tried the TTS.

Is the state not showing when you're playing music? Please note that the TTS will never change the state shown, only music will.

One thing to note is that the volume is very low (3) which is near silent at least on my dots.

Also, you may want to test "announce" as well to see if it makes a difference. Please make sure you've [enabled Communications](https://github.com/custom-components/alexa_media_player/wiki/FAQ#announce-doesnt-work-while-tts-does) in the App though.

**Comment by maciej-szalaj** [comment]
Sorry for the delay - I did not understood what you are asking me for. But now it is done. I have added alexapy debug line into my configuration and new log have been created:
[Alexa log.txt](https://github.com/custom-components/alexa_media_player/files/4713623/Alexa.log.txt)

Media Player card is showing no status - as shown in first post. When playing Spotify, HA card changes from blue into gray, and device (Echo) changes its state from 'standby' into 'unavailable'.

Regarding the volume - when trying to make Alexa say something, there was always Spotify playing before with good enough volume level, so in my opinion it is not about volume level.

Announcement makes no difference. Alexa remains silent. Communications is enabled on all devices.

**Comment by alandtse** [comment]
> Sorry for the delay - I did not understood what you are asking me for. But now it is done. I have added alexapy debug line into my configuration and new log have been created:

> Media Player card is showing no status - as shown in first post. When playing Spotify, HA card changes from blue into gray, and device (Echo) changes its state from 'standby' into 'unavailable'.

> Regarding the volume - when trying to make Alexa say something, there was always Spotify playing before with good enough volume level, so in my opinion it is not about volume level.

> Announcement makes no difference. Alexa remains silent. Communications is enabled on all devices. 

Thanks I deleted the comment so your log would be deleted. Your echo dot appears to be registered in the US and not in Germany. 
```
2020-06-01 23:30:00 DEBUG (MainThread) [custom_components.alexa_media] Echo Dot Sitting room: Locale en-us timezone Europe/Warsaw
```
That may be why it's appearing as unavailable. Can you try switching your domain to amazon.com to see if that works. If that ends up working, then you have to decide if you want to reregister it to your locale or not or just use the domain it's under.
