### ISSUE TITLE
AlarmControlPanel is deprecated, modify AlexaAlarmControlPanel to extend AlarmControlPanelEntity

### ISSUE THREAD

**Issue by tri94** [custom-components/alexa_media_player#753]
Sorry never created one of these. 

Running Home Assistant 0.110.3
In my logs i see the following errors 
AlarmControlPanel is deprecated, modify AlexaAlarmControlPanel to extend AlarmControlPanelEntity

SwitchDevice is deprecated, modify AlexaMediaSwitch to extend SwitchEntity

MediaPlayerDevice is deprecated, modify AlexaClient to extend MediaPlayerEntity

Thanks

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details**
 - Home-assistant (version): Home Assistant 0.110.3
 - Hassio (**Yes**/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by chemelli74** [comment]
You should upgraded to latest version, is already fixed ;-)

Simone

**Comment by tri94** [comment]
This is possibly a really stupid question but how do I do that?
