### ISSUE TITLE
unable to link account

### ISSUE THREAD

**Issue by ygarti** [custom-components/alexa_media_player#754]
**unable to link account and to start use alexa_media**
i am using the latest alexa_media 
i used alexa_media a lot and today on HA Core 0.110.3 (docker) i got a notification that i need to enter a captcha but not matter what i did it didn't work.
after a while i saw that i got an email from amazon (Amazon Authentication) and that i needed to enter a code (i didn't know it because the gui didn't tell me that this is what i needed to do)
i tried to log in to the site and enter the the Amazon Authentication and i was able to enter the site from chrome but the custom component didn't work.

i tried to delete the custom component  folder i tried to remove it from the GUI and reinstall
nothing i tried make it work

it;s asking me for my username and password ask me to enter a captcha theni got a blank text with no info and the alexa_meida was waiting for me to enter something but i don't know what because it's just a blank text (see below the link for the pic)

**To Reproduce**
1. to reconfigure the component.

**Expected behavior**
passing the authentication 

**Screenshots**
https://ibb.co/2ZD1vxk

**Additional context**
i have backup to my HA folder if it helps in any way

Thanks a lot :)

**Comment by HutchMD** [comment]
I have having an almost similar problem: It asks to enter a Captcha code, however the image above does not load, so it's impossible to enter the correct Captcha code.

**Comment by ygarti** [comment]
i was able to solve this

1. clear cache
2. when i got this empty text amazon sent me an email with a code (you need to write it so people will know to open their email and search for the code)
3. remove everything related from the yaml (i dont know if it did something but i still did it).
4. pray :)
