### ISSUE TITLE
JSONDecodeError on login error flooding the logs

### ISSUE THREAD

**Issue by eifinger** [custom-components/alexa_media_player#756]
**Describe the bug**

My homeassistant log gets flooded with messages in the form of
```bash
2020-05-28 01:09:15 ERROR (MainThread) [alexapy.helpers] alexaapi.get_notifications: A login error occured: An exception of type JSONDecodeError occurred. Arguments:
('Expecting value: line 1 column 1 (char 0)',)
```
The exact function differs but it is always in the form of `alexaapi.get_<...>`.
Due to the extreme volume of messages I cannot determine what started them.
A restart of homeassistant seems to work.

**To Reproduce**

Unknown

**Expected behavior**

No JSONDecodeErrors

**Screenshots**

**System details**
 - Home-assistant (version): 0.110.3
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug). No
 - alexa_media  (version from `const.py` or HA startup): v2.8.2
 - alexapy (version from `pip show alexapy` or HA startup): v1.10.1

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

```bash
2020-05-28 01:09:15 ERROR (MainThread) [alexapy.helpers] alexaapi.get_notifications: A login error occured: An exception of type JSONDecodeError occurred. Arguments:
('Expecting value: line 1 column 1 (char 0)',)
```

**Additional context**

**Comment by eifinger** [comment]
Additional information: After the restart I had to login again with my password and a captcha.

**Comment by alandtse** [comment]
Thanks. This is a bug that we're trying to track down. It's detecting your cookie has expired but it's not stopping the update requests.
