### ISSUE TITLE
Additional Sounds - Not All Play 

### ISSUE THREAD

**Issue by tonyawad88** [custom-components/alexa_media_player#757]
**Describe the bug**
When using HAAS service: "media_player.play_media" with the entity being my echo dot, not all sounds play on the echo dot. I basically tried to retrieve the sounds from the link at: https://developer.amazon.com/en-US/docs/alexa/custom-skills/ask-soundlibrary.html 
**works well:**
`{"entity_id": "media_player.my_echo_do","media_content_id": "amzn_sfx_doorbell_01", "media_content_type": "sound"}`
**doesn't work:**
`{"entity_id": "media_player.my_echo_do","media_content_id": "amzn_sfx_doorbell_buzz_01", "media_content_type": "sound"}`

Could it be a limitation of the echo device? 

**To Reproduce**
1. Go to 'HAAS Developer Tools' 
2. Select Service: `media_player.play_media`
3. Select your Amazon Alexa device
4. Paste the above JSON and click "Call Service"

**Expected behavior**
I was expecting that both should play. 

**Screenshots**
N/A

**System details**
 - Home-assistant (version): 0.110.3
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): 2.8.2
 - alexapy (version from `pip show alexapy` or HA startup): Not sure where to get it..

**Logs**
N/A
**Additional context**
N/A

**Comment by alandtse** [comment]
Only those supported by the Alexa app will work. The [wiki](https://github.com/custom-components/alexa_media_player/wiki#known-available-sounds) lists what people have confirmed works. Feel free to add more if you see something missing.
