### ISSUE TITLE
Dual Alexa Media integration

### ISSUE THREAD

**Issue by ripvega** [custom-components/alexa_media_player#760]
Home Assistant alerted me to a new integration - Alexa Media Player, which is already integrated.

Please see the screenshot.

Latest versions of both HA and Alexa Media Player
<img width="541" alt="Screenshot 2020-05-31 at 12 12 00" src="https://user-images.githubusercontent.com/42817627/83351105-22c4af00-a339-11ea-942a-8eecace0473d.png">

**Comment by alandtse** [comment]
I don't have any control over the "Discovered" box so I'm not sure there's anything to be done from the custom_component side. Perhaps it sees something in your configuration.yaml which you could try deleting.

**Comment by ripvega** [comment]
Thank you. That pointed me in the right direction. All sorted.
