### ISSUE TITLE
Update for sensor.echo_dot_next_reminder fails: AttributeError: 'float' object has no attribute 'isoweekday'

### ISSUE THREAD

**Issue by drthanwho** [custom-components/alexa_media_player#771]
**Describe the bug**
I don't see any issues in the frontend but my logs get filled with the following log. Is this a known issue? 

**System details**
 - Home-assistant (version): 1.110.4
 - Hassio (Yes/No):  Yes
 - alexa_media  (version from `const.py` or HA startup): v2.8.2
 - alexapy (version from `pip show alexapy` or HA startup): not sure

**Logs**
```
2020-06-07 15:25:05 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.thanasis_dot_next_reminder fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in async_device_update
    await self.async_update()
  File "/config/custom_components/alexa_media/sensor.py", line 353, in async_update
    self._process_raw_notifications()
  File "/config/custom_components/alexa_media/sensor.py", line 166, in _process_raw_notifications
    self._all = list(map(self._update_recurring_alarm, self._all))
  File "/config/custom_components/alexa_media/sensor.py", line 229, in _update_recurring_alarm
    and alarm.isoweekday not in RECURRING_PATTERN_ISO_SET[recurring_pattern]
AttributeError: 'float' object has no attribute 'isoweekday'
```

**Additional context**

**Comment by alandtse** [comment]
Please provide `alexa_media` logs as instructed by the template. There's some strange data in your notifications json probably.

**Comment by drthanwho** [comment]
Sorry about template. Was trying to avoid having to enable debug on the logs. 

I thought I'd restart first in case it would go away but it didn't. And now that I enabled debug I'm still waiting for it to show up.

**Comment by alandtse** [comment]
It's always how it is. ;) It's probably tied to an alarm/timer/reminder you might have set recently. Did any recently get disabled since you last saw the error?

**Comment by drthanwho** [comment]
No not really. I have a reminder on the weekend but that's set up months ago.  I haven't touched any kind of alarms or timers either since that showed up. And even weirdly this is the first time I see that kind of error. I'll just leave debug on overnight and if still nothing I guess I'll just close the issue and reopen it if it shows up again.

**Comment by alandtse** [comment]
Ok, let me know if it pops up again. With the logs on, it'll tell you the exact json data it is processing so if you get the same error again, it'll have the necessary data.
