### ISSUE TITLE
Cannot log in with amazon.es, amazon.fr and amazon.it

### ISSUE THREAD

**Issue by sinclairfr** [custom-components/alexa_media_player#774]
Hi everyone,

**Describe the bug**

I lost both tts and announce features since Hassio & Alexa Media update.
Alson realized I cannot log in with a amazon.fr domain, only amazon.com

**To Reproduce**
Update to the latest HA and HACS Amazon Media component

**Expected behavior**
No more TTS and Announce

**Screenshots**
![image](https://user-images.githubusercontent.com/118417/84269308-5669bb00-ab29-11ea-90c2-4771d1b7bcec.png)

**System details**
 - Home-assistant (version): 0.110.7
 - Hassio : yes
 - alexa_media  v2.8.4

**Logs**

```
2020-06-10 14:47:23 ERROR (MainThread) [alexapy.helpers] alexalogin.login((<alexapy.alexalogin.AlexaLogin object at 0x7f70cc361150>,),}): An error occured accessing AlexaAPI: An exception of type AssertionError occurred. Arguments:
```
.
**_After trying TTS :_**

2020-06-10 14:51:26 DEBUG (MainThread) [custom_components.alexa_media.notify] Announce targets: ['G************XTK'] entities: [<Entity Echo Dot - Study: unavailable>]

2020-06-10 14:51:26 DEBUG (MainThread) [custom_components.alexa_media.notify] Testing item: <Entity Echo Dot - Study: unavailable> against (<Entity Echo Dot - Study: unavailable>, Echo Dot - Study, G************XTK, media_player.echo_dot_study)

2020-06-10 14:51:26 DEBUG (MainThread) [custom_components.alexa_media.notify] Converting: <Entity Echo Dot - Study: unavailable> to (serialnumbers): G090U50990350XTK

2020-06-10 14:51:26 DEBUG (MainThread) [custom_components.alexa_media.notify] Testing item: <Entity Echo Dot - Study: unavailable> against (<Entity Echo Dot  - Kitchen: unavailable>, Echo Dot  - Kitchen, G************6RR, media_player.echo_dot_kitchen)

2020-06-10 14:51:26 DEBUG (MainThread) [custom_components.alexa_media.notify] Testing item: <Entity Echo Dot - Study: unavailable> against (<Entity Everywhere: unavailable>, Everywhere, d****************************483, media_player.everywhere)

2020-06-10 14:51:26 DEBUG (MainThread) [custom_components.alexa_media.notify] Testing item: <Entity Echo Dot - Study: unavailable> against (<Entity Echo Dot - bedroom: unavailable>, Echo Dot - bedroom, G************W6R, media_player.echo_dot_bedroom)

2020-06-10 14:51:26 DEBUG (MainThread) [custom_components.alexa_media.notify] Testing item: <Entity Echo Dot - Study: unavailable> against (<Entity Zoo: unavailable>, Zoo, 1****************************fc8, media_player.zoo)

2020-06-10 14:51:26 DEBUG (MainThread) [custom_components.alexa_media.notify] Testing item: <Entity Echo Dot - Study: unavailable> against (<Entity This Device: standby>, This Device, 5****************************126, media_player.this_device)

2020-06-10 14:51:26 DEBUG (MainThread) [custom_components.alexa_media.notify] Announce targets: ['G************XTK'] entities: [<Entity Echo Dot - Study: unavailable>]

      
**Additional context**
Everything worked fine for a long time before the update.

**Comment by alandtse** [comment]
Please provide the full startup logs. You should scrub them before you post them. The template explains how to get logs. You can dm me on the HA forums or through discord.

Ultimately, you can try renaming your .pickle file and then remove and readd the integration in Config-> Integrations.

**Comment by marioedani** [comment]
Hi, I have the same problem using amazon.it

This is my log:
`2020-06-11 19:46:12 ERROR (MainThread) [alexapy.helpers] alexalogin.login((<alexapy.alexalogin.AlexaLogin object at 0x6a6040d0>,), {'data': {'url': 'amazon.it', 'debug': False, 'scan_interval': 60, 'email': 'marioedani@xxxxxxx.it', 'password': 'xxxxxxxxxxxxxx', 'exclude_devices': '', 'include_devices': ''}}): An error occured accessing AlexaAPI: An exception of type InvalidURL occurred. Arguments:
(URL(''),)`

`2020-06-11 19:46:12 WARNING (MainThread) [custom_components.alexa_media.config_flow] Unknown error: `

I removed integration, but when I re-add it I have the same error as @sinclairfr 

Thank you

**Comment by alesoft73** [comment]
I have the same problem, amazon.it

2020-06-11 23:03:30 ERROR (MainThread) [alexapy.helpers] alexalogin.login((<alexapy.alexalogin.AlexaLogin object at 0x7f8b18ef8c50>,), {'data': {}}): An error occured accessing AlexaAPI: An exception of type InvalidURL occurred. Arguments:
(URL(''),)
2020-06-11 23:03:30 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.14xxxxxxxxxx9872] 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1259, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1294, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/configurator/__init__.py", line 235, in async_handle_service_call
    await self.hass.async_add_job(callback, call.data.get(ATTR_FIELDS, {}))
  File "/config/custom_components/alexa_media/configurator.py", line 28, in configuration_callback
    setup_platform_callback, hass, config_entry, login, callback_data
  File "/config/custom_components/alexa_media/configurator.py", line 177, in setup_platform_callback
    await login.login(data=callback_data)
  File "/usr/local/lib/python3.7/site-packages/alexapy/helpers.py", line 69, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexalogin.py", line 442, in login
    site, data=self._data, headers=self._headers, ssl=self._ssl
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 473, in _request
    ssl=ssl, proxy_headers=proxy_headers, traces=traces)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 285, in __init__
    self.update_host(url)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 339, in update_host
    raise InvalidURL(url)
aiohttp.client_exceptions.InvalidURL
2020-06-11 23:03:33 ERROR (MainThread) [alexapy.helpers] alexalogin.login((<alexapy.alexalogin.AlexaLogin object at 0x7f8b18ef8c50>,), {'data': {}}): An error occured accessing AlexaAPI: An exception of type InvalidURL occurred. Arguments:
(URL(''),)

**Comment by caiosweet** [comment]
I confirm. same problem.

**Comment by alandtse** [comment]
It'd be helpful to get some debug logs of adding the integration from the Configuration menu. Please follow the [wiki](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component)

**Comment by marioedani** [comment]
> It'd be helpful to get some debug logs ...

Hi Alan, I sent you a message on HA forum with detailed log. Hope it helps. Thank you

**Comment by alesoft73** [comment]
> 
> 
> It'd be helpful to get some debug logs of adding the integration from the Configuration menu. Please follow the [wiki](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component)

I have see this error:

**Comment by alesoft73** [comment]
2020-06-12 08:44:52 DEBUG (MainThread) [alexapy.alexalogin] Processing https://www.amazon.it/ap/signin/260-37xx8-53xxx28?ie=UTF8&showRememberMe=true&showRmrMe=1&openid.identity=http://specs.openid.net/auth/2.0/identifier_select&pageId=amzn_dp_project_dee_it&openid.return_to=https://alexa.amazon.it/&prevRID=MBQTJVS4FMG3Y697C6CR&openid.assoc_handle=amzn_dp_project_dee_it&openid.mode=checkid_setup&prepopulatedLoginId=&failedSignInCount=0&showPasswordChecked=false&rememberMe=true&openid.claimed_id=http://specs.openid.net/auth/2.0/identifier_select&email=superman130173@gmail.com&openid.ns=http://specs.openid.net/auth/2.0%C3%97tamp=1591943479xxx00/260-37xx798-53xxx28?ie=UTF8&email=sxxxxxxxxxx@gmail.com
2020-06-12 08:44:52 DEBUG (MainThread) [alexapy.alexalogin] Error page detected:
2020-06-12 08:44:52 DEBUG (MainThread) [alexapy.alexalogin] Found post url to get; forcing get to 
2020-06-12 08:44:52 DEBUG (MainThread) [alexapy.alexalogin] Preparing post to  data: {}
2020-06-12 08:44:52 ERROR (MainThread) [alexapy.helpers] alexalogin.login((<alexapy.alexalogin.AlexaLogin object at 0x7f181fd1a990>,), {'data': {}}): An error occured accessing AlexaAPI: An exception of type InvalidURL occurred. Arguments:
(URL(''),)
2020-06-12 08:44:52 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.xxxxxxxxxxxx1] 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1259, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1294, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/configurator/__init__.py", line 235, in async_handle_service_call
    await self.hass.async_add_job(callback, call.data.get(ATTR_FIELDS, {}))
  File "/config/custom_components/alexa_media/configurator.py", line 28, in configuration_callback
    setup_platform_callback, hass, config_entry, login, callback_data
  File "/config/custom_components/alexa_media/configurator.py", line 177, in setup_platform_callback
    await login.login(data=callback_data)
  File "/usr/local/lib/python3.7/site-packages/alexapy/helpers.py", line 69, in wrapper
    return await func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/alexapy/alexalogin.py", line 442, in login
    site, data=self._data, headers=self._headers, ssl=self._ssl
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 473, in _request
    ssl=ssl, proxy_headers=proxy_headers, traces=traces)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 285, in __init__
    self.update_host(url)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 339, in update_host
    raise InvalidURL(url)
aiohttp.client_exceptions.InvalidURL

**Comment by diazdeespada** [comment]
I have the same problem with amazon.es

**Comment by jgyoldi** [comment]
Hello. Same issue for me with amazon.es

**Comment by CiquattroFPV** [comment]
try to do some Host reboot and try to add the integration.. it will work

**Comment by alesoft73** [comment]
Nothing the same error in debug

**Comment by sinclairfr** [comment]
Same here. Tried all : repairing the supervisor, rebooting, hard delete the custom_components folder, downgrading to an earlier version of Alexa_media in HACS and git cloning the project.
All failed.
I can log in with amazon.com, my 3 echo dots are found and added to HA but TTS and announce do not work.

**Comment by ricargr** [comment]
Confirmed, same problem here with amazon.es

**Comment by andrea-mattioli** [comment]
me too with url amazon.it:
alexalogin.login((<alexapy.alexalogin.AlexaLogin object at 0xffff8aa2cc10>,), {'data': {}}): An error occured accessing AlexaAPI: An exception of type InvalidURL occurred. Arguments: (URL(''),)

**Comment by AngelofromTurin** [comment]
same here for amazon.it 
last ha version
last alexa media server component

**Comment by alandtse** [comment]
It's looking like the cookies are not being saved because Amazon is sending both a max-age and an expires. The expires is in the past. It looks like the browser behavior is to use max-age. https://mrcoles.com/blog/cookies-max-age-vs-expires/#:~:text=Quick%20Answer%3A,this%2C%20it's%20no%20longer%202009)

**Comment by alandtse** [comment]
Please check your system clocks are accurate. I am seeing in the logs that Amazon is providing a cookie that is set to expire in the past. If your clocks are wrong, this may result in the cookie immediately expiring and leading the component to an error page.

**Comment by AngelofromTurin** [comment]
The time its right , my time its utc +2 ,

**Comment by ricargr** [comment]
Same here, time right utc+2 and the problem persist.  Thanks alan for your comment

**Comment by brinzlee** [comment]
Exactly the same issue here in the uk.....Amazon.co.uk.....I deleted Alexa Media Player from HACS and now can't find it in the HACS store has it been taken down

**Comment by drako86** [comment]
Same error ... Amazon.it
![5EF67189-566F-4EF2-8C9E-C55C1AF69963](https://user-images.githubusercontent.com/54599925/84563907-4a673e80-ad5f-11ea-9799-116d687973e4.jpeg)

**Comment by maxalbani** [comment]
The same for me. The integration ends successfully only with amazon.com, but I need the IT domain.
Is there any news for the resolution?

**Comment by brinzlee** [comment]
I deleted mine from HACS reinstalled...refreshed the cache on the integrations page.....It asked for a captcha code then a 2fa code.....and now it is working again....weird

**Comment by maxalbani** [comment]
I also tried to reinstall, clear the cache, etc etc ... but it still doesn't work with the IT domain

**Comment by alandtse** [comment]
It's looking like Amazon changed something in it's cookie response recently that breaks one of the underlying aiohttp library's cookie management. Even if I confirm it, it may take a while to actually fix it in the underlying library.

**Comment by sinclairfr** [comment]
> I also tried to reinstall, clear the cache, etc etc ... but it still doesn't work with the IT domain

I did the same. No Improvement.

**Comment by alandtse** [comment]
All, I found the bug's cause and will see if I can resolve it although it honestly may not be a quick fix given it's in a lower level library. 

I'll also clean up the thread. If you have a "me too" post, please refrain from adding it so it doesn't explode the thread. Please just +1 someone who has mentioned your domain with the issue.
 
I don't think there will be any workaround but if someone finds one, please feel free to post.

**Comment by mfabiani53** [comment]
+1 with amazon.it domain.
I am having this in the notification bar:

![Schermata 2020-06-13 alle 15 57 08](https://user-images.githubusercontent.com/37701688/84570577-a6958700-ad8e-11ea-8a0d-6d756e8944a4.png)

Then i have this:

![Schermata 2020-06-13 alle 15 57 22](https://user-images.githubusercontent.com/37701688/84570589-af865880-ad8e-11ea-9cdb-9dd7d96fa4dd.png)

But when i click on it i get this error:

```
Fallita chiamata a servizio configurator/configure
```
Is it the same issue all is having?

**Comment by Muyayo22** [comment]
+1 with amazon.es domain.

**Comment by KennethLavrsen** [comment]
+1 for plain amazon.com

**Comment by Sergiio** [comment]
+1 with amazon.es domain

**Comment by Pinky-bit** [comment]
+1 with amazon.it domain

**Comment by tbkon3** [comment]
+1 with amazon.it domain

**Comment by antimix** [comment]
I am sure this depend to the new user authentication method active in Amazon since a week.
It requires: email and password as usual, but then instead of display the page, it comes back with a NEW authentication dialog, with again a password request AND a CAPTCHA to solve (and an "I'm not a Robot" sign)
This break all the Alexa player python Amazon login logic, and it should be rewritten to overcome the captcha. Also the "I'm not a robot" may implicate Amazon policy infringement, if the login is performed by a script and not a human.

**Comment by trusky77** [comment]
+1 Amazon.es

**Comment by chemelli74** [comment]
> I am sure this depend to the new user authentication method active in Amazon since a week.
> It requires: email and password as usual, but then instead of display the page, it comes back with a NEW authentication dialog, with again a password request AND a CAPTCHA to solve (and an "I'm not a Robot" sign)
> This break all the Alexa player python Amazon login logic, and it should be rewritten to overcome the captcha. Also the "I'm not a robot" may implicate Amazon policy infringement, if the login is performed by a script and not a human.

In order to try to solve another issue, I noticed that there is an official API for 3rd party devices:
https://github.com/custom-components/alexa_media_player/issues/637#issuecomment-639283396

My bes is it will solve this case as well.

Simone

**Comment by alandtse** [comment]
Need testers to try a potential fix. You will need to modify your alexapy using this [PR](https://gitlab.com/keatontaylor/alexapy/-/merge_requests/159). Please only do this if you understand how to do it as I probably won't have time to help you with the basics and with reverting it afterward.

Again, use the emoticon for thumbs up :thumbsup: if you have a me too post. I am trying to keep this organized.

**Comment by alandtse** [comment]
> I am sure this depend to the new user authentication method active in Amazon since a week.
> It requires: email and password as usual, but then instead of display the page, it comes back with a NEW authentication dialog, with again a password request AND a CAPTCHA to solve (and an "I'm not a Robot" sign)

It may be related but the new page isn't what's causing the reported errors. We already handled a recent addition of the anti-automation page like 3 weeks ago.

> This break all the Alexa player python Amazon login logic, and it should be rewritten to overcome the captcha. Also the "I'm not a robot" may implicate Amazon policy infringement, if the login is performed by a script and not a human.

The script isn't doing anything automated when it comes to login. It's converting the page to what HA can show so a human is in fact solving all the steps. This is why if Amazon adds a new page, I have to see the page to figure out how to convert it to HA. Again, the root cause for what's reported isn't a new login page but the fact Amazon is sending multiple `Set-Cookie` requests with the same name which breaks the underlying aiohttp library since it goes against the relevant [RFC](https://tools.ietf.org/html/rfc6265#section-4.1.1).

> In order to try to solve another issue, I noticed that there is an official API for 3rd party devices:

That requires a different set of APIs then this component uses so will not be helpful. As soon as Amazon exposes an oauth for the alexa pages we use, this will greatly simplify how we login.

**Comment by chemelli74** [comment]
> Need testers to try a potential fix. You will need to modify your alexapy using this [PR](https://gitlab.com/keatontaylor/alexapy/-/merge_requests/159). 

Instructions used on my docker test container:

```
docker exec -it <container name> /bin/bash
cd /usr/local/lib/python3.7/site-packages/alexapy
cp alexalogin.py alexalogin.old
curl https://gitlab.com/keatontaylor/alexapy/-/raw/43514340eda667615bd80bb047a98eeea6419dc3/alexapy/alexalogin.py --output alexalogin.py
rm -rf __pycache__/
exit

```

Then after HA full reboot, I get stuck on the following request:

![image](https://user-images.githubusercontent.com/57354320/84591563-ce90f300-ae3f-11ea-9c45-2e3a725efed8.png)

When I click "configure" it asks for "begin" and then again back to the notification in a loop.

Simone

**Comment by chemelli74** [comment]
> > In order to try to solve another issue, I noticed that there is an official API for 3rd party devices:
> 
> That requires a different set of APIs then this component uses so will not be helpful.

Very true, but this is the only official way to access Alexa for 3rd party.
So maybe you can consider switching to those set of API in the near future.

Simone

**Comment by ollo69** [comment]
> Need testers to try a potential fix. You will need to modify your alexapy using this [PR](https://gitlab.com/keatontaylor/alexapy/-/merge_requests/159). 

Tried this PR modifing my alexapy but doesn't solve for me, same result described by @chemelli74.

**Comment by genex89** [comment]
> +1 with amazon.it domain.
> I am having this in the notification bar:
> 
> ![Schermata 2020-06-13 alle 15 57 08](https://user-images.githubusercontent.com/37701688/84570577-a6958700-ad8e-11ea-8a0d-6d756e8944a4.png)
> 
> Then i have this:
> 
> ![Schermata 2020-06-13 alle 15 57 22](https://user-images.githubusercontent.com/37701688/84570589-af865880-ad8e-11ea-9cdb-9dd7d96fa4dd.png)
> 
> But when i click on it i get this error:
> 
> ```
> Fallita chiamata a servizio configurator/configure
> ```
> 
> Is it the same issue all is having?

The same for me

**Comment by alandtse** [comment]
Thanks. Please try this fix.  It is a much more involved [PR](https://gitlab.com/keatontaylor/alexapy/-/merge_requests/160) but fixes it on my test systems. Please test and report back. As soon as I get a confirmation form someone in region, I can push it to the main branch.

**Comment by somar05** [comment]
> Thanks. Please try this fix. It is a much more involved PR but fixes it on my test systems. Please test and report back. As soon as I get a confirmation from someone in region, I can push it to the main branch.

I'm lost because not sure where put the files. I have copied (overwrite) them into custom components/alexa_media, and try to test the PR throught integration page. Sorry if is not the correct procedure to test. Anyway, I receive this error (amazon.es domain):

```
Source: custom_components/alexa_media/config_flow.py:186
First occurred: 9:04:39 (1 occurrences)
Last logged: 9:04:39

alexalogin.login((<alexapy.alexalogin.AlexaLogin object at 0x66a325d0>,), {'data': {'email': 'xxxx@gmail.com', 'password': 'xxxx', 'url': 'amazon.es', 'debug': False, 'scan_interval': 60, 'include_devices': '', 'exclude_devices': ''}}): An error occured accessing AlexaAPI: An exception of type InvalidURL occurred. Arguments: (URL(''),)
```

**Comment by CelestinoMarini** [comment]
> Thanks. Please try this fix. It is a much more involved [PR](https://gitlab.com/keatontaylor/alexapy/-/merge_requests/160) but fixes it on my test systems. Please test and report back. As soon as I get a confirmation from someone in region, I can push it to the main branch.

Can you please explain how we have to do to test using Hassio?. Thanks for your precious support

**Comment by nogardris** [comment]
+1 for plain amazon.es

**Comment by CiquattroFPV** [comment]
> > Thanks. Please try this fix. It is a much more involved [PR](https://gitlab.com/keatontaylor/alexapy/-/merge_requests/160) but fixes it on my test systems. Please test and report back. As soon as I get a confirmation from someone in region, I can push it to the main branch.
> 
> Can you please explain how we have to do to test using Hassio?. Thanks for your precious support

you have to clone the PR and then copy the file into the custom component folder

**Comment by CelestinoMarini** [comment]
> > > Thanks. Please try this fix. It is a much more involved [PR](https://gitlab.com/keatontaylor/alexapy/-/merge_requests/160) but fixes it on my test systems. Please test and report back. As soon as I get a confirmation from someone in region, I can push it to the main branch.
> > 
> > 
> > Can you please explain how we have to do to test using Hassio?. Thanks for your precious support
> 
> you have to clone the PR and then copy the file into the custom component folder then restart

I need a clarification, it's not clear to me if I have to copy the PR into custom components/alexa_media or to dedicated folder. Thanks

**Comment by CiquattroFPV** [comment]
> > > > Thanks. Please try this fix. It is a much more involved [PR](https://gitlab.com/keatontaylor/alexapy/-/merge_requests/160) but fixes it on my test systems. Please test and report back. As soon as I get a confirmation from someone in region, I can push it to the main branch.
> > > 
> > > 
> > > Can you please explain how we have to do to test using Hassio?. Thanks for your precious support
> > 
> > 
> > you have to clone the PR and then copy the file into the custom component folder then restart
> 
> I need a clarification, it's not clear to me if I have to copy the PR into custom components/alexa_media or to dedicated folder. Thanks

1. Go there and download/clone the repository
https://gitlab.com/alandtse/alexapy/-/tree/local_aiohttp
2.  Extract in a folder 
3. Replace the content of folder custom_compontent/alexa_media with the extracted file of the new repository
4. Restart

**Comment by somar05** [comment]
Another try with the PR. Maybe something missing related with aiohttp:

```
Logger: homeassistant.config_entries
Source: config_entries.py:526
First occurred: 17:28:17 (1 occurrences)
Last logged: 17:28:17

Error occurred loading configuration flow for integration alexa_media: No module named 'alexapy.aiohttp'
```

**Comment by KennethLavrsen** [comment]
> > > > > Thanks. Please try this fix. ..
> 
> 1. Go there and download/clone the repository
>    https://gitlab.com/alandtse/alexapy/-/tree/local_aiohttp
> 2. Extract in a folder
> 3. Replace the content of folder custom_compontent/alexa_media with the extracted file of the new repository
> 4. Restart

If someone follows this they will delete the entire custom component directory and replace it by a dependency. This is surely not the correct instruction.
I cannot understand why we are asked to try a PR and then give no clear instruction how to apply it on a Home Assistant installed the most standard ways. It is only few experts in Docker than know how to do this and I for sure have no clue. But I can tell that the above is not correct

**Comment by alandtse** [comment]
Please note if you don't know how to test a PR you should not try as there are others on the thread who do. I already stated that once but I can state it again in the message.

**Comment by bf69** [comment]
seguo..

**Comment by alandtse** [comment]
Upgrade to 2.8.6 to resolve.

**Comment by jgyoldi** [comment]
Cheers! It works with 2.8.6 and HA 0.111.3.
Just one question, what is the difference beetwen identification 0 and 1 ? I have choosen 0 and it has sent me a SMS with a validation code.

**Comment by nogardris** [comment]
It doesn't work for me, I have version 0.111.3 and alex media 2.8.6

Domain: amazon.es

**Comment by somar05** [comment]
> It doesn't work for me, I have version 0.111.3 and alex media 2.8.6
> 
> Domain: amazon.es

For me it's working: domain amazon.es. Have you tried uninstall integration (integration page) and Hacs, and then install, reboot and add integration again?

**Comment by AngelofromTurin** [comment]
Working for me , try to remove in “.storage” directory the “alexa_media.xxxxxxx.pickle” file and restart :)

**Comment by Pinky-bit** [comment]
It works with 2.8.6 and HA 0.111.3
Domain: amazon.it

**Comment by maxalbani** [comment]
It works for me too, domain .it
Thanks!

**Comment by Niconath** [comment]
> Pour moi, essayez de supprimer dans le répertoire «.storage» le fichier «alexa_media.xxxxxxx.pickle» et redémarrez :)

Thanks to you, I did as you said it would work for me.

**Comment by ollo69** [comment]
It works also for me (Amazon.it)
Thanks

**Comment by laccio85** [comment]
Hi to all!!
after re-integration the HACS component I recevived this error and still unable to integrate Alexa into HA again:


2020-06-16 16:09:44 ERROR (MainThread) [alexapy.helpers] alexalogin.login((<alexapy.alexalogin.AlexaLogin object at 0x7f6af72590>,), {'data': {'email': 'èlamiamail@gmail.com (èlamiamail@gmail.com)', 'password': 'COLCAVOLOCHETELADICO', 'url': 'amazon.it', 'debug': False, 'exclude_devices': 'this device', 'scan_interval': 60, 'include_devices': ''}}): An error occured accessing AlexaAPI: An exception of type ContentTypeError occurred. Arguments:
(RequestInfo(url=URL('https://www.amazon.it/ap/signin?

**Comment by nogardris** [comment]
> Hi to all!!
> after re-integration the HACS component I recevived this error and still unable to integrate Alexa into HA again:
> 
> 2020-06-16 16:09:44 ERROR (MainThread) [alexapy.helpers] alexalogin.login((<alexapy.alexalogin.AlexaLogin object at 0x7f6af72590>,), {'data': {'email': 'è[lamiamail@gmail.com](mailto:lamiamail@gmail.com) (è[lamiamail@gmail.com](mailto:lamiamail@gmail.com))', 'password': 'COLCAVOLOCHETELADICO', 'url': 'amazon.it', 'debug': False, 'exclude_devices': 'this device', 'scan_interval': 60, 'include_devices': ''}}): An error occured accessing AlexaAPI: An exception of type ContentTypeError occurred. Arguments:
> (RequestInfo(url=URL('https://www.amazon.it/ap/signin?

same error for me

**Comment by somar05** [comment]
@laccio85  you should edit your post. Hide sensitive info

**Comment by somar05** [comment]
@nogardris @laccio85 have you rebooted Hassio after reinstall?
@nogardris I think you have to hide same sensitive info in your reference to @laccio85 post

**Comment by nogardris** [comment]
> @laccio85 you should edit your post. Hide sensitive info

Yes, a lot times.

**Comment by somar05** [comment]
> Working for me , try to remove in “.storage” directory the “alexa_media.xxxxxxx.pickle” file and restart :)

@nogardris and this one?

**Comment by laccio85** [comment]
> @nogardris @laccio85 have you rebooted Hassio after reinstall?
> @nogardris I think you have to hide same sensitive info in your reference to @laccio85 post

Delete pickle file in storage folder, delete integration, delete folder Alexa_media in custom component, same error

**Comment by alandtse** [comment]
@laccio85 please change your Amazon password. You just posted if publicly and it's in people's emails now. I've deleted it in the history, but you should change it.

**Comment by laccio85** [comment]
> @laccio85 please change your Amazon password. You just posted if publicly and it's in people's emails now. I've deleted it in the history, but you should change it.

Many thanks but not real Amazon credential..

**Comment by user514** [comment]
> Upgrade to 2.8.6 to resolve.

2.8.6... fixed it for me on amazon.es.

**Comment by AngelofromTurin** [comment]
@alandtse for my Hassio on raspy4 it’s perfect but on Hassio on raspy3b+ dont work ... its possibile something different on home assistant’s software dependecy for raspy3b+ ? 
Last ha version
Last alexa media player version

**Comment by laccio85** [comment]
Hi to All!!
The latest tests:
deleted the integration, the component folder alexa_media and the pickle file.
Connected the Amazon account from the same lan as HA:
- Logoff account from the Amazon website
- changed Amazon account password
- installed new Alexa Media integration via HACS
- added integration in configuration.yaml
- after a complete restart of HA the new devices were discovered
- guided configuration of the Alexa component performed

everything was so integrated again without further problems!

**Comment by nogardris** [comment]
> Hi to All!!
> The latest tests:
> deleted the integration, the component folder alexa_media and the pickle file.
> Connected the Amazon account from the same lan as HA:
> 
> * Logoff account from the Amazon website
> * changed Amazon account password
> * installed new Alexa Media integration via HACS
> * added integration in configuration.yaml
> * after a complete restart of HA the new devices were discovered
> * guided configuration of the Alexa component performed
> 
> everything was so integrated again without further problems!

Works for me. Thank you. Domain: amazon.es

**Comment by diazdeespada** [comment]
Work for me. Best regards

**Comment by genex89** [comment]
Work for me. Thanks 😊

Il mer 17 giu 2020, 15:27 diazdeespada <notifications@github.com> ha
scritto:

**Comment by alandtse** [comment]
> @alandtse for my Hassio on raspy4 it’s perfect but on Hassio on raspy3b+ dont work ... its possibile something different on home assistant’s software dependecy for raspy3b+ ?

@AngelofromTurin Yes. Hard to debug it though. See for example #764 where someone's RPI4 has strange connection timeout errors that their RPI3 doesn't.
