### ISSUE TITLE
Alexa play media not working in everywhere group

### ISSUE THREAD

**Issue by Wibias** [custom-components/alexa_media_player#775]
Hey!

So once again playing music in the everywhere group via

```
{
    "media_content_type": "TUNEIN",
    "media_content_id": "Radio Hamburg in uberall Gruppe"
}
```

isn't working. I'm just getting "I am not sure" from Alexa(Hope thats the right translation since I am using german Alexa).
I am on the newest Alexa Media Player Verison and Home Assistant Version 0.110.7.

![grafik](https://user-images.githubusercontent.com/37517432/84275824-d3992e00-ab31-11ea-8e69-efc0ee3695ae.png)

**Comment by alandtse** [comment]
Did this work before for you? This is likely an Amazon error as we haven't changed that part of the code recently.

**Comment by Wibias** [comment]
Yea it worked before. And I didn't changed a thing since then. The last time it stopped working the solution was changing "Überall" to "Uberall". Not sure what could be a fix to the problem this time..

**Comment by alandtse** [comment]
I'll leave this up in case someone figures it out, but not much we can do here.

**Comment by Wibias** [comment]
Fixed itself.

**Comment by Chekedaudau** [comment]
@Wibias How Did you fixed it? I have the same problem since yesterday and didn't find a fix yet...

**Comment by Wibias** [comment]
Cant really help you there. Didnt really do anything to fix it expect reinstalling Alexa Media Player. That in itself didn't fix it. Just after like 2 days after reinstalling it it worked again. Now on the newest Alexa Media Player version and its still working just fine. Still using the same stuff as in the picture above.

**Comment by Wibias** [comment]
So its not working once again. So I am reopening this.

**Comment by Wibias** [comment]
So I fixed it by removing the "Gruppe" in "media_content_id": "Radio Hamburg in überall Gruppe". In case of other languages try to remove "group" from the media_content_id.
