### ISSUE TITLE
clarification on white space after comma for listing devices

### ISSUE THREAD

**Issue by flashbacck** [custom-components/alexa_media_player#780]
This is very minor, but confused me for a good 30 minutes. During the setup of the integration, where you can list devices you would like included or excluded, the white space after a comma is also included in the device name. I don't think any behavior needs to be changed since white spaces can be included in a device name, but a note about white spaces where it mentions separating the list by commas would be useful for future users.
Thanks

**Comment by alandtse** [comment]
Thanks. Please feel free to update the wiki to make that clear. It's open for edits. At some point in the future I may add something that will remove that requirement but I've been focusing on other issues.
