### ISSUE TITLE
Can't integrate Alexa Media Player

### ISSUE THREAD

**Issue by Gdii** [custom-components/alexa_media_player#788]
Hello,
for some days I have been unable to integrate Alexa media palyer into my Home assistant, when I try to enter my credentials, (which I am sure of, and that they work perfectly on the amazon.it website), does not log in, and writes me in red "Unknown error, please report log info ", please, help !!

my HA is
Home Assistant
0.111.2
the log:
Unknown error:
10:24:35 - Alexa Media Player (WARNING)
alexalogin.login ((<alexapy.alexalogin.AlexaLogin object at 0x7f8e639190>,), {'data': {'email': 'XXXXXXX@gmail.com', 'password': 'XXXXXXXXX', 'url': 'amazon .it ',' debug ': False,' scan_interval ': 60,' include_devices': '', 'exclude_devices':' '}}): An error occured accessing AlexaAPI: An exception of type InvalidURL occurred. Arguments: (URL (''),)
10:24:35 - custom_components / alexa_media / config_flow.py (ERROR)

**Comment by alandtse** [comment]
Please make sure you're using 2.8.6. The log indicates you're probably not. Also please fill out the template completely.

**Comment by SuperNeo84** [comment]
I've the same issue, since when i upgraded my Hassio to 111.3.

Home Assistant version: v. 111.3
Alexa Media Player  Custom components: v. 2.8.6

i tried to remove, the integration and custom component from HACS, and i reinstalled it. but when i try to create the integration and i put in the fields

My email account of amazon
My Password
amazon.it

i have this error

`2020-06-17 08:38:58 ERROR (MainThread) [alexapy.helpers] alexalogin.login((<alexapy.alexalogin.AlexaLogin object at 0x7f5def27d0>,)......

2020-06-17 08:38:58 WARNING (MainThread) [custom_components.alexa_media.config_flow] Unknown error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html;charset=utf-8', url=URL('.......')
`

Any Ideas?

**Comment by nerdefierodiesserlo** [comment]
I had the same error...It was like during the login something went wrong...so i tried to login on Amazon website and Amazon ask me to change my password (i really don't know why)...that was the problem...i I followed the steps to change the password and then i added Alexa media player with the new credentials...that worked for me

**Comment by theHasp** [comment]
Same here

I had a working installation which suddenly stopped working....
I noticed that my echo could not been found ... tried to do the configuration process again and failed.
Then I reinstalled alexa_media via HACs
And tried to add the echo again and it is failing.

I can not proceed at all withe amazon.de url ... none works
Error is:

Logger: custom_components.alexa_media.config_flow
Source: custom_components/alexa_media/config_flow.py:191
Integration: alexa_media (documentation)
First occurred: 17:13:11 (6 occurrences)
Last logged: 17:35:52

-     Unknown error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html;charset=utf-8', url=URL('https://www.amazon.de/ap/signin?showRmrMe=1&openid.return_to=https://alexa.amazon.de/api/bootstrap&openid.identity=http://specs.openid.net/auth/2.0/identifier_select&openid.assoc_handle=amzn_dp_project_dee_de&openid.mode=checkid_setup&openid.claimed_id=http://specs.openid.net/auth/2.0/identifier_select&openid.ns=http://specs.openid.net/auth/2.0&')

-     Unknown error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html;charset=utf-8', url=URL('https://www.amazon.com/ap/signin?showRmrMe=1&openid.return_to=https://alexa.amazon.com/api/bootstrap&openid.identity=http://specs.openid.net/auth/2.0/identifier_select&openid.assoc_handle=amzn_dp_project_dee&openid.mode=checkid_setup&openid.claimed_id=http://specs.openid.net/auth/2.0/identifier_select&openid.ns=http://specs.openid.net/auth/2.0&')

**Comment by alandtse** [comment]
Again if you want help, provide logs per the template. I can't help based on the information so far.

**Comment by theHasp** [comment]
> Again if you want help, provide logs per the template. I can't help based on the information so far.

ALANDTSE Which logs do you need?

**Comment by theHasp** [comment]
Something what could be related is, as it happens at the same time

`Logger: homeassistant.core
Source: core.py:156
First occurred: 17:17:58 (6 occurrences)
Last logged: 17:35:58

    Error doing job: Unclosed client session
    Error doing job: Unclosed connector
`

**Comment by alandtse** [comment]
> ALANDTSE Which logs do you need? I updated as much as I could above

Logs as described [here](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). As you noted, you have to scrub info out before posting.

**Comment by theHasp** [comment]
> > ALANDTSE Which logs do you need? I updated as much as I could above
> 
> Logs as described [here](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). As you noted, you have to scrub info out before posting.

Thanks will do ...

**Comment by alandtse** [comment]
One potential fix for those who are comfortable is to modify [alexalogin line 278](https://gitlab.com/keatontaylor/alexapy/-/blob/dev/alexapy/alexalogin.py#L278).
From:
```python
        from aiohttp.client_exceptions import ContentTypeError
```
To:
```python
        from alexapy.aiohttp.client_exceptions import ContentTypeError
```

**Comment by pizzakid25** [comment]
> One potential fix for those who are comfortable is to modify [alexalogin line 278](https://gitlab.com/keatontaylor/alexapy/-/blob/dev/alexapy/alexalogin.py#L278).
> From:
> 
> ```python
>         from aiohttp.client_exceptions import ContentTypeError
> ```
> 
> To:
> 
> ```python
>         from alexapy.aiohttp.client_exceptions import ContentTypeError
> ```

@alandtse Do you know where alexalogin.py is located?

**Comment by MYeager1967** [comment]
I'm getting a message from Amazon that I have to click a link the send me in a text. I'm doing that and them clicking the submit button on the screen that it's been done, but the integration won't finish setting up. Any suggestions?
