### ISSUE TITLE
No captcha

### ISSUE THREAD

**Issue by danmed** [custom-components/alexa_media_player#790]
**Describe the bug**
I've got a notification to "Click button to configure Alexa Media Player - Captcha -" however i don't see a captch to enter..

![image](https://user-images.githubusercontent.com/3878490/85184887-80d61980-b289-11ea-852e-503be260e8c5.png)

**To Reproduce**
Be running HA 0.111.4 and latest integration.

**Expected behavior**
Captcha should be available to enter

**Screenshots**

**System details**
 - Home-assistant (version):  0.111.4
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup):

**Comment by alandtse** [comment]
Enter anything. Please search before asking as this has been asked multiple times.
