### ISSUE TITLE
help: triggering a skill

### ISSUE THREAD

**Issue by jactora** [custom-components/alexa_media_player#791]
i use this for sending tts message from HA to Alexa.
but i want to trigger a skill.
skill is 
https://alexa.amazon.co.uk/spa/index.html#skills/dp/B07H3LFKW1/?ref=skill_dsk_skb_ys
is skill id - B07H3LFKW1 ?
i want this skill to be triggered when HA meets a condition.
eg. when xiaomi room temp is 15 deg, i want my climote heating to be switched on.
i usually tell alexa - Alexa ask climote to turn on the heating
how can i do this from home assistant using this alexa media player?
can i send a message to alexa to trigger a skill?
i saw this link but still dont know how to send the exact command to switch on heating
https://github.com/custom-components/alexa_media_player/wiki#triggering-a-skill-versions--270

**Comment by alandtse** [comment]
Questions like this should be on the [community forum](https://community.home-assistant.io/t/echo-devices-alexa-as-media-player-testers-needed/58639/4035). GitHub is more for technical issues. I can leave this open for a week or so but I don't think there's enough traffic here that you'll get an answer.

**Comment by jactora** [comment]
sorry. thanks. i have put a request on forum, reddit too.

**Comment by alandtse** [comment]
Closing since moved to forum.
