### ISSUE TITLE
List of Compatible sounds - Questions - Potential sounds / available sounds

### ISSUE THREAD

**Issue by VarenDerpsAround** [custom-components/alexa_media_player#793]
Hello, I currently use my alexa's for several automation's involving sounds that are played to signify certain events in my house. I love that alexa has 100's of sounds to choose from in it's api, but I was curious as to why the majority of the sounds that are in the list on amazon's website ("potentially working sounds") is so much different then the sounds available inside home assistant automation's with this integration.

I'd love to be able to run through all the available sounds to pick out the perfect one to creep out guests, or notify when it's time to give my cat her meds... and so on and so forth. 

Sorry if this seems brash, I just was curious as to why the available sounds seem to far undershadow the potentially available ones. 

I'm willing to bet if I where to implement my own alexa media player api integration this wouldn't be an issue? or maybe it's just how home assisstant / the integration talks to alexa that is beansing it up?

**Comment by alandtse** [comment]
We can only play what the app can play. The published API of sounds is intended for skills. You're more than welcome to add any you can confirm are working to the [Wiki](https://github.com/custom-components/alexa_media_player/wiki#known-available-sounds).

As to the reason why Amazon has restricted the sounds in the App, you'd have to ask Amazon.

**Comment by VarenDerpsAround** [comment]
Thanks, I kinda figured it was something app/skill/api restriction related. I'll make a list of the additional ones I have one, I have a couple and submit a pr. Thanks again for clearing it up.

**Comment by alandtse** [comment]
Thanks. No need to submit PRs to the wiki. It's world editable so feel free to just add it as you find stuff out. It's a team effort to document what we can access. ;)
