### ISSUE TITLE
Unclosed client session & Unclosed connector

### ISSUE THREAD

**Issue by stvnmbr1** [custom-components/alexa_media_player#794]
Add-on just stopped working
Home Assistant 0.111.4 supervised on debian host
addon 2.8.6

tried deleting from HACS & integrations, reboot, delete pickle & file in custom_components root, reboot, reinstall through HACS, login

 Unknown error, please report log info 

    Error doing job: Unclosed client session
    Error doing job: Unclosed connecton

also ended all open sessions through amazon.com and retried..

**Comment by wes1993** [comment]
Try to reboot HA instance after you have inserted the 2FA in HA (if you have one)

**Comment by stvnmbr1** [comment]
i can't get to the point it even asks anything. I enter login data, press next/save -> unknown error

**Comment by alandtse** [comment]
Please fill out the template.

**Comment by willyk0** [comment]
Same problem here, "unclosed client session" and "unclossed connection". It keeped me asking for a captcha and after rebooting it never worked again. I deleted the integration and tried to re-add again, it says "unknown error".

Hass 0.111.2 running under debian 10 with docker.

At the console, the errors are (I omitted some URLS, cookies and more):

An error occured accessing AlexaAPI: An exception of type ContentTypeError occurred.

2020-06-21 21:52:17 WARNING (MainThread) [custom_components.alexa_media.config_flow] Unknown error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html;charset=utf-8', url=URL(....)

**Comment by stvnmbr1** [comment]
lol... same info though..

**Describe the bug**
Addon just stopped working, can't add it back in any way
add through hacs, install in integrations -> login -> FAILED with unknown error..

**To Reproduce**
Steps to reproduce the behavior:
open hassio
(extra: install addon and try to login to amazon account, shows instant unknown error)

**Expected behavior**
find working alexa media player -> instead shows entity not found
(extra: get capchta)

**System details**
 - Home-assistant (version): Home Assistant 0.111.4 supervised on debian host
 - Hassio (Yes/No): YES
 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
Error doing job: Unclosed client session
Error doing job: Unclosed connecton

[custom_components.alexa_media.config_flow] Unknown error: 0, message='Attempt to decode JSON with unexpected mimetype: text/html;charset=utf-8', url=URL(....)

**Additional context**

No updates or whatever were executed before addon stopped working..

tried deleting from HACS & integrations, reboot, delete pickle & file in custom_components root, reboot, reinstall through HACS, login
also ended all open sessions through amazon.com and retried..

**Comment by stvnmbr1** [comment]
![afbeelding](https://user-images.githubusercontent.com/9010189/85294314-c455a100-b49e-11ea-8dee-0b7af144f54a.png)

**Comment by stvnmbr1** [comment]
The same way  it stopped working, it just started working -_-

after the 24th time of deleting everything, rebooting, install, reboot, ..........
i got my capchta and 2fa back..

don't know what changed as i've been doing this for the past 2 days to get it working again..

**Comment by alandtse** [comment]
I'll close this then. Without debug logs showing what is happening before the error, there is no effective way to figure out what's wrong.  It could be internet connectivity issues, it could be Amazon being down.
