### ISSUE TITLE
Question: Is Alexa Media Player emulating Google Chrome Browser?

### ISSUE THREAD

**Issue by monotonus** [custom-components/alexa_media_player#795]
Today I received a account warning from Amazon which has more or less the same timestamp as some home assistant log entries belonging to alexa media player.

Date 21. Juni 2020 09:07
Device Google Chrome for Windows (Desktop)
Location Hesse/Germany

This is my location indeed.

In the HA log I see:

Protokolldetails ( WARNING )
Logger: alexapy.alexawebsocket
Source: custom_components/alexa_media/__init__.py:587
First occurred: 9:07:48 (1 occurrences)
Last logged: 9:07:48

Websocket is missing ubid-main and ubid-acbde cookies; please report this if anything isn't working.

Logger: aiohttp.websocket
Source: custom_components/alexa_media/__init__.py:590
First occurred: 9:07:49 (4 occurrences)
Last logged: 9:07:49

websocket connection is closing.

And further I see problems with updating my devices:

Logger: alexapy.helpers
Source: custom_components/alexa_media/media_player.py:545
First occurred: 9:07:48 (78 occurrences)
Last logged: 10:04:10

alexaapi.get_state((<alexapy.alexaapi.AlexaAPI object at 0x7f03018d0f90>,), {}): A login error occured: An exception of type JSONDecodeError occurred. Arguments: ('Expecting value: line 1 column 1 (char 0)',)
alexaapi.get_state((<alexapy.alexaapi.AlexaAPI object at 0x7f0302bb9f50>,), {}): An error occured accessing AlexaAPI: An exception of type RuntimeError occurred. Arguments: ('Session is closed',)
alexaapi.get_state((<alexapy.alexaapi.AlexaAPI object at 0x7f03018d0f90>,), {}): An error occured accessing AlexaAPI: An exception of type RuntimeError occurred. Arguments: ('Session is closed',)
alexaapi.get_state((<alexapy.alexaapi.AlexaAPI object at 0x7f03018c8d50>,), {}): An error occured accessing AlexaAPI: An exception of type RuntimeError occurred. Arguments: ('Session is closed',)
alexaapi.get_state((<alexapy.alexaapi.AlexaAPI object at 0x7f03018c8d10>,), {}): An error occured accessing AlexaAPI: An exception of type RuntimeError occurred. Arguments: ('Session is closed',)

I haven't blocked the login yet or changed my password. I wanted to ensure if it is really the Google chrome desktop browser which I'm not using by myself.

**Comment by alandtse** [comment]
Yes.
