### ISSUE TITLE
Manifest.json needs the requirements version bumped to 1.10.4

### ISSUE THREAD

**Issue by ransom3910** [custom-components/alexa_media_player#800]
In the manifest.json file requirements is set to "requirements": ["alexapy==1.10.3"].

The current version on pypi is 1.10.4. The .3 version seems to be missing the aiohttp folder.   I found I was able to pip install alexapy to get it to work but as soon as you restart the services or click on interrogations it reads the manifest file and tries to install version .3 which breaks it.

I updated the version to 10.1.4 in the manifest files and all is working great now.

**Comment by alandtse** [comment]
2.8.6 already has [this](https://github.com/custom-components/alexa_media_player/blob/v2.8.6/custom_components/alexa_media/manifest.json). Please make sure you're using the latest version.

**Comment by ransom3910** [comment]
Thanks for the response, but I cloned it directly from this repository.  I just looked in the manifest.json file on gitgub and it still says 1.10.3

There is a note that says it was updated to 1.10.3 8 days ago.

**Comment by alandtse** [comment]
The dev branch is not the release branch.
