### ISSUE TITLE
echo devices not available anymore

### ISSUE THREAD

**Issue by Joebinator** [custom-components/alexa_media_player#806]
Hi there!

I noticed that my echo devices are not available anymore. :(

After trying to new install the the integration via hacs i alway get an unknown error when trying to login

Maybe someone has an idea what to do

> 2020-06-25 09:20:12 ERROR (MainThread) [alexapy.helpers] alexalogin.login((<alexapy.alexalogin.AlexaLogin object at 0x7f9f9e492850>,), {'cookies': {'session-id': '258-9861325-3973868', 'session-id-time': '2222343526l', 'ubid-acbde': '262-9988822-0972906', 'session-token': 'daKalFoDv6CXoKt5O3kpNybbR6Vrpcqa6fmXZknD84lxZSMA+stBdfKA7Zd6ka0jkPp1S0ZFKMSLiiB7y5vY04nepY5sIT0sjuQRzTHsxXEDOr9LaRabsxpFAy57mecUWN7mnEGxA0KjlxDopJYzBj1t6FyxcUgkzBnNesd7leWI3XylGllcs/egmOJlReKwCH3o3vOdIcOeNUTCpRV2LTkLpuDEdSxHmT8xvSQhdHU=', 'x-acbde': 'idgHH36OLN09BAg8rJNtPwUuN8qaTlJE', 'at-acbde': 'Atza|IwEBIM2Vf6nIsrU3KvmgRy2pj3-P7Mz9_l0j1uo9eE4mZTUK3i66j2YO9ZWJ7wi31KaM0-8kThb1zmK8KtRLxlX7E8TIIHvNJoxa5L9TfWyp0SqMjBFx03nyPO9ZqdBNyih25LDSPkenwK8SsHSuBQloLllk3sOG9fnLA1R_JNDcQ5PFYu6IV5VFBQH2p74jKXrfIb-bW0KOSuo3-K-UTgLDAcLBTMGjBu60JB5JdCW1XBvafxKyVoxep7NPOcmvBybZ3JiW9OwkDObI4OiMhWWJFIWm9PDLlAiHirUb2XTsidup3mERJ0X1UEoExjTcHY5jlwR1QoYj8abHchn-Xm4fHhCVurrPpx3VBM6cQZAlr9ahsHrFIcSLO3VKMCnt-nxBthGzlkVbf45I2-LEc-0nd2XC', 'sess-at-acbde': '+ncEKsvTf1D138x0Hv5zTgNmU1IFMuybVETxIe3CIgI=', 'sst-acbde': 'Sst1|PQHJ9zEyhgydj22GsLNOQJszC9oufw5HpxE4JAb_WZ9ODzmu5OIHpntA48QAEf_ducPUgOy-M4WSFihZOqmjkOnvsQGNKWrrXcr9dec0gUzzKofpk2OBBAzSoCNzbIdIQGQiSQn7rdJN_LrDmCkac73Q9twRi7LpdwfPxYklQnU4yFk-ywYIvliYP0kGlctwp7_8iYWJNvKdJs1zflzjZjr4-AQ8gAjZOyLjkhWbdl5uww-BGxmqvoatLcv8AfnBL10_e3piw366yVk0NQCEWQY01rXFKqfjD_rbBLzbOtNPQXz75K4raUxBB-oD2Dpykbnn3es-f1t2RiS9DbjqHArJoQ', 'csrf': '-1702881792'}}): An error occured accessing AlexaAPI: An exception of type AssertionError occurred. Arguments:
> ()
> 2020-06-25 09:20:12 WARNING (MainThread) [custom_components.alexa_media.config_flow] Unknown error: 
> 2020-06-25 09:20:25 INFO (SyncWorker_7) [pynetgear] Get attached devices 2
> 2020-06-25 09:20:36 ERROR (MainThread) [alexapy.helpers] alexalogin.login((<alexapy.alexalogin.AlexaLogin object at 0x7f9f9e492850>,), {'data': {'url': 'amazon.de', 'debug': False, 'scan_interval': 60, 'email': 'j************s@g*******m', 'password': 'REDACTED 64 CHARS', 'exclude_devices': '', 'include_devices': ''}}): An error occured accessing AlexaAPI: An exception of type AssertionError occurred. Arguments:
> ()
> 2020-06-25 09:20:36 WARNING (MainThread) [custom_components.alexa_media.config_flow] Unknown error: 
> 
> 2020-06-25 09:28:59 ERROR (MainThread) [alexapy.helpers] alexalogin.login((<alexapy.alexalogin.AlexaLogin object at 0x7f9f9e492850>,), {'data': {'url': 'amazon.de', 'debug': True, 'scan_interval': 60, 'email': 'j************s@g*******m', 'password': 'REDACTED 1016 CHARS', 'exclude_devices': '', 'include_devices': ''}}): An error occured accessing AlexaAPI: An exception of type AssertionError occurred. Arguments:
> ()
> 2020-06-25 09:28:59 WARNING (MainThread) [custom_components.alexa_media.config_flow] Unknown error: 
>

**Comment by L2v2P** [comment]
Same here. I have two Alexa device on two different accounts. One of them has become unavailable as of yesterday. For both devices I have configurator notifications in HA:

![image](https://user-images.githubusercontent.com/26650432/85680083-42e25680-b6ca-11ea-95a5-06378f1bd4df.png)

**Comment by L2v2P** [comment]
> Hi there!
> 
> I noticed that my echo devices are not available anymore. :(
> 
> After trying to new install the the integration via hacs i alway get an unknown error when trying to login
> 
> Maybe someone has an idea what to do
> 
Where can I find the log for this integration?

**Comment by Joebinator** [comment]
> > Hi there!
> > I noticed that my echo devices are not available anymore. :(
> > After trying to new install the the integration via hacs i alway get an unknown error when trying to login
> > Maybe someone has an idea what to do
> 
> Where can I find the log for this integration?

home-assistant.log in config folder of home assistant

**Comment by rdavey228** [comment]
Same problem here - My devices were asking for authentication this morning.

I logged in and was asked to provide a captcha code, the captcha code doesn't work and just refreshes the page for a new code. No matter how many times I try it won't accept the captcha. Even if I remove the integration and set it up from scratch it won't configure with captcha.

**Comment by alandtse** [comment]
Please fill out the bug report template.

**Comment by rcrisp** [comment]
I had the same issue of all Alexa devices being Unavailable and the continuous loop of the Captcha notification.  I was able to resolve this by deleting the integration (Configuration > Integrations > Alexa Media Player > Delete) and then adding the Alexa Media Player integration again.  This seems to have resolved all issues for me.

**Comment by Wibias** [comment]
Yea when I try to reconfigure it I get this in my logs:


`2020-06-27 11:42:52 DEBUG (MainThread) [alexapy.alexalogin] Login failed; check credentials


2020-06-27 11:42:52 DEBUG (MainThread) [alexapy.alexalogin] If credentials correct, please report these missing values: ['encryptedPasswordExpected']`

On newest Version 2.8.8.

**Comment by Joebinator** [comment]
Update to v2.8.9 solved my problem :)
