### ISSUE TITLE
Setup Integration - amazon.com works somewhat but amazon.de won't at all

### ISSUE THREAD

**Issue by SublimePotato** [custom-components/alexa_media_player#808]
**Under construction**
I figured I was missing the alexapy debug log - adding it a the moment. 

**Describe the bug**
I recently did an overhaul of my HASS instance and in the progress I needed to recreate the alexa_media integration.
Previously I was using a combination of configuration entry and integration, which was working fine. 

With the new HASS instance I am only using the integration as the wiki suggests, but the setup fails with `Unknown error, please report log info` (logs at the end). 
While troubleshooting i did create the integration with `amazon.com` by accident, but it worked fetched a captcha and 2FA and even found my devices. But devices found with the `amazon.com` integration are crippled, not showing media and read only, so I am still facing an issue here.

![image](https://user-images.githubusercontent.com/4058166/85751473-e81d1f00-b70a-11ea-802d-a7689f6d0058.png)

**Additional Info**
I did delete my pickle while redoing everything deleted the new (amazon.com) one multiple times while troubleshooting. 
Actually I am quite sure the error I get now is not the same as a few days before when I was trying. The previous error was an `ContentTypeError` where the `text\html` did not match the `json` that was needed. Likely due to my update `2.8.6` -> `2.8.7`?

**Comment by SublimePotato** [comment]
**Solved**
I missed the change where the pickle was moved to the `.storage` dir. 
There was a pickle with the wrog credentials stored. With the `alexapy` debug log I was able to figure that out since there was an error regarding credentials and that it was using stored credentials. 

**Feature Request**
It did not matter what credentials I was using since the config flow was using the stored pickle. 
Why using the pickle at all in the config flow? At least the user should be notified, that stored credentials were used and the ones he entered in the setup are not used.

**Comment by alandtse** [comment]
The pickle file is ignored if it doesn't successfully log in so it shouldn't matter if it's there. It allows you to save your credentials across HA installations.

**Comment by SublimePotato** [comment]
Since I deleted the faulty pickle file and it worked since then I can't provide the logs anymore. 
But I can guarantee that at least one of the 25+ times I tried to add the integration should have worked, if the faulty pickle was not preventing it. I am using an password manager to fill the form, so typos are unlikely. 

Happy my problem is solved tho.
Keep up the good work. 
Btw. - do you have way so I can buy a beer/coffee to express my gratitude?

**Comment by alandtse** [comment]
It's possible the pickle is providing session information that puts it in a weird state. I'll double check that. https://www.buymeacoffee.com/alandtse if you'd like to buy me a coffee. Thanks!
