### ISSUE TITLE
Add Russian language to the translation

### ISSUE THREAD

**Issue by vlad36N** [custom-components/alexa_media_player#818]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alandtse** [comment]
Thanks, it's added to lokalise. As you add translations they will get picked up in the next release.

**Comment by vlad36N** [comment]
I can see it is added on main page:

![r](https://user-images.githubusercontent.com/30022288/85997483-8a712700-b9d7-11ea-97d2-5aed368ee93c.png)

When click Start translating it's not on a list of the languages:

![r1](https://user-images.githubusercontent.com/30022288/85997521-95c45280-b9d7-11ea-98db-e05088849b18.png)

**Comment by alandtse** [comment]
Specifically added Russian to you. I think you can actually select it, but I'm not sure of the UI after you've already joined.
