### ISSUE TITLE
No devices detected on one of two accounts

### ISSUE THREAD

**Issue by genem2** [custom-components/alexa_media_player#820]
Tonight I'm seeing that all my devices on my primary account are unavailable. One device on a secondary account is still fine. I've tried everything: removed the integration & pickle, uninstalled/reinstalled from the HACS, and even restored my .db and .storage folder from earlier today.  I'm at a loss. 
All my Alexa devices are appearing as unavailable. (And under Entities, these are reported as Restored.)
The one device on that second account appears perfectly fine.

Do you see anything?
[MyLogs.txt](https://github.com/custom-components/alexa_media_player/files/4861925/MyLogs.txt)

Home Assistant 0.111.4  (Docker)
arch | x86_64
dev | false
docker | true
hassio | false
installation_type | Home Assistant Container
os_name | Linux
os_version | 4.19.107-Unraid
python_version | 3.7.7
timezone | America/Los_Angeles
version | 0.111.4
virtualenv | false

Thank you, sir.

**Comment by alandtse** [comment]
If possible, can you get me the json from https://alexa.amazon.com/api/np/player?deviceSerialNumber=G0918308001602WE&deviceType=A1Z88NGR2BK6A2&screenWidth=2560? It's looking like it's providing weird data.

**Comment by genem2** [comment]
Attached.  And, thank you!
[requested.txt](https://github.com/custom-components/alexa_media_player/files/4863988/requested.txt)

**Comment by user514** [comment]
I think I'm having same issue. Yesterday I reautorize one of my two accounts. Today I got the other alexa as unavailable with 1 notification to enter captcha, etc. I tried but it keeps asking to confirm in red characters and sending me an email, I receive an email to aprove I'm trying to login in another computer, and again in hassio the notifiacion with action required in an endless loop. When I reboot hassio, It sends me again the email to gmail account when I retry, and again the endless loop. I went to delete the pickle file in .storage, but it was already gone. I only have the one from my first account...

**Comment by alandtse** [comment]
@genem2 ok thanks. I got it. I guess ebooks don't provide any progress info. It'll be in the next release.

**Comment by user514** [comment]
I was preparing a log file right now... and while I was at it trying to reproduce the problem trying to authorize, suddenly when I hit CONFIGURE it close the window wiithout problem this time and hassio remove the notification. I receive instantly an email saying somebody (me) has logged at amazon, etc.

  Problem solved. seconds after that, I was informed that genem2 was publishing an edit on his message saying he solved his problem. So I think that it could be related with amazon servers doing something fancy?, that was solved at around 23:40 UTC (1:40am Madrid time).

**Comment by alandtse** [comment]
@user514 Sounds like you had a different problem unless you were reading an ebook too.
@genem2 If you switched what you were reading to something non ebookish then that would solve it too. Also Amazon could have reset the info on all its servers. Regardless, I have a fix so you should be able to listen to ebooks. :)

**Comment by genem2** [comment]
Thank you. I appreciate your support.
