### ISSUE TITLE
Removal deletes entire custom_components folder

### ISSUE THREAD

**Issue by Shadowstrider77** [custom-components/alexa_media_player#825]
**Describe the bug**
Removal deletes entire custom_components folder

**To Reproduce**
1. Go to 'HACS'
2. Click on 'three dots'
3. Scroll down to 'click Unistall'
4. Folder is gone. HACS not working after reboot as HACS is also gone.

**Expected behavior**
Only remove the Alexa component.

**System details**
 - Home-assistant (0.111.4): 
 - Hassio (No): 

**Logs**
No logs

**Comment by alandtse** [comment]
This is not something I can fix. You need to report this to [HACS](https://github.com/hacs/integration/issues).
