### ISSUE TITLE
notify.alexa_media with target not working but others do

### ISSUE THREAD

**Issue by sinabahram** [custom-components/alexa_media_player#827]
**Describe the bug**
When using Appdaemon or just the services test in HA, I get no errors but also no speech when doing something like this.

{ "message": "test", "data": { "type": "tts"}, "target": "name of echo device"}

If I chop off the target and use any of the notify services that include the alexa device in their name already, again in Python with AD or in the services test in HA, I get speech.

Super possible I'm doing something wrong here, but since I get speech the other way, and I'm essentially just setting things up so copy/pasting from the docs themselves, I feel like maybe there's an odd bug or I'm seriously missing something about notify/alexa_media compared to the notify services specific to an Alexa device, which work fine.

My only goal is to be able to specify a target so I can begin building up some logic in AD about when to speak what where.

**To Reproduce**
Use notify/alexa_media in AD or notify.alexa_media in HA services test and specify a target. There is no speech.

Now change to any of the alexa_media that specifies a specific device, delete target from your payload, either in AD or HA, and notice speech works just fine.

**Expected behavior**
Speech should come out of the specified alexa device specified in target

Happy to provide more info. Running latest HA and AD via docker-compose. No errors reported in either HA services test tool or via AD in the various logs. Oh, and a million thanks for creating this. You rock!

**Comment by alandtse** [comment]
Please fill out the entire template and properly quote your service call as your typing it in. For example, if I don't know what version you're on I can't figure out what the problem is. Similarly, if you have a syntax error, I can't tell without seeing the call.

**Comment by alandtse** [comment]
For example this is a valid service call:
```json
{
"message":"test",
"title":"test",
"data":{"type":"tts"},
"target":["media_player.great_room"]
}
```

As is this:

```json
{
"message":"test",
"title":"test",
"data":{"type":"tts"},
"target":"media_player.great_room"
}
```

**Comment by sinabahram** [comment]
That's fair enough, and my apologies for the lack of specitivity.

versions:
AppDaemon 4.0.3. This could very well not matter, though, as I'm able to replicate the same difference in behavior of working/not working over in pure HA.

HomeAssistant: 0.112.1                                                                                                                 

alexa_mediaplayer: 2.9.1

URL from browser after I went to developer tools and activated services:
https://(homeassistant-hostname)/developer-tools/service

I can then select the following service:
notify.alexa_media_guest_bedroom_dot

And then if I paste the following string into the edit field and hit the "Call Service" button, I hear "message contents" out of the dot.

{
"message":"message contents",
"title":"test",
"data":{"type":"tts"},
}

Now, I will make only two changes. I will add the target line back in from your example, addressing the guest bedroom dot (see below), and I will change the service from "notify.alexa_media_guest_bedroom_dot" to "notify.alexa_media".

Here's the string I'm pasting in.
{
"message":"message contents",
"title":"test",
"data":{"type":"tts"},
"target":["media_player.guest_bedroom_dot"]
}

I get no speech output from the above. I also tried using "media_player.alexa_media_guest_bedroom_dot". Still, nothing.

I will note, I've tried other devices, and they all behave this way. They all talk when using the service with their name built in but not with me using the generic service and trying to use the target parameter. I've even tried using target but aiming it at a specific service naming a specific device like the guest_bedroom_dot but setting target elsewhere, and only the guest bedroom dot says the contents as I suspected would happen.

If I may provide anything else, I'm happy to do so, but no errors are returned on the page or in home-assistant.log. Huge thanks in advance.

**Comment by alandtse** [comment]
Please enable [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).  Also, please use quotes like I just added in the edit.

The targeted versions merely fill in the target for you so if that works, it should also work if you do it manually.

**Comment by sinabahram** [comment]
Sorry about the quotes, and will do. I'm blind, and I sometimes forget to turn those on. I know they can apply helpful visual formatting.

In going to turn on logs and such, I seem to have hosed this thing beyond recovery, which is fine as it'll ive me a chance to learn more about debugging it in the future, though unfortunate to solving this specific issue.

Question: is there a way of forcing the uninstall when the uninstall from the docs no longer works?

Here is where I am. I have deleted it from integrations and removed the entire custom_components folder as this was the only one in there. It still gives the exact error referenced in the docs. If I copy the custom_components recursively back over from the latest checkout of the code, restarting home-assistant afterwards, I'm then left with this in the logs after I try to install it which fails:

```
2020-07-05 00:31:44 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration alexa_media: No module named 'custom_components.alexa_media.config_flow'                                        
```

So, I can't fully uninstall it nor fully install it. How do I et out of this state?

After I've removed the entire custom_components folder, the only results that

```
grep -r -i alexa_media *
```

returns is the binary db file for HA, that's it, so somehow some state is maintained post-uninstallation, but I don't know how to clear that out nor do I see it in the docs.

Any help would be most appreciated , and sorry for the tangential issue.

**Comment by alandtse** [comment]
Just install HACS and let it manage the installation of the files. You need to go into Configuration -> Integrations and remove it in HA.

**Comment by sinabahram** [comment]
Thanks for your help on this. I will investigate doing that, but adding complexity by integrating hacs doesn't really address my concern, unless if hacs is now required to install this custom component? As I said, I did uninstall the integration. It does not show up in integrations. No matter what I do or in what sequence it occurs, the following error shows up in my logs when I go to add the integration:

```
2020-07-05 16:25:06 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration alexa_media: No module named 'custom_components.alexa_media.config_flow'                                        
```

I've checked, there is no such module present in the folder. I also see the rellevent import in the Python file, so the error seems reasonable to me. presumably some step is supposed to execute before-hand to place config flow in the right place, right? This folder used to have a lot more stuff in it before with .translation, etc. so something early on is presumably failing.

In an effort not to bother you in case I could figure it out, I read up on this by way of:
https://developers.home-assistant.io/docs/config_entries_config_flow_handler/

And while I do see the correct entry in the manifest, I do not see any config flow stuff in the alexa_media folder that I copied directly from the repository. This raises a question for me, which is whether master is currently in a runnable state or should I always checkout a specific release?

If I'm being stupid and I shouldn't be running from master, let me know, but info online seems to indicate to do this.

Not that it will be news to you most likely, but the line I found referencing this in the __init__.py was this one of course:

```python
from .config_flow import configured_instances
```

This very well could be a red haring, but as I've said, I've tried uninstalling, completely removing that folder and recreating it, uninstalling per the documentation, installing again, etc. It does not show up in integrations. When I go to install it, it  does show up, but when I go to install, that's the message that appears in the logs with no helpful UI feedback about any errors. 

That log message is the only constant that keeps coming up.

Speaking of logs, here is my entire configuration.yaml, which includes my logger directive, as it is super-simple. Most of the yaml files included are empty.

```yaml
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  auth_mfa_modules:
    - type: totp

automation: !include automations.yaml
ecobee: !include ecobee.yaml
group: !include groups.yaml
homekit: !include homekit.yaml
http: !include http.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
zwave: !include zwave.yaml

alexa:
  smart_home:

logger:
  default: warning
  logs:
    custom_components.alexa_media: debug 
```

If it helps, inside of __pycache__ for alexa_media, it only got as far as to compile __init__, but that's also probably obvious since it's failing early on in that file per the line I indicated above.

If I'm doing something wrong, please tell me exactly what it is, but I do believe I've gotten it in a state that the published docs and posts don't address. I'm happy to hose some stuff or take a one-time step, but it just doesn't let me install this thing anymore. I very much would like to address that to at least return to my previous state.

Sorry for the trouble, and my sincere thanks for your work on this.

**Comment by alandtse** [comment]
HACS simplifies the install process. I don't have time to figure out if you copied files correctly. The error says you are missing a file which exists in the [release](https://github.com/custom-components/alexa_media_player/releases/tag/v2.9.1). So the issue is user error since you are copying files wrong.

This entire issue appears to be a user configuration error and not a technical issue. Please use the forums if you need help.
