### ISSUE TITLE
captcha image is broken

### ISSUE THREAD

**Issue by k1ng440** [custom-components/alexa_media_player#832]
**Describe the bug**
components ask for captcha frequently and I have to remove and add it back every time because the captcha image is always unavailable. 

https://puu.sh/G3KWh/0c4c483b1e.png

**To Reproduce**
1. Go to 'notifications'
2. Click on 'configure'
4. captcha image is broken

**Expected behavior**
captcha image should be visible 

**Screenshots**
https://puu.sh/G3KWh/0c4c483b1e.png

**Comment by alandtse** [comment]
Just enter anything and it'll refresh.
