### ISSUE TITLE
[FR] Consider switching to official API

### ISSUE THREAD

**Issue by chemelli74** [custom-components/alexa_media_player#837]
Would you consider switching your great plugin to the official API ?

- https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/avs-rest-alarms.html
- https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/get-started-with-alexa-voice-service.html

I think the gain is a more stable access to Alexa functions and get more of those available in HA

Alternative is to stay with current unofficial API that works great but require nearly daily release.

Simone

**Comment by alandtse** [comment]
If you want the official API, please use the official [integration](https://www.home-assistant.io/integrations/alexa/) and ask for features there. They have different APIs with different feature access. The API used by this component is not the same.
