### ISSUE TITLE
No album artwork + other issues when logged into wrong domain

### ISSUE THREAD

**Issue by agneevX** [custom-components/alexa_media_player#838]
**Describe the bug**
When music is playing from Amazon Music/Apple Music, the state of the `media_player` keeps switching from `standby` to `unavailable` and there is no Now Playing screen or any artwork. 

The only thing that works is that the correct devices show up and the volume is shown correctly although I can't change it but changing it elsewhere reflects immediately. 

**To Reproduce**

**Expected behavior**
Now Playing/Album Artwork should show. 

**Screenshots**
As I'm typing this, I noticed that the device is showing `Unavailable` as it does from time to time.

<img width="952" alt="image" src="https://user-images.githubusercontent.com/19761269/86776487-df670a00-c075-11ea-91c1-0997369bf96d.png">

**System details**
 - Home-assistant (version): 0.112.0
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup): 1.10.8

**Logs**
https://paste.ubuntu.com/p/QGC9wWpds6/

**Additional context**

**Comment by alandtse** [comment]
Your template is incomplete. I don't know what version you're using. Also, what region are you logging in to? The issue you're reporting can happen if your'e logged in to the wrong region.

Your logs aren't indicating you are playing music. The timeframe is probably too small to catch any change in music. Please provide logs showing when you are starting or stopping music. Please also provide a snippet showing the initial device discovery.

Unavailability is being reported by Amazon's device [page (fix region)](https://alexa.amazon.com/api/devices-v2/device) with `"online":false`. Your echo device may be disconnecting from Amazon so we're reporting what Amazon is reporting. 

The reason it comes back is when we detect a websocket coming from the device, we change the device to online until the next time we check with Amazon. If it says you're offline, we'll mark it as unavailable.
```text
2020-07-07 17:05:20 DEBUG (MainThread) [custom_components.alexa_media] Updating media_player availability {'destinationUserId': 'A*********ULI', 'dopplerId': {'deviceType': 'A3S5BH2HU6VAYF', 'deviceSerialNumber': 'G************1ET'}, 'bass': 6, 'midrange': 0, 'treble': 0}
```

**Comment by agneevX** [comment]
>  I don't know what version you're using. 

I installed it through HACS. If you're asking about `alexa_media`, I can't find the details in the logs. Otherwise I have version 2.9.2 installed (per HACS). 

> Also, what region are you logging in to?

`amazon.com`. I tried `amazon.in` as I am in that locale but received errors.

Please note that when I sign into the Amazon Alexa app, the website is `alexa.amazon.com` and not `alexa.amazon.in`.

```
2020-07-08 12:25:30 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Creating new login
2020-07-08 12:25:30 ERROR (MainThread) [alexapy.helpers] alexalogin.login((<alexapy.alexalogin.AlexaLogin object at 0xa22b0230>,), {'cookies': {}}): A connection error occured: An exception of type ClientConnectorError occurred. Arguments:
(ConnectionKey(host='alexa.amazon.co.in', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0xa10e9ef0>, proxy=None, proxy_auth=None, proxy_headers_hash=-1629788111), gaierror(-5, 'No address associated with hostname'))
```

> Your logs aren't indicating you are playing music. The timeframe is probably too small to catch any change in music. Please provide logs showing when you are starting or stopping music.

That is exactly what I did (and expected it to show up in the logs).

**Comment by agneevX** [comment]
Fixed with manually adding to `configuration.yaml` with `amazon.in`.

Please note that in the Integration setup, `amazon.co.in` and `amazon.in` made the same request. In case of `amazon.in`, `alexa.amazon.in` would've worked, so there's a possible bug. 

```
2020-07-08 12:25:30 ERROR (MainThread) [alexapy.helpers] alexalogin.login((<alexapy.alexalogin.AlexaLogin object at 0xa22b0230>,), {'cookies': {}}): A connection error occured: An exception of type ClientConnectorError occurred. Arguments:
(ConnectionKey(host='alexa.amazon.co.in', port=443, is_ssl=True, ssl=<ssl.SSLContext object at 0xa10e9ef0>, proxy=None, proxy_auth=None, proxy_headers_hash=-1629788111), gaierror(-5, 'No address associated with hostname'))
```

**Comment by alandtse** [comment]
If it's trying to connect to `alexa.amazon.co.in` it's because you typed in `amazon.co.in`. Please make sure you use the proper domain `amazon.in` in your configuration. It's possible it remember your old attempt at `amazon.com.in`. 

The reason you're not seeing any information is because Amazon believes the echo dot is offline. This is because the Echo Dot isn't registered to amazon.com (you can confirm it with the alexa device page I already provided). You will need to register them to the right domain and have the component log into that domain.

**Comment by agneevX** [comment]
> If it's trying to connect to alexa.amazon.co.in it's because you typed in amazon.co.in.

No I did not. I initially typed in `amazon.co.in` but I changed it to `amazon.in` and retried.

> It's possible it remember your old attempt at amazon.com.in.

There we go. That's the bug.

**Comment by alandtse** [comment]
Please make sure you've removed the integration from your the Configuration -> Integrations page. If you didn't, it's still connecting through there.

**Comment by agneevX** [comment]
Yeah that I did.
