### ISSUE TITLE
Node-Red Sound Integration

### ISSUE THREAD

**Issue by pbishop1418** [custom-components/alexa_media_player#839]
I am trying to follow the sound instructions for Node-Red. I can get it working in the HA but can not in Node-Red.

Here is my HA script and my Node-Red setup. Please advise!

![HA](https://user-images.githubusercontent.com/68039398/87001026-79b57380-c184-11ea-942c-b5deee61fb44.png)

Node-Red

![NR-2](https://user-images.githubusercontent.com/68039398/87001033-7de19100-c184-11ea-9998-bd2d47c5f4b1.png)
![NR-1](https://user-images.githubusercontent.com/68039398/87001034-7e7a2780-c184-11ea-8c6f-af97a2c67218.png)

**Comment by alandtse** [comment]
The best place for `how to use` questions like this is the HA [forums](https://community.home-assistant.io/t/echo-devices-alexa-as-media-player-testers-needed/58639/4091). I'll leave this up for a week, but I doubt you'll get enough traffic to get a response.

**Comment by philharle** [comment]
You want to be calling the `media_player` service in Node-Red rather than `notify`.

Using your example the `call service` node should be configured as
**Domain:** `media_player`
**Service:** `play_media`
**Data:**
```
{
    "entity_id": "media_player.my_device_name",
    "media_content_id": "amzn_sfx_doorbell_chime_01",
    "media_content_type": "sound"
}
```

**Comment by pbishop1418** [comment]
You rock! Thank you!
