### ISSUE TITLE
HASSIO Integration Config Page - no labels

### ISSUE THREAD

**Issue by njloki30** [custom-components/alexa_media_player#847]
**Describe the bug**
Missing field labels on Home Assistant Config Integration Page / can't sign in
**To Reproduce**
1.Go to integrations, Add new, Choose Alexa Media Player
2. When pop up opens to sign in, labels are missing, can't log in
![image](https://user-images.githubusercontent.com/20994562/87901293-a8550900-ca24-11ea-8437-eb684766a0bb.png)

**System details**
 - Home-assistant:  0.112.4
 - Hassio : Yes
 - alexa_media : 2.10.0
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by alandtse** [comment]
Refresh your browser cache.

**Comment by jcjenk** [comment]
I have the same issue. Tried in Firefox, Chrome, and Edge

**Comment by alandtse** [comment]
What are your language settings?

**Comment by jcjenk** [comment]
English

**Comment by alandtse** [comment]
Check your custom_components/alexa_media directory for a translations directory. Please confirm it's there. If it is, it's because your browser cache is not downloading the .json files when viewing the page.

**Comment by njloki30** [comment]
Yes, the translations folder is there. I've tried both Firefox and Chrome as well as as Safari on IOS 13 still no luck 
![image](https://user-images.githubusercontent.com/20994562/88060736-9cf10300-cb34-11ea-870b-fea018d09fda.png)

**Comment by njloki30** [comment]
Ok so I'm all straightened out, I downloaded the latest version from Git, cleared my cache and restarted Hass, and was able to re login. thanks guys for the help. cheers.

**Comment by jcjenk** [comment]
I've tried uninstalling, reinstalling an old version, clearing cache, restarting the system, updating to the new version, etc. and I can't get this to work.  (It stopped working several weeks ago.)
My system:
![SystemHealth](https://user-images.githubusercontent.com/31355763/88087696-2a852080-cb3e-11ea-80c0-48b2c9fa4f7f.png)
If I go through HACS/Integrations, if I click "Update information" nothing happens, nothing opens.
![HacsAlexa](https://user-images.githubusercontent.com/31355763/88087843-65875400-cb3e-11ea-90f7-091f46b58c4f.png)
If I go through Configuration/Integrations I can click "alexa_media"
![ConfigAM](https://user-images.githubusercontent.com/31355763/88087984-97001f80-cb3e-11ea-870c-b78a6e99ccef.png)
but then I get this window with missing labels
![AMmissing](https://user-images.githubusercontent.com/31355763/88088043-aaab8600-cb3e-11ea-88ff-7392b4d6620d.png)
And I have the translation files:
![translations](https://user-images.githubusercontent.com/31355763/88088107-c4e56400-cb3e-11ea-9a84-dda407cef7f9.png)

Anything else I can try?

**Comment by njloki30** [comment]
When I downloaded the latest from this link
https://github.com/custom-components/alexa_media_player/releases/tag/v2.10.0 

There was another translations folder, one without a “dot” in front of it. Maybe that makes the difference. I copied the folder contents from this version, restarted hass and cleared cache. It got it working for me.

**Comment by jcjenk** [comment]
I did see that folder. I just tried copying those files into the .translations folder, rebooting, and clearing cache but I have the same problem.  This is how I'm clearing the cache, is that enough or do I need to clear cookies too?
![clearcache](https://user-images.githubusercontent.com/31355763/88096355-5ce94a80-cb4b-11ea-982d-3811ac1adf37.png)

**Comment by jcjenk** [comment]
I just realized some of my other "cards" in configuration/integrations are having the same problem, but not all of them.  HACS and UPNP are two missing labels. Logitech Harmony and MQTT have the labels.

**Comment by njloki30** [comment]
That should be enough to clear before restarting the browser. But just to clarify, when I listed the previous link and it's contents I copied "everything" to hassio. So I have two folders in my Alexa-media folder 
.translations and
Translations. 

Download the 2.10 zip file and load those all into custom-components/Alexa-media

**Comment by jcjenk** [comment]
It is working. I uninstalled Alexa-media then uninstalled HACS.  I reinstalled hacsHACS, then Alexa media with appropriate rebooting and cache clearing per the instructions. (I know I did all this prior as well).  This time, I could see the text in the box and I got it set up.  I had downloaded the Alexa zip file and was preparing to copy into the alexa_media folder that HACS created but I didn't end up needing to do that.   Thank you for all the help.

**Comment by jcjenk** [comment]
I should clarify, I also rebooted my computer that I'm using to access Home Assistant prior to reinstalling HACS.  I had other strange things happening as well like the light scheduler in Node-Red wouldn't schedule by clicking in the calendar.  That is also fixed.  I do not believe this issue was an Alexa_Media_Player issue.

**Comment by alandtse** [comment]
So the .translations/translations thing is a symlink so it should create both directories. It should be in the release package with HACS.  It's needed for backward compatibility with older HA versions. 

The issue described is typically a problem with the cache of the browser trying to access HA. This is fixed by forcing your browser to [reload](https://www.namecheap.com/support/knowledgebase/article.aspx/10078/2194/how-to-do-a-hard-refresh-in-chrome-firefox-and-ie) the page (ignoring the cache).

I'm glad you were able to resolve it.
