### ISSUE TITLE
Issues with install with python 3.8 - No module named 'importlib_metadata'

### ISSUE THREAD

**Issue by cbailes78** [custom-components/alexa_media_player#849]
My Home Assistant instance is version 0.112.4 built upon Ubuntu 20.04 standard with python 3.8.  Everything works well apart from trying to install alexa_media install gives me the following error:

2020-07-21 19:08:54 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration alexa_media: No module named 'importlib_metadata'

I cannot get to the screen where I add the email and password.

Googling suggest external module 'importlib_metadata' became internal function 'importlib.metadata' at python 3.8.

Many thanks for your kind help and for a great product.

**Comment by alandtse** [comment]
Thanks. I'm having mixed results on 3.8. My production system is on HASSIO with Python3.8 and it doesn't have an issue importing. Other times I've seen the error you're talking about. Can you please fill out the full template so I have all the system info?

**Comment by cbailes78** [comment]
**Describe the bug**
When attempting to install the alexa_media integration, it consistently flashes and instantly returns to the list of integrations.  It does not get far enough to enter the Alexa account /password details.

**To Reproduce**
Consistent early set-up issue for me.

**Expected behavior**
Ability to install and configure alex_media.

**Screenshots**
N/A

**System details**
OS: Ubuntu 18.04 standard (apt upgraded)
python: 3.8.2
pip: 20.0.2
Home-assistant (version): 0.112.4 (via venv)
Hassio (Yes/No): no
alexa_media (version from const.py or HA startup): 2.10.0
alexapy (version from pip show alexapy or HA startup): 1.12.0

**Logs**
`2020-07-21 19:08:54 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration alexa_media: No module named 'importlib_metadata'`

**Comment by alandtse** [comment]
Thanks. A fix will be in the next version.
