### ISSUE TITLE
Problem setting up integration - AttributeError

### ISSUE THREAD

**Issue by jgalak** [custom-components/alexa_media_player#854]
**Describe the bug**
When I attempt to add the integration, I get a message that says "Unknown error, please report log info"

The HA log contains the following:

ERROR (MainThread) [alexapy.helpers] alexalogin.login((<alexapy.alexalogin.AlexaLogin object at 0x7feab64e46d0>,), {'cookies': {'session-id': '136-0112779-1138664', 'session-id-time': '2219522337l', 'ubid-main': 'REDACTED', 'session-token': 'REDACTED', 'x-main': 'REDACTED', 'at-main': 'REDACTED', 'sess-at-main': 'REDACTED', 'csrf': 'REDACTED'}}): An error occured accessing AlexaAPI: An exception of type AttributeError occurred. Arguments:
("module 'aiofiles.os' has no attribute 'remove'",)

(I've redacted out most of the JSON data, as I don't know if it contains encoded log in credentials or other private data.  If it's important for resolving the issue, please let me know which elements you need and I'll post them.)

followed by: 
WARNING (MainThread) [custom_components.alexa_media.config_flow] Unknown error: module 'aiofiles.os' has no attribute 'remove'

**To Reproduce**
I am running HA 0.106.6 installed in Docker on generic Linux (Ubuntu).  In the past, I had the alexa media player component running on older versions of HA, installed directly.  I recently removed the old installation and reinstalled with HACS.  HACS is showing that version 2.10.0 is installed.

Following Instructions, I went to the Integrations tab, clicked the orange + button, selected "Alexa Media Player" and got the configuration screen.

On that screen I entered the user name and password, leaving everything else as default.

It displayed the "Unknown error, please report log info" message and did not create the integration.  See above for log details.

Selecting "Advanced Logging" did not add anything new to the log.

I have tried this multiple times.

**Expected behavior**
An integration would be created for this component.

**System details**
 - Home-assistant (version): 0.106.6
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug). Yes.  Tried multiple restarts.
 - alexa_media  (version from `const.py` or HA startup): 2.10.0 (as per HACS)
 - alexapy (version from `pip show alexapy` or HA startup): 1.12.0 (as per pip show alexapy

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

The instructions at that address tell you how to enable logging when the component is installed without HACS and configured via YAML.  I don't see instructions for how to enable logging when installing via HACS and integration, unless it's just the "advanced debugging" checkbox, which doesn't seem to do anything.

HA log errors posted above.

**Comment by alandtse** [comment]
Thanks. Can you determine what version of aiofiles you're on? You need at least 0.5.0.

```bash
# pip list  | grep aiofiles
aiofiles                         0.5.0
```

For the logs link, you need to edit your configuration.yaml to create debug logs. There is no config flow way to enable the logger that I'm aware of.

**Comment by alandtse** [comment]
As Alexapy does require 0.5.0, my guess is you have another component that is keeping you on an older version of 0.4.0. You'll need to resolve that conflict.

**Comment by jgalak** [comment]
It is, indeed, using 0.4.0.  I have no clue what else uses it or how to find it...  I don't think Hass.io add-ons would affect this, right?  Since they live in separate containers?  So it's just whatever is in the main home assistant container?  

The only things I have running in that container that are not base HA is HACS, and via HACS I have installed the Youtube Sensor integration, and the Custom Header plugin.

Could this be because I'm running an older version of HA (0.106.6) and thus an older version of HACS (1.2.2 - it won't let me upgrade to newer as that requires HA 0.110.0 or later)?

**Comment by jgalak** [comment]
So from poking around the forums, it seems that that version of HACS itself requires 0.4.0.  So unless someone knows of a workaround that allows two versions of the same package to coexist (I don't think it's possible without manually installing one version in a different directory and then editing the source of either HACS or this integration to point to the non-standard directory), it looks like I'm stuck until I upgrade HA itself.

Suggestion:  perhaps make HA 0.110.0 a requirement to install whichever versions of this integration require aiofiles 0.5.0.  So that one can't accidentally upgrade too far?

**Comment by alandtse** [comment]
You can't have two versions. And no, it's not a requirement with HA 0.110.0. It's an issue with HACS for whatever version you're on. Unfortunately, there is no way right now to specify a HACS requirement. Also, when you're dealing with custom components, there is no checking about dependency conflicts like with official components.

So in this case you can try to going back to an older `alexa_media` (I believe before 2.6.0) or you can update to a later HA. Unfortunately, I'm not going to spend any time trying to solve problems with older versions of HA or alexa_media.

I may have a fix so it doesn't completely fail because it's missing this dependency but it may mean it won't be able to save your .pickle file anywhere.

**Comment by jgalak** [comment]
Totally fair not trying to support old version.  I'll work on updating HA, hopefully that'll be the only issue

Thanks for the help!
