### ISSUE TITLE
Alexa Speechcon Integration

### ISSUE THREAD

**Issue by andykams** [custom-components/alexa_media_player#860]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**
I am trying to use speechcon  function but it does not seem to work.

**Describe the solution you'd like**
Below is the link to speechcon where we can add interjections similar to emotions and effects.
https://developer.amazon.com/en-US/docs/alexa/custom-skills/speechcon-reference-interjections-english-us.html

**Describe alternatives you've considered**
Tried using Lang feature but does not have the same effect. 

**Additional context**
https://developer.amazon.com/en-US/docs/alexa/custom-skills/speechcon-reference-interjections-english-india.html

**Comment by alandtse** [comment]
Can you do this in the official Amazon app? If not, we can't. That said, please review the [wiki](https://github.com/custom-components/alexa_media_player/wiki/Configuration%3A-Notification-Component#announce) for known ssml support.
