### ISSUE TITLE
shuffle, repeat, do no disturb toggle with area

### ISSUE THREAD

**Issue by metaxis** [custom-components/alexa_media_player#861]
**Describe the bug**
After putting the various Echo devices into the correct rooms, announcements stopped, but only when the lights were turned on.  This is because the device "do not disturb" option is showing up as a switch device. Same for shuffle and repeat.

**To Reproduce**
0. Give your echo device a non-null area
1. Go to any area panel with an echo device in it
2. Toggle the area room switch
3. See the echo option switches toggle along with the lights

**Expected behavior**
Area-wide toggles should not adjust echo device options

**System details**
 - Home-assistant (version): 0.113.2
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): v2.10.1
 - alexapy (version from `pip show alexapy` or HA startup):1.12.1

**Comment by alandtse** [comment]
This is likely a HA issue where it needs to provide an option so that area level on and off only impact lights or some other defined class. Short of removing the switches, there's nothing we can do no the component level to change this behavior in HA.

**Comment by alandtse** [comment]
Closing as this is an HA issue. You can also remove the device from an area since it doesn't actually do anything for the component. We don't magically link to other devices in HA just because you put it in the same area.
