### ISSUE TITLE
An exception of type CookieError occurred. Arguments: ("Attempt to set a reserved key 'SameSite'",)

### ISSUE THREAD

**Issue by toben1997** [custom-components/alexa_media_player#862]
I have the problem that after a integration update all the devices in the second account are unavailable.

A login error occured: An exception of type CookieError occurred. Arguments: ("Attempt to set a reserved key 'SameSite'",)

**Comment by alandtse** [comment]
Thanks. Please fill out the template. This should have already been fixed in the latest version. If not, delete the cookie file.

**Comment by pfriedrich84** [comment]
How to find and delete the cookie file? have the same error since a few days ...

**Comment by alandtse** [comment]
/config/.storage

**Comment by alandtse** [comment]
This probably needs an update from aiohttp. https://github.com/aio-libs/aiohttp/pull/4224. It looks like python 3.8 should natively support it.

**Comment by alandtse** [comment]
Will need logs to see what's going on. Please fill out the bug template.

**Comment by alandtse** [comment]
I'm going to close this as resolved since I'm not seeing anyone with logs for it.
