### ISSUE TITLE
dont know how i can add this in home-assistant

### ISSUE THREAD

**Issue by gbdavidx** [custom-components/alexa_media_player#865]
**Describe the bug**
I have HACS installed but it does not show up

**To Reproduce**
1. Go to hacs, search for alexa media, does not show up

**Expected behavior**
be able to see alexia media player in Integrations

**Screenshots**

**System details**
Integration version: | 1.3.3
-- | --
Frontend version: | 202008050145
Repositories: | 606
Installed repositories: | 20

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by gbdavidx** [comment]
weird, it showed up when i clicked the + sign but not when i searched for it

**Comment by gbdavidx** [comment]
So i was able to add this, but i cannot change my password.  it automatically detected my email address, but i was not able to put in my password.  when i type in the 2fa it says password incorrect

**Comment by alandtse** [comment]
The + sign is how you add it in HACS. This is not a bug we can control. It shouldn't automatically do anything. Check your configuration.yaml or remove the integration and readd it.

**Comment by gbdavidx** [comment]
Ok but only way to get it to work was adding the credentials in my
config.yaml file which says you shouldn’t have to do
