### ISSUE TITLE
routines don't trigger

### ISSUE THREAD

**Issue by micaelp** [custom-components/alexa_media_player#869]
Hi,

Following from your example in the wiki for routine triggering, I tried the following in Developer Tools/Services

Service
media_player.play_media

Service Data
{
  "entity_id": "media_player.alexa",
  "media_content_id": "BathroomLights",
  "media_content_type": "routine"
}
  
This does not trigger the BathroomLights routine, which I can trigger just fine from Alexa.

I also tried

{
  "entity_id": "media_player.play_media",
  "media_content_id": "BathroomLights",
  "media_content_type": "routine"
}

But this doesn't work either.

HA is 0.114.1
AMP is 2.10.1

**Comment by CCOSTAN** [comment]
I have it working with the following Code. 
https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/config/packages/noonhome.yaml#L14-L22

**Comment by batizisanya** [comment]
I have the same problem. When I want to run my routine, I get this error message: `An error occured accessing AlexaAPI: An exception of type TypeError occurred. Arguments:
("'>' not supported between instances of 'NoneType' and 'int'",)`

**Comment by alandtse** [comment]
Please use the bug template if you want me to review this.

**Comment by micaelp** [comment]
CCOSTAN/Home-AssistantConfig#812 that was the fix.  The routine needs to be set as a "when you say" as this is what HA sends to Alexa (the routine name).  Thanks a million CCOSATN!

**Comment by alandtse** [comment]
You can also update the [wiki](https://github.com/custom-components/alexa_media_player/wiki#automation-routines-versions--100) to explain this if you want.

**Comment by CCOSTAN** [comment]
I'm in the process of making a video on this topic (Using Routines in Home Assistant via Alexa Media Player) that I will link in the wiki once published.
