### ISSUE TITLE
alexa_media.xxxx@xxx.xxx.pickle

### ISSUE THREAD

**Issue by newbee112** [custom-components/alexa_media_player#87]
Not so nice that it creates a file with full email address.

**Comment by alandtse** [comment]
This is local to your system so you should have control on who has access.  This allows users with multiple accounts to know which cookie file to delete. We may be able to migrate away from the cookie file once we have config_flow working, but until then, I am unlikely to put any effort to change it.  If someone wants to put in a PR to address this, I can merge it in.

**Comment by alandtse** [comment]
As a note, I took a quick look and the changes would have to happen in the [API](https://gitlab.com/keatontaylor/alexapy/tree/master/alexapy) where I do not have contributor rights to for now.

**Comment by keatontaylor** [comment]
@alandtse added as a maintainer on gitlab

**Comment by newbee112** [comment]
i know it is my local system :) but becomes an issue if you use for example git to backup your files.. in this case you need to add it to be ignored.. easily missed. i know this now so for me its not an issue.. perhaps for other future users?

**Comment by alandtse** [comment]
I get your point; although if people are backing up the cookie (even without the email address) to github that's already a problem. I'll see if there's some better location in the config directory we can write to like .storage but it'll be a low priority fix.

**Comment by keatontaylor** [comment]
We need to consider that this will require migration from the existing configuration location, we should consider three release cycles that look in both locations while storing in the new one and eventually phase out.

I'll look into it.

**Comment by alandtse** [comment]
I'm thinking we could probably provide some logic when spawning the AlexaLogin to specify the old_path and the new_path.  

1. If it detects a cookie in the old_path, it should test it, delete from the old_path, and save it in the new_path.
2. If it doesn't detect a cookie the old_path, it should only check the new_path.

This will allow us to move the cookie around moving forward. We also wouldn't have to ever deprecate the old_path. To be honest, once we have config_flow #48, I don't think we need to save in the filesystem anymore anyway.

**Comment by alandtse** [comment]
This will be closed because we are migrating the pickle file into the `.storage` directory due to #670. That directory is filled with email addresses and password information in plaintext anyway so if a user is not protecting that directory, they're already screwed.
