### ISSUE TITLE
URL object has no attribute 'decode'

### ISSUE THREAD

**Issue by alandtse** [custom-components/alexa_media_player#880]
@alandtse I still have this issue and i did not reset the password. I have the following in the error log:

`alexalogin.login((<alexapy.alexalogin.AlexaLogin object at 0xa301e100>,), {'data': {'password': 'REDACTED 14 CHARS', 'captcha': 'afxxbw'}}): An error occured accessing AlexaAPI: An exception of type AttributeError occurred. Arguments: ("'URL' object has no attribute 'decode'",)`

I also have tried removing the integration from the config and activating it from the beginning of the UI (i also don't have 2fa enabled). 
It seems the issue is triggered because amazon sends a text to my cell phone about allowing access (you have to click a link then press approve button) and this is probably why the login fails.

"Amazon security alert. Tap link to respond: https://amazon.com/a/c/r?k=3543871c62084f9ebfd3708e3e804411-8dc5"

There is also a "/n" in a dialog box, not sure if that could be the reason or not.
![image](https://user-images.githubusercontent.com/8117544/91082540-aa028580-e5fd-11ea-9872-20bb2d4fbd26.png)

_Originally posted by @skynet01 in https://github.com/custom-components/alexa_media_player/issues/873#issuecomment-679293848_

**Comment by alandtse** [comment]
Please use this PR for [alexapy](https://gitlab.com/keatontaylor/alexapy/-/merge_requests/192) and report logs.

**Comment by Arrheniu2** [comment]
same problem here, this is my log

Detalles de registro (ERROR)
Logger: alexapy.helpers
Source: /usr/local/lib/python3.8/site-packages/alexapy/helpers.py:155
First occurred: 8:57:41 (1 occurrences)
Last logged: 8:57:41

alexalogin.login((<alexapy.alexalogin.AlexaLogin object at 0xa48823b8>,), {'data': {'password': 'REDACTED 11 CHARS', 'captcha': '426n68'}}): An error occured accessing AlexaAPI: An exception of type AttributeError occurred. Arguments: ("'URL' object has no attribute 'decode'",)

i receive an sms from amazon to authorise the login but the component fails before i can click on the link

**Comment by quentino18** [comment]
You can also enable Two-Factor Authentication (2FA) on your amazon account, it solved the issue for me.

**Comment by Arrheniu2** [comment]
> You can also enable Two-Factor Authentication (2FA) on your amazon account, it solved the issue for me.

it worked, thanks

**Comment by glassbase** [comment]
I also added 2FA to my account and working for me again as well. 

Previously to 2FA, I would receive a approve/deny request via text and Amazon app to approve the connection, but I don’t think HA waits for the approval, hence why this integration does not finish setup?

**Comment by denniswham** [comment]
My account is MFA'd but still getting the above error in my log

**Comment by skynet01** [comment]
Thank you, I can confirm that enabling 2fa fixes the issue. Looks like @glassbase is right that integration does not support text message approval feature.

**Comment by denniswham** [comment]
My bad, appending the code from the auth app to the psw did the trick. Thanks!

**Comment by alandtse** [comment]
> Previously to 2FA, I would receive a approve/deny request via text and Amazon app to approve the connection, but I don’t think HA waits for the approval, hence why this integration does not finish setup?

Yes. The issue is no one is willing to help test a fix so we can resolve it since the workaround is so easy. Hopefully one day someone in this state can help me solve it.

**Comment by skynet01** [comment]
I can help, what do you need me to do to debug this

**Comment by alandtse** [comment]
@skynet01 If you can try the alexapy PR in the first reply, enable [debug logging](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component) (please scrub data), and turn on Advanced Debugging, that will help me see if the fix helps or what else we may have to do.

**Comment by alandtse** [comment]
Update, you don't have to download the PR. Just update to the latest as it's already in.

**Comment by alandtse** [comment]
Since the specific decode error is probably resolved now. I'll close this. We are still trying to figure out the login error in #807
