### ISSUE TITLE
Authentication Not Working

### ISSUE THREAD

**Issue by omayhemo** [custom-components/alexa_media_player#885]
Latest Alexa Media Player source, using HACS on a supervised linux install on 114.3

Authentication has stopped working. Initially, gone is the captcha replaced by an OTP. When the OTP received via email from Amazon and entered as requested, it simply asks for it again and again. Authentication fails. Rebooted, captcha was back, it failed repeatedly and locked me out with a message about forgot password screen being detected.

Uninstalled, reinstalled integration. Went through the setup process again, captcha included. Sent link to phone to approve, which I did but the screen in HA Integration just sat there and could not be dismissed with the submit button after a lot of time waiting. Using the X to close the window caused the integration setup to fail.

image

I tried several times.

**Comment by singhj0910** [comment]
Same exact issue here except I was forced to change my password as well. Please fix this.

**Comment by valy2000** [comment]
Please hit confirm to begin login attempt.

Forgot password page detected; Amazon has detected too many failed logins. Please check to see if Amazon requires any further action. You may have to wait before retrying.

**Comment by alandtse** [comment]
Please fill out the template and provide logs or I will not be able to help you.

**Comment by omayhemo** [comment]
The password had not changed when I received this error.  Further, when I removed the integration and reinstalled, a new problem in authentication emerged with the scratch setup.  Please direct me to the logs you need and I will post.

I provided the information about my setup in the OP, I just don't know what logs you're looking for, as there's nothing specific to your component in the home-assistant.log

**Comment by alandtse** [comment]
All instructions are in the template.

**Comment by omayhemo** [comment]
**Describe the bug**
2FA is failing when trying to authenticate the integration upon installation.

**To Reproduce**
Steps to reproduce the behavior:
1. Uninstall Integration
2. From the Integrations page add the integration back
3. Attempt Sign-in with CAPTCHA
4. Receive 2FA code via text message from Amazon
5. Authorize via browser the 'unusual login activity'
6. Click submit on the notification window in HA for the Integration

**Expected behavior**
Once getting to step 6, I expect the window to close and the integration to be installed and configured


**System details**
 - Home-assistant (version): 114.3
 - Hassio (Yes/No): No
 - alexa_media  (version from `const.py` or HA startup): latest from HACS


**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

No logs are generated by this method, instead two HTML pages reflecting the stage one is in with the authentication process.  I'm not sure what value posting them here would have.  Using the login page 'logged' by this method successfully logs in.

**Comment by alandtse** [comment]
You need to enable logs for them to be generated. Again it's in the template link.

**Comment by omayhemo** [comment]
I did that as I stated above.  As I'm using the integration screen, I turned on the Boolean slider for advanced logs.  As per the link posted in the template and re-posted in my previous post:

> This will generate two debug files in the configuration directory.
> 
> alexa_media.(email).get.html - This will show the initial form where the credentials will be input.
> alexa_media.(email).post.html - This is the webpage immediately after submitting login credential data via a post. This will often show Amazon's response indicating a need for 2FA or a captcha.

I described what I found with these two HTML pages in my previous post.  I'm not trying to be difficult here, but I don't know else you believe is in the template link that I need to provide, I'm beginning to get frustrated with your terse responses.

**Comment by alandtse** [comment]
And I am frustrated that you won't enable logs despite the fact is in the template that you ignored from your first post.
```
logger:
  default: critical
  logs:
# for v 1.0.0
    custom_components.alexa_media: debug  
# for API debugging (verbose and intended for service debugging)
    alexapy: debug
```

The template was put in place so I could answer the question from the first reply. The failure to follow the template means I wasted 4 replies already.

**Comment by omayhemo** [comment]
I'm sorry to waste your time.  There's too much PII to post in totality, hopefully you'll take some time to attempt to repro this issue as it's clear several of us encountered it now.  

Reading through the logs, there's nothing unusual as far as I can see with exception of

`2020-08-26 13:05:36 DEBUG (MainThread) [alexapy.alexalogin] WARNING: Detected missing params: ['encryptedPasswordExpected']`

and then at the end where the polling for the 2FA approval occurs each time I click submit.

```
2020-08-26 13:05:37 DEBUG (MainThread) [alexapy.alexalogin] Found url for polling page https://www.amazon.com/ap/cvf/approval/poll
2020-08-26 13:05:37 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Testing login status: {'force_get': True, 'message': 'To complete the sign-in, approve the notification sent to:\nMobile number ***-***-****\nApplication AmazonShopping, iPhone\n'}
2020-08-26 13:05:37 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Creating config_flow to wait for user action
2020-08-26 13:05:53 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Testing login status: {'force_get': True, 'message': 'To complete the sign-in, approve the notification sent to:\nMobile number ***-***-****\nApplication AmazonShopping, iPhone\n'}
2020-08-26 13:05:53 DEBUG (MainThread) [custom_components.alexa_media.config_flow] Creating config_flow to wait for user action
```

**Comment by alandtse** [comment]
> There's too much PII to post in totality, hopefully you'll take some time to attempt to repro this issue as it's clear several of us encountered it now.

That is awfully presumptuous. I've spent more time on this issue then you have and the issue is I cannot reproduce this locally and have requested time and time again for people to provide information so I can resolve this. Please see #807, #840, #846, #870, #872, #880 and now this.

If you had searched, you would've seen the workaround for this is to enable 2FA. Feel free to enable 2FA and then I'll work with someone who wants to resolve this for other people.

**Comment by omayhemo** [comment]
Didn't mean to sound presumptuous, and I apologize for unintended inferences.  Unfortunately I guess my git-fu is weak.  Thanks for the point out sorry, again, to waste your time.

**Comment by omayhemo** [comment]
https://www.amazon.com/gp/help/customer/display.html?nodeId=202073820

For others, so if they search better than I, they don't bother you with this...
