### ISSUE TITLE
Groups / clusters not populated? / Parent playing state

### ISSUE THREAD

**Issue by akaho** [custom-components/alexa_media_player#886]
Is there a particular reason why right now clusters / groups seem to be not populated to HA or are hidden? Is this an issue related to the deviceOwnerCustomerId of the group?
 
I would like to know if a device is currently playing something no matter alone or as part of a group. Maybe this could become an attribute? This would enable me to trigger automatons based on playing music, e.g. I could start my stereo (connected to an echo).

@alandtse btw. thanks for the quick implementation concerning #848

**Comment by alandtse** [comment]
I didn't change that code at all recently. May have broken something with the revamp for #848. I'll take a look.

**Comment by akaho** [comment]
Accessing group info actually never worked with me (not that I remember).

**Comment by akaho** [comment]
Just to be clear: Let `echo` be a device and `group1 ` be a group that includes `echo`.
Then, when radio is playing on `group1 `,  `echo` s state is not PLAYING but e.g. standby.
Furthermore i can not access `group1` via HA (`media_player.group1 `), independent from any playing activity.

**Comment by alandtse** [comment]
I just tested on my system and it still works. I'll need you to help debug this then. The way this works is we use the `parentClusters` info from [devices (fix domain)](https://alexa.amazon.com/api/devices-v2/device) and if the parent is playing, we [mirror](https://github.com/custom-components/alexa_media_player/blob/dev/custom_components/alexa_media/media_player.py#L517,L562) it for child devices.

Is group1 a HA group or a Alexa group?

**Comment by akaho** [comment]
It's an Alexa speaker group. Already checked the devices endpoint. That one is correctly referencing to the devices of the group. When I then check https://alexa.amazon.de/api/np/player?deviceSerialNumber=... with the clusters's device ID, it returns "state":"PLAYING".

**Comment by akaho** [comment]
For debugging purposes I also exposed `self._playing_parent is not None` as an attribute.  It is always false.

**Comment by alandtse** [comment]
What about `self._parent_clusters`. And is the parent group actually updating in HA.

**Comment by akaho** [comment]
What do you mean with:
>  And is the parent group actually updating in HA.

There is no HA entity named `group1` and no other speaker group visible in my HA setup.

len(self._parent_clusters) is always 0 (don't know what dtypes HA is accepting).

**Comment by alandtse** [comment]
If you created a group in Alexa, it should get exposed as a separate entity in HA. If that entity is not created, then there will be no cluster updates if that is playing.

For example, the logs report all media players that are added. In my case, I have an everywhere group.
```text
 2020-08-25 22:11:44 DEBUG (MainThread) [custom_components.alexa_media] a******e@g*******m: Existing: [<Entity Kitchen: paused>, <Entity Everywhere: standby>, <Entity Echo Show: standby>, <Entity Alan's Fire: unavailable>, <Entity Guest Room: standby>, <Entity Master Bedroom: standby>, <Entity Great Room: standby>, <Entity Office: paused>, <Entity This Device: standby>, <Entity Alan's Alexa Apps  unavailable>] New: []; Filtered out by not being in include: [] or in exclude: []
```
Are you filtering the entities from Alexa?

**Comment by akaho** [comment]
It looks like the reason is the second account that is involved. The groups seem not to be shared between accounts (though the devices are). I did a two account setup for security reasons. Maybe I should reconsider this approach.
Thanks for your help!

**Comment by alandtse** [comment]
Glad you figured it out. My only comment would be that to the extent you were adding the account with the group, it should have been picked up. The code doesn't currently care which account a device is under, so it should try to update the info if it determines there is a parent group. Of course, it may have 400 permission errors like we just fixed if the account we're using to query the info doesn't have the permissions.

Please feel free to reopen assuming you do add an account with the group and we can see what we can do.
