### ISSUE TITLE
TTS to Echo Auto doesnt work

### ISSUE THREAD

**Issue by CaptainSweatpants** [custom-components/alexa_media_player#891]
**Describe the bug**
Not sure if it ever did, but all my other echos run TTS just fine, but the Echo Auto seems to ignore them.

**To Reproduce**
Any attempt at sending TTS to an Echo Auto

**Expected behavior**
To speak

**Screenshots**
n/a

**System details**
 - Home Assistant 0.114.1
 - Hassio (Yes/No): No, Raspian 5.4.51-v7l+ with HA running in docker
 - alexa_media version: 2.10.3

**Logs**
Logs are clean. It successfully sent. 

**Additional context**
As mentioned, this may not be a bug, but more a restriction by Amazon. Im just checking to make sure it's not an issue exclusive to my setup.

**Comment by alandtse** [comment]
My understanding is it doesn't work with the Echo Auto. The way to check if it's possible is checkin what the official app does. Are you able to do it using the official Amazon app? You should try both the simon says and the announce options.

**Comment by Sym-bIOTic** [comment]
Is there any update with this ISSUE?

Im facing similar issue:
TTS not send to echo 
![image](https://user-images.githubusercontent.com/56655471/94479789-971f3a00-01d5-11eb-9c45-56a0f28060e3.png)

Simon says on amazon app works well

tts files stored in folder (tts) correctly
![image](https://user-images.githubusercontent.com/56655471/94479919-c9309c00-01d5-11eb-89ad-674af2a729d3.png)

Im using tts: google_translate in my configuration.yaml
Is that correct?

Any suggestions?
