### ISSUE TITLE
Invalid Config

### ISSUE THREAD

**Issue by curt7000** [custom-components/alexa_media_player#896]
**Describe the bug**
Invalid Config after install and restart of HA using Ver. 2.10.5

**To Reproduce**
1. Update to Ver.2.10.5
2. Restart HA

**Expected behavior**
Custom component to load in HA

**System details**
 - Home-assistant (version): 114.4
 - Hassio (Yes/No): No, using VENV on Ubuntu 18.04 LTS Server
 - alexa_media  (version from `const.py` or HA startup): not available sending from mobile
 - alexapy (version from `pip show alexapy` or HA startup): not available, sending from mobile

**Logs**
Not available, sending from mobile.

**Additional context**

**Comment by drako86** [comment]
Same bau i run HA 114.4 core on Debian last vers

**Comment by alandtse** [comment]
Thanks. Probably missing wrapt but can't know without logs. 
```bash
pip install wrapt
```

**Comment by curt7000** [comment]
2.10.6 corrects the Invalid Config issue.  Thanks!  However, I am unable to reauthenticate via Integrations.

**Comment by curt7000** [comment]
Or do I reauthenticate by adding the integration again, over top of the existing?

**Comment by alandtse** [comment]
It won't let you install it twice, but it's safe to remove and readd. It should detect if the authentication needs to be redone automatically and will pop up a notification.

Closing since this fixed the initial reported issue.
