### ISSUE TITLE
Memory usage stop the docker running home assistant

### ISSUE THREAD

**Issue by Thomasdmm** [custom-components/alexa_media_player#901]
**Describe the bug**
Hello since the last udpade several python3 ressource on my nas Synology DS920+ 12gb Ram is grow up to 2,4 GB of memory usage and crash the home assistant docker. Since I have uninstall this integration Alexa media player V2.10.6 phyton3 ressource come back to 300 - 400 Mb.

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details**

arch | x86_64
-- | --
dev | false
docker | true
hassio | false
installation_type | Home Assistant Container
os_name | Linux
os_version | 4.4.59+
python_version | 3.8.3
timezone | Europe/Brussels
version | 0.114.4
virtualenv | false

 - alexa_media  (version from `const.py` or HA startup): 2.10.6
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by alandtse** [comment]
It's hard for me to debug this without more information. Are you seeing log errors? Is it re-logging in a lot? What's the uptime before it crashes? How many Alexa devices are you using? How many Amazon accounts?

In my production system (rpi4) HA only takes 154-158 MiB even with the component so your 300-400 seems like a lot for me even with Alexa_media removed. Is it reproduceable that you enable Alexa_media and it spikes to 2.4GB every time?
