### ISSUE TITLE
Multiple discovered integrations after relogin required

### ISSUE THREAD

**Issue by moranbf** [custom-components/alexa_media_player#903]
**Describe the bug**
 
I've setup the integration and successfully integrated with my user/pass/2factor/captcha, and had everything working as expected with a couple of automations using the media player.  Later I get a notification that I need to re-authenticate, and go to integrations and there are pages of discovered media player integrations, each asking for a re authentication, which if you click on the captcha has expired.

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details**
 - Home-assistant (version): 
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup):

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by alandtse** [comment]
Thanks for the report. If you enter anything in the Captcha it will refresh. Does relogging in work? Does it clear the discovered integrations?

**Comment by eschrip** [comment]
I had a similar problem.  A "discovered" AMP integration, and the original, I ended up just deleting the integrations, assuming I could just add it back, as I have done a few times.

This time however, when I got to the page with the "submit" after I have approved the log in via Amazon, it wouldn't continue.  Pressing the submit re-displayed the dialog.  I have tried on numerous platforms in browsers in case it was something specific to the environment.    I rolled back to the 2.10.4 since that was the version that was working prior.  It did the same thing.  

This problem did not appear when I first upgraded but probably a day or so later after restarting for some other reason.

**Comment by Leapo** [comment]
Yup, seeing the same thing here. Multiple "Discovered" Alexa Media Player integrations, and I can't get any of them to actually work anymore. No error messages...

**Comment by eschrip** [comment]
I just tried again this evening, and now I cant login with the captcha at all.    So getting stuck earlier in the process.

**Comment by eschrip** [comment]
Last FYI.. I bit the bullet and did full two factor authentication and it seems to have let me login.  So it may be that there is some changes in accounts that require this?  But I am back up and running.

**Comment by alandtse** [comment]
Please note enabling 2FA is mandatory for the component. If you haven't, you won't be able to log in.

**Comment by Leapo** [comment]
I have 2 factor enabled but Amazon isn't sending me any kind of code when I log in

**Comment by alandtse** [comment]
This isn't the thread to talk about 2FA. I'll be marking it off-topic. If you have the issue with multiple integrations after it logs out, then I'll help you here.

**Comment by Leapo** [comment]
I have a combination of "multiple integrations" and "it lets me log in but doesn't actually appear to function correctly" and "it isn't sending me a 2FA code even though 2FA is enabled, but login appears to be working anyway because it enumerated all of my echo dots into devices and entities"

**Comment by alandtse** [comment]
@Leapo After logging in you still have multiple discovered integrations? Please enable logs per the template. The functionality issues after login are a separate issue so you'll need to open a new issue.

**Comment by ImEmJay** [comment]
Ran into the same problem yesterday. Had to relogin and discovered a lot of these requests on the integrations page. After i got one of these to login successfully i had to restart HA to get rid of all the others.

**Comment by moranbf** [comment]
So my guess is these queued up over time. The box to authenticate had a
broken picture link for the captcha, and when I clicked on the broken link
I received a message to the effect that the captcha had timed out. I was
able to get things cleared up by re-installing the integration.

**Comment by moranbf** [comment]
I have 2 factor enabled and everything was working fine for a while

**Comment by Kev1000000** [comment]
I have also ran into this issue.  Had 6 integrations "Discovered" and none of them actually work with Alexa :(

**Comment by jrnhrmn** [comment]
Same her. But a lot more then six (more like 80). After a restart there were only two left. One asking for configuration and the other one my original one. Configured the new one: showed only devices and no entities. Then removed this new integration and everything still works fine.
