### ISSUE TITLE
integrations page config: "please enter your information" whatever I enter

### ISSUE THREAD

**Issue by Stooovie** [custom-components/alexa_media_player#904]
**Describe the bug**
Whatever I enter in the integration setup, it tells me to "Please enter your information"
**To Reproduce**
1. Go to HA Integrations page'
2. Click on 'Configure'
3. fill info

**Expected behavior**
Finish config

**System details**
 - Home-assistant (version): 0.14.4
 - Hassio (Yes/No): yes
 - alexa_media  (version from `const.py` or HA startup): 2.10.6

**Comment by alandtse** [comment]
Please provide logs.

**Comment by Stooovie** [comment]
Ah sorry, [here](https://stooovie.quickconnect.to/d/f/574632835661479088)

**Comment by Shadow14-PS** [comment]
Hi, same here with 0.113.3 instead of 0.114.4

**Comment by alandtse** [comment]
Thanks. It doesn't look like you enabled the debug logging per the instructions.

Do you have 2FA enabled on your account? That is mandatory now due to Amazon.

**Comment by Shadow14-PS** [comment]
I will try to activate the logging and get back (little experience with issue reporting), but I think this is related to #903. I have 2FA activated and was working like a charm for a long time, just entering 2FA after updating and sometimes after restarting. Now there is a persistentnotification asking for 2FA but two integrations, the normal one (which is not asking for the code) and the new one with the pop up for the code, after entering the code you get into the issue described in #904.

**Comment by Stooovie** [comment]
I do have 2FA activated, I just don't get the captcha challenge.

**Comment by Stooovie** [comment]
![F2600982-8131-44BB-8616-FDF4FEC4EDBD](https://user-images.githubusercontent.com/10572373/92322707-34ea7380-f033-11ea-826d-8456e369bb9d.png)

**Comment by alandtse** [comment]
I'll have a new release shortly. See if that resolves it as I ironed a bunch of bugs in the config_flow.

**Comment by Shadow14-PS** [comment]
OK, great! I will let you know. Thanks.

**Comment by Stooovie** [comment]
[Here's the log](https://stooovie.quickconnect.to/d/f/574638253655765825) with the debug info. The captcha eventually appeared, the integration was "successfully reauthenticated", I do see music metadata and can control music but I still can't use TTS (it worked before).
I also had two discovered integrations but that's probably because I have two Echo Dots.

**Comment by alandtse** [comment]
@Stooovie Based off your information, it looks like the captcha being missing was tied to something I just fixed in 2.11.0. Since  your original issue fixed itself already and the tts issue may be related to other fixes, can you please update and open a new issue on that specific topic if it persists? I'll close this for now. If you run into the same integration setup issue in 2.11.0, feel free to reopen.
