### ISSUE TITLE
Alexa Media Player - Action Required

### ISSUE THREAD

**Issue by MYLE-01** [custom-components/alexa_media_player#919]
just upgraded 

I click CONFIGURE

do the Captcha thing

then I get the TXT on phone

click the Link approve it

![image](https://user-images.githubusercontent.com/4362345/92429101-10ce9400-f1e5-11ea-9163-506229d3361d.png)

when hit SUBMIT on above screen nothing happen

what do i miss

If i click the x it goes away but the if i hit CONFIGURE again I get above screen up.

IF do a restart of HA we back to the beginning again

**Comment by alandtse** [comment]
Fill out the template. You are required to have 2FA already enabled to use the component. I will not debug issues if your account does not have 2FA.

**Comment by alandtse** [comment]
Please see the [instructions](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account).

**Comment by MYLE-01** [comment]
THANK YOU 

SEE YOU MUST READ MANUAL
