### ISSUE TITLE
Missing dependency: packaging

### ISSUE THREAD

**Issue by mikeage** [custom-components/alexa_media_player#920]
**Describe the bug**
PR #916  replaces semvar with packaging, but this needs to be included in the manifest.json

**To Reproduce**
Install 2.11.1

**Expected behavior**
Works

**Screenshots**
```
2020-09-08 06:10:50 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform alexa_media.sensor: Platform not found (No module named 'packaging').
```

**System details**
 - Home-assistant (version): 0.114.4
 - Hassio (Yes/No):  No
 - alexa_media  (version from `const.py` or HA startup): 2.11.1
 - alexapy (version from `pip show alexapy` or HA startup): 1.14.1
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). n/a

**Logs**
above

**Additional context**

**Comment by alandtse** [comment]
Thanks. You run a minimalist python environment huh? You always keep me honest on these things.

**Comment by mikeage** [comment]
I mean, I actually do, but more specifically, HA Core (at least for me? I never really looked into the details) keeps a virtualenv like setup in ~/.homeassistant/deps, so none of my system packages are used

**Comment by alandtse** [comment]
It's because I do my testing typically on a dev server which has HA dev deps loaded. Packaging is used there but not in production so I missed it here.

**Comment by mikeage** [comment]
Ah, makes sense. Well, glad to be assistance :-)
