### ISSUE TITLE
Stuck on "Alexa Media Player - Action Required"

### ISSUE THREAD

**Issue by oneseventhree** [custom-components/alexa_media_player#924]
**Describe the bug**
After I do this:
![unnamed (1)](https://user-images.githubusercontent.com/15043282/92855049-30f49200-f435-11ea-900e-aecceeb27844.jpg)

This dialogue appears and does not go away when I press 'Submit'
![1](https://user-images.githubusercontent.com/15043282/92855026-29cd8400-f435-11ea-899a-5ce6633ff3b9.png)

**To Reproduce**
1. Go to 'Integrations'
2. Click "CONFIGURE" on 'Alexa Media Player'
3. Enter CAPTCHA code
4. Accept new device with code from SMS
5. Try and click submit

**Expected behavior**
After hitting submit Alexa Media Player is now paired to home assistant.

**Screenshots**
See above

**System details**
 - Home-assistant (version): 0.114.4/HassOS 4.13
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): v2.11.2
 - alexapy (version from `pip show alexapy` or HA startup): 
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: Not inabled. I did enable it to seeif it woruld fix this issue but it didnt help.

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by alandtse** [comment]
You need to leave 2FA enabled. I will not debug login issues if is disabled.

**Comment by oneseventhree** [comment]
I have left it enabled and still having the same problems

**Comment by oneseventhree** [comment]
> You need to leave 2FA enabled. I will not debug login issues if is disabled.

I have left it enabled and still having the same problems

**Comment by alandtse** [comment]
Please remove the integration including removing from your configuration.yaml. Make sure debug logs are enabled and add the integration. If 2FA is enabled, you shouldn't even get to this action required step. But if you do, please provide the logs after scrubbing them per the wiki.

**Comment by oneseventhree** [comment]
> Please remove the integration including removing from your configuration.yaml. Make sure debug logs are enabled and add the integration. If 2FA is enabled, you shouldn't even get to this action required step. But if you do, please provide the logs after scrubbing them per the wiki.

![Untitled](https://user-images.githubusercontent.com/15043282/92867331-dca4de80-f443-11ea-8336-3e3d33c63005.png)

Where am I going wrong here? The code is right, the 2FA code is right and it keeps telling me that I am wrong and then it says this after too many tries:
![sss](https://user-images.githubusercontent.com/15043282/92868375-03afe000-f445-11ea-9fb8-befada990e8a.png)

**Comment by alandtse** [comment]
The 2FA code changes every 30 seconds so make sure that's correct. Also, the error message says your captcha is wrong.  Regardless, without logs I can't help you.

**Comment by oneseventhree** [comment]
> The 2FA code changes every 30 seconds so make sure that's correct. Also, the error message says your captcha is wrong. Regardless, without logs I can't help you.

The 2FA code changing every 30 seconds was the trick.

Thanks
