### ISSUE TITLE
"alexa_media_player_relogin_success" causing DB error: Data too long for column 'event_type' 

### ISSUE THREAD

**Issue by alvaromi** [custom-components/alexa_media_player#926]
**Describe the bug**

When re-configuring login, DB error below is reported in logs:

Error saving events: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (MySQLdb._exceptions.DataError) (1406, **"Data too long for column 'event_type' at row 1"**) [SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id, context_parent_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)] [parameters: ('**alexa_media_player_relogin_success**', ...........

**To Reproduce**
1. get notification to re-configure integration login
2. Click on Integrations link, then click on configure for "Alexa Media Player"
3. Enter credentials/2fa/captcha/etc.
4. Go to Configuration -> Logs

**Expected behavior**
Entry should be properly saved to recorder DB

**Screenshots**
n/a

**System details**
 - Home-assistant (version): 0.114.4 (latest)
 - Hassio (Yes/No): YES
 - alexa_media  (version from `const.py` or HA startup): 2.11.0
 - alexapy (version from `pip show alexapy` or HA startup): 1.14.1
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: YES

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**
I use Maria DB as the recorder DB, but this is likely a common constraint for any other recorder DB config.

**Comment by alandtse** [comment]
What's the length setting for the event_type in the events table? I use postgres so I don't run into this issue.

**Comment by alvaromi** [comment]
It's a varchar(32), "alexa_media_player_relogin_success" is 34 chars.
