### ISSUE TITLE
Integration showing twice, while one unauthenticated?

### ISSUE THREAD

**Issue by membersound** [custom-components/alexa_media_player#936]
![alexa](https://user-images.githubusercontent.com/5269630/93661990-9ad7f180-fa5c-11ea-913c-0360cf1a39af.PNG)

What can I do to remove the unauthenticated integration?
Alexa is working fine, but I cannot remove the unauthenticated integration as there is no remove button for it. Which file do I have to edit to remove it?

**Comment by poudenes** [comment]
I have same issue... and reconfigure won't work. All the time it say password incorrect. (password is correct, tried login on Amazon itself also)

**Comment by poudenes** [comment]
Removing the integration, reboot HA and add it again won't work also ... keeps saying password incorrect

**Comment by alandtse** [comment]
Please fill out the template.

**Comment by sheikhnoyonahmed234-cmd** [comment]
Gemil password back me 🥺 ![Image](https://github.com/user-attachments/assets/c3017c5f-0018-4e62-bd72-f5eb2fe4015a)
