### ISSUE TITLE
Integration showing twice, while one unauthenticated?

### ISSUE THREAD

**Issue by membersound** [custom-components/alexa_media_player#939]
**Describe the bug**
Hassio Integrations page is showing duplicate alexa component, with one unauthenticated.

**To Reproduce**
Go to Configuration > Integrations. See screenshot for result.

**Expected behavior**
Only one component would be expected. As I can send commands to alexa without a problem, the component to the right seems to be fine. But I cannot remove the unauthenticated component, as there is no removal button for it.

**Screenshots**
![93661990-9ad7f180-fa5c-11ea-913c-0360cf1a39af](https://user-images.githubusercontent.com/5269630/93717631-52612680-fb77-11ea-937b-a93b3c7b9511.PNG)

**System details**
 - Home-assistant (version): 0.115.1
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup): 3.0.0
 - alexapy (version from `pip show alexapy` or HA startup): I searched the whole /custom_components folder, but could not find any file called `alexapy`. If you guide me, I could add the version.
 - Amazon [2FA is enabled]: yes

**Additional notes**
Follow up from https://github.com/custom-components/alexa_media_player/issues/936

**Comment by alandtse** [comment]
The component has detected that you needed to relogin. Some functionality may remain even when this happens as Amazon is strange like that.

Once you reauthenticate the discovered component will disappear. This is how HA handles reauths.

**Comment by membersound** [comment]
Strange thing is that relogin is not possible. I have 2FA enabled, and when hitting the Submit button, no token is send to me. Thus I need to find a way to get rid of the duplicate component here...

**Comment by poudenes** [comment]
@membersound had same problem. I did it without filling in 2FA. I get a popup to enter the 2FA and Amazon was sending me a code. That did the trick for me

**Comment by alandtse** [comment]
Per the [documentation,](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) It's highly recommended to use an authenticator app.

**Comment by poudenes** [comment]
@alandtse i have this already but still it wasn't work. So I did the first screen without 2FA filled in. Then get popup to enter a 2FA code. Amazon send me one to my mobile... When I use the authenticator app it isn't work.
