### ISSUE TITLE
HA integration not working after 0.115.2 update

### ISSUE THREAD

**Issue by Eric-boop** [custom-components/alexa_media_player#942]
**Describe the bug**
I can't get my Alexa Media Player integration to work. It was working before the 0.115.2. But now I can not get hooked up. I have been trying for the last 24 hrs. I have tried the 2FA and non 2FA. Nothing works. I am getting incorrect password, not! I have done this so many times, I am getting a too many attempts, you have to wait...arggg
This all started with the upgrade to 0.115.2 with a new captcha required. It would not take.

**To Reproduce**
1. I'm doing the same as I have done many time before to get it to integrate.
2. configure/integration/+/Add Alexa Media Player
3. Add email, add password, submit
4. Add captcha
5. Getting wrong password. I have tried changing amazon password and still getting the same results. I have also enabled the 2FA and it still is giving me incorrect password.

**Expected behavior**

**Screenshots**

**System details**
 

arch | aarch64
-- | --
chassis | embedded
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.13
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.127-v8
python_version | 3.8.5
supervisor | 245
timezone | America/New_York
version | 0.115.2
virtualenv | false

This looks like a HA bug).
 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: 

**Logs**
Log Details (WARNING)
Logger: alexapy.alexalogin
Source: /usr/local/lib/python3.8/site-packages/alexapy/alexalogin.py:686
First occurred: 10:35:28 AM (4 occurrences)
Last logged: 11:44:47 AM

Forgot password page detected; Amazon has detected too many failed logins. Please check to see if Amazon requires any further action. You may have to wait before retrying.
**Additional context**

**Comment by poudenes** [comment]
What for me work was enter Email, Password and correct Amazon Region. Then Submit. I got a screen to enter the 2FA, 2FA was send to my mobile by Amazon. That worked for me

**Comment by Eric-boop** [comment]
First it started off just needing a captcha. I got the same message, incorrect password. I uninstalled the HACS add-on and the integration said it was fine with all my all entity, I go the the entity list and it shows them all unavailable. So I deleted the integration. Than I installed the HACS add-on and the integration, go thru the setup steps like I have had to do at least 8 times in the last six months, and all I get is a incorrect password. I know my password and I waited overnight. Changed the amazon/alexa password, and still same results.

**Comment by Eric-boop** [comment]
If 2FA is required, I enabled it for Amazon and got the code to enable it. Then went thru the steps to integrate into HA, Email, password and tried adding the code I had into the setup where it says 2FA, then submit brings me to the capcha window. Now I tried with a 2FA in the first window and without. I never got a window for just the 2FA or a SMS or email 2FA code.

**Comment by jgthornburgh** [comment]
Mine isn't sending a 2FA. I can get here, but haven't been able to get further in a couple weeks. this started before 115, and I have updated to the latest HACS and Integration. 
![image](https://user-images.githubusercontent.com/44178327/94096631-6906b800-fdd9-11ea-934f-7acab06dfc70.png)

**Comment by H2YxAQEeeQYpD2nB** [comment]
the same as jgthornburgh  -- unable to get 2FA from Amazon
the only way is to use token Authenticator app, not SMS response

**Comment by crisflashin** [comment]
Hi guys. I have 2FA and i got the same problem, so is not something from there

**Comment by poudenes** [comment]
I changes my way of getting 2FA from AuthApp to SMS. I got a 2FA send to SMS when I got the only 2FA Popup screen. Enter it and everything here is ok now.

**Comment by Eric-boop** [comment]
> I changes my way of getting 2FA from AuthApp to SMS. I got a 2FA send to SMS when I got the only 2FA Popup screen. Enter it and everything here is ok now.

How did you get the popup screen? Did you fill anything in the 2FA line in the first window?

**Comment by Eric-boop** [comment]
I'm thinking that there is some sort of data file that is holding onto my non 2FA setup? But it sounds like when submitting the email and password, that Amazon should kick back the 2FA requirments. That's just not happening for me. Just the captcha window comes up. Or is the captcha window the popup you are talking about. And my missing piece is I'm not receiving the SMS 2FA code?

**Comment by Eric-boop** [comment]
I still do not know why the non 2FA method that I have used several times is not working?

**Comment by poudenes** [comment]
When I tried to add all info include 2FA from Authenticator App I get errors, was not able to finish. The way how I told you do to without 2FA on first screen worked for me... so im happy that Alexa is speak to me again :D

**Comment by Eric-boop** [comment]
Okay, I got it to work with 2FA. I think the problem was the Amazon 2FA setup. Do not select to disable OTP on this machine.

**Comment by omayhemo** [comment]
Where did you make that change?
