### ISSUE TITLE
HA 0.115.4: play_music() got an unexpected keyword argument 'extra'

### ISSUE THREAD

**Issue by genem2** [custom-components/alexa_media_player#957]
It looks like HA 0.115.4 is jamming us up with play_music()

Upon HA start, my R2D2 sound fails with:
```
2020-09-28 07:52:48 WARNING (MainThread) [alexapy.helpers] alexaapi.play_music((<alexapy.alexaapi.AlexaAPI object at 0x14f924dde5b0>, 'AMAZON_MUSIC', 'Robot Talk 2 by Soundsmack '), {'customer_id': 'A3**********NJ', 'queue_delay': 1.5, 'extra': {}}): An error occured accessing AlexaAPI: An exception of type TypeError occurred. Arguments:
d("play_music() got an unexpected keyword argument 'extra'",)

```
I reverted to 0.115.3 twice and this is only happening on 0.115.4.

**System details**

```
arch	x86_64
dev	false
docker	true
hassio	false
installation_type	Home Assistant Container
os_name	Linux
os_version	4.19.107-Unraid
python_version	3.8.5
timezone	America/Los_Angeles
version	0.115.3
virtualenv	false
```

**Logs**
I enabled detailed logs & can provide if you'd like, but I didn't see anything else in there...

**Comment by alandtse** [comment]
Thanks. It seems odd that they'd change the play_music feature in a minor revision but I'll look.

**Comment by nicolap75** [comment]
Same for me

**Comment by alandtse** [comment]
New build is building. Should address this. This also means that HA is providing additional functionality we can use for play_music such as volume passing or setting timers for how long we can play.

**Comment by genem2** [comment]
Thank you! We appreciate your continued and prompt support on this.
