### ISSUE TITLE
Unhandled command: PUSH_DEVICE_SETUP_STATE_CHANGE

### ISSUE THREAD

**Issue by slomanl1** [custom-components/alexa_media_player#959]
**Describe the bug**
Warning message from Alexa Media Player integration indicating an unhandled command.

**To Reproduce**
See log snippet below

**Expected behavior**
Warning message below occurs approximately once per hour

**Screenshots**
NA

**System details**

**Logs**

2020-09-28 19:04:53 WARNING (MainThread) [custom_components.alexa_media] Unhandled command: PUSH_DEVICE_SETUP_STATE_CHANGE with data {'destinationUserId': 'A*********ESH', 'state': 'DISCOVERED', 'eventSuccess': True, 'deviceType': None, 'deviceSerialNumber': '', 'productIndex': 'FZdX', 'reconnectSession': False, 'timestamp': None}. Please report at https://github.com/custom-components/alexa_media_player/issues

**Additional context**

**Comment by alandtse** [comment]
Thanks. We haven't seen this message before. Did you recently add any Alexa devices or perform any setup operations?

**Comment by slomanl1** [comment]
> Thanks. We haven't seen this message before. Did you recently add any Alexa devices or perform any setup operations?

I recently added a Yamaha Sound Bar Model YAS-209. I t has Alexa built in. I noticed the media player does show the Switch input source selection (HDMI, BLUETOOTH, TV......

**Comment by alandtse** [comment]
The source is based on what we know. I don't have a Yamaha Sound Bar so I'm unlikely to be able to figure out how to manipulate it's sources if at all.

Have you fully configured the device already with Alexa? I'm not sure what this particular command is other than from reading it which indicates there's a setup state change.

**Comment by slomanl1** [comment]
> > Thanks. We haven't seen this message before. Did you recently add any Alexa devices or perform any setup operations?
> 
> I recently added a Yamaha Sound Bar Model YAS-209. It has Alexa built in. I noticed the media player does not show the Switch input source selection (HDMI, BLUETOOTH, TV......



> The source is based on what we know. I don't have a Yamaha Sound Bar so I'm unlikely to be able to figure out how to manipulate it's sources if at all.
> 
> Have you fully configured the device already with Alexa? I'm not sure what this particular command is other than from reading it which indicates there's a setup state change.

Voice control works for changing the input source in accordance with the Yamaha instructions. I tried to use the Developer tools to send a service call to change the source: 
media_player.select_source
entity_id: media_player.paul_s_yamaha_yas_209
source: HDMI
It does not work.

**Comment by alandtse** [comment]
Yes, it wouldn't work because it's not setup so we can access the source list for that. We can only implement what we have access to.

Can you please answer on whether it has any additional configurations required or if it's setup? I'm trying to see if we can figure out what the unhandled command represents.

**Comment by slomanl1** [comment]
> Yes, it wouldn't work because it's not setup so we can access the source list for that. We can only implement what we have access to.
> 
> Can you please answer on whether it has any additional configurations required or if it's setup? I'm trying to see if we can figure out what the unhandled command represents.

Sorry, I was busy buying you a coffee. I used both the iOS and Android apps to set up the sound bar. There is no Alexa Skill for it. I can control all functions of the sound bar with the phone apps. I'm not sure why the service call is not working.

**Comment by alandtse** [comment]
Thanks I saw that. Thank you! 

The service call doesn't work because we haven't implemented it. The original Echo didn't have any source inputs beyond bluetooth which should work. Other inputs won't work unless someone with the device is able to figure out how it works and implement it.

**Comment by bjackson** [comment]
I have the same message in my logs. I haven't added any devices to Alexa lately, but I do have an Ecobee device with built in Alexa capabilities. 

```
Logger: custom_components.alexa_media
Source: custom_components/alexa_media/__init__.py:738 
Integration: Alexa Media Player (documentation, issues) 
First occurred: 10:15:15 AM (83 occurrences) 
Last logged: 9:40:07 PM

Unhandled command: PUSH_DEVICE_SETUP_STATE_CHANGE with data {'destinationUserId': 'A**********OJT', 'state': 'DISCOVERED', 'eventSuccess': True, 'deviceType': 'A1RABVCI4QCIKC', 'deviceSerialNumber': '', 'productIndex': 'g7C4', 'reconnectSession': False, 'timestamp': None}. Please report at https://github.com/custom-components/alexa_media_player/issues
Unhandled command: PUSH_DEVICE_SETUP_STATE_CHANGE with data {'destinationUserId': 'A**********OJT', 'state': 'DISCOVERED', 'eventSuccess': True, 'deviceType': None, 'deviceSerialNumber': '', 'productIndex': 'FZdX', 'reconnectSession': False, 'timestamp': None}. Please report at https://github.com/custom-components/alexa_media_player/issues
```
