### ISSUE TITLE
Alexa, turn off the screen

### ISSUE THREAD

**Issue by nicolap75** [custom-components/alexa_media_player#961]
It would be nice to have at the end of the home assistant automations the possibility to turn off the screen of Echo show 5 or 8 or 10.
The voice already works when I say "Alexa, turn off the screen".

thx
N.

**Comment by alandtse** [comment]
Can you do it in the Alexa app?

**Comment by nicolap75** [comment]
by voice you can do, within the app I could not find.

**Comment by alandtse** [comment]
Then we won't be able to do this as we can only do what is exposed to the app.
