### ISSUE TITLE
QUESTION: Alexa Gadgets API - timer token

### ISSUE THREAD

**Issue by kkellner** [custom-components/alexa_media_player#963]
This is a Question, not a feature request.

I'm using the Alexa Gadgets API to connect to Echo via Bluetooth to get "timer" information (link to API below).  The API uses a "token" for a unique identifier for each timer that is set.  The timer "token" (unique key for the timer instance) is used to track timer changes and cancels.  

I'm trying to associate these timers with the ones returned from this HA Alexa add-on but have been unable to find a matching value between the two JSON values.

From Gadget APIs:  (Look for the "token" property in the below JSON)
```
{ {'header': {'namespace': 'Alerts', 'name': 'SetAlert', 'messageId': '', 'dialogRequestId': ''}, 'payload': {'token': '1122472508', 'type': 'TIMER', 'scheduledTime': '2020-09-30T14:23:38-06:00', 'assetPlayOrder': [], 'loopPauseInMilliSeconds': 0, 'assets': [], 'loopCount': 0, 'backgroundAlertAsset': ''}} }
```

From add-on JSON:  (Can't find a match for the Gadget API token value `1122472508`)
```
[["230ac9db-fe6d-36f4-acac-5b553c2e738f", {"alarmTime": 0, "automationId": null, "createdDate": 1601468618740, "deferredAtTime": null, "deliveryType": null, "deviceName": null, "deviceSerialNumber": "G090VC0123450A0H", "deviceType": "A32DOXYZA6DTXA", "extensibleAttribute": null, "geoLocationTriggerData": null, "id": "A32DOXYZA6DTXA-G090VC0123450A0H-230ac9db-fe6d-36f4-acac-5b553c2e738f", "lastOccurrenceTimeInMilli": 0, "lastUpdatedDate": 0, "loopCount": null, "mrmGroupContext": null, "musicAlarmId": null, "musicEntity": null, "notificationIndex": "230ac9db-fe6d-36f4-acac-5b553c2e738f", "originalDate": null, "originalTime": null, "personProfile": null, "provider": null, "rRuleData": null, "recurrenceEligibility": false, "recurringPattern": null, "remainingTime": 28798000.0, "reminderAppLabel": null, "reminderLabel": null, "reminderSubLabel": null, "skillInfo": null, "snoozedToTime": null, "sound": {"displayName": "Simple Timer", "folder": null, "id": "system_alerts_melodic_02", "isChildDirected": false, "pricing": null, "providerId": "ECHO", "sampleUrl": "https://s3.amazonaws.com/deeappservice.prod.notificationtones/system_alerts_melodic_02.mp3"}, "status": "ON", "targetPersonProfiles": null, "timeZoneId": null, "timerLabel": null, "tmwNotificationProperties": null, "triggerTime": 0, "type": "Timer", "version": "3"}]]
```

Any ideas how to match a timer returned from Gadgets API and the JSON returned from HA add-on? 

Gadgets API docs:
https://developer.amazon.com/en-US/docs/alexa/alexa-gadgets-toolkit/alerts-interface.html#SetAlert-directive

**Comment by alandtse** [comment]
I don't use the Gadgets API so no idea. If you figure it out we have a wiki or you can submit a PR.

**Comment by kkellner** [comment]
I'm closing this question.   The data is simply not available.    

The Alexa Gadgets API seems to have its own unique key (called a token) for each timer.  I have not figured out how this "token" relates to the data returned from `/api/notifications`.   Maybe it's a hash of the `notificationIndex` or the `id`.   In any case, no obvious way to associate timer information between the two types of APIs.
