### ISSUE TITLE
Add property to active timers JSON that is the exact time a timer will expire

### ISSUE THREAD

**Issue by kkellner** [custom-components/alexa_media_player#964]
# Feature request: 
Add property to active timers JSON that is the exact time a timer will expire.

# Background
I need the exact time each timer will expire (not just the next timer).   It seems like the raw JSON data should be enough to get the answer, but I'm always off by a few seconds when I try to calculate it myself.  I would be nice if the raw JSON has a property (e.g., `expireTime`) that would be the exact time the timer was to expire.  This would be the same value that is getting returned for the entity itself but add this value to the raw JSON of each timer so that its available for not just the "next timer" but for all active timers.

# Example of Issue
Below is the output of a template (run via the Developer Tools-->Template page).  Note that the calculated values is 2 seconds different then the value returned from the entity.  `14:23:36` vs `14:23:38`
```
 From raw JSON data:
key: 230ac9db-fe6d-37f4-acac-5b553c2e738f
expireTime: 2020-09-30 14:23:36
---
From the next timer value:
States: 2020-09-30T14:23:38-06:00
```

Here is the template:
```
{% set timers = state_attr('sensor.front_room_dot_next_timer', 'sorted_active') | from_json %}
{% for timerTokenData in timers %}
 {% set timerData = timerTokenData[1] %}
From raw JSON data:
key: {{ timerTokenData[0] }}
expireTime: {{ ((timerData.createdDate + timerData.remainingTime )/1000) | timestamp_local   }}
{% endfor %}
---
From the next timer value:
States: {{ states('sensor.front_room_dot_next_timer') }}
```

**Comment by alandtse** [comment]
All of the raw JSON data we have is already provided to the user.  Timers need to be calculated as they are not absolute in the [API](https://alexa.amazon.com/api/notifications). Please note pausing doesn't change the `createdDate` last I checked so I'm not aware of any absolute value we can grab. There is also some lag in when the request is received by HA (I have no idea why it's so variable as we're all using aiohttp).  If this has changed, then please let me know.

Regardless, feel free to submit a PR if you can figure out a way to accurately pull and calculate it.

**Comment by kkellner** [comment]
I see what you mean that the Alexa API does not return an absolute value.  Bad Amazon design. 

Well it seems that the value for the "next_timer" (for the sensor) is within 1 second (and often dead on) from what is expected.  However when I try to calculate the value via the RAW json, I can get 10+ seconds off.  I believe what is happening is the following code is executed quickly after the API call is made and hence has a very high accuracy.

https://github.com/custom-components/alexa_media_player/blob/dev/custom_components/alexa_media/sensor.py#L447

However when I try to do the same calculation from the RAW JSON within an HA template, HA can take awhile to go through all the state changes before it then interpretes my template and finally does the calculation.  By this time several seconds (sometimes as much as 10) has passed and since `remainingTime` is frozen in time, and I don't know how much time has passed, the result is inaccurate.

So I'm wondering if we can add the calculated value from [here](https://github.com/custom-components/alexa_media_player/blob/dev/custom_components/alexa_media/sensor.py#L447) into the raw JSON values(s) -- e.g., an `expireTime` into each timer that is in the `sorted_active` list.  This way the value is as close in real-time as we can get to "snapshotting" when each timer will expire.   Just an idea.

If you don't like the idea of adding a synthetic property to the sorted_active JSON, we could create another attribute of the sensor that is just an map of timer id and calculated expire time. 

Note the new `expireTimes` attribute in below example:

```
recurrence: Never Repeat
prior_value: 2020-10-01T07:59:23-06:00
expireTimes: ['8734d10a-16ef-34e4-bb21-d6e775d59705': 1601557095376,
   '50cdbd6a-4686-31d7-a8a6-a17c344c4714': 1601557183950]
total_active: 2
total_all: 12
sorted_active:  ....
```

**Comment by alandtse** [comment]
Have you tried using the last_changed or last_updated attribute instead of now()? That won't have any drift due to the system due to the local system.

As a note, what is your actual goal? I am about to introduce event firing when a notification goes off as I found a way to calculate it that seems accurate enough.

**Comment by kkellner** [comment]
So if I use `last_updated` to calculate the value and compare that to the `NextTimer`, I can get a variance.  Sometimes its in-sync but sometimes it's off by many seconds.   So the timestamp used to calculate `NextTimer` internally is not the same timestamp returned by `last_updated`.  This is the reason it would be helpful to either include the internally calculated time (which is accurate) in the attributes, or expose the timestamp used [from here](https://github.com/custom-components/alexa_media_player/blob/dev/custom_components/alexa_media/sensor.py#L447) to calculate the remainingTime as an attribute so that a template can calculate all timers accurately. 


Example:
```
From raw JSON data:
CalcNext:  2020-10-01T16:37:47-0600  1601591867.509802 
NextTimer: 2020-10-01T16:37:44-06:00 1601591864.0 
Diff: 3.5098021030426025
```

Test Template Script that produced the above output:
```
{% set timers = state_attr('sensor.tv_room_next_timer', 'sorted_active') | from_json %}
{% for timerTokenData in timers %}
 {% set timerData = timerTokenData[1] %}
 {% set expireTime =  (timerData.remainingTime/1000 + as_timestamp(states.sensor.tv_room_next_timer.last_updated)) %}
From raw JSON data:
key: {{ timerTokenData[0] }}
CalcNext:  {{ expireTime | timestamp_custom("%Y-%m-%dT%H:%M:%S%z")  }}  {{ expireTime }} 
NextTimer: {{ states('sensor.tv_room_next_timer') }} {{ as_timestamp(strptime(states('sensor.tv_room_next_timer'), "%H:%M, %Y-%m-%d")) }} 
Diff: {{ expireTime - as_timestamp(strptime(states('sensor.tv_room_next_timer'), "%H:%M, %Y-%m-%d")) }}
{% endfor %}
```

# Actual Goal
To you question of the actual goal:  I need the exact expiration time (as accurately as possible given the limitations of the Alexa API) for ALL active timers.

The use case for me is a remote LED matrix display that shows all alexa timers.  Currently its controlled via a Raspberry PI with a bluetooth connection to a echo dot via the Alexa Gadgets API.  This works well and is very accurate as the timer counts down to zero on the display, the echo dot plays its alert tone.   The problem is that it only shows timers from the 1 echo dot that the bluetooth is paired with.   What I want is to display all timers (from all echo devices).   To achieve this I'm looking to abandon the bluetooth method and switch to having HA with this addon to send the timer expire information to the raspberry pi.   To make this work well, the timer expire needs to be within a second or so otherwise the LED display countdown is not in sync with the echo playing the alert tone.

**Comment by kkellner** [comment]
What I need is access to this timestamp:

https://github.com/custom-components/alexa_media_player/blob/dev/custom_components/alexa_media/sensor.py#L358

Where does this timestamp come from?   Is it exposed anywhere that can be access via a template?

**Comment by alandtse** [comment]
No, it's not exposed. If that's all you want, just [subtract](https://github.com/custom-components/alexa_media_player/blob/dev/custom_components/alexa_media/sensor.py#L447-L448) out the 'timeRemaining' from the sensor value and you'll have the value. 

It's generated when we contact the [API](https://github.com/custom-components/alexa_media_player/blob/dev/custom_components/alexa_media/__init__.py#L455).

**Comment by kkellner** [comment]
When you say "from the sensor value", how to I get this value (timestamp) from a template?

**Comment by kkellner** [comment]
FYI, I just hacked the code to insert a `timestamp_base` into the attributes and it's the exact time I need to perform all the calculations.   If this timestamp is already available via some other way, please let me know.  If not, can I request that it be added?

This was my quick and dirty change:  (added 'timestamp_base')

```

        attr = {
            "recurrence": self.recurrence,
            "prior_value": self._process_state(self._prior_value),

            "timestamp_base": 
                dt.as_local(
                        datetime.datetime.fromtimestamp(
                            self._timestamp.timestamp()
                        )
                ).isoformat()
                if self._timestamp
                else STATE_UNAVAILABLE,   

            "total_active": len(self._active),
            "total_all": len(self._all),
            "sorted_active": json.dumps(self._active, default=str),
            "sorted_all": json.dumps(self._all, default=str),
        }
```

**Comment by kkellner** [comment]
Looking at the code you referenced, a better name for the new attribute would have been `process_timestamp`

**Comment by alandtse** [comment]
I don't do templating so I don't know. You can ask the forums. Feel free to submit a PR if you want. Please make sure it doesn't break alarm and reminders though.

**Comment by kkellner** [comment]
Created PR https://github.com/custom-components/alexa_media_player/pull/966.  This PR adds a new attribute to notification sensors called `process_timestamp`.  The value of this attribute provides access to HA templates allowing very accurate calculations of *all* future timers.

I verified alarms, notifications, timers to ensure nothing broke.

**Comment by alandtse** [comment]
Thanks merged it in. It's in dev. Probably release it this weekend.  

With that I assume this issue is closed. Let me know if you think otherwise.
