### ISSUE TITLE
There was a problem Your password is incorrect

### ISSUE THREAD

**Issue by mkanet** [custom-components/alexa_media_player#965]
**Describe the bug**
"There was a problem  Your password is incorrect" when using 2FA for the Integration.

**To Reproduce**
1. Go to 'Integrations'
2. Type latest password
3. Enter 2FA Code (from 2FA app)
4. I keep getting the error message:  "There was a problem  Your password is incorrect"..  then start getting Captcha prompts subsequently.  I don't have any problems logging into the amazon webpage using 2FA and my current password.  The only thing to note is I changed my Amazon password earlier today.  It appears the Integration isn't able to verify the most recent password change to my Amazon account.

**Expected behavior**
Alexa Media Player integration should allow authentication after entering the correct 2FA and amazon account\password.

**Screenshots**

**System details**
 - Home-assistant (version):  Home Assistant 0.115.6
 - Hassio (Yes/No): Not sure if I have HASSIO or not.
 - alexa_media  (version from `const.py` or HA startup): 3.1.2
 - alexapy (version from `pip show alexapy` or HA startup): 1.15.2
 - Amazon [2FA is enabled]: Yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**
I have tried using the below configuration lines (specifying the correct username/password .. as well as enabling them (referring to the correct secret username/password in my secrets.yaml file).  I have also tried commenting out those lines and restarting Home Assistant.  No matter what I do, Alexa Media Player Integration doesn't know how to verify the correct Amazon account password.
```
alexa_media:
  accounts:
    - email: !secret amazon_username
      password: !secret amazon_password
      url: amazon.com
```

Please tell me how to force the Alexa Media Player Integration to recognize the correct password that's on my Amazon account.

**Comment by alandtse** [comment]
Please fill out the template fully.

**Comment by mkanet** [comment]
@alandtse, sorry.  I didn't know the answers to a few questions in the template.  If you could please tell me what specific information you need; and, how/where to get it, I would be happy to do that.

Anyway, I'm using Home Assistant version 0.115.6 (VirtualBox VM running under Windows 20 Version 2004).  


 **- Hassio (Yes/No):**    Not sure if I have HASSIO or not.
    
 **- alexa_media  (version from `const.py` or HA startup):**  I don't know how to retrieve this information.

 **- alexapy (version from `pip show alexapy` or HA startup):**  I don't know how/where to retrieve this information.

Please find my **home-assistant.log** file (with detailed debug enabled) below:

[home-assistant.log](https://github.com/custom-components/alexa_media_player/files/5315744/home-assistant.log)

PS:  I am certain I am using the correct username/password.

Thank you for your time.

**Comment by alandtse** [comment]
Most of it is in the log. However, there's no error with the component based on the logs. The logs indicate you didn't fill in the captcha.

Assuming your password is correct in the configuration.yaml, Amazon is requiring the 2FA from you at the beginning. You need to type in the 2FA code without spaces and enter it right at the beginning. 

If you're using configuration.yaml, you have to update it in your secrets.yaml file. You can also remove the configuration.yaml entry and manually type it all in on the integrations page.

**Comment by mkanet** [comment]
Thanks, it worked perfectly!  It looks like I was waiting too long before entering the 2FA code also, I was sometimes incorrectly adding spaces in the 2FA code.
