### ISSUE TITLE
[Feature request] Initiate call to other Alexa devices or Skype users

### ISSUE THREAD

**Issue by sgofferj** [custom-components/alexa_media_player#974]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like to trigger a call from an Alexa device to another Alexa device or a Skype user. My current application would be an integration into my HA alarm routine. The idea is that in case of an alarm, HA initiates a call from an Echo device to my Alexa phone app. Naturally, I can then listen in and decide what to do about the alarm.
Other possible applications would include panic or assistance call functions e.g. for elderly people.

**Describe alternatives you've considered**
The alternative is to put all phones in the apartment into speakerphone mode, throw them into a conference, call my mobile phone and throw that into the conference too. I have implemented that in my asterisk PBX but the quality is bad due to feebacks and the phone mics only being designed for close range. The quality of the Echo mics is much better.

**Additional context**
I can trigger an Alexa to Alexa call by adding myself to my contacts in the phone app and then either say "Alexa, call Stefan Gofferje's Alexa" or just initiate a call or drop in from the app. Skype works analogously ("Alexa, call Stefan Gofferje on Skype").

**Comment by alandtse** [comment]
Can it be done with routines? That's the easiest way for us to mimic it. Anything else may be more difficult as we'd have to reverse engineer what the app is doing.

**Comment by sgofferj** [comment]
Doesn't look like it's possible.

**Comment by alandtse** [comment]
I'll leave this open in case someone figures out how Amazon's app does it.

**Comment by alandtse** [comment]
Check out if https://github.com/custom-components/alexa_media_player/wiki#run-custom-command allows this now.

**Comment by sgofferj** [comment]
Yeah, that seems to work!
At least, I can trigger call to other Alexa devices.

**Comment by alandtse** [comment]
Ok, so I'll close this then.
