### ISSUE TITLE
update_last_called Slow Response

### ISSUE THREAD

**Issue by pdgithub78** [custom-components/alexa_media_player#982]
**Describe the bug**
The update_last_called service has become very slow to update. Taking around 10-20 seconds to update. I have noticed this on 0.116.2. When reverting back to 0.115.0 it is no longer slow.

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details**
 - Home-assistant (version): 0.116.2
 - Hassio (Yes/No): Yess
 - alexa_media  (version from `const.py` or HA startup): 3.2.2
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: No

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by alandtse** [comment]
There were no changes to the code. This is likely a HA issues.

**Comment by 3ative** [comment]
I too have noticed this behaviour - While the **last called** device changes, I've noticed the time stamps on it and all other media_players gets updated too.
This maybe the reason for HA getting confused and flip-flopping between players.

**Comment by 3ative** [comment]
Fixed with update - Now a moot issue. Closing.
