### ISSUE TITLE
Reauthentication creates second account entry

### ISSUE THREAD

**Issue by Trev-W** [custom-components/alexa_media_player#987]
**Describe the bug**
Reauthenticating causes second instance of account to be created
**To Reproduce**
1. Go to '.Integrations.'
2. Click on '.configure..'
3. Scroll down to '..complete authentication.'

**Expected behavior**
Notification of requirement to reauthenticate should dissappear from sidebar and only 1 account should be visible in inegration panel

**Screenshots**
Sorry can't provide screenshot as already "rectified" by deleting bottom-most account, this also cleared the notification.
**System details**
 - Home-assistant (version): 0.116.4
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug). yes
 - alexa_media  (version from `const.py` or HA startup):3.2.2
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: yes

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by alandtse** [comment]
Thanks. This is how HA does a reauth. Once you reauthenticate the account labeled attention required, the extra should disappear.

**Comment by mwunderling** [comment]
Am piggybacking on this issue since my question is related.  So far, reauth has worked, takes about a min once you cycle through the recaptcha & MFA, but am having to do so now every 2wks or so. Is this the new nomal? Anything that can be done to lengthen the time between reauth events?

**Comment by mikesalz** [comment]
I think this is a related issue.  I am stuck on this authentication screen.  I have uninstalled, reinstalled, restarted, clicked the link to approve the sign-in, and even clicked my heels together many times. Nothing works! 

![image](https://user-images.githubusercontent.com/46855061/96629963-4daca100-12e2-11eb-8c57-c95ae8d45b98.png)

**Comment by mikesalz** [comment]
@alandtse My previous comment was marked as off-topic, even though I am fairly certain it is related. So what happens now?  It just gets ignored?  There are others encountering the same issue, which you'll see on [this thread](https://community.home-assistant.io/t/echo-devices-alexa-as-media-player-testers-needed/58639/4319).
