### ISSUE TITLE
Problem trying to use TTS

### ISSUE THREAD

**Issue by rubenltp** [custom-components/alexa_media_player#991]
Hi,
I'm trying to use this integration, and I have configured successfully the devices, at least the devices are showing in hassio; but the state many times is unavailable.
Also, I can't send  TTS using the notify.alexa_media, neither the notify for the echo device.
Anyone can help me?

**Comment by alandtse** [comment]
Read the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ#all-my-media_players-are-unavailable-and-the-component-doesnt-work).
