### ISSUE TITLE
Alexa Media Player - Not found on Configuration->Integrations

### ISSUE THREAD

**Issue by NapalmCandy** [custom-components/alexa_media_player#992]
I installed Alexa Media Player with HACS, I restarted then, I go to Configuration->Integrations->Click on orange circle, to add a new integration, but it do not show Alexa Media Player, I can't add it

Home Assistant last version 
Hassio, Yes

**Comment by alandtse** [comment]
Hard [refresh ](https://fabricdigital.co.nz/blog/how-to-hard-refresh-your-browser-and-clear-cache)your browser cache.
