### ISSUE TITLE
Alexa configuration details missing text

### ISSUE THREAD

**Issue by UmbeMont** [custom-components/alexa_media_player#993]
**Describe the bug**
upgrading to latest version of HA , and replacing the pi 3 to pi4 the integration was asking a reauth in loop.
disinstalled everything and during the reinstall the main mask is as below

**To Reproduce**
1. Go to integration add alexa media

**Expected behavior**
a mask with contents

**Screenshots**

<img width="390" alt="image" src="https://user-images.githubusercontent.com/60969724/97088771-12380c80-162b-11eb-9774-eab763758fad.png">

**System details**
 - Home-assistant (249): 
 - Hassio (Yes/No): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media  (latest):
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). We will not debug login issues if unanswered: 

**Logs**
Please provide [logs](https://github.com/custom-components/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). We'll be most likely asking for them anyway.

**Additional context**

**Comment by alandtse** [comment]
Hard [refresh ](https://fabricdigital.co.nz/blog/how-to-hard-refresh-your-browser-and-clear-cache)your browser cache.
