### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by andreaconfa** [custom-components/alexa_media_player#994]
since some day i can't login to my account. home assistant ask me to accept the 2FA notification but, after accepting it, if i click "GO" nothing happens.

![image](https://user-images.githubusercontent.com/44619437/97095733-7aa2e000-1663-11eb-98ec-08b2f1a43771.png)

**Comment by andreaconfa** [comment]
solved

**Comment by lardissone** [comment]
@andreaconfa how did you solve it? I got stuck in that page too, approved from my SMS link but nothing happens.
