### ISSUE TITLE
Question: How to stop or pause alexa playback ?

### ISSUE THREAD

**Issue by cburkins** [custom-components/alexa_media_player#997]
I feel like I'm missing something, but here goes: Happily using the Alexa Media Player in HA via HACS.    Can't find reference to the command/JSON to pause and/or stop media playback ?

**Comment by alandtse** [comment]
It's the standard HA command for media players.
`media_player.media_play_pause`.

Review HA documentation or dev tools for how to use that.

**Comment by cburkins** [comment]
Ahh!  Yes !   Apologies, I guess my inexperience is showing through here.   I didn't understand the overlap between the Alexa media functions and the core Home Assistant media player functions.   For anyone else who stumbles into this, here's a reference to the [Home Assistant media player commands](https://www.home-assistant.io/integrations/media_player/)
