### ISSUE TITLE
Keep getting prompted with forgot password prompt

### ISSUE THREAD

**Issue by mkanet** [custom-components/alexa_media_player#999]
**Describe the bug**
I'm currently using 2FA to authenticate.  I don't have ANY authentication issues when logging into my Amazon account on any of my web browsers and mobile Amazon apps.  However...

I keep getting prompted with the **_Aborted The Forgot Password page was detected. This normally is the result of too may failed logins. Amazon may require action before a relogin can be attempted_** error message  on my Alexa Media Player Integration when I enter a valid/updated 2FA code. 

**Expected behavior**
Alexa Media Player Integration should allow me to authenticate successfully after entering the correct password + updated 2FA code.

**Screenshots**

**System details**
 - Home-assistant (version): 0.116.4
 - Hassio (Yes/No): Yes
 - alexa_media  (version from `const.py` or HA startup):  v3.2.2
 - alexapy (version from `pip show alexapy` or HA startup):
 - Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). y

**Logs**
No logger errors

**Additional context**
I had to go through this once before recently... resolving the issue by changing my Amazon password; and, re-authenticate with the new password + 2FA on over 15 Amazon devices/web browsers/apps.  I definitely don't want to go through that again unless I know for sure this wont happen again; since this would effect all my family members each time this happens.  It seems like this issue is affected several other users too:

https://community.home-assistant.io/t/echo-devices-alexa-as-media-player-testers-needed/58639/4375

**Comment by alandtse** [comment]
Enable logs per the template and we can review if your'e getting a new page and whether your information is correct. However, if it's not a new page, then you're getting Amazon's response and there may not be anything to be done. Please note that the 2FA will change every 30 seconds so if you're not changing that correctly you will get what you're describing.

**Comment by mkanet** [comment]
@alandtse , yes I change 2FA each time I try just like all my other 2FA capable apps.  Please find the attached advanced Debug log while authenticating with 2FA.

It's important to note that I don't have any authentications issues with any of my Amazon apps, web browsers, or devices currently

**Advanced Debug Log:** 
[home-assistant.log](https://github.com/custom-components/alexa_media_player/files/5507543/home-assistant.log)

**Comment by alandtse** [comment]
Do you have an old password in the configuration.yaml? Are you setting up the component via configuration.yaml or from the integrations page? Anything in the configuration.yaml will be imported on startup and there will be a login attempt. The logs show you try logging in with an 8 character password at first and then you switch to a 14 character password. I'm guessing, Amazon will likely treat this as fraudulent if the first password is the old password.

You can remove the configuration.yaml entry or properly update it to the latest password.

**Comment by mkanet** [comment]
Thank you.  You're partially right, I do have my password set in my configuration file.  However, at the time I got locked out, my configuration file still had the correct 8 character password (and, the Integration's GUI displayed the same 8 character password).

I'm not sure what caused the integration to get locked out in the first place if the passwords were correct in the configuration as well as the Integration GUI.  I'm guessing it has to do with the mysterious 14 character password?  My 2FA codes are only 6 characters in length.

This is what my configuration had at the time of the lockout:

**Configuration.yaml**
alexa_media:
  accounts:
    - email: !secret amazon_username
      password: !secret amazon_password
      url: amazon.com
      # debug: True

**secrets.yaml**
amazon_username: myemailaddress@mail.com
amazon_password: xxxxxxxx

I can still comment out this stuff in configuration.yaml ; however, I have a feeling this may happen again.  

Whenever this issue happens, it's usually when I'm upgrading Home Assistant and/or the Media Player Addon via HACS.

BTW:  I just changed my Amazon password.. and, got the integration working again.  However, I would really feel better if we knew why this happened; and, a way to prevent it from happening.  It's not just me that this issue happens to.

**Comment by alandtse** [comment]
I have no idea why Amazon decides to randomly lock accounts. Perhaps its tied to the number of different devices you said you had logging into Amazon outside of the component.  However, that's a guess. Updating the component or HA shouldn't cause any of this.

14 chars password is password + 2fa so it's probably fine.
